FreeNOS: bin/mpiprime/Main.cpp File Reference
Main.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <mpi.h>
#include <unistd.h>
#include <String.h>
#include <sys/time.h>
Macros
#define PERNODE(id, nids, base, n) (((n) - (base)) / (nids))
#define START(id, nids, base, n) ((base) + ((id) * PERNODE(id, nids, base, n)))
#define END(id, nids, base, n) (START(id, nids, base, n) + PERNODE(id, nids, base, n))
Functions
void collect (int n, unsigned *map)
void search_sequential (int k, int n, unsigned *map, int argc, char **argv)
void search_parallel (int k, int n, unsigned *map, int argc, char **argv)
int main (int argc, char **argv)
Program entry point.
Variables
static int rank
static int total
static int length
static char name [64]
Macro Definition Documentation
END
#define END (id, nids, base, n) (START(id, nids, base, n) + PERNODE(id, nids, base, n))
Definition at line 30 of file Main.cpp.
Referenced by collect(), and search_parallel().
PERNODE
#define PERNODE (id, nids, base, n) (((n) - (base)) / (nids))
Definition at line 28 of file Main.cpp.
Referenced by collect().
START
#define START (id, nids, base, n) ((base) + ((id) * PERNODE(id, nids, base, n)))
Definition at line 29 of file Main.cpp.
Referenced by collect(), and search_parallel().
Function Documentation
collect()
void collect (int n, unsigned * map)
Definition at line 35 of file Main.cpp.
References END, free(), malloc(), MPI_COMM_WORLD, MPI_INT, MPI_Recv(), MPI_Send(), PERNODE, rank, sqrt(), START, and total.
Referenced by search_parallel().
search_parallel()
void search_parallel (int k, int n, unsigned * map, int argc, char ** argv)
Definition at line 87 of file Main.cpp.
References collect(), END, gettimeofday(), printf(), printtimediff(), rank, search_sequential(), sqrt(), START, and total.
Referenced by main().
search_sequential()
void search_sequential (int k, int n, unsigned * map, int argc, char ** argv)
Definition at line 66 of file Main.cpp.
Referenced by search_parallel().
Variable Documentation
length
int length static
Definition at line 32 of file Main.cpp.
Referenced by main().
name
char name[64] static
Definition at line 33 of file Main.cpp.
Referenced by BootImageStorage::BootImageStorage(), Cat::cat(), BootImageCreate::exec(), Directory::get(), main(), Directory::remove(), Argument::setName(), and ShellCommand::ShellCommand().
rank
int rank static
Definition at line 32 of file Main.cpp.
Referenced by collect(), main(), and search_parallel().
total
int total static
Definition at line 32 of file Main.cpp.
Referenced by collect(), Shell::getInput(), Login::getUsername(), main(), LinnFile::read(), search_parallel(), and VMCopyHandler().