FreeNOS: Ethernet Class Reference
Ethernet Class Reference
lib » libnet
Ethernet networking protocol.
#include <Ethernet.h>
Data Structures
struct Address
Ethernet network address.
struct Header
Ethernet network packet header.
Public Types
enum PayloadType { IPV4 = 0x0800u, IPV6 = 0x86ddu, ARP = 0x0806u }
List of ethernet payload types.
typedef struct Ethernet::Address Address
Ethernet network address.
typedef struct Ethernet::Header Header
Ethernet network packet header.
Public Member Functions
Ethernet (NetworkServer *server, NetworkDevice *device)
Constructor.
virtual ~Ethernet ()
Destructor.
virtual Error initialize ()
Perform initialization.
virtual Error getAddress (Address *address)
Retrieve Ethernet address.
virtual Error setAddress (Address *address)
Set Ethernet address.
NetworkQueue::Packet * getTransmitPacket (const Address *destination, PayloadType type)
Get a new packet for transmission.
void setARP (::ARP *arp)
Set ARP instance.
void setIP (::IPV4 *ip)
Set IPV4 instance.
virtual Error process (NetworkQueue::Packet *pkt, Size offset)
Process incoming network packet.
Public Member Functions inherited from NetworkProtocol
NetworkProtocol (NetworkServer *server, NetworkDevice *device)
Constructor.
virtual ~NetworkProtocol ()
Destructor.
virtual const Size getMaximumPacketSize () const
Get maximum packet size.
Public Member Functions inherited from Directory
Directory ()
Constructor.
virtual ~Directory ()
Destructor.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read directory entries.
virtual File * lookup (const char *name)
Retrieve a File from storage.
void insert (FileType type, const char *name,...)
Insert a new directory entry.
void remove (const char *name)
Remove a directory entry.
void clear ()
Clears the internal list of entries.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Static Public Member Functions
static const String toString (Address address)
Convert address to string.
Static Public Attributes
static const Size CRCSize = 4
Size of the CRC checksum (which is set after the payload)
Private Attributes
Address m_address
Current ethernet address.
::ARP * m_arp
ARP protocol.
::IPV4 * m_ipv4
IPV4 protocol.
Additional Inherited Members
Protected Attributes inherited from NetworkProtocol
NetworkServer * m_server
Network server instance.
NetworkDevice * m_device
Network device instance.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
Ethernet networking protocol.
Definition at line 40 of file Ethernet.h.
Member Typedef Documentation
Address
typedef struct Ethernet::Address Ethernet::Address
Ethernet network address.
Header
typedef struct Ethernet::Header Ethernet::Header
Ethernet network packet header.
This header is prepended to every ethernet packet send on the actual physical link.
Member Enumeration Documentation
PayloadType
enum Ethernet::PayloadType
List of ethernet payload types.
Enumerator
IPV4
Internet protocol v4.
IPV6
Internet protocol v6.
ARP
Address resolution protocol.
Definition at line 73 of file Ethernet.h.
Constructor & Destructor Documentation
Ethernet()
Ethernet::Ethernet (NetworkServer * server, NetworkDevice * device)
Constructor.
Definition at line 24 of file Ethernet.cpp.
References NetworkDevice::getAddress(), m_address, m_arp, m_ipv4, and ZERO.
~Ethernet()
Ethernet::~Ethernet () virtual
Destructor.
Definition at line 32 of file Ethernet.cpp.
Member Function Documentation
getAddress()
Error Ethernet::getAddress (Ethernet::Address * address) virtual
Retrieve Ethernet address.
Parameters
address Output buffer to store the address
Returns
Error code
Definition at line 43 of file Ethernet.cpp.
References MemoryBlock::copy(), ESUCCESS, and m_address.
Referenced by EthernetAddress::read().
getTransmitPacket()
NetworkQueue::Packet * Ethernet::getTransmitPacket (const Address * destination, Ethernet::PayloadType type)
Get a new packet for transmission.
Parameters
destination
Definition at line 84 of file Ethernet.cpp.
References MemoryBlock::copy(), cpu_to_be16, NetworkQueue::Packet::data, Ethernet::Header::destination, NetworkQueue::get(), NetworkDevice::getTransmitQueue(), m_address, NetworkProtocol::m_device, NetworkQueue::Packet::size, Ethernet::Header::source, Ethernet::Header::type, and ZERO.
Referenced by IPV4::getTransmitPacket(), ARP::sendReply(), and ARP::sendRequest().
initialize()
Error Ethernet::initialize () virtual
Perform initialization.
Implements NetworkProtocol.
Definition at line 36 of file Ethernet.cpp.
References ESUCCESS, NetworkProtocol::m_server, and FileSystem::registerFile().
Referenced by NetworkDevice::initialize().
process()
Error Ethernet::process (NetworkQueue::Packet * pkt, Size offset) virtual
Process incoming network packet.
Returns
Error code
Implements NetworkProtocol.
Definition at line 100 of file Ethernet.cpp.
References ARP, be16_to_cpu, NetworkQueue::Packet::data, DEBUG, EINVAL, IPV4, m_arp, m_ipv4, ARP::process(), IPV4::process(), and Ethernet::Header::type.
Referenced by NetworkDevice::process().
setAddress()
Error Ethernet::setAddress (Ethernet::Address * address) virtual
Set Ethernet address.
Parameters
address Input address
Returns
Error code
Definition at line 49 of file Ethernet.cpp.
References MemoryBlock::copy(), ESUCCESS, m_address, NetworkProtocol::m_device, and NetworkDevice::setAddress().
setARP()
void Ethernet::setARP (::ARP * arp)
Set ARP instance.
Parameters
arp ARP object instance
Definition at line 59 of file Ethernet.cpp.
References m_arp.
Referenced by NetworkDevice::initialize().
setIP()
void Ethernet::setIP (::IPV4 * ip)
Set IPV4 instance.
Parameters
ip IPV4 instance
Definition at line 64 of file Ethernet.cpp.
References m_ipv4.
Referenced by NetworkDevice::initialize().
toString()
const String Ethernet::toString (Ethernet::Address address) static
Convert address to string.
Parameters
address Input ethernet address
Returns
Text value of the ethernet address
Definition at line 69 of file Ethernet.cpp.
References Ethernet::Address::addr, and Number::Hex.
Referenced by EthernetAddress::read().
Field Documentation
CRCSize
const Size Ethernet::CRCSize = 4 static
Size of the CRC checksum (which is set after the payload)
Definition at line 45 of file Ethernet.h.
m_address
Address Ethernet::m_address private
Current ethernet address.
Definition at line 156 of file Ethernet.h.
Referenced by Ethernet(), getAddress(), getTransmitPacket(), and setAddress().
m_arp
::ARP* Ethernet::m_arp private
ARP protocol.
Definition at line 159 of file Ethernet.h.
Referenced by Ethernet(), process(), and setARP().
m_ipv4
::IPV4* Ethernet::m_ipv4 private
IPV4 protocol.
Definition at line 162 of file Ethernet.h.
Referenced by Ethernet(), process(), and setIP().
The documentation for this class was generated from the following files:
lib/libnet/Ethernet.h
lib/libnet/Ethernet.cpp