FreeNOS: Allocator Class Reference
Allocator Class Reference abstract
lib » liballoc
Memory Allocator.
#include <Allocator.h>
Public Types
enum Result {
Success = 0, InvalidAddress, InvalidSize, InvalidAlignment,
OutOfMemory
}
Allocation results.
Public Member Functions
Allocator ()
Class constructor.
virtual ~Allocator ()
Class destructor.
void setParent (Allocator *parent)
Set parent allocator.
Result setAlignment (Size size)
Set allocation alignment.
Result setBase (Address addr)
Set allocation base.
virtual Size size () const =0
Get memory size.
virtual Size available () const =0
Get memory available.
virtual Result allocate (Size *size, Address *addr, Size align=ZERO)=0
Allocate memory.
virtual Result release (Address addr)=0
Release memory.
Static Public Member Functions
static void setDefault (Allocator *alloc)
Makes the given Allocator the default.
static Allocator * getDefault ()
Retrieve the currently default Allocator.
Protected Member Functions
Address aligned (Address addr, Size boundary) const
Align memory address.
Protected Attributes
Allocator * m_parent
Our parent Allocator, if any.
Size m_alignment
Allocation memory alignment.
Address m_base
Allocation base address.
Static Private Attributes
static Allocator * m_default = ZERO
Points to the default Allocator for new()/delete().
Detailed Description
Memory Allocator.
This class defines an abstract memory allocator. Each class which derives must provide functions for memory allocation and release. The memory allocators form a hierarcy of parent-child. A parent allocator can provide memory to a child allocator. If a child allocator runs out of memory, it can ask the parent for more memory.
Definition at line 46 of file Allocator.h.
Member Enumeration Documentation
Result
enum Allocator::Result
Allocation results.
Enumerator
Success
InvalidAddress
InvalidSize
InvalidAlignment
OutOfMemory
Definition at line 53 of file Allocator.h.
Constructor & Destructor Documentation
Allocator()
Allocator::Allocator ()
Class constructor.
Definition at line 24 of file Allocator.cpp.
~Allocator()
Allocator::~Allocator () virtual
Class destructor.
Definition at line 31 of file Allocator.cpp.
Member Function Documentation
aligned()
Address Allocator::aligned (Address addr, Size boundary) const protected
Align memory address.
Any alignment corrections on the input address will result in an address which is higher than the input address.
Parameters
addr Input address which need to be aligned.
boundary Boundary size to align the address for.
Returns
Aligned Address.
Definition at line 68 of file Allocator.cpp.
Referenced by BubbleAllocator::allocate(), PageAllocator::allocate(), and PoolAllocator::newPool().
allocate()
virtual Result Allocator::allocate (Size * size, Address * addr, Size align = ZERO) pure virtual
Allocate memory.
Parameters
size Amount of memory in bytes to allocate on input. On output, the amount of memory in bytes actually allocated.
addr Output parameter which contains the address allocated on success.
align Alignment of the required memory or use ZERO for default.
Returns
Result value.
Implemented in PoolAllocator, BitAllocator, PageAllocator, SplitAllocator, and BubbleAllocator.
Referenced by PoolAllocator::newPool(), operator new(), and operator new[]().
available()
virtual Size Allocator::available () const pure virtual
Get memory available.
Returns
Size of memory available by the Allocator.
Implemented in PoolAllocator, BitAllocator, PageAllocator, SplitAllocator, and BubbleAllocator.
Referenced by PoolAllocator::available().
getDefault()
Allocator * Allocator::getDefault () static
Retrieve the currently default Allocator.
Returns
Allocator pointer.
Definition at line 40 of file Allocator.cpp.
References m_default.
Referenced by operator delete(), operator delete[](), operator new(), and operator new[]().
release()
virtual Result Allocator::release (Address addr) pure virtual
Release memory.
Parameters
addr Points to memory previously returned by allocate().
Returns
Result value.
See also
allocate
Implemented in PoolAllocator, BitAllocator, SplitAllocator, PageAllocator, and BubbleAllocator.
Referenced by operator delete(), operator delete[](), and ProcessShares::releaseShare().
setAlignment()
Allocator::Result Allocator::setAlignment (Size size)
Set allocation alignment.
Configure the Allocator such that each allocated address must be aligned to the given size.
Parameters
size Alignment size
Returns
Result code
Definition at line 50 of file Allocator.cpp.
References InvalidAlignment, m_alignment, MEMALIGN, size(), and Success.
setBase()
Allocator::Result Allocator::setBase (Address addr)
Set allocation base.
The allocation base will be added to each allocation.
Parameters
addr Allocation base address.
Returns
Result code
Definition at line 59 of file Allocator.cpp.
References InvalidAddress, m_base, PAGESIZE, and Success.
setDefault()
void Allocator::setDefault (Allocator * alloc) static
Makes the given Allocator the default.
Parameters
alloc Instance of an Allocator.
Definition at line 45 of file Allocator.cpp.
References m_default.
Referenced by Kernel::heap(), and setupHeap().
setParent()
void Allocator::setParent (Allocator * parent)
Set parent allocator.
Parameters
p New parent allocator.
Definition at line 35 of file Allocator.cpp.
References m_parent.
Referenced by Kernel::heap(), and setupHeap().
size()
virtual Size Allocator::size () const pure virtual
Get memory size.
Returns
Size of memory owned by the Allocator.
Implemented in PoolAllocator, BitAllocator, PageAllocator, SplitAllocator, and BubbleAllocator.
Referenced by setAlignment(), and PoolAllocator::size().
Field Documentation
m_alignment
Size Allocator::m_alignment protected
Allocation memory alignment.
Definition at line 175 of file Allocator.h.
Referenced by setAlignment().
m_base
Address Allocator::m_base protected
Allocation base address.
Definition at line 178 of file Allocator.h.
Referenced by setBase().
m_default
Allocator * Allocator::m_default = ZERO static private
Points to the default Allocator for new()/delete().
Definition at line 183 of file Allocator.h.
Referenced by getDefault(), and setDefault().
m_parent
Allocator* Allocator::m_parent protected
Our parent Allocator, if any.
Definition at line 172 of file Allocator.h.
Referenced by PoolAllocator::allocate(), PoolAllocator::available(), PoolAllocator::newPool(), setParent(), and PoolAllocator::size().
The documentation for this class was generated from the following files:
lib/liballoc/Allocator.h
lib/liballoc/Allocator.cpp