FreeNOS: Loopback Class Reference
Loopback Class Reference
server » loopback
Loopback network device implementation.
#include <Loopback.h>
Public Member Functions
Loopback (NetworkServer *server)
Constructor.
virtual ~Loopback ()
Destructor.
virtual Error initialize ()
Perform initialization.
virtual Error getAddress (Ethernet::Address *address)
Read ethernet address.
virtual Error setAddress (Ethernet::Address *address)
Set ethernet address.
virtual Error transmit (NetworkQueue::Packet *pkt)
Transmit one network packet.
Public Member Functions inherited from NetworkDevice
NetworkDevice (NetworkServer *server)
Constructor.
virtual ~NetworkDevice ()
Destructor.
const Size getMaximumPacketSize () const
Get maximum packet size.
NetworkQueue * getReceiveQueue ()
Get receive queue.
NetworkQueue * getTransmitQueue ()
Get transmit queue.
virtual Error process (NetworkQueue::Packet *packet, Size offset=0)
Process a received network packet.
Public Member Functions inherited from Device
Device (FileType type)
Constructor.
virtual ~Device ()
Destructor.
virtual const String & getIdentifier () const
Get unique device identifier.
virtual Error interrupt (Size vector)
Called when an interrupt has been triggered for this device.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read bytes from the file.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Attributes
Ethernet::Address m_address
Ethernet address for the loopback device.
Additional Inherited Members
Protected Attributes inherited from NetworkDevice
Size m_maximumPacketSize
Maximum size of each packet.
NetworkQueue m_receive
NetworkQueue m_transmit
NetworkServer * m_server
Ethernet * m_eth
ARP * m_arp
IPV4 * m_ipv4
ICMP * m_icmp
UDP * m_udp
Protected Attributes inherited from Device
String m_identifier
Unique identifier for this Device.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
Loopback network device implementation.
Definition at line 36 of file Loopback.h.
Constructor & Destructor Documentation
Loopback()
Loopback::Loopback (NetworkServer * server)
Constructor.
Definition at line 20 of file Loopback.cpp.
References Ethernet::Address::addr, DEBUG, and m_address.
~Loopback()
Loopback::~Loopback () virtual
Destructor.
Definition at line 32 of file Loopback.cpp.
References DEBUG.
Member Function Documentation
getAddress()
Error Loopback::getAddress (Ethernet::Address * address) virtual
Read ethernet address.
Parameters
address Ethernet address reference for output
Returns
Error code
Implements NetworkDevice.
Definition at line 43 of file Loopback.cpp.
References MemoryBlock::copy(), DEBUG, ESUCCESS, and m_address.
initialize()
Error Loopback::initialize () virtual
Perform initialization.
Reimplemented from NetworkDevice.
Definition at line 37 of file Loopback.cpp.
References DEBUG, and NetworkDevice::initialize().
setAddress()
Error Loopback::setAddress (Ethernet::Address * address) virtual
Set ethernet address.
Parameters
address New ethernet address to set
Returns
Error code
Implements NetworkDevice.
Definition at line 50 of file Loopback.cpp.
References MemoryBlock::copy(), DEBUG, ESUCCESS, and m_address.
transmit()
Error Loopback::transmit (NetworkQueue::Packet * pkt) virtual
Transmit one network packet.
Parameters
pkt Network packet buffer
Implements NetworkDevice.
Definition at line 57 of file Loopback.cpp.
References DEBUG, ERESTART, NetworkDevice::m_transmit, NetworkDevice::process(), NetworkQueue::release(), and NetworkQueue::Packet::size.
Field Documentation
m_address
Ethernet::Address Loopback::m_address private
Ethernet address for the loopback device.
Definition at line 83 of file Loopback.h.
Referenced by getAddress(), Loopback(), and setAddress().
The documentation for this class was generated from the following files:
server/network/loopback/Loopback.h
server/network/loopback/Loopback.cpp