FreeNOS: IntelMP Class Reference
IntelMP Class Reference
lib » libarch » Intel
Intel Multi-Processor Specification.
#include <IntelMP.h>
Data Structures
struct MPConfig
Multiprocessor Configuration Structure.
struct MPEntry
Multiprocessor Configuration Entry.
struct MPFloat
Multiprocessor Floating Structure.
Public Member Functions
IntelMP ()
Constructor.
virtual Result discover ()
Discover processors.
virtual Result boot (CoreInfo *info)
Boot a processor.
Public Member Functions inherited from CoreManager
CoreManager ()
Constructor.
List< uint > & getCores ()
Get list of core identities.
Private Types
typedef struct IntelMP::MPFloat MPFloat
Multiprocessor Floating Structure.
typedef struct IntelMP::MPConfig MPConfig
Multiprocessor Configuration Structure.
typedef struct IntelMP::MPEntry MPEntry
Multiprocessor Configuration Entry.
Private Member Functions
MPEntry * parseEntry (MPEntry *entry)
Parse Multiprocessor Config entry.
MPConfig * scanMemory (Address addr)
Scan memory for a Multiprocessor Config structure.
Private Attributes
IntelIO m_bios
I/O instance for BIOS memory.
IntelIO m_lastMemory
I/O instance for the last 1MB of physical memory.
IntelAPIC m_apic
APIC instance.
Static Private Attributes
static const uint MPFloatSignature = 0x5f504d5f
Multiprocessor Floating Structure Signature.
static const uint MPEntryProc = 0
Multiprocessor Configuration Type ID for processors.
static const Address MPEntryAddr = 0xf000
Physical memory address at which cores start (bootEntry16).
static const Address MPInfoAddr = MPINFOADDR
Physical memory address for the CoreInfo structure.
static const Address MPAreaAddr = 0x1000
BIOS memory area to search for MP tables.
static const Size MPAreaSize = 0x100000-0x1000
BIOS memory area size to search for MP tables.
Additional Inherited Members
Public Types inherited from CoreManager
enum Result { Success, IOError, NotFound }
Result codes.
Protected Attributes inherited from CoreManager
List< uint > m_cores
List of core ids found.
Detailed Description
Intel Multi-Processor Specification.
Definition at line 70 of file IntelMP.h.
Member Typedef Documentation
MPConfig
typedef struct IntelMP::MPConfig IntelMP::MPConfig private
Multiprocessor Configuration Structure.
MPEntry
typedef struct IntelMP::MPEntry IntelMP::MPEntry private
Multiprocessor Configuration Entry.
MPFloat
typedef struct IntelMP::MPFloat IntelMP::MPFloat private
Multiprocessor Floating Structure.
Constructor & Destructor Documentation
IntelMP()
IntelMP::IntelMP ()
Constructor.
Definition at line 24 of file IntelMP.cpp.
References IntelAPIC::getIO(), IntelAPIC::IOBase, m_apic, m_bios, m_lastMemory, IO::map(), MegaByte, SystemInformation::memorySize, MPAreaAddr, MPAreaSize, and PAGESIZE.
Member Function Documentation
boot()
IntelMP::Result IntelMP::boot (CoreInfo * info) virtual
Boot a processor.
Parameters
info CoreInfo object pointer.
Returns
Result code.
Implements CoreManager.
Definition at line 84 of file IntelMP.cpp.
References bootEntry16(), CoreInfo::coreId, DEBUG, CoreManager::IOError, CoreInfo::kernelCommand, m_apic, CoreInfo::memory, MPEntryAddr, MPInfoAddr, PAGESIZE, Memory::Range::phys, API::Read, SELF, IntelAPIC::sendStartupIPI(), IntController::Success, CoreManager::Success, VMCopy(), and API::Write.
discover()
IntelMP::Result IntelMP::discover () virtual
Discover processors.
Returns
Result code.
Implements CoreManager.
Definition at line 50 of file IntelMP.cpp.
References List< T >::clear(), DEBUG, ERROR, IO::getBase(), m_bios, CoreManager::m_cores, m_lastMemory, CoreManager::NotFound, parseEntry(), scanMemory(), and CoreManager::Success.
parseEntry()
IntelMP::MPEntry * IntelMP::parseEntry (IntelMP::MPEntry * entry) private
Parse Multiprocessor Config entry.
Returns
MPEntry object pointer of the next entry.
Definition at line 112 of file IntelMP.cpp.
References IntelMP::MPEntry::apicId, List< T >::append(), CoreManager::m_cores, MPEntryProc, and IntelMP::MPEntry::type.
Referenced by discover().
scanMemory()
IntelMP::MPConfig * IntelMP::scanMemory (Address addr) private
Scan memory for a Multiprocessor Config structure.
Returns
MPConfig object pointer on success or ZERO on failure.
Definition at line 35 of file IntelMP.cpp.
References IntelMP::MPFloat::configAddr, MPAreaAddr, MPAreaSize, MPFloatSignature, IntelMP::MPFloat::signature, and ZERO.
Referenced by discover().
Field Documentation
m_apic
IntelAPIC IntelMP::m_apic private
APIC instance.
Definition at line 189 of file IntelMP.h.
Referenced by boot(), and IntelMP().
m_bios
IntelIO IntelMP::m_bios private
I/O instance for BIOS memory.
Definition at line 183 of file IntelMP.h.
Referenced by discover(), and IntelMP().
m_lastMemory
IntelIO IntelMP::m_lastMemory private
I/O instance for the last 1MB of physical memory.
Definition at line 186 of file IntelMP.h.
Referenced by discover(), and IntelMP().
MPAreaAddr
const Address IntelMP::MPAreaAddr = 0x1000 static private
BIOS memory area to search for MP tables.
Definition at line 87 of file IntelMP.h.
Referenced by IntelMP(), and scanMemory().
MPAreaSize
const Size IntelMP::MPAreaSize = 0x100000-0x1000 static private
BIOS memory area size to search for MP tables.
Definition at line 90 of file IntelMP.h.
Referenced by IntelMP(), and scanMemory().
MPEntryAddr
const Address IntelMP::MPEntryAddr = 0xf000 static private
Physical memory address at which cores start (bootEntry16).
Definition at line 81 of file IntelMP.h.
Referenced by boot().
MPEntryProc
const uint IntelMP::MPEntryProc = 0 static private
Multiprocessor Configuration Type ID for processors.
Definition at line 78 of file IntelMP.h.
Referenced by parseEntry().
MPFloatSignature
const uint IntelMP::MPFloatSignature = 0x5f504d5f static private
Multiprocessor Floating Structure Signature.
Definition at line 75 of file IntelMP.h.
Referenced by scanMemory().
MPInfoAddr
const Address IntelMP::MPInfoAddr = MPINFOADDR static private
Physical memory address for the CoreInfo structure.
Definition at line 84 of file IntelMP.h.
Referenced by boot().
The documentation for this class was generated from the following files:
lib/libarch/intel/IntelMP.h
lib/libarch/intel/IntelMP.cpp