FreeNOS: SMSC95xx Class Reference
SMSC95xx Class Reference
server » smsc95xx
SMSC95xx USB-based Ethernet controller.
#include <SMSC95xx.h>
Public Member Functions
SMSC95xx (u8 deviceId, const char *usbPath, NetworkServer *server)
Constructor.
virtual ~SMSC95xx ()
Destructor.
virtual Error initialize ()
Initialize the controller.
virtual Error getAddress (Ethernet::Address *address)
Read ethernet address.
virtual Error setAddress (Ethernet::Address *address)
Set ethernet address.
virtual Error transmit (NetworkQueue::Packet *pkt)
Transmit one network packet.
Public Member Functions inherited from NetworkDevice
NetworkDevice (NetworkServer *server)
Constructor.
virtual ~NetworkDevice ()
Destructor.
const Size getMaximumPacketSize () const
Get maximum packet size.
NetworkQueue * getReceiveQueue ()
Get receive queue.
NetworkQueue * getTransmitQueue ()
Get transmit queue.
virtual Error process (NetworkQueue::Packet *packet, Size offset=0)
Process a received network packet.
Public Member Functions inherited from Device
Device (FileType type)
Constructor.
virtual ~Device ()
Destructor.
virtual const String & getIdentifier () const
Get unique device identifier.
virtual Error interrupt (Size vector)
Called when an interrupt has been triggered for this device.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read bytes from the file.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Attributes
SMSC95xxUSB * m_usb
USB enabled implementation class.
Additional Inherited Members
Protected Attributes inherited from NetworkDevice
Size m_maximumPacketSize
Maximum size of each packet.
NetworkQueue m_receive
NetworkQueue m_transmit
NetworkServer * m_server
Ethernet * m_eth
ARP * m_arp
IPV4 * m_ipv4
ICMP * m_icmp
UDP * m_udp
Protected Attributes inherited from Device
String m_identifier
Unique identifier for this Device.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
SMSC95xx USB-based Ethernet controller.
Definition at line 35 of file SMSC95xx.h.
Constructor & Destructor Documentation
SMSC95xx()
SMSC95xx::SMSC95xx (u8 deviceId, const char * usbPath, NetworkServer * server)
Constructor.
Definition at line 22 of file SMSC95xx.cpp.
References DEBUG, NetworkDevice::m_server, and m_usb.
~SMSC95xx()
SMSC95xx::~SMSC95xx () virtual
Destructor.
Definition at line 31 of file SMSC95xx.cpp.
References DEBUG, and m_usb.
Member Function Documentation
getAddress()
Error SMSC95xx::getAddress (Ethernet::Address * address) virtual
Read ethernet address.
Parameters
address Ethernet address reference for output
Returns
Error code
Implements NetworkDevice.
Definition at line 59 of file SMSC95xx.cpp.
References Ethernet::Address::addr, DEBUG, and ESUCCESS.
initialize()
Error SMSC95xx::initialize () virtual
Initialize the controller.
Returns
Result code
Reimplemented from NetworkDevice.
Definition at line 38 of file SMSC95xx.cpp.
References DEBUG, ERROR, ESUCCESS, NetworkDevice::initialize(), SMSC95xxUSB::initialize(), NetworkDevice::m_maximumPacketSize, m_usb, and SMSC95xxUSB::TransmitCommandSize.
setAddress()
Error SMSC95xx::setAddress (Ethernet::Address * address) virtual
Set ethernet address.
Parameters
address New ethernet address to set
Returns
Error code
Implements NetworkDevice.
Definition at line 72 of file SMSC95xx.cpp.
References DEBUG, and ESUCCESS.
transmit()
Error SMSC95xx::transmit (NetworkQueue::Packet * pkt) virtual
Transmit one network packet.
Parameters
pkt Network packet buffer
Implements NetworkDevice.
Definition at line 78 of file SMSC95xx.cpp.
References DEBUG, m_usb, and SMSC95xxUSB::transmit().
Field Documentation
m_usb
SMSC95xxUSB* SMSC95xx::m_usb private
USB enabled implementation class.
Definition at line 86 of file SMSC95xx.h.
Referenced by initialize(), SMSC95xx(), transmit(), and ~SMSC95xx().
The documentation for this class was generated from the following files:
server/network/smsc95xx/SMSC95xx.h
server/network/smsc95xx/SMSC95xx.cpp