FreeNOS: StdoutReporter Class Reference
StdoutReporter Class Reference
lib » libtest
Output TestResults to standard output.
#include <StdoutReporter.h>
Public Member Functions
StdoutReporter (int argc, char **argv)
Constructor.
virtual void reportBegin (List< TestInstance *> &tests)
Report start of testing.
virtual void reportBefore (TestInstance &test)
Report start of a test.
virtual void reportAfter (TestInstance &test, TestResult &result)
Report finish of a test.
virtual void reportFinish (List< TestInstance *> &tests)
Report completion of all tests.
Public Member Functions inherited from TestReporter
TestReporter (int argc, char **argv)
Constructor.
virtual ~TestReporter ()
Destructor.
uint getOk () const
Get OK count.
uint getFailed () const
Get fail count.
uint getSkipped () const
Get skip count.
void setReport (bool value)
Set reporting on/off.
void setStatistics (bool value)
Set show statistics on/off.
virtual void prepare (TestInstance &test)
Prepare for next test.
virtual void collect (TestInstance &test, TestResult &result)
Collect test statistics.
virtual void begin (List< TestInstance *> &tests)
Begin testing.
virtual void finish (List< TestInstance *> &tests)
Finish testing.
Additional Inherited Members
Protected Attributes inherited from TestReporter
int m_argc
Argument count.
char ** m_argv
Argument values.
bool m_report
Report on/off.
bool m_showStatistics
Show final statistics.
uint m_ok
Test statistics.
uint m_fail
uint m_skip
Detailed Description
Output TestResults to standard output.
Definition at line 34 of file StdoutReporter.h.
Constructor & Destructor Documentation
StdoutReporter()
StdoutReporter::StdoutReporter (int argc, char ** argv)
Constructor.
Definition at line 27 of file StdoutReporter.cpp.
Member Function Documentation
reportAfter()
void StdoutReporter::reportAfter (TestInstance & test, TestResult & result) virtual
Report finish of a test.
Implements TestReporter.
Definition at line 41 of file StdoutReporter.cpp.
References TestResult::Failure, TestResult::getDescription(), TestResult::getResult(), GREEN, printf(), RED, TestResult::Skipped, TestResult::Success, WHITE, and YELLOW.
reportBefore()
void StdoutReporter::reportBefore (TestInstance & test) virtual
Report start of a test.
Implements TestReporter.
Definition at line 36 of file StdoutReporter.cpp.
References basename(), TestReporter::m_argv, TestInstance::m_name, printf(), and WHITE.
reportBegin()
void StdoutReporter::reportBegin (List< TestInstance *> & tests) virtual
Report start of testing.
Implements TestReporter.
Definition at line 32 of file StdoutReporter.cpp.
reportFinish()
void StdoutReporter::reportFinish (List< TestInstance *> & tests) virtual
Report completion of all tests.
Implements TestReporter.
Definition at line 52 of file StdoutReporter.cpp.
References basename(), GREEN, TestReporter::m_argv, TestReporter::m_fail, TestReporter::m_ok, TestReporter::m_skip, printf(), RED, and WHITE.
The documentation for this class was generated from the following files:
lib/libtest/StdoutReporter.h
lib/libtest/StdoutReporter.cpp