FreeNOS: ARPSocket Class Reference
ARPSocket Class Reference
lib » libnet
Address Resolution Protocol (ARP) socket.
#include <ARPSocket.h>
Public Member Functions
ARPSocket (ARP *arp)
Constructor.
virtual ~ARPSocket ()
Destructor.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Receive ARP response.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Send ARP request.
virtual Error process (NetworkQueue::Packet *pkt)
Process incoming network packet.
virtual void error (Error err)
Set error status.
Public Member Functions inherited from NetworkSocket
NetworkSocket (Size packetSize)
Constructor.
virtual ~NetworkSocket ()
Destructor.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Attributes
ARP * m_arp
ARP protocol instance.
IPV4::Address m_ipAddr
IPV4 address for request.
Ethernet::Address m_ethAddr
Ethernet address for reply.
Additional Inherited Members
Protected Attributes inherited from NetworkSocket
ProcessID m_pid
Process which owns the socket.
NetworkQueue m_receive
Receive queue.
NetworkQueue m_transmit
Transmit queue.
NetworkClient::SocketInfo m_info
Socket connection.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
Address Resolution Protocol (ARP) socket.
ARP sockets receive a copy of ARP reply packets.
Definition at line 40 of file ARPSocket.h.
Constructor & Destructor Documentation
ARPSocket()
ARPSocket::ARPSocket (ARP * arp)
Constructor.
Definition at line 24 of file ARPSocket.cpp.
References m_arp, m_ethAddr, m_ipAddr, and MemoryBlock::set().
~ARPSocket()
ARPSocket::~ARPSocket () virtual
Destructor.
Definition at line 32 of file ARPSocket.cpp.
Member Function Documentation
error()
void ARPSocket::error (Error err) virtual
Set error status.
Parameters
err Error code
Definition at line 76 of file ARPSocket.cpp.
References DEBUG.
process()
Error ARPSocket::process (NetworkQueue::Packet * pkt) virtual
Process incoming network packet.
Returns
Error code
Implements NetworkSocket.
Definition at line 70 of file ARPSocket.cpp.
References DEBUG, and ESUCCESS.
Referenced by ARP::process().
read()
Error ARPSocket::read (IOBuffer & buffer, Size size, Size offset) virtual
Receive ARP response.
Parameters
buffer Input/Output buffer to output bytes to.
size Number of bytes to read, at maximum.
offset Offset inside the file to start reading.
Returns
Number of bytes read on success, Error on failure.
Reimplemented from File.
Definition at line 36 of file ARPSocket.cpp.
References DEBUG, ERANGE, ESUCCESS, ARP::lookupAddress(), m_arp, m_ethAddr, m_ipAddr, and IOBuffer::write().
write()
Error ARPSocket::write (IOBuffer & buffer, Size size, Size offset) virtual
Send ARP request.
Parameters
buffer Input/Output buffer to input bytes from.
size Number of bytes to write, at maximum.
offset Offset inside the file to start writing.
Returns
Number of bytes written on success, Error on failure.
Reimplemented from File.
Definition at line 54 of file ARPSocket.cpp.
References DEBUG, ESUCCESS, ARP::lookupAddress(), m_arp, m_ethAddr, m_ipAddr, and IOBuffer::read().
Field Documentation
m_arp
ARP* ARPSocket::m_arp private
ARP protocol instance.
Definition at line 93 of file ARPSocket.h.
Referenced by ARPSocket(), read(), and write().
m_ethAddr
Ethernet::Address ARPSocket::m_ethAddr private
Ethernet address for reply.
Definition at line 99 of file ARPSocket.h.
Referenced by ARPSocket(), read(), and write().
m_ipAddr
IPV4::Address ARPSocket::m_ipAddr private
IPV4 address for request.
Definition at line 96 of file ARPSocket.h.
Referenced by ARPSocket(), read(), and write().
The documentation for this class was generated from the following files:
lib/libnet/ARPSocket.h
lib/libnet/ARPSocket.cpp