FreeNOS: MakeNode Class Reference
MakeNode Class Reference
bin
Create new device file node.
#include <MakeNode.h>
Public Member Functions
MakeNode (int argc, char **argv)
Constructor.
virtual ~MakeNode ()
Destructor.
virtual Result exec ()
Execute the application.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
Create new device file node.
Definition at line 31 of file MakeNode.h.
Constructor & Destructor Documentation
MakeNode()
MakeNode::MakeNode (int argc, char ** argv)
Constructor.
Parameters
argc Argument count
argv Argument values
Definition at line 26 of file MakeNode.cpp.
References Application::parser(), ArgumentParser::registerPositional(), and ArgumentParser::setDescription().
~MakeNode()
MakeNode::~MakeNode () virtual
Destructor.
Definition at line 36 of file MakeNode.cpp.
Member Function Documentation
exec()
MakeNode::Result MakeNode::exec () virtual
Execute the application.
Returns
Result code
Implements Application.
Definition at line 40 of file MakeNode.cpp.
References Application::arguments(), atoi(), errno, ERROR, Application::IOError, DeviceID::major, DeviceID::minor, mknod(), refreshMounts(), S_IFCHR, strerror(), and Application::Success.
The documentation for this class was generated from the following files:
bin/mknod/MakeNode.h
bin/mknod/MakeNode.cpp