FreeNOS: ListFiles Class Reference
ListFiles Class Reference
bin
List files on the filesystem.
#include <ListFiles.h>
Public Member Functions
ListFiles (int argc, char **argv)
Constructor.
virtual ~ListFiles ()
Destructor.
virtual Result exec ()
Execute the application.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Private Member Functions
Result printFiles (const String &path) const
List files on the filesystem.
Result printSingleFile (const String &path, String &out) const
List single file on the filesystem.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
List files on the filesystem.
Definition at line 31 of file ListFiles.h.
Constructor & Destructor Documentation
ListFiles()
ListFiles::ListFiles (int argc, char ** argv)
Constructor.
Parameters
argc Argument count
argv Argument values
Definition at line 31 of file ListFiles.cpp.
References Application::parser(), ArgumentParser::registerFlag(), ArgumentParser::registerPositional(), and ArgumentParser::setDescription().
~ListFiles()
ListFiles::~ListFiles () virtual
Destructor.
Definition at line 40 of file ListFiles.cpp.
Member Function Documentation
exec()
ListFiles::Result ListFiles::exec () virtual
Execute the application.
Returns
Result code
Implements Application.
Definition at line 44 of file ListFiles.cpp.
References Application::arguments(), Vector< T >::count(), getcwd(), ArgumentContainer::getPositionals(), PATH_MAX, printFiles(), refreshMounts(), and Application::Success.
printFiles()
ListFiles::Result ListFiles::printFiles (const String & path) const private
List files on the filesystem.
Parameters
path Path to the file(s) to list
Returns
Result code
Definition at line 79 of file ListFiles.cpp.
References Application::arguments(), closedir(), dirent::d_name, errno, ERROR, Application::IOError, String::length(), opendir(), PATH_MAX, printSingleFile(), readdir(), S_ISDIR, snprintf(), stat::st_mode, stat(), strerror(), Application::Success, and write().
Referenced by exec().
printSingleFile()
ListFiles::Result ListFiles::printSingleFile (const String & path, String & out) const private
List single file on the filesystem.
Parameters
path Path to the file to list
out String to write the output to
Returns
Result code
Definition at line 135 of file ListFiles.cpp.
References Application::arguments(), basename(), BLUE, errno, ERROR, GREEN, Application::IOError, String::pad(), S_IRGRP, S_IROTH, S_IRUSR, S_ISBLK, S_ISCHR, S_ISDIR, S_IWGRP, S_IWOTH, S_IWUSR, S_IXGRP, S_IXOTH, S_IXUSR, stat::st_gid, stat::st_mode, stat::st_size, stat::st_uid, stat(), strerror(), Application::Success, WHITE, and YELLOW.
Referenced by printFiles().
The documentation for this class was generated from the following files:
bin/ls/ListFiles.h
bin/ls/ListFiles.cpp