FreeNOS: RaspiSerial Class Reference
RaspiSerial Class Reference
kernel » ARM
BCM2835 specific UART logging implementation for the ARMKernel.
#include <RaspiSerial.h>
Public Member Functions
RaspiSerial ()
Constructor.
void init (void)
Initialize UART0.
u8 get (void)
Receive a byte via UART0.
void put (u8 byte)
Transmit a byte via UART0.
Public Member Functions inherited from Log
Log ()
Constructor.
virtual ~Log ()
Destructor.
Level getMinimumLogLevel ()
Get the minimum logging level.
void setMinimumLogLevel (Level level)
Set the minimum logging level.
void append (const char *str)
Append to buffered output.
void setIdent (const char *ident)
Set log identity.
const char * getIdent () const
Retrieve log identify.
Public Member Functions inherited from Singleton< Log >
Singleton (Log *obj)
Constructor.
Protected Member Functions
virtual void write (const char *str)
Write to the actual output device.
Private Types
enum {
GPIO_BASE = 0x200000, GPPUD = (GPIO_BASE + 0x94), GPPUDCLK0 = (GPIO_BASE + 0x98), PL011_BASE = (GPIO_BASE + 0x1000),
PL011_DR = (PL011_BASE + 0x00), PL011_RSRECR = (PL011_BASE + 0x04), PL011_FR = (PL011_BASE + 0x18), PL011_FR_RXFE = (1 << 4),
PL011_FR_TXFE = (1 << 7), PL011_ILPR = (PL011_BASE + 0x20), PL011_IBRD = (PL011_BASE + 0x24), PL011_FBRD = (PL011_BASE + 0x28),
PL011_LCRH = (PL011_BASE + 0x2C), PL011_LCRH_WLEN_8BIT = (0b11<<5), PL011_CR = (PL011_BASE + 0x30), PL011_IFLS = (PL011_BASE + 0x34),
PL011_IMSC = (PL011_BASE + 0x38), PL011_IMSC_RXIM = (1 << 4), PL011_IMSC_TXIM = (1 << 5), PL011_RIS = (PL011_BASE + 0x3C),
PL011_MIS = (PL011_BASE + 0x40), PL011_MIS_RXMIS = (1 << 4), PL011_MIS_TXMIS = (1 << 5), PL011_ICR = (PL011_BASE + 0x44),
PL011_ICR_TXIC = (1 << 5), PL011_ICR_RXIC = (1 << 4), PL011_DMACR = (PL011_BASE + 0x48), PL011_ITCR = (PL011_BASE + 0x80),
PL011_ITIP = (PL011_BASE + 0x84), PL011_ITOP = (PL011_BASE + 0x88), PL011_TDR = (PL011_BASE + 0x8C)
}
Private Member Functions
void delay (s32 count)
delay function
Private Attributes
ARMIO m_io
I/O instance.
Additional Inherited Members
Public Types inherited from Log
enum Level {
Emergency, Alert, Critical, Error,
Warning, Notice, Info, Debug
}
Logging level values.
Static Public Attributes inherited from Singleton< Log >
static Log * instance
One and only instance.
Detailed Description
BCM2835 specific UART logging implementation for the ARMKernel.
Definition at line 36 of file RaspiSerial.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
GPIO_BASE
GPPUD
GPPUDCLK0
PL011_BASE
PL011_DR
PL011_RSRECR
PL011_FR
PL011_FR_RXFE
PL011_FR_TXFE
PL011_ILPR
PL011_IBRD
PL011_FBRD
PL011_LCRH
PL011_LCRH_WLEN_8BIT
PL011_CR
PL011_IFLS
PL011_IMSC
PL011_IMSC_RXIM
PL011_IMSC_TXIM
PL011_RIS
PL011_MIS
PL011_MIS_RXMIS
PL011_MIS_TXMIS
PL011_ICR
PL011_ICR_TXIC
PL011_ICR_RXIC
PL011_DMACR
PL011_ITCR
PL011_ITIP
PL011_ITOP
PL011_TDR
Definition at line 75 of file RaspiSerial.h.
Constructor & Destructor Documentation
RaspiSerial()
RaspiSerial::RaspiSerial ()
Constructor.
Definition at line 23 of file RaspiSerial.cpp.
References init().
Member Function Documentation
delay()
void RaspiSerial::delay (s32 count) private
delay function
This just loops <delay> times in a way that the compiler wont optimize away.
Parameters
count number of cycles to delay
Definition at line 95 of file RaspiSerial.cpp.
Referenced by init().
get()
u8 RaspiSerial::get (void)
Receive a byte via UART0.
Returns
byte received.
Definition at line 74 of file RaspiSerial.cpp.
References m_io, PL011_DR, PL011_FR, and ARMIO::read().
init()
void RaspiSerial::init (void)
Initialize UART0.
Definition at line 28 of file RaspiSerial.cpp.
References delay(), GPPUD, GPPUDCLK0, m_io, PL011_CR, PL011_FBRD, PL011_IBRD, PL011_ICR, PL011_IMSC, PL011_LCRH, PL011_LCRH_WLEN_8BIT, and ARMIO::write().
Referenced by RaspiSerial().
put()
void RaspiSerial::put (u8 byte)
Transmit a byte via UART0.
Parameters
byte byte to send.
Definition at line 64 of file RaspiSerial.cpp.
References m_io, PL011_DR, PL011_FR, ARMIO::read(), and ARMIO::write().
Referenced by write().
write()
void RaspiSerial::write (const char * str) protected virtual
Write to the actual output device.
Implements Log.
Definition at line 87 of file RaspiSerial.cpp.
References put().
Field Documentation
m_io
ARMIO RaspiSerial::m_io private
I/O instance.
Definition at line 139 of file RaspiSerial.h.
Referenced by get(), init(), and put().
The documentation for this class was generated from the following files:
kernel/arm/raspberry/RaspiSerial.h
kernel/arm/raspberry/RaspiSerial.cpp