FreeNOS: SynopsisController Class Reference
SynopsisController Class Reference
server » usb » controller
Synopsis DesignWare USB Host Controller implementation.
#include <SynopsisController.h>
Public Member Functions
SynopsisController (const char *path)
Constructor.
virtual Error initialize ()
Initialize the Controller.
virtual Error transfer (const FileSystemMessage *msg, USBMessage *usb)
Submit USB transfer.
Public Member Functions inherited from USBController
USBController (const char *path)
Constructor.
Public Member Functions inherited from DeviceServer
DeviceServer (const char *path)
Constructor.
virtual ~DeviceServer ()
Destructor.
void registerDevice (Device *dev, const char *path,...)
Add a Device.
void registerInterrupt (Device *dev, Size vector)
Register an interrupt vector for the given device.
Public Member Functions inherited from FileSystem
FileSystem (const char *path)
Constructor function.
virtual ~FileSystem ()
Destructor function.
const char * getMountPath () const
Get mount path.
Directory * getRoot ()
Get root directory.
Error mount ()
Mount the FileSystem.
Error registerFile (File *file, const char *path,...)
Register a new File.
Error registerFile (File *file, const char *path, va_list args)
Register a new File with variable arguments.
virtual File * createFile (FileType type, DeviceID deviceID)
Create a new file.
FileCache * insertFileCache (File *file, const char *pathFormat,...)
Inserts a file into the in-memory filesystem tree.
FileCache * insertFileCache (File *file, const char *pathFormat, va_list args)
Inserts a file into the in-memory filesystem tree.
void pathHandler (FileSystemMessage *msg)
Process an incoming filesystem request using a path.
virtual void timeout ()
Called when a sleep timeout is expired.
virtual bool retryRequests ()
Retry any pending requests.
Public Member Functions inherited from ChannelServer< FileSystem, FileSystemMessage >
ChannelServer (FileSystem *inst, Size num=32)
Constructor function.
virtual ~ChannelServer ()
Destructor function.
int run ()
Enters an infinite loop, serving incoming requests.
void addIPCHandler (Size slot, IPCHandlerFunction h, bool sendReply=true)
Register a new IPC message action handler.
void addIRQHandler (Size slot, IRQHandlerFunction h)
Register a new IRQ message vector handler.
void setTimeout (uint msec)
Set a sleep timeout.
Private Types
enum Registers {
OTGControl = 0x000, OTGInterrupt = 0x004, AHBConfig = 0x008, CoreConfig = 0x00c,
CoreReset = 0x010, CoreInterrupt = 0x014, CoreIntMask = 0x018, ReceiveStatus = 0x01c,
ReceiveStatusPop = 0x020, RxFIFOSize = 0x024, TxFIFOSize = 0x028, TxFIFOStatus = 0x02c,
I2CControl = 0x030, PhyVendorControl = 0x034, GPIO = 0x038, UserId = 0x03c,
VendorId = 0x040, HardwareConfig1 = 0x044, HardwareConfig2 = 0x048, HardwareConfig3 = 0x04c,
HardwareConfig4 = 0x050, CoreLPMConfig = 0x054, GlobalPowerDn = 0x058, GlobalFIFOConfig = 0x05c,
ADPControl = 0x060, PeriodTxFIFOSize = 0x100, HostConfig = 0x400, HostFrameInterval = 0x404,
HostFrameNumber = 0x408, HostFIFOStatus = 0x410, HostChannelInt = 0x414, HostChannelMask = 0x418,
HostFrameList = 0x41c, HostPortControl = 0x440, HostChannel = 0x500, Power = 0xe00
}
Hardware registers.
enum AHBConfigFlags { InterruptEnable = (1 << 0), AXIWait = (1 << 4), DMAEnable = (1 << 5) }
AHBConfig register flags.
enum CoreIntFlags { CoreIntPort = (1 << 24), CoreIntChannel = (1 << 25) }
CoreInterrupt register flags.
enum HostPortControlFlags {
HostPortConnect = (1 << 0), HostPortConnectChanged = (1 << 1), HostPortEnable = (1 << 2), HostPortEnableChanged = (1 << 3),
HostPortCurrent = (1 << 4), HostPortCurrentChanged = (1 << 5), HostPortReset = (1 << 8), HostPortPower = (1 << 12),
HostPortSpeed = (1 << 17) | (1 << 18)
}
HostPortControl register flags.
enum PacketId { Data0 = 0, Data1 = 2, Data2 = 1, SetupId = 3 }
Packet ID constants.
Private Member Functions
SynopsisChannel * getChannel (const FileSystemMessage *msg, USBMessage *usb)
Get a Channel.
virtual void interruptHandler (Size vector)
Interrupt request handler.
void hostPortChanged ()
Called when the Host Port status changes.
void softReset ()
Reset the Controller.
Private Attributes
BroadcomPower m_power
Power Management.
Index< SynopsisChannel > m_channels
Channels.
Static Private Attributes
static const Address Base = 0x980000
Register base (offset from I/O base) for the USB controller.
static const uint DefaultVendorId = 0x4f54280a
Vendor Identity number for this device.
static const uint InterruptNumber = 9
Interrupt number for the USB controller in BCM2835.
static const Size ChannelCount = 8
Number of transfer channels supported by hardware.
Additional Inherited Members
Public Types inherited from ChannelServer< FileSystem, FileSystemMessage >
enum Result
Result codes.
Protected Types inherited from ChannelServer< FileSystem, FileSystemMessage >
typedef void(FileSystem ::* IPCHandlerFunction) (FileSystemMessage *)
Member function pointer inside Base, to handle IPC messages.
typedef void(FileSystem ::* IRQHandlerFunction) (Size)
Member function pointer inside Base, to handle interrupts.
Protected Member Functions inherited from FileSystem
Error processRequest (FileSystemRequest *req)
Process a FileSystemRequest.
void sendResponse (FileSystemMessage *msg)
Send response for a FileSystemMessage.
void setRoot (Directory *newRoot)
Change the filesystem root directory.
FileCache * lookupFile (FileSystemPath *path)
Retrieve a File from storage.
FileCache * findFileCache (char *path)
Search the cache for an entry.
FileCache * findFileCache (String *path)
Search the cache for an entry.
FileCache * findFileCache (FileSystemPath *p)
Search the cache for an entry.
virtual FileCache * cacheHit (FileCache *cache)
Process a cache hit.
void clearFileCache (FileCache *cache=ZERO)
Cleans up the entire file cache (except opened file caches and root).
Protected Attributes inherited from USBController
Arch::IO m_io
I/O instance.
Protected Attributes inherited from FileSystem
FileCache * m_root
Root entry of the filesystem tree.
const char * m_mountPath
Mount point.
List< FileSystemRequest * > * m_requests
Contains ongoing requests.
Protected Attributes inherited from ChannelServer< FileSystem, FileSystemMessage >
ChannelRegistry * m_registry
Contains registered channels.
ChannelClient * m_client
Client for sending replies.
MemoryChannel m_kernelEvent
Kernel event channel.
bool m_sendReply
Should we send a reply message?
Vector< MessageHandler< IPCHandlerFunction > *> * m_ipcHandlers
IPC handler functions.
Vector< MessageHandler< IRQHandlerFunction > *> * m_irqHandlers
IRQ handler functions.
FileSystem * m_instance
Server object instance.
ProcessID m_self
ProcessID of ourselves.
Timer::Info m_time
System timer value.
Detailed Description
Synopsis DesignWare USB Host Controller implementation.
See also
https://github.com/xinu-os/xinu/system/platforms/arm-rpi/usb_dwc_regs.h
Definition at line 44 of file SynopsisController.h.
Member Enumeration Documentation
AHBConfigFlags
enum SynopsisController::AHBConfigFlags private
AHBConfig register flags.
Enumerator
InterruptEnable
AXIWait
DMAEnable
Definition at line 106 of file SynopsisController.h.
CoreIntFlags
enum SynopsisController::CoreIntFlags private
CoreInterrupt register flags.
Enumerator
CoreIntPort
Host port status changed.
CoreIntChannel
Channel interrupt occurred.
Definition at line 116 of file SynopsisController.h.
HostPortControlFlags
enum SynopsisController::HostPortControlFlags private
HostPortControl register flags.
Enumerator
HostPortConnect
HostPortConnectChanged
HostPortEnable
HostPortEnableChanged
HostPortCurrent
HostPortCurrentChanged
HostPortReset
HostPortPower
HostPortSpeed
00: high speed 01: full speed 10: low speed
Definition at line 125 of file SynopsisController.h.
PacketId
enum SynopsisController::PacketId private
Packet ID constants.
Enumerator
Data0
Data1
Data2
SetupId
Definition at line 142 of file SynopsisController.h.
Registers
enum SynopsisController::Registers private
Hardware registers.
Enumerator
OTGControl
OTGInterrupt
AHBConfig
CoreConfig
CoreReset
CoreInterrupt
CoreIntMask
ReceiveStatus
ReceiveStatusPop
RxFIFOSize
TxFIFOSize
TxFIFOStatus
I2CControl
PhyVendorControl
GPIO
UserId
VendorId
HardwareConfig1
HardwareConfig2
HardwareConfig3
HardwareConfig4
CoreLPMConfig
GlobalPowerDn
GlobalFIFOConfig
ADPControl
PeriodTxFIFOSize
HostConfig
HostFrameInterval
HostFrameNumber
HostFIFOStatus
HostChannelInt
HostChannelMask
HostFrameList
HostPortControl
HostChannel
Power
Definition at line 63 of file SynopsisController.h.
Constructor & Destructor Documentation
SynopsisController()
SynopsisController::SynopsisController (const char * path)
Constructor.
Definition at line 24 of file SynopsisController.cpp.
References ChannelCount, Index< T >::insert(), m_channels, and USBController::m_io.
Member Function Documentation
getChannel()
SynopsisChannel * SynopsisController::getChannel (const FileSystemMessage * msg, USBMessage * usb) private
Get a Channel.
Returns
Channel object pointer or ZERO.
Definition at line 195 of file SynopsisController.cpp.
References ChannelCount, SynopsisChannel::getMessage(), SynopsisChannel::getState(), SynopsisChannel::Idle, m_channels, and ZERO.
Referenced by transfer().
hostPortChanged()
void SynopsisController::hostPortChanged () private
Called when the Host Port status changes.
Definition at line 159 of file SynopsisController.cpp.
References HostPortConnect, HostPortConnectChanged, HostPortControl, HostPortCurrent, HostPortCurrentChanged, HostPortEnable, HostPortEnableChanged, HostPortPower, HostPortReset, HostPortSpeed, USBController::m_io, NOTICE, ARMIO::read(), and ARMIO::write().
Referenced by interruptHandler().
initialize()
Error SynopsisController::initialize () virtual
Initialize the Controller.
Returns
Result code
Reimplemented from USBController.
Definition at line 32 of file SynopsisController.cpp.
References ChannelServer< FileSystem, FileSystemMessage >::addIRQHandler(), AHBConfig, AXIWait, Base, ChannelCount, CoreIntChannel, CoreInterrupt, CoreIntMask, CoreIntPort, DEBUG, DefaultVendorId, Memory::Device, DMAEnable, EIO, BroadcomPower::enable(), EnableIRQ, ERROR, ESUCCESS, HostPortConnectChanged, HostPortControl, HostPortCurrentChanged, HostPortEnable, HostPortEnableChanged, HostPortPower, HostPortReset, USBController::initialize(), BroadcomPower::initialize(), InterruptEnable, interruptHandler(), InterruptNumber, m_channels, USBController::m_io, m_power, IO::map(), NOTICE, PAGESIZE, PeriodTxFIFOSize, ProcessCtl(), ARMIO::read(), Memory::Readable, RxFIFOSize, SELF, ARMIO::set(), sleep(), softReset(), IO::Success, BroadcomPower::Success, TxFIFOSize, BroadcomPower::USB, Memory::User, UserId, VendorId, WatchIRQ, Memory::Writable, and ARMIO::write().
Referenced by main().
interruptHandler()
void SynopsisController::interruptHandler (Size vector) private virtual
Interrupt request handler.
Parameters
vector Interrupt vector
Reimplemented from DeviceServer.
Definition at line 127 of file SynopsisController.cpp.
References ChannelCount, CoreIntChannel, CoreInterrupt, CoreIntPort, DEBUG, EnableIRQ, HostChannelInt, hostPortChanged(), DeviceServer::interruptHandler(), InterruptNumber, m_channels, USBController::m_io, ProcessCtl(), ARMIO::read(), and SELF.
Referenced by initialize().
softReset()
void SynopsisController::softReset () private
Reset the Controller.
Definition at line 179 of file SynopsisController.cpp.
References CoreReset, DEBUG, USBController::m_io, ARMIO::read(), sleep(), and ARMIO::write().
Referenced by initialize().
transfer()
Error SynopsisController::transfer (const FileSystemMessage * msg, USBMessage * usb) virtual
Submit USB transfer.
Returns
Result code
Implements USBController.
Definition at line 219 of file SynopsisController.cpp.
References USBMessage::Data, DEBUG, EAGAIN, EIO, ENOTSUP, ERROR, ESUCCESS, USBMessage::Failure, getChannel(), USBMessage::Setup, USBMessage::state, USBMessage::Status, USBMessage::Success, SynopsisChannel::Success, SynopsisChannel::transfer(), and SynopsisChannel::TransferStarted.
Field Documentation
Base
const Address SynopsisController::Base = 0x980000 static private
Register base (offset from I/O base) for the USB controller.
Definition at line 49 of file SynopsisController.h.
Referenced by initialize().
ChannelCount
const Size SynopsisController::ChannelCount = 8 static private
Number of transfer channels supported by hardware.
Definition at line 58 of file SynopsisController.h.
Referenced by getChannel(), initialize(), interruptHandler(), and SynopsisController().
DefaultVendorId
const uint SynopsisController::DefaultVendorId = 0x4f54280a static private
Vendor Identity number for this device.
Definition at line 52 of file SynopsisController.h.
Referenced by initialize().
InterruptNumber
const uint SynopsisController::InterruptNumber = 9 static private
Interrupt number for the USB controller in BCM2835.
Definition at line 55 of file SynopsisController.h.
Referenced by initialize(), and interruptHandler().
m_channels
Index<SynopsisChannel> SynopsisController::m_channels private
Channels.
Definition at line 205 of file SynopsisController.h.
Referenced by getChannel(), initialize(), interruptHandler(), and SynopsisController().
m_power
BroadcomPower SynopsisController::m_power private
Power Management.
Definition at line 202 of file SynopsisController.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
server/usb/controller/SynopsisController.h
server/usb/controller/SynopsisController.cpp