FreeNOS: TestSuite Class Reference
TestSuite Class Reference
lib » libtest
Maintains a list of test instances.
#include <TestSuite.h>
Public Member Functions
TestSuite ()
Class constructor.
void addTest (TestInstance *test)
Add a test.
List< TestInstance * > * getTests ()
Retrieve a list of all tests.
Public Member Functions inherited from Singleton< TestSuite >
Singleton (TestSuite *obj)
Constructor.
Private Attributes
List< TestInstance * > m_tests
List of TestInstances in the suite.
Additional Inherited Members
Static Public Attributes inherited from Singleton< TestSuite >
static TestSuite * instance
One and only instance.
Detailed Description
Maintains a list of test instances.
Definition at line 37 of file TestSuite.h.
Constructor & Destructor Documentation
TestSuite()
TestSuite::TestSuite ()
Class constructor.
Definition at line 22 of file TestSuite.cpp.
Member Function Documentation
addTest()
void TestSuite::addTest (TestInstance * test)
Add a test.
Parameters
test TestInstance to add
Definition at line 26 of file TestSuite.cpp.
References List< T >::append(), and m_tests.
Referenced by TestInstance::TestInstance().
getTests()
List< TestInstance * > * TestSuite::getTests ()
Retrieve a list of all tests.
Returns
List of TestInstances
Definition at line 31 of file TestSuite.cpp.
References m_tests.
Referenced by TestRunner::run().
Field Documentation
m_tests
List<TestInstance *> TestSuite::m_tests private
List of TestInstances in the suite.
Definition at line 63 of file TestSuite.h.
Referenced by addTest(), and getTests().
The documentation for this class was generated from the following files:
lib/libtest/TestSuite.h
lib/libtest/TestSuite.cpp