FreeNOS: BitArray Class Reference
BitArray Class Reference
lib » libstd
Represents an array of bits.
#include <BitArray.h>
Public Types
enum Result { Success, InvalidArgument, OutOfMemory }
Result codes.
Public Member Functions
BitArray (Size size, u8 *array=ZERO)
Class constructor.
virtual ~BitArray ()
Class destructor.
Size size () const
Returns the maximum size of this Container.
Size count (bool on) const
Get the number of bits in the map which have the given value.
void set (Size bit, bool value=true)
Sets the given bit to the given value.
void setRange (Size from, Size to)
Set a range of bits inside the map to 1.
Result setNext (Size *bit, Size count=1, Size offset=0, Size boundary=1)
Sets the next unset bit(s).
void unset (Size bit)
Sets the given bit to zero.
void clear ()
Set all bits to zero.
bool isSet (Size bit) const
Verify if a given bit is set.
u8 * array () const
Retrieve a pointer to the internal BitArray.
void setArray (u8 *array, Size size=ZERO)
Use the given pointer as the BitArray buffer.
bool operator[] (Size bit) const
Retrieve the value of the given bit.
bool operator[] (int bit) const
Retrieve the value of the given bit.
Private Attributes
Size m_size
Total number of bits in the array.
Size m_set
Set bits in the array.
u8 * m_array
Array containing the bits.
bool m_allocated
True if m_array was allocated interally.
Detailed Description
Represents an array of bits.
Definition at line 39 of file BitArray.h.
Member Enumeration Documentation
Result
enum BitArray::Result
Result codes.
Enumerator
Success
InvalidArgument
OutOfMemory
Definition at line 46 of file BitArray.h.
Constructor & Destructor Documentation
BitArray()
BitArray::BitArray (Size size, u8 * array = ZERO)
Class constructor.
Parameters
bits Number of bits.
array Pointer to the bits array to manage.
Definition at line 21 of file BitArray.cpp.
References array(), BITS_TO_BYTES, clear(), m_allocated, m_array, m_set, m_size, size(), and ZERO.
~BitArray()
BitArray::~BitArray () virtual
Class destructor.
Definition at line 30 of file BitArray.cpp.
References m_allocated, and m_array.
Member Function Documentation
array()
u8 * BitArray::array () const
Retrieve a pointer to the internal BitArray.
Returns
Internal BitArray.
Definition at line 130 of file BitArray.cpp.
References m_array.
Referenced by BitArray().
clear()
void BitArray::clear ()
Set all bits to zero.
Definition at line 156 of file BitArray.cpp.
References BITS_TO_BYTES, m_array, m_set, m_size, and MemoryBlock::set().
Referenced by BitArray().
count()
Size BitArray::count (bool on) const
Get the number of bits in the map which have the given value.
Parameters
on True to get the number of 1-bits, false for 0-bits.
Returns
Number of bits with the given value.
Definition at line 41 of file BitArray.cpp.
References m_set, and m_size.
Referenced by BitAllocator::available().
isSet()
bool BitArray::isSet (Size bit) const
Verify if a given bit is set.
Parameters
bit Bit number to check.
Returns
True if marked, false otherwise.
Definition at line 79 of file BitArray.cpp.
References assert, assertRead, m_array, and m_size.
Referenced by BitAllocator::isAllocated(), operator[](), setArray(), and setNext().
operator[]() [1/2]
bool BitArray::operator[] (Size bit) const
Retrieve the value of the given bit.
Parameters
bit Bit number to find
Returns
True if set, false otherwise
Definition at line 165 of file BitArray.cpp.
References isSet().
operator[]() [2/2]
bool BitArray::operator[] (int bit) const
Retrieve the value of the given bit.
Parameters
bit Bit number to find
Returns
True if set, false otherwise
Definition at line 170 of file BitArray.cpp.
References isSet().
set()
void BitArray::set (Size bit, bool value = true)
Sets the given bit to the given value.
Parameters
bit Bit number to set.
value Value to set.
Definition at line 46 of file BitArray.cpp.
References assertRead, assertWrite, m_array, m_set, and m_size.
Referenced by BitAllocator::allocate(), LinnCreate::create(), and LinnCreate::createInode().
setArray()
void BitArray::setArray (u8 * array, Size size = ZERO)
Use the given pointer as the BitArray buffer.
Parameters
array New bits array pointer.
size New number of bits. ZERO to keep the old value.
Definition at line 135 of file BitArray.cpp.
References isSet(), m_allocated, m_array, m_set, m_size, and size().
Referenced by LinnCreate::create(), and LinnCreate::createInode().
setNext()
BitArray::Result BitArray::setNext (Size * bit, Size count = 1, Size offset = 0, Size boundary = 1)
Sets the next unset bit(s).
Parameters
bit Start bit number on success.
count Number of consequetive bits required.
offset Start bit number to start searching at inside the BitArray.
boundary First bit number must be on the given alignment boundary.
Returns
Result code.
Definition at line 93 of file BitArray.cpp.
References isSet(), m_size, OutOfMemory, setRange(), and Success.
Referenced by BitAllocator::allocate(), and LinnCreate::createInode().
setRange()
void BitArray::setRange (Size from, Size to)
Set a range of bits inside the map to 1.
Parameters
from Bit to start with.
to End bit (inclusive).
Definition at line 87 of file BitArray.cpp.
Referenced by setNext().
size()
Size BitArray::size () const
Returns the maximum size of this Container.
Returns
size The maximum size of this Container.
Definition at line 36 of file BitArray.cpp.
References m_size.
Referenced by BitArray(), setArray(), and BitAllocator::size().
unset()
void BitArray::unset (Size bit)
Sets the given bit to zero.
Parameters
bit Bit number to unset.
Definition at line 74 of file BitArray.cpp.
Referenced by BitAllocator::release().
Field Documentation
m_allocated
bool BitArray::m_allocated private
True if m_array was allocated interally.
Definition at line 178 of file BitArray.h.
Referenced by BitArray(), setArray(), and ~BitArray().
m_array
u8* BitArray::m_array private
Array containing the bits.
Definition at line 175 of file BitArray.h.
Referenced by array(), BitArray(), clear(), isSet(), set(), setArray(), and ~BitArray().
m_set
Size BitArray::m_set private
Set bits in the array.
Definition at line 172 of file BitArray.h.
Referenced by BitArray(), clear(), count(), set(), and setArray().
m_size
Size BitArray::m_size private
Total number of bits in the array.
Definition at line 169 of file BitArray.h.
Referenced by BitArray(), clear(), count(), isSet(), set(), setArray(), setNext(), and size().
The documentation for this class was generated from the following files:
lib/libstd/BitArray.h
lib/libstd/BitArray.cpp