FreeNOS: HashTable< K, V > Class Template Reference
HashTable< K, V > Class Template Reference
lib » libstd
Efficient key -> value lookups.
#include <HashTable.h>
Data Structures
class Bucket
Describes a bucket in the HashTable, for collision avoidance.
Public Member Functions
HashTable (Size size=HASHTABLE_DEFAULT_SIZE)
Class constructor.
virtual bool insert (const K &key, const V &value)
Inserts the given item to the Assocation.
virtual bool append (const K &key, const V &value)
Append a new item.
virtual int remove (const K &key)
Remove value(s) for the given key.
virtual Size size () const
Get the size of the HashTable.
virtual Size count () const
Get the number of values stored in the HashTable.
virtual List< K > keys () const
Retrieve all keys inside the Association.
virtual List< K > keys (const V &value) const
Retrieve list of Keys for the given value.
virtual List< V > values () const
Retrieve all values inside the Association.
virtual List< V > values (const K &key) const
Retrieve values for the given key inside the Association.
virtual const V * get (const K &key) const
Returns the first value for the given key.
virtual const V & at (const K &key) const
Returns a reference to the first value for the given key.
virtual const V value (const K &key, const V defaultValue=V()) const
Return the first value for the given key.
Vector< List< Bucket > > & table ()
Get the internal Vector with Buckets.
V & operator[] (const K &key)
Modifiable index operator.
const V & operator[] (const K &key) const
Constant index operator.
Public Member Functions inherited from Associative< K, V >
virtual void clear ()
Removes all items from the Association.
virtual bool contains (const K &key) const
Check if the given key exists.
virtual int compareTo (const Associative< K, V > &a) const
Compare this instance to another instance.
const V & operator[] (K key) const
Returns the first value for the given key.
Public Member Functions inherited from Container
Container ()
Constructor.
virtual ~Container ()
Destructor.
virtual bool isEmpty () const
Check if the Container is empty.
virtual bool reserve (Size size)
Ensure that at least the given size is available.
virtual bool shrink (Size size)
Shrink the container size by the given amount of items.
virtual Size squeeze ()
Try to minimize the memory required in the Container.
virtual bool resize (Size size)
Change the size of the Container.
Public Member Functions inherited from Comparable< Associative< K, V > >
virtual ~Comparable ()
Class destructor.
virtual bool equals (const Associative< K, V > &t) const
Test if an object is equal to an other object.
Private Attributes
Vector< List< Bucket > > m_table
Internal table.
Size m_count
Number of values in the buckets.
Detailed Description
template<class K, class V>
class HashTable< K, V >
Efficient key -> value lookups.
Definition at line 44 of file HashTable.h.
Constructor & Destructor Documentation
HashTable()
template<class K, class V> HashTable< K, V >::HashTable (Size size = HASHTABLE_DEFAULT_SIZE) inline
Class constructor.
Parameters
size Initial size of the internal table.
Definition at line 111 of file HashTable.h.
Member Function Documentation
append()
template<class K, class V> virtual bool HashTable< K, V >::append (const K & key, const V & value) inline virtual
Append a new item.
Parameters
k Associated key.
v New item to append.
Returns
True if append successfull, false otherwise.
Reimplemented from Associative< K, V >.
Definition at line 164 of file HashTable.h.
Referenced by HashTable< String, FileCache *>::append().
at()
template<class K, class V> virtual const V& HashTable< K, V >::at (const K & key) const inline virtual
Returns a reference to the first value for the given key.
Parameters
key Key to find.
Returns
Reference to the first value for the key.
Note
This function assumes the key exists.
Implements Associative< K, V >.
Definition at line 311 of file HashTable.h.
Referenced by HashTable< String, FileCache *>::operator[]().
count()
template<class K, class V> virtual Size HashTable< K, V >::count () const inline virtual
Get the number of values stored in the HashTable.
Returns
Number of items in the HashTable.
Implements Container.
Definition at line 215 of file HashTable.h.
Referenced by FileSystem::clearFileCache(), ArgumentParser::getUsage(), and FileSystem::processRequest().
get()
template<class K, class V> virtual const V* HashTable< K, V >::get (const K & key) const inline virtual
Returns the first value for the given key.
Parameters
key Key to find.
Returns
Pointer to the first value for the given key or ZERO if not found.
Implements Associative< K, V >.
Definition at line 291 of file HashTable.h.
Referenced by ArgumentContainer::get(), Shell::getCommand(), ChannelRegistry::getConsumer(), ChannelRegistry::getProducer(), ArgumentParser::parse(), and UDP::process().
insert()
template<class K, class V> virtual bool HashTable< K, V >::insert (const K & key, const V & value) inline virtual
Inserts the given item to the Assocation.
If an item exists for the given key, its value will be replaced.
Parameters
position The position to insert the item.
item The item to insert
Returns
bool Whether inserting the item at the given position succeeded.
Reimplemented from Associative< K, V >.
Definition at line 133 of file HashTable.h.
Referenced by ArgumentContainer::addFlag(), UDP::bind(), FileCache::FileCache(), LinnFileSystem::getInode(), Shell::registerCommand(), ChannelRegistry::registerConsumer(), ArgumentParser::registerFlag(), and ChannelRegistry::registerProducer().
keys() [1/2]
template<class K, class V> virtual List<K> HashTable< K, V >::keys () const inline virtual
Retrieve all keys inside the Association.
Returns
A List of keys.
Implements Associative< K, V >.
Definition at line 225 of file HashTable.h.
keys() [2/2]
template<class K, class V> virtual List<K> HashTable< K, V >::keys (const V & value) const inline virtual
Retrieve list of Keys for the given value.
Implements Associative< K, V >.
Definition at line 240 of file HashTable.h.
operator[]() [1/2]
template<class K, class V> V& HashTable< K, V >::operator[] (const K & key) inline
Modifiable index operator.
Definition at line 353 of file HashTable.h.
operator[]() [2/2]
template<class K, class V> const V& HashTable< K, V >::operator[] (const K & key) const inline
Constant index operator.
Definition at line 361 of file HashTable.h.
remove()
template<class K, class V> virtual int HashTable< K, V >::remove (const K & key) inline virtual
Remove value(s) for the given key.
Parameters
k Associated key.
Returns
Number of values removed.
Reimplemented from Associative< K, V >.
Definition at line 182 of file HashTable.h.
Referenced by FileSystem::clearFileCache(), ChannelRegistry::unregisterConsumer(), and ChannelRegistry::unregisterProducer().
size()
template<class K, class V> virtual Size HashTable< K, V >::size () const inline virtual
Get the size of the HashTable.
Returns
Size of the internal array.
Implements Container.
Definition at line 205 of file HashTable.h.
Referenced by HashTable< String, FileCache *>::HashTable().
table()
template<class K, class V> Vector<List<Bucket> >& HashTable< K, V >::table () inline
Get the internal Vector with Buckets.
Returns
Reference to the Vector with Buckets.
Definition at line 345 of file HashTable.h.
value()
template<class K, class V> virtual const V HashTable< K, V >::value (const K & key, const V defaultValue = V()) const inline virtual
Return the first value for the given key.
If the key is not found, the default value is returned.
Returns
First value for the given key, or the defaultValue.
Implements Associative< K, V >.
Definition at line 329 of file HashTable.h.
Referenced by FileSystem::findFileCache(), LinnFileSystem::getInode(), and FileSystem::lookupFile().
values() [1/2]
template<class K, class V> virtual List<V> HashTable< K, V >::values () const inline virtual
Retrieve all values inside the Association.
Returns
A List of values.
Implements Associative< K, V >.
Definition at line 257 of file HashTable.h.
values() [2/2]
template<class K, class V> virtual List<V> HashTable< K, V >::values (const K & key) const inline virtual
Retrieve values for the given key inside the Association.
Returns
A List of values.
Implements Associative< K, V >.
Definition at line 273 of file HashTable.h.
Field Documentation
m_count
template<class K, class V> Size HashTable< K, V >::m_count private
Number of values in the buckets.
Definition at line 372 of file HashTable.h.
Referenced by HashTable< String, FileCache *>::append(), HashTable< String, FileCache *>::count(), HashTable< String, FileCache *>::HashTable(), HashTable< String, FileCache *>::insert(), and HashTable< String, FileCache *>::remove().
m_table
template<class K, class V> Vector<List<Bucket> > HashTable< K, V >::m_table private
Internal table.
Definition at line 369 of file HashTable.h.
Referenced by HashTable< String, FileCache *>::append(), HashTable< String, FileCache *>::at(), HashTable< String, FileCache *>::get(), HashTable< String, FileCache *>::HashTable(), HashTable< String, FileCache *>::insert(), HashTable< String, FileCache *>::keys(), HashTable< String, FileCache *>::remove(), HashTable< String, FileCache *>::size(), HashTable< String, FileCache *>::table(), HashTable< String, FileCache *>::value(), and HashTable< String, FileCache *>::values().
The documentation for this class was generated from the following file:
lib/libstd/HashTable.h