FreeNOS: Vector< T > Class Template Reference
Vector< T > Class Template Reference
lib » libstd
Vectors are dynamically resizeable Arrays.
#include <Vector.h>
Public Member Functions
Vector (Size size=VECTOR_DEFAULT_SIZE)
Constructor.
Vector (const Vector< T > &a)
Copy constructor.
virtual ~Vector ()
Destructor.
virtual int insert (const T &item)
Adds the given item to the Vector, if possible.
virtual bool insert (Size position, const T &item)
Inserts the given item at the given position.
virtual const T * get (Size position) const
Returns the item at the given position.
virtual const T & at (Size position) const
Return item at the given position as a reference.
virtual void clear ()
Remove all items from the vector.
virtual bool removeAt (Size position)
Removes the item at the given position.
virtual Size size () const
Returns the maximum size of this Vector.
virtual Size count () const
Returns the number of items inside the Vector.
virtual const T * vector () const
Get Vector data pointer.
virtual bool resize (Size size)
Resize the Vector.
Public Member Functions inherited from Sequence< T >
virtual void fill (T value)
Fill the Sequence with the given value.
virtual int remove (T value)
Remove all items with the given value.
virtual bool contains (const T value) const
Check if the given item is stored in this Sequence.
virtual int compareTo (const Sequence< T > &s) const
Compare this Sequence to another Sequence.
const T & operator[] (int i) const
Returns the item at the given position in the Sequence.
const T & operator[] (Size i) const
Returns the item at the given position in the Sequence.
T & operator[] (int i)
Returns the item at the given position in the Sequence.
T & operator[] (Size i)
Returns the item at the given position in the Sequence.
Public Member Functions inherited from Container
Container ()
Constructor.
virtual ~Container ()
Destructor.
virtual bool isEmpty () const
Check if the Container is empty.
virtual bool reserve (Size size)
Ensure that at least the given size is available.
virtual bool shrink (Size size)
Shrink the container size by the given amount of items.
virtual Size squeeze ()
Try to minimize the memory required in the Container.
Public Member Functions inherited from Comparable< Sequence< T > >
virtual ~Comparable ()
Class destructor.
virtual bool equals (const Sequence< T > &t) const
Test if an object is equal to an other object.
Private Attributes
T * m_array
The actual array where the data is stored.
Size m_size
The maximum size of the array.
Size m_count
Number of used items in the array.
Detailed Description
template<class T>
class Vector< T >
Vectors are dynamically resizeable Arrays.
Definition at line 41 of file Vector.h.
Constructor & Destructor Documentation
Vector() [1/2]
template<class T> Vector< T >::Vector (Size size = VECTOR_DEFAULT_SIZE) inline
Constructor.
Initializes the Vector with the given Size.
Parameters
size The maximum size of the array
Definition at line 52 of file Vector.h.
Vector() [2/2]
template<class T> Vector< T >::Vector (const Vector< T > & a) inline
Copy constructor.
Parameters
a Vector reference to copy from.
Definition at line 66 of file Vector.h.
~Vector()
template<class T> virtual Vector< T >::~Vector () inline virtual
Destructor.
Definition at line 81 of file Vector.h.
Member Function Documentation
at()
template<class T> virtual const T& Vector< T >::at (Size position) const inline virtual
Return item at the given position as a reference.
Parameters
position Position of the item to get.
Implements Sequence< T >.
Definition at line 153 of file Vector.h.
Referenced by DeviceServer::interruptHandler(), ArgumentParser::registerPositional(), CoreServer::runCore(), and Scheduler::select().
clear()
template<class T> virtual void Vector< T >::clear () inline virtual
Remove all items from the vector.
Reimplemented from Sequence< T >.
Definition at line 161 of file Vector.h.
count()
template<class T> virtual Size Vector< T >::count () const inline virtual
Returns the number of items inside the Vector.
Returns
Number of items inside the Vector.
Implements Container.
Definition at line 204 of file Vector.h.
Referenced by ProcessManager::create(), Echo::exec(), FileStatus::exec(), CreateFile::exec(), ListFiles::exec(), Remove::exec(), Shell::exec(), Cat::exec(), BootImageCreate::exec(), ArgumentContainer::get(), ArgumentParser::getUsage(), Cat::initialize(), ArgumentParser::parse(), ArgumentParser::registerPositional(), ArgumentContainer::~ArgumentContainer(), and ArgumentParser::~ArgumentParser().
get()
template<class T> virtual const T* Vector< T >::get (Size position) const inline virtual
Returns the item at the given position.
Parameters
position The position of the item to get.
Returns
Pointer to the item at the given position.
Implements Sequence< T >.
Definition at line 139 of file Vector.h.
Referenced by ProcessManager::get(), and API::invoke().
insert() [1/2]
template<class T> virtual int Vector< T >::insert (const T & item) inline virtual
Adds the given item to the Vector, if possible.
Parameters
item The item to add to the Vector.
Returns
Position of the item in the Vector or -1 on failure.
Reimplemented from Sequence< T >.
Definition at line 93 of file Vector.h.
Referenced by ArgumentContainer::addPositional(), API::API(), ProcessManager::create(), Kernel::hookIntVector(), LinnFileSystem::LinnFileSystem(), TestChar< T >::random(), BootImageCreate::readBootSymbols(), DeviceServer::registerDevice(), DeviceServer::registerInterrupt(), ArgumentParser::registerPositional(), and TestChar< T >::unique().
insert() [2/2]
template<class T> virtual bool Vector< T >::insert (Size position, const T & item) inline virtual
Inserts the given item at the given position.
If an item exists at the given position, it will be replaced by the given item.
Parameters
position The position to insert the item.
item The item to insert
Returns
bool Whether inserting the item at the given position succeeded.
Reimplemented from Sequence< T >.
Definition at line 113 of file Vector.h.
removeAt()
template<class T> virtual bool Vector< T >::removeAt (Size position) inline virtual
Removes the item at the given position.
Parameters
position The position of the item to remove.
Returns
bool Whether removing the item succeeded.
Reimplemented from Sequence< T >.
Definition at line 173 of file Vector.h.
resize()
template<class T> virtual bool Vector< T >::resize (Size size) inline virtual
Resize the Vector.
Parameters
increase Size to add to the Vector.
Reimplemented from Container.
Definition at line 224 of file Vector.h.
Referenced by Vector< List< HashTable::Bucket > >::insert().
size()
template<class T> virtual Size Vector< T >::size () const inline virtual
Returns the maximum size of this Vector.
Returns
size The maximum size of this Vector.
Implements Container.
Definition at line 194 of file Vector.h.
Referenced by BootImageCreate::exec(), ProcessManager::remove(), Vector< List< HashTable::Bucket > >::resize(), Scheduler::select(), and Vector< List< HashTable::Bucket > >::Vector().
vector()
template<class T> virtual const T* Vector< T >::vector () const inline virtual
Get Vector data pointer.
Returns
Pointer to Vector data.
Definition at line 214 of file Vector.h.
Field Documentation
m_array
template<class T> T* Vector< T >::m_array private
The actual array where the data is stored.
Definition at line 247 of file Vector.h.
Referenced by Vector< List< HashTable::Bucket > >::at(), Vector< List< HashTable::Bucket > >::get(), Vector< List< HashTable::Bucket > >::insert(), Vector< List< HashTable::Bucket > >::removeAt(), Vector< List< HashTable::Bucket > >::resize(), Vector< List< HashTable::Bucket > >::Vector(), Vector< List< HashTable::Bucket > >::vector(), and Vector< List< HashTable::Bucket > >::~Vector().
m_count
template<class T> Size Vector< T >::m_count private
Number of used items in the array.
Definition at line 253 of file Vector.h.
Referenced by Vector< List< HashTable::Bucket > >::clear(), Vector< List< HashTable::Bucket > >::count(), Vector< List< HashTable::Bucket > >::get(), Vector< List< HashTable::Bucket > >::insert(), Vector< List< HashTable::Bucket > >::removeAt(), and Vector< List< HashTable::Bucket > >::Vector().
m_size
template<class T> Size Vector< T >::m_size private
The maximum size of the array.
Definition at line 250 of file Vector.h.
Referenced by Vector< List< HashTable::Bucket > >::insert(), Vector< List< HashTable::Bucket > >::resize(), Vector< List< HashTable::Bucket > >::size(), and Vector< List< HashTable::Bucket > >::Vector().
The documentation for this class was generated from the following file:
lib/libstd/Vector.h