FreeNOS: USBHub Class Reference
USBHub Class Reference
lib » libusb
USB Hub driver.
#include <USBHub.h>
Data Structures
struct Status
USB Hub current status and changed status format.
Public Member Functions
USBHub (u8 deviceId, const char *usbPath="/usb")
Constructor.
virtual ~USBHub ()
Destructor.
virtual Error initialize ()
Initialize the hub.
Public Member Functions inherited from USBDevice
USBDevice (u8 deviceId, const char *usbPath="/usb")
Constructor.
virtual ~USBDevice ()
Destructor.
Public Member Functions inherited from Device
Device (FileType type)
Constructor.
virtual ~Device ()
Destructor.
virtual const String & getIdentifier () const
Get unique device identifier.
virtual Error interrupt (Size vector)
Called when an interrupt has been triggered for this device.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read bytes from the file.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Types
enum RequestType {
GetStatus = 0, ClearFeature = 1, SetFeature = 3, GetDescriptor = 6,
SetDescriptor = 7, ClearTTBuffer = 8, ResetTT = 9, GetTTState = 10,
StopTT = 11
}
USB Hub standard requests.
enum PortFeature {
PortConnection = 0, PortEnable = 1, PortSuspend = 2, PortOverCurrent = 3,
PortReset = 4, PortPower = 8, PortLowSpeed = 9, PortClearConnection = 16,
PortClearEnable = 17, PortClearSuspsend = 18, PortClearOverCurrent = 19, PortClearReset = 20,
PortTest = 21, PortIndicator = 22
}
USB Hub Port Features.
typedef struct USBHub::Status Status
USB Hub current status and changed status format.
Private Member Functions
Error setPortFeature (u8 port, PortFeature feature)
Set feature on a HUB port.
Error portAttach (u8 port)
Attach device on port.
Private Attributes
USBDescriptor::Hub * m_hub
Hub descriptor.
Additional Inherited Members
Protected Member Functions inherited from USBDevice
Error getDeviceDescriptor (USBDescriptor::Device *desc, Size size=sizeof(USBDescriptor::Device))
Get device descriptor.
Error getConfigDescriptor (USBDescriptor::Configuration *desc, Size size=sizeof(USBDescriptor::Configuration))
Get configuration descriptor.
Error getInterfaceDescriptor (USBDescriptor::Interface *desc)
Get interface descriptor.
Error getEndpointDescriptor (u8 endpointId, USBDescriptor::Endpoint *desc)
Get endpoint descriptor.
Error setAddress (u8 address)
Set device address.
Error setConfiguration (u8 configId)
Activate a configuration.
Error controlMessage (u8 request, const USBTransfer::Direction direction, const USBTransfer::RequestType type, const USBTransfer::Recipient recipient, u16 value, u16 index, void *buffer, Size size)
Send a control message.
Error transfer (const USBTransfer::Type type, const USBTransfer::Direction direction, Address endpointId, void *buffer, Size size, Size maxPacketSize=0)
Start a synchronous USB transfer.
Error beginTransfer (const USBTransfer::Type type, const USBTransfer::Direction direction, Address endpointId, void *buffer, Size size, Size maxPacketSize=0, CallbackFunction *callback=0)
Start an asynchronous USB transfer.
Error finishTransfer (FileSystemMessage *msg)
Complete asynchronous USB transfer.
Error submit (USBMessage &msg)
Submit a USB transfer to the Host controller.
Protected Attributes inherited from USBDevice
Address m_id
USB device identifier.
USBTransfer::Speed m_speed
USB speed.
int m_transferFile
USB transfer I/O file.
String m_busPath
USB bus path.
USBDescriptor::Device * m_device
USB device descriptor.
USBDescriptor::Configuration * m_config
USB configuration descriptor.
Index< USBDescriptor::Interface > m_interfaces
USB interface descriptors.
Index< USBDescriptor::Endpoint > m_endpoints
USB endpoint descriptors.
Index< USBDescriptor::String > m_strings
USB string descriptor.
Array< u8, 128 > m_endpointsPacketId
Contains endpoint to saved packet id mapping.
Protected Attributes inherited from Device
String m_identifier
Unique identifier for this Device.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
USB Hub driver.
Definition at line 36 of file USBHub.h.
Member Typedef Documentation
Status
typedef struct USBHub::Status USBHub::Status private
USB Hub current status and changed status format.
Member Enumeration Documentation
PortFeature
enum USBHub::PortFeature private
USB Hub Port Features.
Enumerator
PortConnection
PortEnable
PortSuspend
PortOverCurrent
PortReset
PortPower
PortLowSpeed
PortClearConnection
PortClearEnable
PortClearSuspsend
PortClearOverCurrent
PortClearReset
PortTest
PortIndicator
Definition at line 67 of file USBHub.h.
RequestType
enum USBHub::RequestType private
USB Hub standard requests.
Enumerator
GetStatus
ClearFeature
SetFeature
GetDescriptor
SetDescriptor
ClearTTBuffer
ResetTT
GetTTState
StopTT
Definition at line 41 of file USBHub.h.
Constructor & Destructor Documentation
USBHub()
USBHub::USBHub (u8 deviceId, const char * usbPath = "/usb")
Constructor.
Definition at line 23 of file USBHub.cpp.
References DEBUG, and m_hub.
~USBHub()
USBHub::~USBHub () virtual
Destructor.
Definition at line 31 of file USBHub.cpp.
References m_hub.
Member Function Documentation
initialize()
Error USBHub::initialize () virtual
Initialize the hub.
Returns
Result code
Reimplemented from USBDevice.
Definition at line 36 of file USBHub.cpp.
References USBTransfer::Class, USBDevice::controlMessage(), DEBUG, USBTransfer::Device, ERROR, ESUCCESS, GetDescriptor, USBDescriptor::Hub::hubCharacteristics, USBDescriptor::HubType, USBTransfer::In, USBDevice::initialize(), m_hub, USBDescriptor::Hub::numPorts, portAttach(), PortPower, and setPortFeature().
portAttach()
Error USBHub::portAttach (u8 port) private
Attach device on port.
Definition at line 90 of file USBHub.cpp.
References DEBUG, USBDescriptor::Device::descriptorType, USBDescriptor::Device::deviceClass, USBDescriptor::Device::deviceSubClass, EIO, errno, ERROR, ESUCCESS, forkexec(), USBDevice::getDeviceDescriptor(), USBDevice::m_id, USBDescriptor::Device::manufacturer, NOTICE, PortReset, USBDescriptor::Device::product, USBDescriptor::Device::productId, setPortFeature(), sleep(), strerror(), and USBDescriptor::Device::vendorId.
Referenced by initialize().
setPortFeature()
Error USBHub::setPortFeature (u8 port, USBHub::PortFeature feature) private
Set feature on a HUB port.
Definition at line 79 of file USBHub.cpp.
References USBTransfer::Class, USBDevice::controlMessage(), DEBUG, USBTransfer::Other, USBTransfer::Out, and SetFeature.
Referenced by initialize(), and portAttach().
Field Documentation
m_hub
USBDescriptor::Hub* USBHub::m_hub private
Hub descriptor.
Definition at line 119 of file USBHub.h.
Referenced by initialize(), USBHub(), and ~USBHub().
The documentation for this class was generated from the following files:
lib/libusb/USBHub.h
lib/libusb/USBHub.cpp