FreeNOS: SievePrime Class Reference
SievePrime Class Reference
bin
Compute prime numbers using the Sieve of Eratosthenes algorithm.
#include <SievePrime.h>
Public Member Functions
SievePrime (int argc, char **argv)
Constructor.
virtual ~SievePrime ()
Destructor.
virtual Result exec ()
Execute the application.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Private Member Functions
void searchSequential (int number, unsigned *map) const
Perform sequential search for prime numbers.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
Compute prime numbers using the Sieve of Eratosthenes algorithm.
Definition at line 31 of file SievePrime.h.
Constructor & Destructor Documentation
SievePrime()
SievePrime::SievePrime (int argc, char ** argv)
Constructor.
Parameters
argc Argument count
argv Argument values
Definition at line 27 of file SievePrime.cpp.
References Application::parser(), ArgumentParser::registerFlag(), ArgumentParser::registerPositional(), and ArgumentParser::setDescription().
~SievePrime()
SievePrime::~SievePrime () virtual
Destructor.
Definition at line 35 of file SievePrime.cpp.
Member Function Documentation
exec()
SievePrime::Result SievePrime::exec () virtual
Execute the application.
Returns
Result code
Implements Application.
Definition at line 60 of file SievePrime.cpp.
References Application::arguments(), atoi(), errno, ERROR, Application::IOError, String::length(), malloc(), NULL, POSIXApplication::output(), searchSequential(), sqrt(), strerror(), Application::Success, and write().
searchSequential()
void SievePrime::searchSequential (int number, unsigned * map) const private
Perform sequential search for prime numbers.
Parameters
number Maximum number to search for prime numbers
map Pointer to array with prime numbers marked
Definition at line 39 of file SievePrime.cpp.
Referenced by exec().
The documentation for this class was generated from the following files:
bin/prime/SievePrime.h
bin/prime/SievePrime.cpp