FreeNOS: ELF Class Reference
ELF Class Reference
lib » libexec
Executable and Linkable Format (ELF).
#include <ELF.h>
Public Member Functions
ELF (const u8 *image, Size size)
Class constructor.
virtual ~ELF ()
Class destructor.
virtual Result regions (Region *regions, Size *count) const
Reads out segments from the ELF program table.
virtual Result entry (Address *entry) const
Lookup the program entry point.
Public Member Functions inherited from ExecutableFormat
ExecutableFormat (const u8 *image, Size size)
Class constructor.
virtual ~ExecutableFormat ()
Class destructor.
Static Public Member Functions
static Result detect (const u8 *image, Size size, ExecutableFormat **fmt)
Read ELF header from memory.
Static Public Member Functions inherited from ExecutableFormat
static Result find (const u8 *image, Size size, ExecutableFormat **fmt)
Find a ExecutableFormat which can handle the given format.
Additional Inherited Members
Public Types inherited from ExecutableFormat
enum Result { Success, NotFound, InvalidFormat, OutOfMemory }
Result code.
typedef struct ExecutableFormat::Region Region
Memory region.
Protected Attributes inherited from ExecutableFormat
const u8 * m_image
Input image raw data.
const Size m_size
Input image size in bytes.
Detailed Description
Executable and Linkable Format (ELF).
Definition at line 37 of file ELF.h.
Constructor & Destructor Documentation
ELF()
ELF::ELF (const u8 * image, Size size)
Class constructor.
Parameters
image Pointer to raw input image data
size Number of bytes of input image data
Definition at line 28 of file ELF.cpp.
Referenced by detect().
~ELF()
ELF::~ELF () virtual
Class destructor.
Definition at line 33 of file ELF.cpp.
Member Function Documentation
detect()
ELF::Result ELF::detect (const u8 * image, Size size, ExecutableFormat ** fmt) static
Read ELF header from memory.
Parameters
image Pointer to raw input image data
size Number of bytes of input image data
fmt Outputs a pointer to an ELF instance
Returns
Result code
Definition at line 37 of file ELF.cpp.
References ELF(), ELF_CLASS_32, ELF_INDEX_CLASS, ELF_INDEX_MAGIC0, ELF_INDEX_MAGIC1, ELF_INDEX_MAGIC2, ELF_INDEX_MAGIC3, ELF_MAGIC0, ELF_MAGIC1, ELF_MAGIC2, ELF_MAGIC3, ELF_TYPE_EXEC, ELF_VERSION_CURRENT, ELFHeader::ident, ExecutableFormat::InvalidFormat, ExecutableFormat::Success, ELFHeader::type, and ELFHeader::version.
Referenced by ExecutableFormat::find().
entry()
ELF::Result ELF::entry (Address * entry) const virtual
Lookup the program entry point.
Parameters
entry Program entry point on output.
Returns
Result code.
Implements ExecutableFormat.
Definition at line 106 of file ELF.cpp.
References ELFHeader::entry, ExecutableFormat::m_image, and ExecutableFormat::Success.
regions()
ELF::Result ELF::regions (ELF::Region * regions, Size * count) const virtual
Reads out segments from the ELF program table.
Parameters
regions Memory regions to fill.
count Maximum number of memory regions on input. Actual number of memory regions on output.
Returns
Result code.
Implements ExecutableFormat.
Definition at line 59 of file ELF.cpp.
References ExecutableFormat::Region::access, MemoryBlock::copy(), ExecutableFormat::Region::data, ELF_SEGMENT_LOAD, ExecutableFormat::InvalidFormat, ExecutableFormat::m_image, ELFSegment::memorySize, memset(), ELFHeader::programHeaderEntryCount, ELFHeader::programHeaderEntrySize, ELFHeader::programHeaderOffset, Memory::Readable, ExecutableFormat::Region::size, ExecutableFormat::Success, Memory::User, ExecutableFormat::Region::virt, ELFSegment::virtualAddress, and Memory::Writable.
The documentation for this class was generated from the following files:
lib/libexec/ELF.h
lib/libexec/ELF.cpp