FreeNOS: IOBuffer Class Reference
IOBuffer Class Reference
lib » libfs
Abstract Input/Output buffer.
#include <IOBuffer.h>
Public Member Functions
IOBuffer (const FileSystemMessage *msg)
Constructor.
virtual ~IOBuffer ()
Destructor.
Size getCount () const
Get byte count.
const FileSystemMessage * getMessage () const
Get filesystem message.
const u8 * getBuffer () const
Get raw buffer.
Error read (void *buffer, Size size, Size offset=ZERO) const
Read bytes from the I/O buffer.
Error write (void *buffer, Size size, Size offset=ZERO) const
Write bytes to the I/O buffer.
Error bufferedRead ()
Buffered read bytes from message to the I/O buffer.
Error bufferedWrite (void *buffer, Size size)
Buffered write bytes to the I/O buffer.
Error flush () const
Flush write buffers.
u8 operator[] (Size index) const
Byte index operator.
Private Attributes
const FileSystemMessage * m_message
Current request being processed.
u8 * m_buffer
Buffer for storing temporary data.
Size m_size
Buffer size.
Size m_count
Bytes written to the buffer.
Detailed Description
Abstract Input/Output buffer.
Definition at line 36 of file IOBuffer.h.
Constructor & Destructor Documentation
IOBuffer()
IOBuffer::IOBuffer (const FileSystemMessage * msg)
Constructor.
Parameters
msg Describes the request being processed.
Definition at line 20 of file IOBuffer.cpp.
References FileSystemMessage::action, m_buffer, m_count, m_size, ReadFile, FileSystemMessage::size, and WriteFile.
~IOBuffer()
IOBuffer::~IOBuffer () virtual
Destructor.
Definition at line 32 of file IOBuffer.cpp.
References m_buffer.
Member Function Documentation
bufferedRead()
Error IOBuffer::bufferedRead ()
Buffered read bytes from message to the I/O buffer.
Returns
Error code.
Definition at line 53 of file IOBuffer.cpp.
References m_buffer, m_count, m_message, read(), and FileSystemMessage::size.
Referenced by FileSystem::processRequest().
bufferedWrite()
Error IOBuffer::bufferedWrite (void * buffer, Size size)
Buffered write bytes to the I/O buffer.
Parameters
buffer Contains the bytes to write.
size Number of bytes to write.
offset The offset inside the I/O buffer to start writing.
Returns
Number of bytes written on success, and error code on failure.
Definition at line 59 of file IOBuffer.cpp.
References m_buffer, m_count, m_message, m_size, and FileSystemMessage::size.
Referenced by Terminal::initialize(), PL011::read(), i8250::read(), and ATAController::read().
flush()
Error IOBuffer::flush () const
Flush write buffers.
Returns
Error code.
Definition at line 87 of file IOBuffer.cpp.
References m_buffer, m_count, and write().
Referenced by FileSystem::processRequest().
getBuffer()
const u8 * IOBuffer::getBuffer () const
Get raw buffer.
Returns
Buffer pointer.
Definition at line 48 of file IOBuffer.cpp.
References m_buffer.
Referenced by USBTransferFile::write(), LCDBar::write(), and VGA::write().
getCount()
Size IOBuffer::getCount () const
Get byte count.
Returns
Byte count of the internal buffer.
Definition at line 38 of file IOBuffer.cpp.
References m_count.
Referenced by Terminal::initialize(), FileSystem::processRequest(), and PL011::read().
getMessage()
const FileSystemMessage * IOBuffer::getMessage () const
Get filesystem message.
Returns
FileSystemMessage pointer.
Definition at line 43 of file IOBuffer.cpp.
References m_message.
Referenced by USBTransferFile::write().
operator[]()
u8 IOBuffer::operator[] (Size index) const
Byte index operator.
Parameters
index Index value
Returns
Byte value at the given index or 0 if index is invalid.
Definition at line 92 of file IOBuffer.cpp.
References m_buffer, and m_size.
read()
Error IOBuffer::read (void * buffer, Size size, Size offset = ZERO) const
Read bytes from the I/O buffer.
Parameters
buffer Copy bytes from the I/O buffer to this memory address.
size Number of bytes to copy.
offset The offset inside the I/O buffer to start reading.
Returns
Number of bytes read on success, and error code on failure.
Definition at line 73 of file IOBuffer.cpp.
References FileSystemMessage::buffer, FileSystemMessage::from, m_message, API::Read, and VMCopy().
Referenced by bufferedRead(), UDP::sendPacket(), MountWaitFile::write(), IPV4Address::write(), MountsFile::write(), ARPSocket::write(), UDPSocket::write(), ICMPSocket::write(), and PseudoFile::write().
write()
Error IOBuffer::write (void * buffer, Size size, Size offset = ZERO) const
Write bytes to the I/O buffer.
Parameters
buffer Contains the bytes to write.
size Number of bytes to write.
offset The offset inside the I/O buffer to start writing.
Returns
Number of bytes written on success, and error code on failure.
Definition at line 80 of file IOBuffer.cpp.
References FileSystemMessage::buffer, FileSystemMessage::from, m_message, VMCopy(), and API::Write.
Referenced by flush(), EthernetAddress::read(), IPV4Address::read(), UDPFactory::read(), ICMPFactory::read(), MountsFile::read(), ARPSocket::read(), DigitalPort::read(), AnalogPort::read(), LinnFile::read(), UDPSocket::read(), LinnDirectory::read(), ICMPSocket::read(), PseudoFile::read(), Keyboard::read(), Directory::read(), Time::read(), VGA::read(), Terminal::read(), and USBTransferFile::write().
Field Documentation
m_buffer
u8* IOBuffer::m_buffer private
Buffer for storing temporary data.
Definition at line 144 of file IOBuffer.h.
Referenced by bufferedRead(), bufferedWrite(), flush(), getBuffer(), IOBuffer(), operator[](), and ~IOBuffer().
m_count
Size IOBuffer::m_count private
Bytes written to the buffer.
Definition at line 150 of file IOBuffer.h.
Referenced by bufferedRead(), bufferedWrite(), flush(), getCount(), and IOBuffer().
m_message
const FileSystemMessage* IOBuffer::m_message private
Current request being processed.
Read() and write() will use fields from the current request to fill in arguments for VMCopy().
See also
VMCopy
IOBuffer::read
IOBuffer::write
Definition at line 141 of file IOBuffer.h.
Referenced by bufferedRead(), bufferedWrite(), getMessage(), read(), and write().
m_size
Size IOBuffer::m_size private
Buffer size.
Definition at line 147 of file IOBuffer.h.
Referenced by bufferedWrite(), IOBuffer(), and operator[]().
The documentation for this class was generated from the following files:
lib/libfs/IOBuffer.h
lib/libfs/IOBuffer.cpp