FreeNOS: LinnFileSystem Class Reference
LinnFileSystem Class Reference
server » LinnFS
Linnenbank FileSystem (LinnFS).
#include <LinnFileSystem.h>
Public Member Functions
LinnFileSystem (const char *path, Storage *storage)
Class constructor function.
LinnSuperBlock * getSuperBlock ()
Retrieve the superblock pointer.
Storage * getStorage ()
Get the underlying Storage object.
LinnInode * getInode (u32 inodeNum)
Read an inode from the filesystem.
LinnGroup * getGroup (u32 groupNum)
Read a group descriptor from the filesystem.
LinnGroup * getGroupByInode (u32 inodeNum)
Read a group descriptor from the filesystem, given an inode number.
u64 getOffset (LinnInode *inode, u32 blk)
Calculates the offset inside storage for a given block.
Public Member Functions inherited from FileSystem
FileSystem (const char *path)
Constructor function.
virtual ~FileSystem ()
Destructor function.
const char * getMountPath () const
Get mount path.
Directory * getRoot ()
Get root directory.
Error mount ()
Mount the FileSystem.
Error registerFile (File *file, const char *path,...)
Register a new File.
Error registerFile (File *file, const char *path, va_list args)
Register a new File with variable arguments.
virtual File * createFile (FileType type, DeviceID deviceID)
Create a new file.
FileCache * insertFileCache (File *file, const char *pathFormat,...)
Inserts a file into the in-memory filesystem tree.
FileCache * insertFileCache (File *file, const char *pathFormat, va_list args)
Inserts a file into the in-memory filesystem tree.
void pathHandler (FileSystemMessage *msg)
Process an incoming filesystem request using a path.
virtual void timeout ()
Called when a sleep timeout is expired.
virtual bool retryRequests ()
Retry any pending requests.
Public Member Functions inherited from ChannelServer< FileSystem, FileSystemMessage >
ChannelServer (FileSystem *inst, Size num=32)
Constructor function.
virtual ~ChannelServer ()
Destructor function.
int run ()
Enters an infinite loop, serving incoming requests.
void addIPCHandler (Size slot, IPCHandlerFunction h, bool sendReply=true)
Register a new IPC message action handler.
void addIRQHandler (Size slot, IRQHandlerFunction h)
Register a new IRQ message vector handler.
void setTimeout (uint msec)
Set a sleep timeout.
Private Member Functions
void notSupportedHandler (FileSystemMessage *msg)
Callback handler for unsupported operations.
Private Attributes
Storage * storage
Provides storage.
LinnSuperBlock super
Describes the filesystem.
Vector< LinnGroup * > * groups
Group descriptors.
HashTable< u32, LinnInode * > inodes
Inode cache.
Additional Inherited Members
Public Types inherited from ChannelServer< FileSystem, FileSystemMessage >
enum Result
Result codes.
Protected Types inherited from ChannelServer< FileSystem, FileSystemMessage >
typedef void(FileSystem ::* IPCHandlerFunction) (FileSystemMessage *)
Member function pointer inside Base, to handle IPC messages.
typedef void(FileSystem ::* IRQHandlerFunction) (Size)
Member function pointer inside Base, to handle interrupts.
Protected Member Functions inherited from FileSystem
Error processRequest (FileSystemRequest *req)
Process a FileSystemRequest.
void sendResponse (FileSystemMessage *msg)
Send response for a FileSystemMessage.
void setRoot (Directory *newRoot)
Change the filesystem root directory.
FileCache * lookupFile (FileSystemPath *path)
Retrieve a File from storage.
FileCache * findFileCache (char *path)
Search the cache for an entry.
FileCache * findFileCache (String *path)
Search the cache for an entry.
FileCache * findFileCache (FileSystemPath *p)
Search the cache for an entry.
virtual FileCache * cacheHit (FileCache *cache)
Process a cache hit.
void clearFileCache (FileCache *cache=ZERO)
Cleans up the entire file cache (except opened file caches and root).
Protected Attributes inherited from FileSystem
FileCache * m_root
Root entry of the filesystem tree.
const char * m_mountPath
Mount point.
List< FileSystemRequest * > * m_requests
Contains ongoing requests.
Protected Attributes inherited from ChannelServer< FileSystem, FileSystemMessage >
ChannelRegistry * m_registry
Contains registered channels.
ChannelClient * m_client
Client for sending replies.
MemoryChannel m_kernelEvent
Kernel event channel.
bool m_sendReply
Should we send a reply message?
Vector< MessageHandler< IPCHandlerFunction > *> * m_ipcHandlers
IPC handler functions.
Vector< MessageHandler< IRQHandlerFunction > *> * m_irqHandlers
IRQ handler functions.
FileSystem * m_instance
Server object instance.
ProcessID m_self
ProcessID of ourselves.
Timer::Info m_time
System timer value.
Detailed Description
Linnenbank FileSystem (LinnFS).
This filesystem is rougly based on the Extended 2 FileSystem. Some changes have been made to the superblock: leaving out unused fields and simplified the meaning of existing onces. Directory entries are now static in size, i.e. 64-bytes. Those changes make it easier to program the FileSystem implementation, thus easier to understand and learn from.
See also
FileSystem
Ext2FileSystem
Definition at line 72 of file LinnFileSystem.h.
Constructor & Destructor Documentation
LinnFileSystem()
LinnFileSystem::LinnFileSystem (const char * path, Storage * storage)
Class constructor function.
Parameters
path Path to which we are mounted.
storage Storage provider.
Definition at line 70 of file LinnFileSystem.cpp.
References ChannelServer< FileSystem, FileSystemMessage >::addIPCHandler(), LinnSuperBlock::blocksCount, LinnSuperBlock::blockSize, DeleteFile, FATAL, Sequence< T >::fill(), LinnSuperBlock::freeBlocksCount, LinnSuperBlock::freeInodesCount, getInode(), groups, LinnSuperBlock::groupsTable, INFO, LinnSuperBlock::inodesCount, Vector< T >::insert(), LINN_GROUP_COUNT, LINN_INODE_ROOT, LINN_SUPER_MAGIC0, LINN_SUPER_MAGIC1, LINN_SUPER_OFFSET, LinnSuperBlock::magic0, LinnSuperBlock::magic1, NOTICE, notSupportedHandler(), Storage::read(), FileSystem::setRoot(), strerror(), super, WriteFile, and ZERO.
Member Function Documentation
getGroup()
LinnGroup * LinnFileSystem::getGroup (u32 groupNum)
Read a group descriptor from the filesystem.
Parameters
groupNum Group descriptor number.
Returns
Pointer to an LinnGroup on success, ZERO on failure.
See also
LinnGroup
Definition at line 170 of file LinnFileSystem.cpp.
References groups.
Referenced by getGroupByInode(), and getStorage().
getGroupByInode()
LinnGroup * LinnFileSystem::getGroupByInode (u32 inodeNum)
Read a group descriptor from the filesystem, given an inode number.
Parameters
inodeNum Find the corresponding group via this inode number.
Returns
Pointer to an LinnGroup on success, ZERO on failure.
See also
LinnGroup
LinnInode
Definition at line 175 of file LinnFileSystem.cpp.
References getGroup(), LinnSuperBlock::inodesPerGroup, and super.
Referenced by getInode(), and getStorage().
getInode()
LinnInode * LinnFileSystem::getInode (u32 inodeNum)
Read an inode from the filesystem.
Parameters
inodeNum Inode number.
Returns
Pointer to an LinnInode on success, ZERO on failure.
See also
LinnInode
Definition at line 131 of file LinnFileSystem.cpp.
References LinnSuperBlock::blockSize, Associative< K, V >::contains(), ERROR, getGroupByInode(), inodes, LinnSuperBlock::inodesCount, LinnSuperBlock::inodesPerGroup, LinnGroup::inodeTable, HashTable< K, V >::insert(), Storage::read(), storage, strerror(), super, HashTable< K, V >::value(), and ZERO.
Referenced by getStorage(), LinnFileSystem(), LinnDirectory::lookup(), and LinnDirectory::read().
getOffset()
u64 LinnFileSystem::getOffset (LinnInode * inode, u32 blk)
Calculates the offset inside storage for a given block.
Parameters
inode LinnInode pointer.
blk Calculate the offset for this block.
Returns
Offset in bytes in storage.
See also
LinnInode
Definition at line 180 of file LinnFileSystem.cpp.
References LinnInode::block, LinnSuperBlock::blockSize, LINN_INODE_DIR_BLOCKS, LINN_SUPER_NUM_PTRS, Storage::read(), storage, super, and ZERO.
Referenced by getStorage(), and LinnFile::read().
getStorage()
Storage* LinnFileSystem::getStorage () inline
Get the underlying Storage object.
Returns
Storage pointer.
See also
Storage
Definition at line 103 of file LinnFileSystem.h.
References getGroup(), getGroupByInode(), getInode(), getOffset(), notSupportedHandler(), and storage.
Referenced by LinnDirectory::getLinnDirectoryEntry(), LinnFile::read(), and LinnDirectory::read().
getSuperBlock()
LinnSuperBlock* LinnFileSystem::getSuperBlock () inline
Retrieve the superblock pointer.
Returns
Pointer to the superblock for this filesystem.
See also
LinnSuperBlock
Definition at line 91 of file LinnFileSystem.h.
References super.
Referenced by LinnDirectory::getLinnDirectoryEntry(), LinnFile::read(), and LinnDirectory::read().
notSupportedHandler()
void LinnFileSystem::notSupportedHandler (FileSystemMessage * msg) private
Callback handler for unsupported operations.
Parameters
msg FileSystemMessage pointer
Definition at line 245 of file LinnFileSystem.cpp.
References ENOTSUP, FileSystemMessage::result, and FileSystem::sendResponse().
Referenced by getStorage(), and LinnFileSystem().
Field Documentation
groups
Vector<LinnGroup *>* LinnFileSystem::groups private
Group descriptors.
Definition at line 172 of file LinnFileSystem.h.
Referenced by getGroup(), and LinnFileSystem().
inodes
HashTable<u32, LinnInode *> LinnFileSystem::inodes private
Inode cache.
Definition at line 175 of file LinnFileSystem.h.
Referenced by getInode().
storage
Storage* LinnFileSystem::storage private
Provides storage.
Definition at line 166 of file LinnFileSystem.h.
Referenced by getInode(), getOffset(), and getStorage().
super
LinnSuperBlock LinnFileSystem::super private
Describes the filesystem.
Definition at line 169 of file LinnFileSystem.h.
Referenced by getGroupByInode(), getInode(), getOffset(), getSuperBlock(), and LinnFileSystem().
The documentation for this class was generated from the following files:
server/filesystem/linn/LinnFileSystem.h
server/filesystem/linn/LinnFileSystem.cpp