FreeNOS: Init Class Reference
Init Class Reference
bin
Initialize system processes.
#include <Init.h>
Public Member Functions
Init (int argc, char **argv)
Constructor.
virtual ~Init ()
Destructor.
virtual Result exec ()
Execute the application.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
Initialize system processes.
Definition at line 31 of file Init.h.
Constructor & Destructor Documentation
Init()
Init::Init (int argc, char ** argv)
Constructor.
Parameters
argc Argument count
argv Argument values
Definition at line 26 of file Init.cpp.
References Application::parser(), ArgumentParser::registerFlag(), and ArgumentParser::setDescription().
~Init()
Init::~Init () virtual
Destructor.
Definition at line 33 of file Init.cpp.
Member Function Documentation
exec()
Init::Result Init::exec () virtual
Execute the application.
Returns
Result code
Implements Application.
Definition at line 37 of file Init.cpp.
References Application::arguments(), SystemInformation::coreId, errno, ERROR, forkexec(), ArgumentContainer::get(), Application::IOError, NOTICE, strerror(), Application::Success, and ZERO.
The documentation for this class was generated from the following files:
bin/init/Init.h
bin/init/Init.cpp