FreeNOS: ConstHashIterator< K, V > Class Template Reference
ConstHashIterator< K, V > Class Template Reference
lib » libstd
Iterate through a constant (read-only) HashTable.
#include <ConstHashIterator.h>
Public Member Functions
ConstHashIterator (const HashTable< K, V > &hash)
Class constructor.
virtual ~ConstHashIterator ()
Destructor.
virtual void reset ()
Reset the iterator.
virtual bool hasNext () const
Check if there is more to iterate.
virtual bool hasCurrent () const
Check if there is a current item.
virtual const V & current () const
Get the current value (read-only).
virtual const K & key () const
Get the current key.
virtual const V & next ()
Fetch the next item.
virtual void operator++ (int num)
Increment operator.
Public Member Functions inherited from ConstIterator< V >
virtual ~ConstIterator ()
Destructor.
Private Attributes
const HashTable< K, V > & m_hash
Points to the HashTable to iterate.
List< K > m_keys
List of keys to iterate.
ListIterator< K > m_iter
Iterator of keys.
Detailed Description
template<class K, class V>
class ConstHashIterator< K, V >
Iterate through a constant (read-only) HashTable.
Definition at line 39 of file ConstHashIterator.h.
Constructor & Destructor Documentation
ConstHashIterator()
template<class K , class V > ConstHashIterator< K, V >::ConstHashIterator (const HashTable< K, V > & hash) inline
Class constructor.
Parameters
hash Reference to the HashTable to iterate.
Definition at line 48 of file ConstHashIterator.h.
References assertRead.
~ConstHashIterator()
template<class K , class V > virtual ConstHashIterator< K, V >::~ConstHashIterator () inline virtual
Destructor.
Definition at line 57 of file ConstHashIterator.h.
Member Function Documentation
current()
template<class K , class V > virtual const V& ConstHashIterator< K, V >::current () const inline virtual
Get the current value (read-only).
Returns
Reference to the current read-only value.
Implements ConstIterator< V >.
Definition at line 93 of file ConstHashIterator.h.
References ListIterator< T >::current(), ConstHashIterator< K, V >::m_hash, and ConstHashIterator< K, V >::m_iter.
hasCurrent()
template<class K , class V > virtual bool ConstHashIterator< K, V >::hasCurrent () const inline virtual
Check if there is a current item.
Returns
True if the iterator has a current item, false otherwise.
Implements ConstIterator< V >.
Definition at line 83 of file ConstHashIterator.h.
References ListIterator< T >::hasCurrent(), and ConstHashIterator< K, V >::m_iter.
Referenced by ArgumentParser::getUsage().
hasNext()
template<class K , class V > virtual bool ConstHashIterator< K, V >::hasNext () const inline virtual
Check if there is more to iterate.
Returns
true if more items, false if not.
Implements ConstIterator< V >.
Definition at line 73 of file ConstHashIterator.h.
References ListIterator< T >::hasNext(), and ConstHashIterator< K, V >::m_iter.
key()
template<class K , class V > virtual const K& ConstHashIterator< K, V >::key () const inline virtual
Get the current key.
Returns
Reference to the current key.
Definition at line 103 of file ConstHashIterator.h.
References ListIterator< T >::current(), and ConstHashIterator< K, V >::m_iter.
next()
template<class K , class V > virtual const V& ConstHashIterator< K, V >::next () inline virtual
Fetch the next item.
This function first fetches the next item and then updates the current item pointer to that item.
Returns
Reference to the next item.
Implements ConstIterator< V >.
Definition at line 116 of file ConstHashIterator.h.
References ConstHashIterator< K, V >::m_hash, ConstHashIterator< K, V >::m_iter, and ListIterator< T >::next().
operator++()
template<class K , class V > virtual void ConstHashIterator< K, V >::operator++ (int num) inline virtual
Increment operator.
This function first increment the current item and then updates the next item pointer.
Parameters
num Ignored
Implements ConstIterator< V >.
Definition at line 129 of file ConstHashIterator.h.
References ConstHashIterator< K, V >::m_iter.
reset()
template<class K , class V > virtual void ConstHashIterator< K, V >::reset () inline virtual
Reset the iterator.
Implements ConstIterator< V >.
Definition at line 64 of file ConstHashIterator.h.
References ConstHashIterator< K, V >::m_iter, and ListIterator< T >::reset().
Field Documentation
m_hash
template<class K , class V > const HashTable<K, V>& ConstHashIterator< K, V >::m_hash private
Points to the HashTable to iterate.
Definition at line 137 of file ConstHashIterator.h.
Referenced by ConstHashIterator< K, V >::current(), and ConstHashIterator< K, V >::next().
m_iter
template<class K , class V > ListIterator<K> ConstHashIterator< K, V >::m_iter private
Iterator of keys.
Definition at line 143 of file ConstHashIterator.h.
Referenced by ConstHashIterator< K, V >::current(), ConstHashIterator< K, V >::hasCurrent(), ConstHashIterator< K, V >::hasNext(), ConstHashIterator< K, V >::key(), ConstHashIterator< K, V >::next(), ConstHashIterator< K, V >::operator++(), and ConstHashIterator< K, V >::reset().
m_keys
template<class K , class V > List<K> ConstHashIterator< K, V >::m_keys private
List of keys to iterate.
Definition at line 140 of file ConstHashIterator.h.
The documentation for this class was generated from the following file:
lib/libstd/ConstHashIterator.h