FreeNOS: TAPReporter Class Reference
TAPReporter Class Reference
lib » libtest
Output TestResults in TAP format to stdout.
#include <TAPReporter.h>
Public Member Functions
TAPReporter (int argc, char **argv)
Constructor.
virtual void reportBegin (List< TestInstance *> &tests)
Report start of testing.
virtual void reportBefore (TestInstance &test)
Report start of a test.
virtual void reportAfter (TestInstance &test, TestResult &result)
Report finish of a test.
virtual void reportFinish (List< TestInstance *> &tests)
Report completion of all tests.
Public Member Functions inherited from TestReporter
TestReporter (int argc, char **argv)
Constructor.
virtual ~TestReporter ()
Destructor.
uint getOk () const
Get OK count.
uint getFailed () const
Get fail count.
uint getSkipped () const
Get skip count.
void setReport (bool value)
Set reporting on/off.
void setStatistics (bool value)
Set show statistics on/off.
virtual void prepare (TestInstance &test)
Prepare for next test.
virtual void collect (TestInstance &test, TestResult &result)
Collect test statistics.
virtual void begin (List< TestInstance *> &tests)
Begin testing.
virtual void finish (List< TestInstance *> &tests)
Finish testing.
Private Attributes
uint m_count
Test counter.
Additional Inherited Members
Protected Attributes inherited from TestReporter
int m_argc
Argument count.
char ** m_argv
Argument values.
bool m_report
Report on/off.
bool m_showStatistics
Show final statistics.
uint m_ok
Test statistics.
uint m_fail
uint m_skip
Detailed Description
Output TestResults in TAP format to stdout.
See also
https://testanything.org/tap-specification.html
Definition at line 36 of file TAPReporter.h.
Constructor & Destructor Documentation
TAPReporter()
TAPReporter::TAPReporter (int argc, char ** argv)
Constructor.
Definition at line 23 of file TAPReporter.cpp.
References m_count.
Member Function Documentation
reportAfter()
void TAPReporter::reportAfter (TestInstance & test, TestResult & result) virtual
Report finish of a test.
Implements TestReporter.
Definition at line 38 of file TAPReporter.cpp.
References TestResult::Failure, TestResult::getDescription(), TestInstance::getName(), TestResult::getResult(), m_count, printf(), TestResult::Skipped, and TestResult::Success.
reportBefore()
void TAPReporter::reportBefore (TestInstance & test) virtual
Report start of a test.
Implements TestReporter.
Definition at line 34 of file TAPReporter.cpp.
reportBegin()
void TAPReporter::reportBegin (List< TestInstance *> & tests) virtual
Report start of testing.
Implements TestReporter.
Definition at line 29 of file TAPReporter.cpp.
References List< T >::count(), TestReporter::m_argv, and printf().
reportFinish()
void TAPReporter::reportFinish (List< TestInstance *> & tests) virtual
Report completion of all tests.
Implements TestReporter.
Definition at line 49 of file TAPReporter.cpp.
References TestReporter::m_argv, and printf().
Field Documentation
m_count
uint TAPReporter::m_count private
Test counter.
Definition at line 68 of file TAPReporter.h.
Referenced by reportAfter(), and TAPReporter().
The documentation for this class was generated from the following files:
lib/libtest/TAPReporter.h
lib/libtest/TAPReporter.cpp