FreeNOS: UDP Class Reference
UDP Class Reference
lib » libnet
User Datagram Protocol (UDP)
#include <UDP.h>
Data Structures
struct Header
Packet header format.
Public Types
typedef struct UDP::Header Header
Packet header format.
Public Member Functions
UDP (NetworkServer *server, NetworkDevice *device)
Constructor.
virtual ~UDP ()
Destructor.
void setIP (::IPV4 *ip)
Set IP object.
virtual Error initialize ()
Perform initialization.
UDPSocket * createSocket (String &path)
Creates an UDP socket.
virtual Error process (NetworkQueue::Packet *pkt, Size offset)
Process incoming network packet.
Error bind (UDPSocket *sock, u16 port)
Bind to UDP port.
Error sendPacket (NetworkClient::SocketInfo *info, IOBuffer &buffer, Size size)
Send packet.
Public Member Functions inherited from NetworkProtocol
NetworkProtocol (NetworkServer *server, NetworkDevice *device)
Constructor.
virtual ~NetworkProtocol ()
Destructor.
virtual const Size getMaximumPacketSize () const
Get maximum packet size.
Public Member Functions inherited from Directory
Directory ()
Constructor.
virtual ~Directory ()
Destructor.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read directory entries.
virtual File * lookup (const char *name)
Retrieve a File from storage.
void insert (FileType type, const char *name,...)
Insert a new directory entry.
void remove (const char *name)
Remove a directory entry.
void clear ()
Clears the internal list of entries.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Static Public Member Functions
static const u16 checksum (const IPV4::Header *ip, const Header *header, const Size datalen)
Calculate ICMP checksum.
Static Private Member Functions
static const ulong calculateSum (const u16 *ptr, Size bytes)
Private Attributes
UDPFactory * m_factory
Index< UDPSocket > m_sockets
HashTable< u16, UDPSocket * > m_ports
Maps UDP ports to UDP sockets.
::IPV4 * m_ipv4
Additional Inherited Members
Protected Attributes inherited from NetworkProtocol
NetworkServer * m_server
Network server instance.
NetworkDevice * m_device
Network device instance.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
User Datagram Protocol (UDP)
Definition at line 43 of file UDP.h.
Member Typedef Documentation
Header
typedef struct UDP::Header UDP::Header
Packet header format.
Constructor & Destructor Documentation
UDP()
UDP::UDP (NetworkServer * server, NetworkDevice * device)
Constructor.
Definition at line 24 of file UDP.cpp.
References m_ipv4.
~UDP()
UDP::~UDP () virtual
Destructor.
Definition at line 31 of file UDP.cpp.
Member Function Documentation
bind()
Error UDP::bind (UDPSocket * sock, u16 port)
Bind to UDP port.
Parameters
sock UDP socket
port The port to bind to
Returns
Error code
Definition at line 131 of file UDP.cpp.
References DEBUG, EINVAL, ESUCCESS, HashTable< K, V >::insert(), and m_ports.
Referenced by UDPSocket::write().
calculateSum()
const ulong UDP::calculateSum (const u16 * ptr, Size bytes) static private
Definition at line 142 of file UDP.cpp.
Referenced by checksum().
checksum()
const u16 UDP::checksum (const IPV4::Header * ip, const Header * header, const Size datalen) static
Calculate ICMP checksum.
Parameters
header ICMP header
Returns
ICMP checksum value for the given header
Definition at line 158 of file UDP.cpp.
References calculateSum(), cpu_to_be16, DEBUG, IPV4::Header::destination, IPV4::PseudoHeader::destination, IPV4::PseudoHeader::length, IPV4::PseudoHeader::protocol, IPV4::PseudoHeader::reserved, IPV4::Header::source, IPV4::PseudoHeader::source, and IPV4::UDP.
Referenced by sendPacket().
createSocket()
UDPSocket * UDP::createSocket (String & path)
Creates an UDP socket.
Returns
UDPSocket object instance
Definition at line 49 of file UDP.cpp.
References DEBUG, FileSystem::getMountPath(), Index< T >::insert(), NetworkProtocol::m_server, m_sockets, FileSystem::registerFile(), and ZERO.
Referenced by UDPFactory::read().
initialize()
Error UDP::initialize () virtual
Perform initialization.
Implements NetworkProtocol.
Definition at line 40 of file UDP.cpp.
References DEBUG, ESUCCESS, m_factory, NetworkProtocol::m_server, and FileSystem::registerFile().
Referenced by NetworkDevice::initialize().
process()
Error UDP::process (NetworkQueue::Packet * pkt, Size offset) virtual
Process incoming network packet.
Returns
Error code
Implements NetworkProtocol.
Definition at line 71 of file UDP.cpp.
References be16_to_cpu, NetworkQueue::Packet::data, DEBUG, UDP::Header::destPort, EINVAL, ESUCCESS, HashTable< K, V >::get(), and m_ports.
Referenced by IPV4::process().
sendPacket()
Error UDP::sendPacket (NetworkClient::SocketInfo * info, IOBuffer & buffer, Size size)
Send packet.
Definition at line 89 of file UDP.cpp.
References NetworkClient::SocketInfo::address, UDP::Header::checksum, checksum(), cpu_to_be16, NetworkQueue::Packet::data, DEBUG, UDP::Header::destPort, ESUCCESS, IPV4::getTransmitPacket(), UDP::Header::length, NetworkProtocol::m_device, m_ipv4, NetworkClient::SocketInfo::port, IOBuffer::read(), NetworkQueue::Packet::size, UDP::Header::sourcePort, NetworkDevice::transmit(), and IPV4::UDP.
Referenced by UDPSocket::write().
setIP()
void UDP::setIP (::IPV4 * ip)
Set IP object.
Definition at line 35 of file UDP.cpp.
References m_ipv4.
Referenced by NetworkDevice::initialize().
Field Documentation
m_factory
UDPFactory* UDP::m_factory private
Definition at line 127 of file UDP.h.
Referenced by initialize().
m_ipv4
::IPV4* UDP::m_ipv4 private
Definition at line 134 of file UDP.h.
Referenced by sendPacket(), setIP(), and UDP().
m_ports
HashTable<u16, UDPSocket *> UDP::m_ports private
Maps UDP ports to UDP sockets.
Definition at line 132 of file UDP.h.
Referenced by bind(), and process().
m_sockets
Index<UDPSocket> UDP::m_sockets private
Definition at line 129 of file UDP.h.
Referenced by createSocket().
The documentation for this class was generated from the following files:
lib/libnet/UDP.h
lib/libnet/UDP.cpp