FreeNOS: CoreServer Class Reference
CoreServer Class Reference
server » core
Represents a single Core in a Central Processing Unit (CPU).
#include <CoreServer.h>
Public Types
enum Result {
Success, NotFound, BootError, ExecError,
OutOfMemory, IOError, MemoryError
}
Result codes.
Public Types inherited from ChannelServer< CoreServer, FileSystemMessage >
enum Result
Result codes.
Public Member Functions
CoreServer ()
Class constructor function.
Result initialize ()
Initialize the server.
Result bootCore (uint coreId, CoreInfo *info, ExecutableFormat::Region *regions)
Boot a processor core.
Result discover ()
Discover processor cores.
Result loadKernel ()
Load operating system kernel.
Result bootAll ()
Boot all processor cores.
Result test ()
Run a ping-pong test.
int runCore ()
Routine for the slave processor core.
Public Member Functions inherited from ChannelServer< CoreServer, FileSystemMessage >
ChannelServer (CoreServer *inst, Size num=32)
Constructor function.
virtual ~ChannelServer ()
Destructor function.
int run ()
Enters an infinite loop, serving incoming requests.
void addIPCHandler (Size slot, IPCHandlerFunction h, bool sendReply=true)
Register a new IPC message action handler.
void addIRQHandler (Size slot, IRQHandlerFunction h)
Register a new IRQ message vector handler.
virtual void timeout ()
Called when sleep timeout is reached.
virtual bool retryRequests ()
Retry any pending requests.
void setTimeout (uint msec)
Set a sleep timeout.
Private Member Functions
Result setupChannels ()
Setup communication channels between CoreServers.
Result clearPages (Address addr, Size size)
Clear memory pages with zeroes.
void getCoreCount (FileSystemMessage *msg)
Get and fill the number of processor cores.
void createProcess (FileSystemMessage *msg)
Create a process on the current processor core.
Private Attributes
ExecutableFormat * m_kernel
u8 * m_kernelImage
ExecutableFormat::Region m_regions [16]
Size m_numRegions
Index< CoreInfo > * m_coreInfo
SystemInformation m_info
Index< MemoryChannel > * m_fromSlave
Index< MemoryChannel > * m_toSlave
MemoryChannel * m_toMaster
MemoryChannel * m_fromMaster
Static Private Attributes
static const char * kernelPath = "/boot/kernel"
The default kernel for starting new cores.
Additional Inherited Members
Protected Types inherited from ChannelServer< CoreServer, FileSystemMessage >
typedef void(CoreServer ::* IPCHandlerFunction) (FileSystemMessage *)
Member function pointer inside Base, to handle IPC messages.
typedef void(CoreServer ::* IRQHandlerFunction) (Size)
Member function pointer inside Base, to handle interrupts.
Protected Attributes inherited from ChannelServer< CoreServer, FileSystemMessage >
ChannelRegistry * m_registry
Contains registered channels.
ChannelClient * m_client
Client for sending replies.
MemoryChannel m_kernelEvent
Kernel event channel.
bool m_sendReply
Should we send a reply message?
Vector< MessageHandler< IPCHandlerFunction > *> * m_ipcHandlers
IPC handler functions.
Vector< MessageHandler< IRQHandlerFunction > *> * m_irqHandlers
IRQ handler functions.
CoreServer * m_instance
Server object instance.
ProcessID m_self
ProcessID of ourselves.
Timer::Info m_time
System timer value.
Detailed Description
Represents a single Core in a Central Processing Unit (CPU).
Each core in a system will run its own instance of CoreServer. CoreServers will communicate and collaborate together to implement functionality.
Note
Multiprocessor support is only implemented for the Intel architecture
See also
IntelMP
Definition at line 58 of file CoreServer.h.
Member Enumeration Documentation
Result
enum CoreServer::Result
Result codes.
Enumerator
Success
NotFound
BootError
ExecError
OutOfMemory
IOError
MemoryError
Definition at line 70 of file CoreServer.h.
Constructor & Destructor Documentation
CoreServer()
CoreServer::CoreServer ()
Class constructor function.
Definition at line 34 of file CoreServer.cpp.
References ChannelServer< CoreServer, FileSystemMessage >::addIPCHandler(), createProcess(), getCoreCount(), m_coreInfo, m_fromMaster, m_fromSlave, m_kernel, m_kernelImage, m_numRegions, m_toMaster, m_toSlave, ReadFile, and ZERO.
Member Function Documentation
bootAll()
CoreServer::Result CoreServer::bootAll ()
Boot all processor cores.
Returns
Result code
Definition at line 420 of file CoreServer.cpp.
References bootCore(), List< T >::count(), ERROR, Index< T >::get(), ListIterator< T >::hasCurrent(), m_coreInfo, m_regions, NotFound, and Success.
Referenced by initialize().
bootCore()
CoreServer::Result CoreServer::bootCore (uint coreId, CoreInfo * info, ExecutableFormat::Region * regions)
Boot a processor core.
Parameters
coreId Core identifier number
info CoreInfo pointer containing specific core information
regions Kernel executable memory regions
Returns
Result code
Definition at line 263 of file CoreServer.cpp.
References Memory::Range::access, BootError, CoreInfo::bootImageAddress, SystemInformation::bootImageAddress, CoreInfo::bootImageSize, SystemInformation::bootImageSize, DEBUG, ERROR, kernelPath, m_numRegions, m_regions, Map, CoreInfo::memory, SystemInformation::memoryAvail, MemoryError, NOTICE, OutOfMemory, Memory::Range::phys, Memory::Readable, ReserveMem, SELF, ExecutableFormat::Region::size, Memory::Range::size, CoreManager::Success, API::Success, Success, UnMap, Memory::User, Memory::Range::virt, ExecutableFormat::Region::virt, VMCopy(), VMCtl(), Memory::Writable, and API::Write.
Referenced by bootAll().
clearPages()
CoreServer::Result CoreServer::clearPages (Address addr, Size size) private
Clear memory pages with zeroes.
Parameters
addr Physical memory address to clear
size Number of bytes to clear
Returns
Exit code
Definition at line 444 of file CoreServer.cpp.
References Memory::Range::access, Map, Memory::Range::phys, Memory::Readable, SELF, MemoryBlock::set(), Memory::Range::size, Success, UnMap, Memory::User, Memory::Range::virt, VMCtl(), Memory::Writable, and ZERO.
Referenced by discover().
createProcess()
void CoreServer::createProcess (FileSystemMessage * msg) private
Create a process on the current processor core.
Parameters
msg FileSystemMessage containing process information
Returns
Exit code
Definition at line 83 of file CoreServer.cpp.
References Memory::Range::access, FileSystemMessage::buffer, SystemInformation::coreId, DEBUG, EBADF, ERROR, ESUCCESS, FileSystemMessage::from, Index< T >::get(), Singleton< ChannelClient >::instance, LookupVirtual, m_fromSlave, m_info, m_toMaster, m_toSlave, Map, FileSystemMessage::offset, FileSystemMessage::path, Memory::Range::phys, MemoryChannel::read(), Memory::Readable, API::ReadPhys, FileSystemMessage::result, SELF, Memory::Range::size, FileSystemMessage::size, spawn(), Channel::Success, ChannelClient::syncSendTo(), Memory::User, Memory::Range::virt, VMCopy(), VMCtl(), waitpid(), and MemoryChannel::write().
Referenced by CoreServer().
discover()
CoreServer::Result CoreServer::discover ()
Discover processor cores.
Returns
Result code
Definition at line 349 of file CoreServer.cpp.
References CoreInfo::bootImageAddress, CoreInfo::bootImageSize, SystemInformation::bootImageSize, clearPages(), CoreInfo::coreChannelAddress, CoreInfo::coreChannelSize, CoreInfo::coreId, List< T >::count(), ExecutableFormat::entry(), ERROR, ListIterator< T >::hasCurrent(), Index< T >::insert(), CoreInfo::kernel, KERNEL_PATHLEN, CoreInfo::kernelCommand, CoreInfo::kernelEntry, kernelPath, m_coreInfo, m_kernel, MegaByte, CoreInfo::memory, SystemInformation::memorySize, NotFound, NOTICE, PAGESIZE, Memory::Range::phys, MemoryBlock::set(), Memory::Range::size, strlcpy(), CoreManager::Success, Success, CoreInfo::timerCounter, and SystemInformation::timerCounter.
Referenced by initialize().
getCoreCount()
void CoreServer::getCoreCount (FileSystemMessage * msg) private
Get and fill the number of processor cores.
Parameters
msg FileSystemMessage to fill in the core count
Returns
Exit code
Definition at line 152 of file CoreServer.cpp.
References SystemInformation::coreId, DEBUG, EINVAL, ESUCCESS, m_info, FileSystemMessage::result, and FileSystemMessage::size.
Referenced by CoreServer().
initialize()
CoreServer::Result CoreServer::initialize ()
Initialize the server.
Returns
Result code
Definition at line 209 of file CoreServer.cpp.
References bootAll(), SystemInformation::coreId, discover(), loadKernel(), m_info, setupChannels(), and Success.
Referenced by main().
loadKernel()
CoreServer::Result CoreServer::loadKernel ()
Load operating system kernel.
Returns
Result code
Definition at line 229 of file CoreServer.cpp.
References close(), DEBUG, ExecError, ExecutableFormat::find(), IOError, kernelPath, m_kernel, m_kernelImage, m_numRegions, m_regions, O_RDONLY, open(), read(), ExecutableFormat::regions(), stat::st_size, stat(), ExecutableFormat::Success, and Success.
Referenced by initialize().
runCore()
int CoreServer::runCore ()
Routine for the slave processor core.
Returns
Exit code
Definition at line 57 of file CoreServer.cpp.
References FileSystemMessage::action, Vector< T >::at(), SystemInformation::coreId, m_fromMaster, m_info, ChannelServer< CoreServer, FileSystemMessage >::m_ipcHandlers, ChannelServer< CoreServer, FileSystemMessage >::m_sendReply, m_toMaster, MemoryChannel::read(), ChannelServer< CoreServer, FileSystemMessage >::run(), MessageHandler< Func >::sendReply, Channel::Success, and MemoryChannel::write().
Referenced by main().
setupChannels()
CoreServer::Result CoreServer::setupChannels () private
Setup communication channels between CoreServers.
Returns
Exit code
Definition at line 460 of file CoreServer.cpp.
References Channel::Consumer, CoreInfo::coreChannelAddress, SystemInformation::coreChannelAddress, SystemInformation::coreId, coreInfo, Index< T >::get(), Index< T >::insert(), m_coreInfo, m_fromMaster, m_fromSlave, m_toMaster, m_toSlave, PAGESIZE, Channel::Producer, MemoryChannel::setMessageSize(), Channel::setMode(), MemoryChannel::setPhysical(), and Success.
Referenced by initialize().
test()
CoreServer::Result CoreServer::test ()
Run a ping-pong test.
Returns
Result code
Definition at line 172 of file CoreServer.cpp.
References FileSystemMessage::action, SystemInformation::coreId, Index< T >::get(), IOError, m_fromSlave, m_info, m_toMaster, NOTICE, FileSystemMessage::path, MemoryChannel::read(), ChannelMessage::Request, FileSystemMessage::size, StatFile, Channel::Success, Success, ChannelMessage::type, and MemoryChannel::write().
Referenced by main().
Field Documentation
kernelPath
const char * CoreServer::kernelPath = "/boot/kernel" static private
The default kernel for starting new cores.
Definition at line 63 of file CoreServer.h.
Referenced by bootCore(), discover(), and loadKernel().
m_coreInfo
Index<CoreInfo>* CoreServer::m_coreInfo private
Definition at line 193 of file CoreServer.h.
Referenced by bootAll(), CoreServer(), discover(), and setupChannels().
m_fromMaster
MemoryChannel* CoreServer::m_fromMaster private
Definition at line 200 of file CoreServer.h.
Referenced by CoreServer(), runCore(), and setupChannels().
m_fromSlave
Index<MemoryChannel>* CoreServer::m_fromSlave private
Definition at line 196 of file CoreServer.h.
Referenced by CoreServer(), createProcess(), setupChannels(), and test().
m_info
SystemInformation CoreServer::m_info private
Definition at line 194 of file CoreServer.h.
Referenced by createProcess(), getCoreCount(), initialize(), runCore(), and test().
m_kernel
ExecutableFormat* CoreServer::m_kernel private
Definition at line 186 of file CoreServer.h.
Referenced by CoreServer(), discover(), and loadKernel().
m_kernelImage
u8* CoreServer::m_kernelImage private
Definition at line 187 of file CoreServer.h.
Referenced by CoreServer(), and loadKernel().
m_numRegions
Size CoreServer::m_numRegions private
Definition at line 191 of file CoreServer.h.
Referenced by bootCore(), CoreServer(), and loadKernel().
m_regions
ExecutableFormat::Region CoreServer::m_regions[16] private
Definition at line 189 of file CoreServer.h.
Referenced by bootAll(), bootCore(), and loadKernel().
m_toMaster
MemoryChannel* CoreServer::m_toMaster private
Definition at line 199 of file CoreServer.h.
Referenced by CoreServer(), createProcess(), runCore(), setupChannels(), and test().
m_toSlave
Index<MemoryChannel>* CoreServer::m_toSlave private
Definition at line 197 of file CoreServer.h.
Referenced by CoreServer(), createProcess(), and setupChannels().
The documentation for this class was generated from the following files:
server/core/CoreServer.h
server/core/CoreServer.cpp