FreeNOS: ARMProcess Class Reference
ARMProcess Class Reference
kernel » ARM
ARM specific process implementation.
#include <ARMProcess.h>
Public Member Functions
ARMProcess (ProcessID id, Address entry, bool privileged, const MemoryMap &map)
Constructor function.
virtual ~ARMProcess ()
Destructor function.
void setCpuState (const CPUState *cpuState)
Overwrite the saved CPU registers for this task.
const CPUState * cpuState () const
Retrieve saved CPU state.
virtual Result initialize ()
Initialize the Process.
virtual void execute (Process *previous)
Allow the Process to run on the CPU.
Public Member Functions inherited from Process
Process (ProcessID id, Address entry, bool privileged, const MemoryMap &map)
Constructor function.
virtual ~Process ()
Destructor function.
ProcessID getID () const
Retrieve our ID number.
ProcessID getParent () const
Retrieve our parent ID.
ProcessID getWait () const
Get Wait ID.
const Timer::Info & getSleepTimer () const
Get sleep timer.
ProcessShares & getShares ()
Get process shares.
State getState () const
Retrieves the current state.
Address getPageDirectory () const
Get the address of our page directory.
Address getUserStack () const
Get the address of the user stack.
Address getKernelStack () const
Get the address of the kernel stack.
MemoryContext * getMemoryContext ()
Get MMU memory context.
Result raiseEvent (struct ProcessEvent *event)
Raise kernel event.
bool isPrivileged () const
Get privilege.
void setState (State st)
Puts the Process in a new state.
void setParent (ProcessID id)
Set parent process ID.
void setWait (ProcessID id)
Set Wait ID.
void setSleepTimer (const Timer::Info *sleeptimer)
Set sleep timer.
void setPageDirectory (Address addr)
Set page directory address.
void setUserStack (Address addr)
Sets the address of the user stack.
void setKernelStack (Address addr)
Set the kernel stack address.
bool operator== (Process *proc)
Compare two processes.
Result wakeup ()
Prevent process from sleeping.
Result sleep (Timer::Info *timer=0)
Stops the process for executing until woken up.
Static Public Attributes
static const Size KernelStackSize = PAGESIZE
Size of the kernel stack.
Private Attributes
CPUState m_cpuState
Contains all the CPU registers for this task.
Additional Inherited Members
Public Types inherited from Process
enum Result { Success, MemoryMapError, OutOfMemory, WakeupPending }
enum State {
Running, Ready, Stopped, Sleeping,
Waiting
}
Protected Attributes inherited from Process
const ProcessID m_id
Process Identifier.
ProcessID m_parent
Parent process.
State m_state
Current process status.
ProcessID m_waitId
Waits for exit of this Process.
bool m_privileged
Privilege level.
Address m_entry
Entry point of the program.
MemoryMap m_map
Virtual memory layout.
MemoryContext * m_memoryContext
MMU memory context.
Address m_pageDirectory
Page directory.
Address m_userStack
User stack address.
Address m_kernelStack
Current kernel stack address (changes during execution).
Address m_kernelStackBase
Base kernel stack (fixed)
Size m_wakeups
Number of wakeups received.
Timer::Info m_sleepTimer
Sleep timer value.
ProcessShares m_shares
Contains virtual memory shares between this process and others.
MemoryChannel * m_kernelChannel
Channel for sending kernel events to the Process.
Detailed Description
ARM specific process implementation.
Definition at line 34 of file ARMProcess.h.
Constructor & Destructor Documentation
ARMProcess()
ARMProcess::ARMProcess (ProcessID id, Address entry, bool privileged, const MemoryMap & map)
Constructor function.
Parameters
id Process Identifier
entry Initial program counter value.
privileged If true, the process has unlimited access to hardware.
Definition at line 28 of file ARMProcess.cpp.
~ARMProcess()
ARMProcess::~ARMProcess () virtual
Destructor function.
Definition at line 65 of file ARMProcess.cpp.
Member Function Documentation
cpuState()
const CPUState * ARMProcess::cpuState () const
Retrieve saved CPU state.
Returns
Saved CPUState for this task.
Definition at line 69 of file ARMProcess.cpp.
References m_cpuState.
execute()
void ARMProcess::execute (Process * previous) virtual
Allow the Process to run on the CPU.
Implements Process.
Definition at line 80 of file ARMProcess.cpp.
References MemoryContext::activate(), MemoryBlock::copy(), firstProcess, m_cpuState, Process::m_memoryContext, CPUState::padding, and svcStack.
initialize()
Process::Result ARMProcess::initialize () virtual
Initialize the Process.
Allocates various (architecture specific) resources, creates MMU context and stacks.
Returns
Result code
Reimplemented from Process.
Definition at line 33 of file ARMProcess.cpp.
References Memory::Range::access, CPUState::cpsr, Process::initialize(), Singleton< Kernel >::instance, m_cpuState, Process::m_entry, Process::m_map, Process::m_memoryContext, Process::m_privileged, Process::m_userStack, MemoryContext::mapRange(), MEMALIGN8, Process::MemoryMapError, Process::OutOfMemory, CPUState::pc, Memory::Range::phys, MemoryMap::range(), Memory::Readable, MemoryBlock::set(), Process::setUserStack(), Memory::Range::size, CPUState::sp, MemoryContext::Success, Allocator::Success, SYS_MODE, Memory::User, MemoryMap::UserStack, USR_MODE, Memory::Range::virt, and Memory::Writable.
setCpuState()
void ARMProcess::setCpuState (const CPUState * cpuState)
Overwrite the saved CPU registers for this task.
Parameters
cpuState Pointer to newly saved CPU registers
Definition at line 74 of file ARMProcess.cpp.
References MemoryBlock::copy(), and m_cpuState.
Referenced by ARMKernel::trap().
Field Documentation
KernelStackSize
const Size ARMProcess::KernelStackSize = PAGESIZE static
Size of the kernel stack.
Definition at line 39 of file ARMProcess.h.
m_cpuState
CPUState ARMProcess::m_cpuState private
Contains all the CPU registers for this task.
Definition at line 87 of file ARMProcess.h.
Referenced by cpuState(), execute(), initialize(), and setCpuState().
The documentation for this class was generated from the following files:
kernel/arm/ARMProcess.h
kernel/arm/ARMProcess.cpp