FreeNOS: HelpCommand Class Reference
HelpCommand Class Reference
bin » sh
Prints the help info for all known ShellCommands.
#include <HelpCommand.h>
Public Member Functions
HelpCommand (Shell *shell)
Constructor.
virtual int execute (Size nparams, char **params)
Executes the command.
Public Member Functions inherited from ShellCommand
ShellCommand (const char *name, Size minParams=0)
Constructor.
virtual ~ShellCommand ()
Destructor.
const char * getName () const
Get command name.
const char * getHelp () const
Get command help.
Size getMinimumParams () const
Get the minimum number of parameters required.
Private Attributes
Shell * m_shell
Shell object.
Additional Inherited Members
Protected Attributes inherited from ShellCommand
const char * m_name
Unique name of the command.
const char * m_help
Command help text.
Size m_minParams
Minimum number of parameters required.
Detailed Description
Prints the help info for all known ShellCommands.
Definition at line 37 of file HelpCommand.h.
Constructor & Destructor Documentation
HelpCommand()
HelpCommand::HelpCommand (Shell * shell)
Constructor.
Definition at line 24 of file HelpCommand.cpp.
References ShellCommand::m_help, and m_shell.
Member Function Documentation
execute()
int HelpCommand::execute (Size nparams, char ** params) virtual
Executes the command.
Parameters
nparams Number of parameters given.
params Array of parameters.
Returns
Error code or zero on success.
Implements ShellCommand.
Definition at line 31 of file HelpCommand.cpp.
References Shell::getCommands(), HashIterator< K, V >::hasCurrent(), m_shell, and printf().
Field Documentation
m_shell
Shell* HelpCommand::m_shell private
Shell object.
Definition at line 58 of file HelpCommand.h.
Referenced by execute(), and HelpCommand().
The documentation for this class was generated from the following files:
bin/sh/HelpCommand.h
bin/sh/HelpCommand.cpp