FreeNOS: IO Class Reference
IO Class Reference
lib » libarch
Generic I/O functions.
#include <IO.h>
Public Types
enum Result { Success, MapFailure, OutOfMemory }
Result codes.
Public Member Functions
IO ()
Constructor.
uint getBase () const
Get I/O base offset.
void setBase (uint base)
Set I/O base offset.
Result map (Address phys, Size size=4096, Memory::Access access=Memory::Readable|Memory::Writable|Memory::User)
Map I/O address space.
Result unmap ()
Unmap I/O address space.
Protected Attributes
volatile uint m_base
I/O base offset is added to each I/O address.
Memory::Range m_range
Memory range for performing I/O mappings.
Detailed Description
Generic I/O functions.
Definition at line 35 of file IO.h.
Member Enumeration Documentation
Result
enum IO::Result
Result codes.
Enumerator
Success
MapFailure
OutOfMemory
Definition at line 42 of file IO.h.
Constructor & Destructor Documentation
IO()
IO::IO ()
Constructor.
Definition at line 23 of file IO.cpp.
References m_base.
Referenced by IntelIO::unset().
Member Function Documentation
getBase()
uint IO::getBase () const
Get I/O base offset.
Returns
Base offset to add to each I/O address.
Definition at line 28 of file IO.cpp.
References m_base.
Referenced by IntelMP::discover(), IntelACPI::discover(), MemoryChannel::flush(), and IntelACPI::initialize().
map()
IO::Result IO::map (Address phys, Size size = 4096, Memory::Access access = Memory::Readable | Memory::Writable | Memory::User)
Map I/O address space.
Parameters
phys Physical address for start of the range.
size Size of the I/O address space.
access Memory access flags
Returns
Result code.
Definition at line 38 of file IO.cpp.
References Memory::Range::access, MemoryContext::findFree(), MemoryContext::getCurrent(), isKernel, MemoryMap::KernelPrivate, m_base, m_range, Map, MemoryContext::map(), MapFailure, OutOfMemory, Memory::Range::phys, SELF, Memory::Range::size, Success, MemoryContext::Success, API::Success, Memory::User, Memory::Range::virt, and VMCtl().
Referenced by IntelACPI::discover(), PL011::initialize(), BroadcomGPIO::initialize(), BroadcomSPI::initialize(), BroadcomI2C::initialize(), BroadcomMailbox::initialize(), IntelAPIC::initialize(), SynopsisController::initialize(), IntelACPI::initialize(), IntelACPI::IntelACPI(), IntelMP::IntelMP(), and MemoryChannel::setPhysical().
setBase()
void IO::setBase (uint base)
Set I/O base offset.
Parameters
base Offset to add to each I/O address.
Definition at line 33 of file IO.cpp.
References m_base.
Referenced by ARMIO::ARMIO(), Broadcom2836::Broadcom2836(), IntelAPIC::IntelAPIC(), IntelPIC::IntelPIC(), IntelSerial::IntelSerial(), and MemoryChannel::setVirtual().
unmap()
IO::Result IO::unmap ()
Unmap I/O address space.
Returns
Result code.
Definition at line 68 of file IO.cpp.
References MemoryContext::getCurrent(), isKernel, m_range, MapFailure, SELF, Success, MemoryContext::Success, API::Success, UnMap, MemoryContext::unmapRange(), and VMCtl().
Referenced by IntelACPI::discover().
Field Documentation
m_base
volatile uint IO::m_base protected
I/O base offset is added to each I/O address.
Definition at line 90 of file IO.h.
Referenced by getBase(), IntelIO::inb(), IntelIO::inw(), IO(), map(), IntelIO::outb(), IntelIO::outl(), IntelIO::outw(), IntelIO::read(), ARMIO::read(), setBase(), ARMIO::write(), and IntelIO::write().
m_range
Memory::Range IO::m_range protected
Memory range for performing I/O mappings.
Definition at line 93 of file IO.h.
Referenced by map(), and unmap().
The documentation for this class was generated from the following files:
lib/libarch/IO.h
lib/libarch/IO.cpp