FreeNOS: i8250 Class Reference
i8250 Class Reference
server » serial
i8250 serial UART.
#include <i8250.h>
Public Types
enum Constants {
TRANSMIT = 0, RECEIVE = 0, DIVISORLOW = 0, DIVISORHIGH = 1,
RXREADY = 1, IRQCONTROL = 1, IRQSTATUS = 2, FIFOCONTROL = 2,
LINECONTROL = 3, MODEMCONTROL = 4, LINESTATUS = 5, TXREADY = 0x20,
DLAB = 0x80, BAUDRATE = 9600
}
Constants used to communicate with the UART.
Public Member Functions
i8250 (u16 base, u16 irq)
Constructor function.
virtual Error initialize ()
Initializes the i8250 serial UART.
virtual Error interrupt (Size vector)
Called when an interrupt has been triggered for this device.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read bytes from the i8250.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the device.
Public Member Functions inherited from Device
Device (FileType type)
Constructor.
virtual ~Device ()
Destructor.
virtual const String & getIdentifier () const
Get unique device identifier.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Attributes
u16 base
Base I/O port.
u16 irq
Interrupt vector.
Additional Inherited Members
Protected Attributes inherited from Device
String m_identifier
Unique identifier for this Device.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
i8250 serial UART.
Definition at line 36 of file i8250.h.
Member Enumeration Documentation
Constants
enum i8250::Constants
Constants used to communicate with the UART.
Enumerator
TRANSMIT
RECEIVE
DIVISORLOW
DIVISORHIGH
RXREADY
IRQCONTROL
IRQSTATUS
FIFOCONTROL
LINECONTROL
MODEMCONTROL
LINESTATUS
TXREADY
DLAB
BAUDRATE
Definition at line 43 of file i8250.h.
Constructor & Destructor Documentation
i8250()
i8250::i8250 (u16 base, u16 irq)
Constructor function.
Parameters
base I/O base port.
Definition at line 25 of file i8250.cpp.
References Device::m_identifier.
Member Function Documentation
initialize()
Error i8250::initialize () virtual
Initializes the i8250 serial UART.
Returns
Error status code.
Reimplemented from Device.
Definition at line 31 of file i8250.cpp.
References base, BAUDRATE, DIVISORHIGH, DIVISORLOW, DLAB, ESUCCESS, FIFOCONTROL, INFO, IRQCONTROL, LINECONTROL, MODEMCONTROL, ReadByte(), and WriteByte().
interrupt()
Error i8250::interrupt (Size vector) virtual
Called when an interrupt has been triggered for this device.
Parameters
vector Vector number of the interrupt.
Returns
Error result code.
Reimplemented from Device.
Definition at line 57 of file i8250.cpp.
References EnableIRQ, ESUCCESS, irq, ProcessCtl(), and SELF.
read()
Error i8250::read (IOBuffer & buffer, Size size, Size offset) virtual
Read bytes from the i8250.
Parameters
buffer Buffer to save the read bytes.
size Number of bytes to read.
offset Unused.
Returns
Number of bytes on success and ZERO on failure.
Reimplemented from File.
Definition at line 63 of file i8250.cpp.
References base, IOBuffer::bufferedWrite(), EAGAIN, LINESTATUS, ReadByte(), and RXREADY.
write()
Error i8250::write (IOBuffer & buffer, Size size, Size offset) virtual
Write bytes to the device.
Parameters
buffer Buffer containing bytes to write.
size Number of bytes to write.
offset Unused.
Returns
Number of bytes on success and ZERO on failure.
Reimplemented from File.
Definition at line 78 of file i8250.cpp.
References base, EAGAIN, LINESTATUS, ReadByte(), TXREADY, and WriteByte().
Field Documentation
base
u16 i8250::base private
Base I/O port.
Definition at line 109 of file i8250.h.
Referenced by initialize(), read(), and write().
irq
u16 i8250::irq private
Interrupt vector.
Definition at line 112 of file i8250.h.
Referenced by interrupt().
The documentation for this class was generated from the following files:
server/serial/i8250.h
server/serial/i8250.cpp