FreeNOS: NetPing Class Reference
NetPing Class Reference
bin
Network ping/pong application.
#include <NetPing.h>
Public Member Functions
NetPing (int argc, char **argv)
Class constructor.
virtual ~NetPing ()
Class destructor.
virtual Result exec ()
Execute the application event loop.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Private Member Functions
Result arpPing (const char *dev, const char *host)
Send ARP ping/pong.
Result icmpPing (const char *dev, const char *host)
Send ICMP ping/pong.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
Network ping/pong application.
Definition at line 33 of file NetPing.h.
Constructor & Destructor Documentation
NetPing()
NetPing::NetPing (int argc, char ** argv)
Class constructor.
Definition at line 52 of file NetPing.cpp.
References Application::parser(), ArgumentParser::registerFlag(), ArgumentParser::registerPositional(), and ArgumentParser::setDescription().
~NetPing()
NetPing::~NetPing () virtual
Class destructor.
Definition at line 62 of file NetPing.cpp.
Member Function Documentation
arpPing()
NetPing::Result NetPing::arpPing (const char * dev, const char * host) private
Send ARP ping/pong.
Definition at line 89 of file NetPing.cpp.
References Ethernet::Address::addr, NetworkClient::ARP, NetworkClient::close(), NetworkClient::createSocket(), DEBUG, errno, ERROR, NetworkClient::initialize(), Application::IOError, printf(), read(), strerror(), Application::Success, NetworkClient::Success, IPV4::toAddress(), and write().
Referenced by exec().
exec()
NetPing::Result NetPing::exec () virtual
Execute the application event loop.
Implements Application.
Definition at line 66 of file NetPing.cpp.
References Application::arguments(), arpPing(), DEBUG, ArgumentContainer::get(), icmpPing(), and Application::Success.
icmpPing()
NetPing::Result NetPing::icmpPing (const char * dev, const char * host) private
Send ICMP ping/pong.
Definition at line 145 of file NetPing.cpp.
References ICMP::Header::checksum, ICMP::checksum(), close(), ICMP::Header::code, NetworkClient::connectSocket(), NetworkClient::createSocket(), DEBUG, ICMP::EchoReply, ICMP::EchoRequest, ERROR, NetworkClient::ICMP, ICMP::Header::id, NetworkClient::initialize(), Application::IOError, printf(), read(), ICMP::Header::sequence, Application::Success, NetworkClient::Success, IPV4::toAddress(), ICMP::Header::type, and write().
Referenced by exec().
The documentation for this class was generated from the following files:
bin/netping/NetPing.h
bin/netping/NetPing.cpp