FreeNOS: Associative< K, V > Class Template Reference
Associative< K, V > Class Template Reference abstract
lib » libstd
Associatives are containers that provide a mapping of keys to values.
#include <Associative.h>
Public Member Functions
virtual bool insert (const K &key, const V &item)
Inserts the given item to the Assocation.
virtual bool append (const K &key, const V &item)
Append the given item to the Association.
virtual int remove (const K &key)
Removes all items associated with the given key.
virtual void clear ()
Removes all items from the Association.
virtual List< K > keys () const =0
Retrieve all keys inside the Association.
virtual List< K > keys (const V &value) const =0
Retrieve list of Keys for the given value.
virtual bool contains (const K &key) const
Check if the given key exists.
virtual List< V > values () const =0
Retrieve all values inside the Association.
virtual List< V > values (const K &key) const =0
Retrieve values for the given key inside the Association.
virtual const V * get (const K &key) const =0
Returns the first value for the given key.
virtual const V & at (const K &key) const =0
Returns a reference to the first value for the given key.
virtual const V value (const K &key, const V defaultValue=V()) const =0
Return the first value for the given key.
virtual int compareTo (const Associative< K, V > &a) const
Compare this instance to another instance.
const V & operator[] (K key) const
Returns the first value for the given key.
Public Member Functions inherited from Container
Container ()
Constructor.
virtual ~Container ()
Destructor.
virtual Size size () const =0
Returns the maximum size of this Container.
virtual Size count () const =0
Returns the number of items inside the Container.
virtual bool isEmpty () const
Check if the Container is empty.
virtual bool reserve (Size size)
Ensure that at least the given size is available.
virtual bool shrink (Size size)
Shrink the container size by the given amount of items.
virtual Size squeeze ()
Try to minimize the memory required in the Container.
virtual bool resize (Size size)
Change the size of the Container.
Public Member Functions inherited from Comparable< Associative< K, V > >
virtual ~Comparable ()
Class destructor.
virtual bool equals (const Associative< K, V > &t) const
Test if an object is equal to an other object.
Detailed Description
template<class K, class V>
class Associative< K, V >
Associatives are containers that provide a mapping of keys to values.
Definition at line 39 of file Associative.h.
Member Function Documentation
append()
template<class K, class V> virtual bool Associative< K, V >::append (const K & key, const V & item) inline virtual
Append the given item to the Association.
Parameters
key The key of the item to insert
item The item to insert
Returns
True on success and false otherwise
Reimplemented in HashTable< K, V >, HashTable< String, Argument *>, HashTable< u16, UDPSocket *>, HashTable< String, ShellCommand *>, HashTable< u32, LinnInode *>, HashTable< IPV4::Address, ARP::ARPCache *>, HashTable< ProcessID, Channel *>, and HashTable< String, FileCache *>.
Definition at line 66 of file Associative.h.
at()
template<class K, class V> virtual const V& Associative< K, V >::at (const K & key) const pure virtual
Returns a reference to the first value for the given key.
This function assumes the key exists.
Parameters
key Key to find.
Returns
Reference to the first value for the key.
Implemented in HashTable< K, V >, HashTable< String, Argument *>, HashTable< u16, UDPSocket *>, HashTable< String, ShellCommand *>, HashTable< u32, LinnInode *>, HashTable< IPV4::Address, ARP::ARPCache *>, HashTable< ProcessID, Channel *>, and HashTable< String, FileCache *>.
Referenced by Associative< String, FileCache * >::contains(), and Associative< String, FileCache * >::operator[]().
clear()
template<class K, class V> virtual void Associative< K, V >::clear () inline virtual
Removes all items from the Association.
Implements Container.
Definition at line 86 of file Associative.h.
compareTo()
template<class K, class V> virtual int Associative< K, V >::compareTo (const Associative< K, V > & a) const inline virtual
Compare this instance to another instance.
Parameters
a Other instance to compare to
Returns
Zero if equal, non-zero otherwise
Implements Comparable< Associative< K, V > >.
Definition at line 169 of file Associative.h.
contains()
template<class K, class V> virtual bool Associative< K, V >::contains (const K & key) const inline virtual
Check if the given key exists.
Returns
True if exists, false otherwise.
Definition at line 111 of file Associative.h.
Referenced by FileSystem::findFileCache(), LinnFileSystem::getInode(), and FileSystem::lookupFile().
get()
template<class K, class V> virtual const V* Associative< K, V >::get (const K & key) const pure virtual
Returns the first value for the given key.
Parameters
key Key to find.
Returns
Pointer to the first value for the given key or ZERO if not found.
Implemented in HashTable< K, V >, HashTable< String, Argument *>, HashTable< u16, UDPSocket *>, HashTable< String, ShellCommand *>, HashTable< u32, LinnInode *>, HashTable< IPV4::Address, ARP::ARPCache *>, HashTable< ProcessID, Channel *>, and HashTable< String, FileCache *>.
insert()
template<class K, class V> virtual bool Associative< K, V >::insert (const K & key, const V & item) inline virtual
Inserts the given item to the Assocation.
If an item exists for the given key, its value will be replaced.
Parameters
key The key of the item to insert
item The item to insert
Returns
bool Whether inserting the item at the given position succeeded.
Reimplemented in HashTable< K, V >, HashTable< String, Argument *>, HashTable< u16, UDPSocket *>, HashTable< String, ShellCommand *>, HashTable< u32, LinnInode *>, HashTable< IPV4::Address, ARP::ARPCache *>, HashTable< ProcessID, Channel *>, and HashTable< String, FileCache *>.
Definition at line 53 of file Associative.h.
keys() [1/2]
template<class K, class V> virtual List<K> Associative< K, V >::keys () const pure virtual
Retrieve all keys inside the Association.
Returns
A List of keys.
Implemented in HashTable< K, V >, HashTable< String, Argument *>, HashTable< u16, UDPSocket *>, HashTable< String, ShellCommand *>, HashTable< u32, LinnInode *>, HashTable< IPV4::Address, ARP::ARPCache *>, HashTable< ProcessID, Channel *>, and HashTable< String, FileCache *>.
Referenced by Associative< String, FileCache * >::clear().
keys() [2/2]
template<class K, class V> virtual List<K> Associative< K, V >::keys (const V & value) const pure virtual
Retrieve list of Keys for the given value.
Implemented in HashTable< K, V >, HashTable< String, Argument *>, HashTable< u16, UDPSocket *>, HashTable< String, ShellCommand *>, HashTable< u32, LinnInode *>, HashTable< IPV4::Address, ARP::ARPCache *>, HashTable< ProcessID, Channel *>, and HashTable< String, FileCache *>.
operator[]()
template<class K, class V> const V& Associative< K, V >::operator[] (K key) const inline
Returns the first value for the given key.
If there are multiple values for the key, the first value is returned.
Parameters
key The key of the item to return.
Returns
The first value for the key.
Definition at line 201 of file Associative.h.
remove()
template<class K, class V> virtual int Associative< K, V >::remove (const K & key) inline virtual
Removes all items associated with the given key.
Parameters
key The key to remove items for.
Returns
Number of items removed associated with the key.
Reimplemented in HashTable< K, V >, HashTable< String, Argument *>, HashTable< u16, UDPSocket *>, HashTable< String, ShellCommand *>, HashTable< u32, LinnInode *>, HashTable< IPV4::Address, ARP::ARPCache *>, HashTable< ProcessID, Channel *>, and HashTable< String, FileCache *>.
Definition at line 78 of file Associative.h.
value()
template<class K, class V> virtual const V Associative< K, V >::value (const K & key, const V defaultValue = V()) const pure virtual
Return the first value for the given key.
If the key is not found, the default value is returned.
Parameters
key Key to find value for
defaultValue Return this default value if not found
Returns
First value for the given key, or the defaultValue.
Implemented in HashTable< K, V >, HashTable< String, Argument *>, HashTable< u16, UDPSocket *>, HashTable< String, ShellCommand *>, HashTable< u32, LinnInode *>, HashTable< IPV4::Address, ARP::ARPCache *>, HashTable< ProcessID, Channel *>, and HashTable< String, FileCache *>.
Referenced by Associative< String, FileCache * >::clear(), and Associative< String, FileCache * >::contains().
values() [1/2]
template<class K, class V> virtual List<V> Associative< K, V >::values () const pure virtual
Retrieve all values inside the Association.
Returns
A List of values.
Implemented in HashTable< K, V >, HashTable< String, Argument *>, HashTable< u16, UDPSocket *>, HashTable< String, ShellCommand *>, HashTable< u32, LinnInode *>, HashTable< IPV4::Address, ARP::ARPCache *>, HashTable< ProcessID, Channel *>, and HashTable< String, FileCache *>.
Referenced by Associative< String, FileCache * >::compareTo(), and Associative< String, FileCache * >::contains().
values() [2/2]
template<class K, class V> virtual List<V> Associative< K, V >::values (const K & key) const pure virtual
Retrieve values for the given key inside the Association.
Returns
A List of values.
Implemented in HashTable< K, V >, HashTable< String, Argument *>, HashTable< u16, UDPSocket *>, HashTable< String, ShellCommand *>, HashTable< u32, LinnInode *>, HashTable< IPV4::Address, ARP::ARPCache *>, HashTable< ProcessID, Channel *>, and HashTable< String, FileCache *>.
The documentation for this class was generated from the following file:
lib/libstd/Associative.h