FreeNOS: Sequence< T > Class Template Reference
Sequence< T > Class Template Reference abstract
lib » libstd
Sequences are containers that provide indexed based storage of items.
#include <Sequence.h>
Public Member Functions
virtual int insert (const T &item)
Adds the given item to the Sequence, if possible.
virtual bool insert (Size position, const T &item)
Inserts the given item at the given position.
virtual void fill (T value)
Fill the Sequence with the given value.
virtual int remove (T value)
Remove all items with the given value.
virtual bool removeAt (Size position)
Removes the item at the given position.
virtual void clear ()
Removes all items from the Sequence.
virtual const T * get (Size position) const =0
Returns the item at the given position.
virtual const T & at (Size position) const =0
Returns a reference to the item at the given position.
virtual bool contains (const T value) const
Check if the given item is stored in this Sequence.
virtual int compareTo (const Sequence< T > &s) const
Compare this Sequence to another Sequence.
const T & operator[] (int i) const
Returns the item at the given position in the Sequence.
const T & operator[] (Size i) const
Returns the item at the given position in the Sequence.
T & operator[] (int i)
Returns the item at the given position in the Sequence.
T & operator[] (Size i)
Returns the item at the given position in the Sequence.
Public Member Functions inherited from Container
Container ()
Constructor.
virtual ~Container ()
Destructor.
virtual Size size () const =0
Returns the maximum size of this Container.
virtual Size count () const =0
Returns the number of items inside the Container.
virtual bool isEmpty () const
Check if the Container is empty.
virtual bool reserve (Size size)
Ensure that at least the given size is available.
virtual bool shrink (Size size)
Shrink the container size by the given amount of items.
virtual Size squeeze ()
Try to minimize the memory required in the Container.
virtual bool resize (Size size)
Change the size of the Container.
Public Member Functions inherited from Comparable< Sequence< T > >
virtual ~Comparable ()
Class destructor.
virtual bool equals (const Sequence< T > &t) const
Test if an object is equal to an other object.
Detailed Description
template<class T>
class Sequence< T >
Sequences are containers that provide indexed based storage of items.
Definition at line 37 of file Sequence.h.
Member Function Documentation
at()
template<class T> virtual const T& Sequence< T >::at (Size position) const pure virtual
Returns a reference to the item at the given position.
Parameters
position Valid index inside this array.
Returns
Reference to the item at the given position
Note
Position must be a valid index.
Implemented in List< T >, List< Dirent *>, List< InterruptHook *>, List< FileSystemRequest *>, List< Device *>, List< TestInstance *>, List< String *>, List< HashTable::Bucket >, List< uint >, List< K >, List< ATADrive *>, Index< T >, Index< NetworkQueue::Packet >, Index< MemoryChannel >, Index< ProcessShares::MemoryShare >, Index< USBDescriptor::Endpoint >, Index< UDPSocket >, Index< USBDescriptor::String >, Index< ChannelClient::Request >, Index< ICMPSocket >, Index< USBDescriptor::Interface >, Index< CoreInfo >, Index< SynopsisChannel >, String, Vector< T >, Vector< LinnGroup *>, Vector< Argument *>, Vector< Size >, Vector< MessageHandler< IPCHandlerFunction > *>, Vector< Process *>, Vector< List< InterruptHook *> *>, Vector< MessageHandler< IRQHandlerFunction > *>, Vector< Device *>, Vector< List< Device *> *>, Vector< Handler *>, Vector< List< HashTable::Bucket > >, Array< T, N >, and Array< u8, 128 >.
Referenced by Sequence< ATADrive * >::clear(), Sequence< ATADrive * >::compareTo(), Sequence< ATADrive * >::contains(), and Sequence< ATADrive * >::operator[]().
clear()
template<class T> virtual void Sequence< T >::clear () inline virtual
Removes all items from the Sequence.
Implements Container.
Reimplemented in List< T >, List< Dirent *>, List< InterruptHook *>, List< FileSystemRequest *>, List< Device *>, List< TestInstance *>, List< String *>, List< HashTable::Bucket >, List< uint >, List< K >, List< ATADrive *>, Vector< T >, Vector< LinnGroup *>, Vector< Argument *>, Vector< Size >, Vector< MessageHandler< IPCHandlerFunction > *>, Vector< Process *>, Vector< List< InterruptHook *> *>, Vector< MessageHandler< IRQHandlerFunction > *>, Vector< Device *>, Vector< List< Device *> *>, Vector< Handler *>, and Vector< List< HashTable::Bucket > >.
Definition at line 108 of file Sequence.h.
compareTo()
template<class T> virtual int Sequence< T >::compareTo (const Sequence< T > & s) const inline virtual
Compare this Sequence to another Sequence.
Implements Comparable< Sequence< T > >.
Definition at line 153 of file Sequence.h.
contains()
template<class T> virtual bool Sequence< T >::contains (const T value) const inline virtual
Check if the given item is stored in this Sequence.
Reimplemented in List< T >, List< Dirent *>, List< InterruptHook *>, List< FileSystemRequest *>, List< Device *>, List< TestInstance *>, List< String *>, List< HashTable::Bucket >, List< uint >, List< K >, List< ATADrive *>, and String.
Definition at line 139 of file Sequence.h.
fill()
template<class T> virtual void Sequence< T >::fill (T value) inline virtual
Fill the Sequence with the given value.
Parameters
value New value to fill the Sequence.
Reimplemented in Index< T >, Index< NetworkQueue::Packet >, Index< MemoryChannel >, Index< ProcessShares::MemoryShare >, Index< USBDescriptor::Endpoint >, Index< UDPSocket >, Index< USBDescriptor::String >, Index< ChannelClient::Request >, Index< ICMPSocket >, Index< USBDescriptor::Interface >, Index< CoreInfo >, and Index< SynopsisChannel >.
Definition at line 73 of file Sequence.h.
Referenced by API::API(), ChannelServer< FileSystem, FileSystemMessage >::ChannelServer(), DeviceServer::DeviceServer(), Kernel::Kernel(), and LinnFileSystem::LinnFileSystem().
get()
template<class T> virtual const T* Sequence< T >::get (Size position) const pure virtual
Returns the item at the given position.
Parameters
position The position of the item to get.
Returns
Pointer to the item at the given position or ZERO if no item available.
Implemented in List< T >, List< Dirent *>, List< InterruptHook *>, List< FileSystemRequest *>, List< Device *>, List< TestInstance *>, List< String *>, List< HashTable::Bucket >, List< uint >, List< K >, List< ATADrive *>, String, Index< T >, Index< NetworkQueue::Packet >, Index< MemoryChannel >, Index< ProcessShares::MemoryShare >, Index< USBDescriptor::Endpoint >, Index< UDPSocket >, Index< USBDescriptor::String >, Index< ChannelClient::Request >, Index< ICMPSocket >, Index< USBDescriptor::Interface >, Index< CoreInfo >, Index< SynopsisChannel >, Vector< T >, Vector< LinnGroup *>, Vector< Argument *>, Vector< Size >, Vector< MessageHandler< IPCHandlerFunction > *>, Vector< Process *>, Vector< List< InterruptHook *> *>, Vector< MessageHandler< IRQHandlerFunction > *>, Vector< Device *>, Vector< List< Device *> *>, Vector< Handler *>, Vector< List< HashTable::Bucket > >, Array< T, N >, and Array< u8, 128 >.
insert() [1/2]
template<class T> virtual int Sequence< T >::insert (const T & item) inline virtual
Adds the given item to the Sequence, if possible.
Parameters
item The item to add to the Sequence.
Returns
Position of the item in the Sequence or -1 on failure.
Reimplemented in Vector< T >, Vector< LinnGroup *>, Vector< Argument *>, Vector< Size >, Vector< MessageHandler< IPCHandlerFunction > *>, Vector< Process *>, Vector< List< InterruptHook *> *>, Vector< MessageHandler< IRQHandlerFunction > *>, Vector< Device *>, Vector< List< Device *> *>, Vector< Handler *>, Vector< List< HashTable::Bucket > >, Index< T >, Index< NetworkQueue::Packet >, Index< MemoryChannel >, Index< ProcessShares::MemoryShare >, Index< USBDescriptor::Endpoint >, Index< UDPSocket >, Index< USBDescriptor::String >, Index< ChannelClient::Request >, Index< ICMPSocket >, Index< USBDescriptor::Interface >, Index< CoreInfo >, and Index< SynopsisChannel >.
Definition at line 48 of file Sequence.h.
Referenced by Sequence< ATADrive * >::fill().
insert() [2/2]
template<class T> virtual bool Sequence< T >::insert (Size position, const T & item) inline virtual
Inserts the given item at the given position.
If an item exists at the given position, it will be replaced by the given item.
Parameters
position The position to insert the item.
item The item to insert
Returns
bool Whether inserting the item at the given position succeeded.
Reimplemented in Vector< T >, Vector< LinnGroup *>, Vector< Argument *>, Vector< Size >, Vector< MessageHandler< IPCHandlerFunction > *>, Vector< Process *>, Vector< List< InterruptHook *> *>, Vector< MessageHandler< IRQHandlerFunction > *>, Vector< Device *>, Vector< List< Device *> *>, Vector< Handler *>, Vector< List< HashTable::Bucket > >, Index< T >, Index< NetworkQueue::Packet >, Index< MemoryChannel >, Index< ProcessShares::MemoryShare >, Index< USBDescriptor::Endpoint >, Index< UDPSocket >, Index< USBDescriptor::String >, Index< ChannelClient::Request >, Index< ICMPSocket >, Index< USBDescriptor::Interface >, Index< CoreInfo >, Index< SynopsisChannel >, Array< T, N >, and Array< u8, 128 >.
Definition at line 63 of file Sequence.h.
operator[]() [1/4]
template<class T> const T& Sequence< T >::operator[] (int i) const inline
Returns the item at the given position in the Sequence.
Parameters
i The index of the item to return.
Returns
the Item at position i.
Definition at line 184 of file Sequence.h.
operator[]() [2/4]
template<class T> const T& Sequence< T >::operator[] (Size i) const inline
Returns the item at the given position in the Sequence.
Parameters
i The index of the item to return.
Returns
the Item at position i.
Definition at line 196 of file Sequence.h.
operator[]() [3/4]
template<class T> T& Sequence< T >::operator[] (int i) inline
Returns the item at the given position in the Sequence.
Parameters
i The index of the item to return.
Returns
the Item at position i.
Definition at line 208 of file Sequence.h.
operator[]() [4/4]
template<class T> T& Sequence< T >::operator[] (Size i) inline
Returns the item at the given position in the Sequence.
Parameters
i The index of the item to return.
Returns
the Item at position i.
Definition at line 220 of file Sequence.h.
remove()
template<class T> virtual int Sequence< T >::remove (T value) inline virtual
Remove all items with the given value.
Parameters
value Value to remove.
Returns
Number of items removed.
Reimplemented in List< T >, List< Dirent *>, List< InterruptHook *>, List< FileSystemRequest *>, List< Device *>, List< TestInstance *>, List< String *>, List< HashTable::Bucket >, List< uint >, List< K >, and List< ATADrive *>.
Definition at line 88 of file Sequence.h.
removeAt()
template<class T> virtual bool Sequence< T >::removeAt (Size position) inline virtual
Removes the item at the given position.
Parameters
position The position of the item to remove.
Returns
bool Whether removing the item succeeded.
Reimplemented in Vector< T >, Vector< LinnGroup *>, Vector< Argument *>, Vector< Size >, Vector< MessageHandler< IPCHandlerFunction > *>, Vector< Process *>, Vector< List< InterruptHook *> *>, Vector< MessageHandler< IRQHandlerFunction > *>, Vector< Device *>, Vector< List< Device *> *>, Vector< Handler *>, and Vector< List< HashTable::Bucket > >.
Definition at line 100 of file Sequence.h.
Referenced by Sequence< ATADrive * >::clear().
The documentation for this class was generated from the following file:
lib/libstd/Sequence.h