FreeNOS: MemoryBlock Class Reference
MemoryBlock Class Reference
lib » libstd
Memory block operations class.
#include <MemoryBlock.h>
Static Public Member Functions
static void * set (void *dest, int ch, unsigned count)
Fill memory with a constant byte.
static Size copy (void *dest, const void *src, Size count)
Copy memory from one place to another.
static Size copy (char *dest, char *src, Size count)
Copy a character string.
static bool compare (void *dest, void *src, Size count)
Compare memory.
static bool compare (const char *p1, const char *p2, Size count=0)
Compare memory.
Detailed Description
Memory block operations class.
Definition at line 34 of file MemoryBlock.h.
Member Function Documentation
compare() [1/2]
static bool MemoryBlock::compare (void * dest, void * src, Size count) static
Compare memory.
Parameters
dest Destination address
src Source address
count Number of bytes to compare
Returns
Zero if equal or non-zero if not equal
compare() [2/2]
bool MemoryBlock::compare (const char * p1, const char * p2, Size count = 0) static
Compare memory.
Parameters
p1 Memory pointer one.
p2 Memory pointer two.
count Number of bytes to compare or zero to continue until a ZERO byte.
Returns
True if equal, false otherwise.
Definition at line 68 of file MemoryBlock.cpp.
References ZERO.
copy() [1/2]
Size MemoryBlock::copy (void * dest, const void * src, Size count) static
Copy memory from one place to another.
Parameters
dest Destination address.
src Source address.
count Number of bytes to copy.
Returns
Number of bytes copied.
Definition at line 32 of file MemoryBlock.cpp.
References sp.
Referenced by ARMInterrupt::ARMInterrupt(), NetSend::arpRequest(), ProcessShares::createShare(), ARMProcess::execute(), Loopback::getAddress(), Ethernet::getAddress(), Ethernet::getTransmitPacket(), ARMKernel::interrupt(), Kernel::loadBootProcess(), ARP::lookupAddress(), multibootToCoreInfo(), String::operator<<(), String::operator=(), UDPSocket::process(), ProcessShares::readShare(), ELF::regions(), String::resize(), ICMP::sendPacket(), ARP::sendReply(), ChannelClient::sendRequest(), ARP::sendRequest(), Loopback::setAddress(), Ethernet::setAddress(), ARMProcess::setCpuState(), ICMPSocket::setReply(), Process::setSleepTimer(), Process::sleep(), String::String(), SystemInfoHandler(), ARMKernel::trap(), String::trim(), TestChar< T >::unique(), ARP::updateCacheEntry(), VMCopyHandler(), and NetworkClient::writeSocketInfo().
copy() [2/2]
Size MemoryBlock::copy (char * dest, char * src, Size count) static
Copy a character string.
Parameters
dest Destination string.
src Source string.
count Number of bytes to copy.
Returns
Number of bytes copied
Definition at line 43 of file MemoryBlock.cpp.
set()
void * MemoryBlock::set (void * dest, int ch, unsigned count) static
Fill memory with a constant byte.
Parameters
dest Memory to write to.
ch Constant byte.
Returns
Pointer to dest.
Definition at line 21 of file MemoryBlock.cpp.
Referenced by PageAllocator::allocate(), ARMMap::ARMMap(), ARMPaging::ARMPaging(), NetSend::arpRequest(), ARPSocket::ARPSocket(), BitArray::clear(), clearBSS(), CoreServer::clearPages(), ProcessShares::createShare(), CoreServer::discover(), Kernel::heap(), ICMPSocket::ICMPSocket(), IntelProcess::initialize(), ARMProcess::initialize(), Process::initialize(), ARP::insertCacheEntry(), IntelKernel::IntelKernel(), IntelMap::IntelMap(), IntelPaging::IntelPaging(), Kernel::Kernel(), kernel_main(), Kernel::loadBootProcess(), ARMFirstTable::map(), IntelPageDirectory::map(), MemoryChannel::MemoryChannel(), MPI_Init(), multibootToCoreInfo(), PoolAllocator::newPool(), String::pad(), PoolAllocator::PoolAllocator(), Process::Process(), refreshMounts(), ARP::sendRequest(), Timer::Timer(), USBDevice::USBDevice(), and Process::wakeup().
The documentation for this class was generated from the following files:
lib/libstd/MemoryBlock.h
lib/libstd/MemoryBlock.cpp