FreeNOS: ProcessManager Class Reference
ProcessManager Class Reference
kernel
Represents a process which may run on the host.
#include <ProcessManager.h>
Public Member Functions
ProcessManager (Scheduler *scheduler)
Constructor function.
virtual ~ProcessManager ()
Destructor function.
Scheduler * getScheduler ()
Get scheduler object.
Process * create (Address entry, const MemoryMap &map)
Create and add a new Process.
Process * get (ProcessID id)
Retrieve a Process by it's ID.
void remove (Process *proc, uint exitStatus=0)
Remove a Process.
Process * schedule (Process *proc=ZERO)
Schedule next process to run.
void setIdle (Process *proc)
Set the idle process.
Process * current ()
Current process running.
Process * previous ()
Get the previous process running.
Vector< Process * > * getProcessTable ()
Retrieve the process table.
Private Attributes
Vector< Process * > m_procs
All known Processes.
Scheduler * m_scheduler
Object which selects processes to run.
Process * m_current
Currently executing process.
Process * m_previous
Previous process executing.
Process * m_idle
Idle process.
Detailed Description
Represents a process which may run on the host.
Definition at line 37 of file ProcessManager.h.
Constructor & Destructor Documentation
ProcessManager()
ProcessManager::ProcessManager (Scheduler * scheduler)
Constructor function.
Definition at line 22 of file ProcessManager.cpp.
References DEBUG, m_current, m_idle, m_previous, m_scheduler, MAX_PROCS, and ZERO.
~ProcessManager()
ProcessManager::~ProcessManager () virtual
Destructor function.
Definition at line 32 of file ProcessManager.cpp.
Member Function Documentation
create()
Process * ProcessManager::create (Address entry, const MemoryMap & map)
Create and add a new Process.
Definition at line 41 of file ProcessManager.cpp.
References Vector< T >::count(), Process::initialize(), Vector< T >::insert(), m_procs, Process::Success, and ZERO.
Referenced by Kernel::loadBootProcess(), and ProcessCtlHandler().
current()
Process * ProcessManager::current ()
Current process running.
NULL if no process running yet.
Returns
Process pointer
Definition at line 125 of file ProcessManager.cpp.
References m_current.
Referenced by IntelKernel::exception(), Kernel::getMemoryContext(), ARMKernel::interrupt(), PrivExecHandler(), ProcessCtlHandler(), ARMKernel::trap(), VMCopyHandler(), VMCtlHandler(), and VMShareHandler().
get()
Process * ProcessManager::get (ProcessID id)
Retrieve a Process by it's ID.
Parameters
id ProcessID number.
Returns
Pointer to the appropriate process or ZERO if not found.
Definition at line 54 of file ProcessManager.cpp.
References Vector< T >::get(), m_procs, and ZERO.
Referenced by ProcessShares::createShare(), ProcessCtlHandler(), ProcessShares::releaseShare(), ARMKernel::trap(), VMCopyHandler(), VMCtlHandler(), VMShareHandler(), and ProcessShares::~ProcessShares().
getProcessTable()
Vector< Process * > * ProcessManager::getProcessTable ()
Retrieve the process table.
Returns
Pointer to the process table.
Definition at line 140 of file ProcessManager.cpp.
References m_procs.
getScheduler()
Scheduler * ProcessManager::getScheduler ()
Get scheduler object.
Returns
Scheduler object instance
Definition at line 36 of file ProcessManager.cpp.
References m_scheduler.
Referenced by Kernel::run().
previous()
Process * ProcessManager::previous ()
Get the previous process running.
Returns
Process pointer
Definition at line 130 of file ProcessManager.cpp.
References m_previous.
remove()
void ProcessManager::remove (Process * proc, uint exitStatus = 0)
Remove a Process.
Definition at line 60 of file ProcessManager.cpp.
References Process::getID(), m_current, m_idle, m_previous, m_procs, Process::Ready, Vector< T >::size(), Process::Waiting, and ZERO.
Referenced by IntelKernel::exception(), and ProcessCtlHandler().
schedule()
Process * ProcessManager::schedule (Process * proc = ZERO)
Schedule next process to run.
Returns
Pointer to newly scheduled Process or NULL if unchanged
Definition at line 92 of file ProcessManager.cpp.
References Process::execute(), FATAL, Process::getState(), m_current, m_idle, m_previous, m_procs, m_scheduler, NULL, Process::Ready, Process::Running, Scheduler::select(), and Process::setState().
Referenced by IntelKernel::clocktick(), IntelKernel::exception(), ARMKernel::interrupt(), ProcessCtlHandler(), and Kernel::run().
setIdle()
void ProcessManager::setIdle (Process * proc)
Set the idle process.
Definition at line 135 of file ProcessManager.cpp.
References m_idle.
Referenced by PrivExecHandler().
Field Documentation
m_current
Process* ProcessManager::m_current private
Currently executing process.
Definition at line 119 of file ProcessManager.h.
Referenced by current(), ProcessManager(), remove(), and schedule().
m_idle
Process* ProcessManager::m_idle private
Idle process.
Definition at line 125 of file ProcessManager.h.
Referenced by ProcessManager(), remove(), schedule(), and setIdle().
m_previous
Process* ProcessManager::m_previous private
Previous process executing.
Definition at line 122 of file ProcessManager.h.
Referenced by previous(), ProcessManager(), remove(), and schedule().
m_procs
Vector<Process *> ProcessManager::m_procs private
All known Processes.
Definition at line 113 of file ProcessManager.h.
Referenced by create(), get(), getProcessTable(), remove(), and schedule().
m_scheduler
Scheduler* ProcessManager::m_scheduler private
Object which selects processes to run.
Definition at line 116 of file ProcessManager.h.
Referenced by getScheduler(), ProcessManager(), and schedule().
The documentation for this class was generated from the following files:
kernel/ProcessManager.h
kernel/ProcessManager.cpp