FreeNOS: VGA Class Reference
VGA Class Reference
server » video
Video Graphics Array (VGA) support.
#include <VGA.h>
Public Member Functions
VGA (Size width=80, Size height=25)
Class constructor function.
virtual Error initialize ()
Initializes the VGA device.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read from VGA video memory.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write to VGA video memory.
Public Member Functions inherited from Device
Device (FileType type)
Constructor.
virtual ~Device ()
Destructor.
virtual const String & getIdentifier () const
Get unique device identifier.
virtual Error interrupt (Size vector)
Called when an interrupt has been triggered for this device.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Attributes
u16 * vga
VGA video memory address.
Size width
Number of characters horizontally.
Size height
Number of characters vertically.
Additional Inherited Members
Protected Attributes inherited from Device
String m_identifier
Unique identifier for this Device.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
Video Graphics Array (VGA) support.
This class implements a VGA driver. Applications may read and write from the /dev/vga0 device file to retrieve and modify the current screen. Currently the Terminal driver uses the /dev/vga device file to implement the system console in FreeNOS.
See also
Terminal
Definition at line 93 of file VGA.h.
Constructor & Destructor Documentation
VGA()
VGA::VGA (Size width = 80, Size height = 25)
Class constructor function.
Parameters
width Number of characters horizontally.
height Number of characters vertically.
Definition at line 23 of file VGA.cpp.
References Device::m_identifier.
Member Function Documentation
initialize()
Error VGA::initialize () virtual
Initializes the VGA device.
First this function maps the VGA video memory into our address space. It clears the screen and finally disables the VGA hardware cursor.
Returns
Error status code.
Reimplemented from Device.
Definition at line 28 of file VGA.cpp.
References Memory::Range::access, BLACK, ESUCCESS, height, LIGHTGREY, Map, PAGESIZE, Memory::Range::phys, Memory::Readable, SELF, Memory::Range::size, Memory::User, vga, VGA_CHAR, VGA_IOADDR, VGA_IODATA, VGA_PADDR, Memory::Range::virt, VMCtl(), width, Memory::Writable, WriteByte(), and ZERO.
read()
Error VGA::read (IOBuffer & buffer, Size size, Size offset) virtual
Read from VGA video memory.
This function copies bytes directly from VGA video memory into the target buffer.
Parameters
buffer Output buffer.
size Number of bytes to copy into the buffer.
offset Offset in VGA video memory to read in bytes.
Returns
An error code describing the status of the operation.
Reimplemented from File.
Definition at line 58 of file VGA.cpp.
References EFAULT, height, vga, width, and IOBuffer::write().
write()
Error VGA::write (IOBuffer & buffer, Size size, Size offset) virtual
Write to VGA video memory.
This function copies bytes directly into VGA video memory from the source buffer.
Parameters
buffer Input buffer.
size Number of bytes to copy from the buffer.
offset Offset in VGA video memory to write in bytes.
Returns
An error code describing the status of the operation.
Reimplemented from File.
Definition at line 68 of file VGA.cpp.
References EFAULT, IOBuffer::getBuffer(), height, memcpy(), vga, and width.
Field Documentation
height
Size VGA::height private
Number of characters vertically.
Definition at line 153 of file VGA.h.
Referenced by initialize(), read(), and write().
vga
u16* VGA::vga private
VGA video memory address.
Definition at line 147 of file VGA.h.
Referenced by initialize(), read(), and write().
width
Size VGA::width private
Number of characters horizontally.
Definition at line 150 of file VGA.h.
Referenced by initialize(), read(), and write().
The documentation for this class was generated from the following files:
server/video/VGA.h
server/video/VGA.cpp