FreeNOS: IPV4 Class Reference
IPV4 Class Reference
lib » libnet
Internet Protocol Version 4.
#include <IPV4.h>
Data Structures
struct Header
IP network packet header.
struct PseudoHeader
Pseudo Header.
Public Types
enum Protocol { ICMP = 1, IGMP = 2, UDP = 17, TCP = 6 }
Protocol types.
typedef u32 Address
IP-address.
typedef struct IPV4::Header Header
IP network packet header.
typedef struct IPV4::PseudoHeader PseudoHeader
Pseudo Header.
Public Member Functions
IPV4 (NetworkServer *server, NetworkDevice *device)
Constructor.
virtual ~IPV4 ()
Destructor.
virtual Error initialize ()
Perform initialization.
void setICMP (::ICMP *icmp)
Set ICMP instance.
void setARP (::ARP *arp)
void setUDP (::UDP *udp)
void setEthernet (::Ethernet *ether)
virtual Error getAddress (Address *address)
Get current IP address.
virtual Error setAddress (Address *address)
Set current IP address.
Error getTransmitPacket (NetworkQueue::Packet **pkt, Address destination, Protocol type, Size size)
Get a new packet for transmission.
virtual Error process (NetworkQueue::Packet *pkt, Size offset)
Process incoming network packet.
Public Member Functions inherited from NetworkProtocol
NetworkProtocol (NetworkServer *server, NetworkDevice *device)
Constructor.
virtual ~NetworkProtocol ()
Destructor.
virtual const Size getMaximumPacketSize () const
Get maximum packet size.
Public Member Functions inherited from Directory
Directory ()
Constructor.
virtual ~Directory ()
Destructor.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read directory entries.
virtual File * lookup (const char *name)
Retrieve a File from storage.
void insert (FileType type, const char *name,...)
Insert a new directory entry.
void remove (const char *name)
Remove a directory entry.
void clear ()
Clears the internal list of entries.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Static Public Member Functions
static const String toString (Address address)
Convert address to string.
static const Address toAddress (const char *address)
Convert string to IPV4 address.
static const u16 checksum (const void *buffer, Size length)
Calculate IP checksum.
Private Attributes
Address m_address
Current IP address.
::ICMP * m_icmp
ICMP instance.
::ARP * m_arp
ARP instance.
::UDP * m_udp
UDP instance.
::Ethernet * m_ether
Ethernet instance.
u16 m_id
Packet ID for IPV4.
Additional Inherited Members
Protected Attributes inherited from NetworkProtocol
NetworkServer * m_server
Network server instance.
NetworkDevice * m_device
Network device instance.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
Internet Protocol Version 4.
Definition at line 41 of file IPV4.h.
Member Typedef Documentation
Address
typedef u32 IPV4::Address
IP-address.
Definition at line 48 of file IPV4.h.
Header
typedef struct IPV4::Header IPV4::Header
IP network packet header.
This header is prepended to every IP packet send on the actual physical link.
PseudoHeader
typedef struct IPV4::PseudoHeader IPV4::PseudoHeader
Pseudo Header.
This header can be used by sub-protocols for checksum calculation (e.g. TCP and UDP).
Member Enumeration Documentation
Protocol
enum IPV4::Protocol
Protocol types.
Enumerator
ICMP
IGMP
UDP
TCP
Definition at line 53 of file IPV4.h.
Constructor & Destructor Documentation
IPV4()
IPV4::IPV4 (NetworkServer * server, NetworkDevice * device)
Constructor.
Definition at line 29 of file IPV4.cpp.
References m_address, m_ether, m_icmp, m_id, and m_udp.
~IPV4()
IPV4::~IPV4 () virtual
Destructor.
Definition at line 40 of file IPV4.cpp.
Member Function Documentation
checksum()
const u16 IPV4::checksum (const void * buffer, Size length) static
Calculate IP checksum.
Parameters
buffer Input buffer for calculating checksum
length Number of bytes in the buffer
Returns
IP checksum value for the given buffer
Definition at line 156 of file IPV4.cpp.
References be16_to_cpu.
Referenced by ICMP::checksum(), and getTransmitPacket().
getAddress()
Error IPV4::getAddress (IPV4::Address * address) virtual
Get current IP address.
Parameters
address IPV4 address buffer
Returns
Error code
Definition at line 72 of file IPV4.cpp.
References ESUCCESS, and m_address.
Referenced by ARP::process(), IPV4Address::read(), ARP::sendReply(), and ARP::sendRequest().
getTransmitPacket()
Error IPV4::getTransmitPacket (NetworkQueue::Packet ** pkt, IPV4::Address destination, IPV4::Protocol type, Size size)
Get a new packet for transmission.
Parameters
destination
Returns
Error code
Definition at line 119 of file IPV4.cpp.
References IPV4::Header::checksum, checksum(), cpu_to_be16, cpu_to_be32, IPV4::Header::destination, ESUCCESS, IPV4::Header::fragmentOffset, Ethernet::getTransmitPacket(), IPV4::Header::identification, Ethernet::IPV4, IPV4::Header::length, ARP::lookupAddress(), m_address, m_arp, m_ether, m_id, IPV4::Header::protocol, IPV4::Header::source, IPV4::Header::timeToLive, IPV4::Header::typeOfService, and IPV4::Header::versionIHL.
Referenced by UDP::sendPacket(), and ICMP::sendPacket().
initialize()
Error IPV4::initialize () virtual
Perform initialization.
Returns
Error code
Implements NetworkProtocol.
Definition at line 44 of file IPV4.cpp.
References DEBUG, ESUCCESS, NetworkProtocol::m_server, and FileSystem::registerFile().
Referenced by NetworkDevice::initialize().
process()
Error IPV4::process (NetworkQueue::Packet * pkt, Size offset) virtual
Process incoming network packet.
Returns
Error code
Implements NetworkProtocol.
Definition at line 181 of file IPV4.cpp.
References be32_to_cpu, NetworkQueue::Packet::data, DEBUG, IPV4::Header::destination, EINVAL, ERANGE, ICMP, m_address, m_icmp, m_udp, UDP::process(), ICMP::process(), IPV4::Header::protocol, and UDP.
Referenced by Ethernet::process().
setAddress()
Error IPV4::setAddress (IPV4::Address * address) virtual
Set current IP address.
Parameters
address IPV4 address buffer
Returns
Error code
Definition at line 78 of file IPV4.cpp.
References ESUCCESS, and m_address.
Referenced by IPV4Address::write().
setARP()
void IPV4::setARP (::ARP * arp)
Definition at line 62 of file IPV4.cpp.
References m_arp.
Referenced by NetworkDevice::initialize().
setEthernet()
void IPV4::setEthernet (::Ethernet * ether)
Definition at line 57 of file IPV4.cpp.
References m_ether.
Referenced by NetworkDevice::initialize().
setICMP()
void IPV4::setICMP (::ICMP * icmp)
Set ICMP instance.
Parameters
icmp ICMP instance
Definition at line 52 of file IPV4.cpp.
References m_icmp.
Referenced by NetworkDevice::initialize().
setUDP()
void IPV4::setUDP (::UDP * udp)
Definition at line 67 of file IPV4.cpp.
References m_udp.
Referenced by NetworkDevice::initialize().
toAddress()
const IPV4::Address IPV4::toAddress (const char * address) static
Convert string to IPV4 address.
Parameters
address Input textual IP address in dot notation (xxx.xxx.xxx.xxx)
Returns
IPV4::Address or ZERO if not valid
Definition at line 96 of file IPV4.cpp.
References List< T >::count(), ListIterator< T >::hasCurrent(), String::split(), String::toLong(), and ZERO.
Referenced by NetPing::arpPing(), NetPing::icmpPing(), NetCat::initialize(), and IPV4Address::write().
toString()
const String IPV4::toString (Address address) static
Convert address to string.
Parameters
address Input IP address
Returns
Text value of the IP
Definition at line 84 of file IPV4.cpp.
Referenced by IPV4Address::read().
Field Documentation
m_address
Address IPV4::m_address private
Current IP address.
Definition at line 197 of file IPV4.h.
Referenced by getAddress(), getTransmitPacket(), IPV4(), process(), and setAddress().
m_arp
::ARP* IPV4::m_arp private
ARP instance.
Definition at line 203 of file IPV4.h.
Referenced by getTransmitPacket(), and setARP().
m_ether
::Ethernet* IPV4::m_ether private
Ethernet instance.
Definition at line 209 of file IPV4.h.
Referenced by getTransmitPacket(), IPV4(), and setEthernet().
m_icmp
::ICMP* IPV4::m_icmp private
ICMP instance.
Definition at line 200 of file IPV4.h.
Referenced by IPV4(), process(), and setICMP().
m_id
u16 IPV4::m_id private
Packet ID for IPV4.
Definition at line 212 of file IPV4.h.
Referenced by getTransmitPacket(), and IPV4().
m_udp
::UDP* IPV4::m_udp private
UDP instance.
Definition at line 206 of file IPV4.h.
Referenced by IPV4(), process(), and setUDP().
The documentation for this class was generated from the following files:
lib/libnet/IPV4.h
lib/libnet/IPV4.cpp