FreeNOS: IntelSerial Class Reference
IntelSerial Class Reference
kernel » Intel
Intel Serial port debug log class.
#include <IntelSerial.h>
Public Member Functions
IntelSerial (u16 base)
Constructor.
Public Member Functions inherited from Log
Log ()
Constructor.
virtual ~Log ()
Destructor.
Level getMinimumLogLevel ()
Get the minimum logging level.
void setMinimumLogLevel (Level level)
Set the minimum logging level.
void append (const char *str)
Append to buffered output.
void setIdent (const char *ident)
Set log identity.
const char * getIdent () const
Retrieve log identify.
Public Member Functions inherited from Singleton< Log >
Singleton (Log *obj)
Constructor.
Protected Member Functions
virtual void write (const char *str)
Write to the actual output device.
Private Types
enum IntelSerialReg {
TRANSMIT = 0, RECEIVE = 0, DIVISORLOW = 0, DIVISORHIGH = 1,
RXREADY = 1, IRQCONTROL = 1, IRQSTATUS = 2, FIFOCONTROL = 2,
LINECONTROL = 3, MODEMCONTROL = 4, LINESTATUS = 5, TXREADY = 0x20,
DLAB = 0x80, BAUDRATE = 9600
}
Constants used to communicate with the UART.
Private Attributes
IntelIO m_io
I/O instance.
Additional Inherited Members
Public Types inherited from Log
enum Level {
Emergency, Alert, Critical, Error,
Warning, Notice, Info, Debug
}
Logging level values.
Static Public Attributes inherited from Singleton< Log >
static Log * instance
One and only instance.
Detailed Description
Intel Serial port debug log class.
Note
This class is a singleton
Definition at line 39 of file IntelSerial.h.
Member Enumeration Documentation
IntelSerialReg
enum IntelSerial::IntelSerialReg private
Constants used to communicate with the UART.
Enumerator
TRANSMIT
RECEIVE
DIVISORLOW
DIVISORHIGH
RXREADY
IRQCONTROL
IRQSTATUS
FIFOCONTROL
LINECONTROL
MODEMCONTROL
LINESTATUS
TXREADY
DLAB
BAUDRATE
Definition at line 62 of file IntelSerial.h.
Constructor & Destructor Documentation
IntelSerial()
IntelSerial::IntelSerial (u16 base)
Constructor.
Parameters
base I/O base to use
Definition at line 21 of file IntelSerial.cpp.
References BAUDRATE, DIVISORHIGH, DIVISORLOW, DLAB, FIFOCONTROL, IntelIO::inb(), IRQCONTROL, LINECONTROL, m_io, MODEMCONTROL, IntelIO::outb(), and IO::setBase().
Member Function Documentation
write()
void IntelSerial::write (const char * str) protected virtual
Write to the actual output device.
Implements Log.
Definition at line 44 of file IntelSerial.cpp.
References IntelIO::inb(), LINESTATUS, m_io, IntelIO::outb(), TRANSMIT, and TXREADY.
Field Documentation
m_io
IntelIO IntelSerial::m_io private
I/O instance.
Definition at line 83 of file IntelSerial.h.
Referenced by IntelSerial(), and write().
The documentation for this class was generated from the following files:
kernel/intel/IntelSerial.h
kernel/intel/IntelSerial.cpp