FreeNOS: Application Class Reference
Application Class Reference abstract
lib » libstd
Generic application.
#include <Application.h>
Public Types
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Public Member Functions
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Protected Member Functions
virtual Result initialize ()
Initialize the application.
virtual Result exec ()=0
Execute the application event loop.
virtual Result output (const char *string) const =0
Print text to output.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Private Member Functions
void usage () const
Print usage and terminate.
Private Attributes
ArgumentParser m_parser
Program argument parser object.
ArgumentContainer m_arguments
Parsed Arguments.
int m_argc
Input argument count.
char ** m_argv
Input argument values.
String m_version
Program version.
Static Private Attributes
static const uint ExitSuccess = 0
Exit code for successful termination.
static const uint ExitFailure = 1
Exit code for failure termination.
Detailed Description
Generic application.
Definition at line 38 of file Application.h.
Member Enumeration Documentation
Result
enum Application::Result
Result codes.
Enumerator
Success
NotFound
IOError
InvalidArgument
ShowUsage
Definition at line 53 of file Application.h.
Constructor & Destructor Documentation
Application()
Application::Application (int argc, char ** argv)
Class constructor.
Parameters
argc Argument count
argv Argument values
Definition at line 20 of file Application.cpp.
References m_argc, m_argv, m_parser, and ArgumentParser::registerFlag().
~Application()
Application::~Application () virtual
Class destructor.
Definition at line 29 of file Application.cpp.
Member Function Documentation
arguments()
const ArgumentContainer & Application::arguments () const protected
Get program arguments.
Definition at line 110 of file Application.cpp.
References m_arguments.
Referenced by NetSend::arpRequest(), NetPing::exec(), CreateFile::exec(), Init::exec(), SievePrime::exec(), Remove::exec(), Sleep::exec(), MakeNode::exec(), ListFiles::exec(), FileStatus::exec(), UnixName::exec(), Login::exec(), Echo::exec(), Shell::exec(), NetCat::exec(), Cat::exec(), BootImageCreate::exec(), NetCat::initialize(), Cat::initialize(), ListFiles::printFiles(), ListFiles::printSingleFile(), and NetReceive::receivePacket().
exec()
virtual Result Application::exec () protected pure virtual
Execute the application event loop.
Returns
Result code
Implemented in BootImageCreate, Cat, NetCat, NetCtl, Shell, BenchMark, Echo, Hostname, Init, IPCTest, Login, ListFiles, MakeNode, Mount, SievePrime, ProcessList, Remove, Sleep, FileStatus, SysInfo, CreateFile, UnixName, NetPing, NetReceive, and NetSend.
Referenced by run().
initialize()
Application::Result Application::initialize () protected virtual
Initialize the application.
Returns
Result code
Reimplemented in Cat, NetCat, and NetCtl.
Definition at line 33 of file Application.cpp.
References Success.
Referenced by run().
output() [1/2]
virtual Result Application::output (const char * string) const protected pure virtual
Print text to output.
Parameters
string Text to print to program output.
Returns
Result code.
Implemented in BootImageCreate, and POSIXApplication.
Referenced by output(), run(), and usage().
output() [2/2]
Application::Result Application::output (String & string) const protected virtual
Print string to output.
Parameters
string Reference to string to output.
Returns
Result code.
Definition at line 95 of file Application.cpp.
References output().
parser() [1/2]
ArgumentParser & Application::parser () protected
Get program arguments parser.
Returns
Program arguments parser.
Definition at line 100 of file Application.cpp.
References m_parser.
Referenced by BenchMark::BenchMark(), BootImageCreate::BootImageCreate(), Cat::Cat(), Cat::cat(), CreateFile::CreateFile(), Echo::Echo(), BootImageCreate::exec(), FileStatus::FileStatus(), Hostname::Hostname(), Init::Init(), IPCTest::IPCTest(), ListFiles::ListFiles(), Login::Login(), MakeNode::MakeNode(), Mount::Mount(), NetCat::NetCat(), NetCtl::NetCtl(), NetPing::NetPing(), NetReceive::NetReceive(), NetSend::NetSend(), ProcessList::ProcessList(), BootImageCreate::readBootSymbols(), Remove::Remove(), Shell::Shell(), SievePrime::SievePrime(), Sleep::Sleep(), SysInfo::SysInfo(), and UnixName::UnixName().
parser() [2/2]
const ArgumentParser & Application::parser () const protected
Get constant program arguments parser.
Returns
Program arguments parser.
Definition at line 105 of file Application.cpp.
References m_parser.
run()
int Application::run () virtual
Run the application.
Returns
Exit code
Definition at line 38 of file Application.cpp.
References Log::Debug, exec(), ExitFailure, ExitSuccess, ArgumentContainer::get(), initialize(), Singleton< Log >::instance, m_argc, m_arguments, m_argv, m_parser, m_version, output(), ArgumentParser::parse(), ArgumentParser::setName(), ShowUsage, ArgumentParser::Success, Success, and usage().
Referenced by main().
setVersion()
void Application::setVersion (const String & version) protected
Set program version.
Parameters
version Program version string
Definition at line 115 of file Application.cpp.
References m_version.
Referenced by POSIXApplication::POSIXApplication().
usage()
void Application::usage () const private
Print usage and terminate.
Definition at line 89 of file Application.cpp.
References ArgumentParser::getUsage(), m_parser, and output().
Referenced by run().
Field Documentation
ExitFailure
const uint Application::ExitFailure = 1 static private
Exit code for failure termination.
Definition at line 46 of file Application.h.
Referenced by run().
ExitSuccess
const uint Application::ExitSuccess = 0 static private
Exit code for successful termination.
Definition at line 43 of file Application.h.
Referenced by run().
m_argc
int Application::m_argc private
Input argument count.
Definition at line 161 of file Application.h.
Referenced by Application(), and run().
m_arguments
ArgumentContainer Application::m_arguments private
Parsed Arguments.
Definition at line 158 of file Application.h.
Referenced by arguments(), and run().
m_argv
char** Application::m_argv private
Input argument values.
Definition at line 164 of file Application.h.
Referenced by Application(), and run().
m_parser
ArgumentParser Application::m_parser private
Program argument parser object.
Definition at line 155 of file Application.h.
Referenced by Application(), parser(), run(), and usage().
m_version
String Application::m_version private
Program version.
Definition at line 167 of file Application.h.
Referenced by run(), and setVersion().
The documentation for this class was generated from the following files:
lib/libstd/Application.h
lib/libstd/Application.cpp