FreeNOS: USBDevice Class Reference
USBDevice Class Reference
lib » libusb
USB device class.
#include <USBDevice.h>
Public Member Functions
USBDevice (u8 deviceId, const char *usbPath="/usb")
Constructor.
virtual ~USBDevice ()
Destructor.
virtual Error initialize ()
Initialize the USBDevice.
Public Member Functions inherited from Device
Device (FileType type)
Constructor.
virtual ~Device ()
Destructor.
virtual const String & getIdentifier () const
Get unique device identifier.
virtual Error interrupt (Size vector)
Called when an interrupt has been triggered for this device.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read bytes from the file.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Protected Member Functions
Error getDeviceDescriptor (USBDescriptor::Device *desc, Size size=sizeof(USBDescriptor::Device))
Get device descriptor.
Error getConfigDescriptor (USBDescriptor::Configuration *desc, Size size=sizeof(USBDescriptor::Configuration))
Get configuration descriptor.
Error getInterfaceDescriptor (USBDescriptor::Interface *desc)
Get interface descriptor.
Error getEndpointDescriptor (u8 endpointId, USBDescriptor::Endpoint *desc)
Get endpoint descriptor.
Error setAddress (u8 address)
Set device address.
Error setConfiguration (u8 configId)
Activate a configuration.
Error controlMessage (u8 request, const USBTransfer::Direction direction, const USBTransfer::RequestType type, const USBTransfer::Recipient recipient, u16 value, u16 index, void *buffer, Size size)
Send a control message.
Error transfer (const USBTransfer::Type type, const USBTransfer::Direction direction, Address endpointId, void *buffer, Size size, Size maxPacketSize=0)
Start a synchronous USB transfer.
Error beginTransfer (const USBTransfer::Type type, const USBTransfer::Direction direction, Address endpointId, void *buffer, Size size, Size maxPacketSize=0, CallbackFunction *callback=0)
Start an asynchronous USB transfer.
Error finishTransfer (FileSystemMessage *msg)
Complete asynchronous USB transfer.
Error submit (USBMessage &msg)
Submit a USB transfer to the Host controller.
Protected Attributes
Address m_id
USB device identifier.
USBTransfer::Speed m_speed
USB speed.
int m_transferFile
USB transfer I/O file.
String m_busPath
USB bus path.
USBDescriptor::Device * m_device
USB device descriptor.
USBDescriptor::Configuration * m_config
USB configuration descriptor.
Index< USBDescriptor::Interface > m_interfaces
USB interface descriptors.
Index< USBDescriptor::Endpoint > m_endpoints
USB endpoint descriptors.
Index< USBDescriptor::String > m_strings
USB string descriptor.
Array< u8, 128 > m_endpointsPacketId
Contains endpoint to saved packet id mapping.
Protected Attributes inherited from Device
String m_identifier
Unique identifier for this Device.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
USB device class.
Definition at line 42 of file USBDevice.h.
Constructor & Destructor Documentation
USBDevice()
USBDevice::USBDevice (u8 deviceId, const char * usbPath = "/usb")
Constructor.
Definition at line 29 of file USBDevice.cpp.
References Array< T, N >::insert(), m_busPath, m_config, m_device, m_endpointsPacketId, m_id, m_transferFile, MemoryBlock::set(), and Array< T, N >::size().
~USBDevice()
USBDevice::~USBDevice () virtual
Destructor.
Definition at line 45 of file USBDevice.cpp.
References m_config, and m_device.
Member Function Documentation
beginTransfer()
Error USBDevice::beginTransfer (const USBTransfer::Type type, const USBTransfer::Direction direction, Address endpointId, void * buffer, Size size, Size maxPacketSize = 0, CallbackFunction * callback = 0) protected
Start an asynchronous USB transfer.
Returns
Result code
Definition at line 347 of file USBDevice.cpp.
References FileSystemMessage::action, Array< T, N >::at(), USBMessage::buffer, FileSystemMessage::buffer, DEBUG, USBMessage::deviceId, FileSystemMessage::deviceID, USBMessage::direction, EIO, USBMessage::endpointId, ESUCCESS, FILE_DESCRIPTOR_MAX, files, FileSystemMessage::from, getFiles(), FileDescriptor::identifier, Singleton< ChannelClient >::instance, LookupVirtual, m_device, m_endpointsPacketId, m_id, m_speed, m_transferFile, USBMessage::maxPacketSize, USBDescriptor::Device::maxPacketSize, DeviceID::minor, FileDescriptor::mount, FileSystemMessage::offset, open(), USBMessage::packetId, FileDescriptor::path, FileSystemMessage::path, Memory::Range::phys, ChannelMessage::Request, SELF, USBMessage::size, FileSystemMessage::size, USBMessage::speed, USBMessage::state, USBMessage::Status, ChannelClient::Success, USBMessage::type, ChannelMessage::type, Memory::Range::virt, VMCtl(), and WriteFile.
Referenced by SMSC95xxUSB::readStart(), and SMSC95xxUSB::writeStart().
controlMessage()
Error USBDevice::controlMessage (u8 request, const USBTransfer::Direction direction, const USBTransfer::RequestType type, const USBTransfer::Recipient recipient, u16 value, u16 index, void * buffer, Size size) protected
Send a control message.
Returns
Result code
Definition at line 268 of file USBDevice.cpp.
References USBMessage::buffer, USBTransfer::Control, DEBUG, USBMessage::deviceId, USBMessage::direction, USBMessage::endpointId, USBMessage::hubAddress, USBTransfer::Setup::index, USBTransfer::Setup::length, LookupVirtual, m_device, m_id, m_speed, USBMessage::maxPacketSize, USBDescriptor::Device::maxPacketSize, Memory::Range::phys, USBMessage::portAddress, USBTransfer::Setup::request, USBTransfer::Setup::requestType, SELF, USBMessage::setup, USBMessage::Setup, USBMessage::size, USBMessage::speed, USBMessage::state, submit(), USBMessage::type, USBTransfer::Setup::value, Memory::Range::virt, and VMCtl().
Referenced by getConfigDescriptor(), getDeviceDescriptor(), getEndpointDescriptor(), getInterfaceDescriptor(), USBHub::initialize(), SMSC95xxUSB::read(), setAddress(), setConfiguration(), USBHub::setPortFeature(), and SMSC95xxUSB::write().
finishTransfer()
Error USBDevice::finishTransfer (FileSystemMessage * msg) protected
Complete asynchronous USB transfer.
Returns
Result code
Definition at line 402 of file USBDevice.cpp.
References FileSystemMessage::buffer, USBTransfer::Control, DEBUG, USBMessage::endpointId, ESUCCESS, Array< T, N >::insert(), m_endpointsPacketId, USBMessage::packetId, and USBMessage::type.
Referenced by SMSC95xxUSB::readFinished(), and SMSC95xxUSB::writeFinished().
getConfigDescriptor()
Error USBDevice::getConfigDescriptor (USBDescriptor::Configuration * desc, Size size = sizeof(USBDescriptor::Configuration)) protected
Get configuration descriptor.
Returns
Result code
Definition at line 204 of file USBDevice.cpp.
References USBDescriptor::ConfigurationType, controlMessage(), DEBUG, USBTransfer::Device, USBTransfer::GetDescriptor, USBTransfer::In, and USBTransfer::Standard.
Referenced by initialize().
getDeviceDescriptor()
Error USBDevice::getDeviceDescriptor (USBDescriptor::Device * desc, Size size = sizeof(USBDescriptor::Device)) protected
Get device descriptor.
Returns
Result code
Definition at line 192 of file USBDevice.cpp.
References controlMessage(), DEBUG, USBTransfer::Device, USBDescriptor::DeviceType, USBTransfer::GetDescriptor, USBTransfer::In, and USBTransfer::Standard.
Referenced by initialize(), and USBHub::portAttach().
getEndpointDescriptor()
Error USBDevice::getEndpointDescriptor (u8 endpointId, USBDescriptor::Endpoint * desc) protected
Get endpoint descriptor.
Returns
Result code
Definition at line 228 of file USBDevice.cpp.
References controlMessage(), DEBUG, USBTransfer::Device, USBDescriptor::EndpointType, USBTransfer::GetDescriptor, USBTransfer::In, and USBTransfer::Standard.
getInterfaceDescriptor()
Error USBDevice::getInterfaceDescriptor (USBDescriptor::Interface * desc) protected
Get interface descriptor.
Returns
Result code
Definition at line 216 of file USBDevice.cpp.
References controlMessage(), DEBUG, USBTransfer::Device, USBTransfer::GetDescriptor, USBTransfer::In, USBDescriptor::InterfaceType, and USBTransfer::Standard.
initialize()
Error USBDevice::initialize () virtual
Initialize the USBDevice.
Returns
Result code
Reimplemented from Device.
Reimplemented in SMSC95xxUSB, and USBHub.
Definition at line 51 of file USBDevice.cpp.
References USBDescriptor::Endpoint::attributes, USBDescriptor::ConfigurationType, USBDescriptor::Configuration::configurationValue, DEBUG, USBDescriptor::Configuration::descriptorType, USBDescriptor::Device::deviceClass, USBDescriptor::Device::deviceProtocol, USBDescriptor::Device::deviceSubClass, USBDescriptor::DeviceType, EIO, USBDescriptor::Endpoint::endpointAddress, USBDescriptor::EndpointType, errno, ERROR, ESUCCESS, getConfigDescriptor(), getDeviceDescriptor(), USBDescriptor::HubType, Index< T >::insert(), USBDescriptor::InterfaceType, USBDescriptor::Configuration::length, USBDescriptor::Interface::length, USBDescriptor::Endpoint::length, USBDescriptor::String::length, m_busPath, m_config, m_device, m_endpoints, m_id, m_interfaces, m_strings, m_transferFile, USBDescriptor::Device::maxPacketSize, O_RDWR, open(), USBDescriptor::Device::productId, setAddress(), setConfiguration(), strerror(), USBDescriptor::StringType, USBDescriptor::Configuration::totalLength, and USBDescriptor::Device::vendorId.
Referenced by USBHub::initialize(), and SMSC95xxUSB::initialize().
setAddress()
Error USBDevice::setAddress (u8 address) protected
Set device address.
Returns
Result code
Definition at line 240 of file USBDevice.cpp.
References controlMessage(), DEBUG, USBTransfer::Device, ESUCCESS, m_id, USBTransfer::Out, USBTransfer::SetAddress, and USBTransfer::Standard.
Referenced by initialize().
setConfiguration()
Error USBDevice::setConfiguration (u8 configId) protected
Activate a configuration.
Returns
Result code
Definition at line 258 of file USBDevice.cpp.
References controlMessage(), DEBUG, USBTransfer::Device, USBTransfer::Out, USBTransfer::SetConfiguration, and USBTransfer::Standard.
Referenced by initialize().
submit()
Error USBDevice::submit (USBMessage & msg) protected
Submit a USB transfer to the Host controller.
Returns
Result code
Definition at line 416 of file USBDevice.cpp.
References DEBUG, EIO, errno, ERROR, ESUCCESS, m_transferFile, USBMessage::state, strerror(), and File::write().
Referenced by controlMessage(), and transfer().
transfer()
Error USBDevice::transfer (const USBTransfer::Type type, const USBTransfer::Direction direction, Address endpointId, void * buffer, Size size, Size maxPacketSize = 0) protected
Start a synchronous USB transfer.
Returns
Result code
Definition at line 313 of file USBDevice.cpp.
References USBMessage::buffer, DEBUG, USBMessage::deviceId, USBMessage::direction, USBMessage::endpointId, LookupVirtual, m_device, m_id, m_speed, USBMessage::maxPacketSize, USBDescriptor::Device::maxPacketSize, Memory::Range::phys, SELF, USBMessage::size, USBMessage::speed, USBMessage::state, USBMessage::Status, submit(), USBMessage::type, Memory::Range::virt, and VMCtl().
Field Documentation
m_busPath
String USBDevice::m_busPath protected
USB bus path.
Definition at line 174 of file USBDevice.h.
Referenced by initialize(), and USBDevice().
m_config
USBDescriptor::Configuration* USBDevice::m_config protected
USB configuration descriptor.
Definition at line 180 of file USBDevice.h.
Referenced by initialize(), USBDevice(), and ~USBDevice().
m_device
USBDescriptor::Device* USBDevice::m_device protected
USB device descriptor.
Definition at line 177 of file USBDevice.h.
Referenced by beginTransfer(), controlMessage(), initialize(), transfer(), USBDevice(), and ~USBDevice().
m_endpoints
Index<USBDescriptor::Endpoint> USBDevice::m_endpoints protected
USB endpoint descriptors.
Definition at line 186 of file USBDevice.h.
Referenced by initialize(), SMSC95xxUSB::readStart(), and SMSC95xxUSB::writeStart().
m_endpointsPacketId
Array<u8, 128> USBDevice::m_endpointsPacketId protected
Contains endpoint to saved packet id mapping.
Some host controllers require the endpoint to save the next packet identifier (Data0, Data1) for non-control transfers.
Definition at line 197 of file USBDevice.h.
Referenced by beginTransfer(), finishTransfer(), and USBDevice().
m_id
Address USBDevice::m_id protected
USB device identifier.
Definition at line 165 of file USBDevice.h.
Referenced by beginTransfer(), controlMessage(), initialize(), USBHub::portAttach(), setAddress(), transfer(), and USBDevice().
m_interfaces
Index<USBDescriptor::Interface> USBDevice::m_interfaces protected
USB interface descriptors.
Definition at line 183 of file USBDevice.h.
Referenced by initialize().
m_speed
USBTransfer::Speed USBDevice::m_speed protected
USB speed.
Definition at line 168 of file USBDevice.h.
Referenced by beginTransfer(), controlMessage(), and transfer().
m_strings
Index<USBDescriptor::String> USBDevice::m_strings protected
USB string descriptor.
Definition at line 189 of file USBDevice.h.
Referenced by initialize().
m_transferFile
int USBDevice::m_transferFile protected
USB transfer I/O file.
Definition at line 171 of file USBDevice.h.
Referenced by beginTransfer(), initialize(), submit(), and USBDevice().
The documentation for this class was generated from the following files:
lib/libusb/USBDevice.h
lib/libusb/USBDevice.cpp