FreeNOS: ARMKernel Class Reference
ARMKernel Class Reference
kernel » ARM
Represents the ARM kernel implementation.
#include <ARMKernel.h>
Public Member Functions
ARMKernel (ARMInterrupt *intr, CoreInfo *info)
Constructor function.
Public Member Functions inherited from Kernel
Kernel (CoreInfo *info)
Constructor function.
SplitAllocator * getAllocator ()
Get physical memory allocator.
ProcessManager * getProcessManager ()
Get process manager.
API * getAPI ()
Get API.
MemoryContext * getMemoryContext ()
Get the current MMU context.
CoreInfo * getCoreInfo ()
Get CoreInfo.
Timer * getTimer ()
Get Timer.
int run ()
Execute the kernel.
void enableIRQ (u32 irq, bool enabled)
Enable or disable an hardware interrupt (IRQ).
virtual void hookIntVector (u32 vec, InterruptHandler h, ulong p)
Hooks a function to an hardware interrupt.
virtual void executeIntVector (u32 vec, CPUState *state)
Execute an interrupt handler.
virtual Result loadBootImage ()
Loads the boot image.
Public Member Functions inherited from Singleton< Kernel >
Singleton (Kernel *obj)
Constructor.
Static Private Member Functions
static void interrupt (CPUState state)
Interrupt handler routine.
static void trap (CPUState state)
Software trap routine.
static void undefinedInstruction (CPUState state)
Undefined instruction routine.
static void prefetchAbort (CPUState state)
Prefetch abort routine.
static void dataAbort (CPUState state)
Data abort routine.
static void reserved (CPUState state)
Reserved routine.
Private Attributes
BroadcomTimer m_bcmTimer
Broadcom specific timer module.
u8 m_timerIrq
Interrupt number for the timer.
Additional Inherited Members
Public Types inherited from Kernel
enum Result { Success, InvalidBootImage, ProcessError }
Result codes.
Static Public Member Functions inherited from Kernel
static Error heap (Address base, Size size)
Initialize heap.
Static Public Attributes inherited from Singleton< Kernel >
static Kernel * instance
One and only instance.
Protected Attributes inherited from Kernel
SplitAllocator * m_alloc
Physical memory allocator.
ProcessManager * m_procs
Process Manager.
API * m_api
API handlers object.
CoreInfo * m_coreInfo
CoreInfo object for this core.
Vector< List< InterruptHook * > * > m_interrupts
Interrupt handlers.
IntController * m_intControl
Interrupt Controller.
Timer * m_timer
Timer device.
Detailed Description
Represents the ARM kernel implementation.
Definition at line 187 of file ARMKernel.h.
Constructor & Destructor Documentation
ARMKernel()
ARMKernel::ARMKernel (ARMInterrupt * intr, CoreInfo * info)
Constructor function.
Parameters
intr ARM interrupt controller implementation.
info Contains processor core specific information
Definition at line 27 of file ARMKernel.cpp.
References ARMControl::AlignmentCorrect, ARMControl::AlignmentFaults, BCM_IRQ_SYSTIMERM1, ARMControl::BigEndian, ARMInterrupt::DataAbort, dataAbort(), IntController::enable(), ARMInterrupt::FIQ, GTIMER_PHYS_1_IRQ, ARMInterrupt::install(), interrupt(), ARMInterrupt::IRQ, m_bcmTimer, Kernel::m_intControl, Kernel::m_timer, m_timerIrq, NOTICE, NULL, Broadcom2836::PhysicalTimer1, ARMInterrupt::PrefetchAbort, prefetchAbort(), ARMControl::read(), ARMInterrupt::Reserved, reserved(), ARMControl::set(), BroadcomTimer::setFrequency(), ARMInterrupt::SoftwareInterrupt, ARMControl::SystemFrequency, trap(), ARMInterrupt::UndefinedInstruction, undefinedInstruction(), and ARMControl::unset().
Member Function Documentation
dataAbort()
void ARMKernel::dataAbort (CPUState state) static private
Data abort routine.
Parameters
state Saved CPU register state
Definition at line 141 of file ARMKernel.cpp.
References FATAL, Kernel::getProcessManager(), Singleton< Kernel >::instance, and ARMCore::logException().
Referenced by ARMKernel().
interrupt()
void ARMKernel::interrupt (CPUState state) static private
Interrupt handler routine.
Parameters
state Saved CPU register state
Definition at line 84 of file ARMKernel.cpp.
References BCM_IRQ_SYSTIMERM1, MemoryBlock::copy(), ProcessManager::current(), DEBUG, Kernel::executeIntVector(), Kernel::getProcessManager(), Singleton< Kernel >::instance, ARMInterrupt::isTriggered(), Kernel::m_intControl, Kernel::m_timer, m_timerIrq, Broadcom2836::PhysicalTimer1, ProcessManager::schedule(), and Timer::tick().
Referenced by ARMKernel().
prefetchAbort()
void ARMKernel::prefetchAbort (CPUState state) static private
Prefetch abort routine.
Parameters
state Saved CPU register state
Definition at line 133 of file ARMKernel.cpp.
References FATAL, Kernel::getProcessManager(), Singleton< Kernel >::instance, and ARMCore::logException().
Referenced by ARMKernel().
reserved()
void ARMKernel::reserved (CPUState state) static private
Reserved routine.
Parameters
state Saved CPU register state
Definition at line 150 of file ARMKernel.cpp.
References FATAL, Kernel::getProcessManager(), Singleton< Kernel >::instance, and ARMCore::logException().
Referenced by ARMKernel().
trap()
void ARMKernel::trap (CPUState state) static private
Software trap routine.
Parameters
state Saved CPU register state
Definition at line 158 of file ARMKernel.cpp.
References MemoryBlock::copy(), ProcessManager::current(), DEBUG, ProcessManager::get(), Kernel::getAPI(), Process::getID(), Kernel::getProcessManager(), Singleton< Kernel >::instance, API::invoke(), NULL, CPUState::r0, CPUState::r1, CPUState::r2, CPUState::r3, CPUState::r4, CPUState::r5, and ARMProcess::setCpuState().
Referenced by ARMKernel().
undefinedInstruction()
void ARMKernel::undefinedInstruction (CPUState state) static private
Undefined instruction routine.
Parameters
state Saved CPU register state
Definition at line 125 of file ARMKernel.cpp.
References FATAL, Kernel::getProcessManager(), Singleton< Kernel >::instance, and ARMCore::logException().
Referenced by ARMKernel().
Field Documentation
m_bcmTimer
BroadcomTimer ARMKernel::m_bcmTimer private
Broadcom specific timer module.
Definition at line 255 of file ARMKernel.h.
Referenced by ARMKernel().
m_timerIrq
u8 ARMKernel::m_timerIrq private
Interrupt number for the timer.
Definition at line 258 of file ARMKernel.h.
Referenced by ARMKernel(), and interrupt().
The documentation for this class was generated from the following files:
kernel/arm/ARMKernel.h
kernel/arm/ARMKernel.cpp