FreeNOS: IntelProcess Class Reference
IntelProcess Class Reference
kernel » Intel
Process which may execute on an Intel CPU.
#include <IntelProcess.h>
Public Member Functions
IntelProcess (ProcessID id, Address entry, bool privileged, const MemoryMap &map)
Constructor function.
virtual ~IntelProcess ()
Destructor function.
virtual Result initialize ()
Initialize the Process.
virtual void execute (Process *previous)
Execute the process.
Public Member Functions inherited from Process
Process (ProcessID id, Address entry, bool privileged, const MemoryMap &map)
Constructor function.
virtual ~Process ()
Destructor function.
ProcessID getID () const
Retrieve our ID number.
ProcessID getParent () const
Retrieve our parent ID.
ProcessID getWait () const
Get Wait ID.
const Timer::Info & getSleepTimer () const
Get sleep timer.
ProcessShares & getShares ()
Get process shares.
State getState () const
Retrieves the current state.
Address getPageDirectory () const
Get the address of our page directory.
Address getUserStack () const
Get the address of the user stack.
Address getKernelStack () const
Get the address of the kernel stack.
MemoryContext * getMemoryContext ()
Get MMU memory context.
Result raiseEvent (struct ProcessEvent *event)
Raise kernel event.
bool isPrivileged () const
Get privilege.
void setState (State st)
Puts the Process in a new state.
void setParent (ProcessID id)
Set parent process ID.
void setWait (ProcessID id)
Set Wait ID.
void setSleepTimer (const Timer::Info *sleeptimer)
Set sleep timer.
void setPageDirectory (Address addr)
Set page directory address.
void setUserStack (Address addr)
Sets the address of the user stack.
void setKernelStack (Address addr)
Set the kernel stack address.
bool operator== (Process *proc)
Compare two processes.
Result wakeup ()
Prevent process from sleeping.
Result sleep (Timer::Info *timer=0)
Stops the process for executing until woken up.
Static Private Attributes
static const Size KernelStackSize = PAGESIZE
Size of the kernel stack.
Additional Inherited Members
Public Types inherited from Process
enum Result { Success, MemoryMapError, OutOfMemory, WakeupPending }
enum State {
Running, Ready, Stopped, Sleeping,
Waiting
}
Protected Attributes inherited from Process
const ProcessID m_id
Process Identifier.
ProcessID m_parent
Parent process.
State m_state
Current process status.
ProcessID m_waitId
Waits for exit of this Process.
bool m_privileged
Privilege level.
Address m_entry
Entry point of the program.
MemoryMap m_map
Virtual memory layout.
MemoryContext * m_memoryContext
MMU memory context.
Address m_pageDirectory
Page directory.
Address m_userStack
User stack address.
Address m_kernelStack
Current kernel stack address (changes during execution).
Address m_kernelStackBase
Base kernel stack (fixed)
Size m_wakeups
Number of wakeups received.
Timer::Info m_sleepTimer
Sleep timer value.
ProcessShares m_shares
Contains virtual memory shares between this process and others.
MemoryChannel * m_kernelChannel
Channel for sending kernel events to the Process.
Detailed Description
Process which may execute on an Intel CPU.
Definition at line 35 of file IntelProcess.h.
Constructor & Destructor Documentation
IntelProcess()
IntelProcess::IntelProcess (ProcessID id, Address entry, bool privileged, const MemoryMap & map)
Constructor function.
Parameters
id Process Identifier.
entry Initial EIP register value.
privileged If true, the Process has unlimited access to hardware.
map Virtual memory layout.
Definition at line 25 of file IntelProcess.cpp.
~IntelProcess()
IntelProcess::~IntelProcess () virtual
Destructor function.
Definition at line 101 of file IntelProcess.cpp.
References Kernel::getAllocator(), Singleton< Kernel >::instance, KernelStackSize, Process::m_kernelStackBase, SplitAllocator::release(), and SplitAllocator::toPhysical().
Member Function Documentation
execute()
void IntelProcess::execute (Process * previous) virtual
Execute the process.
Saves and restores registers, then perform a context switch.
Implements Process.
Definition at line 108 of file IntelProcess.cpp.
References MemoryContext::activate(), TSS::esp0, kernelTss, Process::m_kernelStack, Process::m_kernelStackBase, Process::m_memoryContext, switchCoreState(), and ZERO.
initialize()
Process::Result IntelProcess::initialize () virtual
Initialize the Process.
Allocates various (architecture specific) resources, creates MMU context and stacks.
Returns
Result code
Reimplemented from Process.
Definition at line 30 of file IntelProcess.cpp.
References Memory::Range::access, IRQRegs0::cs, IRQRegs3::cs, SegRegs::ds, CPURegs::ebp, IRQRegs0::eflags, IRQRegs3::eflags, IRQRegs0::eip, IRQRegs3::eip, SegRegs::es, CPURegs::esp0, IRQRegs3::esp3, SegRegs::fs, SegRegs::gs, Process::initialize(), Singleton< Kernel >::instance, INTEL_EFLAGS_DEFAULT, INTEL_EFLAGS_IRQ, CPUState::irq, KERNEL_CS_SEL, KERNEL_DS_SEL, KernelStackSize, loadCoreState(), Process::m_entry, Process::m_kernelStack, Process::m_kernelStackBase, Process::m_map, Process::m_memoryContext, Process::m_privileged, Process::m_userStack, MemoryContext::mapRange(), MEMALIGN, Process::MemoryMapError, Process::OutOfMemory, Memory::Range::phys, MemoryMap::range(), Memory::Readable, CPUState::regs, CPUState::seg, MemoryBlock::set(), Process::setKernelStack(), Process::setUserStack(), Memory::Range::size, SegRegs::ss0, IRQRegs3::ss3, MemoryContext::Success, Allocator::Success, Memory::User, USER_CS_SEL, USER_DS_SEL, MemoryMap::UserStack, Memory::Range::virt, and Memory::Writable.
Field Documentation
KernelStackSize
const Size IntelProcess::KernelStackSize = PAGESIZE static private
Size of the kernel stack.
Definition at line 40 of file IntelProcess.h.
Referenced by initialize(), and ~IntelProcess().
The documentation for this class was generated from the following files:
kernel/intel/IntelProcess.h
kernel/intel/IntelProcess.cpp