FreeNOS: IPCTestServer Class Reference
IPCTestServer Class Reference
server » ipctest
Test server for inter process communication (IPC).
#include <IPCTestServer.h>
Public Member Functions
IPCTestServer ()
Constructor function.
virtual ~IPCTestServer ()
Destructor function.
Public Member Functions inherited from ChannelServer< IPCTestServer, IPCTestMessage >
ChannelServer (IPCTestServer *inst, Size num=32)
Constructor function.
virtual ~ChannelServer ()
Destructor function.
int run ()
Enters an infinite loop, serving incoming requests.
void addIPCHandler (Size slot, IPCHandlerFunction h, bool sendReply=true)
Register a new IPC message action handler.
void addIRQHandler (Size slot, IRQHandlerFunction h)
Register a new IRQ message vector handler.
virtual void timeout ()
Called when sleep timeout is reached.
virtual bool retryRequests ()
Retry any pending requests.
void setTimeout (uint msec)
Set a sleep timeout.
Private Member Functions
void testActionAHandler (IPCTestMessage *msg)
Handler for ActionA messages.
void testActionBHandler (IPCTestMessage *msg)
Handler for ActionB messages.
Additional Inherited Members
Public Types inherited from ChannelServer< IPCTestServer, IPCTestMessage >
enum Result
Result codes.
Protected Types inherited from ChannelServer< IPCTestServer, IPCTestMessage >
typedef void(IPCTestServer ::* IPCHandlerFunction) (IPCTestMessage *)
Member function pointer inside Base, to handle IPC messages.
typedef void(IPCTestServer ::* IRQHandlerFunction) (Size)
Member function pointer inside Base, to handle interrupts.
Protected Attributes inherited from ChannelServer< IPCTestServer, IPCTestMessage >
ChannelRegistry * m_registry
Contains registered channels.
ChannelClient * m_client
Client for sending replies.
MemoryChannel m_kernelEvent
Kernel event channel.
bool m_sendReply
Should we send a reply message?
Vector< MessageHandler< IPCHandlerFunction > *> * m_ipcHandlers
IPC handler functions.
Vector< MessageHandler< IRQHandlerFunction > *> * m_irqHandlers
IRQ handler functions.
IPCTestServer * m_instance
Server object instance.
ProcessID m_self
ProcessID of ourselves.
Timer::Info m_time
System timer value.
Detailed Description
Test server for inter process communication (IPC).
Definition at line 36 of file IPCTestServer.h.
Constructor & Destructor Documentation
IPCTestServer()
IPCTestServer::IPCTestServer ()
Constructor function.
Definition at line 20 of file IPCTestServer.cpp.
References ChannelServer< IPCTestServer, IPCTestMessage >::addIPCHandler(), NOTICE, TestActionA, testActionAHandler(), TestActionB, and testActionBHandler().
~IPCTestServer()
IPCTestServer::~IPCTestServer () virtual
Destructor function.
Definition at line 30 of file IPCTestServer.cpp.
Member Function Documentation
testActionAHandler()
void IPCTestServer::testActionAHandler (IPCTestMessage * msg) private
Handler for ActionA messages.
Parameters
msg Input message
Definition at line 34 of file IPCTestServer.cpp.
References IPCTestMessage::data, and NOTICE.
Referenced by IPCTestServer().
testActionBHandler()
void IPCTestServer::testActionBHandler (IPCTestMessage * msg) private
Handler for ActionB messages.
Parameters
msg Input message
Definition at line 40 of file IPCTestServer.cpp.
References IPCTestMessage::data, and NOTICE.
Referenced by IPCTestServer().
The documentation for this class was generated from the following files:
server/ipctest/IPCTestServer.h
server/ipctest/IPCTestServer.cpp