FreeNOS: ARMCacheV6 Class Reference
ARMCacheV6 Class Reference
lib » libarch » ARM
ARMv6 cache management implementation.
#include <ARMCacheV6.h>
Public Member Functions
virtual Result invalidate (Type type)
Invalidate the entire cache.
virtual Result cleanInvalidate (Type type)
Clean and invalidate entire cache.
virtual Result cleanInvalidateAddress (Type type, Address addr)
Clean and invalidate one memory page.
virtual Result cleanAddress (Type type, Address addr)
Clean one memory page.
Public Member Functions inherited from Cache
virtual Result cleanData (Address addr)
Clean one data page.
virtual Result cleanData (void *ptr)
Clean one data page.
Private Attributes
ARMControl m_control
ARM system control processor object.
Additional Inherited Members
Public Types inherited from Cache
enum Result { Success, InvalidArgument, IOError }
Result codes.
enum Type { Instruction, Data, Unified }
Cache types.
Detailed Description
ARMv6 cache management implementation.
See also
ARM Architecture Reference Manual, page xxx
Definition at line 42 of file ARMCacheV6.h.
Member Function Documentation
cleanAddress()
ARMCacheV6::Result ARMCacheV6::cleanAddress (ARMCacheV6::Type type, Address addr) virtual
Clean one memory page.
Parameters
type Cache type to clean
addr Virtual memory address of the page to clean and invalidate
Returns
Result code
Implements Cache.
Definition at line 96 of file ARMCacheV6.cpp.
References Cache::Data, Cache::Instruction, mcr, Cache::Success, and Cache::Unified.
cleanInvalidate()
ARMCacheV6::Result ARMCacheV6::cleanInvalidate (ARMCacheV6::Type type) virtual
Clean and invalidate entire cache.
This operation will clean and invalidate the entire given cache.
Parameters
type Cache type to clean and invalidate.
Returns
Result code
Implements Cache.
Definition at line 41 of file ARMCacheV6.cpp.
References Cache::Data, dsb(), flushBranchPrediction(), flushPrefetchBuffer(), Cache::Instruction, mcr, Cache::Success, and Cache::Unified.
Referenced by ARMPaging::activate(), invalidate(), VMCtlHandler(), and ARMPaging::~ARMPaging().
cleanInvalidateAddress()
ARMCacheV6::Result ARMCacheV6::cleanInvalidateAddress (Type type, Address addr) virtual
Clean and invalidate one memory page.
Parameters
type Cache type to clean and invalidate.
addr Virtual memory address of the page to clean and invalidate
Returns
Result code
Implements Cache.
Definition at line 78 of file ARMCacheV6.cpp.
References Cache::Data, Cache::Instruction, mcr, Cache::Success, and Cache::Unified.
Referenced by ARMPaging::unmap().
invalidate()
ARMCacheV6::Result ARMCacheV6::invalidate (ARMCacheV6::Type type) virtual
Invalidate the entire cache.
Parameters
type Cache type to invalidate.
Returns
Result code
Implements Cache.
Definition at line 21 of file ARMCacheV6.cpp.
References cleanInvalidate(), Cache::Data, dsb(), Cache::Instruction, mcr, Cache::Success, and Cache::Unified.
Referenced by kernel_main().
Field Documentation
m_control
ARMControl ARMCacheV6::m_control private
ARM system control processor object.
Definition at line 90 of file ARMCacheV6.h.
The documentation for this class was generated from the following files:
lib/libarch/arm/ARMCacheV6.h
lib/libarch/arm/ARMCacheV6.cpp