FreeNOS: Terminal Class Reference
Terminal Class Reference
server » terminal
A Terminal enables user to interact with the system.
#include <Terminal.h>
Public Member Functions
Terminal (const char *inputFile, const char *outputFile, Size width=80, Size height=25)
Class constructor.
virtual ~Terminal ()
Class destructor.
Size getWidth ()
Retrieve the width of the Terminal.
Size getHeight ()
Retrieve the height of the Terminal.
int getInput ()
Retrieve file descriptor of the input source.
int getOutput ()
Retrieve file descriptor of the output source.
u16 * getBuffer ()
Retrieve a pointer to the local buffer.
u16 * getCursorValue ()
Saved byte and attribute value at cursor position.
void hideCursor ()
Hides the cursor from the VGA screen.
void setCursor (const teken_pos_t *pos)
Sets the new position of the cursor.
void showCursor ()
Show the VGA cursor.
virtual Error initialize ()
Initializes the Terminal.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read bytes from the Terminal.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the Terminal (vga memory).
Public Member Functions inherited from Device
Device (FileType type)
Constructor.
virtual ~Device ()
Destructor.
virtual const String & getIdentifier () const
Get unique device identifier.
virtual Error interrupt (Size vector)
Called when an interrupt has been triggered for this device.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Attributes
teken_t state
Terminal state.
teken_funcs_t funcs
Terminal function handlers.
u16 * buffer
Buffer for local Terminal updates.
teken_pos_t cursorPos
Saved cursor position.
u16 cursorValue
Saved value at cursor position.
const char * inputFile
Path to the input and output files.
const char * outputFile
const Size width
Width and height of the Terminal.
const Size height
int input
Input and output file descriptors.
int output
Additional Inherited Members
Protected Attributes inherited from Device
String m_identifier
Unique identifier for this Device.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
A Terminal enables user to interact with the system.
Definition at line 44 of file Terminal.h.
Constructor & Destructor Documentation
Terminal()
Terminal::Terminal (const char * inputFile, const char * outputFile, Size width = 80, Size height = 25)
Class constructor.
Parameters
inputFile Path to the (device) file to use as input source.
outputFile Path to the (device) file to use as an output source.
width Width of the Terminal.
height Height of the Terminal.
Definition at line 43 of file Terminal.cpp.
References buffer, height, Device::m_identifier, and width.
~Terminal()
Terminal::~Terminal () virtual
Class destructor.
Definition at line 107 of file Terminal.cpp.
References buffer, close(), input, and output.
Member Function Documentation
getBuffer()
u16 * Terminal::getBuffer ()
Retrieve a pointer to the local buffer.
Returns
Pointer to the local buffer.
Definition at line 134 of file Terminal.cpp.
References buffer.
Referenced by copy(), fill(), and putchar().
getCursorValue()
u16 * Terminal::getCursorValue ()
Saved byte and attribute value at cursor position.
Returns
Saved value.
Definition at line 139 of file Terminal.cpp.
References cursorValue.
getHeight()
Size Terminal::getHeight ()
Retrieve the height of the Terminal.
Returns
Terminal height.
Definition at line 119 of file Terminal.cpp.
References height.
getInput()
int Terminal::getInput ()
Retrieve file descriptor of the input source.
Returns
File descriptor number.
Definition at line 124 of file Terminal.cpp.
References input.
getOutput()
int Terminal::getOutput ()
Retrieve file descriptor of the output source.
Returns
File descriptor number.
Definition at line 129 of file Terminal.cpp.
References output.
getWidth()
Size Terminal::getWidth ()
Retrieve the width of the Terminal.
Returns
Terminal width.
Definition at line 114 of file Terminal.cpp.
References width.
Referenced by copy(), fill(), and putchar().
hideCursor()
void Terminal::hideCursor ()
Hides the cursor from the VGA screen.
Definition at line 184 of file Terminal.cpp.
References buffer, cursorPos, cursorValue, teken_pos_t::tp_col, teken_pos_t::tp_row, and width.
Referenced by copy(), cursor(), fill(), and putchar().
initialize()
Error Terminal::initialize () virtual
Initializes the Terminal.
Returns
Error result code.
Reimplemented from Device.
Definition at line 51 of file Terminal.cpp.
References BANNER, bell(), IOBuffer::bufferedWrite(), close(), copy(), cursor(), cursorPos, errno, ESUCCESS, exit(), EXIT_FAILURE, fill(), funcs, IOBuffer::getCount(), input, inputFile, memset(), O_RDONLY, O_RDWR, open(), output, outputFile, param(), printf(), putchar(), ChannelMessage::Request, respond(), FileSystemMessage::size, state, strerror(), strlen(), teken_init(), teken_set_winsize(), teken_funcs_t::tf_bell, teken_funcs_t::tf_copy, teken_funcs_t::tf_cursor, teken_funcs_t::tf_fill, teken_funcs_t::tf_param, teken_funcs_t::tf_putchar, teken_funcs_t::tf_respond, teken_pos_t::tp_col, teken_pos_t::tp_row, ChannelMessage::type, and write().
read()
Error Terminal::read (IOBuffer & buffer, Size size, Size offset) virtual
Read bytes from the Terminal.
Parameters
buffer Output buffer.
size Number of bytes to read.
offset Unused.
Returns
Number of bytes read or error code on failure.
Reimplemented from File.
Definition at line 144 of file Terminal.cpp.
References input, and IOBuffer::write().
Referenced by write().
setCursor()
void Terminal::setCursor (const teken_pos_t * pos)
Sets the new position of the cursor.
Parameters
pos New position coordinates.
Definition at line 193 of file Terminal.cpp.
References buffer, cursorPos, cursorValue, teken_pos_t::tp_col, teken_pos_t::tp_row, and width.
Referenced by cursor(), and showCursor().
showCursor()
void Terminal::showCursor ()
Show the VGA cursor.
Definition at line 200 of file Terminal.cpp.
References buffer, cursorPos, LIGHTGREY, setCursor(), teken_pos_t::tp_col, teken_pos_t::tp_row, VGA_ATTR, and width.
Referenced by copy(), cursor(), fill(), and putchar().
write()
Error Terminal::write (IOBuffer & buffer, Size size, Size offset) virtual
Write bytes to the Terminal (vga memory).
Parameters
buffer Contains the bytes to write.
size Number of bytes to write.
offset Unused.
Returns
Number of bytes written or error code on failure.
Reimplemented from File.
Definition at line 156 of file Terminal.cpp.
References height, lseek(), output, read(), SEEK_SET, state, teken_input(), and width.
Referenced by initialize().
Field Documentation
buffer
u16* Terminal::buffer private
Buffer for local Terminal updates.
Definition at line 162 of file Terminal.h.
Referenced by copy(), getBuffer(), hideCursor(), putchar(), setCursor(), showCursor(), Terminal(), and ~Terminal().
cursorPos
teken_pos_t Terminal::cursorPos private
Saved cursor position.
Definition at line 165 of file Terminal.h.
Referenced by hideCursor(), initialize(), setCursor(), and showCursor().
cursorValue
u16 Terminal::cursorValue private
Saved value at cursor position.
Definition at line 168 of file Terminal.h.
Referenced by getCursorValue(), hideCursor(), and setCursor().
funcs
teken_funcs_t Terminal::funcs private
Terminal function handlers.
Definition at line 159 of file Terminal.h.
Referenced by initialize().
height
const Size Terminal::height private
Definition at line 178 of file Terminal.h.
Referenced by getHeight(), Terminal(), and write().
input
int Terminal::input private
Input and output file descriptors.
Definition at line 181 of file Terminal.h.
Referenced by getInput(), initialize(), read(), and ~Terminal().
inputFile
const char* Terminal::inputFile private
Path to the input and output files.
Definition at line 173 of file Terminal.h.
Referenced by initialize().
output
int Terminal::output private
Definition at line 181 of file Terminal.h.
Referenced by getOutput(), initialize(), write(), and ~Terminal().
outputFile
const char * Terminal::outputFile private
Definition at line 173 of file Terminal.h.
Referenced by initialize().
state
teken_t Terminal::state private
Terminal state.
Definition at line 156 of file Terminal.h.
Referenced by initialize(), and write().
width
const Size Terminal::width private
Width and height of the Terminal.
Definition at line 178 of file Terminal.h.
Referenced by copy(), getWidth(), hideCursor(), putchar(), setCursor(), showCursor(), Terminal(), and write().
The documentation for this class was generated from the following files:
server/terminal/Terminal.h
server/terminal/Terminal.cpp