FreeNOS: USBTransferFile Class Reference
USBTransferFile Class Reference
lib » libusb
USB transfer file for USBController (/usb/transfer)
#include <USBTransferFile.h>
Public Member Functions
USBTransferFile (USBController *controller)
Constructor.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read bytes from the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Attributes
USBController * m_controller
Pointer to the USB controller for doing actual transfers.
Additional Inherited Members
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
USB transfer file for USBController (/usb/transfer)
Definition at line 35 of file USBTransferFile.h.
Constructor & Destructor Documentation
USBTransferFile()
USBTransferFile::USBTransferFile (USBController * controller)
Constructor.
Definition at line 23 of file USBTransferFile.cpp.
References File::m_access, m_controller, and OwnerRW.
Member Function Documentation
write()
Error USBTransferFile::write (IOBuffer & buffer, Size size, Size offset) virtual
Write bytes to the file.
Parameters
buffer Input/Output buffer to input bytes from.
size Number of bytes to write, at maximum.
offset Offset inside the file to start writing.
Returns
Number of bytes written on success, Error on failure.
Reimplemented from File.
Definition at line 30 of file USBTransferFile.cpp.
References USBMessage::Data, EIO, ERROR, USBMessage::Failure, IOBuffer::getBuffer(), IOBuffer::getMessage(), m_controller, USBMessage::Setup, USBMessage::state, USBMessage::Status, USBMessage::Success, USBController::transfer(), and IOBuffer::write().
Field Documentation
m_controller
USBController* USBTransferFile::m_controller private
Pointer to the USB controller for doing actual transfers.
Definition at line 58 of file USBTransferFile.h.
Referenced by USBTransferFile(), and write().
The documentation for this class was generated from the following files:
lib/libusb/USBTransferFile.h
lib/libusb/USBTransferFile.cpp