FreeNOS: IntelPaging Class Reference
IntelPaging Class Reference
lib » libarch » Intel
Intel virtual memory implementation.
#include <IntelPaging.h>
Public Member Functions
IntelPaging (MemoryMap *map, SplitAllocator *alloc)
Constructor.
IntelPaging (MemoryMap *map, Address pageDirectory, SplitAllocator *alloc)
Constructor.
virtual ~IntelPaging ()
Destructor.
virtual Result activate ()
Activate the MemoryContext.
virtual Result map (Address virt, Address phys, Memory::Access access)
Map a physical page to a virtual address.
virtual Result unmap (Address virt)
Unmap a virtual address.
virtual Result lookup (Address virt, Address *phys) const
Translate virtual address to physical address.
virtual Result access (Address addr, Memory::Access *access) const
Get Access flags for a virtual address.
virtual Result releaseRegion (MemoryMap::Region region, bool tablesOnly)
Release region of memory.
virtual Result releaseRange (Memory::Range *range, bool tablesOnly)
Release range of memory.
Public Member Functions inherited from MemoryContext
MemoryContext (MemoryMap *map, SplitAllocator *alloc)
Constructor.
virtual ~MemoryContext ()
Destructor.
virtual Result mapRange (Memory::Range *range)
Map a range of physical pages to virtual addresses.
virtual Result unmapRange (Memory::Range *range)
Unmaps a range of virtual memory.
virtual Result release (Address virt)
Release a memory page mapping.
virtual Result findFree (Size size, MemoryMap::Region region, Address *virt) const
Find unused memory.
Private Attributes
IntelPageDirectory * m_pageDirectory
Pointer to page directory in kernel's virtual memory.
Address m_pageDirectoryAddr
Physical address of the page directory.
bool m_pageDirectoryAllocated
Set to true if page directory was allocated by this class.
Additional Inherited Members
Public Types inherited from MemoryContext
enum Result {
Success, InvalidAddress, InvalidSize, AlreadyExists,
OutOfMemory
}
Result codes.
typedef enum MemoryContext::Result Result
Result codes.
Static Public Member Functions inherited from MemoryContext
static MemoryContext * getCurrent ()
Get currently active MemoryContext.
Protected Attributes inherited from MemoryContext
SplitAllocator * m_alloc
Physical memory allocator.
MemoryMap * m_map
Virtual memory layout.
Static Protected Attributes inherited from MemoryContext
static MemoryContext * m_current = 0
The currently active MemoryContext.
Detailed Description
Intel virtual memory implementation.
Definition at line 43 of file IntelPaging.h.
Constructor & Destructor Documentation
IntelPaging() [1/2]
IntelPaging::IntelPaging (MemoryMap * map, SplitAllocator * alloc)
Constructor.
Allocates new page tables for the paged memory context.
Parameters
map Virtual memory map.
alloc Allocator for physical memory page allocations.
Definition at line 23 of file IntelPaging.cpp.
References SplitAllocator::allocateLow(), IntelPageDirectory::copy(), currentDirectory, MemoryMap::KernelData, MemoryMap::KernelPrivate, MemoryContext::m_map, m_pageDirectory, m_pageDirectoryAddr, m_pageDirectoryAllocated, MemoryMap::range(), IntelCore::readCR3(), MemoryBlock::set(), Memory::Range::size, Allocator::Success, SplitAllocator::toVirtual(), and Memory::Range::virt.
IntelPaging() [2/2]
IntelPaging::IntelPaging (MemoryMap * map, Address pageDirectory, SplitAllocator * alloc)
Constructor.
Assign the given page directory to this paged memory context. This constructor does not allocate new page tables.
Parameters
map Virtual memory map.
pageDirectory Physical address of the page directory to use.
alloc Allocator for physical memory page allocations.
Definition at line 61 of file IntelPaging.cpp.
~IntelPaging()
IntelPaging::~IntelPaging () virtual
Destructor.
Definition at line 69 of file IntelPaging.cpp.
References MemoryContext::m_alloc, m_pageDirectoryAddr, m_pageDirectoryAllocated, and SplitAllocator::release().
Member Function Documentation
access()
MemoryContext::Result IntelPaging::access (Address addr, Memory::Access * access) const virtual
Get Access flags for a virtual address.
Parameters
virt Virtual address to get Access flags for.
access MemoryAccess object pointer.
Returns
Result code.
Implements MemoryContext.
Definition at line 112 of file IntelPaging.cpp.
References IntelPageDirectory::access(), MemoryContext::m_alloc, and m_pageDirectory.
activate()
MemoryContext::Result IntelPaging::activate () virtual
Activate the MemoryContext.
This function applies this MemoryContext to the hardware MMU.
Returns
Result code.
Implements MemoryContext.
Definition at line 77 of file IntelPaging.cpp.
References MemoryContext::m_current, m_pageDirectoryAddr, MemoryContext::Success, and IntelCore::writeCR3().
Referenced by IntelKernel::IntelKernel().
lookup()
MemoryContext::Result IntelPaging::lookup (Address virt, Address * phys) const virtual
Translate virtual address to physical address.
Parameters
virt Virtual address to lookup on input, physical address on output.
Returns
Result code
Implements MemoryContext.
Definition at line 107 of file IntelPaging.cpp.
References MemoryContext::m_alloc, m_pageDirectory, and IntelPageDirectory::translate().
map()
MemoryContext::Result IntelPaging::map (Address virt, Address phys, Memory::Access access) virtual
Map a physical page to a virtual address.
Parameters
virt Virtual address.
phys Physical address.
access Memory access flags.
Returns
Result code
Implements MemoryContext.
Definition at line 85 of file IntelPaging.cpp.
References MemoryContext::m_alloc, MemoryContext::m_current, m_pageDirectory, IntelPageDirectory::map(), MemoryContext::Success, and tlb_flush.
releaseRange()
MemoryContext::Result IntelPaging::releaseRange (Memory::Range * range, bool tablesOnly) virtual
Release range of memory.
Parameters
range Memory range input
tablesOnly Set to true to only release page tables and not mapped pages.
Returns
Result code.
Implements MemoryContext.
Definition at line 122 of file IntelPaging.cpp.
References MemoryContext::m_alloc, m_pageDirectory, and IntelPageDirectory::releaseRange().
releaseRegion()
MemoryContext::Result IntelPaging::releaseRegion (MemoryMap::Region region, bool tablesOnly) virtual
Release region of memory.
Parameters
region Memory region input
tablesOnly Set to true to only release page tables and not mapped pages.
Returns
Result code.
Implements MemoryContext.
Definition at line 117 of file IntelPaging.cpp.
References MemoryContext::m_alloc, MemoryContext::m_map, m_pageDirectory, MemoryMap::range(), and IntelPageDirectory::releaseRange().
unmap()
MemoryContext::Result IntelPaging::unmap (Address virt) virtual
Unmap a virtual address.
This function removes a virtual to physical memory mapping without deallocating any physical memory.
Parameters
virt Virtual address to unmap.
Returns
Result code
Implements MemoryContext.
Definition at line 96 of file IntelPaging.cpp.
References MemoryContext::m_alloc, MemoryContext::m_current, m_pageDirectory, MemoryContext::Success, tlb_flush, and IntelPageDirectory::unmap().
Field Documentation
m_pageDirectory
IntelPageDirectory* IntelPaging::m_pageDirectory private
Pointer to page directory in kernel's virtual memory.
Definition at line 148 of file IntelPaging.h.
Referenced by access(), IntelPaging(), lookup(), map(), releaseRange(), releaseRegion(), and unmap().
m_pageDirectoryAddr
Address IntelPaging::m_pageDirectoryAddr private
Physical address of the page directory.
Definition at line 151 of file IntelPaging.h.
Referenced by activate(), IntelPaging(), and ~IntelPaging().
m_pageDirectoryAllocated
bool IntelPaging::m_pageDirectoryAllocated private
Set to true if page directory was allocated by this class.
Definition at line 154 of file IntelPaging.h.
Referenced by IntelPaging(), and ~IntelPaging().
The documentation for this class was generated from the following files:
lib/libarch/intel/IntelPaging.h
lib/libarch/intel/IntelPaging.cpp