FreeNOS: FileStatus Class Reference
FileStatus Class Reference
bin
Retrieve file status from the filesystem.
#include <FileStatus.h>
Public Member Functions
FileStatus (int argc, char **argv)
Constructor.
virtual ~FileStatus ()
Destructor.
virtual Result exec ()
Execute the application.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Private Member Functions
Result printStatus (const String &file) const
Concatenate a file.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
Retrieve file status from the filesystem.
Definition at line 31 of file FileStatus.h.
Constructor & Destructor Documentation
FileStatus()
FileStatus::FileStatus (int argc, char ** argv)
Constructor.
Parameters
argc Argument count
argv Argument values
Definition at line 27 of file FileStatus.cpp.
References Application::parser(), ArgumentParser::registerPositional(), and ArgumentParser::setDescription().
~FileStatus()
FileStatus::~FileStatus () virtual
Destructor.
Definition at line 34 of file FileStatus.cpp.
Member Function Documentation
exec()
FileStatus::Result FileStatus::exec () virtual
Execute the application.
Returns
Result code
Implements Application.
Definition at line 38 of file FileStatus.cpp.
References Application::arguments(), Vector< T >::count(), ArgumentContainer::getPositionals(), printStatus(), refreshMounts(), and Application::Success.
printStatus()
FileStatus::Result FileStatus::printStatus (const String & file) const private
Concatenate a file.
Parameters
file Name of file to concatenate
Returns
Result code
Definition at line 64 of file FileStatus.cpp.
References errno, ERROR, Application::IOError, DeviceID::major, DeviceID::minor, printf(), S_ISBLK, S_ISCHR, S_ISDIR, S_ISREG, stat::st_dev, stat::st_gid, stat::st_mode, stat::st_size, stat::st_uid, stat(), strerror(), and Application::Success.
Referenced by exec().
The documentation for this class was generated from the following files:
bin/stat/FileStatus.h
bin/stat/FileStatus.cpp