FreeNOS: BroadcomInterrupt Class Reference
BroadcomInterrupt Class Reference
lib » libarch » Broadcom
Raspberry Pi Interrupt Controller implementation.
#include <BroadcomInterrupt.h>
Public Member Functions
BroadcomInterrupt ()
Constructor.
virtual Result enable (uint vector)
Enable an IRQ vector.
virtual Result disable (uint vector)
Disable an IRQ vector.
virtual Result clear (uint vector)
Clear an IRQ vector.
virtual bool isTriggered (uint vector)
Check if an IRQ vector is set.
Public Member Functions inherited from ARMInterrupt
ARMInterrupt (Address base=0x0)
Constructor.
Result install (Interrupt vector, Handler handler)
Install an interrupt handler.
Public Member Functions inherited from IntController
IntController ()
Constructor.
uint getBase () const
Get interrupt number base offset.
Private Attributes
ARMIO m_io
I/O instance.
Additional Inherited Members
Public Types inherited from ARMInterrupt
enum Interrupt {
Reset = 0, UndefinedInstruction, SoftwareInterrupt, PrefetchAbort,
DataAbort, Reserved, IRQ, FIQ
}
ARM interrupt types.
Public Types inherited from IntController
enum Result {
Success, InvalidIRQ, InvalidFrequency, IOError,
NotFound
}
Result codes.
typedef void Handler(struct CPUState state)
Function which is called when the CPU is interrupted.
Protected Attributes inherited from IntController
uint m_base
Interrupt number base offset.
Detailed Description
Raspberry Pi Interrupt Controller implementation.
Definition at line 50 of file BroadcomInterrupt.h.
Constructor & Destructor Documentation
BroadcomInterrupt()
BroadcomInterrupt::BroadcomInterrupt ()
Constructor.
Definition at line 37 of file BroadcomInterrupt.cpp.
References INTERRUPT_DISABLEIRQ1, INTERRUPT_DISABLEIRQ2, m_io, and ARMIO::write().
Member Function Documentation
clear()
BroadcomInterrupt::Result BroadcomInterrupt::clear (uint vector) virtual
Clear an IRQ vector.
Returns
Result code
Implements IntController.
Definition at line 84 of file BroadcomInterrupt.cpp.
References IntController::Success.
disable()
BroadcomInterrupt::Result BroadcomInterrupt::disable (uint vector) virtual
Disable an IRQ vector.
Returns
Result code
Implements IntController.
Definition at line 66 of file BroadcomInterrupt.cpp.
References INTERRUPT_DISABLEIRQ1, INTERRUPT_DISABLEIRQ2, m_io, IntController::Success, and ARMIO::write().
enable()
BroadcomInterrupt::Result BroadcomInterrupt::enable (uint vector) virtual
Enable an IRQ vector.
Returns
Result code
Implements IntController.
Definition at line 44 of file BroadcomInterrupt.cpp.
References INTERRUPT_ENABLEIRQ1, INTERRUPT_ENABLEIRQ2, m_io, IntController::Success, and ARMIO::write().
isTriggered()
bool BroadcomInterrupt::isTriggered (uint vector) virtual
Check if an IRQ vector is set.
Returns
Result code
Implements ARMInterrupt.
Definition at line 89 of file BroadcomInterrupt.cpp.
References INTERRUPT_BASICPEND, INTERRUPT_IRQPEND1, INTERRUPT_IRQPEND2, m_io, and ARMIO::read().
Field Documentation
m_io
ARMIO BroadcomInterrupt::m_io private
I/O instance.
Definition at line 90 of file BroadcomInterrupt.h.
Referenced by BroadcomInterrupt(), disable(), enable(), and isTriggered().
The documentation for this class was generated from the following files:
lib/libarch/arm/broadcom/BroadcomInterrupt.h
lib/libarch/arm/broadcom/BroadcomInterrupt.cpp