FreeNOS: IntelPIT Class Reference
IntelPIT Class Reference
lib » libarch » Intel
Intel 8254 Programmable Interrupt Timer (PIT).
#include <IntelPIT.h>
Public Member Functions
IntelPIT ()
Constructor.
uint getCounter ()
Get current timer counter.
virtual Result setFrequency (Size hertz)
Set interrupt frequency.
Result waitTrigger ()
Busy wait for one trigger period.
Public Member Functions inherited from Timer
struct Timer::Info ALIGN (8) Info
Timer information structure.
Timer ()
Constructor.
Size getInterrupt () const
Get timer interrupt number.
Size getFrequency () const
Get timer frequency.
virtual Result getCurrent (Info *info)
Get current timer info.
virtual Result initialize ()
Initialize the timer.
virtual Result start ()
Start the timer.
virtual Result stop ()
Stop the timer.
virtual Result tick ()
Process timer tick.
virtual Result wait (u32 microseconds) const
Busy wait a number of microseconds.
bool isExpired (const Info &info) const
Check if a timer value is expired.
Private Types
enum Registers { Control = 0x43, Channel0Data = 0x40 }
Hardware registers.
enum ControlFlags {
Channel0 = 0, LatchedRead = 0, AccessLowHigh = (3 << 4), SquareWave = (3 << 1),
RateGenerator = (2 << 1)
}
Control Register Flags.
Private Member Functions
Result setControl (ControlFlags flags)
Set Control register.
Private Attributes
IntelIO m_io
I/O instance.
Static Private Attributes
static const uint OscillatorFreq = 1193182
Oscillator frequency in hertz used by the PIT.
static const uint InterruptNumber = 0
The IRQ vector for channel 0 is fixed to IRQ0.
Additional Inherited Members
Public Types inherited from Timer
enum Result { Success, NotFound, IOError, InvalidFrequency }
Result codes.
Data Fields inherited from Timer
enum Timer::Result ALIGN
Protected Attributes inherited from Timer
Info m_info
The current Timer information.
Size m_frequency
Frequency of the Timer.
Size m_int
Timer interrupt number.
Detailed Description
Intel 8254 Programmable Interrupt Timer (PIT).
Definition at line 40 of file IntelPIT.h.
Member Enumeration Documentation
ControlFlags
enum IntelPIT::ControlFlags private
Control Register Flags.
Enumerator
Channel0
LatchedRead
AccessLowHigh
SquareWave
RateGenerator
Definition at line 62 of file IntelPIT.h.
Registers
enum IntelPIT::Registers private
Hardware registers.
Enumerator
Control
Channel0Data
Definition at line 53 of file IntelPIT.h.
Constructor & Destructor Documentation
IntelPIT()
IntelPIT::IntelPIT ()
Constructor.
Definition at line 20 of file IntelPIT.cpp.
References InterruptNumber, and Timer::m_int.
Member Function Documentation
getCounter()
uint IntelPIT::getCounter ()
Get current timer counter.
The timer counter is used internally by the PIT to generate interrupts on the desired frequency. The PIT will decrement the timer counter until 0 is reached, at which it will generate an interrupt and restart at the initial timer counter value.
Returns
Current timer counter.
Definition at line 26 of file IntelPIT.cpp.
References Channel0, Channel0Data, IntelIO::inb(), LatchedRead, m_io, and setControl().
Referenced by waitTrigger().
setControl()
IntelPIT::Result IntelPIT::setControl (IntelPIT::ControlFlags flags) private
Set Control register.
Parameters
flags New flags to set in the Control register.
Returns
Result code.
Definition at line 76 of file IntelPIT.cpp.
References Control, m_io, IntelIO::outb(), and Timer::Success.
Referenced by getCounter(), and setFrequency().
setFrequency()
IntelPIT::Result IntelPIT::setFrequency (Size hertz) virtual
Set interrupt frequency.
This function configures the PIT to generate interrupts on the given frequency. The new frequency will be applied immediately on the interrupts generated.
Parameters
hertz Number of interrupt triggers per second (in hertz)
Returns
Result code.
Reimplemented from Timer.
Definition at line 37 of file IntelPIT.cpp.
References AccessLowHigh, Channel0, Channel0Data, Timer::InvalidFrequency, Timer::m_frequency, m_io, OscillatorFreq, IntelIO::outb(), RateGenerator, setControl(), and Timer::Success.
Referenced by IntelKernel::IntelKernel().
waitTrigger()
IntelPIT::Result IntelPIT::waitTrigger ()
Busy wait for one trigger period.
Returns
Result code.
Definition at line 58 of file IntelPIT.cpp.
References getCounter(), and Timer::Success.
Referenced by IntelAPIC::start().
Field Documentation
InterruptNumber
const uint IntelPIT::InterruptNumber = 0 static private
The IRQ vector for channel 0 is fixed to IRQ0.
Definition at line 48 of file IntelPIT.h.
Referenced by IntelPIT().
m_io
IntelIO IntelPIT::m_io private
I/O instance.
Definition at line 126 of file IntelPIT.h.
Referenced by getCounter(), setControl(), and setFrequency().
OscillatorFreq
const uint IntelPIT::OscillatorFreq = 1193182 static private
Oscillator frequency in hertz used by the PIT.
Definition at line 45 of file IntelPIT.h.
Referenced by setFrequency().
The documentation for this class was generated from the following files:
lib/libarch/intel/IntelPIT.h
lib/libarch/intel/IntelPIT.cpp