FreeNOS: Mount Class Reference
Mount Class Reference
bin
Mount filesystems on the system.
#include <Mount.h>
Public Member Functions
Mount (int argc, char **argv)
Constructor.
virtual ~Mount ()
Destructor.
virtual Result exec ()
Execute the application.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
Mount filesystems on the system.
Definition at line 31 of file Mount.h.
Constructor & Destructor Documentation
Mount()
Mount::Mount (int argc, char ** argv)
Constructor.
Parameters
argc Argument count
argv Argument values
Definition at line 27 of file Mount.cpp.
References Application::parser(), and ArgumentParser::setDescription().
~Mount()
Mount::~Mount () virtual
Destructor.
Definition at line 33 of file Mount.cpp.
Member Function Documentation
exec()
Mount::Result Mount::exec () virtual
Execute the application.
Returns
Result code
Implements Application.
Definition at line 37 of file Mount.cpp.
References FILESYSTEM_MAXMOUNTS, getMounts(), mounts, PAGESIZE, printf(), MemoryMap::range(), API::Read, refreshMounts(), Application::Success, MemoryMap::UserArgs, Memory::Range::virt, and VMCopy().
The documentation for this class was generated from the following files:
bin/mount/Mount.h
bin/mount/Mount.cpp