FreeNOS: IntController Class Reference
IntController Class Reference abstract
lib » libarch
Interrupt controller interface.
#include <IntController.h>
Public Types
enum Result {
Success, InvalidIRQ, InvalidFrequency, IOError,
NotFound
}
Result codes.
typedef void Handler(struct CPUState state)
Function which is called when the CPU is interrupted.
Public Member Functions
IntController ()
Constructor.
uint getBase () const
Get interrupt number base offset.
virtual Result enable (uint irq)=0
Enable hardware interrupt (IRQ).
virtual Result disable (uint irq)=0
Disable hardware interrupt (IRQ).
virtual Result clear (uint irq)=0
Clear hardware interrupt (IRQ).
Protected Attributes
uint m_base
Interrupt number base offset.
Detailed Description
Interrupt controller interface.
Definition at line 38 of file IntController.h.
Member Typedef Documentation
Handler
typedef void IntController::Handler(struct CPUState state)
Function which is called when the CPU is interrupted.
Parameters
state State of the CPU on the moment the interrupt occurred.
Definition at line 59 of file IntController.h.
Member Enumeration Documentation
Result
enum IntController::Result
Result codes.
Enumerator
Success
InvalidIRQ
InvalidFrequency
IOError
NotFound
Definition at line 45 of file IntController.h.
Constructor & Destructor Documentation
IntController()
IntController::IntController ()
Constructor.
Definition at line 20 of file IntController.cpp.
Member Function Documentation
clear()
virtual Result IntController::clear (uint irq) pure virtual
Clear hardware interrupt (IRQ).
Clearing marks the end of an interrupt service routine and causes the controller to trigger the interrupt again on the next trigger moment.
Parameters
irq Interrupt Request number to clear.
Returns
Result code.
Implemented in IntelAPIC, IntelPIC, and BroadcomInterrupt.
Referenced by IntelKernel::interrupt().
disable()
virtual Result IntController::disable (uint irq) pure virtual
Disable hardware interrupt (IRQ).
Parameters
irq Interrupt Request number.
Returns
Result code.
Implemented in IntelAPIC, IntelPIC, and BroadcomInterrupt.
Referenced by Kernel::enableIRQ().
enable()
virtual Result IntController::enable (uint irq) pure virtual
Enable hardware interrupt (IRQ).
Parameters
irq Interrupt Request number.
Returns
Result code.
Implemented in IntelAPIC, IntelPIC, and BroadcomInterrupt.
Referenced by ARMKernel::ARMKernel(), and Kernel::enableIRQ().
getBase()
uint IntController::getBase () const
Get interrupt number base offset.
Some interrupt controllers remap the interrupt numbers to a certain base offset.
Returns
Interrupt number base offset.
Definition at line 25 of file IntController.cpp.
References m_base.
Referenced by IntelKernel::IntelKernel(), and IntelKernel::interrupt().
Field Documentation
m_base
uint IntController::m_base protected
Interrupt number base offset.
Definition at line 110 of file IntController.h.
Referenced by getBase(), and IntelPIC::IntelPIC().
The documentation for this class was generated from the following files:
lib/libarch/IntController.h
lib/libarch/IntController.cpp