FreeNOS: NetCat Class Reference
NetCat Class Reference
bin
Network send/receive (cat) application.
#include <NetCat.h>
Public Member Functions
NetCat (int argc, char **argv)
Class constructor.
virtual ~NetCat ()
Class destructor.
virtual Result initialize ()
Initialize the application.
virtual Result exec ()
Execute the application event loop.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Private Member Functions
Result readLine ()
Read one line from standard input.
Result udpSend ()
Send UDP packet.
Result udpReceive ()
Result printLine ()
Private Attributes
NetworkClient * m_client
Networking client.
int m_socket
Socket.
char m_lineBuf [64]
Line buffer.
Size m_lineLen
IPV4::Address m_host
Host IP.
u16 m_port
Host port.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
Network send/receive (cat) application.
Definition at line 34 of file NetCat.h.
Constructor & Destructor Documentation
NetCat()
NetCat::NetCat (int argc, char ** argv)
Class constructor.
Definition at line 33 of file NetCat.cpp.
References Application::parser(), ArgumentParser::registerFlag(), ArgumentParser::registerPositional(), and ArgumentParser::setDescription().
~NetCat()
NetCat::~NetCat () virtual
Class destructor.
Definition at line 50 of file NetCat.cpp.
Member Function Documentation
exec()
NetCat::Result NetCat::exec () virtual
Execute the application event loop.
Implements Application.
Definition at line 93 of file NetCat.cpp.
References Application::arguments(), DEBUG, printLine(), readLine(), Application::Success, udpReceive(), and udpSend().
initialize()
NetCat::Result NetCat::initialize () virtual
Initialize the application.
Reimplemented from Application.
Definition at line 54 of file NetCat.cpp.
References Application::arguments(), atoi(), NetworkClient::bindSocket(), NetworkClient::createSocket(), DEBUG, ERROR, NetworkClient::initialize(), Application::IOError, m_client, m_host, m_port, m_socket, Application::Success, NetworkClient::Success, IPV4::toAddress(), and NetworkClient::UDP.
printLine()
NetCat::Result NetCat::printLine () private
Definition at line 122 of file NetCat.cpp.
References m_lineBuf, m_lineLen, printf(), and Application::Success.
Referenced by exec().
readLine()
NetCat::Result NetCat::readLine () private
Read one line from standard input.
Definition at line 130 of file NetCat.cpp.
References DEBUG, exit(), m_lineBuf, m_lineLen, printf(), read(), strcmp(), Application::Success, and ZERO.
Referenced by exec().
udpReceive()
NetCat::Result NetCat::udpReceive () private
Definition at line 199 of file NetCat.cpp.
References sockaddr::addr, DEBUG, errno, ERROR, Application::IOError, m_lineBuf, m_socket, sockaddr::port, recvfrom(), strerror(), Application::Success, and ZERO.
Referenced by exec().
udpSend()
NetCat::Result NetCat::udpSend () private
Send UDP packet.
Definition at line 180 of file NetCat.cpp.
References sockaddr::addr, DEBUG, errno, ERROR, Application::IOError, m_host, m_lineBuf, m_lineLen, m_port, m_socket, sockaddr::port, sendto(), strerror(), and Application::Success.
Referenced by exec().
Field Documentation
m_client
NetworkClient* NetCat::m_client private
Networking client.
Definition at line 75 of file NetCat.h.
Referenced by initialize().
m_host
IPV4::Address NetCat::m_host private
Host IP.
Definition at line 85 of file NetCat.h.
Referenced by initialize(), and udpSend().
m_lineBuf
char NetCat::m_lineBuf[64] private
Line buffer.
Definition at line 81 of file NetCat.h.
Referenced by printLine(), readLine(), udpReceive(), and udpSend().
m_lineLen
Size NetCat::m_lineLen private
Definition at line 82 of file NetCat.h.
Referenced by printLine(), readLine(), and udpSend().
m_port
u16 NetCat::m_port private
Host port.
Definition at line 88 of file NetCat.h.
Referenced by initialize(), and udpSend().
m_socket
int NetCat::m_socket private
Socket.
Definition at line 78 of file NetCat.h.
Referenced by initialize(), udpReceive(), and udpSend().
The documentation for this class was generated from the following files:
bin/netcat/NetCat.h
bin/netcat/NetCat.cpp