FreeNOS: UnixName Class Reference
UnixName Class Reference
bin
Print the operating system name.
#include <UnixName.h>
Public Member Functions
UnixName (int argc, char **argv)
Constructor.
virtual ~UnixName ()
Destructor.
virtual Result exec ()
Execute the application.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
Print the operating system name.
Definition at line 31 of file UnixName.h.
Constructor & Destructor Documentation
UnixName()
UnixName::UnixName (int argc, char ** argv)
Constructor.
Parameters
argc Argument count
argv Argument values
Definition at line 25 of file UnixName.cpp.
References Application::parser(), ArgumentParser::registerFlag(), and ArgumentParser::setDescription().
~UnixName()
UnixName::~UnixName () virtual
Destructor.
Definition at line 36 of file UnixName.cpp.
Member Function Documentation
exec()
UnixName::Result UnixName::exec () virtual
Execute the application.
Returns
Result code
Implements Application.
Definition at line 40 of file UnixName.cpp.
References Application::arguments(), errno, ERROR, Application::IOError, utsname::machine, utsname::nodename, printf(), utsname::release, strerror(), Application::Success, utsname::sysname, uname(), and utsname::version.
The documentation for this class was generated from the following files:
bin/uname/UnixName.h
bin/uname/UnixName.cpp