FreeNOS: LinnDirectory Class Reference
LinnDirectory Class Reference
server » LinnFS
Represents an directory on a LinnFS filesystem.
#include <LinnDirectory.h>
Public Member Functions
LinnDirectory (LinnFileSystem *fs, LinnInode *inode)
Constructor function.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read directory entries.
virtual File * lookup (const char *name)
Retrieves a File pointer for the given entry name.
Public Member Functions inherited from Directory
Directory ()
Constructor.
virtual ~Directory ()
Destructor.
void insert (FileType type, const char *name,...)
Insert a new directory entry.
void remove (const char *name)
Remove a directory entry.
void clear ()
Clears the internal list of entries.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Member Functions
bool getLinnDirectoryEntry (LinnDirectoryEntry *dent, const char *name)
Retrieve a directory entry.
Private Attributes
LinnFileSystem * fs
Filesystem pointer.
LinnInode * inode
Inode which describes the directory.
Additional Inherited Members
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
Represents an directory on a LinnFS filesystem.
See also
Directory
LinnDirectoryEntry
LinnFileSystem
Definition at line 45 of file LinnDirectory.h.
Constructor & Destructor Documentation
LinnDirectory()
LinnDirectory::LinnDirectory (LinnFileSystem * fs, LinnInode * inode)
Constructor function.
Parameters
fs Filesystem pointer.
inode Inode pointer.
See also
LinnFileSystem
LinnInode
Definition at line 22 of file LinnDirectory.cpp.
References inode, File::m_access, File::m_size, LinnInode::mode, and LinnInode::size.
Referenced by lookup().
Member Function Documentation
getLinnDirectoryEntry()
bool LinnDirectory::getLinnDirectoryEntry (LinnDirectoryEntry * dent, const char * name) private
Retrieve a directory entry.
Parameters
dent LinnDirectoryEntry buffer pointer.
name Unique name of the entry.
Returns
True if successful, false otherwise.
Definition at line 110 of file LinnDirectory.cpp.
References LinnInode::block, LinnSuperBlock::blockSize, fs, LinnFileSystem::getStorage(), LinnFileSystem::getSuperBlock(), inode, LINN_DIRENT_PER_BLOCK, LINN_INODE_NUM_BLOCKS, LinnDirectoryEntry::name, Storage::read(), and strcmp().
Referenced by lookup().
lookup()
File * LinnDirectory::lookup (const char * name) virtual
Retrieves a File pointer for the given entry name.
This function reads a file from disk corresponding to the LinnInode of the given entry name. It returns an File object associated with that LinnInode.
Parameters
name Name of the entry to lookup.
Returns
Pointer to a File if found, or ZERO otherwise.
See also
File
LinnInode
Reimplemented from Directory.
Definition at line 83 of file LinnDirectory.cpp.
References DirectoryFile, fs, LinnFileSystem::getInode(), getLinnDirectoryEntry(), LinnDirectoryEntry::inode, inode, LinnDirectory(), RegularFile, LinnInode::type, and ZERO.
read()
Error LinnDirectory::read (IOBuffer & buffer, Size size, Size offset) virtual
Read directory entries.
Parameters
buffer Input/Output buffer to write bytes to.
size Number of bytes to copy at maximum.
offset Offset in the file to start reading.
Returns
Number of bytes read on success, Error on failure.
See also
IOBuffer
Reimplemented from Directory.
Definition at line 31 of file LinnDirectory.cpp.
References LinnInode::block, LinnSuperBlock::blockSize, EACCES, EFAULT, EINVAL, fs, LinnFileSystem::getInode(), LinnFileSystem::getStorage(), LinnFileSystem::getSuperBlock(), LinnDirectoryEntry::inode, inode, LINN_DIRENT_NAME_LEN, LINN_INODE_DIR_BLOCKS, Dirent::name, LinnDirectoryEntry::name, Storage::read(), LinnInode::size, strlcpy(), Dirent::type, LinnInode::type, IOBuffer::write(), and ZERO.
Field Documentation
fs
LinnFileSystem* LinnDirectory::fs private
Filesystem pointer.
Definition at line 105 of file LinnDirectory.h.
Referenced by getLinnDirectoryEntry(), lookup(), and read().
inode
LinnInode* LinnDirectory::inode private
Inode which describes the directory.
Definition at line 108 of file LinnDirectory.h.
Referenced by getLinnDirectoryEntry(), LinnDirectory(), lookup(), and read().
The documentation for this class was generated from the following files:
server/filesystem/linn/LinnDirectory.h
server/filesystem/linn/LinnDirectory.cpp