FreeNOS: TestChar< T > Class Template Reference
TestChar< T > Class Template Reference
lib » libtest
Generate test data for character strings.
#include <TestChar.h>
Public Member Functions
TestChar (Size min, Size max)
Constructor.
virtual ~TestChar ()
Destructor.
virtual T random (Size count=1)
Get random test value(s).
virtual T unique (Size count=1)
Get unique random test value(s).
virtual Size length (Size position)
Get the length of the generated character string.
template<>
char * random (Size count)
Get random test value(s).
template<>
char * unique (Size count)
Get unique random test value(s).
Public Member Functions inherited from TestData< T >
TestData ()
Constructor.
virtual ~TestData ()
Destructor.
void seed ()
Initialize the random number generator.
Size count () const
The number of generated values.
T & get (Size index)
Retrieve previously random generated test data by index.
T & operator[] (Size index)
Retrieve previously random generated test data by index.
Private Attributes
Size m_max
Maximum value.
Size m_min
Minimum value.
Vector< Size > m_lengths
String lengths.
Additional Inherited Members
Protected Attributes inherited from TestData< T >
Vector< T > m_values
Vector with generated values.
Detailed Description
template<class T>
class TestChar< T >
Generate test data for character strings.
Definition at line 35 of file TestChar.h.
Constructor & Destructor Documentation
TestChar()
template<class T > TestChar< T >::TestChar (Size min, Size max) inline
Constructor.
Parameters
min Minimum length of the character strings.
max Maximum length of the character strings.
Definition at line 45 of file TestChar.h.
References TestChar< T >::m_max, and TestChar< T >::m_min.
~TestChar()
template<class T > virtual TestChar< T >::~TestChar () inline virtual
Destructor.
Definition at line 54 of file TestChar.h.
References TestData< T >::count(), TestData< T >::m_values, TestChar< T >::random(), and TestChar< T >::unique().
Member Function Documentation
length()
template<class T > virtual Size TestChar< T >::length (Size position) inline virtual
Get the length of the generated character string.
Definition at line 81 of file TestChar.h.
References TestChar< T >::m_lengths.
random() [1/2]
template<class T > virtual T TestChar< T >::random (Size count = 1) virtual
Get random test value(s).
Parameters
count Number or values to generate.
Returns
The last generated T value.
Implements TestData< T >.
Referenced by TestChar< T >::~TestChar().
random() [2/2]
template<> char * TestChar< char * >::random (Size count) virtual
Get random test value(s).
Parameters
count Number or values to generate.
Returns
The last generated T value.
Implements TestData< T >.
Definition at line 98 of file TestChar.h.
References Vector< T >::insert(), TestChar< T >::m_lengths, TestChar< T >::m_max, TestChar< T >::m_min, TestData< T >::m_values, TestInt< T >::random(), and ZERO.
unique() [1/2]
template<class T > virtual T TestChar< T >::unique (Size count = 1) virtual
Get unique random test value(s).
Parameters
count Number of unique values to generate.
Returns
The last generated T value.
Implements TestData< T >.
Referenced by TestChar< T >::~TestChar().
unique() [2/2]
template<> char * TestChar< char * >::unique (Size count) virtual
Get unique random test value(s).
Parameters
count Number of unique values to generate.
Returns
The last generated T value.
Implements TestData< T >.
Definition at line 122 of file TestChar.h.
References MemoryBlock::copy(), TestData< T >::count(), Vector< T >::insert(), TestChar< T >::m_lengths, TestChar< T >::m_max, TestChar< T >::m_min, TestData< T >::m_values, TestInt< T >::random(), and ZERO.
Field Documentation
m_lengths
template<class T > Vector<Size> TestChar< T >::m_lengths private
String lengths.
Definition at line 95 of file TestChar.h.
Referenced by TestChar< T >::length(), TestChar< T >::random(), and TestChar< T >::unique().
m_max
template<class T > Size TestChar< T >::m_max private
Maximum value.
Definition at line 89 of file TestChar.h.
Referenced by TestChar< T >::random(), TestChar< T >::TestChar(), and TestChar< T >::unique().
m_min
template<class T > Size TestChar< T >::m_min private
Minimum value.
Definition at line 92 of file TestChar.h.
Referenced by TestChar< T >::random(), TestChar< T >::TestChar(), and TestChar< T >::unique().
The documentation for this class was generated from the following file:
lib/libtest/TestChar.h