FreeNOS: BootImageStorage Class Reference
BootImageStorage Class Reference
lib » libfs
Uses a BootImage symbol entry as filesystem storage provider (aka RamFS).
#include <BootImageStorage.h>
Public Member Functions
BootImageStorage (const char *name)
Constructor function.
bool load ()
Loads the boot module into virtual memory.
virtual Error read (u64 offset, void *buffer, Size size)
Reads data from the boot module.
virtual u64 capacity () const
Retrieve maximum storage capacity.
Public Member Functions inherited from Storage
Storage ()
Constructor function.
virtual ~Storage ()
Destructor function.
virtual Error write (u64 offset, void *buffer, Size size)
Write a contiguous set of data.
Private Attributes
const char * m_name
Name of the BootSymbol.
u8 * m_data
Data pointer.
Size m_size
Size of the BootSymbol.
Detailed Description
Uses a BootImage symbol entry as filesystem storage provider (aka RamFS).
Definition at line 36 of file BootImageStorage.h.
Constructor & Destructor Documentation
BootImageStorage()
BootImageStorage::BootImageStorage (const char * name)
Constructor function.
Parameters
name Name of the BootSymbol entry to use.
Definition at line 22 of file BootImageStorage.cpp.
References m_data, m_name, m_size, name, and ZERO.
Member Function Documentation
capacity()
u64 BootImageStorage::capacity () const virtual
Retrieve maximum storage capacity.
Returns
Storage capacity.
Implements Storage.
Definition at line 76 of file BootImageStorage.cpp.
References m_size.
load()
bool BootImageStorage::load ()
Loads the boot module into virtual memory.
Returns
True on success, false otherwise.
Definition at line 29 of file BootImageStorage.cpp.
References Memory::Range::access, SystemInformation::bootImageAddress, SystemInformation::bootImageSize, m_data, m_name, m_size, Map, BootSymbol::name, BootSegment::offset, Memory::Range::phys, Memory::Readable, BootSymbol::segmentsOffset, BootImage::segmentsTableOffset, BootSymbol::segmentsTotalSize, SELF, Memory::Range::size, strcmp(), BootImage::symbolTableCount, BootImage::symbolTableOffset, Memory::User, Memory::Range::virt, VMCtl(), and ZERO.
Referenced by main().
read()
Error BootImageStorage::read (u64 offset, void * buffer, Size size) virtual
Reads data from the boot module.
Parameters
offset Offset to start reading from.
buffer Output buffer.
size Number of bytes to copied.
Returns
Error code
Reimplemented from Storage.
Definition at line 70 of file BootImageStorage.cpp.
References m_data, and memcpy().
Field Documentation
m_data
u8* BootImageStorage::m_data private
Data pointer.
Definition at line 78 of file BootImageStorage.h.
Referenced by BootImageStorage(), load(), and read().
m_name
const char* BootImageStorage::m_name private
Name of the BootSymbol.
Definition at line 75 of file BootImageStorage.h.
Referenced by BootImageStorage(), and load().
m_size
Size BootImageStorage::m_size private
Size of the BootSymbol.
Definition at line 81 of file BootImageStorage.h.
Referenced by BootImageStorage(), capacity(), and load().
The documentation for this class was generated from the following files:
lib/libfs/BootImageStorage.h
lib/libfs/BootImageStorage.cpp