FreeNOS: ChannelClient Class Reference
ChannelClient Class Reference
lib » libipc
Client for using Channels.
#include <ChannelClient.h>
Data Structures
struct Request
Holds an outgoing request.
Public Types
enum Result {
Success, InvalidArgument, InvalidSize, IOError,
OutOfMemory, NotFound
}
Result codes.
Public Member Functions
ChannelClient ()
Constructor.
virtual ~ChannelClient ()
Destructor.
ChannelRegistry * getRegistry ()
Get channel registry.
Result setRegistry (ChannelRegistry *registry)
Assign channel registry.
virtual Result initialize ()
Initialize the ChannelClient.
virtual Result connect (ProcessID pid, Size msgSize=sizeof(FileSystemMessage))
Connect to a process.
virtual Result receiveAny (void *buffer, ProcessID *pid)
Try to receive message from any channel.
virtual Result sendRequest (ProcessID pid, void *buffer, CallbackFunction *callback)
Send asynchronous request message.
virtual Result processResponse (ProcessID pid, ChannelMessage *msg)
Process a response message.
virtual Result syncReceiveFrom (void *buffer, ProcessID pid)
Synchronous receive from one process.
virtual Result syncSendTo (void *buffer, ProcessID pid)
Synchronous send to one process.
virtual Result syncSendReceive (void *buffer, ProcessID pid)
Synchronous send and receive to/from one process.
Public Member Functions inherited from Singleton< ChannelClient >
Singleton (ChannelClient *obj)
Constructor.
Private Types
typedef struct ChannelClient::Request Request
Holds an outgoing request.
Private Member Functions
Channel * findConsumer (ProcessID pid)
Get consumer for a process.
Channel * findProducer (ProcessID pid)
Get producer for a process.
Private Attributes
ChannelRegistry * m_registry
Contains registered channels.
Index< Request > m_requests
Contains ongoing requests.
Additional Inherited Members
Static Public Attributes inherited from Singleton< ChannelClient >
static ChannelClient * instance
One and only instance.
Detailed Description
Client for using Channels.
Definition at line 40 of file ChannelClient.h.
Member Typedef Documentation
Request
typedef struct ChannelClient::Request ChannelClient::Request private
Holds an outgoing request.
Member Enumeration Documentation
Result
enum ChannelClient::Result
Result codes.
Enumerator
Success
InvalidArgument
InvalidSize
IOError
OutOfMemory
NotFound
Definition at line 71 of file ChannelClient.h.
Constructor & Destructor Documentation
ChannelClient()
ChannelClient::ChannelClient ()
Constructor.
Definition at line 24 of file ChannelClient.cpp.
References m_registry.
~ChannelClient()
ChannelClient::~ChannelClient () virtual
Destructor.
Definition at line 30 of file ChannelClient.cpp.
Member Function Documentation
connect()
ChannelClient::Result ChannelClient::connect (ProcessID pid, Size msgSize = sizeof(FileSystemMessage)) virtual
Connect to a process.
This function creates a producer and consumer Channel to the given process and registers it with the ChannelRegistry.
Parameters
pid ProcessID for the process to connect to.
msgSize Default message size to use.
Returns
Result code
Definition at line 50 of file ChannelClient.cpp.
References Memory::Range::access, API::AlreadyExists, Channel::Consumer, ProcessShares::MemoryShare::coreId, SystemInformation::coreId, API::Create, IOError, m_registry, OutOfMemory, PAGESIZE, Memory::Range::phys, ProcessShares::MemoryShare::pid, Channel::Producer, ProcessShares::MemoryShare::range, Memory::Readable, ChannelRegistry::registerConsumer(), ChannelRegistry::registerProducer(), MemoryChannel::setMessageSize(), Channel::setMode(), MemoryChannel::setVirtual(), Memory::Range::size, Channel::Success, API::Success, Success, ProcessShares::MemoryShare::tagId, Memory::User, Memory::Range::virt, VMShare(), and Memory::Writable.
Referenced by findConsumer(), and findProducer().
findConsumer()
Channel * ChannelClient::findConsumer (ProcessID pid) private
Get consumer for a process.
Parameters
pid ProcessID of the process
Returns
Channel object if found or ZERO otherwise.
Definition at line 211 of file ChannelClient.cpp.
References connect(), ChannelRegistry::getConsumer(), m_registry, Success, and ZERO.
Referenced by syncReceiveFrom().
findProducer()
Channel * ChannelClient::findProducer (ProcessID pid) private
Get producer for a process.
Parameters
pid ProcessID of the process
Returns
Channel object if found or ZERO otherwise.
Definition at line 225 of file ChannelClient.cpp.
References connect(), ChannelRegistry::getProducer(), m_registry, Success, and ZERO.
Referenced by sendRequest(), and syncSendTo().
getRegistry()
ChannelRegistry * ChannelClient::getRegistry ()
Get channel registry.
Returns
ChannelRegistry object pointer or ZERO if not set
Definition at line 34 of file ChannelClient.cpp.
References m_registry.
Referenced by ChannelServer< FileSystem, FileSystemMessage >::ChannelServer().
initialize()
ChannelClient::Result ChannelClient::initialize () virtual
Initialize the ChannelClient.
Returns
Result code
Definition at line 45 of file ChannelClient.cpp.
References Success.
processResponse()
ChannelClient::Result ChannelClient::processResponse (ProcessID pid, ChannelMessage * msg) virtual
Process a response message.
Parameters
pid ProcessID from which we receive the message
msg Message which is received
Returns
Result code
Definition at line 189 of file ChannelClient.cpp.
References ChannelClient::Request::active, ChannelClient::Request::callback, CallbackFunction::execute(), ChannelMessage::identifier, m_requests, ChannelClient::Request::message, NotFound, ChannelClient::Request::pid, and Success.
receiveAny()
ChannelClient::Result ChannelClient::receiveAny (void * buffer, ProcessID * pid) virtual
Try to receive message from any channel.
Parameters
buffer Message buffer for output
pid ProcessID for output
Returns
Result code
Definition at line 128 of file ChannelClient.cpp.
References ChannelRegistry::getConsumers(), HashIterator< K, V >::hasCurrent(), m_registry, NotFound, Channel::Success, and Success.
sendRequest()
ChannelClient::Result ChannelClient::sendRequest (ProcessID pid, void * buffer, CallbackFunction * callback) virtual
Send asynchronous request message.
The client assigns an internal request identifier for the message and ensures that the callback will be called when a response messages is received.
Parameters
pid ProcessID to send the message to
buffer Points to message to send
callback Called when response message is received
Returns
Result code
Definition at line 141 of file ChannelClient.cpp.
References ChannelClient::Request::active, ChannelClient::Request::callback, MemoryBlock::copy(), DEBUG, findProducer(), Channel::getMessageSize(), ChannelMessage::identifier, IOError, m_requests, ChannelClient::Request::message, NotFound, ChannelClient::Request::pid, ProcessCtl(), ChannelMessage::Request, Resume, Channel::Success, Success, ChannelMessage::type, and Channel::write().
setRegistry()
ChannelClient::Result ChannelClient::setRegistry (ChannelRegistry * registry)
Assign channel registry.
Parameters
registry ChannelRegistry object pointer
Returns
Result code
Definition at line 39 of file ChannelClient.cpp.
References m_registry, and Success.
Referenced by setupChannels().
syncReceiveFrom()
ChannelClient::Result ChannelClient::syncReceiveFrom (void * buffer, ProcessID pid) virtual
Synchronous receive from one process.
Parameters
buffer Message buffer for output
pid ProcessID for the channel
Returns
Result code
Definition at line 239 of file ChannelClient.cpp.
References EnterSleep, findConsumer(), NotFound, ProcessCtl(), Channel::read(), SELF, Channel::Success, and Success.
Referenced by syncSendReceive().
syncSendReceive()
ChannelClient::Result ChannelClient::syncSendReceive (void * buffer, ProcessID pid) virtual
Synchronous send and receive to/from one process.
Parameters
buffer Message buffer to send/receive
pid ProcessID for the channel
Returns
Result code
Definition at line 277 of file ChannelClient.cpp.
References Success, syncReceiveFrom(), and syncSendTo().
Referenced by creat(), SysInfo::exec(), mkdir(), mknod(), MPI_Init(), open(), read(), refreshMounts(), stat(), unlink(), waitMount(), and write().
syncSendTo()
ChannelClient::Result ChannelClient::syncSendTo (void * buffer, ProcessID pid) virtual
Synchronous send to one process.
Parameters
buffer Message buffer to send
pid ProcessID for the channel
Returns
Result code
Definition at line 251 of file ChannelClient.cpp.
References Channel::ChannelFull, findProducer(), IOError, NotFound, ProcessCtl(), Resume, Schedule, SELF, Channel::Success, Success, and Channel::write().
Referenced by CoreServer::createProcess(), and syncSendReceive().
Field Documentation
m_registry
ChannelRegistry* ChannelClient::m_registry private
Contains registered channels.
Definition at line 220 of file ChannelClient.h.
Referenced by ChannelClient(), connect(), findConsumer(), findProducer(), getRegistry(), receiveAny(), and setRegistry().
m_requests
Index<Request> ChannelClient::m_requests private
Contains ongoing requests.
Definition at line 223 of file ChannelClient.h.
Referenced by processResponse(), and sendRequest().
The documentation for this class was generated from the following files:
lib/libipc/ChannelClient.h
lib/libipc/ChannelClient.cpp