FreeNOS: IntelACPI Class Reference
IntelACPI Class Reference
lib » libarch » Intel
Intel Advanced Configuration and Power Interface (ACPI).
#include <IntelACPI.h>
Data Structures
struct ExtendedSystemTable
Extended System Descriptor Table (XSDT)
struct MultipleAPICTable
Multiple APIC Description Table (MADT).
struct MultipleAPICTableEntry
Multiple APIC Description Table (MADT) entry.
struct MultipleAPICTableProc
Multiple APIC Description Table (MADT) processor entry.
struct RootSystemDescriptor1
Root System Description Pointer (ACPI v1.0).
struct RootSystemDescriptor2
Root System Description Pointer (ACPI v2.0)
struct RootSystemTable
Root System Descriptor Table (RSDT)
struct SystemDescriptorHeader
System Descriptor Header (ACPI v3.0)
Public Member Functions
IntelACPI ()
Constructor.
Result initialize ()
Initialize the ACPI.
virtual Result discover ()
Discover processors.
virtual Result boot (CoreInfo *info)
Boot a processor.
Public Member Functions inherited from CoreManager
CoreManager ()
Constructor.
List< uint > & getCores ()
Get list of core identities.
Private Types
enum Registers
Hardware registers.
typedef struct IntelACPI::RootSystemTable RootSystemTable
Root System Descriptor Table (RSDT)
typedef struct IntelACPI::ExtendedSystemTable ExtendedSystemTable
Extended System Descriptor Table (XSDT)
typedef struct IntelACPI::MultipleAPICTableEntry MultipleAPICTableEntry
Multiple APIC Description Table (MADT) entry.
typedef struct IntelACPI::MultipleAPICTableProc MultipleAPICTableProc
Multiple APIC Description Table (MADT) processor entry.
typedef struct IntelACPI::MultipleAPICTable MultipleAPICTable
Multiple APIC Description Table (MADT).
Private Member Functions
struct IntelACPI::RootSystemDescriptor1 __attribute__ ((packed)) RootSystemDescriptor1
Root System Description Pointer (ACPI v1.0).
struct IntelACPI::RootSystemDescriptor2 __attribute__ ((packed)) RootSystemDescriptor2
Root System Description Pointer (ACPI v2.0)
struct IntelACPI::SystemDescriptorHeader __attribute__ ((packed)) SystemDescriptorHeader
System Descriptor Header (ACPI v3.0)
Result scanAPIC (MultipleAPICTable *madt)
Scan for cores in the APIC tables.
Private Attributes
IntelIO m_bios
I/O object for searching the RootSystemDescriptor.
IntelIO m_rootIO
Root/Extended SDT table I/O object.
Static Private Attributes
static const uint RSDBase = 0x1000
Memory base address for searching the RootSystemDescriptor.
static const uint RSDSize = MegaByte(1) - 0x1000
Size of the memory region for searching the RootSystemDescriptor.
static const uint RootSystemSignature1 = 0x20445352
Signature to detect a valid RootSystemDescriptor (part 1).
static const uint RootSystemSignature2 = 0x20525450
Signature to detect a valid RootSystemDescriptor (part 2).
static const u32 RootSystemTableSignature = 0x54445352
Signature for the Root System Descriptor Table (RSDT).
static const u32 ExtendedSystemTableSignature = 0x54445358
Signature for the Extended System Descriptor Table (XSDT).
static const u32 MultipleAPICTableSignature = 0x43495041
Signature for the Multiple APIC Descriptor Table (MADT).
Additional Inherited Members
Public Types inherited from CoreManager
enum Result { Success, IOError, NotFound }
Result codes.
Protected Attributes inherited from CoreManager
List< uint > m_cores
List of core ids found.
Detailed Description
Intel Advanced Configuration and Power Interface (ACPI).
Definition at line 39 of file IntelACPI.h.
Member Typedef Documentation
ExtendedSystemTable
typedef struct IntelACPI::ExtendedSystemTable IntelACPI::ExtendedSystemTable private
Extended System Descriptor Table (XSDT)
MultipleAPICTable
typedef struct IntelACPI::MultipleAPICTable IntelACPI::MultipleAPICTable private
Multiple APIC Description Table (MADT).
MultipleAPICTableEntry
typedef struct IntelACPI::MultipleAPICTableEntry IntelACPI::MultipleAPICTableEntry private
Multiple APIC Description Table (MADT) entry.
MultipleAPICTableProc
typedef struct IntelACPI::MultipleAPICTableProc IntelACPI::MultipleAPICTableProc private
Multiple APIC Description Table (MADT) processor entry.
RootSystemTable
typedef struct IntelACPI::RootSystemTable IntelACPI::RootSystemTable private
Root System Descriptor Table (RSDT)
Member Enumeration Documentation
Registers
enum IntelACPI::Registers private
Hardware registers.
Definition at line 164 of file IntelACPI.h.
Constructor & Destructor Documentation
IntelACPI()
IntelACPI::IntelACPI ()
Constructor.
Definition at line 22 of file IntelACPI.cpp.
References m_bios, IO::map(), RSDBase, and RSDSize.
Member Function Documentation
__attribute__() [1/3]
struct IntelACPI::RootSystemDescriptor1 IntelACPI::__attribute__ ((packed)) private
Root System Description Pointer (ACPI v1.0).
__attribute__() [2/3]
struct IntelACPI::RootSystemDescriptor2 IntelACPI::__attribute__ ((packed)) private
Root System Description Pointer (ACPI v2.0)
__attribute__() [3/3]
struct IntelACPI::SystemDescriptorHeader IntelACPI::__attribute__ ((packed)) private
System Descriptor Header (ACPI v3.0)
boot()
IntelACPI::Result IntelACPI::boot (CoreInfo * info) virtual
Boot a processor.
Parameters
info CoreInfo object pointer.
Returns
Result code.
Implements CoreManager.
Definition at line 148 of file IntelACPI.cpp.
References CoreManager::IOError.
discover()
IntelACPI::Result IntelACPI::discover () virtual
Discover processors.
Returns
Result code.
Implements CoreManager.
Definition at line 97 of file IntelACPI.cpp.
References List< T >::clear(), DEBUG, IntelACPI::RootSystemTable::entry, IntelACPI::ExtendedSystemTable::entry, ExtendedSystemTableSignature, IO::getBase(), IntelACPI::RootSystemTable::header, IntelACPI::ExtendedSystemTable::header, IntelACPI::SystemDescriptorHeader::length, CoreManager::m_cores, m_rootIO, IO::map(), MultipleAPICTableSignature, PAGESIZE, RootSystemTableSignature, scanAPIC(), IntelACPI::SystemDescriptorHeader::signature, CoreManager::Success, and IO::unmap().
initialize()
IntelACPI::Result IntelACPI::initialize ()
Initialize the ACPI.
Returns
Result code.
Definition at line 27 of file IntelACPI.cpp.
References DEBUG, IO::getBase(), m_bios, m_rootIO, IO::map(), CoreManager::NotFound, NOTICE, PAGESIZE, IntelACPI::RootSystemDescriptor1::revision, RootSystemSignature1, RootSystemSignature2, RSDSize, IntelACPI::RootSystemDescriptor1::rsdtAddress, IntelACPI::RootSystemDescriptor1::signature, CoreManager::Success, IntelACPI::RootSystemDescriptor2::xsdtAddress, and ZERO.
scanAPIC()
IntelACPI::Result IntelACPI::scanAPIC (MultipleAPICTable * madt) private
Scan for cores in the APIC tables.
Returns
Result code.
Definition at line 66 of file IntelACPI.cpp.
References IntelACPI::MultipleAPICTableProc::apicId, List< T >::append(), DEBUG, IntelACPI::MultipleAPICTable::entry, IntelACPI::MultipleAPICTable::header, IntelACPI::SystemDescriptorHeader::length, IntelACPI::MultipleAPICTableEntry::length, CoreManager::m_cores, CoreManager::Success, and IntelACPI::MultipleAPICTableEntry::type.
Referenced by discover().
Field Documentation
ExtendedSystemTableSignature
const u32 IntelACPI::ExtendedSystemTableSignature = 0x54445358 static private
Signature for the Extended System Descriptor Table (XSDT).
Definition at line 59 of file IntelACPI.h.
Referenced by discover().
m_bios
IntelIO IntelACPI::m_bios private
I/O object for searching the RootSystemDescriptor.
Definition at line 210 of file IntelACPI.h.
Referenced by initialize(), and IntelACPI().
m_rootIO
IntelIO IntelACPI::m_rootIO private
Root/Extended SDT table I/O object.
Definition at line 213 of file IntelACPI.h.
Referenced by discover(), and initialize().
MultipleAPICTableSignature
const u32 IntelACPI::MultipleAPICTableSignature = 0x43495041 static private
Signature for the Multiple APIC Descriptor Table (MADT).
Definition at line 62 of file IntelACPI.h.
Referenced by discover().
RootSystemSignature1
const uint IntelACPI::RootSystemSignature1 = 0x20445352 static private
Signature to detect a valid RootSystemDescriptor (part 1).
Definition at line 50 of file IntelACPI.h.
Referenced by initialize().
RootSystemSignature2
const uint IntelACPI::RootSystemSignature2 = 0x20525450 static private
Signature to detect a valid RootSystemDescriptor (part 2).
Definition at line 53 of file IntelACPI.h.
Referenced by initialize().
RootSystemTableSignature
const u32 IntelACPI::RootSystemTableSignature = 0x54445352 static private
Signature for the Root System Descriptor Table (RSDT).
Definition at line 56 of file IntelACPI.h.
Referenced by discover().
RSDBase
const uint IntelACPI::RSDBase = 0x1000 static private
Memory base address for searching the RootSystemDescriptor.
Definition at line 44 of file IntelACPI.h.
Referenced by IntelACPI().
RSDSize
const uint IntelACPI::RSDSize = MegaByte(1) - 0x1000 static private
Size of the memory region for searching the RootSystemDescriptor.
Definition at line 47 of file IntelACPI.h.
Referenced by initialize(), and IntelACPI().
The documentation for this class was generated from the following files:
lib/libarch/intel/IntelACPI.h
lib/libarch/intel/IntelACPI.cpp