FreeNOS: Argument Class Reference
Argument Class Reference
lib » libstd
Represents program command line argument.
#include <Argument.h>
Public Member Functions
Argument (const char *name)
Class constructor.
Argument (const String &name)
Class constructor.
char getIdentifier () const
Get single character identifier
const String & getName () const
Retrieve argument name.
const String & getDescription () const
Retrieve single line argument description.
const String & getValue () const
Retrieve argument option value (if any)
Size getCount () const
Retrieve maximum argument count (if set)
void setIdentifier (char id)
Set argument identifier.
void setName (const char *name)
Set argument name.
void setDescription (const char *description)
Set argument single line description.
void setValue (const char *value)
Set argument option value
void setCount (Size count)
Set argument maximum count.
bool operator== (const Argument &arg) const
Equality operator: compares argument identifier.
bool operator!= (const Argument &arg) const
Non-equality operator.
Private Attributes
char m_id
Argument identifier (single character)
String m_name
Argument name.
String m_description
Argument description in a single line.
String m_value
Optional argument value.
Size m_count
Maximum argument count.
Detailed Description
Represents program command line argument.
Definition at line 35 of file Argument.h.
Constructor & Destructor Documentation
Argument() [1/2]
Argument::Argument (const char * name)
Class constructor.
Parameters
name Input argument name
Definition at line 20 of file Argument.cpp.
Argument() [2/2]
Argument::Argument (const String & name)
Class constructor.
Parameters
name Input argument name
Definition at line 27 of file Argument.cpp.
Member Function Documentation
getCount()
Size Argument::getCount () const
Retrieve maximum argument count (if set)
Returns
Maximum argument count
Definition at line 39 of file Argument.cpp.
References m_count.
getDescription()
const String & Argument::getDescription () const
Retrieve single line argument description.
Returns
Argument description
Definition at line 49 of file Argument.cpp.
References m_description.
getIdentifier()
char Argument::getIdentifier () const
Get single character identifier
Returns
Single character identifier
Definition at line 34 of file Argument.cpp.
References m_id.
getName()
const String & Argument::getName () const
Retrieve argument name.
Returns
Argument name
Definition at line 44 of file Argument.cpp.
References m_name.
Referenced by ArgumentContainer::addFlag(), and ArgumentContainer::get().
getValue()
const String & Argument::getValue () const
Retrieve argument option value (if any)
Returns
Argument value
Definition at line 54 of file Argument.cpp.
References m_value.
Referenced by ArgumentContainer::get().
operator!=()
bool Argument::operator!= (const Argument & arg) const
Non-equality operator.
Parameters
arg Argument reference
Returns
Boolean
Definition at line 89 of file Argument.cpp.
References m_id.
operator==()
bool Argument::operator== (const Argument & arg) const
Equality operator: compares argument identifier.
Parameters
arg Argument reference
Returns
Boolean
Definition at line 84 of file Argument.cpp.
References m_id.
setCount()
void Argument::setCount (Size count)
Set argument maximum count.
Parameters
count New argument maximum count
Definition at line 79 of file Argument.cpp.
References m_count.
Referenced by ArgumentParser::registerPositional().
setDescription()
void Argument::setDescription (const char * description)
Set argument single line description.
Parameters
description New argument description
Definition at line 69 of file Argument.cpp.
References m_description.
Referenced by ArgumentParser::registerFlag(), and ArgumentParser::registerPositional().
setIdentifier()
void Argument::setIdentifier (char id)
Set argument identifier.
Parameters
id Argument identifier
Definition at line 59 of file Argument.cpp.
References m_id.
Referenced by ArgumentParser::registerFlag().
setName()
void Argument::setName (const char * name)
Set argument name.
Parameters
name New argument name
Definition at line 64 of file Argument.cpp.
References m_name, and name.
setValue()
void Argument::setValue (const char * value)
Set argument option value
Parameters
value New argument option value
Definition at line 74 of file Argument.cpp.
References m_value.
Referenced by ArgumentParser::parse().
Field Documentation
m_count
Size Argument::m_count private
Maximum argument count.
Definition at line 157 of file Argument.h.
Referenced by getCount(), and setCount().
m_description
String Argument::m_description private
Argument description in a single line.
Definition at line 151 of file Argument.h.
Referenced by getDescription(), and setDescription().
m_id
char Argument::m_id private
Argument identifier (single character)
Definition at line 145 of file Argument.h.
Referenced by getIdentifier(), operator!=(), operator==(), and setIdentifier().
m_name
String Argument::m_name private
Argument name.
Definition at line 148 of file Argument.h.
Referenced by getName(), and setName().
m_value
String Argument::m_value private
Optional argument value.
Definition at line 154 of file Argument.h.
Referenced by getValue(), and setValue().
The documentation for this class was generated from the following files:
lib/libstd/Argument.h
lib/libstd/Argument.cpp