FreeNOS: ProcessShares Class Reference
ProcessShares Class Reference
kernel
Manages memory shares for a Process.
#include <ProcessShares.h>
Data Structures
struct MemoryShare
Public Types
enum Result {
Success, InvalidArgument, MemoryMapError, OutOfMemory,
AlreadyExists, NotFound
}
typedef struct ProcessShares::MemoryShare MemoryShare
Public Member Functions
ProcessShares (ProcessID pid)
Constructor.
virtual ~ProcessShares ()
Destructor function.
const ProcessID getProcessID () const
Get process.
MemoryContext * getMemoryContext ()
Get MemoryContext object.
Result setMemoryContext (MemoryContext *context)
Set MemoryContext.
Result createShare (ProcessShares &instance, MemoryShare *share)
Result createShare (ProcessID pid, Size coreId, Size tagId, Address virt, Size size)
Create memory share.
Result readShare (MemoryShare *share)
Read memory share by Process, Core and Tag IDs.
Result removeShares (ProcessID pid)
Remove all shares for the given ProcessID.
Private Member Functions
Result releaseShare (MemoryShare *share, Size idx)
Release one memory share.
Private Attributes
ProcessID m_pid
ProcessID associated to these shares.
MemoryContext * m_memory
MemoryContext instance.
MemoryChannel * m_kernelChannel
Memory channel for sending kernel events to the associated Process.
Index< MemoryShare > m_shares
Contains all memory shares.
Detailed Description
Manages memory shares for a Process.
Definition at line 39 of file ProcessShares.h.
Member Typedef Documentation
MemoryShare
typedef struct ProcessShares::MemoryShare ProcessShares::MemoryShare
Member Enumeration Documentation
Result
enum ProcessShares::Result
Enumerator
Success
InvalidArgument
MemoryMapError
OutOfMemory
AlreadyExists
NotFound
Definition at line 71 of file ProcessShares.h.
Constructor & Destructor Documentation
ProcessShares()
ProcessShares::ProcessShares (ProcessID pid)
Constructor.
Definition at line 25 of file ProcessShares.cpp.
References m_kernelChannel, m_memory, m_pid, and ZERO.
~ProcessShares()
ProcessShares::~ProcessShares () virtual
Destructor function.
Definition at line 32 of file ProcessShares.cpp.
References List< T >::append(), List< T >::contains(), ProcessManager::get(), Kernel::getProcessManager(), ListIterator< T >::hasCurrent(), Singleton< Kernel >::instance, m_kernelChannel, m_pid, m_shares, ProcessShares::MemoryShare::pid, ProcessTerminated, Process::raiseEvent(), releaseShare(), and ProcessEvent::type.
Member Function Documentation
createShare() [1/2]
ProcessShares::Result ProcessShares::createShare (ProcessShares & instance, ProcessShares::MemoryShare * share)
Definition at line 116 of file ProcessShares.cpp.
References Memory::Range::access, AlreadyExists, ProcessShares::MemoryShare::attached, Cache::cleanData(), MemoryBlock::copy(), ProcessShares::MemoryShare::coreId, CoreInfo::coreId, MemoryContext::findFree(), ProcessManager::get(), Kernel::getCoreInfo(), getMemoryContext(), getProcessID(), Kernel::getProcessManager(), Singleton< Kernel >::instance, InvalidArgument, m_memory, m_pid, m_shares, MemoryContext::mapRange(), OutOfMemory, PAGESIZE, Memory::Range::phys, ProcessShares::MemoryShare::pid, Process::raiseEvent(), ProcessShares::MemoryShare::range, readShare(), MemoryBlock::set(), ProcessEvent::share, ShareCreated, Memory::Range::size, MemoryContext::Success, Allocator::Success, Success, ProcessShares::MemoryShare::tagId, ProcessEvent::type, Memory::User, MemoryMap::UserShare, Memory::Range::virt, and ZERO.
Referenced by Process::initialize(), and VMShareHandler().
createShare() [2/2]
ProcessShares::Result ProcessShares::createShare (ProcessID pid, Size coreId, Size tagId, Address virt, Size size)
Create memory share.
Parameters
pid ProcessID for the share.
coreId CoreID for the share.
tagId TagID for the share.
virt Virtual address of the share.
size Size of the share.
Returns
Result code.
Definition at line 86 of file ProcessShares.cpp.
References Memory::Range::access, MemoryContext::access(), ProcessShares::MemoryShare::coreId, InvalidArgument, MemoryContext::lookup(), m_memory, m_shares, OutOfMemory, PAGESIZE, Memory::Range::phys, ProcessShares::MemoryShare::pid, ProcessShares::MemoryShare::range, Memory::Range::size, Success, ProcessShares::MemoryShare::tagId, Memory::Range::virt, and ZERO.
getMemoryContext()
MemoryContext * ProcessShares::getMemoryContext ()
Get MemoryContext object.
Returns
MemoryContext object pointer.
Definition at line 75 of file ProcessShares.cpp.
References m_memory.
Referenced by createShare().
getProcessID()
const ProcessID ProcessShares::getProcessID () const
Get process.
Definition at line 70 of file ProcessShares.cpp.
References m_pid.
Referenced by createShare().
readShare()
ProcessShares::Result ProcessShares::readShare (MemoryShare * share)
Read memory share by Process, Core and Tag IDs.
Parameters
share MemoryShare buffer (input/output).
Returns
Result code.
Definition at line 271 of file ProcessShares.cpp.
References MemoryBlock::copy(), ProcessShares::MemoryShare::coreId, m_shares, NotFound, ProcessShares::MemoryShare::pid, Success, ProcessShares::MemoryShare::tagId, and ZERO.
Referenced by createShare(), and VMShareHandler().
releaseShare()
ProcessShares::Result ProcessShares::releaseShare (MemoryShare * share, Size idx) private
Release one memory share.
Parameters
share MemoryShare object pointer
idx Index position of the object
Returns
Result code
Definition at line 224 of file ProcessShares.cpp.
References ProcessShares::MemoryShare::attached, ProcessShares::MemoryShare::coreId, ProcessManager::get(), Kernel::getAllocator(), Kernel::getProcessManager(), Process::getShares(), Singleton< Kernel >::instance, m_memory, m_pid, m_shares, PAGESIZE, Memory::Range::phys, ProcessShares::MemoryShare::pid, ProcessShares::MemoryShare::range, Allocator::release(), Memory::Range::size, Success, and MemoryContext::unmapRange().
Referenced by removeShares(), and ~ProcessShares().
removeShares()
ProcessShares::Result ProcessShares::removeShares (ProcessID pid)
Remove all shares for the given ProcessID.
Parameters
pid ProcessID to remove all shares for
Returns
Result code
Definition at line 206 of file ProcessShares.cpp.
References m_shares, ProcessShares::MemoryShare::pid, releaseShare(), Success, and ZERO.
Referenced by VMShareHandler().
setMemoryContext()
ProcessShares::Result ProcessShares::setMemoryContext (MemoryContext * context)
Set MemoryContext.
Parameters
context MemoryContext object
Returns
Result code.
Definition at line 80 of file ProcessShares.cpp.
References m_memory, and Success.
Referenced by Process::initialize().
Field Documentation
m_kernelChannel
MemoryChannel* ProcessShares::m_kernelChannel private
Memory channel for sending kernel events to the associated Process.
Definition at line 174 of file ProcessShares.h.
Referenced by ProcessShares(), and ~ProcessShares().
m_memory
MemoryContext* ProcessShares::m_memory private
MemoryContext instance.
Definition at line 171 of file ProcessShares.h.
Referenced by createShare(), getMemoryContext(), ProcessShares(), releaseShare(), and setMemoryContext().
m_pid
ProcessID ProcessShares::m_pid private
ProcessID associated to these shares.
Definition at line 168 of file ProcessShares.h.
Referenced by createShare(), getProcessID(), ProcessShares(), releaseShare(), and ~ProcessShares().
m_shares
Index<MemoryShare> ProcessShares::m_shares private
Contains all memory shares.
Definition at line 177 of file ProcessShares.h.
Referenced by createShare(), readShare(), releaseShare(), removeShares(), and ~ProcessShares().
The documentation for this class was generated from the following files:
kernel/ProcessShares.h
kernel/ProcessShares.cpp