FreeNOS: IntelAPIC Class Reference
IntelAPIC Class Reference
lib » libarch » Intel
Intel Advanced Programmable Interrupt Controller (APIC)
#include <IntelAPIC.h>
Public Member Functions
IntelAPIC ()
Constructor.
IntelIO & getIO ()
Get I/O object.
uint getCounter () const
Get timer initial counter.
virtual Timer::Result initialize ()
Initialize the APIC.
virtual Timer::Result wait (u32 microseconds) const
Busy wait a number of microseconds.
Timer::Result start (IntelPIT *pit)
Start the timer using PIT as reference timer.
Timer::Result start (uint initialCounter, uint hertz)
Start the timer with initial counter.
virtual IntController::Result enable (uint irq)
Enable hardware interrupt (IRQ).
virtual IntController::Result disable (uint irq)
Disable hardware interrupt (IRQ).
virtual IntController::Result clear (uint irq)
Clear hardware interrupt (IRQ).
IntController::Result sendStartupIPI (uint cpuId, Address addr)
Send startup Intercore-Processor-Interrupt.
Public Member Functions inherited from IntController
IntController ()
Constructor.
uint getBase () const
Get interrupt number base offset.
Public Member Functions inherited from Timer
struct Timer::Info ALIGN (8) Info
Timer information structure.
Timer ()
Constructor.
Size getInterrupt () const
Get timer interrupt number.
Size getFrequency () const
Get timer frequency.
virtual Result setFrequency (Size hertz)
Set timer frequency.
virtual Result getCurrent (Info *info)
Get current timer info.
virtual Result start ()
Start the timer.
virtual Result stop ()
Stop the timer.
virtual Result tick ()
Process timer tick.
bool isExpired (const Info &info) const
Check if a timer value is expired.
Static Public Attributes
static const uint IOBase = 0xfee00000
APIC memory mapped I/O register base offset (physical address).
static const uint TimerVector = 48
APIC timer interrupt vector is fixed at 48.
Private Types
enum Registers {
Identifier = 0x20, Version = 0x30, TaskPriority = 0x80, ArbitrationPriority = 0x90,
ProcessorPriority = 0xa0, EndOfInterrupt = 0xb0, SpuriousIntVec = 0xf0, InService = 0x100,
TriggerMode = 0x180, IntRequest = 0x200, ErrorStatus = 0x280, IntCommand1 = 0x300,
IntCommand2 = 0x310, Timer = 0x320, ThermalSensor = 0x330, PerfCounters = 0x340,
LocalInt0 = 0x350, LocalInt1 = 0x360, Error = 0x370, InitialCount = 0x380,
CurrentCount = 0x390, DivideConfig = 0x3e0
}
Hardware registers.
enum SpuriousIntVecFlags { APICEnable = 0x100 }
Spurious Interrupt Vector Register flags.
enum DivideConfigFlags { Divide16 = 3 }
Timer Divide Configuration Register flags.
enum TimerFlags { PeriodicMode = (1 << 17) }
Timer Register flags.
Private Attributes
IntelIO m_io
I/O object.
Additional Inherited Members
Public Types inherited from IntController
enum Result {
Success, InvalidIRQ, InvalidFrequency, IOError,
NotFound
}
Result codes.
typedef void Handler(struct CPUState state)
Function which is called when the CPU is interrupted.
Public Types inherited from Timer
enum Result { Success, NotFound, IOError, InvalidFrequency }
Result codes.
Data Fields inherited from Timer
enum Timer::Result ALIGN
Protected Attributes inherited from IntController
uint m_base
Interrupt number base offset.
Protected Attributes inherited from Timer
Info m_info
The current Timer information.
Size m_frequency
Frequency of the Timer.
Size m_int
Timer interrupt number.
Detailed Description
Intel Advanced Programmable Interrupt Controller (APIC)
Definition at line 45 of file IntelAPIC.h.
Member Enumeration Documentation
DivideConfigFlags
enum IntelAPIC::DivideConfigFlags private
Timer Divide Configuration Register flags.
Enumerator
Divide16
Definition at line 99 of file IntelAPIC.h.
Registers
enum IntelAPIC::Registers private
Hardware registers.
Enumerator
Identifier
Version
TaskPriority
ArbitrationPriority
ProcessorPriority
EndOfInterrupt
SpuriousIntVec
InService
TriggerMode
IntRequest
ErrorStatus
IntCommand1
IntCommand2
Timer
ThermalSensor
PerfCounters
LocalInt0
LocalInt1
Error
InitialCount
CurrentCount
DivideConfig
Definition at line 62 of file IntelAPIC.h.
SpuriousIntVecFlags
enum IntelAPIC::SpuriousIntVecFlags private
Spurious Interrupt Vector Register flags.
Enumerator
APICEnable
Definition at line 91 of file IntelAPIC.h.
TimerFlags
enum IntelAPIC::TimerFlags private
Timer Register flags.
Enumerator
PeriodicMode
Definition at line 107 of file IntelAPIC.h.
Constructor & Destructor Documentation
IntelAPIC()
IntelAPIC::IntelAPIC ()
Constructor.
Definition at line 36 of file IntelAPIC.cpp.
References IOBase, Timer::m_frequency, Timer::m_int, m_io, IO::setBase(), and TimerVector.
Member Function Documentation
clear()
IntController::Result IntelAPIC::clear (uint irq) virtual
Clear hardware interrupt (IRQ).
Clearing marks the end of an interrupt service routine and causes the controller to trigger the interrupt again on the next trigger moment.
Parameters
irq Interrupt Request number to clear.
Returns
Result code.
Implements IntController.
Definition at line 175 of file IntelAPIC.cpp.
References EndOfInterrupt, m_io, IntController::Success, and IntelIO::write().
Referenced by IntelKernel::clocktick().
disable()
IntController::Result IntelAPIC::disable (uint irq) virtual
Disable hardware interrupt (IRQ).
Parameters
irq Interrupt Request number.
Returns
Result code.
Implements IntController.
Definition at line 170 of file IntelAPIC.cpp.
References IntController::NotFound.
enable()
IntController::Result IntelAPIC::enable (uint irq) virtual
Enable hardware interrupt (IRQ).
Parameters
irq Interrupt Request number.
Returns
Result code.
Implements IntController.
Definition at line 165 of file IntelAPIC.cpp.
References IntController::NotFound.
getCounter()
uint IntelAPIC::getCounter () const
Get timer initial counter.
Returns
Initial timer counter.
Definition at line 49 of file IntelAPIC.cpp.
References InitialCount, m_io, and IntelIO::read().
Referenced by IntelKernel::IntelKernel().
getIO()
IntelIO & IntelAPIC::getIO ()
Get I/O object.
Returns
I/O object reference.
Definition at line 44 of file IntelAPIC.cpp.
References m_io.
Referenced by IntelMP::IntelMP().
initialize()
Timer::Result IntelAPIC::initialize () virtual
Initialize the APIC.
Returns
Result code.
Reimplemented from Timer.
Definition at line 148 of file IntelAPIC.cpp.
References APICEnable, Divide16, DivideConfig, EndOfInterrupt, InitialCount, IOBase, Timer::IOError, m_io, IO::map(), PeriodicMode, IntelIO::set(), SpuriousIntVec, IO::Success, Timer::Success, TimerVector, and IntelIO::write().
Referenced by IntelKernel::IntelKernel().
sendStartupIPI()
IntController::Result IntelAPIC::sendStartupIPI (uint cpuId, Address addr)
Send startup Intercore-Processor-Interrupt.
Parameters
cpuId CPU identifier to send startup IPI.
addr Start of execution address.
Returns
Result code.
Definition at line 181 of file IntelAPIC.cpp.
References APIC_DEST, APIC_DEST_ASSERT, APIC_DEST_DM_INIT, APIC_DEST_DM_STARTUP, APIC_DEST_FIELD, APIC_DEST_LEVELTRIG, IntCommand1, IntCommand2, m_io, IntelIO::read(), IntController::Success, wait(), and IntelIO::write().
Referenced by IntelMP::boot().
start() [1/2]
Timer::Result IntelAPIC::start (IntelPIT * pit)
Start the timer using PIT as reference timer.
Parameters
pit PIT instance used to measure the APIC bus speed for clock calibration.
Returns
Result code.
Definition at line 54 of file IntelAPIC.cpp.
References CurrentCount, Divide16, DivideConfig, Timer::getFrequency(), InitialCount, Timer::m_frequency, m_io, NOTICE, PeriodicMode, IntelIO::read(), Timer::Success, TimerVector, IntelPIT::waitTrigger(), and IntelIO::write().
Referenced by IntelKernel::IntelKernel().
start() [2/2]
Timer::Result IntelAPIC::start (uint initialCounter, uint hertz)
Start the timer with initial counter.
Parameters
initialCounter The value of the InitialCount register.
hertz Hertz associated to the initial counter.
Returns
Result code.
Definition at line 136 of file IntelAPIC.cpp.
References Divide16, DivideConfig, InitialCount, Timer::m_frequency, m_io, PeriodicMode, Timer::Success, TimerVector, and IntelIO::write().
wait()
Timer::Result IntelAPIC::wait (u32 microseconds) const virtual
Busy wait a number of microseconds.
Parameters
microseconds The number of microseconds to wait at minimum.
Returns
Result code.
Reimplemented from Timer.
Definition at line 92 of file IntelAPIC.cpp.
References CurrentCount, InfoTimer, InitialCount, Timer::IOError, isKernel, Timer::m_frequency, m_io, ProcessCtl(), IntelIO::read(), SELF, Timer::Success, API::Success, and WaitTimer.
Referenced by sendStartupIPI().
Field Documentation
IOBase
const uint IntelAPIC::IOBase = 0xfee00000 static
APIC memory mapped I/O register base offset (physical address).
Definition at line 52 of file IntelAPIC.h.
Referenced by initialize(), IntelAPIC(), and IntelMP::IntelMP().
m_io
IntelIO IntelAPIC::m_io private
I/O object.
Definition at line 205 of file IntelAPIC.h.
Referenced by clear(), getCounter(), getIO(), initialize(), IntelAPIC(), sendStartupIPI(), start(), and wait().
TimerVector
const uint IntelAPIC::TimerVector = 48 static
APIC timer interrupt vector is fixed at 48.
Definition at line 55 of file IntelAPIC.h.
Referenced by initialize(), IntelAPIC(), and start().
The documentation for this class was generated from the following files:
lib/libarch/intel/IntelAPIC.h
lib/libarch/intel/IntelAPIC.cpp