FreeNOS: Storage Class Reference
Storage Class Reference abstract
lib » libfs
Provides a storage device to build filesystems on top.
#include <Storage.h>
Public Member Functions
Storage ()
Constructor function.
virtual ~Storage ()
Destructor function.
virtual Error read (u64 offset, void *buffer, Size size)
Read a contiguous set of data.
virtual Error write (u64 offset, void *buffer, Size size)
Write a contiguous set of data.
virtual u64 capacity () const =0
Retrieve maximum storage capacity.
Detailed Description
Provides a storage device to build filesystems on top.
Definition at line 35 of file Storage.h.
Constructor & Destructor Documentation
Storage()
Storage::Storage ()
Constructor function.
Definition at line 22 of file Storage.cpp.
~Storage()
Storage::~Storage () virtual
Destructor function.
Definition at line 26 of file Storage.cpp.
Member Function Documentation
capacity()
virtual u64 Storage::capacity () const pure virtual
Retrieve maximum storage capacity.
Returns
Storage capacity.
Implemented in FileStorage, and BootImageStorage.
read()
Error Storage::read (u64 offset, void * buffer, Size size) virtual
Read a contiguous set of data.
Parameters
offset Offset to start reading from.
buffer Output buffer.
size Number of bytes to copied.
Returns
Result code
Reimplemented in FileStorage, and BootImageStorage.
Definition at line 30 of file Storage.cpp.
References ENOTSUP.
Referenced by LinnFileSystem::getInode(), LinnDirectory::getLinnDirectoryEntry(), LinnFileSystem::getOffset(), LinnFileSystem::LinnFileSystem(), LinnFile::read(), and LinnDirectory::read().
write()
Error Storage::write (u64 offset, void * buffer, Size size) virtual
Write a contiguous set of data.
Parameters
offset Offset to start writing to.
buffer Input buffer.
size Number of bytes to written.
Returns
Result code
Reimplemented in FileStorage.
Definition at line 35 of file Storage.cpp.
References ENOTSUP.
The documentation for this class was generated from the following files:
lib/libfs/Storage.h
lib/libfs/Storage.cpp