FreeNOS: ExecutableFormat Class Reference
ExecutableFormat Class Reference abstract
lib » libexec
Abstraction class of various executable formats.
#include <ExecutableFormat.h>
Data Structures
struct Region
Memory region.
Public Types
enum Result { Success, NotFound, InvalidFormat, OutOfMemory }
Result code.
typedef struct ExecutableFormat::Region Region
Memory region.
Public Member Functions
ExecutableFormat (const u8 *image, Size size)
Class constructor.
virtual ~ExecutableFormat ()
Class destructor.
virtual Result regions (Region *regions, Size *count) const =0
Memory regions a program needs at runtime.
virtual Result entry (Address *entry) const =0
Lookup the program entry point.
Static Public Member Functions
static Result find (const u8 *image, Size size, ExecutableFormat **fmt)
Find a ExecutableFormat which can handle the given format.
Protected Attributes
const u8 * m_image
Input image raw data.
const Size m_size
Input image size in bytes.
Detailed Description
Abstraction class of various executable formats.
Definition at line 48 of file ExecutableFormat.h.
Member Typedef Documentation
Region
typedef struct ExecutableFormat::Region ExecutableFormat::Region
Memory region.
Member Enumeration Documentation
Result
enum ExecutableFormat::Result
Result code.
Enumerator
Success
NotFound
InvalidFormat
OutOfMemory
Definition at line 67 of file ExecutableFormat.h.
Constructor & Destructor Documentation
ExecutableFormat()
ExecutableFormat::ExecutableFormat (const u8 * image, Size size)
Class constructor.
Parameters
image Pointer to program image.
size Size of the program image.
Definition at line 22 of file ExecutableFormat.cpp.
~ExecutableFormat()
ExecutableFormat::~ExecutableFormat () virtual
Class destructor.
Definition at line 28 of file ExecutableFormat.cpp.
Member Function Documentation
entry()
virtual Result ExecutableFormat::entry (Address * entry) const pure virtual
Lookup the program entry point.
Parameters
entry Entry point on output.
Returns
Result code.
Implemented in ELF.
Referenced by CoreServer::discover(), forkexec(), BootImageCreate::readBootSymbols(), and spawn().
find()
ExecutableFormat::Result ExecutableFormat::find (const u8 * image, Size size, ExecutableFormat ** fmt) static
Find a ExecutableFormat which can handle the given format.
Parameters
image Program image to read.
size Program image size.
fmt ExecutableFormat object pointer on output.
Returns
Result code.
Definition at line 32 of file ExecutableFormat.cpp.
References ELF::detect().
Referenced by forkexec(), CoreServer::loadKernel(), BootImageCreate::readBootSymbols(), and spawn().
regions()
virtual Result ExecutableFormat::regions (Region * regions, Size * count) const pure virtual
Memory regions a program needs at runtime.
Parameters
regions Memory regions to fill.
count On input, the maximum number of regions to read. On output, the actual number of regions read.
Returns
Result code.
Implemented in ELF.
Referenced by forkexec(), CoreServer::loadKernel(), BootImageCreate::readBootSymbols(), and spawn().
Field Documentation
m_image
const u8* ExecutableFormat::m_image protected
Input image raw data.
Definition at line 122 of file ExecutableFormat.h.
Referenced by ELF::entry(), and ELF::regions().
m_size
const Size ExecutableFormat::m_size protected
Input image size in bytes.
Definition at line 125 of file ExecutableFormat.h.
The documentation for this class was generated from the following files:
lib/libexec/ExecutableFormat.h
lib/libexec/ExecutableFormat.cpp