FreeNOS: ARMSecondTable Class Reference
ARMSecondTable Class Reference
lib » libarch » ARM
ARM second level page table implementation.
#include <ARMSecondTable.h>
Public Member Functions
MemoryContext::Result map (Address virt, Address phys, Memory::Access)
Map a virtual address to a physical address.
MemoryContext::Result unmap (Address virt)
Remove virtual address mapping.
MemoryContext::Result translate (Address virt, Address *phys) const
Translate virtual address to physical address.
MemoryContext::Result access (Address virt, Memory::Access *access) const
Get Access flags for a virtual address.
Private Member Functions
u32 flags (Memory::Access access) const
Convert MemoryAccess to page table flags.
Private Attributes
u32 m_pages [256]
Array of second level page table entries.
Detailed Description
ARM second level page table implementation.
Definition at line 39 of file ARMSecondTable.h.
Member Function Documentation
access()
MemoryContext::Result ARMSecondTable::access (Address virt, Memory::Access * access) const
Get Access flags for a virtual address.
Parameters
virt Virtual address to get Access flags for.
access MemoryAccess object pointer.
Returns
Result code.
Definition at line 137 of file ARMSecondTable.cpp.
References Memory::Device, Memory::InnerCached, MemoryContext::InvalidAddress, m_pages, Memory::OuterCached, PAGE2_AP_USER, PAGE2_APX, PAGE2_DEVICE_SHARED, PAGE2_PRESENT, PAGE2_UNCACHED, Memory::Readable, MemoryContext::Success, TABENTRY, Memory::Uncached, Memory::User, and Memory::Writable.
Referenced by ARMFirstTable::access().
flags()
u32 ARMSecondTable::flags (Memory::Access access) const private
Convert MemoryAccess to page table flags.
Parameters
access Memory access flags
Returns
Page table access flags
Definition at line 164 of file ARMSecondTable.cpp.
References Memory::Device, Memory::Executable, PAGE2_AP_SYS, PAGE2_AP_USER, PAGE2_APX, PAGE2_CACHE_WRITEBACK, PAGE2_DEVICE_SHARED, PAGE2_NOEXEC, PAGE2_UNCACHED, Memory::Uncached, Memory::User, and Memory::Writable.
Referenced by map().
map()
MemoryContext::Result ARMSecondTable::map (Address virt, Address phys, Memory::Access access)
Map a virtual address to a physical address.
Parameters
virt Virtual address.
phys Physical address.
access Memory access flags.
Returns
Result code
Definition at line 103 of file ARMSecondTable.cpp.
References MemoryContext::AlreadyExists, Cache::cleanData(), flags(), m_pages, PAGE2_PRESENT, MemoryContext::Success, and TABENTRY.
Referenced by ARMFirstTable::map().
translate()
MemoryContext::Result ARMSecondTable::translate (Address virt, Address * phys) const
Translate virtual address to physical address.
Parameters
virt Virtual address to lookup as input
phys Physical address for output.
Returns
Result code
Definition at line 128 of file ARMSecondTable.cpp.
References MemoryContext::InvalidAddress, m_pages, PAGE2_PRESENT, PAGEMASK, MemoryContext::Success, and TABENTRY.
Referenced by ARMFirstTable::releaseRange(), and ARMFirstTable::translate().
unmap()
MemoryContext::Result ARMSecondTable::unmap (Address virt)
Remove virtual address mapping.
Parameters
virt Virtual address.
Returns
Result code
Definition at line 119 of file ARMSecondTable.cpp.
References Cache::cleanData(), m_pages, PAGE2_NONE, MemoryContext::Success, and TABENTRY.
Referenced by ARMFirstTable::unmap().
Field Documentation
m_pages
u32 ARMSecondTable::m_pages[256] private
Array of second level page table entries.
Definition at line 99 of file ARMSecondTable.h.
Referenced by access(), map(), translate(), and unmap().
The documentation for this class was generated from the following files:
lib/libarch/arm/ARMSecondTable.h
lib/libarch/arm/ARMSecondTable.cpp