FreeNOS: BroadcomI2C Class Reference
BroadcomI2C Class Reference
lib » libi2c
Broadcom (2835) I2C controller implementation.
#include <BroadcomI2C.h>
Public Member Functions
BroadcomI2C ()
Constructor.
virtual Result initialize ()
Initialize the Controller.
virtual Result setClockDivider (Size divider)
Set clock divider.
virtual Result setAddress (Address addr)
Set Slave address.
virtual Result write (u8 *buf, Size size)
Write data to slave.
virtual Result read (u8 *buf, Size size)
Read data from slave.
Public Member Functions inherited from I2C
I2C ()
Constructor.
Private Types
enum Registers {
Control = 0x0, Status = 0x4, DataLength = 0x8, SlaveAddress = 0xc,
FIFO = 0x10, ClockDivider = 0x14, DataDelay = 0x18, ClockStretch = 0x1c
}
Hardware registers.
enum ControlFlags {
Enable = (1 << 15), RxIntr = (1 << 10), TxIntr = (1 << 9), Transfer = (1 << 7),
ClearFIFO = (1 << 5), ReadMode = (1), WriteMode = (0)
}
Control Register Flags.
enum StatusFlags {
ClockStretchTimeout = (1 << 9), AcknowledgeError = (1 << 8), RxFIFOFull = (1 << 7), TxFIFOEmpty = (1 << 6),
RxFIFOHasData = (1 << 5), TxFIFOHasData = (1 << 4), RxFIFOReady = (1 << 3), TxFIFOReady = (1 << 2),
TransferDone = (1 << 1), TransferActive = (1 << 0)
}
Status Register Flags.
Private Attributes
BroadcomGPIO m_gpio
GPIO controller.
Static Private Attributes
static const uint BSC0 = 0x205000
static const uint BSC1 = 0x804000
static const uint BSC2 = 0x805000
static const Size FIFOSize = 16
Additional Inherited Members
Public Types inherited from I2C
enum Result { Success, NotFound, IOError, RangeError }
Result codes.
Protected Attributes inherited from I2C
Arch::IO m_io
I/O instance.
Detailed Description
Broadcom (2835) I2C controller implementation.
This class implements access to the I2C controller used in the Broadcom 2835 System-on-Chip. The controller features a 16-byte FIFO for data reads and writes and allows the use of interrupts.
See also
BCM2835 ARM Peripherals.pdf
http://www.airspayce.com/mikem/bcm2835/
https://github.com/raspberrypi/linux/issues/254
https://www.raspberrypi.org/forums/viewtopic.php?f=44&t=13771&start=25
http://www.advamation.com/knowhow/raspberrypi/rpi-i2c-bug.html
http://lxr.free-electrons.com/source/drivers/i2c/busses/i2c-bcm2835.c
Definition at line 49 of file BroadcomI2C.h.
Member Enumeration Documentation
ControlFlags
enum BroadcomI2C::ControlFlags private
Control Register Flags.
Enumerator
Enable
RxIntr
TxIntr
Transfer
ClearFIFO
ReadMode
WriteMode
Definition at line 76 of file BroadcomI2C.h.
Registers
enum BroadcomI2C::Registers private
Hardware registers.
Enumerator
Control
Status
DataLength
SlaveAddress
FIFO
ClockDivider
DataDelay
ClockStretch
Definition at line 61 of file BroadcomI2C.h.
StatusFlags
enum BroadcomI2C::StatusFlags private
Status Register Flags.
Enumerator
ClockStretchTimeout
AcknowledgeError
RxFIFOFull
TxFIFOEmpty
RxFIFOHasData
TxFIFOHasData
RxFIFOReady
TxFIFOReady
TransferDone
TransferActive
Definition at line 90 of file BroadcomI2C.h.
Constructor & Destructor Documentation
BroadcomI2C()
BroadcomI2C::BroadcomI2C ()
Constructor.
Definition at line 21 of file BroadcomI2C.cpp.
Member Function Documentation
initialize()
BroadcomI2C::Result BroadcomI2C::initialize () virtual
Initialize the Controller.
Returns
Result code
Implements I2C.
Definition at line 26 of file BroadcomI2C.cpp.
References BSC1, ClockDivider, DEBUG, Memory::Device, BroadcomGPIO::Function0, BroadcomGPIO::initialize(), I2C::IOError, m_gpio, I2C::m_io, IO::map(), I2C::NotFound, PAGESIZE, ARMIO::read(), Memory::Readable, BroadcomGPIO::setAltFunction(), setClockDivider(), Status, IO::Success, I2C::Success, BroadcomGPIO::Success, Memory::User, and Memory::Writable.
Referenced by main().
read()
BroadcomI2C::Result BroadcomI2C::read (u8 * buf, Size size) virtual
Read data from slave.
Parameters
buf Buffer for storing bytes read.
size Number of bytes to read.
Returns
Result code.
Implements I2C.
Definition at line 115 of file BroadcomI2C.cpp.
References AcknowledgeError, ClearFIFO, ClockStretchTimeout, Control, DataLength, DEBUG, Enable, ERROR, FIFO, FIFOSize, I2C::IOError, I2C::m_io, I2C::RangeError, ARMIO::read(), ReadMode, RxFIFOHasData, Status, I2C::Success, Transfer, TransferDone, and ARMIO::write().
setAddress()
BroadcomI2C::Result BroadcomI2C::setAddress (Address addr) virtual
Set Slave address.
Parameters
addr The 7-bit address of the I2C slave device.
Returns
Result code.
Implements I2C.
Definition at line 57 of file BroadcomI2C.cpp.
References DEBUG, I2C::m_io, SlaveAddress, I2C::Success, and ARMIO::write().
Referenced by main().
setClockDivider()
BroadcomI2C::Result BroadcomI2C::setClockDivider (Size divider) virtual
Set clock divider.
Parameters
divider Clock divider to use.
Returns
Result code.
Definition at line 64 of file BroadcomI2C.cpp.
References ClockDivider, I2C::m_io, I2C::Success, and ARMIO::write().
Referenced by initialize().
write()
BroadcomI2C::Result BroadcomI2C::write (u8 * buf, Size size) virtual
Write data to slave.
Parameters
buf Buffer containing bytes to write.
size Number of bytes to write.
Returns
Result code.
Implements I2C.
Definition at line 70 of file BroadcomI2C.cpp.
References AcknowledgeError, ClearFIFO, ClockStretchTimeout, Control, DataLength, DEBUG, Enable, ERROR, FIFO, FIFOSize, I2C::IOError, I2C::m_io, I2C::RangeError, ARMIO::read(), Status, I2C::Success, Transfer, TransferDone, and ARMIO::write().
Referenced by main().
Field Documentation
BSC0
const uint BroadcomI2C::BSC0 = 0x205000 static private
Definition at line 53 of file BroadcomI2C.h.
BSC1
const uint BroadcomI2C::BSC1 = 0x804000 static private
Definition at line 54 of file BroadcomI2C.h.
Referenced by initialize().
BSC2
const uint BroadcomI2C::BSC2 = 0x805000 static private
Definition at line 55 of file BroadcomI2C.h.
FIFOSize
const Size BroadcomI2C::FIFOSize = 16 static private
Definition at line 56 of file BroadcomI2C.h.
Referenced by read(), and write().
m_gpio
BroadcomGPIO BroadcomI2C::m_gpio private
GPIO controller.
Definition at line 159 of file BroadcomI2C.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
lib/libi2c/BroadcomI2C.h
lib/libi2c/BroadcomI2C.cpp