FreeNOS: ICMP Class Reference
ICMP Class Reference
lib » libnet
Internet Control Message Protocol (ICMP)
#include <ICMP.h>
Data Structures
struct Header
Packet header format.
Public Types
enum Type { EchoReply = 0, DestinationUnreachable = 3, Redirect = 5, EchoRequest = 8 }
Packet types.
typedef struct ICMP::Header Header
Packet header format.
Public Member Functions
ICMP (NetworkServer *server, NetworkDevice *device)
Constructor.
virtual ~ICMP ()
Destructor.
void setIP (::IPV4 *ip)
Set IP object.
virtual Error initialize ()
Perform initialization.
ICMPSocket * createSocket (String &path)
Creates an ICMP socket.
virtual Error process (NetworkQueue::Packet *pkt, Size offset)
Process incoming network packet.
Error sendPacket (IPV4::Address ip, Header *header)
Send packet.
Public Member Functions inherited from NetworkProtocol
NetworkProtocol (NetworkServer *server, NetworkDevice *device)
Constructor.
virtual ~NetworkProtocol ()
Destructor.
virtual const Size getMaximumPacketSize () const
Get maximum packet size.
Public Member Functions inherited from Directory
Directory ()
Constructor.
virtual ~Directory ()
Destructor.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read directory entries.
virtual File * lookup (const char *name)
Retrieve a File from storage.
void insert (FileType type, const char *name,...)
Insert a new directory entry.
void remove (const char *name)
Remove a directory entry.
void clear ()
Clears the internal list of entries.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Static Public Member Functions
static const u16 checksum (Header *header)
Calculate ICMP checksum.
Private Attributes
ICMPFactory * m_factory
Index< ICMPSocket > m_sockets
::IPV4 * m_ipv4
Additional Inherited Members
Protected Attributes inherited from NetworkProtocol
NetworkServer * m_server
Network server instance.
NetworkDevice * m_device
Network device instance.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
Internet Control Message Protocol (ICMP)
Definition at line 42 of file ICMP.h.
Member Typedef Documentation
Header
typedef struct ICMP::Header ICMP::Header
Packet header format.
Member Enumeration Documentation
Type
enum ICMP::Type
Packet types.
Enumerator
EchoReply
DestinationUnreachable
Redirect
EchoRequest
Definition at line 49 of file ICMP.h.
Constructor & Destructor Documentation
ICMP()
ICMP::ICMP (NetworkServer * server, NetworkDevice * device)
Constructor.
Definition at line 25 of file ICMP.cpp.
References m_ipv4, and ZERO.
~ICMP()
ICMP::~ICMP () virtual
Destructor.
Definition at line 32 of file ICMP.cpp.
Member Function Documentation
checksum()
const u16 ICMP::checksum (Header * header) static
Calculate ICMP checksum.
Parameters
header ICMP header
Returns
ICMP checksum value for the given header
Definition at line 126 of file ICMP.cpp.
References IPV4::checksum().
Referenced by NetPing::icmpPing(), and process().
createSocket()
ICMPSocket * ICMP::createSocket (String & path)
Creates an ICMP socket.
Returns
ICMPSocket object instance
Definition at line 82 of file ICMP.cpp.
References DEBUG, FileSystem::getMountPath(), Index< T >::insert(), NetworkProtocol::m_server, m_sockets, FileSystem::registerFile(), and ZERO.
Referenced by ICMPFactory::read().
initialize()
Error ICMP::initialize () virtual
Perform initialization.
Returns
Error code
Implements NetworkProtocol.
Definition at line 41 of file ICMP.cpp.
References DEBUG, ESUCCESS, m_factory, NetworkProtocol::m_server, and FileSystem::registerFile().
Referenced by NetworkDevice::initialize().
process()
Error ICMP::process (NetworkQueue::Packet * pkt, Size offset) virtual
Process incoming network packet.
Returns
Error code
Implements NetworkProtocol.
Definition at line 50 of file ICMP.cpp.
References be32_to_cpu, ICMP::Header::checksum, checksum(), ICMP::Header::code, NetworkQueue::Packet::data, DEBUG, EchoReply, EchoRequest, ESUCCESS, Index< T >::get(), ICMPSocket::getAddress(), ICMP::Header::id, m_sockets, sendPacket(), ICMPSocket::setReply(), Index< T >::size(), IPV4::Header::source, and ICMP::Header::type.
Referenced by IPV4::process().
sendPacket()
Error ICMP::sendPacket (IPV4::Address ip, ICMP::Header * header)
Send packet.
Returns
Error code
Definition at line 104 of file ICMP.cpp.
References MemoryBlock::copy(), NetworkQueue::Packet::data, DEBUG, ESUCCESS, IPV4::getTransmitPacket(), IPV4::ICMP, NetworkProtocol::m_device, m_ipv4, NetworkQueue::Packet::size, and NetworkDevice::transmit().
Referenced by process(), and ICMPSocket::write().
setIP()
void ICMP::setIP (::IPV4 * ip)
Set IP object.
Definition at line 36 of file ICMP.cpp.
References m_ipv4.
Referenced by NetworkDevice::initialize().
Field Documentation
m_factory
ICMPFactory* ICMP::m_factory private
Definition at line 126 of file ICMP.h.
Referenced by initialize().
m_ipv4
::IPV4* ICMP::m_ipv4 private
Definition at line 130 of file ICMP.h.
Referenced by ICMP(), sendPacket(), and setIP().
m_sockets
Index<ICMPSocket> ICMP::m_sockets private
Definition at line 128 of file ICMP.h.
Referenced by createSocket(), and process().
The documentation for this class was generated from the following files:
lib/libnet/ICMP.h
lib/libnet/ICMP.cpp