FreeNOS: IPV4Address Class Reference
IPV4Address Class Reference
lib » libnet
IPV4 address file.
#include <IPV4Address.h>
Public Member Functions
IPV4Address (IPV4 *ipv4)
Constructor.
virtual ~IPV4Address ()
Destructor.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read IPV4 address.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Set new IPV4 address.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Attributes
IPV4 * m_ipv4
IPV4 object pointer.
Additional Inherited Members
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
IPV4 address file.
Definition at line 36 of file IPV4Address.h.
Constructor & Destructor Documentation
IPV4Address()
IPV4Address::IPV4Address (IPV4 * ipv4)
Constructor.
Definition at line 22 of file IPV4Address.cpp.
References m_ipv4.
~IPV4Address()
IPV4Address::~IPV4Address () virtual
Destructor.
Definition at line 27 of file IPV4Address.cpp.
Member Function Documentation
read()
Error IPV4Address::read (IOBuffer & buffer, Size size, Size offset) virtual
Read IPV4 address.
Parameters
buffer Input/Output buffer to output bytes to.
size Number of bytes to read, at maximum.
offset Offset inside the file to start reading.
Returns
Number of bytes read on success, Error on failure.
Reimplemented from File.
Definition at line 31 of file IPV4Address.cpp.
References DEBUG, IPV4::getAddress(), String::length(), m_ipv4, IPV4::toString(), and IOBuffer::write().
write()
Error IPV4Address::write (IOBuffer & buffer, Size size, Size offset) virtual
Set new IPV4 address.
Parameters
buffer Input/Output buffer to input bytes from.
size Number of bytes to write, at maximum.
offset Offset inside the file to start writing.
Returns
Number of bytes written on success, Error on failure.
Reimplemented from File.
Definition at line 48 of file IPV4Address.cpp.
References DEBUG, ERANGE, ESUCCESS, m_ipv4, IOBuffer::read(), IPV4::setAddress(), and IPV4::toAddress().
Field Documentation
m_ipv4
IPV4* IPV4Address::m_ipv4 private
IPV4 object pointer.
Definition at line 75 of file IPV4Address.h.
Referenced by IPV4Address(), read(), and write().
The documentation for this class was generated from the following files:
lib/libnet/IPV4Address.h
lib/libnet/IPV4Address.cpp