FreeNOS: ICMPSocket Class Reference
ICMPSocket Class Reference
lib » libnet
Internet Control Message Protocol (ICMP) socket.
#include <ICMPSocket.h>
Public Member Functions
ICMPSocket (ICMP *icmp)
Constructor.
virtual ~ICMPSocket ()
Destructor.
const IPV4::Address getAddress () const
Get associated IP host.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Receive ICMP response.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Send ICMP request.
virtual Error process (NetworkQueue::Packet *pkt)
Process incoming network packet.
virtual void error (Error err)
Set error status.
void setReply (ICMP::Header *reply)
Set ICMP reply.
bool operator== (const ICMPSocket &sock) const
bool operator!= (const ICMPSocket &sock) const
Public Member Functions inherited from NetworkSocket
NetworkSocket (Size packetSize)
Constructor.
virtual ~NetworkSocket ()
Destructor.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Attributes
ICMP * m_icmp
ICMP protocol instance.
ICMP::Header m_reply
Reply.
bool m_gotReply
Additional Inherited Members
Protected Attributes inherited from NetworkSocket
ProcessID m_pid
Process which owns the socket.
NetworkQueue m_receive
Receive queue.
NetworkQueue m_transmit
Transmit queue.
NetworkClient::SocketInfo m_info
Socket connection.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
Internet Control Message Protocol (ICMP) socket.
ICMP sockets are associated with one IP-host and receive packets from that host and allow sending packets to that host.
Definition at line 42 of file ICMPSocket.h.
Constructor & Destructor Documentation
ICMPSocket()
ICMPSocket::ICMPSocket (ICMP * icmp)
Constructor.
Definition at line 25 of file ICMPSocket.cpp.
References m_gotReply, m_icmp, NetworkSocket::m_info, and MemoryBlock::set().
~ICMPSocket()
ICMPSocket::~ICMPSocket () virtual
Destructor.
Definition at line 33 of file ICMPSocket.cpp.
Member Function Documentation
error()
void ICMPSocket::error (Error err) virtual
Set error status.
Parameters
err Error code
Definition at line 82 of file ICMPSocket.cpp.
References DEBUG.
getAddress()
const IPV4::Address ICMPSocket::getAddress () const
Get associated IP host.
Returns
IPV4::Address of the connected host
Definition at line 37 of file ICMPSocket.cpp.
References NetworkClient::SocketInfo::address, and NetworkSocket::m_info.
Referenced by ICMP::process().
operator!=()
bool ICMPSocket::operator!= (const ICMPSocket & sock) const inline
Definition at line 110 of file ICMPSocket.h.
operator==()
bool ICMPSocket::operator== (const ICMPSocket & sock) const inline
Definition at line 106 of file ICMPSocket.h.
process()
Error ICMPSocket::process (NetworkQueue::Packet * pkt) virtual
Process incoming network packet.
Returns
Error code
Implements NetworkSocket.
Definition at line 76 of file ICMPSocket.cpp.
References DEBUG, and ESUCCESS.
read()
Error ICMPSocket::read (IOBuffer & buffer, Size size, Size offset) virtual
Receive ICMP response.
Parameters
buffer Input/Output buffer to output bytes to.
size Number of bytes to read, at maximum.
offset Offset inside the file to start reading.
Returns
Number of bytes read on success, Error on failure.
Reimplemented from File.
Definition at line 42 of file ICMPSocket.cpp.
References DEBUG, EAGAIN, m_gotReply, m_reply, and IOBuffer::write().
setReply()
void ICMPSocket::setReply (ICMP::Header * reply)
Set ICMP reply.
Parameters
reply ICMP reply header
Definition at line 87 of file ICMPSocket.cpp.
References MemoryBlock::copy(), DEBUG, m_gotReply, and m_reply.
Referenced by ICMP::process().
write()
Error ICMPSocket::write (IOBuffer & buffer, Size size, Size offset) virtual
Send ICMP request.
Parameters
buffer Input/Output buffer to input bytes from.
size Number of bytes to write, at maximum.
offset Offset inside the file to start writing.
Returns
Number of bytes written on success, Error on failure.
Reimplemented from File.
Definition at line 54 of file ICMPSocket.cpp.
References NetworkClient::SocketInfo::address, DEBUG, ESUCCESS, m_icmp, NetworkSocket::m_info, IOBuffer::read(), and ICMP::sendPacket().
Field Documentation
m_gotReply
bool ICMPSocket::m_gotReply private
Definition at line 122 of file ICMPSocket.h.
Referenced by ICMPSocket(), read(), and setReply().
m_icmp
ICMP* ICMPSocket::m_icmp private
ICMP protocol instance.
Definition at line 118 of file ICMPSocket.h.
Referenced by ICMPSocket(), and write().
m_reply
ICMP::Header ICMPSocket::m_reply private
Reply.
Definition at line 121 of file ICMPSocket.h.
Referenced by read(), and setReply().
The documentation for this class was generated from the following files:
lib/libnet/ICMPSocket.h
lib/libnet/ICMPSocket.cpp