FreeNOS: NetworkClient Class Reference
NetworkClient Class Reference
lib » libnet
Networking Client implementation.
#include <NetworkClient.h>
Data Structures
struct SocketInfo
Socket information.
Public Types
enum SocketAction { Connect, Listen }
Socket actions.
enum SocketType { ARP, ICMP, TCP, UDP }
Socket types.
enum Result { Success, IOError, NotFound }
Result codes.
typedef struct NetworkClient::SocketInfo SocketInfo
Socket information.
Public Member Functions
NetworkClient (const char *networkDevice)
Constructor.
virtual ~NetworkClient ()
Destructor.
Result initialize ()
Perform initialization.
Result createSocket (SocketType type, int *socket)
Create new socket.
Result connectSocket (int sock, IPV4::Address addr, u16 port=0)
Connect socket to address/port.
Result bindSocket (int sock, IPV4::Address addr=0, u16 port=0)
Bind socket to address/port.
Result close (int sock)
Close the socket.
Private Member Functions
Result writeSocketInfo (int sock, IPV4::Address addr, u16 port, SocketAction action)
Set socket to new state.
Private Attributes
String m_deviceName
Network device name.
Detailed Description
Networking Client implementation.
Maintains also the network state of each TCP/UDP socket, creates the packets and posts them to ethernet. Also receives packets and extracts socket info.
Because of the client and multiplexer separation the networking stack is very parallel. It can scale very well for multicore/manycore systems as each client may run on a different (possibly dedicated using pinning) core thus running multiple network stack instances on each core in parallel.
Definition at line 44 of file NetworkClient.h.
Member Typedef Documentation
SocketInfo
typedef struct NetworkClient::SocketInfo NetworkClient::SocketInfo
Socket information.
This struct is written to a socket to put it in either connect or listen state.
Member Enumeration Documentation
Result
enum NetworkClient::Result
Result codes.
Enumerator
Success
IOError
NotFound
Definition at line 85 of file NetworkClient.h.
SocketAction
enum NetworkClient::SocketAction
Socket actions.
Enumerator
Connect
Listen
Definition at line 51 of file NetworkClient.h.
SocketType
enum NetworkClient::SocketType
Socket types.
Enumerator
ARP
ICMP
TCP
UDP
Definition at line 74 of file NetworkClient.h.
Constructor & Destructor Documentation
NetworkClient()
NetworkClient::NetworkClient (const char * networkDevice)
Constructor.
Parameters
networkDevice Name of the network device to use
Definition at line 27 of file NetworkClient.cpp.
References m_deviceName.
~NetworkClient()
NetworkClient::~NetworkClient () virtual
Destructor.
Definition at line 32 of file NetworkClient.cpp.
Member Function Documentation
bindSocket()
NetworkClient::Result NetworkClient::bindSocket (int sock, IPV4::Address addr = 0, u16 port = 0)
Bind socket to address/port.
Parameters
sock Socket index
addr Address of the address to bind to
port Port to bind to
Returns
Result code
Definition at line 109 of file NetworkClient.cpp.
References DEBUG, Listen, and writeSocketInfo().
Referenced by NetCat::initialize().
close()
NetworkClient::Result NetworkClient::close (int sock)
Close the socket.
Parameters
socket Network socket to close
Returns
Result code
Definition at line 150 of file NetworkClient.cpp.
References Success.
Referenced by NetPing::arpPing().
connectSocket()
NetworkClient::Result NetworkClient::connectSocket (int sock, IPV4::Address addr, u16 port = 0)
Connect socket to address/port.
Parameters
sock Socket index
addr Address of the host to connect to
port Port of the host to connect to (or ZERO to ignore)
Returns
Result code
Definition at line 103 of file NetworkClient.cpp.
References Connect, DEBUG, and writeSocketInfo().
Referenced by connect(), and NetPing::icmpPing().
createSocket()
NetworkClient::Result NetworkClient::createSocket (NetworkClient::SocketType type, int * socket)
Create new socket.
Parameters
type Type of the socket to create
socket Outputs a pointer to NetworkSocket
Returns
Result code
Definition at line 75 of file NetworkClient.cpp.
References ARP, ICMP, IOError, m_deviceName, NotFound, O_RDWR, open(), Success, and UDP.
Referenced by NetPing::arpPing(), NetPing::icmpPing(), and NetCat::initialize().
initialize()
NetworkClient::Result NetworkClient::initialize ()
Perform initialization.
Returns
Result code
Definition at line 36 of file NetworkClient.cpp.
References ERROR, FILESYSTEM_MAXMOUNTS, getMounts(), IOError, m_deviceName, mounts, FileSystemMount::path, refreshMounts(), strncmp(), and Success.
Referenced by NetPing::arpPing(), connect(), NetPing::icmpPing(), and NetCat::initialize().
writeSocketInfo()
NetworkClient::Result NetworkClient::writeSocketInfo (int sock, IPV4::Address addr, u16 port, NetworkClient::SocketAction action) private
Set socket to new state.
Definition at line 115 of file NetworkClient.cpp.
References NetworkClient::SocketInfo::action, NetworkClient::SocketInfo::address, MemoryBlock::copy(), DEBUG, getFiles(), IOError, FileDescriptor::path, NetworkClient::SocketInfo::port, read(), Success, and write().
Referenced by bindSocket(), and connectSocket().
Field Documentation
m_deviceName
String NetworkClient::m_deviceName private
Network device name.
Definition at line 165 of file NetworkClient.h.
Referenced by createSocket(), initialize(), and NetworkClient().
The documentation for this class was generated from the following files:
lib/libnet/NetworkClient.h
lib/libnet/NetworkClient.cpp