FreeNOS: ATAController Class Reference
ATAController Class Reference
server » ATA
AT Attachment (ATA) Host Controller Device.
#include <ATAController.h>
Public Member Functions
ATAController ()
Constructor function.
virtual Error initialize ()
Configures the ATA controller.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read bytes from a drive attached to the ATA controller.
virtual Error interrupt (Size vector)
Process ATA interrupts.
Public Member Functions inherited from Device
Device (FileType type)
Constructor.
virtual ~Device ()
Destructor.
virtual const String & getIdentifier () const
Get unique device identifier.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Member Functions
void pollReady (bool noData=false)
Polls the Regular Status register.
Private Attributes
List< ATADrive * > drives
Drives detected on the ATA bus.
Additional Inherited Members
Protected Attributes inherited from Device
String m_identifier
Unique identifier for this Device.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
AT Attachment (ATA) Host Controller Device.
Definition at line 261 of file ATAController.h.
Constructor & Destructor Documentation
ATAController()
ATAController::ATAController ()
Constructor function.
Definition at line 34 of file ATAController.cpp.
References Device::m_identifier.
Member Function Documentation
initialize()
Error ATAController::initialize () virtual
Configures the ATA controller.
Returns
Error result code.
Reimplemented from Device.
Definition at line 40 of file ATAController.cpp.
References List< T >::append(), ATA_BASE_CMD0, ATA_CMD_IDENTIFY, ATA_REG_CMD, ATA_REG_DATA, ATA_REG_SELECT, ATA_REG_STATUS, ATA_SEL_MASTER, drives, ESUCCESS, exit(), EXIT_FAILURE, IdentifyData::firmware, IDENTIFY_TEXT_SWAP, ATADrive::identity, IdentifyData::majorRevision, IdentifyData::minorRevision, IdentifyData::model, NOTICE, pollReady(), ReadByte(), ReadWord(), IdentifyData::sectors28, IdentifyData::serial, and WriteByte().
interrupt()
Error ATAController::interrupt (Size vector) virtual
Process ATA interrupts.
Parameters
vector Interrupt number.
Returns
Error result code.
Reimplemented from Device.
Definition at line 140 of file ATAController.cpp.
References ESUCCESS, and INFO.
pollReady()
void ATAController::pollReady (bool noData = false) private
Polls the Regular Status register.
Parameters
noData Don't wait for the ATA_STATUS_DATA flag to set.
Definition at line 146 of file ATAController.cpp.
References ATA_BASE_CMD0, ATA_REG_STATUS, ATA_STATUS_BUSY, ATA_STATUS_DATA, ReadByte(), and File::status().
Referenced by initialize(), and read().
read()
Error ATAController::read (IOBuffer & buffer, Size size, Size offset) virtual
Read bytes from a drive attached to the ATA controller.
Parameters
buffer Buffer to store bytes to read.
size Number of bytes to read.
offset Offset in the device.
Returns
Number of bytes on success and an error code on failure.
Reimplemented from File.
Definition at line 93 of file ATAController.cpp.
References ATA_BASE_CMD0, ATA_CMD_READ, ATA_REG_ADDR0, ATA_REG_ADDR1, ATA_REG_ADDR2, ATA_REG_CMD, ATA_REG_COUNT, ATA_REG_DATA, ATA_REG_SELECT, ATA_SEL_MASTER_28, IOBuffer::bufferedWrite(), CEIL, drives, EIO, List< T >::first(), ATADrive::identity, List< T >::isEmpty(), pollReady(), ReadWord(), IdentifyData::sectors28, and WriteByte().
Field Documentation
drives
List<ATADrive *> ATAController::drives private
Drives detected on the ATA bus.
Definition at line 309 of file ATAController.h.
Referenced by initialize(), and read().
The documentation for this class was generated from the following files:
server/ata/ATAController.h
server/ata/ATAController.cpp