FreeNOS: ARMCore Class Reference
ARMCore Class Reference
lib » libarch » ARM
Class representing an ARM processor core.
#include <ARMCore.h>
Public Types
enum Result { Success = 0 }
Result codes.
Public Member Functions
void logException (CPUState *state) const
Log a CPU exception.
void logState (CPUState *state) const
Log the CPU state.
void logRegister (const char *name, u32 reg, const char *text="") const
Log a register.
Detailed Description
Class representing an ARM processor core.
Definition at line 228 of file ARMCore.h.
Member Enumeration Documentation
Result
enum ARMCore::Result
Result codes.
Enumerator
Success
Definition at line 235 of file ARMCore.h.
Member Function Documentation
logException()
void ARMCore::logException (CPUState * state) const
Log a CPU exception.
Parameters
state The current CPU state.
Definition at line 23 of file ARMCore.cpp.
References logState().
Referenced by ARMKernel::dataAbort(), ARMKernel::prefetchAbort(), ARMKernel::reserved(), and ARMKernel::undefinedInstruction().
logRegister()
void ARMCore::logRegister (const char * name, u32 reg, const char * text = "") const
Log a register.
Parameters
name Name of the register.
reg Value of the register.
text Additional information text.
Definition at line 107 of file ARMCore.cpp.
References Number::Dec, ERROR, and Number::Hex.
Referenced by logState().
logState()
void ARMCore::logState (CPUState * state) const
Log the CPU state.
Parameters
state The current CPU state.
Definition at line 28 of file ARMCore.cpp.
References CPUState::cpsr, ARMControl::DataFaultAddress, ARMControl::DataFaultStatus, ARMControl::InstructionFaultAddress, ARMControl::InstructionFaultStatus, logRegister(), CPUState::lr, CPUState::pc, CPUState::r0, CPUState::r1, CPUState::r10, CPUState::r11, CPUState::r12, CPUState::r2, CPUState::r3, CPUState::r4, CPUState::r5, CPUState::r6, CPUState::r7, CPUState::r8, CPUState::r9, ARMControl::read(), and CPUState::sp.
Referenced by logException().
The documentation for this class was generated from the following files:
lib/libarch/arm/ARMCore.h
lib/libarch/arm/ARMCore.cpp