FreeNOS: TimeCommand Class Reference
TimeCommand Class Reference
bin » sh
Measure the execution time of a program.
#include <TimeCommand.h>
Public Member Functions
TimeCommand ()
Constructor function.
virtual int execute (Size nparams, char **params)
Executes the command.
Public Member Functions inherited from ShellCommand
ShellCommand (const char *name, Size minParams=0)
Constructor.
virtual ~ShellCommand ()
Destructor.
const char * getName () const
Get command name.
const char * getHelp () const
Get command help.
Size getMinimumParams () const
Get the minimum number of parameters required.
Additional Inherited Members
Protected Attributes inherited from ShellCommand
const char * m_name
Unique name of the command.
const char * m_help
Command help text.
Size m_minParams
Minimum number of parameters required.
Detailed Description
Measure the execution time of a program.
Definition at line 35 of file TimeCommand.h.
Constructor & Destructor Documentation
TimeCommand()
TimeCommand::TimeCommand ()
Constructor function.
Definition at line 28 of file TimeCommand.cpp.
References ShellCommand::m_help.
Member Function Documentation
execute()
int TimeCommand::execute (Size nparams, char ** params) virtual
Executes the command.
Parameters
nparams Number of parameters given.
params Array of parameters.
Returns
Error code or zero on success.
Implements ShellCommand.
Definition at line 33 of file TimeCommand.cpp.
References errno, ERROR, EXIT_FAILURE, forkexec(), gettimeofday(), printf(), printtimediff(), snprintf(), strerror(), and waitpid().
The documentation for this class was generated from the following files:
bin/sh/TimeCommand.h
bin/sh/TimeCommand.cpp