FreeNOS: Log Class Reference
Log Class Reference abstract
lib » libstd
Logging class.
#include <Log.h>
Public Types
enum Level {
Emergency, Alert, Critical, Error,
Warning, Notice, Info, Debug
}
Logging level values.
Public Member Functions
Log ()
Constructor.
virtual ~Log ()
Destructor.
Level getMinimumLogLevel ()
Get the minimum logging level.
void setMinimumLogLevel (Level level)
Set the minimum logging level.
void append (const char *str)
Append to buffered output.
void setIdent (const char *ident)
Set log identity.
const char * getIdent () const
Retrieve log identify.
Public Member Functions inherited from Singleton< Log >
Singleton (Log *obj)
Constructor.
Protected Member Functions
virtual void write (const char *str)=0
Write to the actual output device.
Private Attributes
Level m_minimumLogLevel
Minimum log level required to log.
const char * m_ident
Identity.
String m_outputBuffer
Buffered output.
Additional Inherited Members
Static Public Attributes inherited from Singleton< Log >
static Log * instance
One and only instance.
Detailed Description
Logging class.
Note
This class is a singleton
Definition at line 93 of file Log.h.
Member Enumeration Documentation
Level
enum Log::Level
Logging level values.
Enumerator
Emergency
Alert
Critical
Error
Warning
Notice
Info
Debug
Definition at line 98 of file Log.h.
Constructor & Destructor Documentation
Log()
Log::Log ()
Constructor.
Definition at line 21 of file Log.cpp.
References Notice, and setMinimumLogLevel().
~Log()
Log::~Log () virtual
Destructor.
Definition at line 26 of file Log.cpp.
Member Function Documentation
append()
void Log::append (const char * str)
Append to buffered output.
Parameters
str String to append to buffer
Definition at line 50 of file Log.cpp.
References String::endsWith(), m_outputBuffer, and write().
Referenced by Kernel::Kernel(), and operator<<().
getIdent()
const char * Log::getIdent () const
Retrieve log identify.
Returns
Log identity
Definition at line 40 of file Log.cpp.
References m_ident.
getMinimumLogLevel()
Log::Level Log::getMinimumLogLevel ()
Get the minimum logging level.
Returns
Minimum LogLevel
Definition at line 30 of file Log.cpp.
References m_minimumLogLevel.
setIdent()
void Log::setIdent (const char * ident)
Set log identity.
Parameters
ident Log identity
Definition at line 45 of file Log.cpp.
References m_ident.
setMinimumLogLevel()
void Log::setMinimumLogLevel (Log::Level level)
Set the minimum logging level.
Definition at line 35 of file Log.cpp.
References m_minimumLogLevel.
Referenced by kernel_main(), Log(), and main().
write()
virtual void Log::write (const char * str) protected pure virtual
Write to the actual output device.
Implemented in RaspiSerial, IntelSerial, StdioLog, and KernelLog.
Referenced by append().
Field Documentation
m_ident
const char* Log::m_ident private
Identity.
Definition at line 168 of file Log.h.
Referenced by getIdent(), and setIdent().
m_minimumLogLevel
Level Log::m_minimumLogLevel private
Minimum log level required to log.
Definition at line 165 of file Log.h.
Referenced by getMinimumLogLevel(), and setMinimumLogLevel().
m_outputBuffer
String Log::m_outputBuffer private
Buffered output.
Definition at line 171 of file Log.h.
Referenced by append().
The documentation for this class was generated from the following files:
lib/libstd/Log.h
lib/libstd/Log.cpp