FreeNOS: MountWaitFile Class Reference
MountWaitFile Class Reference
server » SysFS
The filesystem mount wait file provides a synchronization point for mounted filesystems.
#include <MountWaitFile.h>
Public Member Functions
MountWaitFile ()
Constructor function.
virtual ~MountWaitFile ()
Destructor function.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read bytes from the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Additional Inherited Members
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
The filesystem mount wait file provides a synchronization point for mounted filesystems.
A client program can write to the mount wait file to indicate it needs have a particular mounted filesystem available. As long as the given mounted path is not available, that write call will block.
See also
FileSystem
Definition at line 40 of file MountWaitFile.h.
Constructor & Destructor Documentation
MountWaitFile()
MountWaitFile::MountWaitFile ()
Constructor function.
Definition at line 22 of file MountWaitFile.cpp.
References File::m_access, and OwnerRW.
~MountWaitFile()
MountWaitFile::~MountWaitFile () virtual
Destructor function.
Definition at line 28 of file MountWaitFile.cpp.
Member Function Documentation
write()
Error MountWaitFile::write (IOBuffer & buffer, Size size, Size offset) virtual
Write bytes to the file.
Parameters
buffer Input/Output buffer to input bytes from.
size Number of bytes to write, at maximum.
offset Offset inside the file to start writing.
Returns
Number of bytes written on success, Error on failure.
Reimplemented from File.
Definition at line 32 of file MountWaitFile.cpp.
References EAGAIN, EIO, FILESYSTEM_MAXMOUNTS, getMounts(), mounts, PATH_MAX, IOBuffer::read(), strcmp(), and String::trim().
The documentation for this class was generated from the following files:
server/filesystem/sys/MountWaitFile.h
server/filesystem/sys/MountWaitFile.cpp