FreeNOS: Hostname Class Reference
Hostname Class Reference
bin
Print the system hostname.
#include <Hostname.h>
Public Member Functions
Hostname (int argc, char **argv)
Constructor.
virtual ~Hostname ()
Destructor.
virtual Result exec ()
Execute the application.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
Print the system hostname.
Definition at line 31 of file Hostname.h.
Constructor & Destructor Documentation
Hostname()
Hostname::Hostname (int argc, char ** argv)
Constructor.
Parameters
argc Argument count
argv Argument values
Definition at line 24 of file Hostname.cpp.
References Application::parser(), and ArgumentParser::setDescription().
~Hostname()
Hostname::~Hostname () virtual
Destructor.
Definition at line 30 of file Hostname.cpp.
Member Function Documentation
exec()
Hostname::Result Hostname::exec () virtual
Execute the application.
Returns
Result code
Implements Application.
Definition at line 34 of file Hostname.cpp.
References gethostname(), printf(), and Application::Success.
The documentation for this class was generated from the following files:
bin/hostname/Hostname.h
bin/hostname/Hostname.cpp