FreeNOS: ARMFirstTable Class Reference
ARMFirstTable Class Reference
lib » libarch » ARM
ARM first level page table.
#include <ARMFirstTable.h>
Public Member Functions
MemoryContext::Result map (Address virt, Address phys, Memory::Access access, SplitAllocator *alloc)
Map a virtual address to a physical address.
MemoryContext::Result mapLarge (Memory::Range range, SplitAllocator *alloc)
Map a contigous range of virtual memory to physical memory.
MemoryContext::Result unmap (Address virt, SplitAllocator *alloc)
Remove virtual address mapping.
MemoryContext::Result translate (Address virt, Address *phys, SplitAllocator *alloc) const
Translate virtual address to physical address.
MemoryContext::Result access (Address virt, Memory::Access *access, SplitAllocator *alloc) const
Get Access flags for a virtual address.
MemoryContext::Result releaseRange (Memory::Range range, SplitAllocator *alloc, bool tablesOnly)
Release range of memory.
Private Member Functions
ARMSecondTable * getSecondTable (Address virt, SplitAllocator *alloc) const
Retrieve second level page table.
u32 flags (Memory::Access access) const
Convert Memory::Access to first level page table flags.
Private Attributes
u32 m_tables [4096]
Array of page table entries.
Detailed Description
ARM first level page table.
Definition at line 43 of file ARMFirstTable.h.
Member Function Documentation
access()
MemoryContext::Result ARMFirstTable::access (Address virt, Memory::Access * access, SplitAllocator * alloc) const
Get Access flags for a virtual address.
Parameters
virt Virtual address to get Access flags for.
access MemoryAccess object pointer.
alloc Physical memory allocator
Returns
Result code.
Definition at line 205 of file ARMFirstTable.cpp.
References ARMSecondTable::access(), getSecondTable(), and MemoryContext::InvalidAddress.
Referenced by ARMPaging::access().
flags()
u32 ARMFirstTable::flags (Memory::Access access) const private
Convert Memory::Access to first level page table flags.
Parameters
access Memory access flags to convert
Returns
Page table access flags
Definition at line 216 of file ARMFirstTable.cpp.
References Memory::Device, Memory::Executable, PAGE1_AP_SYS, PAGE1_AP_USER, PAGE1_APX, PAGE1_CACHE_WRITEBACK, PAGE1_DEVICE_SHARED, PAGE1_NOEXEC, PAGE1_UNCACHED, Memory::Uncached, Memory::User, and Memory::Writable.
Referenced by mapLarge().
getSecondTable()
ARMSecondTable * ARMFirstTable::getSecondTable (Address virt, SplitAllocator * alloc) const private
Retrieve second level page table.
Parameters
virt Virtual address to fetch page table for
alloc Physical memory allocator
Returns
Second level page table
Definition at line 107 of file ARMFirstTable.cpp.
References DIRENTRY, m_tables, PAGE1_TABLE, PAGEMASK, SplitAllocator::toVirtual(), and ZERO.
Referenced by access(), map(), releaseRange(), translate(), and unmap().
map()
MemoryContext::Result ARMFirstTable::map (Address virt, Address phys, Memory::Access access, SplitAllocator * alloc)
Map a virtual address to a physical address.
Parameters
virt Virtual address.
phys Physical address.
access Memory access flags.
alloc Physical memory allocator for extra page tables.
Returns
Result code
Definition at line 118 of file ARMFirstTable.cpp.
References SplitAllocator::allocateLow(), MemoryContext::AlreadyExists, Cache::cleanData(), DIRENTRY, getSecondTable(), MemoryContext::InvalidAddress, m_tables, ARMSecondTable::map(), MemoryContext::OutOfMemory, PAGE1_SECTION, PAGE1_TABLE, PAGEMASK, PAGESIZE, MemoryBlock::set(), Allocator::Success, and SplitAllocator::toVirtual().
Referenced by ARMPaging::map().
mapLarge()
MemoryContext::Result ARMFirstTable::mapLarge (Memory::Range range, SplitAllocator * alloc)
Map a contigous range of virtual memory to physical memory.
This function can map at the granularity of 1 megabyte memory chunks.
Parameters
range Virtual to physical memory range.
alloc Physical memory allocator for extra page tables.
Returns
Result code
Definition at line 152 of file ARMFirstTable.cpp.
References Memory::Range::access, MemoryContext::AlreadyExists, Cache::cleanData(), DIRENTRY, flags(), MemoryContext::InvalidAddress, MemoryContext::InvalidSize, m_tables, MegaByte, PAGE1_SECTION, PAGE1_TABLE, PAGEMASK, Memory::Range::phys, Memory::Range::size, MemoryContext::Success, and Memory::Range::virt.
Referenced by ARMPaging::ARMPaging().
releaseRange()
MemoryContext::Result ARMFirstTable::releaseRange (Memory::Range range, SplitAllocator * alloc, bool tablesOnly)
Release range of memory.
Parameters
range Memory range input
alloc Memory allocator to release memory from
tablesOnly Set to true to only release page tables and not mapped pages.
Returns
Result code
Definition at line 233 of file ARMFirstTable.cpp.
References DIRENTRY, getSecondTable(), m_tables, MegaByte, PAGEMASK, PAGESIZE, SplitAllocator::release(), Memory::Range::size, MemoryContext::Success, ARMSecondTable::translate(), and Memory::Range::virt.
Referenced by ARMPaging::releaseRange(), and ARMPaging::releaseRegion().
translate()
MemoryContext::Result ARMFirstTable::translate (Address virt, Address * phys, SplitAllocator * alloc) const
Translate virtual address to physical address.
Parameters
virt Virtual address to lookup as input
phys Physical address corresponding to the virtual address
alloc Physical memory allocator
Returns
Result code
Definition at line 194 of file ARMFirstTable.cpp.
References getSecondTable(), MemoryContext::InvalidAddress, and ARMSecondTable::translate().
Referenced by ARMPaging::lookup().
unmap()
MemoryContext::Result ARMFirstTable::unmap (Address virt, SplitAllocator * alloc)
Remove virtual address mapping.
Parameters
virt Virtual address.
alloc Physical memory allocator
Returns
Result code
Definition at line 174 of file ARMFirstTable.cpp.
References Cache::cleanData(), DIRENTRY, getSecondTable(), MemoryContext::InvalidAddress, m_tables, PAGE1_NONE, PAGE1_SECTION, MemoryContext::Success, and ARMSecondTable::unmap().
Referenced by ARMPaging::ARMPaging(), and ARMPaging::unmap().
Field Documentation
m_tables
u32 ARMFirstTable::m_tables[4096] private
Array of page table entries.
Definition at line 150 of file ARMFirstTable.h.
Referenced by getSecondTable(), map(), mapLarge(), releaseRange(), and unmap().
The documentation for this class was generated from the following files:
lib/libarch/arm/ARMFirstTable.h
lib/libarch/arm/ARMFirstTable.cpp