FreeNOS: Directory Class Reference
Directory Class Reference
lib » libfs
Directory File functionality.
#include <Directory.h>
Public Member Functions
Directory ()
Constructor.
virtual ~Directory ()
Destructor.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read directory entries.
virtual File * lookup (const char *name)
Retrieve a File from storage.
void insert (FileType type, const char *name,...)
Insert a new directory entry.
void remove (const char *name)
Remove a directory entry.
void clear ()
Clears the internal list of entries.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Member Functions
Dirent * get (const char *name)
Retrieve a directory entry by it's name.
Private Attributes
List< Dirent * > entries
List of directory entries.
Additional Inherited Members
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
Directory File functionality.
A Directory is a File which may have several child File's. Each child File which also is a Directory, may in turn have child File's. This way, a FileSystem can form a tree of File's and Directories.
See also
FileSystem
File
Definition at line 72 of file Directory.h.
Constructor & Destructor Documentation
Directory()
Directory::Directory ()
Constructor.
Definition at line 20 of file Directory.cpp.
References DirectoryFile, and insert().
~Directory()
Directory::~Directory () virtual
Destructor.
Definition at line 26 of file Directory.cpp.
References List< T >::clear(), entries, and ListIterator< T >::hasCurrent().
Member Function Documentation
clear()
void Directory::clear ()
Clears the internal list of entries.
Definition at line 95 of file Directory.cpp.
References List< T >::clear(), entries, and ListIterator< T >::hasCurrent().
get()
Dirent * Directory::get (const char * name) private
Retrieve a directory entry by it's name.
Parameters
name Name of the entry to get.
Returns
Direct pointer on success, ZERO otherwise.
Definition at line 103 of file Directory.cpp.
References entries, ListIterator< T >::hasCurrent(), name, strcmp(), and ZERO.
insert()
void Directory::insert (FileType type, const char * name, ...)
Insert a new directory entry.
FileSystem implementations should implement this function to insert a new implementation defined directory entry into the underlying Storage.
Parameters
type File type.
name Formatted name of the entry to add.
... Argument list.
Note
Entry names must be unique within the same Directory.
See also
FileSystem
Storage
Definition at line 58 of file Directory.cpp.
References List< T >::append(), DIRENT_LEN, entries, File::m_size, Dirent::name, PATHLEN, strlcpy(), Dirent::type, va_end, va_start, and vsnprintf().
Referenced by Directory(), main(), and FileSystem::processRequest().
lookup()
File * Directory::lookup (const char * name) virtual
Retrieve a File from storage.
This virtual function is responsible for reading a directory entry from storage which is not already in the FileCache. It creates a File object for the directory entry and returns a pointer to it, if found.
Parameters
name Name of the directory entry to lookup.
Returns
Pointer to a File on success, ZERO otherwise.
See also
File
Dirent
Storage
Reimplemented in LinnDirectory.
Definition at line 53 of file Directory.cpp.
References ZERO.
Referenced by FileSystem::lookupFile().
read()
Error Directory::read (IOBuffer & buffer, Size size, Size offset) virtual
Read directory entries.
This default read implementation reads the private List of Dirent entries from memory. It can be usefull for pseudo filesystems which don't have any real data on Storage. Filesystem that do have date on Storage should implement their version of read().
Parameters
buffer Input/Output buffer to output bytes to.
size Number of bytes to read, at maximum.
offset Offset inside the file to start reading.
Returns
Number of bytes read on success, Error on failure.
See also
FileSystem
Storage
Dirent
Reimplemented from File.
Reimplemented in LinnDirectory.
Definition at line 34 of file Directory.cpp.
References entries, ListIterator< T >::hasCurrent(), and IOBuffer::write().
remove()
void Directory::remove (const char * name)
Remove a directory entry.
A FileSystem implemenatation should lookup the internal entry for the given name, and update the underlying Storage to remove any references for it inside this Directory.
Parameters
name Name of the entry to remove.
See also
FileSystem
Storage
Definition at line 81 of file Directory.cpp.
References entries, ListIterator< T >::hasCurrent(), File::m_size, name, and strcmp().
Field Documentation
entries
List<Dirent *> Directory::entries private
List of directory entries.
This List should only be used for pseudo filesystems, which use the default implementations of read(), insert() and remove().
See also
List
Directory::read
Directory::insert
Directory::remove
Definition at line 185 of file Directory.h.
Referenced by clear(), get(), insert(), read(), remove(), and ~Directory().
The documentation for this class was generated from the following files:
lib/libfs/Directory.h
lib/libfs/Directory.cpp