FreeNOS: Container Class Reference
Container Class Reference abstract
lib » libstd
Containers provide access to stored items.
#include <Container.h>
Public Member Functions
Container ()
Constructor.
virtual ~Container ()
Destructor.
virtual Size size () const =0
Returns the maximum size of this Container.
virtual Size count () const =0
Returns the number of items inside the Container.
virtual void clear ()=0
Removes all items from the Container.
virtual bool isEmpty () const
Check if the Container is empty.
virtual bool reserve (Size size)
Ensure that at least the given size is available.
virtual bool shrink (Size size)
Shrink the container size by the given amount of items.
virtual Size squeeze ()
Try to minimize the memory required in the Container.
virtual bool resize (Size size)
Change the size of the Container.
Detailed Description
Containers provide access to stored items.
Definition at line 35 of file Container.h.
Constructor & Destructor Documentation
Container()
Container::Container ()
Constructor.
Definition at line 20 of file Container.cpp.
~Container()
Container::~Container () virtual
Destructor.
Definition at line 24 of file Container.cpp.
Member Function Documentation
clear()
virtual void Container::clear () pure virtual
Removes all items from the Container.
Implemented in List< T >, List< Dirent *>, List< InterruptHook *>, List< FileSystemRequest *>, List< Device *>, List< TestInstance *>, List< String *>, List< HashTable::Bucket >, List< uint >, List< K >, List< ATADrive *>, Vector< T >, Vector< LinnGroup *>, Vector< Argument *>, Vector< Size >, Vector< MessageHandler< IPCHandlerFunction > *>, Vector< Process *>, Vector< List< InterruptHook *> *>, Vector< MessageHandler< IRQHandlerFunction > *>, Vector< Device *>, Vector< List< Device *> *>, Vector< Handler *>, Vector< List< HashTable::Bucket > >, Sequence< T >, Sequence< Handler * >, Sequence< String * >, Sequence< NetworkQueue::Packet >, Sequence< Size >, Sequence< MemoryChannel >, Sequence< TestInstance * >, Sequence< ProcessShares::MemoryShare >, Sequence< FileSystemRequest * >, Sequence< InterruptHook * >, Sequence< MessageHandler< IRQHandlerFunction > * >, Sequence< Dirent * >, Sequence< USBDescriptor::Endpoint >, Sequence< List< InterruptHook * > * >, Sequence< MessageHandler< IPCHandlerFunction > * >, Sequence< Process * >, Sequence< u8 >, Sequence< LinnGroup * >, Sequence< List< Device * > * >, Sequence< UDPSocket >, Sequence< USBDescriptor::String >, Sequence< HashTable::Bucket >, Sequence< ChannelClient::Request >, Sequence< ICMPSocket >, Sequence< USBDescriptor::Interface >, Sequence< CoreInfo >, Sequence< List< HashTable::Bucket > >, Sequence< char >, Sequence< Argument * >, Sequence< uint >, Sequence< K >, Sequence< SynopsisChannel >, Sequence< Device * >, Sequence< ATADrive * >, Associative< K, V >, Associative< u32, LinnInode * >, Associative< IPV4::Address, ARP::ARPCache * >, Associative< String, ShellCommand * >, Associative< u16, UDPSocket * >, Associative< String, Argument * >, Associative< ProcessID, Channel * >, and Associative< String, FileCache * >.
count()
virtual Size Container::count () const pure virtual
Returns the number of items inside the Container.
Returns
Number of items inside the Container.
Implemented in List< T >, List< Dirent *>, List< InterruptHook *>, List< FileSystemRequest *>, List< Device *>, List< TestInstance *>, List< String *>, List< HashTable::Bucket >, List< uint >, List< K >, List< ATADrive *>, Index< T >, Index< NetworkQueue::Packet >, Index< MemoryChannel >, Index< ProcessShares::MemoryShare >, Index< USBDescriptor::Endpoint >, Index< UDPSocket >, Index< USBDescriptor::String >, Index< ChannelClient::Request >, Index< ICMPSocket >, Index< USBDescriptor::Interface >, Index< CoreInfo >, Index< SynopsisChannel >, HashTable< K, V >, HashTable< String, Argument *>, HashTable< u16, UDPSocket *>, HashTable< String, ShellCommand *>, HashTable< u32, LinnInode *>, HashTable< IPV4::Address, ARP::ARPCache *>, HashTable< ProcessID, Channel *>, HashTable< String, FileCache *>, Vector< T >, Vector< LinnGroup *>, Vector< Argument *>, Vector< Size >, Vector< MessageHandler< IPCHandlerFunction > *>, Vector< Process *>, Vector< List< InterruptHook *> *>, Vector< MessageHandler< IRQHandlerFunction > *>, Vector< Device *>, Vector< List< Device *> *>, Vector< Handler *>, Vector< List< HashTable::Bucket > >, Array< T, N >, Array< u8, 128 >, and String.
Referenced by Sequence< ATADrive * >::compareTo(), Associative< String, FileCache * >::compareTo(), and isEmpty().
isEmpty()
bool Container::isEmpty () const virtual
Check if the Container is empty.
Returns
True if empty, false otherwise.
Reimplemented in List< T >, List< Dirent *>, List< InterruptHook *>, List< FileSystemRequest *>, List< Device *>, List< TestInstance *>, List< String *>, List< HashTable::Bucket >, List< uint >, List< K >, and List< ATADrive *>.
Definition at line 28 of file Container.cpp.
References count().
reserve()
bool Container::reserve (Size size) virtual
Ensure that at least the given size is available.
Parameters
size Size to reserve in the Container
Returns
True if the given size is reserved, false otherwise.
Reimplemented in String.
Definition at line 33 of file Container.cpp.
References resize(), and size().
resize()
bool Container::resize (Size size) virtual
Change the size of the Container.
Parameters
size New size of the container.
Returns
True if the resize succeeded, false otherwise.
Reimplemented in Vector< T >, Vector< LinnGroup *>, Vector< Argument *>, Vector< Size >, Vector< MessageHandler< IPCHandlerFunction > *>, Vector< Process *>, Vector< List< InterruptHook *> *>, Vector< MessageHandler< IRQHandlerFunction > *>, Vector< Device *>, Vector< List< Device *> *>, Vector< Handler *>, Vector< List< HashTable::Bucket > >, and String.
Definition at line 51 of file Container.cpp.
Referenced by Index< SynopsisChannel >::insert(), reserve(), and shrink().
shrink()
bool Container::shrink (Size size) virtual
Shrink the container size by the given amount of items.
Parameters
size Number of items to shrink.
Returns
True if shrink succeeded, false otherwise.
Definition at line 41 of file Container.cpp.
References resize(), and size().
size()
virtual Size Container::size () const pure virtual
Returns the maximum size of this Container.
Returns
size The maximum size of this Container.
Implemented in List< T >, List< Dirent *>, List< InterruptHook *>, List< FileSystemRequest *>, List< Device *>, List< TestInstance *>, List< String *>, List< HashTable::Bucket >, List< uint >, List< K >, List< ATADrive *>, Index< T >, Index< NetworkQueue::Packet >, Index< MemoryChannel >, Index< ProcessShares::MemoryShare >, Index< USBDescriptor::Endpoint >, Index< UDPSocket >, Index< USBDescriptor::String >, Index< ChannelClient::Request >, Index< ICMPSocket >, Index< USBDescriptor::Interface >, Index< CoreInfo >, Index< SynopsisChannel >, HashTable< K, V >, HashTable< String, Argument *>, HashTable< u16, UDPSocket *>, HashTable< String, ShellCommand *>, HashTable< u32, LinnInode *>, HashTable< IPV4::Address, ARP::ARPCache *>, HashTable< ProcessID, Channel *>, HashTable< String, FileCache *>, Vector< T >, Vector< LinnGroup *>, Vector< Argument *>, Vector< Size >, Vector< MessageHandler< IPCHandlerFunction > *>, Vector< Process *>, Vector< List< InterruptHook *> *>, Vector< MessageHandler< IRQHandlerFunction > *>, Vector< Device *>, Vector< List< Device *> *>, Vector< Handler *>, Vector< List< HashTable::Bucket > >, Array< T, N >, Array< u8, 128 >, and String.
Referenced by Sequence< ATADrive * >::clear(), Sequence< ATADrive * >::compareTo(), Associative< String, FileCache * >::compareTo(), Sequence< ATADrive * >::contains(), Sequence< ATADrive * >::fill(), reserve(), shrink(), and squeeze().
squeeze()
Size Container::squeeze () virtual
Try to minimize the memory required in the Container.
Returns
New size of the Container.
Definition at line 46 of file Container.cpp.
References size().
The documentation for this class was generated from the following files:
lib/libstd/Container.h
lib/libstd/Container.cpp