FreeNOS: FileSystem Class Reference
FileSystem Class Reference
lib » libfs
Abstract filesystem class.
#include <FileSystem.h>
Public Member Functions
FileSystem (const char *path)
Constructor function.
virtual ~FileSystem ()
Destructor function.
const char * getMountPath () const
Get mount path.
Directory * getRoot ()
Get root directory.
Error mount ()
Mount the FileSystem.
Error registerFile (File *file, const char *path,...)
Register a new File.
Error registerFile (File *file, const char *path, va_list args)
Register a new File with variable arguments.
virtual File * createFile (FileType type, DeviceID deviceID)
Create a new file.
FileCache * insertFileCache (File *file, const char *pathFormat,...)
Inserts a file into the in-memory filesystem tree.
FileCache * insertFileCache (File *file, const char *pathFormat, va_list args)
Inserts a file into the in-memory filesystem tree.
void pathHandler (FileSystemMessage *msg)
Process an incoming filesystem request using a path.
virtual void timeout ()
Called when a sleep timeout is expired.
virtual bool retryRequests ()
Retry any pending requests.
Public Member Functions inherited from ChannelServer< FileSystem, FileSystemMessage >
ChannelServer (FileSystem *inst, Size num=32)
Constructor function.
virtual ~ChannelServer ()
Destructor function.
int run ()
Enters an infinite loop, serving incoming requests.
void addIPCHandler (Size slot, IPCHandlerFunction h, bool sendReply=true)
Register a new IPC message action handler.
void addIRQHandler (Size slot, IRQHandlerFunction h)
Register a new IRQ message vector handler.
void setTimeout (uint msec)
Set a sleep timeout.
Protected Member Functions
Error processRequest (FileSystemRequest *req)
Process a FileSystemRequest.
void sendResponse (FileSystemMessage *msg)
Send response for a FileSystemMessage.
void setRoot (Directory *newRoot)
Change the filesystem root directory.
FileCache * lookupFile (FileSystemPath *path)
Retrieve a File from storage.
FileCache * findFileCache (char *path)
Search the cache for an entry.
FileCache * findFileCache (String *path)
Search the cache for an entry.
FileCache * findFileCache (FileSystemPath *p)
Search the cache for an entry.
virtual FileCache * cacheHit (FileCache *cache)
Process a cache hit.
void clearFileCache (FileCache *cache=ZERO)
Cleans up the entire file cache (except opened file caches and root).
Protected Attributes
FileCache * m_root
Root entry of the filesystem tree.
const char * m_mountPath
Mount point.
List< FileSystemRequest * > * m_requests
Contains ongoing requests.
Protected Attributes inherited from ChannelServer< FileSystem, FileSystemMessage >
ChannelRegistry * m_registry
Contains registered channels.
ChannelClient * m_client
Client for sending replies.
MemoryChannel m_kernelEvent
Kernel event channel.
bool m_sendReply
Should we send a reply message?
Vector< MessageHandler< IPCHandlerFunction > *> * m_ipcHandlers
IPC handler functions.
Vector< MessageHandler< IRQHandlerFunction > *> * m_irqHandlers
IRQ handler functions.
FileSystem * m_instance
Server object instance.
ProcessID m_self
ProcessID of ourselves.
Timer::Info m_time
System timer value.
Additional Inherited Members
Public Types inherited from ChannelServer< FileSystem, FileSystemMessage >
enum Result
Result codes.
Protected Types inherited from ChannelServer< FileSystem, FileSystemMessage >
typedef void(FileSystem ::* IPCHandlerFunction) (FileSystemMessage *)
Member function pointer inside Base, to handle IPC messages.
typedef void(FileSystem ::* IRQHandlerFunction) (Size)
Member function pointer inside Base, to handle interrupts.
Detailed Description
Abstract filesystem class.
Definition at line 43 of file FileSystem.h.
Constructor & Destructor Documentation
FileSystem()
FileSystem::FileSystem (const char * path)
Constructor function.
Parameters
p Path to which we are mounted.
Definition at line 28 of file FileSystem.cpp.
References ChannelServer< FileSystem, FileSystemMessage >::addIPCHandler(), DeleteFile, m_mountPath, m_requests, m_root, pathHandler(), ReadFile, StatFile, and WriteFile.
~FileSystem()
FileSystem::~FileSystem () virtual
Destructor function.
Definition at line 44 of file FileSystem.cpp.
References m_requests.
Member Function Documentation
cacheHit()
FileCache * FileSystem::cacheHit (FileCache * cache) protected virtual
Process a cache hit.
Parameters
cache FileCache object which has just been referenced.
Returns
FileCache object pointer.
Definition at line 427 of file FileSystem.cpp.
Referenced by findFileCache().
clearFileCache()
void FileSystem::clearFileCache (FileCache * cache = ZERO) protected
Cleans up the entire file cache (except opened file caches and root).
Parameters
cache Input FileCache object. ZERO to clean up all from root.
Definition at line 432 of file FileSystem.cpp.
References HashTable< K, V >::count(), FileCache::entries, FileCache::file, HashIterator< K, V >::hasCurrent(), m_root, FileCache::name, FileCache::parent, HashTable< K, V >::remove(), and FileCache::valid.
Referenced by processRequest().
createFile()
File * FileSystem::createFile (FileType type, DeviceID deviceID) virtual
Create a new file.
Parameters
type Describes the type of file to create.
deviceID Optionally specifies the device identities to create.
Returns
Pointer to a new File on success or ZERO on failure.
Reimplemented in TmpFileSystem.
Definition at line 97 of file FileSystem.cpp.
References ZERO.
Referenced by processRequest().
findFileCache() [1/3]
FileCache * FileSystem::findFileCache (char * path) protected
Search the cache for an entry.
Parameters
path Full path of the file to find.
Returns
Pointer to FileCache object on success, NULL on failure.
Definition at line 389 of file FileSystem.cpp.
Referenced by findFileCache(), insertFileCache(), processRequest(), and registerFile().
findFileCache() [2/3]
FileCache * FileSystem::findFileCache (String * path) protected
Search the cache for an entry.
Parameters
path Full path of the file to find.
Returns
Pointer to FileCache object on success, NULL on failure.
Definition at line 395 of file FileSystem.cpp.
References findFileCache(), and ZERO.
findFileCache() [3/3]
FileCache * FileSystem::findFileCache (FileSystemPath * p) protected
Search the cache for an entry.
Parameters
path Full path of the file to find.
Returns
Pointer to FileCache object on success, NULL on failure.
Definition at line 400 of file FileSystem.cpp.
References cacheHit(), Associative< K, V >::contains(), FileCache::entries, ListIterator< T >::hasCurrent(), FileSystemPath::length(), m_root, FileSystemPath::parent(), FileSystemPath::split(), FileCache::valid, HashTable< K, V >::value(), and ZERO.
getMountPath()
const char * FileSystem::getMountPath () const
Get mount path.
Returns
Mount path of the filesystem
Definition at line 50 of file FileSystem.cpp.
References m_mountPath.
Referenced by UDP::createSocket(), and ICMP::createSocket().
getRoot()
Directory * FileSystem::getRoot ()
Get root directory.
Returns
Root directory pointer
Definition at line 55 of file FileSystem.cpp.
References FileCache::file, and m_root.
Referenced by main().
insertFileCache() [1/2]
FileCache * FileSystem::insertFileCache (File * file, const char * pathFormat, ...)
Inserts a file into the in-memory filesystem tree.
Parameters
file File to insert.
pathFormat Formatted full path to the file to insert.
... Argument list.
Returns
Pointer to the newly created FileCache, or NULL on failure.
Definition at line 353 of file FileSystem.cpp.
References va_end, and va_start.
Referenced by main(), processRequest(), registerFile(), and setRoot().
insertFileCache() [2/2]
FileCache * FileSystem::insertFileCache (File * file, const char * pathFormat, va_list args)
Inserts a file into the in-memory filesystem tree.
Parameters
file File to insert.
pathFormat Formatted full path to the file to insert.
args Argument list.
Returns
Pointer to the newly created FileCache, or NULL on failure.
Definition at line 364 of file FileSystem.cpp.
References FileSystemPath::base(), findFileCache(), m_root, FileSystemPath::parent(), FileSystemPath::parse(), PATHLEN, vsnprintf(), and ZERO.
lookupFile()
FileCache * FileSystem::lookupFile (FileSystemPath * path) protected
Retrieve a File from storage.
This function is responsible for walking the given FileSystemPath, retrieving each uncached File into the FileCache, and returning a pointer to corresponding FileCache of the last entry in the given path.
Parameters
path A path to lookup from storage.
Returns
Pointer to a FileCache on success, ZERO otherwise.
Definition at line 312 of file FileSystem.cpp.
References Associative< K, V >::contains(), DirectoryFile, FileCache::entries, FileCache::file, File::getType(), ListIterator< T >::hasCurrent(), Directory::lookup(), m_root, FileSystemPath::split(), HashTable< K, V >::value(), and ZERO.
Referenced by processRequest().
mount()
Error FileSystem::mount ()
Mount the FileSystem.
This function is responsible for mounting the FileSystem.
Returns
True if mounted successfully, false otherwise.
Definition at line 60 of file FileSystem.cpp.
References close(), errno, ERROR, ESUCCESS, GetPID, m_mountPath, O_WRONLY, open(), FileSystemMount::options, FileSystemMount::path, PATH_MAX, ProcessCtl(), FileSystemMount::procID, ROOTFS_PID, SELF, strerror(), strlcpy(), SYSFS_PID, and write().
Referenced by DeviceServer::initialize(), and main().
pathHandler()
void FileSystem::pathHandler (FileSystemMessage * msg)
Process an incoming filesystem request using a path.
This message handler is responsible for processing any kind of FileSystemMessages which have an FileSystemAction using the path field, such as OpenFile.
Parameters
msg Incoming request message.
See also
FileSystemMessage
FileSystemAction
Definition at line 135 of file FileSystem.cpp.
References List< T >::append(), EAGAIN, m_requests, and processRequest().
Referenced by FileSystem().
processRequest()
Error FileSystem::processRequest (FileSystemRequest * req) protected
Process a FileSystemRequest.
Returns
EAGAIN if the request cannot be completed yet or any other error code if processed.
Definition at line 147 of file FileSystem.cpp.
References FileSystemMessage::action, IOBuffer::bufferedRead(), clearFileCache(), HashTable< K, V >::count(), CreateFile, createFile(), DEBUG, DeleteFile, FileSystemMessage::deviceID, EACCES, EAGAIN, EEXIST, EIO, ENOENT, ENOTEMPTY, FileCache::entries, ERROR, ESUCCESS, FileCache::file, FileSystemMessage::filetype, findFileCache(), IOBuffer::flush(), FileSystemMessage::from, FileSystemPath::full(), FileSystemRequest::getBuffer(), IOBuffer::getCount(), FileSystemRequest::getMessage(), ChannelRegistry::getProducer(), File::getType(), Directory::insert(), insertFileCache(), lookupFile(), m_mountPath, ChannelServer< FileSystem, FileSystemMessage >::m_registry, m_root, ChannelServer< FileSystem, FileSystemMessage >::m_self, FileSystemMessage::offset, FileSystemPath::parent(), FileSystemPath::parse(), FileSystemMessage::path, PATHLEN, ProcessCtl(), File::read(), API::Read, ReadFile, ChannelMessage::Response, FileSystemMessage::result, Resume, sendResponse(), FileSystemMessage::size, FileSystemMessage::stat, StatFile, File::status(), strlen(), ChannelMessage::type, VMCopy(), File::write(), Channel::write(), WriteFile, and ZERO.
Referenced by pathHandler(), and retryRequests().
registerFile() [1/2]
Error FileSystem::registerFile (File * file, const char * path, ...)
Register a new File.
Parameters
file File object pointer.
path The path for the File.
Returns
Error code.
Definition at line 102 of file FileSystem.cpp.
References va_end, and va_start.
Referenced by UDP::createSocket(), ICMP::createSocket(), USBController::initialize(), UDP::initialize(), ICMP::initialize(), Ethernet::initialize(), IPV4::initialize(), ARP::initialize(), DeviceServer::registerDevice(), and SysInfoFileSystem::SysInfoFileSystem().
registerFile() [2/2]
Error FileSystem::registerFile (File * file, const char * path, va_list args)
Register a new File with variable arguments.
Parameters
file File object pointer.
path The path for the File.
args Variable argument list.
Returns
Error code.
Definition at line 114 of file FileSystem.cpp.
References FileSystemPath::base(), ESUCCESS, FileCache::file, findFileCache(), File::getType(), insertFileCache(), m_root, FileSystemPath::parent(), PATHLEN, and vsnprintf().
retryRequests()
bool FileSystem::retryRequests () virtual
Retry any pending requests.
Returns
True if retry is needed again, false if all requests processed
Reimplemented from ChannelServer< FileSystem, FileSystemMessage >.
Definition at line 279 of file FileSystem.cpp.
References DEBUG, EAGAIN, ListIterator< T >::hasCurrent(), m_requests, and processRequest().
Referenced by DeviceServer::interruptHandler(), and timeout().
sendResponse()
void FileSystem::sendResponse (FileSystemMessage * msg) protected
Send response for a FileSystemMessage.
Parameters
msg The FileSystemMessage to send response for
Definition at line 265 of file FileSystem.cpp.
References FileSystemMessage::from, ChannelRegistry::getProducer(), ChannelServer< FileSystem, FileSystemMessage >::m_registry, ProcessCtl(), ChannelMessage::Response, Resume, ChannelMessage::type, and Channel::write().
Referenced by LinnFileSystem::notSupportedHandler(), and processRequest().
setRoot()
void FileSystem::setRoot (Directory * newRoot) protected
Change the filesystem root directory.
This function set the root member to the given Directory pointer. Additionally, it inserts '/.' and '/..' references to the file cache.
Parameters
newRoot A Directory pointer to set as the new root.
See also
root
insertFileCache
Definition at line 305 of file FileSystem.cpp.
References insertFileCache(), m_root, and ZERO.
Referenced by DeviceServer::initialize(), LinnFileSystem::LinnFileSystem(), SysInfoFileSystem::SysInfoFileSystem(), and TmpFileSystem::TmpFileSystem().
timeout()
void FileSystem::timeout () virtual
Called when a sleep timeout is expired.
This function does a retry on all FileSystemRequests
Reimplemented from ChannelServer< FileSystem, FileSystemMessage >.
Definition at line 272 of file FileSystem.cpp.
References DEBUG, and retryRequests().
Field Documentation
m_mountPath
const char* FileSystem::m_mountPath protected
Mount point.
Definition at line 257 of file FileSystem.h.
Referenced by FileSystem(), getMountPath(), mount(), and processRequest().
m_requests
List<FileSystemRequest *>* FileSystem::m_requests protected
Contains ongoing requests.
Definition at line 260 of file FileSystem.h.
Referenced by FileSystem(), pathHandler(), retryRequests(), and ~FileSystem().
m_root
FileCache* FileSystem::m_root protected
Root entry of the filesystem tree.
Definition at line 254 of file FileSystem.h.
Referenced by clearFileCache(), FileSystem(), findFileCache(), getRoot(), insertFileCache(), lookupFile(), processRequest(), registerFile(), and setRoot().
The documentation for this class was generated from the following files:
lib/libfs/FileSystem.h
lib/libfs/FileSystem.cpp