FreeNOS: ConstIterator< T > Class Template Reference
ConstIterator< T > Class Template Reference abstract
lib » libstd
Abstracts an iteration process for a constant.
#include <ConstIterator.h>
Public Member Functions
virtual ~ConstIterator ()
Destructor.
virtual void reset ()=0
Restart iteration from the beginning.
virtual bool hasNext () const =0
Check if there is more to iterate.
virtual bool hasCurrent () const =0
Check if there is a current item.
virtual const T & current () const =0
Get the current item read-only.
virtual const T & next ()=0
Fetch the next item.
virtual void operator++ (int num)=0
Increment operator.
Detailed Description
template<class T>
class ConstIterator< T >
Abstracts an iteration process for a constant.
Definition at line 34 of file ConstIterator.h.
Constructor & Destructor Documentation
~ConstIterator()
template<class T> virtual ConstIterator< T >::~ConstIterator () inline virtual
Destructor.
Definition at line 41 of file ConstIterator.h.
Member Function Documentation
current()
template<class T> virtual const T& ConstIterator< T >::current () const pure virtual
Get the current item read-only.
Returns
Reference to the next item.
Implemented in ConstHashIterator< K, V >.
Referenced by ConstIterator< V >::~ConstIterator().
hasCurrent()
template<class T> virtual bool ConstIterator< T >::hasCurrent () const pure virtual
Check if there is a current item.
Returns
True if the iterator has a current item, false otherwise.
Implemented in ConstHashIterator< K, V >.
Referenced by ConstIterator< V >::~ConstIterator().
hasNext()
template<class T> virtual bool ConstIterator< T >::hasNext () const pure virtual
Check if there is more to iterate.
Returns
true if more items, false if not.
Implemented in ConstHashIterator< K, V >.
Referenced by ConstIterator< V >::~ConstIterator().
next()
template<class T> virtual const T& ConstIterator< T >::next () pure virtual
Fetch the next item.
This function first fetches the next item and then updates the current item pointer to that item.
Returns
Reference to the next item.
Implemented in ConstHashIterator< K, V >.
Referenced by ConstIterator< V >::~ConstIterator().
operator++()
template<class T> virtual void ConstIterator< T >::operator++ (int num) pure virtual
Increment operator.
This function first increment the current item and then updates the next item pointer.
Parameters
num Ignored
Implemented in ConstHashIterator< K, V >.
Referenced by ConstIterator< V >::~ConstIterator().
reset()
template<class T> virtual void ConstIterator< T >::reset () pure virtual
Restart iteration from the beginning.
Implemented in ConstHashIterator< K, V >.
Referenced by ConstIterator< V >::~ConstIterator().
The documentation for this class was generated from the following file:
lib/libstd/ConstIterator.h