FreeNOS: ArgumentParser Class Reference
ArgumentParser Class Reference
lib » libstd
Generic command-line argument parser.
#include <ArgumentParser.h>
Public Types
enum Result { Success, InvalidArgument, NotFound, AlreadyExists }
Result codes.
Public Member Functions
ArgumentParser ()
Constructor.
virtual ~ArgumentParser ()
Destructor.
String getUsage () const
Get program usage.
const String & name () const
Retrieve program name.
void setName (const char *name)
Set program name.
void setDescription (const String &desciption)
Set program description.
Result registerFlag (char arg, const char *name, const char *description)
Register a flag Argument.
Result registerPositional (const char *name, const char *description, Size count=1)
Register a positional argument.
Result parse (int argc, char **argv, ArgumentContainer &output)
Parse input arguments.
Private Attributes
HashTable< String, Argument * > m_flags
Contains all registered flag arguments by name.
HashTable< String, Argument * > m_flagsId
Contains all registered flag arguments by single character identifier.
Vector< Argument * > m_positionals
Contains all registered positional arguments.
String m_name
Program name.
String m_description
Program description.
Detailed Description
Generic command-line argument parser.
Definition at line 40 of file ArgumentParser.h.
Member Enumeration Documentation
Result
enum ArgumentParser::Result
Result codes.
Enumerator
Success
InvalidArgument
NotFound
AlreadyExists
Definition at line 47 of file ArgumentParser.h.
Constructor & Destructor Documentation
ArgumentParser()
ArgumentParser::ArgumentParser ()
Constructor.
Definition at line 21 of file ArgumentParser.cpp.
References m_description, and m_name.
~ArgumentParser()
ArgumentParser::~ArgumentParser () virtual
Destructor.
Definition at line 27 of file ArgumentParser.cpp.
References Vector< T >::count(), HashIterator< K, V >::hasCurrent(), m_flags, and m_positionals.
Member Function Documentation
getUsage()
String ArgumentParser::getUsage () const
Get program usage.
Returns
Program usage string reference.
Definition at line 42 of file ArgumentParser.cpp.
References Vector< T >::count(), HashTable< K, V >::count(), ConstHashIterator< K, V >::hasCurrent(), m_description, m_flags, m_name, m_positionals, and usage().
Referenced by Application::usage().
name()
const String & ArgumentParser::name () const
Retrieve program name.
Returns
Program name
Definition at line 85 of file ArgumentParser.cpp.
References m_name.
Referenced by Cat::cat(), BootImageCreate::exec(), BootImageCreate::readBootSymbols(), and setName().
parse()
ArgumentParser::Result ArgumentParser::parse (int argc, char ** argv, ArgumentContainer & output)
Parse input arguments.
This function parses the given arguments and fills the argument container with parsed arguments.
Parameters
argc Input argument count.
argv Input argument values.
output Filled with parsed arguments on output.
Returns
Result code.
Definition at line 136 of file ArgumentParser.cpp.
References ArgumentContainer::addFlag(), ArgumentContainer::addPositional(), Vector< T >::count(), HashTable< K, V >::get(), ArgumentContainer::getPositionals(), InvalidArgument, List< T >::last(), String::length(), m_flags, m_flagsId, m_positionals, NotFound, Argument::setValue(), String::split(), String::substring(), and Success.
Referenced by Application::run().
registerFlag()
ArgumentParser::Result ArgumentParser::registerFlag (char arg, const char * name, const char * description)
Register a flag Argument.
Parameters
arg Argument identifier
name Argument name
description Argument single line description
Returns
Result code.
Definition at line 100 of file ArgumentParser.cpp.
References HashTable< K, V >::insert(), m_flags, m_flagsId, Argument::setDescription(), Argument::setIdentifier(), and Success.
Referenced by Application::Application(), BootImageCreate::BootImageCreate(), Echo::Echo(), Init::Init(), ListFiles::ListFiles(), NetCat::NetCat(), NetPing::NetPing(), NetReceive::NetReceive(), NetSend::NetSend(), SievePrime::SievePrime(), and UnixName::UnixName().
registerPositional()
ArgumentParser::Result ArgumentParser::registerPositional (const char * name, const char * description, Size count = 1)
Register a positional argument.
Parameters
name Argument name
description Argument single line description
count Maximum number to set for this positional argument
Returns
Result code.
Definition at line 119 of file ArgumentParser.cpp.
References AlreadyExists, Vector< T >::at(), Vector< T >::count(), Vector< T >::insert(), m_positionals, Argument::setCount(), Argument::setDescription(), and Success.
Referenced by BootImageCreate::BootImageCreate(), Cat::Cat(), CreateFile::CreateFile(), Echo::Echo(), FileStatus::FileStatus(), ListFiles::ListFiles(), Login::Login(), MakeNode::MakeNode(), NetCat::NetCat(), NetCtl::NetCtl(), NetPing::NetPing(), NetReceive::NetReceive(), NetSend::NetSend(), Remove::Remove(), Shell::Shell(), SievePrime::SievePrime(), and Sleep::Sleep().
setDescription()
void ArgumentParser::setDescription (const String & desciption)
Set program description.
Parameters
desc Program description string.
Definition at line 95 of file ArgumentParser.cpp.
References m_description.
Referenced by BenchMark::BenchMark(), BootImageCreate::BootImageCreate(), Cat::Cat(), CreateFile::CreateFile(), Echo::Echo(), FileStatus::FileStatus(), Hostname::Hostname(), Init::Init(), IPCTest::IPCTest(), ListFiles::ListFiles(), Login::Login(), MakeNode::MakeNode(), Mount::Mount(), NetCat::NetCat(), NetCtl::NetCtl(), NetPing::NetPing(), NetReceive::NetReceive(), NetSend::NetSend(), ProcessList::ProcessList(), Remove::Remove(), Shell::Shell(), SievePrime::SievePrime(), Sleep::Sleep(), SysInfo::SysInfo(), and UnixName::UnixName().
setName()
void ArgumentParser::setName (const char * name)
Set program name.
Parameters
name Program name string.
Definition at line 90 of file ArgumentParser.cpp.
References m_name, and name().
Referenced by Application::run().
Field Documentation
m_description
String ArgumentParser::m_description private
Program description.
Definition at line 152 of file ArgumentParser.h.
Referenced by ArgumentParser(), getUsage(), and setDescription().
m_flags
HashTable<String, Argument *> ArgumentParser::m_flags private
Contains all registered flag arguments by name.
Definition at line 140 of file ArgumentParser.h.
Referenced by getUsage(), parse(), registerFlag(), and ~ArgumentParser().
m_flagsId
HashTable<String, Argument *> ArgumentParser::m_flagsId private
Contains all registered flag arguments by single character identifier.
Definition at line 143 of file ArgumentParser.h.
Referenced by parse(), and registerFlag().
m_name
String ArgumentParser::m_name private
Program name.
Definition at line 149 of file ArgumentParser.h.
Referenced by ArgumentParser(), getUsage(), name(), and setName().
m_positionals
Vector<Argument *> ArgumentParser::m_positionals private
Contains all registered positional arguments.
Definition at line 146 of file ArgumentParser.h.
Referenced by getUsage(), parse(), registerPositional(), and ~ArgumentParser().
The documentation for this class was generated from the following files:
lib/libstd/ArgumentParser.h
lib/libstd/ArgumentParser.cpp