FreeNOS: BroadcomTimer Class Reference
BroadcomTimer Class Reference
lib » libarch » Broadcom
Broadcom System-on-Chip system timer.
#include <BroadcomTimer.h>
Public Member Functions
virtual Result setFrequency (Size hertz)
Set timer frequency.
virtual Result tick ()
Process timer tick.
Public Member Functions inherited from Timer
struct Timer::Info ALIGN (8) Info
Timer information structure.
Timer ()
Constructor.
Size getInterrupt () const
Get timer interrupt number.
Size getFrequency () const
Get timer frequency.
virtual Result getCurrent (Info *info)
Get current timer info.
virtual Result initialize ()
Initialize the timer.
virtual Result start ()
Start the timer.
virtual Result stop ()
Stop the timer.
virtual Result wait (u32 microseconds) const
Busy wait a number of microseconds.
bool isExpired (const Info &info) const
Check if a timer value is expired.
Private Attributes
u32 m_cycles
Number of internal cycles needed to provide the current timer frequency.
ARMIO m_io
I/O instance.
Additional Inherited Members
Public Types inherited from Timer
enum Result { Success, NotFound, IOError, InvalidFrequency }
Result codes.
Data Fields inherited from Timer
enum Timer::Result ALIGN
Protected Attributes inherited from Timer
Info m_info
The current Timer information.
Size m_frequency
Frequency of the Timer.
Size m_int
Timer interrupt number.
Detailed Description
Broadcom System-on-Chip system timer.
Definition at line 60 of file BroadcomTimer.h.
Member Function Documentation
setFrequency()
BroadcomTimer::Result BroadcomTimer::setFrequency (Size hertz) virtual
Set timer frequency.
Parameters
hertz Frequency of the timer in hertz.
Returns
Result code.
Reimplemented from Timer.
Definition at line 20 of file BroadcomTimer.cpp.
References BCM_SYSTIMER_FREQ, M1, m_cycles, Timer::m_frequency, m_io, ARMIO::read(), Timer::Success, SYSTIMER_C1, SYSTIMER_CLO, SYSTIMER_CS, and ARMIO::write().
Referenced by ARMKernel::ARMKernel().
tick()
BroadcomTimer::Result BroadcomTimer::tick () virtual
Process timer tick.
Should be called on each Timer interrupt to keep the m_info variable synchronized with the actual hardware. Also clears the timer interrupt flag.
Returns
Result code.
Reimplemented from Timer.
Definition at line 33 of file BroadcomTimer.cpp.
References M1, m_cycles, Timer::m_info, m_io, ARMIO::read(), Timer::Success, SYSTIMER_C1, SYSTIMER_CLO, SYSTIMER_CS, Timer::Info::ticks, and ARMIO::write().
Field Documentation
m_cycles
u32 BroadcomTimer::m_cycles private
Number of internal cycles needed to provide the current timer frequency.
Definition at line 87 of file BroadcomTimer.h.
Referenced by setFrequency(), and tick().
m_io
ARMIO BroadcomTimer::m_io private
I/O instance.
Definition at line 90 of file BroadcomTimer.h.
Referenced by setFrequency(), and tick().
The documentation for this class was generated from the following files:
lib/libarch/arm/broadcom/BroadcomTimer.h
lib/libarch/arm/broadcom/BroadcomTimer.cpp