FreeNOS: Channel Class Reference
Channel Class Reference abstract
lib » libipc
Unidirectional point-to-point messaging channel.
#include <Channel.h>
Public Types
enum Result {
Success, InvalidArgument, InvalidMode, InvalidSize,
IOError, ChannelFull, NotFound
}
Result codes.
enum Mode { Producer, Consumer }
Channel modes.
Public Member Functions
Channel ()
Constructor.
virtual ~Channel ()
Destructor.
const Size getMessageSize () const
Get message size.
const Size getMaximumMessages () const
Get maximum message count.
Result setMode (Mode mode)
Set mode.
virtual Result setMessageSize (Size size)
Set message size.
virtual Result read (void *buffer)=0
Read a message.
virtual Result write (void *buffer)=0
Write a message.
virtual Result flush ()=0
Flush message buffers.
Protected Attributes
Mode m_mode
Channel mode.
Size m_messageSize
Message size.
Size m_maximumMessages
Maximum number of message that the Channel can hold.
Detailed Description
Unidirectional point-to-point messaging channel.
Definition at line 32 of file Channel.h.
Member Enumeration Documentation
Mode
enum Channel::Mode
Channel modes.
Enumerator
Producer
Consumer
Definition at line 53 of file Channel.h.
Result
enum Channel::Result
Result codes.
Enumerator
Success
InvalidArgument
InvalidMode
InvalidSize
IOError
ChannelFull
NotFound
Definition at line 39 of file Channel.h.
Constructor & Destructor Documentation
Channel()
Channel::Channel ()
Constructor.
Definition at line 20 of file Channel.cpp.
References Consumer, m_maximumMessages, m_messageSize, and m_mode.
~Channel()
Channel::~Channel () virtual
Destructor.
Definition at line 27 of file Channel.cpp.
Member Function Documentation
flush()
virtual Result Channel::flush () pure virtual
Flush message buffers.
Ensures that all messages are written through caches.
Returns
Result code.
Implemented in MemoryChannel.
getMaximumMessages()
const Size Channel::getMaximumMessages () const
Get maximum message count.
Returns
Maximum message count.
Definition at line 36 of file Channel.cpp.
References m_maximumMessages.
getMessageSize()
const Size Channel::getMessageSize () const
Get message size.
Returns
Message size
Definition at line 31 of file Channel.cpp.
References m_messageSize.
Referenced by ChannelClient::sendRequest().
read()
virtual Result Channel::read (void * buffer) pure virtual
Read a message.
Parameters
buffer Output buffer for the message.
Returns
Result code.
Implemented in MemoryChannel.
Referenced by ChannelServer< FileSystem, FileSystemMessage >::readChannels(), and ChannelClient::syncReceiveFrom().
setMessageSize()
Channel::Result Channel::setMessageSize (Size size) virtual
Set message size.
Parameters
size New message size.
Returns
Result code.
Reimplemented in MemoryChannel.
Definition at line 47 of file Channel.cpp.
References m_messageSize, and Success.
setMode()
Channel::Result Channel::setMode (Channel::Mode mode)
Set mode.
Parameters
mode Channel mode.
Returns
Result code.
Definition at line 41 of file Channel.cpp.
References m_mode, and Success.
Referenced by ChannelServer< FileSystem, FileSystemMessage >::accept(), ChannelClient::connect(), Process::initialize(), MPI_Init(), and CoreServer::setupChannels().
write()
virtual Result Channel::write (void * buffer) pure virtual
Write a message.
Parameters
buffer Input buffer for the message.
Returns
Result code.
Implemented in MemoryChannel.
Referenced by FileSystem::processRequest(), ChannelServer< FileSystem, FileSystemMessage >::readChannels(), ChannelClient::sendRequest(), FileSystem::sendResponse(), and ChannelClient::syncSendTo().
Field Documentation
m_maximumMessages
Size Channel::m_maximumMessages protected
Maximum number of message that the Channel can hold.
Definition at line 139 of file Channel.h.
Referenced by Channel(), getMaximumMessages(), MemoryChannel::read(), MemoryChannel::setMessageSize(), and MemoryChannel::write().
m_messageSize
Size Channel::m_messageSize protected
Message size.
Definition at line 136 of file Channel.h.
Referenced by Channel(), getMessageSize(), MemoryChannel::read(), setMessageSize(), MemoryChannel::setMessageSize(), and MemoryChannel::write().
m_mode
Mode Channel::m_mode protected
Channel mode.
Definition at line 133 of file Channel.h.
Referenced by Channel(), and setMode().
The documentation for this class was generated from the following files:
lib/libipc/Channel.h
lib/libipc/Channel.cpp