FreeNOS: ChannelRegistry Class Reference
ChannelRegistry Class Reference
lib » libipc
Registration for Channels.
#include <ChannelRegistry.h>
Public Types
enum Result {
Success, InvalidArgument, InvalidSize, IOError,
NotFound
}
Result codes.
Public Member Functions
ChannelRegistry ()
Constructor.
virtual ~ChannelRegistry ()
Destructor.
Channel * getConsumer (ProcessID pid)
Get one consumer.
Channel * getProducer (ProcessID pid)
Get one producer.
HashTable< ProcessID, Channel * > & getConsumers ()
Get all consumers.
HashTable< ProcessID, Channel * > & getProducers ()
Get all producers.
Result registerConsumer (ProcessID pid, Channel *channel)
Register consumer channel.
Result registerProducer (ProcessID pid, Channel *channel)
Register producer channel.
Result unregisterConsumer (ProcessID pid)
Unregister consumer channel.
Result unregisterProducer (ProcessID pid)
Unregister producer channel.
Private Attributes
HashTable< ProcessID, Channel * > m_consumer
Contains registered consumer channels.
HashTable< ProcessID, Channel * > m_producer
Contains registered producer channels.
Detailed Description
Registration for Channels.
Definition at line 37 of file ChannelRegistry.h.
Member Enumeration Documentation
Result
enum ChannelRegistry::Result
Result codes.
Enumerator
Success
InvalidArgument
InvalidSize
IOError
NotFound
Definition at line 44 of file ChannelRegistry.h.
Constructor & Destructor Documentation
ChannelRegistry()
ChannelRegistry::ChannelRegistry ()
Constructor.
Definition at line 21 of file ChannelRegistry.cpp.
~ChannelRegistry()
ChannelRegistry::~ChannelRegistry () virtual
Destructor.
Definition at line 25 of file ChannelRegistry.cpp.
Member Function Documentation
getConsumer()
Channel * ChannelRegistry::getConsumer (ProcessID pid)
Get one consumer.
Parameters
pid ProcessID of the channel to get
Returns
Channel pointer if found or ZERO
Definition at line 29 of file ChannelRegistry.cpp.
References HashTable< K, V >::get(), m_consumer, and ZERO.
Referenced by ChannelClient::findConsumer(), and unregisterConsumer().
getConsumers()
HashTable< ProcessID, Channel * > & ChannelRegistry::getConsumers ()
Get all consumers.
Returns
HashTable with consumer channels
Definition at line 47 of file ChannelRegistry.cpp.
References m_consumer.
Referenced by ChannelClient::receiveAny().
getProducer()
Channel * ChannelRegistry::getProducer (ProcessID pid)
Get one producer.
Parameters
pid ProcessID of the channel to get
Returns
Channel pointer if found or ZERO
Definition at line 38 of file ChannelRegistry.cpp.
References HashTable< K, V >::get(), m_producer, and ZERO.
Referenced by ChannelClient::findProducer(), FileSystem::processRequest(), FileSystem::sendResponse(), and unregisterProducer().
getProducers()
HashTable< ProcessID, Channel * > & ChannelRegistry::getProducers ()
Get all producers.
Returns
HashTable with all producer channels
Definition at line 52 of file ChannelRegistry.cpp.
References m_producer.
registerConsumer()
ChannelRegistry::Result ChannelRegistry::registerConsumer (ProcessID pid, Channel * channel)
Register consumer channel.
Parameters
pid ProcessID of the attached process
channel Channel object
Returns
Result code
Definition at line 57 of file ChannelRegistry.cpp.
References HashTable< K, V >::insert(), m_consumer, and Success.
Referenced by ChannelClient::connect().
registerProducer()
ChannelRegistry::Result ChannelRegistry::registerProducer (ProcessID pid, Channel * channel)
Register producer channel.
Parameters
pid ProcessID of the attached process
channel Channel object
Returns
Result code
Definition at line 65 of file ChannelRegistry.cpp.
References HashTable< K, V >::insert(), m_producer, and Success.
Referenced by ChannelClient::connect().
unregisterConsumer()
ChannelRegistry::Result ChannelRegistry::unregisterConsumer (ProcessID pid)
Unregister consumer channel.
Parameters
pid ProcessID of the attached process
Returns
Result code
Definition at line 73 of file ChannelRegistry.cpp.
References getConsumer(), m_consumer, NotFound, HashTable< K, V >::remove(), and Success.
unregisterProducer()
ChannelRegistry::Result ChannelRegistry::unregisterProducer (ProcessID pid)
Unregister producer channel.
Parameters
pid ProcessID of the attached process
Returns
Result code
Definition at line 85 of file ChannelRegistry.cpp.
References getProducer(), m_producer, NotFound, HashTable< K, V >::remove(), and Success.
Field Documentation
m_consumer
HashTable<ProcessID, Channel *> ChannelRegistry::m_consumer private
Contains registered consumer channels.
Definition at line 138 of file ChannelRegistry.h.
Referenced by getConsumer(), getConsumers(), registerConsumer(), and unregisterConsumer().
m_producer
HashTable<ProcessID, Channel *> ChannelRegistry::m_producer private
Contains registered producer channels.
Definition at line 141 of file ChannelRegistry.h.
Referenced by getProducer(), getProducers(), registerProducer(), and unregisterProducer().
The documentation for this class was generated from the following files:
lib/libipc/ChannelRegistry.h
lib/libipc/ChannelRegistry.cpp