FreeNOS: API Class Reference
API Class Reference
kernel
Generic Kernel API implementation.
#include <API.h>
Public Types
enum Number {
PrivExecNumber = 1, ProcessCtlNumber, SystemInfoNumber, VMCopyNumber,
VMCtlNumber, VMShareNumber, IOCtlNumber
}
Enumeration of supported generic kernel API functions.
enum ErrorCode {
Success = 0, AccessViolation = -1, RangeError = -2, NotFound = -3,
InvalidArgument = -4, OutOfMemory = -5, IOError = -6, AlreadyExists = -7
}
Enumeration of generic kernel API error codes.
enum Operation {
Create = 0, Delete = 1, Send = 2, Receive = 3,
SendReceive = 4, Read = 5, Write = 6, ReadPhys = 7
}
Various actions which may be performed inside an APIHandler.
typedef enum API::Number Number
Enumeration of supported generic kernel API functions.
typedef enum API::ErrorCode Error
Enumeration of generic kernel API error codes.
typedef ::Error Result
Represents the result of an system call handler.
typedef Result Handler(ulong, ulong, ulong, ulong, ulong)
Function which handles an kernel API (system call) request.
typedef enum API::Operation Operation
Various actions which may be performed inside an APIHandler.
Public Member Functions
API ()
Constructor.
Result invoke (Number number, ulong arg1, ulong arg2, ulong arg3, ulong arg4, ulong arg5)
Execute a generic API function.
Private Attributes
Vector< Handler * > m_apis
API handlers.
Detailed Description
Generic Kernel API implementation.
Definition at line 37 of file API.h.
Member Typedef Documentation
Error
typedef enum API::ErrorCode API::Error
Enumeration of generic kernel API error codes.
Handler
typedef Result API::Handler(ulong, ulong, ulong, ulong, ulong)
Function which handles an kernel API (system call) request.
Returns
Status code of the APIHandler execution.
Definition at line 82 of file API.h.
Number
typedef enum API::Number API::Number
Enumeration of supported generic kernel API functions.
Architectures or System implementations can optionally introduce additional specific APIs.
Operation
typedef enum API::Operation API::Operation
Various actions which may be performed inside an APIHandler.
Result
typedef ::Error API::Result
Represents the result of an system call handler.
Definition at line 76 of file API.h.
Member Enumeration Documentation
ErrorCode
enum API::ErrorCode
Enumeration of generic kernel API error codes.
Enumerator
Success
AccessViolation
RangeError
NotFound
InvalidArgument
OutOfMemory
IOError
AlreadyExists
Definition at line 62 of file API.h.
Number
enum API::Number
Enumeration of supported generic kernel API functions.
Architectures or System implementations can optionally introduce additional specific APIs.
Enumerator
PrivExecNumber
ProcessCtlNumber
SystemInfoNumber
VMCopyNumber
VMCtlNumber
VMShareNumber
IOCtlNumber
Definition at line 47 of file API.h.
Operation
enum API::Operation
Various actions which may be performed inside an APIHandler.
Enumerator
Create
Delete
Send
Receive
SendReceive
Read
Write
ReadPhys
Definition at line 87 of file API.h.
Constructor & Destructor Documentation
API()
API::API ()
Constructor.
Definition at line 21 of file API.cpp.
References DEBUG, Sequence< T >::fill(), Vector< T >::insert(), IOCtlHandler(), IOCtlNumber, m_apis, PrivExecHandler(), PrivExecNumber, ProcessCtlHandler(), ProcessCtlNumber, SystemInfoHandler(), SystemInfoNumber, VMCopyHandler(), VMCopyNumber, VMCtlHandler(), VMCtlNumber, VMShareHandler(), VMShareNumber, and ZERO.
Member Function Documentation
invoke()
API::Result API::invoke (Number number, ulong arg1, ulong arg2, ulong arg3, ulong arg4, ulong arg5)
Execute a generic API function.
Definition at line 36 of file API.cpp.
References Vector< T >::get(), InvalidArgument, and m_apis.
Referenced by IntelKernel::trap(), and ARMKernel::trap().
Field Documentation
m_apis
Vector<Handler *> API::m_apis private
API handlers.
Definition at line 120 of file API.h.
Referenced by API(), and invoke().
The documentation for this class was generated from the following files:
kernel/API.h
kernel/API.cpp