FreeNOS: String Class Reference
String Class Reference
lib » libstd
Abstraction of strings.
#include <String.h>
Public Member Functions
String ()
Default constructor.
String (const String &str)
Copy constructor.
String (char *s, bool copy=true)
Constructor.
String (const char *s, bool copy=false)
Constant constructor.
String (int number)
Signed integer constructor.
virtual ~String ()
Destructor.
virtual Size size () const
Calculates the length of the String.
virtual Size count () const
Number of characters in the string.
Size length () const
Same as count().
virtual bool resize (Size size)
Change the size of the String buffer.
virtual bool reserve (Size count)
Make sure at least given number of bytes available.
virtual const char * get (Size position) const
Returns the item at the given position.
virtual const char & at (Size position) const
Returns a reference to the item at the given position.
virtual const char value (Size position) const
Return value at the given position.
virtual bool contains (char character) const
Check if the given character occurs in the String.
bool startsWith (String &prefix) const
Tests if this String starts with the specified prefix.
bool startsWith (const char *prefix) const
Tests if this String starts with the specified prefix.
bool endsWith (String &suffix) const
Tests if this String ends with the specified suffix.
bool endsWith (const char *suffix) const
Tests if this String ends with the specified suffix.
virtual int compareTo (const String &str) const
Compares this String to the given String.
virtual int compareTo (const String &str, bool caseSensitive=true) const
Compare with another String.
virtual int compareTo (const char *str, bool caseSensitive=true, Size count=0) const
Compare with a character string.
virtual bool equals (const String &str) const
Alias for compareTo().
bool match (const char *mask) const
Matches the String against a mask.
String substring (Size index, Size size=0)
Returns a new String that contains a copy of this String.
List< String > split (char delimiter)
Split the String into parts separated by a delimiter.
List< String > split (const String &delimiter)
Split the String into parts separated by a delimiter.
long toLong (Number::Base base=Number::Dec)
Convert the String to a signed long integer.
String & pad (Size length)
Pad line with trailing whitespace.
String & trim ()
Remove leading and trailing whitespace from the String.
String & lower ()
Convert all Characters to lower case.
String & upper ()
Convert all Characters to upper case.
Size set (long number, Number::Base base=Number::Dec, char *string=ZERO)
Set text-representation of a signed number.
Size setUnsigned (ulong number, Number::Base base=Number::Dec, char *string=ZERO, bool sign=false)
Set text-representation of an unsigned number.
void operator= (const char *str)
Assignment operator.
void operator= (const String &str)
Assignment operator.
bool operator== (const String &str) const
Comparision operator.
bool operator!= (const String &str) const
Inequal operator.
const char * operator* () const
Dereference operator (read-only).
char * operator* ()
Dereference operator.
String & operator<< (const char *str)
Append character string to the String.
String & operator<< (const String &str)
Append String to another String.
String & operator<< (int number)
Append the given signed number as text to the String.
String & operator<< (unsigned int number)
Append the given unsigned number as text to the String.
String & operator<< (void *pointer)
Append the pointer as hexidecimal unsigned number to the String.
String & operator<< (Number::Base format)
Change the default number format representation.
Public Member Functions inherited from Sequence< char >
virtual int insert (const char &item)
Adds the given item to the Sequence, if possible.
virtual bool insert (Size position, const char &item)
Inserts the given item at the given position.
virtual void fill (char value)
Fill the Sequence with the given value.
virtual int remove (char value)
Remove all items with the given value.
virtual bool removeAt (Size position)
Removes the item at the given position.
virtual void clear ()
Removes all items from the Sequence.
virtual int compareTo (const Sequence< char > &s) const
Compare this Sequence to another Sequence.
const char & operator[] (int i) const
Returns the item at the given position in the Sequence.
const char & operator[] (Size i) const
Returns the item at the given position in the Sequence.
char & operator[] (int i)
Returns the item at the given position in the Sequence.
char & operator[] (Size i)
Returns the item at the given position in the Sequence.
Public Member Functions inherited from Container
Container ()
Constructor.
virtual ~Container ()
Destructor.
virtual bool isEmpty () const
Check if the Container is empty.
virtual bool shrink (Size size)
Shrink the container size by the given amount of items.
virtual Size squeeze ()
Try to minimize the memory required in the Container.
Public Member Functions inherited from Comparable< Sequence< char > >
virtual ~Comparable ()
Class destructor.
virtual bool equals (const Sequence< char > &t) const
Test if an object is equal to an other object.
Static Public Member Functions
static Size length (char *str)
Get the length of the given character string.
static Size length (const char *str)
Get the length of a constant character string.
Private Attributes
char * m_string
Current value of the String.
Size m_size
Size of the string buffer, including any NULL byte(s) at the end.
Size m_count
Length of the string text, excluding NULL byte(s) at the end.
bool m_allocated
True if the string buffer is a deep copy, false otherwise.
Number::Base m_base
Number format to use for convertions.
Detailed Description
Abstraction of strings.
Definition at line 41 of file String.h.
Constructor & Destructor Documentation
String() [1/5]
String::String ()
Default constructor.
Constructs an empty string with the default size.
Definition at line 22 of file String.cpp.
References Number::Dec, m_allocated, m_base, m_count, m_size, m_string, STRING_DEFAULT_SIZE, and ZERO.
String() [2/5]
String::String (const String & str)
Copy constructor.
Parameters
s String reference.
Definition at line 32 of file String.cpp.
References MemoryBlock::copy(), m_allocated, m_base, m_count, m_size, and m_string.
String() [3/5]
String::String (char * s, bool copy = true)
Constructor.
Parameters
s Initial value of the String.
copy If true allocate and copy the input buffer.
Definition at line 42 of file String.cpp.
References MemoryBlock::copy(), copy(), Number::Dec, length(), m_allocated, m_base, m_count, m_size, m_string, and STRING_DEFAULT_SIZE.
String() [4/5]
String::String (const char * s, bool copy = false)
Constant constructor.
Parameters
s Initial value of the String.
copy If true allocate and copy the input buffer.
Definition at line 58 of file String.cpp.
References MemoryBlock::copy(), copy(), Number::Dec, length(), m_allocated, m_base, m_count, m_size, m_string, and STRING_DEFAULT_SIZE.
String() [5/5]
String::String (int number)
Signed integer constructor.
Creates a String with the textual representation of the given signed integer.
Parameters
number Integer number of the new String.
Definition at line 74 of file String.cpp.
References Number::Dec, m_allocated, m_base, m_count, m_size, m_string, STRING_DEFAULT_SIZE, and ZERO.
~String()
String::~String () virtual
Destructor.
Definition at line 86 of file String.cpp.
References m_allocated, and m_string.
Member Function Documentation
at()
const char & String::at (Size position) const virtual
Returns a reference to the item at the given position.
Parameters
position Valid index inside this array.
Returns
Reference to the item at the given position
Note
Position must be a valid index.
Implements Sequence< char >.
Definition at line 170 of file String.cpp.
References m_string.
compareTo() [1/3]
int String::compareTo (const String & str) const virtual
Compares this String to the given String.
Parameters
s The String to compare us to.
Returns
int < 0, 0, > 0 if we are greater than, equal to or less then the given String.
Definition at line 231 of file String.cpp.
Referenced by compareTo(), equals(), operator!=(), operator==(), and split().
compareTo() [2/3]
int String::compareTo (const String & str, bool caseSensitive = true) const virtual
Compare with another String.
Parameters
s String instance to compare against.
caseSensitive True if uppercase characters are considered not equal to lowercase, false otherwise.
Returns
Zero if equal, negative if smaller or positive if greater.
Definition at line 236 of file String.cpp.
References compareTo(), and m_string.
compareTo() [3/3]
int String::compareTo (const char * str, bool caseSensitive = true, Size count = 0) const virtual
Compare with a character string.
Parameters
str Character string to compare against.
caseSensitive True if uppercase characters are considered not equal to lowercase, false otherwise.
count Number of character to compare or ZERO for whole strings.
Returns
Zero if equal, negative if smaller or positive if greater.
Definition at line 241 of file String.cpp.
References count(), Character::lower(), and m_string.
contains()
bool String::contains (char character) const virtual
Check if the given character occurs in the String.
Parameters
character The character to search for.
Returns
True if found, false otherwise.
Reimplemented from Sequence< char >.
Definition at line 180 of file String.cpp.
References m_count, and m_string.
count()
Size String::count () const virtual
Number of characters in the string.
Returns
Number of characters
Implements Container.
Definition at line 100 of file String.cpp.
References m_count.
Referenced by compareTo(), and length().
endsWith() [1/2]
bool String::endsWith (String & suffix) const
Tests if this String ends with the specified suffix.
Parameters
suffix The suffix String.
Returns
True if matched, false otherwise.
Definition at line 210 of file String.cpp.
References m_string.
Referenced by Log::append(), and DirectoryScanner::scan().
endsWith() [2/2]
bool String::endsWith (const char * suffix) const
Tests if this String ends with the specified suffix.
Parameters
suffix The suffix String.
Returns
True if matched, false otherwise.
Definition at line 215 of file String.cpp.
References length(), m_count, and m_string.
equals()
bool String::equals (const String & str) const virtual
Alias for compareTo().
Definition at line 260 of file String.cpp.
References compareTo(), and m_string.
Referenced by ArgumentContainer::get().
get()
const char * String::get (Size position) const virtual
Returns the item at the given position.
Parameters
position The position of the item to get.
Returns
Pointer to the item at the given position or ZERO if no item available.
Implements Sequence< char >.
Definition at line 165 of file String.cpp.
References m_count, m_string, and ZERO.
length() [1/3]
Size String::length () const
Same as count().
See also
count
Definition at line 105 of file String.cpp.
References count().
Referenced by endsWith(), ProcessList::exec(), SievePrime::exec(), WriteCommand::execute(), hash(), length(), main(), operator<<(), operator=(), ArgumentParser::parse(), ListFiles::printFiles(), EthernetAddress::read(), IPV4Address::read(), UDPFactory::read(), ICMPFactory::read(), startsWith(), and String().
length() [2/3]
Size String::length (char * str) static
Get the length of the given character string.
Parameters
str Input string
Returns
String length in bytes
Definition at line 110 of file String.cpp.
References length().
length() [3/3]
Size String::length (const char * str) static
Get the length of a constant character string.
Parameters
str Input string
Returns
String length
Definition at line 115 of file String.cpp.
lower()
String & String::lower ()
Convert all Characters to lower case.
Returns
Reference to the String.
Definition at line 384 of file String.cpp.
References Character::lower(), m_count, m_string, and reserve().
match()
bool String::match (const char * mask) const
Matches the String against a mask.
Parameters
mask Pattern to match against.
Returns
True if match, false otherwise.
Definition at line 265 of file String.cpp.
References Character::isWildcard(), m_string, and ZERO.
Referenced by LinnCreate::insertDirectory().
operator!=()
bool String::operator!= (const String & str) const
Inequal operator.
Parameters
str Input string
Definition at line 637 of file String.cpp.
References compareTo().
operator*() [1/2]
const char * String::operator* () const
Dereference operator (read-only).
Definition at line 642 of file String.cpp.
References m_string.
operator*() [2/2]
char * String::operator* ()
Dereference operator.
Definition at line 647 of file String.cpp.
References m_string.
operator<<() [1/6]
String & String::operator<< (const char * str)
Append character string to the String.
Definition at line 652 of file String.cpp.
References MemoryBlock::copy(), length(), m_count, m_string, reserve(), and ZERO.
Referenced by operator<<().
operator<<() [2/6]
String & String::operator<< (const String & str)
Append String to another String.
Definition at line 665 of file String.cpp.
References m_string, and operator<<().
operator<<() [3/6]
String & String::operator<< (int number)
Append the given signed number as text to the String.
Definition at line 671 of file String.cpp.
References m_base, m_count, m_string, and reserve().
operator<<() [4/6]
String & String::operator<< (unsigned int number)
Append the given unsigned number as text to the String.
Definition at line 679 of file String.cpp.
References m_base, m_count, m_string, reserve(), and setUnsigned().
operator<<() [5/6]
String & String::operator<< (void * pointer)
Append the pointer as hexidecimal unsigned number to the String.
Definition at line 687 of file String.cpp.
References Number::Hex, m_count, m_string, reserve(), and setUnsigned().
operator<<() [6/6]
String & String::operator<< (Number::Base format)
Change the default number format representation.
Definition at line 695 of file String.cpp.
References m_base.
operator=() [1/2]
void String::operator= (const char * str)
Assignment operator.
Parameters
s Constant string.
Definition at line 608 of file String.cpp.
References MemoryBlock::copy(), length(), m_count, m_string, reserve(), and ZERO.
operator=() [2/2]
void String::operator= (const String & str)
Assignment operator.
Parameters
str Input string
Definition at line 620 of file String.cpp.
References MemoryBlock::copy(), length(), m_count, m_string, reserve(), and ZERO.
operator==()
bool String::operator== (const String & str) const
Comparision operator.
Parameters
str Input string
Definition at line 632 of file String.cpp.
References compareTo().
pad()
String & String::pad (Size length)
Pad line with trailing whitespace.
This function ensures the last line inside the String is at least the given length in characters, by appending extra whitespace at the end of the line.
Parameters
length Length of the String including whitespace pads
Returns
Reference to the String
Definition at line 330 of file String.cpp.
References m_count, m_string, reserve(), MemoryBlock::set(), and ZERO.
Referenced by ListFiles::printSingleFile().
reserve()
bool String::reserve (Size count) virtual
Make sure at least given number of bytes available.
Parameters
count The number of free bytes to guarantee.
Returns
True if success, false otherwise.
Reimplemented from Container.
Definition at line 157 of file String.cpp.
References m_allocated, m_size, and resize().
Referenced by lower(), operator<<(), operator=(), pad(), setUnsigned(), trim(), and upper().
resize()
bool String::resize (Size size) virtual
Change the size of the String buffer.
Parameters
size New size of the String.
Returns
True if resized successfully, false otherwise.
Reimplemented from Container.
Definition at line 125 of file String.cpp.
References MemoryBlock::copy(), m_allocated, m_count, m_size, m_string, size(), and ZERO.
Referenced by reserve().
set()
Size String::set (long number, Number::Base base = Number::Dec, char * string = ZERO)
Set text-representation of a signed number.
Parameters
string Destination character string buffer or ZERO to fill internal String buffer.
Definition at line 534 of file String.cpp.
References setUnsigned().
Referenced by itoa().
setUnsigned()
Size String::setUnsigned (ulong number, Number::Base base = Number::Dec, char * string = ZERO, bool sign = false)
Set text-representation of an unsigned number.
Parameters
number Input number.
base Numberal base type.
string Destination character string buffer or ZERO to fill internal String buffer.
sign Threat input number as signed.
Definition at line 539 of file String.cpp.
References Number::Dec, Number::Hex, m_count, m_string, reserve(), and STRING_DEFAULT_SIZE.
Referenced by operator<<(), set(), and vsnprintf().
size()
Size String::size () const virtual
Calculates the length of the String.
Returns
Length of the current String value.
Implements Container.
Definition at line 95 of file String.cpp.
References m_size.
Referenced by resize(), and substring().
split() [1/2]
List< String > String::split (char delimiter)
Split the String into parts separated by a delimiter.
Parameters
delimiter Character to use a delimiter.
Returns
List of Strings representing the parts.
Definition at line 406 of file String.cpp.
References ZERO.
Referenced by Shell::exec(), FileSystemPath::parse(), ArgumentParser::parse(), and IPV4::toAddress().
split() [2/2]
List< String > String::split (const String & delimiter)
Split the String into parts separated by a delimiter.
Parameters
delimiter String which acts as a delimiter.
Returns
List of Strings representing the parts.
Definition at line 417 of file String.cpp.
References List< T >::append(), compareTo(), copy(), m_count, m_string, and substring().
startsWith() [1/2]
bool String::startsWith (String & prefix) const
Tests if this String starts with the specified prefix.
Parameters
prefix String prefix.
Returns
True if matched, false otherwise.
Definition at line 189 of file String.cpp.
References m_string.
startsWith() [2/2]
bool String::startsWith (const char * prefix) const
Tests if this String starts with the specified prefix.
Parameters
prefix String prefix.
Returns
True if matched, false otherwise.
Definition at line 194 of file String.cpp.
References length(), m_count, and m_string.
substring()
String String::substring (Size index, Size size = 0)
Returns a new String that contains a copy of this String.
This function copies the input starting from index (inclusive), and copies at most size characters.
Parameters
index The begin index to create the substring of.
size The maximum size of the substring.
Returns
String* a pointer to the newly created substring.
Definition at line 312 of file String.cpp.
References m_count, m_string, size(), and ZERO.
Referenced by ArgumentParser::parse(), and split().
toLong()
long String::toLong (Number::Base base = Number::Dec)
Convert the String to a signed long integer.
Parameters
base NumberBase to use. Default is decimal.
Returns
Signed long integer
Definition at line 457 of file String.cpp.
References Number::Dec, Number::Hex, Character::isAlpha(), Character::isDigit(), Character::isUpper(), Character::isWhitespace(), LONG_MAX, LONG_MIN, and m_string.
Referenced by atoi(), MPI_Init(), strtol(), and IPV4::toAddress().
trim()
String & String::trim ()
Remove leading and trailing whitespace from the String.
Returns
Reference to the String.
Definition at line 355 of file String.cpp.
References MemoryBlock::copy(), Character::isWhitespace(), m_count, m_string, and reserve().
Referenced by MountWaitFile::write().
upper()
String & String::upper ()
Convert all Characters to upper case.
Returns
Reference to the String.
Definition at line 395 of file String.cpp.
References m_count, m_string, reserve(), and Character::upper().
value()
const char String::value (Size position) const virtual
Return value at the given position.
If position is not within bounds of this array, this function will return a default constructed T.
Parameters
position Index inside this array.
Returns
T at the given position or default constructed T.
Definition at line 175 of file String.cpp.
References m_string.
Field Documentation
m_allocated
bool String::m_allocated private
True if the string buffer is a deep copy, false otherwise.
Definition at line 451 of file String.h.
Referenced by reserve(), resize(), String(), and ~String().
m_base
Number::Base String::m_base private
Number format to use for convertions.
Definition at line 454 of file String.h.
Referenced by operator<<(), and String().
m_count
Size String::m_count private
Length of the string text, excluding NULL byte(s) at the end.
Definition at line 448 of file String.h.
Referenced by contains(), count(), endsWith(), get(), lower(), operator<<(), operator=(), pad(), resize(), setUnsigned(), split(), startsWith(), String(), substring(), trim(), and upper().
m_size
Size String::m_size private
Size of the string buffer, including any NULL byte(s) at the end.
Definition at line 445 of file String.h.
Referenced by reserve(), resize(), size(), and String().
m_string
char* String::m_string private
Current value of the String.
Definition at line 442 of file String.h.
Referenced by at(), compareTo(), contains(), endsWith(), equals(), get(), lower(), match(), operator*(), operator<<(), operator=(), pad(), resize(), setUnsigned(), split(), startsWith(), String(), substring(), toLong(), trim(), upper(), value(), and ~String().
The documentation for this class was generated from the following files:
lib/libstd/String.h
lib/libstd/String.cpp