FreeNOS: PageAllocator Class Reference
PageAllocator Class Reference
lib » liballoc
Allocates virtual memory using the memory server.
#include <PageAllocator.h>
Public Member Functions
PageAllocator (Address start, Size size)
Class constructor.
Address base () const
Get base address.
virtual Size size () const
Get memory size.
virtual Size available () const
Get memory available.
virtual Result allocate (Size *size, Address *addr, Size align=ZERO)
Allocate memory.
virtual Result release (Address addr)
Release memory.
Public Member Functions inherited from Allocator
Allocator ()
Class constructor.
virtual ~Allocator ()
Class destructor.
void setParent (Allocator *parent)
Set parent allocator.
Result setAlignment (Size size)
Set allocation alignment.
Result setBase (Address addr)
Set allocation base.
Private Attributes
Address m_base
Start of the allocated memory region.
Size m_size
Maximum size to allocate.
Size m_allocated
Total number of bytes allocated.
Additional Inherited Members
Public Types inherited from Allocator
enum Result {
Success = 0, InvalidAddress, InvalidSize, InvalidAlignment,
OutOfMemory
}
Allocation results.
Static Public Member Functions inherited from Allocator
static void setDefault (Allocator *alloc)
Makes the given Allocator the default.
static Allocator * getDefault ()
Retrieve the currently default Allocator.
Protected Member Functions inherited from Allocator
Address aligned (Address addr, Size boundary) const
Align memory address.
Protected Attributes inherited from Allocator
Allocator * m_parent
Our parent Allocator, if any.
Size m_alignment
Allocation memory alignment.
Address m_base
Allocation base address.
Detailed Description
Allocates virtual memory using the memory server.
Definition at line 36 of file PageAllocator.h.
Constructor & Destructor Documentation
PageAllocator()
PageAllocator::PageAllocator (Address start, Size size)
Class constructor.
Parameters
base Starting address to allocate.
size Maximum size in bytes.
Definition at line 24 of file PageAllocator.cpp.
Member Function Documentation
allocate()
Allocator::Result PageAllocator::allocate (Size * size, Address * addr, Size align = ZERO) virtual
Allocate memory.
Parameters
size Amount of memory in bytes to allocate on input. On output, the amount of memory in bytes actually allocated.
addr Output parameter which contains the address allocated on success.
align Alignment of the required memory or use ZERO for default.
Returns
New memory block on success and ZERO on failure.
Implements Allocator.
Definition at line 47 of file PageAllocator.cpp.
References Memory::Range::access, Allocator::aligned(), m_allocated, m_base, Map, PAGEALLOC_MINIMUM, PAGESIZE, Memory::Range::phys, Memory::Readable, SELF, MemoryBlock::set(), Memory::Range::size, size(), Allocator::Success, Memory::User, Memory::Range::virt, VMCtl(), Memory::Writable, and ZERO.
available()
Size PageAllocator::available () const virtual
Get memory available.
Returns
Size of memory available by the Allocator.
Implements Allocator.
Definition at line 42 of file PageAllocator.cpp.
References m_allocated, and m_size.
base()
Address PageAllocator::base () const
Get base address.
Returns the first address of the allocated memory region.
Returns
Start address.
Definition at line 32 of file PageAllocator.cpp.
References m_base.
release()
Allocator::Result PageAllocator::release (Address addr) virtual
Release memory.
Parameters
addr Points to memory previously returned by allocate().
Returns
Result value.
See also
allocate
Implements Allocator.
Definition at line 78 of file PageAllocator.cpp.
References Allocator::InvalidAddress.
size()
Size PageAllocator::size () const virtual
Get memory size.
Returns
Size of memory owned by the Allocator.
Implements Allocator.
Definition at line 37 of file PageAllocator.cpp.
References m_size.
Referenced by allocate().
Field Documentation
m_allocated
Size PageAllocator::m_allocated private
Total number of bytes allocated.
Definition at line 102 of file PageAllocator.h.
Referenced by allocate(), and available().
m_base
Address PageAllocator::m_base private
Start of the allocated memory region.
Definition at line 96 of file PageAllocator.h.
Referenced by allocate(), and base().
m_size
Size PageAllocator::m_size private
Maximum size to allocate.
Definition at line 99 of file PageAllocator.h.
Referenced by available(), and size().
The documentation for this class was generated from the following files:
lib/liballoc/PageAllocator.h
lib/liballoc/PageAllocator.cpp