FreeNOS: ARMInterrupt Class Reference
ARMInterrupt Class Reference abstract
lib » libarch » ARM
ARM interrupt controller.
#include <ARMInterrupt.h>
Public Types
enum Interrupt {
Reset = 0, UndefinedInstruction, SoftwareInterrupt, PrefetchAbort,
DataAbort, Reserved, IRQ, FIQ
}
ARM interrupt types.
Public Types inherited from IntController
enum Result {
Success, InvalidIRQ, InvalidFrequency, IOError,
NotFound
}
Result codes.
typedef void Handler(struct CPUState state)
Function which is called when the CPU is interrupted.
Public Member Functions
ARMInterrupt (Address base=0x0)
Constructor.
Result install (Interrupt vector, Handler handler)
Install an interrupt handler.
virtual bool isTriggered (uint irq)=0
Check if an IRQ vector is set.
Public Member Functions inherited from IntController
IntController ()
Constructor.
uint getBase () const
Get interrupt number base offset.
virtual Result enable (uint irq)=0
Enable hardware interrupt (IRQ).
virtual Result disable (uint irq)=0
Disable hardware interrupt (IRQ).
virtual Result clear (uint irq)=0
Clear hardware interrupt (IRQ).
Private Attributes
Address m_vecTable
ARM interrupt jump table.
Additional Inherited Members
Protected Attributes inherited from IntController
uint m_base
Interrupt number base offset.
Detailed Description
ARM interrupt controller.
This class provides generic functionity for installing and servicing interrupts on ARM. Each ARM system should provide a ARM interrupt controller implementation which inherits from this class.
See also
http://www.state-machine.com/arm/Building_bare-metal_ARM_with_GNU.pdf
Definition at line 48 of file ARMInterrupt.h.
Member Enumeration Documentation
Interrupt
enum ARMInterrupt::Interrupt
ARM interrupt types.
Enumerator
Reset
UndefinedInstruction
SoftwareInterrupt
PrefetchAbort
DataAbort
Reserved
IRQ
FIQ
Definition at line 55 of file ARMInterrupt.h.
Constructor & Destructor Documentation
ARMInterrupt()
ARMInterrupt::ARMInterrupt (Address base = 0x0)
Constructor.
Parameters
base Base address of the interrupt jump table. By default this is physical address 0x0 in RAM.
Definition at line 23 of file ARMInterrupt.cpp.
References ARM_INTR_VECTAB_SIZE, MemoryBlock::copy(), m_vecTable, and vecTable.
Member Function Documentation
install()
ARMInterrupt::Result ARMInterrupt::install (ARMInterrupt::Interrupt vector, ARMInterrupt::Handler handler)
Install an interrupt handler.
Parameters
vector Interrupt vector to install
handler Interrupt handler function to install.
Returns
Result code
Definition at line 29 of file ARMInterrupt.cpp.
References handlerTable, and IntController::Success.
Referenced by ARMKernel::ARMKernel().
isTriggered()
virtual bool ARMInterrupt::isTriggered (uint irq) pure virtual
Check if an IRQ vector is set.
Parameters
irq Interrupt number
Returns
True if triggered. False otherwise
Implemented in BroadcomInterrupt.
Referenced by ARMKernel::interrupt().
Field Documentation
m_vecTable
Address ARMInterrupt::m_vecTable private
ARM interrupt jump table.
The ARM processor will start executing at the appropriate vector offset in the jump table and perform a jump to the interrupt handler address, which it retrieves from the interrupt handlers table.
See also
m_handlerTable;
ARMInterruptTable.S
Definition at line 109 of file ARMInterrupt.h.
Referenced by ARMInterrupt().
The documentation for this class was generated from the following files:
lib/libarch/arm/ARMInterrupt.h
lib/libarch/arm/ARMInterrupt.cpp