FreeNOS: BenchMark Class Reference
BenchMark Class Reference
bin
Perform system benchmarking tests.
#include <BenchMark.h>
Public Member Functions
BenchMark (int argc, char **argv)
Constructor.
virtual ~BenchMark ()
Destructor.
virtual Result exec ()
Execute the application.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
Perform system benchmarking tests.
Definition at line 31 of file BenchMark.h.
Constructor & Destructor Documentation
BenchMark()
BenchMark::BenchMark (int argc, char ** argv)
Constructor.
Parameters
argc Argument count
argv Argument values
Definition at line 26 of file BenchMark.cpp.
References Application::parser(), and ArgumentParser::setDescription().
~BenchMark()
BenchMark::~BenchMark () virtual
Destructor.
Definition at line 32 of file BenchMark.cpp.
Member Function Documentation
exec()
BenchMark::Result BenchMark::exec () virtual
Execute the application.
Returns
Result code
Implements Application.
Definition at line 36 of file BenchMark.cpp.
References GetPID, InfoPID, LookupVirtual, PAGESIZE, printf(), ProcessCtl(), Schedule, SELF, Memory::Range::size, stat(), Application::Success, timestamp(), Memory::Range::virt, and VMCtl().
The documentation for this class was generated from the following files:
bin/bench/BenchMark.h
bin/bench/BenchMark.cpp