FreeNOS: UDPSocket Class Reference
UDPSocket Class Reference
lib » libnet
User Datagram Protocol (UDP) socket.
#include <UDPSocket.h>
Public Member Functions
UDPSocket (UDP *udp)
Constructor.
virtual ~UDPSocket ()
Destructor.
const u16 getPort () const
Get associated local port.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Receive UDP data.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Send UDP data.
virtual Error process (NetworkQueue::Packet *pkt)
Process incoming network packet.
virtual void error (Error err)
Set error status.
bool operator== (const UDPSocket &sock) const
bool operator!= (const UDPSocket &sock) const
Public Member Functions inherited from NetworkSocket
NetworkSocket (Size packetSize)
Constructor.
virtual ~NetworkSocket ()
Destructor.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Attributes
UDP * m_udp
UDP protocol instance.
u16 m_port
Local port.
NetworkQueue m_queue
Incoming packet queue.
Additional Inherited Members
Protected Attributes inherited from NetworkSocket
ProcessID m_pid
Process which owns the socket.
NetworkQueue m_receive
Receive queue.
NetworkQueue m_transmit
Transmit queue.
NetworkClient::SocketInfo m_info
Socket connection.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
User Datagram Protocol (UDP) socket.
UDP sockets accept payloads to send when writing and read payloads when receiving payloads.
Definition at line 41 of file UDPSocket.h.
Constructor & Destructor Documentation
UDPSocket()
UDPSocket::UDPSocket (UDP * udp)
Constructor.
Definition at line 23 of file UDPSocket.cpp.
References m_port, and m_udp.
~UDPSocket()
UDPSocket::~UDPSocket () virtual
Destructor.
Definition at line 31 of file UDPSocket.cpp.
Member Function Documentation
error()
void UDPSocket::error (Error err) virtual
Set error status.
Parameters
err Error code
Definition at line 107 of file UDPSocket.cpp.
References DEBUG.
getPort()
const u16 UDPSocket::getPort () const
Get associated local port.
Returns
Local port
Definition at line 35 of file UDPSocket.cpp.
References m_port.
operator!=()
bool UDPSocket::operator!= (const UDPSocket & sock) const inline
Definition at line 102 of file UDPSocket.h.
operator==()
bool UDPSocket::operator== (const UDPSocket & sock) const inline
Definition at line 98 of file UDPSocket.h.
process()
Error UDPSocket::process (NetworkQueue::Packet * pkt) virtual
Process incoming network packet.
Returns
Error code
Implements NetworkSocket.
Definition at line 91 of file UDPSocket.cpp.
References MemoryBlock::copy(), NetworkQueue::Packet::data, DEBUG, EIO, ERROR, ESUCCESS, NetworkQueue::get(), m_queue, NetworkQueue::push(), and NetworkQueue::Packet::size.
read()
Error UDPSocket::read (IOBuffer & buffer, Size size, Size offset) virtual
Receive UDP data.
Parameters
buffer Input/Output buffer to output bytes to.
size Number of bytes to read, at maximum.
offset Offset inside the file to start reading.
Returns
Number of bytes read on success, Error on failure.
Reimplemented from File.
Definition at line 40 of file UDPSocket.cpp.
References NetworkClient::SocketInfo::address, NetworkQueue::Packet::data, DEBUG, EAGAIN, m_queue, NetworkQueue::pop(), NetworkClient::SocketInfo::port, NetworkQueue::release(), NetworkQueue::Packet::size, IPV4::Header::source, UDP::Header::sourcePort, and IOBuffer::write().
write()
Error UDPSocket::write (IOBuffer & buffer, Size size, Size offset) virtual
Send UDP data.
Parameters
buffer Input/Output buffer to input bytes from.
size Number of bytes to write, at maximum.
offset Offset inside the file to start writing.
Returns
Number of bytes written on success, Error on failure.
Reimplemented from File.
Definition at line 67 of file UDPSocket.cpp.
References NetworkClient::SocketInfo::address, UDP::bind(), DEBUG, ESUCCESS, NetworkSocket::m_info, m_udp, NetworkClient::SocketInfo::port, random(), IOBuffer::read(), and UDP::sendPacket().
Field Documentation
m_port
u16 UDPSocket::m_port private
Local port.
Definition at line 113 of file UDPSocket.h.
Referenced by getPort(), and UDPSocket().
m_queue
NetworkQueue UDPSocket::m_queue private
Incoming packet queue.
Definition at line 116 of file UDPSocket.h.
Referenced by process(), and read().
m_udp
UDP* UDPSocket::m_udp private
UDP protocol instance.
Definition at line 110 of file UDPSocket.h.
Referenced by UDPSocket(), and write().
The documentation for this class was generated from the following files:
lib/libnet/UDPSocket.h
lib/libnet/UDPSocket.cpp