FreeNOS: ARMControl Class Reference
ARMControl Class Reference
lib » libarch » ARM
ARM System Control Coprocessor (CP15).
#include <ARMControl.h>
Public Types
enum Register {
MainID = 0, CoreID, SystemControl, AuxControl,
DomainControl, TranslationTable0, TranslationTable1, TranslationTableCtrl,
CacheClear, DataCacheClean, FlushPrefetchBuffer, InstructionCacheClear,
InstructionTLBClear, DataTLBClear, UnifiedTLBClear, UserProcID,
InstructionFaultAddress, InstructionFaultStatus, DataFaultAddress, DataFaultStatus,
SystemFrequency
}
System Control Registers.
enum SystemControlFlags {
MMUEnabled = (1 << 0), InstructionCache = (1 << 12), DataCache = (1 << 2), ExtendedPaging = (1 << 23),
AccessPermissions = (1 << 29), BranchPrediction = (1 << 11), AlignmentCorrect = (1 << 22), AlignmentFaults = (1 << 1),
BigEndian = (1 << 25)
}
System Control flags.
enum AuxControlFlags { DisablePageColoring = (1 << 6), SMPBit = (1 << 6) }
Aux Control flags.
enum DomainControlFlags { DomainClient = 1, DomainManager = 3 }
Domain Control flags.
Public Member Functions
ARMControl ()
Constructor.
virtual ~ARMControl ()
Destructor.
u32 read (Register reg) const
Read a register from the CP15.
void write (Register reg, u32 value)
Write register to the CP15.
void set (SystemControlFlags flags)
Set system control flags in CP15.
void unset (SystemControlFlags flags)
Unset system control flags in CP15.
void set (AuxControlFlags flags)
Set auxillary flags in CP15.
void set (DomainControlFlags flags)
Set domain control flags in CP15.
Private Member Functions
void set (Register reg, u32 flags)
Set flag(s) in a CP15 register.
void unset (Register reg, u32 flags)
Unset flag(s) in a CP15 register.
Detailed Description
ARM System Control Coprocessor (CP15).
The ARM Architecture defines a coprocessor to manage various subsystems in the ARM core, including virtual memory, interrupts, debugging and more. It appears as coprocessor number 15 to the ARM core and is accessible by the MRC (ARM Register from Coprocessor) and MCR () instructions.
See also
ARM Architecture Reference Manual, page xxx
Definition at line 47 of file ARMControl.h.
Member Enumeration Documentation
AuxControlFlags
enum ARMControl::AuxControlFlags
Aux Control flags.
Enumerator
DisablePageColoring
SMPBit
Definition at line 102 of file ARMControl.h.
DomainControlFlags
enum ARMControl::DomainControlFlags
Domain Control flags.
Enumerator
DomainClient
DomainManager
Definition at line 111 of file ARMControl.h.
Register
enum ARMControl::Register
System Control Registers.
Enumerator
MainID
CoreID
SystemControl
AuxControl
DomainControl
TranslationTable0
TranslationTable1
TranslationTableCtrl
CacheClear
DataCacheClean
FlushPrefetchBuffer
InstructionCacheClear
InstructionTLBClear
DataTLBClear
UnifiedTLBClear
UserProcID
InstructionFaultAddress
InstructionFaultStatus
DataFaultAddress
DataFaultStatus
SystemFrequency
Definition at line 54 of file ARMControl.h.
SystemControlFlags
enum ARMControl::SystemControlFlags
System Control flags.
Enumerator
MMUEnabled
InstructionCache
DataCache
ExtendedPaging
AccessPermissions
BranchPrediction
AlignmentCorrect
AlignmentFaults
BigEndian
Definition at line 82 of file ARMControl.h.
Constructor & Destructor Documentation
ARMControl()
ARMControl::ARMControl ()
Constructor.
Definition at line 21 of file ARMControl.cpp.
~ARMControl()
ARMControl::~ARMControl () virtual
Destructor.
Definition at line 25 of file ARMControl.cpp.
Member Function Documentation
read()
u32 ARMControl::read (Register reg) const
Read a register from the CP15.
Parameters
reg The Register to read.
Returns
32-bit value of the register.
Definition at line 29 of file ARMControl.cpp.
References AuxControl, CoreID, DataFaultAddress, DataFaultStatus, DomainControl, InstructionFaultAddress, InstructionFaultStatus, MainID, mrc, SystemControl, SystemFrequency, TranslationTable0, TranslationTable1, TranslationTableCtrl, and UserProcID.
Referenced by ARMPaging::activate(), ARMKernel::ARMKernel(), ARMCore::logState(), set(), unset(), and ARMPaging::~ARMPaging().
set() [1/4]
void ARMControl::set (ARMControl::SystemControlFlags flags)
Set system control flags in CP15.
Parameters
flags New system control flags
Definition at line 88 of file ARMControl.cpp.
References SystemControl.
Referenced by ARMKernel::ARMKernel(), kernel_main(), and ARMPaging::~ARMPaging().
set() [2/4]
void ARMControl::set (ARMControl::AuxControlFlags flags)
Set auxillary flags in CP15.
Parameters
flags Auxillary flags to set
Definition at line 98 of file ARMControl.cpp.
References AuxControl.
set() [3/4]
void ARMControl::set (ARMControl::DomainControlFlags flags)
Set domain control flags in CP15.
Parameters
flags New domain control flags
Definition at line 103 of file ARMControl.cpp.
References DomainControl.
set() [4/4]
void ARMControl::set (Register reg, u32 flags) private
Set flag(s) in a CP15 register.
Parameters
reg Register to set
flags Flag values to set in the register
Definition at line 74 of file ARMControl.cpp.
References read(), and write().
unset() [1/2]
void ARMControl::unset (ARMControl::SystemControlFlags flags)
Unset system control flags in CP15.
Parameters
flags System control flags to remove
Definition at line 93 of file ARMControl.cpp.
References SystemControl.
Referenced by ARMKernel::ARMKernel(), and ARMPaging::~ARMPaging().
unset() [2/2]
void ARMControl::unset (Register reg, u32 flags) private
Unset flag(s) in a CP15 register.
Parameters
reg Register to unset
flags Flag values to remove from the register
Definition at line 81 of file ARMControl.cpp.
References read(), and write().
write()
void ARMControl::write (Register reg, u32 value)
Write register to the CP15.
Parameters
reg The Register to write.
value 32-value to write.
Definition at line 52 of file ARMControl.cpp.
References AuxControl, CacheClear, DataCacheClean, DataTLBClear, DomainControl, FlushPrefetchBuffer, InstructionCacheClear, InstructionTLBClear, mcr, SystemControl, TranslationTable0, TranslationTable1, TranslationTableCtrl, UnifiedTLBClear, and UserProcID.
Referenced by ARMPaging::activate(), set(), unset(), and ARMPaging::~ARMPaging().
The documentation for this class was generated from the following files:
lib/libarch/arm/ARMControl.h
lib/libarch/arm/ARMControl.cpp