FreeNOS: LinnFile Class Reference
LinnFile Class Reference
server » LinnFS
Represents a file on a mounted LinnFS filesystem.
#include <LinnFile.h>
Public Member Functions
LinnFile (LinnFileSystem *fs, LinnInode *inode)
Constructor function.
virtual ~LinnFile ()
Destructor function.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read out the file.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Attributes
LinnFileSystem * fs
Filesystem pointer.
LinnInode * inode
Inode pointer.
Additional Inherited Members
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
Represents a file on a mounted LinnFS filesystem.
Definition at line 41 of file LinnFile.h.
Constructor & Destructor Documentation
LinnFile()
LinnFile::LinnFile (LinnFileSystem * fs, LinnInode * inode)
Constructor function.
Parameters
fs LinnFS filesystem pointer.
inode Inode pointer.
Definition at line 22 of file LinnFile.cpp.
References inode, File::m_access, File::m_size, LinnInode::mode, and LinnInode::size.
~LinnFile()
LinnFile::~LinnFile () virtual
Destructor function.
Definition at line 29 of file LinnFile.cpp.
Member Function Documentation
read()
Error LinnFile::read (IOBuffer & buffer, Size size, Size offset) virtual
Read out the file.
Parameters
buffer Input/Output buffer to write bytes to.
size Number of bytes to copy at maximum.
offset Offset in the file to start reading.
Returns
Number of bytes read, or Error number.
See also
IOBuffer
Reimplemented from File.
Definition at line 33 of file LinnFile.cpp.
References LinnSuperBlock::blockSize, EIO, fs, LinnFileSystem::getOffset(), LinnFileSystem::getStorage(), LinnFileSystem::getSuperBlock(), inode, LINN_INODE_NUM_BLOCKS, Storage::read(), LinnInode::size, total, and IOBuffer::write().
Field Documentation
fs
LinnFileSystem* LinnFile::fs private
Filesystem pointer.
Definition at line 73 of file LinnFile.h.
Referenced by read().
inode
LinnInode* LinnFile::inode private
Inode pointer.
Definition at line 76 of file LinnFile.h.
Referenced by LinnFile(), and read().
The documentation for this class was generated from the following files:
server/filesystem/linn/LinnFile.h
server/filesystem/linn/LinnFile.cpp