FreeNOS: MemoryContext Class Reference
MemoryContext Class Reference abstract
lib » libarch
Virtual memory abstract interface.
#include <MemoryContext.h>
Public Types
enum Result {
Success, InvalidAddress, InvalidSize, AlreadyExists,
OutOfMemory
}
Result codes.
typedef enum MemoryContext::Result Result
Result codes.
Public Member Functions
MemoryContext (MemoryMap *map, SplitAllocator *alloc)
Constructor.
virtual ~MemoryContext ()
Destructor.
virtual Result activate ()=0
Activate the MemoryContext.
virtual Result map (Address virt, Address phys, Memory::Access access)=0
Map a physical page to a virtual address.
virtual Result unmap (Address virt)=0
Unmap a virtual address.
virtual Result lookup (Address virt, Address *phys) const =0
Translate virtual address to physical address.
virtual Result access (Address addr, Memory::Access *access) const =0
Get Access flags for a virtual address.
virtual Result mapRange (Memory::Range *range)
Map a range of physical pages to virtual addresses.
virtual Result unmapRange (Memory::Range *range)
Unmaps a range of virtual memory.
virtual Result release (Address virt)
Release a memory page mapping.
virtual Result releaseRange (Memory::Range *range, bool tablesOnly=false)=0
Release a range of physical memory by its virtual memory pages.
virtual Result releaseRegion (MemoryMap::Region region, bool tablesOnly=false)=0
Release memory region.
virtual Result findFree (Size size, MemoryMap::Region region, Address *virt) const
Find unused memory.
Static Public Member Functions
static MemoryContext * getCurrent ()
Get currently active MemoryContext.
Protected Attributes
SplitAllocator * m_alloc
Physical memory allocator.
MemoryMap * m_map
Virtual memory layout.
Static Protected Attributes
static MemoryContext * m_current = 0
The currently active MemoryContext.
Detailed Description
Virtual memory abstract interface.
Definition at line 41 of file MemoryContext.h.
Member Typedef Documentation
Result
typedef enum MemoryContext::Result MemoryContext::Result
Result codes.
Member Enumeration Documentation
Result
enum MemoryContext::Result
Result codes.
Enumerator
Success
InvalidAddress
InvalidSize
AlreadyExists
OutOfMemory
Definition at line 48 of file MemoryContext.h.
Constructor & Destructor Documentation
MemoryContext()
MemoryContext::MemoryContext (MemoryMap * map, SplitAllocator * alloc)
Constructor.
Parameters
alloc Allocator used to allocate page tables.
Definition at line 24 of file MemoryContext.cpp.
~MemoryContext()
MemoryContext::~MemoryContext () virtual
Destructor.
Definition at line 30 of file MemoryContext.cpp.
Member Function Documentation
access()
virtual Result MemoryContext::access (Address addr, Memory::Access * access) const pure virtual
Get Access flags for a virtual address.
Parameters
virt Virtual address to get Access flags for.
access MemoryAccess object pointer.
Returns
Result code.
Implemented in IntelPaging, and ARMPaging.
Referenced by ProcessShares::createShare(), and VMCtlHandler().
activate()
virtual Result MemoryContext::activate () pure virtual
Activate the MemoryContext.
This function applies this MemoryContext to the hardware MMU.
Returns
Result code.
Implemented in IntelPaging, and ARMPaging.
Referenced by IntelProcess::execute(), and ARMProcess::execute().
findFree()
MemoryContext::Result MemoryContext::findFree (Size size, MemoryMap::Region region, Address * virt) const virtual
Find unused memory.
This function finds a contigeous block of a given size of virtual memory which is unused and then returns the virtual address of the first page in the block.
Parameters
region Memory region to search in.
size Number of bytes requested to be free.
virt Virtual memory address on output.
Returns
Result code
Definition at line 80 of file MemoryContext.cpp.
References InvalidAddress, lookup(), m_map, OutOfMemory, PAGESIZE, MemoryMap::range(), Memory::Range::size, Success, and Memory::Range::virt.
Referenced by ProcessShares::createShare(), Process::initialize(), IO::map(), VMCopyHandler(), and VMCtlHandler().
getCurrent()
MemoryContext * MemoryContext::getCurrent () static
Get currently active MemoryContext.
Returns
MemoryContext object pointer or NULL.
Definition at line 34 of file MemoryContext.cpp.
References m_current.
Referenced by IO::map(), and IO::unmap().
lookup()
virtual Result MemoryContext::lookup (Address virt, Address * phys) const pure virtual
Translate virtual address to physical address.
Parameters
virt Virtual address to lookup on input, physical address on output.
Returns
Result code
Implemented in IntelPaging, and ARMPaging.
Referenced by ProcessShares::createShare(), findFree(), release(), VMCopyHandler(), and VMCtlHandler().
map()
virtual Result MemoryContext::map (Address virt, Address phys, Memory::Access access) pure virtual
Map a physical page to a virtual address.
Parameters
virt Virtual address.
phys Physical address.
access Page entry protection flags.
Returns
Result code.
Implemented in IntelPaging, and ARMPaging.
Referenced by Process::initialize(), Kernel::loadBootProcess(), IO::map(), mapRange(), and VMCopyHandler().
mapRange()
MemoryContext::Result MemoryContext::mapRange (Memory::Range * range) virtual
Map a range of physical pages to virtual addresses.
Parameters
range Range object describing the range of physical pages.
Returns
Result code.
Definition at line 39 of file MemoryContext.cpp.
References Memory::Range::access, SplitAllocator::allocate(), m_alloc, map(), PAGESIZE, Memory::Range::phys, Memory::Range::size, Success, and Memory::Range::virt.
Referenced by ProcessShares::createShare(), IntelProcess::initialize(), ARMProcess::initialize(), Process::initialize(), Kernel::loadBootProcess(), and VMCtlHandler().
release()
MemoryContext::Result MemoryContext::release (Address virt) virtual
Release a memory page mapping.
Parameters
virt Virtual address of the page to release.
Returns
Result code
Definition at line 69 of file MemoryContext.cpp.
References lookup(), m_alloc, SplitAllocator::release(), and Success.
releaseRange()
virtual Result MemoryContext::releaseRange (Memory::Range * range, bool tablesOnly = false) pure virtual
Release a range of physical memory by its virtual memory pages.
Parameters
range Range object describing the range of physical pages to release.
Returns
Result code
Implemented in IntelPaging, and ARMPaging.
Referenced by VMCtlHandler().
releaseRegion()
virtual Result MemoryContext::releaseRegion (MemoryMap::Region region, bool tablesOnly = false) pure virtual
Release memory region.
Deallocate all associated physical memory which resides in the given memory region.
Parameters
region Memory region to release
Returns
Result code
Implemented in IntelPaging, and ARMPaging.
Referenced by Process::~Process().
unmap()
virtual Result MemoryContext::unmap (Address virt) pure virtual
Unmap a virtual address.
This function removes a virtual to physical memory mapping without deallocating any physical memory.
Parameters
virt Virtual address to unmap.
Returns
Result code
Implemented in IntelPaging, and ARMPaging.
Referenced by Process::initialize(), unmapRange(), and VMCopyHandler().
unmapRange()
MemoryContext::Result MemoryContext::unmapRange (Memory::Range * range) virtual
Unmaps a range of virtual memory.
Parameters
range Range object describing the range of virtual addresses.
Returns
Result code
Definition at line 58 of file MemoryContext.cpp.
References PAGESIZE, Memory::Range::size, Success, unmap(), and Memory::Range::virt.
Referenced by ProcessShares::releaseShare(), IO::unmap(), and VMCtlHandler().
Field Documentation
m_alloc
SplitAllocator* MemoryContext::m_alloc protected
Physical memory allocator.
Definition at line 194 of file MemoryContext.h.
Referenced by ARMPaging::access(), IntelPaging::access(), ARMPaging::ARMPaging(), ARMPaging::lookup(), IntelPaging::lookup(), ARMPaging::map(), IntelPaging::map(), mapRange(), release(), ARMPaging::releaseRange(), IntelPaging::releaseRange(), ARMPaging::releaseRegion(), IntelPaging::releaseRegion(), ARMPaging::unmap(), IntelPaging::unmap(), ARMPaging::~ARMPaging(), and IntelPaging::~IntelPaging().
m_current
MemoryContext * MemoryContext::m_current = 0 static protected
The currently active MemoryContext.
Definition at line 200 of file MemoryContext.h.
Referenced by ARMPaging::activate(), IntelPaging::activate(), getCurrent(), ARMPaging::map(), IntelPaging::map(), ARMPaging::unmap(), and IntelPaging::unmap().
m_map
MemoryMap* MemoryContext::m_map protected
Virtual memory layout.
Definition at line 197 of file MemoryContext.h.
Referenced by ARMPaging::ARMPaging(), findFree(), IntelPaging::IntelPaging(), ARMPaging::releaseRegion(), and IntelPaging::releaseRegion().
The documentation for this class was generated from the following files:
lib/libarch/MemoryContext.h
lib/libarch/MemoryContext.cpp