FreeNOS: IntelPageDirectory Class Reference
IntelPageDirectory Class Reference
lib » libarch » Intel
Intel page directory implementation.
#include <IntelPageDirectory.h>
Public Member Functions
MemoryContext::Result copy (IntelPageDirectory *directory, Address from, Address to)
Copy mappings from another directory.
MemoryContext::Result map (Address virt, Address phys, Memory::Access access, SplitAllocator *alloc)
Map a virtual address to a physical address.
MemoryContext::Result unmap (Address virt, SplitAllocator *alloc)
Remove virtual address mapping.
MemoryContext::Result translate (Address virt, Address *phys, SplitAllocator *alloc) const
Translate virtual address to physical address.
MemoryContext::Result access (Address virt, Memory::Access *access, SplitAllocator *alloc) const
Get Access flags for a virtual address.
MemoryContext::Result releaseRange (Memory::Range range, SplitAllocator *alloc, bool tablesOnly)
Release range of memory.
Private Member Functions
IntelPageTable * getPageTable (Address virt, SplitAllocator *alloc) const
Retrieve second level page table.
u32 flags (Memory::Access access) const
Convert Memory::Access to page directory flags.
Private Attributes
u32 m_tables [1024]
Array of page directory entries.
Detailed Description
Intel page directory implementation.
Definition at line 42 of file IntelPageDirectory.h.
Member Function Documentation
access()
MemoryContext::Result IntelPageDirectory::access (Address virt, Memory::Access * access, SplitAllocator * alloc) const
Get Access flags for a virtual address.
Parameters
virt Virtual address to get Access flags for.
access MemoryAccess object pointer.
Returns
Result code.
Definition at line 115 of file IntelPageDirectory.cpp.
References IntelPageTable::access(), getPageTable(), and MemoryContext::InvalidAddress.
Referenced by IntelPaging::access().
copy()
MemoryContext::Result IntelPageDirectory::copy (IntelPageDirectory * directory, Address from, Address to)
Copy mappings from another directory.
Parameters
directory Source page directory to copy from
from Virtual address to start copy mapping from
to End virtual address of mappings to copy
Returns
Result code
Definition at line 52 of file IntelPageDirectory.cpp.
References DIRENTRY, m_tables, MegaByte, and MemoryContext::Success.
Referenced by IntelPaging::IntelPaging().
flags()
u32 IntelPageDirectory::flags (Memory::Access access) const private
Convert Memory::Access to page directory flags.
Parameters
acess Input memory access flags
Returns
Page directory flags
Definition at line 126 of file IntelPageDirectory.cpp.
References PAGE_USER, PAGE_WRITE, Memory::User, and Memory::Writable.
Referenced by map().
getPageTable()
IntelPageTable * IntelPageDirectory::getPageTable (Address virt, SplitAllocator * alloc) const private
Retrieve second level page table.
Parameters
virt Input virtual address to find second level page table for
alloc Memory allocator for high/low translation
Returns
Pointer to second level page table
Definition at line 41 of file IntelPageDirectory.cpp.
References DIRENTRY, m_tables, PAGE_PRESENT, PAGEMASK, SplitAllocator::toVirtual(), and ZERO.
Referenced by access(), map(), releaseRange(), translate(), and unmap().
map()
MemoryContext::Result IntelPageDirectory::map (Address virt, Address phys, Memory::Access access, SplitAllocator * alloc)
Map a virtual address to a physical address.
Parameters
virt Virtual address.
phys Physical address.
access Memory access flags.
alloc Physical memory allocator for extra page tables.
Returns
Result code
Definition at line 64 of file IntelPageDirectory.cpp.
References SplitAllocator::allocateLow(), DIRENTRY, flags(), getPageTable(), m_tables, IntelPageTable::map(), MemoryContext::OutOfMemory, PAGE_PRESENT, PAGE_WRITE, MemoryBlock::set(), Allocator::Success, and SplitAllocator::toVirtual().
Referenced by IntelPaging::map().
releaseRange()
MemoryContext::Result IntelPageDirectory::releaseRange (Memory::Range range, SplitAllocator * alloc, bool tablesOnly)
Release range of memory.
Parameters
range Memory range input
alloc Memory allocator to release memory from
tablesOnly Set to true to only release page tables and not mapped pages.
Returns
Result code.
Definition at line 136 of file IntelPageDirectory.cpp.
References DIRENTRY, getPageTable(), m_tables, MegaByte, PAGEMASK, PAGESIZE, SplitAllocator::release(), Memory::Range::size, MemoryContext::Success, IntelPageTable::translate(), and Memory::Range::virt.
Referenced by IntelPaging::releaseRange(), and IntelPaging::releaseRegion().
translate()
MemoryContext::Result IntelPageDirectory::translate (Address virt, Address * phys, SplitAllocator * alloc) const
Translate virtual address to physical address.
Parameters
virt Virtual address to lookup on input, physical address on output.
Returns
Result code
Definition at line 97 of file IntelPageDirectory.cpp.
References DIRENTRY, getPageTable(), MemoryContext::InvalidAddress, m_tables, MegaByte, PAGE_SECTION, PAGEMASK, MemoryContext::Success, and IntelPageTable::translate().
Referenced by IntelPaging::lookup().
unmap()
MemoryContext::Result IntelPageDirectory::unmap (Address virt, SplitAllocator * alloc)
Remove virtual address mapping.
Parameters
virt Virtual address.
Returns
Result code
Definition at line 88 of file IntelPageDirectory.cpp.
References getPageTable(), MemoryContext::InvalidAddress, and IntelPageTable::unmap().
Referenced by IntelPaging::unmap().
Field Documentation
m_tables
u32 IntelPageDirectory::m_tables[1024] private
Array of page directory entries.
Definition at line 144 of file IntelPageDirectory.h.
Referenced by copy(), getPageTable(), map(), releaseRange(), and translate().
The documentation for this class was generated from the following files:
lib/libarch/intel/IntelPageDirectory.h
lib/libarch/intel/IntelPageDirectory.cpp