FreeNOS: IntelIO Class Reference
IntelIO Class Reference
lib » libarch » Intel
Intel I/O functions.
#include <IntelIO.h>
Public Member Functions
u8 inb (u16 port) const
Read a byte from a port.
u16 inw (u16 port) const
Read a word from a port.
void outb (u16 port, u8 byte)
Output a byte to a port.
void outw (u16 port, u16 word)
Output a word to a port.
void outl (u16 port, u32 l)
Output a long to a I/O port.
u32 read (Address addr) const
Read memory mapped register.
void read (Address addr, Size count, void *buf) const
Read a number of 32-bit values.
void write (Address addr, u32 data)
Write memory mapped register.
void write (Address addr, Size count, void *buf)
Write a number of 32-bit values.
void set (Address addr, u32 data)
Set bits in memory mapped register.
void unset (Address addr, u32 data)
Unset bits in memory mapped register.
Public Member Functions inherited from IO
IO ()
Constructor.
uint getBase () const
Get I/O base offset.
void setBase (uint base)
Set I/O base offset.
Result map (Address phys, Size size=4096, Memory::Access access=Memory::Readable|Memory::Writable|Memory::User)
Map I/O address space.
Result unmap ()
Unmap I/O address space.
Additional Inherited Members
Public Types inherited from IO
enum Result { Success, MapFailure, OutOfMemory }
Result codes.
Protected Attributes inherited from IO
volatile uint m_base
I/O base offset is added to each I/O address.
Memory::Range m_range
Memory range for performing I/O mappings.
Detailed Description
Intel I/O functions.
Definition at line 38 of file IntelIO.h.
Member Function Documentation
inb()
u8 IntelIO::inb (u16 port) const inline
Read a byte from a port.
Parameters
port The I/O port to read from.
Returns
A byte read from the port.
Definition at line 49 of file IntelIO.h.
References IO::m_base.
Referenced by IntelPIC::disable(), IntelPIC::enable(), IntelPIT::getCounter(), IntelSerial::IntelSerial(), and IntelSerial::write().
inw()
u16 IntelIO::inw (u16 port) const inline
Read a word from a port.
Parameters
port The I/O port to read from.
Returns
Word read from the port.
Definition at line 64 of file IntelIO.h.
References IO::m_base.
outb()
void IntelIO::outb (u16 port, u8 byte) inline
Output a byte to a port.
Parameters
port Port to write to.
byte The byte to output.
Definition at line 78 of file IntelIO.h.
References IO::m_base.
Referenced by IntelPIC::clear(), IntelPIC::disable(), IntelPIC::enable(), IntelPIC::initialize(), IntelSerial::IntelSerial(), IntelPIT::setControl(), IntelPIT::setFrequency(), and IntelSerial::write().
outl()
void IntelIO::outl (u16 port, u32 l) inline
Output a long to a I/O port.
Parameters
port Target I/O port.
l The long 32-bit number to output.
Definition at line 102 of file IntelIO.h.
References IO::m_base.
outw()
void IntelIO::outw (u16 port, u16 word) inline
Output a word to a port.
Parameters
port Port to write to.
byte The word to output.
Definition at line 90 of file IntelIO.h.
References IO::m_base.
read() [1/2]
u32 IntelIO::read (Address addr) const inline
Read memory mapped register.
Parameters
addr Address of the register to read.
Returns
32-bit value of the register.
Definition at line 115 of file IntelIO.h.
References IO::m_base.
Referenced by IntelAPIC::getCounter(), read(), IntelAPIC::sendStartupIPI(), set(), IntelAPIC::start(), unset(), and IntelAPIC::wait().
read() [2/2]
void IntelIO::read (Address addr, Size count, void * buf) const inline
Read a number of 32-bit values.
Parameters
addr Address of the starting 32-bit value.
count Number of bytes to read.
buf Output buffer.
Definition at line 128 of file IntelIO.h.
References read().
set()
void IntelIO::set (Address addr, u32 data) inline
Set bits in memory mapped register.
Parameters
addr Address of the register to write.
data 32-bit value containing the bits to set (bitwise or).
Definition at line 169 of file IntelIO.h.
References read(), and write().
Referenced by IntelAPIC::initialize().
unset()
void IntelIO::unset (Address addr, u32 data) inline
Unset bits in memory mapped register.
Parameters
addr Address of the register to write.
data 32-bit value containing the bits to set (bitwise or).
Definition at line 182 of file IntelIO.h.
References IO::IO(), read(), and write().
write() [1/2]
void IntelIO::write (Address addr, u32 data) inline
Write memory mapped register.
Parameters
addr Address of the register to write.
data 32-bit value to write in the register.
Definition at line 142 of file IntelIO.h.
References IO::m_base.
Referenced by IntelAPIC::clear(), IntelAPIC::initialize(), IntelAPIC::sendStartupIPI(), set(), IntelAPIC::start(), unset(), and write().
write() [2/2]
void IntelIO::write (Address addr, Size count, void * buf) inline
Write a number of 32-bit values.
Parameters
addr Address of the starting 32-bit value.
count Number of bytes to write.
buf Input buffer.
Definition at line 155 of file IntelIO.h.
References write().
The documentation for this class was generated from the following file:
lib/libarch/intel/IntelIO.h