FreeNOS: IPCTest Class Reference
IPCTest Class Reference
bin
Test program for inter process communication.
#include <IPCTest.h>
Public Member Functions
IPCTest (int argc, char **argv)
Constructor.
virtual ~IPCTest ()
Destructor.
virtual Result exec ()
Execute the application.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
Test program for inter process communication.
Definition at line 31 of file IPCTest.h.
Constructor & Destructor Documentation
IPCTest()
IPCTest::IPCTest (int argc, char ** argv)
Constructor.
Parameters
argc Argument count
argv Argument values
Definition at line 31 of file IPCTest.cpp.
References Application::parser(), and ArgumentParser::setDescription().
~IPCTest()
IPCTest::~IPCTest () virtual
Destructor.
Definition at line 37 of file IPCTest.cpp.
Member Function Documentation
exec()
IPCTest::Result IPCTest::exec () virtual
Execute the application.
Returns
Result code
Implements Application.
Definition at line 41 of file IPCTest.cpp.
References IPCTestMessage::action, connect(), IPCTestMessage::data, ERROR, InfoPID, Singleton< ChannelClient >::instance, Application::InvalidArgument, Application::IOError, IPCTESTSERVER_CMD, MAX_PROCS, API::NotFound, NOTICE, PAGESIZE, ProcessCtl(), MemoryMap::range(), API::Read, strlen(), strncmp(), Application::Success, ChannelClient::Success, TestActionB, MemoryMap::UserArgs, Memory::Range::virt, and VMCopy().
The documentation for this class was generated from the following files:
bin/ipctest/IPCTest.h
bin/ipctest/IPCTest.cpp