FreeNOS: ICMPFactory Class Reference
ICMPFactory Class Reference
lib » libnet
Internet Control Message Protocol (ICMP) factory.
#include <ICMPFactory.h>
Public Member Functions
ICMPFactory (ICMP *icmp)
Constructor.
virtual ~ICMPFactory ()
Destructor.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Receive ICMP response.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Attributes
ICMP * m_icmp
ICMP protocol instance.
Additional Inherited Members
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
Internet Control Message Protocol (ICMP) factory.
The ICMP factory creates new sockets for applications.
Definition at line 39 of file ICMPFactory.h.
Constructor & Destructor Documentation
ICMPFactory()
ICMPFactory::ICMPFactory (ICMP * icmp)
Constructor.
Definition at line 21 of file ICMPFactory.cpp.
References m_icmp.
~ICMPFactory()
ICMPFactory::~ICMPFactory () virtual
Destructor.
Definition at line 26 of file ICMPFactory.cpp.
Member Function Documentation
read()
Error ICMPFactory::read (IOBuffer & buffer, Size size, Size offset) virtual
Receive ICMP response.
Parameters
buffer Input/Output buffer to output bytes to.
size Number of bytes to read, at maximum.
offset Offset inside the file to start reading.
Returns
Number of bytes read on success, Error on failure.
Reimplemented from File.
Definition at line 30 of file ICMPFactory.cpp.
References ICMP::createSocket(), DEBUG, EIO, String::length(), m_icmp, and IOBuffer::write().
Field Documentation
m_icmp
ICMP* ICMPFactory::m_icmp private
ICMP protocol instance.
Definition at line 67 of file ICMPFactory.h.
Referenced by ICMPFactory(), and read().
The documentation for this class was generated from the following files:
lib/libnet/ICMPFactory.h
lib/libnet/ICMPFactory.cpp