FreeNOS: List< T >::Node Class Reference
List< T >::Node Class Reference
Represents an item on the List.
#include <List.h>
Public Member Functions
Node (T t)
Constructor.
Data Fields
T data
Item of this node.
Node * prev
Previous node.
Node * next
Next node.
Detailed Description
template<class T>
class List< T >::Node
Represents an item on the List.
Definition at line 43 of file List.h.
Constructor & Destructor Documentation
Node()
template<class T> List< T >::Node::Node (T t) inline
Constructor.
Definition at line 50 of file List.h.
References List< T >::Node::next, List< T >::Node::prev, and ZERO.
Referenced by List< ATADrive *>::append(), List< ATADrive *>::at(), List< ATADrive *>::clear(), List< ATADrive *>::contains(), List< ATADrive *>::get(), List< ATADrive *>::List(), List< ATADrive *>::operator!=(), List< ATADrive *>::operator==(), List< ATADrive *>::prepend(), List< ATADrive *>::remove(), and List< ATADrive *>::~List().
Field Documentation
data
template<class T> T List< T >::Node::data
Item of this node.
Definition at line 57 of file List.h.
Referenced by List< ATADrive *>::at(), List< ATADrive *>::first(), and List< ATADrive *>::last().
next
template<class T> Node* List< T >::Node::next
Next node.
Definition at line 63 of file List.h.
Referenced by List< ATADrive *>::append(), List< ATADrive *>::at(), List< ATADrive *>::clear(), List< ATADrive *>::contains(), List< T >::Node::Node(), List< ATADrive *>::operator!=(), List< ATADrive *>::operator==(), List< ATADrive *>::prepend(), and List< ATADrive *>::remove().
prev
template<class T> Node* List< T >::Node::prev
Previous node.
Definition at line 60 of file List.h.
Referenced by List< T >::Node::Node(), List< ATADrive *>::prepend(), and List< ATADrive *>::remove().
The documentation for this class was generated from the following file:
lib/libstd/List.h