FreeNOS: PoolAllocator Class Reference
PoolAllocator Class Reference
lib » liballoc
Memory allocator which uses pools.
#include <PoolAllocator.h>
Public Member Functions
PoolAllocator ()
Constructor.
virtual Size size () const
Get memory size.
virtual Size available () const
Get memory available.
virtual Result allocate (Size *size, Address *addr, Size align=ZERO)
Allocate memory.
virtual Result release (Address addr)
Release memory.
Public Member Functions inherited from Allocator
Allocator ()
Class constructor.
virtual ~Allocator ()
Class destructor.
void setParent (Allocator *parent)
Set parent allocator.
Result setAlignment (Size size)
Set allocation alignment.
Result setBase (Address addr)
Set allocation base.
Private Member Functions
MemoryPool * newPool (Size index, Size cnt)
Creates a new MemoryPool instance.
Private Attributes
MemoryPool * m_pools [POOL_MAX_POWER]
Array of memory pools.
Additional Inherited Members
Public Types inherited from Allocator
enum Result {
Success = 0, InvalidAddress, InvalidSize, InvalidAlignment,
OutOfMemory
}
Allocation results.
Static Public Member Functions inherited from Allocator
static void setDefault (Allocator *alloc)
Makes the given Allocator the default.
static Allocator * getDefault ()
Retrieve the currently default Allocator.
Protected Member Functions inherited from Allocator
Address aligned (Address addr, Size boundary) const
Align memory address.
Protected Attributes inherited from Allocator
Allocator * m_parent
Our parent Allocator, if any.
Size m_alignment
Allocation memory alignment.
Address m_base
Allocation base address.
Detailed Description
Memory allocator which uses pools.
Allocates memory from pools the size of a power of two. Each pool is pre-allocated and has a bitmap representing free blocks.
Definition at line 139 of file PoolAllocator.h.
Constructor & Destructor Documentation
PoolAllocator()
PoolAllocator::PoolAllocator ()
Constructor.
Definition at line 22 of file PoolAllocator.cpp.
References m_pools, and MemoryBlock::set().
Member Function Documentation
allocate()
Allocator::Result PoolAllocator::allocate (Size * size, Address * addr, Size align = ZERO) virtual
Allocate memory.
Parameters
size Amount of memory in bytes to allocate on input. On output, the amount of memory in bytes actually allocated.
addr Output parameter which contains the address allocated on success.
align Alignment of the required memory or use ZERO for default.
Returns
Result value.
Implements Allocator.
Definition at line 38 of file PoolAllocator.cpp.
References MemoryPool::allocate(), MemoryPool::free, Allocator::m_parent, m_pools, newPool(), MemoryPool::next, Allocator::OutOfMemory, POOL_MAX_POWER, POOL_MIN_COUNT, POOL_MIN_POWER, Allocator::Success, and ZERO.
available()
Size PoolAllocator::available () const virtual
Get memory available.
Returns
Size of memory available by the Allocator.
Implements Allocator.
Definition at line 33 of file PoolAllocator.cpp.
References Allocator::available(), Allocator::m_parent, and ZERO.
newPool()
MemoryPool * PoolAllocator::newPool (Size index, Size cnt) private
Creates a new MemoryPool instance.
Parameters
index Index in the pools array.
cnt Allocate for this many of blocks from our parent.
Returns
Pointer to a MemoryPool object on success, ZERO on failure.
Definition at line 82 of file PoolAllocator.cpp.
References Allocator::aligned(), Allocator::allocate(), BITMAP_NUM_BYTES, MemoryPool::free, Allocator::m_parent, m_pools, MEMALIGN, MemoryBlock::set(), and Allocator::Success.
Referenced by allocate().
release()
Allocator::Result PoolAllocator::release (Address addr) virtual
Release memory.
Parameters
addr Points to memory previously returned by allocate().
Returns
Result value.
See also
allocate
Implements Allocator.
Definition at line 107 of file PoolAllocator.cpp.
References Allocator::InvalidAddress, m_pools, MemoryPool::next, POOL_MAX_POWER, POOL_MIN_POWER, and Allocator::Success.
size()
Size PoolAllocator::size () const virtual
Get memory size.
Returns
Size of memory owned by the Allocator.
Implements Allocator.
Definition at line 28 of file PoolAllocator.cpp.
References Allocator::m_parent, Allocator::size(), and ZERO.
Field Documentation
m_pools
MemoryPool* PoolAllocator::m_pools[POOL_MAX_POWER] private
Array of memory pools.
Index represents the power of two.
Definition at line 201 of file PoolAllocator.h.
Referenced by allocate(), newPool(), PoolAllocator(), and release().
The documentation for this class was generated from the following files:
lib/liballoc/PoolAllocator.h
lib/liballoc/PoolAllocator.cpp