FreeNOS: BootImageCreate Class Reference
BootImageCreate Class Reference
bin
Create system boot image.
#include <BootImageCreate.h>
Public Member Functions
BootImageCreate (int argc, char **argv)
Constructor.
virtual ~BootImageCreate ()
Destructor.
virtual Result exec ()
Execute the application.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Protected Member Functions
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Private Member Functions
Size readBootSymbols (const char *file, const char *prefix, Vector< BootEntry *> *entries)
Read boot symbols using a configuration file.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Detailed Description
Create system boot image.
Definition at line 52 of file BootImageCreate.h.
Constructor & Destructor Documentation
BootImageCreate()
BootImageCreate::BootImageCreate (int argc, char ** argv)
Constructor.
Parameters
argc Argument count
argv Argument values
Definition at line 31 of file BootImageCreate.cpp.
References Application::parser(), ArgumentParser::registerFlag(), ArgumentParser::registerPositional(), and ArgumentParser::setDescription().
~BootImageCreate()
BootImageCreate::~BootImageCreate () virtual
Destructor.
Definition at line 40 of file BootImageCreate.cpp.
Member Function Documentation
exec()
BootImageCreate::Result BootImageCreate::exec () virtual
Execute the application.
Returns
Result code
Implements Application.
Definition at line 166 of file BootImageCreate.cpp.
References Application::arguments(), BOOTIMAGE_MAGIC0, BOOTIMAGE_MAGIC1, BOOTIMAGE_NAMELEN, BOOTIMAGE_REVISION, BootImage::bootImageSize, Vector< T >::count(), BootSymbol::entry, errno, fclose(), fopen(), ArgumentContainer::get(), Application::IOError, BootImage::layoutRevision, BootImage::magic, memset(), name, ArgumentParser::name(), NULL, BootSegment::offset, PAGESIZE, Application::parser(), readBootSymbols(), SEEK_SET, BootSymbol::segmentsCount, BootSymbol::segmentsOffset, BootImage::segmentsTableCount, BootImage::segmentsTableOffset, BootSymbol::segmentsTotalSize, BootSegment::size, Vector< T >::size(), strerror(), strncpy(), Application::Success, BootImage::symbolTableCount, BootImage::symbolTableOffset, BootSymbol::type, and BootSegment::virtualAddress.
output()
BootImageCreate::Result BootImageCreate::output (const char * string) const protected virtual
Print text to output.
Parameters
string Text to print to program output.
Returns
Result code.
Implements Application.
Definition at line 44 of file BootImageCreate.cpp.
References printf(), and Application::Success.
readBootSymbols()
Size BootImageCreate::readBootSymbols (const char * file, const char * prefix, Vector< BootEntry *> * entries) private
Read boot symbols using a configuration file.
Parameters
file Name of the boot configuration file.
prefix Prefix each entry from the config file with the given path or NULL
entries Pointer to Vector with BootEntry's
Returns
Number of bytes read
Definition at line 50 of file BootImageCreate.cpp.
References ExecutableFormat::Region::access, BootData, BOOTENTRY_MAX_REGIONS, BOOTIMAGE_NAMELEN, BootProgram, ExecutableFormat::Region::data, BootSymbol::entry, ExecutableFormat::entry(), errno, exit(), EXIT_FAILURE, fclose(), ExecutableFormat::find(), fopen(), fread(), Vector< T >::insert(), ArgumentParser::name(), BootSymbol::name, NULL, BootEntry::numRegions, Application::parser(), PATH_MAX, printf(), Memory::Readable, BootEntry::regions, ExecutableFormat::regions(), ExecutableFormat::Region::size, snprintf(), stat::st_size, stat(), strerror(), strlen(), strncpy(), ExecutableFormat::Success, BootEntry::symbol, BootSymbol::type, Memory::User, ExecutableFormat::Region::virt, and Memory::Writable.
Referenced by exec().
The documentation for this class was generated from the following files:
bin/img/BootImageCreate.h
bin/img/BootImageCreate.cpp