FreeNOS: MemoryChannel Class Reference
MemoryChannel Class Reference
lib » libipc
Unidirectional point-to-point channel using shared memory.
#include <MemoryChannel.h>
Data Structures
struct RingHead
Defines in-memory ring header.
Public Member Functions
MemoryChannel ()
Constructor.
virtual ~MemoryChannel ()
Destructor.
Result setVirtual (Address data, Address feedback)
Set memory pages by virtual address.
Result setPhysical (Address data, Address feedback)
Set memory pages by physical address.
virtual Result setMessageSize (Size size)
Set message size.
virtual Result read (void *buffer)
Read a message.
virtual Result write (void *buffer)
Write a message.
virtual Result flush ()
Flush message buffers.
bool operator== (const MemoryChannel &ch) const
bool operator!= (const MemoryChannel &ch) const
Public Member Functions inherited from Channel
Channel ()
Constructor.
virtual ~Channel ()
Destructor.
const Size getMessageSize () const
Get message size.
const Size getMaximumMessages () const
Get maximum message count.
Result setMode (Mode mode)
Set mode.
Private Types
typedef struct MemoryChannel::RingHead RingHead
Defines in-memory ring header.
Private Attributes
Arch::IO m_data
The data page.
Arch::IO m_feedback
The feedback page.
RingHead m_head
Local RingHead.
Additional Inherited Members
Public Types inherited from Channel
enum Result {
Success, InvalidArgument, InvalidMode, InvalidSize,
IOError, ChannelFull, NotFound
}
Result codes.
enum Mode { Producer, Consumer }
Channel modes.
Protected Attributes inherited from Channel
Mode m_mode
Channel mode.
Size m_messageSize
Message size.
Size m_maximumMessages
Maximum number of message that the Channel can hold.
Detailed Description
Unidirectional point-to-point channel using shared memory.
Implemented by using two separated memory pages. The data page is for the consumer in which it only reads the incoming data payloads. The producer writes payloads to the data page. The feedback page is written only by the consumer, where it stores the feedback information from its consumption, such as the total bytes read and status.
Definition at line 43 of file MemoryChannel.h.
Member Typedef Documentation
RingHead
typedef struct MemoryChannel::RingHead MemoryChannel::RingHead private
Defines in-memory ring header.
Constructor & Destructor Documentation
MemoryChannel()
MemoryChannel::MemoryChannel ()
Constructor.
Definition at line 22 of file MemoryChannel.cpp.
References m_head, and MemoryBlock::set().
~MemoryChannel()
MemoryChannel::~MemoryChannel () virtual
Destructor.
Definition at line 28 of file MemoryChannel.cpp.
Member Function Documentation
flush()
MemoryChannel::Result MemoryChannel::flush () virtual
Flush message buffers.
Ensures that all messages are written through caches.
Returns
Result code.
Implements Channel.
Definition at line 103 of file MemoryChannel.cpp.
References Cache::cleanData(), IO::getBase(), Channel::IOError, isKernel, m_data, m_feedback, and Channel::Success.
Referenced by Process::raiseEvent().
operator!=()
bool MemoryChannel::operator!= (const MemoryChannel & ch) const inline
Definition at line 140 of file MemoryChannel.h.
operator==()
bool MemoryChannel::operator== (const MemoryChannel & ch) const inline
Definition at line 135 of file MemoryChannel.h.
read()
MemoryChannel::Result MemoryChannel::read (void * buffer) virtual
Read a message.
Parameters
buffer Output buffer for the message.
Returns
Result code.
Implements Channel.
Definition at line 61 of file MemoryChannel.cpp.
References MemoryChannel::RingHead::index, m_data, m_feedback, m_head, Channel::m_maximumMessages, Channel::m_messageSize, Channel::NotFound, ARMIO::read(), Channel::Success, and ARMIO::write().
Referenced by CoreServer::createProcess(), MPI_Recv(), CoreServer::runCore(), and CoreServer::test().
setMessageSize()
MemoryChannel::Result MemoryChannel::setMessageSize (Size size) virtual
Set message size.
Parameters
size New message size.
Returns
Result code.
Reimplemented from Channel.
Definition at line 32 of file MemoryChannel.cpp.
References Channel::InvalidArgument, Channel::m_maximumMessages, Channel::m_messageSize, PAGESIZE, and Channel::Success.
Referenced by ChannelServer< FileSystem, FileSystemMessage >::accept(), ChannelClient::connect(), Process::initialize(), MPI_Init(), and CoreServer::setupChannels().
setPhysical()
MemoryChannel::Result MemoryChannel::setPhysical (Address data, Address feedback)
Set memory pages by physical address.
This function maps the given physical addresses into the current address space using IO::map.
Parameters
data Physical memory address of the data page. Read/Write for the producer, Read-only for the consumer.
feedback Physical memory address of the feedback page. Read/write for the consumer, read-only for the producer.
Returns
Result code.
Definition at line 50 of file MemoryChannel.cpp.
References Channel::IOError, m_data, m_feedback, IO::map(), PAGESIZE, Channel::Success, and IO::Success.
Referenced by MPI_Init(), and CoreServer::setupChannels().
setVirtual()
MemoryChannel::Result MemoryChannel::setVirtual (Address data, Address feedback)
Set memory pages by virtual address.
This function assumes that the given virtual addresses are already mapped into the associated address space.
Parameters
data Virtual memory address of the data page. Read/Write for the producer, Read-only for the consumer.
feedback Virtual memory address of the feedback page. Read/write for the consumer, read-only for the producer.
Returns
Result code.
Definition at line 43 of file MemoryChannel.cpp.
References m_data, m_feedback, IO::setBase(), and Channel::Success.
Referenced by ChannelServer< FileSystem, FileSystemMessage >::accept(), ChannelClient::connect(), and Process::initialize().
write()
MemoryChannel::Result MemoryChannel::write (void * buffer) virtual
Write a message.
Parameters
buffer Input buffer for the message.
Returns
Result code.
Implements Channel.
Definition at line 83 of file MemoryChannel.cpp.
References Channel::ChannelFull, MemoryChannel::RingHead::index, m_data, m_feedback, m_head, Channel::m_maximumMessages, Channel::m_messageSize, ARMIO::read(), Channel::Success, and ARMIO::write().
Referenced by CoreServer::createProcess(), MPI_Send(), Process::raiseEvent(), CoreServer::runCore(), and CoreServer::test().
Field Documentation
m_data
Arch::IO MemoryChannel::m_data private
The data page.
Definition at line 148 of file MemoryChannel.h.
Referenced by flush(), read(), setPhysical(), setVirtual(), and write().
m_feedback
Arch::IO MemoryChannel::m_feedback private
The feedback page.
Definition at line 151 of file MemoryChannel.h.
Referenced by flush(), read(), setPhysical(), setVirtual(), and write().
m_head
RingHead MemoryChannel::m_head private
Local RingHead.
Definition at line 154 of file MemoryChannel.h.
Referenced by MemoryChannel(), read(), and write().
The documentation for this class was generated from the following files:
lib/libipc/MemoryChannel.h
lib/libipc/MemoryChannel.cpp