FreeNOS: NetworkQueue Class Reference
NetworkQueue Class Reference
lib » libnet
Networking packet queue implementation.
#include <NetworkQueue.h>
Data Structures
struct Packet
Represents a network packet.
Public Types
typedef struct NetworkQueue::Packet Packet
Represents a network packet.
Public Member Functions
NetworkQueue (Size packetSize, Size headerSize=0, Size queueSize=8)
Constructor.
virtual ~NetworkQueue ()
Destructor.
void setHeaderSize (Size size)
Set default packet header size.
Packet * get ()
Get unused packet.
void release (Packet *packet)
Put unused packet back.
void push (Packet *packet)
Enqueue packet with data.
Packet * pop ()
Retrieve packet with data.
Private Attributes
Index< Packet > m_free
Contains unused packets.
Index< Packet > m_data
Contains packets with data.
Size m_packetSize
Size of each packet.
Size m_packetHeader
Size of physical hardware header.
Detailed Description
Networking packet queue implementation.
Definition at line 35 of file NetworkQueue.h.
Member Typedef Documentation
Packet
typedef struct NetworkQueue::Packet NetworkQueue::Packet
Represents a network packet.
Constructor & Destructor Documentation
NetworkQueue()
NetworkQueue::NetworkQueue (Size packetSize, Size headerSize = 0, Size queueSize = 8)
Constructor.
Parameters
packetSize The size of each packet in bytes
headerSize Size of the physical header, if any
queueSize The size of the queue in number of packets
Definition at line 20 of file NetworkQueue.cpp.
References NetworkQueue::Packet::data, m_free, m_packetHeader, m_packetSize, and NetworkQueue::Packet::size.
Referenced by NetworkQueue::Packet::operator!=().
~NetworkQueue()
NetworkQueue::~NetworkQueue () virtual
Destructor.
Definition at line 34 of file NetworkQueue.cpp.
References NetworkQueue::Packet::data, and m_free.
Referenced by NetworkQueue::Packet::operator!=().
Member Function Documentation
get()
NetworkQueue::Packet * NetworkQueue::get ()
Get unused packet.
Definition at line 52 of file NetworkQueue.cpp.
References m_free, m_packetHeader, NetworkQueue::Packet::size, and ZERO.
Referenced by Ethernet::getTransmitPacket(), UDPSocket::process(), and SMSC95xxUSB::readStart().
pop()
NetworkQueue::Packet * NetworkQueue::pop ()
Retrieve packet with data.
Definition at line 78 of file NetworkQueue.cpp.
References m_data, and ZERO.
Referenced by NetworkQueue::Packet::operator!=(), UDPSocket::read(), and SMSC95xxUSB::writeStart().
push()
void NetworkQueue::push (NetworkQueue::Packet * packet)
Enqueue packet with data.
Definition at line 73 of file NetworkQueue.cpp.
References m_data.
Referenced by NetworkQueue::Packet::operator!=(), UDPSocket::process(), and SMSC95xxUSB::transmit().
release()
void NetworkQueue::release (NetworkQueue::Packet * packet)
Put unused packet back.
Definition at line 67 of file NetworkQueue.cpp.
References m_free, m_packetHeader, and NetworkQueue::Packet::size.
Referenced by NetworkQueue::Packet::operator!=(), UDPSocket::read(), SMSC95xxUSB::readFinished(), Loopback::transmit(), and SMSC95xxUSB::writeFinished().
setHeaderSize()
void NetworkQueue::setHeaderSize (Size size)
Set default packet header size.
Definition at line 47 of file NetworkQueue.cpp.
References m_packetHeader.
Referenced by NetworkQueue::Packet::operator!=(), and SMSC95xxUSB::SMSC95xxUSB().
Field Documentation
m_data
Index<Packet> NetworkQueue::m_data private
Contains packets with data.
Definition at line 105 of file NetworkQueue.h.
Referenced by pop(), and push().
m_free
Index<Packet> NetworkQueue::m_free private
Contains unused packets.
Definition at line 102 of file NetworkQueue.h.
Referenced by get(), NetworkQueue(), release(), and ~NetworkQueue().
m_packetHeader
Size NetworkQueue::m_packetHeader private
Size of physical hardware header.
This reserves some bytes at the start of the actual packet payload. Some hardware needs an extra physical header before the ethernet/ip headers.
Definition at line 116 of file NetworkQueue.h.
Referenced by get(), NetworkQueue(), release(), and setHeaderSize().
m_packetSize
Size NetworkQueue::m_packetSize private
Size of each packet.
Definition at line 108 of file NetworkQueue.h.
Referenced by NetworkQueue().
The documentation for this class was generated from the following files:
lib/libnet/NetworkQueue.h
lib/libnet/NetworkQueue.cpp