FreeNOS: MountsFile Class Reference
MountsFile Class Reference
server » SysFS
The filesystem mounts file exports the FileSystemMount table.
#include <MountsFile.h>
Public Member Functions
MountsFile ()
Constructor function.
virtual ~MountsFile ()
Destructor function.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read bytes from the file.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Additional Inherited Members
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
The filesystem mounts file exports the FileSystemMount table.
To retrieve the currently mounted filesystems, a process simply reads this entire file. To mount a new file system, a process writes a new 'FileSystemMount' structure to this file.
See also
FileSystem
Definition at line 39 of file MountsFile.h.
Constructor & Destructor Documentation
MountsFile()
MountsFile::MountsFile ()
Constructor function.
Definition at line 22 of file MountsFile.cpp.
References FILESYSTEM_MAXMOUNTS, File::m_access, File::m_size, and OwnerRW.
~MountsFile()
MountsFile::~MountsFile () virtual
Destructor function.
Definition at line 28 of file MountsFile.cpp.
Member Function Documentation
read()
Error MountsFile::read (IOBuffer & buffer, Size size, Size offset) virtual
Read bytes from the file.
Parameters
buffer Input/Output buffer to output bytes to.
size Number of bytes to read, at maximum.
offset Offset inside the file to start reading.
Returns
Number of bytes read on success, Error on failure.
Reimplemented from File.
Definition at line 32 of file MountsFile.cpp.
References EIO, getMounts(), File::m_size, mounts, and IOBuffer::write().
write()
Error MountsFile::write (IOBuffer & buffer, Size size, Size offset) virtual
Write bytes to the file.
Parameters
buffer Input/Output buffer to input bytes from.
size Number of bytes to write, at maximum.
offset Offset inside the file to start writing.
Returns
Number of bytes written on success, Error on failure.
Reimplemented from File.
Definition at line 44 of file MountsFile.cpp.
References EIO, ENOBUFS, FILESYSTEM_MAXMOUNTS, getMounts(), memcpy(), mounts, NOTICE, and IOBuffer::read().
The documentation for this class was generated from the following files:
server/filesystem/sys/MountsFile.h
server/filesystem/sys/MountsFile.cpp