FreeNOS: SMSC95xxUSB Class Reference
SMSC95xxUSB Class Reference
server » smsc95xx
SMSC95xx USB-based Ethernet controller.
#include <SMSC95xxUSB.h>
Public Member Functions
SMSC95xxUSB (u8 deviceId, const char *usbPath, NetworkServer *server, SMSC95xx *smsc)
Constructor.
virtual ~SMSC95xxUSB ()
Destructor.
virtual Error initialize ()
Initialize the controller.
virtual Error transmit (NetworkQueue::Packet *pkt)
Transmit one network packet.
Public Member Functions inherited from USBDevice
USBDevice (u8 deviceId, const char *usbPath="/usb")
Constructor.
virtual ~USBDevice ()
Destructor.
Public Member Functions inherited from Device
Device (FileType type)
Constructor.
virtual ~Device ()
Destructor.
virtual const String & getIdentifier () const
Get unique device identifier.
virtual Error interrupt (Size vector)
Called when an interrupt has been triggered for this device.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read bytes from the file.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Static Public Attributes
static const Size TransmitCommandSize = 8
Transmit Command Word size.
static const Size ReceiveCommandSize = 4
Receive Command Word size.
Private Types
enum Register {
DeviceID = 0x00, InterruptStatus = 0x08, ReceiveConfig = 0x0c, TransmitConfig = 0x10,
HardwareConfig = 0x14, ReceiveFIFOInfo = 0x18, PowerControl = 0x20, LEDConfig = 0x24,
GPIOConfig = 0x28, FlowControl = 0x2c, EEPromCommand = 0x30, EEPromData = 0x34,
BurstCap = 0x38, GPIOWake = 0x64, MACControl = 0x100, MACAddrHigh = 0x104,
MACAddrLow = 0x108, MIIControl = 0x114
}
Hardware registers.
enum InterruptStatusFlags { TransferStop = 0x00020000, ReceiveStop = 0x00010000, PhyInterrupt = 0x00008000 }
InterruptStatus register flags.
enum TransmitConfigFlags { TransmitOn = 0x00000004, TransmitOff = 0x00000002, TransmitFlush = 0x00000001 }
TransmitConfig register flags.
enum HardwareConfigFlags { BulkIn = 0x00001000, MultipleEther = 0x00000020, BCE = 0x00000002 }
HardwareConfig register flags.
enum MACControlFlags { MACTransmit = 0x00000008, MACReceive = 0x00000004 }
MACControl register flags.
enum USBRequest { WriteRegister = 0xa0, ReadRegister = 0xa1, GetStatus = 0xa2 }
Various vendor-specific USB control message requests.
enum TransmitCommand {
TxCommandADataOffset = 0x001F0000, TxCommandAFirstSeg = 0x00002000, TxCommandALastSeg = 0x00001000, TxCommandABufSize = 0x000007FF,
TxCommandBChecksum = 0x00004000, TxCommandBCRC = 0x00002000, TxCommandBPadding = 0x00001000, TxCommandBLength = 0x000007FF
}
Transmit Command Words.
enum ReceiveCommand {
RxCommandFilterFail = 0x40000000, RxCommandFrameLength = 0x3fff0000, RxCommandErrorSummary = 0x00008000, RxCommandBroadcastFrame = 0x00002000,
RxCommandLengthError = 0x00001000, RxCommandRuntFrame = 0x00000800, RxCommandMulticastFrame = 0x00000400, RxCommandFrameTooLong = 0x00000080,
RxCommandFrameCollision = 0x00000040, RxCommandFrameType = 0x00000020, RxCommandReceiveWatchdog = 0x00000010, RxCommandMIIError = 0x00000008,
RxCommandDribbling = 0x00000004, RxCommandCRCError = 0x00000002
}
Receive Command Words.
Private Member Functions
void readStart ()
void readFinished (FileSystemMessage *message)
void writeStart ()
void writeFinished (FileSystemMessage *message)
Error getMACAddress (Ethernet::Address *address)
Get MAC address.
Error setMACAddress (Ethernet::Address address)
Set MAC address.
u32 read (Register reg)
Read a SMSC95xx register.
void write (Register reg, u32 value)
Write a SMSC95xx register.
Private Attributes
u32 * m_value
Word aligned temporary value.
Callback< SMSC95xxUSB, FileSystemMessage > * m_readFinished
Callback object for readFinished()
Callback< SMSC95xxUSB, FileSystemMessage > * m_writeFinished
Callback object for writeFinished()
Size m_packetSize
NetworkServer * m_server
SMSC95xx * m_smsc
NetworkQueue::Packet * m_rxPacket
NetworkQueue::Packet * m_txPacket
Static Private Attributes
static const u16 vendorId = 0x0424
vendor ID in the USB device descriptor for this device
static const u16 productId = 0xec00
product ID in the USB device descriptor for this device
Additional Inherited Members
Protected Member Functions inherited from USBDevice
Error getDeviceDescriptor (USBDescriptor::Device *desc, Size size=sizeof(USBDescriptor::Device))
Get device descriptor.
Error getConfigDescriptor (USBDescriptor::Configuration *desc, Size size=sizeof(USBDescriptor::Configuration))
Get configuration descriptor.
Error getInterfaceDescriptor (USBDescriptor::Interface *desc)
Get interface descriptor.
Error getEndpointDescriptor (u8 endpointId, USBDescriptor::Endpoint *desc)
Get endpoint descriptor.
Error setAddress (u8 address)
Set device address.
Error setConfiguration (u8 configId)
Activate a configuration.
Error controlMessage (u8 request, const USBTransfer::Direction direction, const USBTransfer::RequestType type, const USBTransfer::Recipient recipient, u16 value, u16 index, void *buffer, Size size)
Send a control message.
Error transfer (const USBTransfer::Type type, const USBTransfer::Direction direction, Address endpointId, void *buffer, Size size, Size maxPacketSize=0)
Start a synchronous USB transfer.
Error beginTransfer (const USBTransfer::Type type, const USBTransfer::Direction direction, Address endpointId, void *buffer, Size size, Size maxPacketSize=0, CallbackFunction *callback=0)
Start an asynchronous USB transfer.
Error finishTransfer (FileSystemMessage *msg)
Complete asynchronous USB transfer.
Error submit (USBMessage &msg)
Submit a USB transfer to the Host controller.
Protected Attributes inherited from USBDevice
Address m_id
USB device identifier.
USBTransfer::Speed m_speed
USB speed.
int m_transferFile
USB transfer I/O file.
String m_busPath
USB bus path.
USBDescriptor::Device * m_device
USB device descriptor.
USBDescriptor::Configuration * m_config
USB configuration descriptor.
Index< USBDescriptor::Interface > m_interfaces
USB interface descriptors.
Index< USBDescriptor::Endpoint > m_endpoints
USB endpoint descriptors.
Index< USBDescriptor::String > m_strings
USB string descriptor.
Array< u8, 128 > m_endpointsPacketId
Contains endpoint to saved packet id mapping.
Protected Attributes inherited from Device
String m_identifier
Unique identifier for this Device.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
SMSC95xx USB-based Ethernet controller.
Definition at line 39 of file SMSC95xxUSB.h.
Member Enumeration Documentation
HardwareConfigFlags
enum SMSC95xxUSB::HardwareConfigFlags private
HardwareConfig register flags.
Enumerator
BulkIn
MultipleEther
BCE
Definition at line 97 of file SMSC95xxUSB.h.
InterruptStatusFlags
enum SMSC95xxUSB::InterruptStatusFlags private
InterruptStatus register flags.
Enumerator
TransferStop
ReceiveStop
PhyInterrupt
Definition at line 77 of file SMSC95xxUSB.h.
MACControlFlags
enum SMSC95xxUSB::MACControlFlags private
MACControl register flags.
Enumerator
MACTransmit
MACReceive
Definition at line 107 of file SMSC95xxUSB.h.
ReceiveCommand
enum SMSC95xxUSB::ReceiveCommand private
Receive Command Words.
Enumerator
RxCommandFilterFail
RxCommandFrameLength
RxCommandErrorSummary
RxCommandBroadcastFrame
RxCommandLengthError
RxCommandRuntFrame
RxCommandMulticastFrame
RxCommandFrameTooLong
RxCommandFrameCollision
RxCommandFrameType
RxCommandReceiveWatchdog
RxCommandMIIError
RxCommandDribbling
RxCommandCRCError
Definition at line 141 of file SMSC95xxUSB.h.
Register
enum SMSC95xxUSB::Register private
Hardware registers.
Enumerator
DeviceID
InterruptStatus
ReceiveConfig
TransmitConfig
HardwareConfig
ReceiveFIFOInfo
PowerControl
LEDConfig
GPIOConfig
FlowControl
EEPromCommand
EEPromData
BurstCap
GPIOWake
MACControl
MACAddrHigh
MACAddrLow
MIIControl
Definition at line 52 of file SMSC95xxUSB.h.
TransmitCommand
enum SMSC95xxUSB::TransmitCommand private
Transmit Command Words.
Enumerator
TxCommandADataOffset
TxCommandAFirstSeg
TxCommandALastSeg
TxCommandABufSize
TxCommandBChecksum
TxCommandBCRC
TxCommandBPadding
TxCommandBLength
Definition at line 126 of file SMSC95xxUSB.h.
TransmitConfigFlags
enum SMSC95xxUSB::TransmitConfigFlags private
TransmitConfig register flags.
Enumerator
TransmitOn
TransmitOff
TransmitFlush
Definition at line 87 of file SMSC95xxUSB.h.
USBRequest
enum SMSC95xxUSB::USBRequest private
Various vendor-specific USB control message requests.
Enumerator
WriteRegister
ReadRegister
GetStatus
Definition at line 116 of file SMSC95xxUSB.h.
Constructor & Destructor Documentation
SMSC95xxUSB()
SMSC95xxUSB::SMSC95xxUSB (u8 deviceId, const char * usbPath, NetworkServer * server, SMSC95xx * smsc)
Constructor.
Definition at line 29 of file SMSC95xxUSB.cpp.
References DEBUG, NetworkDevice::getTransmitQueue(), m_packetSize, m_readFinished, m_rxPacket, m_server, m_smsc, m_txPacket, m_value, m_writeFinished, readFinished(), NetworkQueue::setHeaderSize(), TransmitCommandSize, and writeFinished().
~SMSC95xxUSB()
SMSC95xxUSB::~SMSC95xxUSB () virtual
Destructor.
Definition at line 50 of file SMSC95xxUSB.cpp.
References DEBUG, and m_value.
Member Function Documentation
getMACAddress()
Error SMSC95xxUSB::getMACAddress (Ethernet::Address * address) private
Get MAC address.
Definition at line 251 of file SMSC95xxUSB.cpp.
References Ethernet::Address::addr, DEBUG, ESUCCESS, MACAddrHigh, MACAddrLow, and read().
initialize()
Error SMSC95xxUSB::initialize () virtual
Initialize the controller.
Returns
Result code
Reimplemented from USBDevice.
Definition at line 57 of file SMSC95xxUSB.cpp.
References Ethernet::Address::addr, BCE, BulkIn, BurstCap, DEBUG, ERROR, ESUCCESS, HardwareConfig, USBDevice::initialize(), MACControl, MACReceive, MACTransmit, MultipleEther, read(), readStart(), setMACAddress(), SMSC9512_DEFAULT_HS_BURST_CAP_SIZE, SMSC9512_HS_USB_PKT_SIZE, TransmitConfig, TransmitOn, and write().
Referenced by SMSC95xx::initialize().
read()
u32 SMSC95xxUSB::read (SMSC95xxUSB::Register reg) private
Read a SMSC95xx register.
Definition at line 280 of file SMSC95xxUSB.cpp.
References USBDevice::controlMessage(), USBTransfer::Device, ERROR, ESUCCESS, USBTransfer::In, m_value, ReadRegister, and USBTransfer::Vendor.
Referenced by getMACAddress(), and initialize().
readFinished()
void SMSC95xxUSB::readFinished (FileSystemMessage * message) private
Definition at line 119 of file SMSC95xxUSB.cpp.
References DEBUG, ERROR, USBDevice::finishTransfer(), NetworkDevice::getReceiveQueue(), ChannelMessage::identifier, m_packetSize, m_rxPacket, m_smsc, FileSystemMessage::offset, NetworkDevice::process(), readStart(), ReceiveCommandSize, NetworkQueue::release(), FileSystemMessage::result, RxCommandFrameLength, and NetworkQueue::Packet::size.
Referenced by SMSC95xxUSB().
readStart()
void SMSC95xxUSB::readStart () private
Definition at line 92 of file SMSC95xxUSB.cpp.
References USBDevice::beginTransfer(), USBTransfer::Bulk, NetworkQueue::Packet::data, DEBUG, ERROR, ESUCCESS, NetworkQueue::get(), NetworkDevice::getReceiveQueue(), USBTransfer::In, USBDevice::m_endpoints, m_packetSize, m_readFinished, m_rxPacket, and m_smsc.
Referenced by initialize(), and readFinished().
setMACAddress()
Error SMSC95xxUSB::setMACAddress (Ethernet::Address address) private
Set MAC address.
Definition at line 267 of file SMSC95xxUSB.cpp.
References Ethernet::Address::addr, DEBUG, ESUCCESS, MACAddrHigh, MACAddrLow, and write().
Referenced by initialize().
transmit()
Error SMSC95xxUSB::transmit (NetworkQueue::Packet * pkt) virtual
Transmit one network packet.
Parameters
pkt Network packet buffer
Definition at line 212 of file SMSC95xxUSB.cpp.
References NetworkQueue::Packet::data, DEBUG, ERANGE, ERROR, NetworkDevice::getTransmitQueue(), m_packetSize, m_smsc, m_txPacket, NetworkQueue::push(), NetworkQueue::Packet::size, TransmitCommandSize, TxCommandAFirstSeg, TxCommandALastSeg, and writeStart().
Referenced by SMSC95xx::transmit().
write()
void SMSC95xxUSB::write (SMSC95xxUSB::Register reg, u32 value) private
Write a SMSC95xx register.
Definition at line 297 of file SMSC95xxUSB.cpp.
References USBDevice::controlMessage(), USBTransfer::Device, ERROR, ESUCCESS, m_value, USBTransfer::Out, USBTransfer::Vendor, and WriteRegister.
Referenced by initialize(), and setMACAddress().
writeFinished()
void SMSC95xxUSB::writeFinished (FileSystemMessage * message) private
Definition at line 191 of file SMSC95xxUSB.cpp.
References DEBUG, ERROR, USBDevice::finishTransfer(), NetworkDevice::getTransmitQueue(), ChannelMessage::identifier, m_smsc, m_txPacket, NetworkQueue::release(), FileSystemMessage::result, and writeStart().
Referenced by SMSC95xxUSB().
writeStart()
void SMSC95xxUSB::writeStart () private
Definition at line 159 of file SMSC95xxUSB.cpp.
References USBDevice::beginTransfer(), USBTransfer::Bulk, CacheClean, NetworkQueue::Packet::data, DEBUG, ERROR, NetworkDevice::getTransmitQueue(), USBDevice::m_endpoints, m_smsc, m_txPacket, m_writeFinished, USBTransfer::Out, NetworkQueue::pop(), SELF, NetworkQueue::Packet::size, and VMCtl().
Referenced by transmit(), and writeFinished().
Field Documentation
m_packetSize
Size SMSC95xxUSB::m_packetSize private
Definition at line 233 of file SMSC95xxUSB.h.
Referenced by readFinished(), readStart(), SMSC95xxUSB(), and transmit().
m_readFinished
Callback<SMSC95xxUSB, FileSystemMessage>* SMSC95xxUSB::m_readFinished private
Callback object for readFinished()
Definition at line 228 of file SMSC95xxUSB.h.
Referenced by readStart(), and SMSC95xxUSB().
m_rxPacket
NetworkQueue::Packet* SMSC95xxUSB::m_rxPacket private
Definition at line 236 of file SMSC95xxUSB.h.
Referenced by readFinished(), readStart(), and SMSC95xxUSB().
m_server
NetworkServer* SMSC95xxUSB::m_server private
Definition at line 234 of file SMSC95xxUSB.h.
Referenced by SMSC95xxUSB().
m_smsc
SMSC95xx* SMSC95xxUSB::m_smsc private
Definition at line 235 of file SMSC95xxUSB.h.
Referenced by readFinished(), readStart(), SMSC95xxUSB(), transmit(), writeFinished(), and writeStart().
m_txPacket
NetworkQueue::Packet* SMSC95xxUSB::m_txPacket private
Definition at line 237 of file SMSC95xxUSB.h.
Referenced by SMSC95xxUSB(), transmit(), writeFinished(), and writeStart().
m_value
u32* SMSC95xxUSB::m_value private
Word aligned temporary value.
Definition at line 225 of file SMSC95xxUSB.h.
Referenced by read(), SMSC95xxUSB(), write(), and ~SMSC95xxUSB().
m_writeFinished
Callback<SMSC95xxUSB, FileSystemMessage>* SMSC95xxUSB::m_writeFinished private
Callback object for writeFinished()
Definition at line 231 of file SMSC95xxUSB.h.
Referenced by SMSC95xxUSB(), and writeStart().
productId
const u16 SMSC95xxUSB::productId = 0xec00 static private
product ID in the USB device descriptor for this device
Definition at line 47 of file SMSC95xxUSB.h.
ReceiveCommandSize
const Size SMSC95xxUSB::ReceiveCommandSize = 4 static
Receive Command Word size.
Definition at line 165 of file SMSC95xxUSB.h.
Referenced by readFinished().
TransmitCommandSize
const Size SMSC95xxUSB::TransmitCommandSize = 8 static
Transmit Command Word size.
Definition at line 162 of file SMSC95xxUSB.h.
Referenced by SMSC95xx::initialize(), SMSC95xxUSB(), and transmit().
vendorId
const u16 SMSC95xxUSB::vendorId = 0x0424 static private
vendor ID in the USB device descriptor for this device
Definition at line 44 of file SMSC95xxUSB.h.
The documentation for this class was generated from the following files:
server/network/smsc95xx/SMSC95xxUSB.h
server/network/smsc95xx/SMSC95xxUSB.cpp