FreeNOS: List< T > Class Template Reference
List< T > Class Template Reference
lib » libstd
Simple linked list template class.
#include <List.h>
Data Structures
class Node
Represents an item on the List.
Public Member Functions
List ()
Class constructor.
List (const List< T > &lst)
Copy constructor.
virtual ~List ()
Class destructor.
void prepend (T t)
Insert an item at the start of the list.
void append (T t)
Insert an item at the end of the list.
virtual int remove (T t)
Remove all items which are equal to the given item.
virtual int remove (Node *node)
Removes the given node from the list.
virtual bool contains (const T t) const
Check whether an element is on the List.
virtual void clear ()
Clears the entire List.
Node * head ()
Get the first Node on the list.
const Node * head () const
Get the first Node on the List (read-only).
Node * tail ()
Get the last Node on the list.
const Node * tail () const
Get the last Node on the List (read-only).
T first ()
Get the first value in the list.
const T first () const
Get the first value as constant.
T last ()
Get the last value on the list.
const T last () const
Get the last value on the list as constant.
virtual const T * get (Size position) const
Get a pointer to the item at the given position.
virtual const T & at (Size position) const
Get a reference to the item at the given position.
virtual bool isEmpty () const
Check if the List is empty.
Size size () const
Get the size of the list.
Size count () const
Get the number of items on the list.
List & operator<< (T t)
Append operator.
bool operator== (const List< T > &lst) const
Comparison operator.
bool operator!= (const List< T > &lst) const
Inequality operator.
Public Member Functions inherited from Sequence< T >
virtual int insert (const T &item)
Adds the given item to the Sequence, if possible.
virtual bool insert (Size position, const T &item)
Inserts the given item at the given position.
virtual void fill (T value)
Fill the Sequence with the given value.
virtual bool removeAt (Size position)
Removes the item at the given position.
virtual int compareTo (const Sequence< T > &s) const
Compare this Sequence to another Sequence.
const T & operator[] (int i) const
Returns the item at the given position in the Sequence.
const T & operator[] (Size i) const
Returns the item at the given position in the Sequence.
T & operator[] (int i)
Returns the item at the given position in the Sequence.
T & operator[] (Size i)
Returns the item at the given position in the Sequence.
Public Member Functions inherited from Container
Container ()
Constructor.
virtual ~Container ()
Destructor.
virtual bool reserve (Size size)
Ensure that at least the given size is available.
virtual bool shrink (Size size)
Shrink the container size by the given amount of items.
virtual Size squeeze ()
Try to minimize the memory required in the Container.
virtual bool resize (Size size)
Change the size of the Container.
Public Member Functions inherited from Comparable< Sequence< T > >
virtual ~Comparable ()
Class destructor.
virtual bool equals (const Sequence< T > &t) const
Test if an object is equal to an other object.
Private Attributes
Node * m_head
Head of the List.
Node * m_tail
Tail of the list.
Size m_count
Number of items currently in the List.
Detailed Description
template<class T>
class List< T >
Simple linked list template class.
Definition at line 36 of file List.h.
Constructor & Destructor Documentation
List() [1/2]
template<class T> List< T >::List () inline
Class constructor.
Definition at line 69 of file List.h.
List() [2/2]
template<class T> List< T >::List (const List< T > & lst) inline
Copy constructor.
Parameters
lst List instance to copy from
Definition at line 81 of file List.h.
~List()
template<class T> virtual List< T >::~List () inline virtual
Class destructor.
Definition at line 94 of file List.h.
Member Function Documentation
append()
template<class T> void List< T >::append (T t) inline
Insert an item at the end of the list.
Parameters
t Item to insert.
Definition at line 140 of file List.h.
Referenced by TestSuite::addTest(), chdir(), ATAController::initialize(), Directory::insert(), List< ATADrive *>::List(), List< ATADrive *>::operator<<(), FileSystemPath::parse(), IntelMP::parseEntry(), FileSystem::pathHandler(), IntelACPI::scanAPIC(), LinnCreate::setExclude(), String::split(), and ProcessShares::~ProcessShares().
at()
template<class T> virtual const T& List< T >::at (Size position) const inline virtual
Get a reference to the item at the given position.
Parameters
position Index in the list.
Returns
Reference to the item at the given position.
Note
Assumes that the item is available.
Implements Sequence< T >.
Definition at line 372 of file List.h.
clear()
template<class T> virtual void List< T >::clear () inline virtual
Clears the entire List.
Reimplemented from Sequence< T >.
Definition at line 239 of file List.h.
Referenced by Directory::clear(), IntelMP::discover(), IntelACPI::discover(), Directory::~Directory(), and FileSystemPath::~FileSystemPath().
contains()
template<class T> virtual bool List< T >::contains (const T t) const inline virtual
Check whether an element is on the List.
Parameters
t The element to find.
Returns
true if the element is on the List, false otherwise.
Reimplemented from Sequence< T >.
Definition at line 225 of file List.h.
Referenced by Associative< String, FileCache * >::compareTo(), HashTable< String, FileCache *>::keys(), List< ATADrive *>::operator!=(), List< ATADrive *>::operator==(), and ProcessShares::~ProcessShares().
count()
template<class T> Size List< T >::count () const inline virtual
Get the number of items on the list.
Returns
The number of items on the List.
Implements Container.
Definition at line 409 of file List.h.
Referenced by CoreServer::bootAll(), CoreServer::discover(), List< ATADrive *>::operator!=(), List< ATADrive *>::operator==(), TAPReporter::reportBegin(), and IPV4::toAddress().
first() [1/2]
template<class T> T List< T >::first () inline
Get the first value in the list.
Returns
First value on the list.
Note
Assumes that the list is not empty.
Definition at line 299 of file List.h.
Referenced by ATAController::read().
first() [2/2]
template<class T> const T List< T >::first () const inline
Get the first value as constant.
Returns
First value on the list.
Note
Assumes that the list is not empty.
Definition at line 311 of file List.h.
get()
template<class T> virtual const T* List< T >::get (Size position) const inline virtual
Get a pointer to the item at the given position.
Parameters
position Index in the list
Returns
Pointer to the item or ZERO if not available.
Implements Sequence< T >.
Definition at line 347 of file List.h.
head() [1/2]
template<class T> Node* List< T >::head () inline
Get the first Node on the list.
Returns
First Node on the List.
Definition at line 261 of file List.h.
Referenced by FileSystemPath::parse().
head() [2/2]
template<class T> const Node* List< T >::head () const inline
Get the first Node on the List (read-only).
Definition at line 269 of file List.h.
isEmpty()
template<class T> virtual bool List< T >::isEmpty () const inline virtual
Check if the List is empty.
Returns
true if empty, false if not.
Reimplemented from Container.
Definition at line 389 of file List.h.
Referenced by ATAController::read().
last() [1/2]
template<class T> T List< T >::last () inline
Get the last value on the list.
Returns
Last value on the list.
Note
Assumes that the list is not empty.
Definition at line 323 of file List.h.
Referenced by FileSystemPath::base(), and ArgumentParser::parse().
last() [2/2]
template<class T> const T List< T >::last () const inline
Get the last value on the list as constant.
Returns
Last value on the list.
Note
Assumes that the list is not empty.
Definition at line 335 of file List.h.
operator!=()
template<class T> bool List< T >::operator!= (const List< T > & lst) const inline
Inequality operator.
Definition at line 441 of file List.h.
operator<<()
template<class T> List& List< T >::operator<< (T t) inline
Append operator.
Definition at line 417 of file List.h.
operator==()
template<class T> bool List< T >::operator== (const List< T > & lst) const inline
Comparison operator.
Definition at line 426 of file List.h.
prepend()
template<class T> void List< T >::prepend (T t) inline
Insert an item at the start of the list.
Parameters
t Data item to te inserted.
Definition at line 111 of file List.h.
remove() [1/2]
template<class T> virtual int List< T >::remove (T t) inline virtual
Remove all items which are equal to the given item.
Parameters
t Item to remove.
single True to remove only one item, false to remove all matching items.
Returns
Number of items removed from the list.
Reimplemented from Sequence< T >.
Definition at line 170 of file List.h.
Referenced by chdir().
remove() [2/2]
template<class T> virtual int List< T >::remove (Node * node) inline virtual
Removes the given node from the list.
Parameters
node The Node to remove.
Returns
True on success, false otherwise
Definition at line 199 of file List.h.
size()
template<class T> Size List< T >::size () const inline virtual
Get the size of the list.
Returns
Size of the list.
Implements Container.
Definition at line 399 of file List.h.
tail() [1/2]
template<class T> Node* List< T >::tail () inline
Get the last Node on the list.
Returns
Last Node on the list.
Definition at line 279 of file List.h.
tail() [2/2]
template<class T> const Node* List< T >::tail () const inline
Get the last Node on the List (read-only).
Definition at line 287 of file List.h.
Field Documentation
m_count
template<class T> Size List< T >::m_count private
Number of items currently in the List.
Definition at line 462 of file List.h.
Referenced by List< ATADrive *>::append(), List< ATADrive *>::clear(), List< ATADrive *>::count(), List< ATADrive *>::get(), List< ATADrive *>::List(), List< ATADrive *>::operator!=(), List< ATADrive *>::operator==(), List< ATADrive *>::prepend(), List< ATADrive *>::remove(), and List< ATADrive *>::size().
m_head
template<class T> Node* List< T >::m_head private
Head of the List.
Definition at line 456 of file List.h.
Referenced by List< ATADrive *>::append(), List< ATADrive *>::at(), List< ATADrive *>::clear(), List< ATADrive *>::contains(), List< ATADrive *>::first(), List< ATADrive *>::get(), List< ATADrive *>::head(), List< ATADrive *>::isEmpty(), List< ATADrive *>::List(), List< ATADrive *>::operator!=(), List< ATADrive *>::operator==(), List< ATADrive *>::prepend(), List< ATADrive *>::remove(), and List< ATADrive *>::~List().
m_tail
template<class T> Node* List< T >::m_tail private
Tail of the list.
Definition at line 459 of file List.h.
Referenced by List< ATADrive *>::append(), List< ATADrive *>::clear(), List< ATADrive *>::last(), List< ATADrive *>::List(), List< ATADrive *>::prepend(), List< ATADrive *>::remove(), and List< ATADrive *>::tail().
The documentation for this class was generated from the following file:
lib/libstd/List.h