FreeNOS: LinnCreate Class Reference
LinnCreate Class Reference
server » LinnFS » linncreate
Class for creating new Linnenbank FileSystems.
#include <LinnCreate.h>
Public Member Functions
LinnCreate ()
Class constructor.
int create (Size blockSize, Size blockNum, Size inodeNum)
Creates the LinnFS FileSystem.
void setProgram (char *progName)
Set the program name we are invoked with.
void setImage (char *imageName)
Set the output image file name.
void setInput (char *inputName)
Set the input directory name.
void setExclude (char *pattern)
Exclude files matching the given pattern from the image.
void setVerbose (bool newVerbose)
Output verbose messages during the construction.
Private Member Functions
LinnInode * createInode (le32 inodeNum, FileType type, FileModes mode, UserID uid=ZERO, GroupID gid=ZERO)
Creates an empty LinnInode.
le32 createInode (char *inputFile, struct stat *st)
Copies a local file contents into an LinnInode.
void insertEntry (le32 dirInode, le32 entryInode, const char *name, FileType type)
Inserts an LinnDirectoryEntry to the given directory inode.
void insertDirectory (char *inputFile, le32 inodeNum, le32 parentNum)
Inserts the given directory and it's childs to the filesystem image.
void insertFile (char *inputFile, LinnInode *inode, struct stat *st)
Inserts the contents of a local file into an LinnInode.
void insertIndirect (le32 *ptr, le32 blockNumber, le32 blockValue, Size depth)
Inserts an indirect block address.
int writeImage ()
Writes the final image to disk.
Private Attributes
char * prog
Program name we are invoked with.
char * image
Path to the output image.
char * input
Path to the input directory.
bool verbose
Output verbose messages.
List< String * > excludes
List of file patterns to ignore.
LinnSuperBlock * super
Pointer to the superblock.
u8 * blocks
Array of blocks available in the filesystem.
Detailed Description
Class for creating new Linnenbank FileSystems.
Definition at line 95 of file LinnCreate.h.
Constructor & Destructor Documentation
LinnCreate()
LinnCreate::LinnCreate ()
Class constructor.
Definition at line 43 of file LinnCreate.cpp.
References image, input, prog, super, verbose, and ZERO.
Member Function Documentation
create()
int LinnCreate::create (Size blockSize, Size blockNum, Size inodeNum)
Creates the LinnFS FileSystem.
Parameters
blockSize The size of each block in the new filesystem.
blockNum The maximum number of blocks in the new filesystem.
inodeNum Number of inodes to allocate.
Returns
EXIT_SUCCESS if successful and EXIT_FAILURE otherwise.
Definition at line 376 of file LinnCreate.cpp.
References assert, LinnGroup::blockMap, BLOCKPTR, BLOCKS, blocks, LinnSuperBlock::blocksCount, LinnSuperBlock::blockSize, LinnSuperBlock::blocksPerGroup, createInode(), LinnSuperBlock::creationTime, DirectoryFile, LinnSuperBlock::freeBlocksCount, LinnGroup::freeBlocksCount, LinnSuperBlock::freeInodesCount, LinnGroup::freeInodesCount, GroupR, GroupRX, LinnSuperBlock::groupsTable, image, LinnGroup::inodeMap, LinnSuperBlock::inodesCount, LinnSuperBlock::inodesPerGroup, LinnGroup::inodeTable, input, insertDirectory(), LinnSuperBlock::lastCheck, LINN_CREATE_BLOCKS_PER_GROUP, LINN_GROUP_COUNT, LINN_GROUP_NUM_BLOCKMAP, LINN_GROUP_NUM_INODEMAP, LINN_GROUP_NUM_INODETAB, LINN_INODE_BAD, LINN_INODE_JOURNAL, LINN_INODE_LOADER, LINN_INODE_ROOT, LINN_SUPER_MAGIC0, LINN_SUPER_MAGIC1, LINN_SUPER_MAJOR, LINN_SUPER_MINOR, LINN_SUPER_OFFSET, LINN_SUPER_VALID, LinnSuperBlock::magic0, LinnSuperBlock::magic1, LinnSuperBlock::majorRevision, memset(), LinnSuperBlock::minorRevision, LinnSuperBlock::mountCount, LinnSuperBlock::mountTime, OtherR, OtherRX, OwnerRW, OwnerRWX, prog, RegularFile, BitArray::set(), BitArray::setArray(), LinnSuperBlock::state, super, writeImage(), and ZERO.
Referenced by main().
createInode() [1/2]
LinnInode * LinnCreate::createInode (le32 inodeNum, FileType type, FileModes mode, UserID uid = ZERO, GroupID gid = ZERO) private
Creates an empty LinnInode.
Parameters
inodeNum Inode number.
type Type of file.
mode Access permissions.
uid User identity.
gid Group identity.
Returns
LinnInode pointer.
Definition at line 52 of file LinnCreate.cpp.
References LinnInode::accessTime, BLOCKPTR, LinnInode::changeTime, LinnInode::createTime, LinnSuperBlock::freeInodesCount, LinnGroup::freeInodesCount, LinnInode::gid, LinnSuperBlock::groupsTable, LinnGroup::inodeMap, LinnSuperBlock::inodesPerGroup, LinnGroup::inodeTable, LinnInode::links, LinnInode::mode, LinnInode::modifyTime, BitArray::set(), BitArray::setArray(), LinnInode::size, super, LinnInode::type, LinnInode::uid, and ZERO.
Referenced by create(), createInode(), and insertDirectory().
createInode() [2/2]
le32 LinnCreate::createInode (char * inputFile, struct stat * st) private
Copies a local file contents into an LinnInode.
Parameters
inputFile Path to the local file to insert.
st POSIX stat pointer for the local file.
Returns
Inode number of the inserted file.
Definition at line 92 of file LinnCreate.cpp.
References BLOCKPTR, createInode(), exit(), EXIT_FAILURE, FILEMODE_FROM_ST, FILETYPE_FROM_ST, LinnGroup::freeInodesCount, LinnSuperBlock::groupsTable, LinnGroup::inodeMap, LinnSuperBlock::inodesPerGroup, insertFile(), LINN_GROUP_COUNT, printf(), prog, S_ISREG, BitArray::setArray(), BitArray::setNext(), LinnInode::size, stat::st_gid, stat::st_mode, stat::st_uid, super, verbose, and ZERO.
insertDirectory()
void LinnCreate::insertDirectory (char * inputFile, le32 inodeNum, le32 parentNum) private
Inserts the given directory and it's childs to the filesystem image.
Parameters
inputFile Path to a local directory.
inodeNum Inode number for the input directory.
parentNum Inode number of our parent.
Note
This function is recursive.
Definition at line 308 of file LinnCreate.cpp.
References closedir(), createInode(), dirent::d_name, DirectoryFile, errno, excludes, exit(), EXIT_FAILURE, FILETYPE_FROM_ST, ListIterator< T >::hasCurrent(), insertEntry(), String::match(), NULL, opendir(), printf(), prog, readdir(), S_ISDIR, snprintf(), stat::st_mode, stat(), and strerror().
Referenced by create().
insertEntry()
void LinnCreate::insertEntry (le32 dirInode, le32 entryInode, const char * name, FileType type) private
Inserts an LinnDirectoryEntry to the given directory inode.
Parameters
dirInode Inode number of the directory.
entryInode Inode number of the entry to create.
name Unique name (inside this directory) for the entry.
type FileType for the entry to insert.
Definition at line 257 of file LinnCreate.cpp.
References BLOCK, LinnInode::block, BLOCKPTR, LinnSuperBlock::blockSize, exit(), EXIT_FAILURE, LinnSuperBlock::groupsTable, LinnDirectoryEntry::inode, LinnSuperBlock::inodesPerGroup, LinnGroup::inodeTable, LINN_DIRENT_NAME_LEN, LINN_INODE_DIR_BLOCKS, LinnDirectoryEntry::name, printf(), prog, LinnInode::size, strncpy(), super, LinnDirectoryEntry::type, and ZERO.
Referenced by insertDirectory().
insertFile()
void LinnCreate::insertFile (char * inputFile, LinnInode * inode, struct stat * st) private
Inserts the contents of a local file into an LinnInode.
Parameters
inputFile Path to the local file.
inode Pointer to the inode to fill.
st POSIX stats structure of inputFile.
Definition at line 179 of file LinnCreate.cpp.
References BLOCK, LinnInode::block, BLOCKPTR, LinnSuperBlock::blockSize, close(), errno, exit(), EXIT_FAILURE, insertIndirect(), LINN_INODE_DIND_BLOCKS, LINN_INODE_DIR_BLOCKS, LINN_INODE_IND_BLOCKS, LINN_INODE_NUM_BLOCKS, LINN_INODE_TIND_BLOCKS, LINN_SUPER_NUM_PTRS, O_RDONLY, open(), printf(), prog, read(), LinnInode::size, strerror(), and super.
Referenced by createInode().
insertIndirect()
void LinnCreate::insertIndirect (le32 * ptr, le32 blockNumber, le32 blockValue, Size depth) private
Inserts an indirect block address.
Parameters
ptr Buffer containing block addresses.
blockNumber Block index number to insert in the buffer, minus LINN_INODE_DIR_BLOCKS
blockValue The block address to insert indirectly.
depth Level of indirection.
Definition at line 146 of file LinnCreate.cpp.
References BLOCK, BLOCKPTR, LINN_SUPER_NUM_PTRS, and super.
Referenced by insertFile().
setExclude()
void LinnCreate::setExclude (char * pattern)
Exclude files matching the given pattern from the image.
Parameters
pattern Pattern to match against.
Definition at line 498 of file LinnCreate.cpp.
References List< T >::append(), and excludes.
Referenced by main().
setImage()
void LinnCreate::setImage (char * imageName)
Set the output image file name.
Parameters
imageName Image name to use.
Definition at line 488 of file LinnCreate.cpp.
References image.
Referenced by main().
setInput()
void LinnCreate::setInput (char * inputName)
Set the input directory name.
Parameters
inputName Input directory to use.
Definition at line 493 of file LinnCreate.cpp.
References input.
Referenced by main().
setProgram()
void LinnCreate::setProgram (char * progName)
Set the program name we are invoked with.
Parameters
progName program name.
Definition at line 483 of file LinnCreate.cpp.
References prog.
Referenced by main().
setVerbose()
void LinnCreate::setVerbose (bool newVerbose)
Output verbose messages during the construction.
Parameters
newVerbose True to turn on, false to turn off verbose messages.
Definition at line 503 of file LinnCreate.cpp.
References verbose.
Referenced by main().
writeImage()
int LinnCreate::writeImage () private
Writes the final image to disk.
Returns
EXIT_SUCCESS if successful and EXIT_FAILURE otherwise.
Definition at line 457 of file LinnCreate.cpp.
References blocks, LinnSuperBlock::blocksCount, LinnSuperBlock::blockSize, errno, EXIT_FAILURE, EXIT_SUCCESS, fclose(), fopen(), LinnSuperBlock::freeBlocksCount, image, NULL, printf(), prog, strerror(), and super.
Referenced by create().
Field Documentation
blocks
u8* LinnCreate::blocks private
Array of blocks available in the filesystem.
Definition at line 248 of file LinnCreate.h.
Referenced by create(), and writeImage().
excludes
List<String *> LinnCreate::excludes private
List of file patterns to ignore.
Definition at line 242 of file LinnCreate.h.
Referenced by insertDirectory(), and setExclude().
image
char* LinnCreate::image private
Path to the output image.
Definition at line 233 of file LinnCreate.h.
Referenced by create(), LinnCreate(), setImage(), and writeImage().
input
char* LinnCreate::input private
Path to the input directory.
Definition at line 236 of file LinnCreate.h.
Referenced by create(), LinnCreate(), and setInput().
prog
char* LinnCreate::prog private
Program name we are invoked with.
Definition at line 230 of file LinnCreate.h.
Referenced by create(), createInode(), insertDirectory(), insertEntry(), insertFile(), LinnCreate(), setProgram(), and writeImage().
super
LinnSuperBlock* LinnCreate::super private
Pointer to the superblock.
Definition at line 245 of file LinnCreate.h.
Referenced by create(), createInode(), insertEntry(), insertFile(), insertIndirect(), LinnCreate(), and writeImage().
verbose
bool LinnCreate::verbose private
Output verbose messages.
Definition at line 239 of file LinnCreate.h.
Referenced by createInode(), LinnCreate(), and setVerbose().
The documentation for this class was generated from the following files:
server/filesystem/linn/LinnCreate.h
server/filesystem/linn/LinnCreate.cpp