FreeNOS: SysInfo Class Reference
SysInfo Class Reference
bin
Print global system information.
#include <SysInfo.h>
Public Member Functions
SysInfo (int argc, char **argv)
Constructor.
virtual ~SysInfo ()
Destructor.
virtual Result exec ()
Execute the application.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
Print global system information.
Definition at line 31 of file SysInfo.h.
Constructor & Destructor Documentation
SysInfo()
SysInfo::SysInfo (int argc, char ** argv)
Constructor.
Parameters
argc Argument count
argv Argument values
Definition at line 28 of file SysInfo.cpp.
References Application::parser(), and ArgumentParser::setDescription().
~SysInfo()
SysInfo::~SysInfo () virtual
Destructor.
Definition at line 34 of file SysInfo.cpp.
Member Function Documentation
exec()
SysInfo::Result SysInfo::exec () virtual
Execute the application.
Returns
Result code
Implements Application.
Definition at line 38 of file SysInfo.cpp.
References FileSystemMessage::action, CORESRV_PID, FileSystemMessage::from, gettimeofday(), InfoTimer, Singleton< ChannelClient >::instance, SystemInformation::memoryAvail, SystemInformation::memorySize, printf(), ProcessCtl(), ReadFile, ChannelMessage::Request, SELF, FileSystemMessage::size, Application::Success, ChannelClient::syncSendReceive(), timeval::tv_sec, timeval::tv_usec, and ChannelMessage::type.
The documentation for this class was generated from the following files:
bin/sysinfo/SysInfo.h
bin/sysinfo/SysInfo.cpp