FreeNOS: EthernetAddress Class Reference
EthernetAddress Class Reference
lib » libnet
Ethernet address file.
#include <EthernetAddress.h>
Public Member Functions
EthernetAddress (Ethernet *eth)
Constructor.
virtual ~EthernetAddress ()
Destructor.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read Ethernet address.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Set new Ethernet address.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Attributes
Ethernet * m_eth
Ethernet object pointer.
Additional Inherited Members
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
Ethernet address file.
Definition at line 36 of file EthernetAddress.h.
Constructor & Destructor Documentation
EthernetAddress()
EthernetAddress::EthernetAddress (Ethernet * eth)
Constructor.
Definition at line 21 of file EthernetAddress.cpp.
References m_eth.
~EthernetAddress()
EthernetAddress::~EthernetAddress () virtual
Destructor.
Definition at line 26 of file EthernetAddress.cpp.
Member Function Documentation
read()
Error EthernetAddress::read (IOBuffer & buffer, Size size, Size offset) virtual
Read Ethernet address.
Parameters
buffer Input/Output buffer to output bytes to.
size Number of bytes to read, at maximum.
offset Offset inside the file to start reading.
Returns
Number of bytes read on success, Error on failure.
Reimplemented from File.
Definition at line 30 of file EthernetAddress.cpp.
References Ethernet::getAddress(), String::length(), m_eth, Ethernet::toString(), and IOBuffer::write().
write()
Error EthernetAddress::write (IOBuffer & buffer, Size size, Size offset) virtual
Set new Ethernet address.
Parameters
buffer Input/Output buffer to input bytes from.
size Number of bytes to write, at maximum.
offset Offset inside the file to start writing.
Returns
Number of bytes written on success, Error on failure.
Reimplemented from File.
Definition at line 44 of file EthernetAddress.cpp.
References ENOTSUP.
Field Documentation
m_eth
Ethernet* EthernetAddress::m_eth private
Ethernet object pointer.
Definition at line 73 of file EthernetAddress.h.
Referenced by EthernetAddress(), and read().
The documentation for this class was generated from the following files:
lib/libnet/EthernetAddress.h
lib/libnet/EthernetAddress.cpp