FreeNOS: BitAllocator Class Reference
BitAllocator Class Reference
lib » liballoc
Bit memory allocator.
#include <BitAllocator.h>
Public Member Functions
BitAllocator (Memory::Range range, Size chunkSize)
Constructor function.
Size chunkSize () const
Get chunk size.
virtual Size size () const
Get total size.
virtual Size available () const
Get available memory.
Address base () const
Get base memory address.
BitArray * getBitArray ()
Get allocation BitArray.
virtual Result allocate (Size *size, Address *addr, Size align=ZERO)
Allocate memory.
Result allocate (Size *size, Address *addr, Size align=ZERO, Address allocStart=0)
Allocate memory.
Result allocate (Address addr)
Allocate address.
bool isAllocated (Address page) const
Check if a chunk is allocated.
virtual Result release (Address chunk)
Release memory chunk.
Public Member Functions inherited from Allocator
Allocator ()
Class constructor.
virtual ~Allocator ()
Class destructor.
void setParent (Allocator *parent)
Set parent allocator.
Result setAlignment (Size size)
Set allocation alignment.
Result setBase (Address addr)
Set allocation base.
Private Attributes
BitArray m_array
Marks which chunks are (un)used.
Address m_base
Start of memory region.
Size m_chunkSize
Size of each chunk.
Additional Inherited Members
Public Types inherited from Allocator
enum Result {
Success = 0, InvalidAddress, InvalidSize, InvalidAlignment,
OutOfMemory
}
Allocation results.
Static Public Member Functions inherited from Allocator
static void setDefault (Allocator *alloc)
Makes the given Allocator the default.
static Allocator * getDefault ()
Retrieve the currently default Allocator.
Protected Member Functions inherited from Allocator
Address aligned (Address addr, Size boundary) const
Align memory address.
Protected Attributes inherited from Allocator
Allocator * m_parent
Our parent Allocator, if any.
Size m_alignment
Allocation memory alignment.
Address m_base
Allocation base address.
Detailed Description
Bit memory allocator.
Allocates memory by using a BitArray. All memory is divided in same sized parts called chunks. 1 in the BitArray means the chunk is used, 0 means unused.
Definition at line 41 of file BitAllocator.h.
Constructor & Destructor Documentation
BitAllocator()
BitAllocator::BitAllocator (Memory::Range range, Size chunkSize)
Constructor function.
Parameters
range Contigeous range of memory to manage.
chunkSize Total memory will be divided into chunks.
Definition at line 20 of file BitAllocator.cpp.
Member Function Documentation
allocate() [1/3]
Allocator::Result BitAllocator::allocate (Size * size, Address * addr, Size align = ZERO) virtual
Allocate memory.
Parameters
size Size of memory to allocate.
addr Address allocated.
align Alignment of the required memory or use ZERO for chunksize. Must be a multiple of the chunksize.
Returns
Result value.
Implements Allocator.
Definition at line 53 of file BitAllocator.cpp.
Referenced by SplitAllocator::allocate(), SplitAllocator::allocateHigh(), and SplitAllocator::allocateLow().
allocate() [2/3]
Allocator::Result BitAllocator::allocate (Size * size, Address * addr, Size align = ZERO, Address allocStart = 0)
Allocate memory.
Parameters
size Size of memory to allocate.
addr Address allocated.
align Alignment of the required memory or use ZERO for chunksize. Must be a multiple of the chunksize.
allocStart Allocation address to start searching at.
Returns
Result value.
Definition at line 60 of file BitAllocator.cpp.
References Allocator::InvalidAlignment, m_array, m_base, m_chunkSize, Allocator::OutOfMemory, BitArray::setNext(), BitArray::Success, and Allocator::Success.
allocate() [3/3]
Allocator::Result BitAllocator::allocate (Address addr)
Allocate address.
Parameters
addr Allocate a specific address.
Returns
Result value.
Definition at line 87 of file BitAllocator.cpp.
References Allocator::InvalidAddress, isAllocated(), m_array, m_base, m_chunkSize, BitArray::set(), and Allocator::Success.
available()
Size BitAllocator::available () const virtual
Get available memory.
Returns
Available memory.
Implements Allocator.
Definition at line 38 of file BitAllocator.cpp.
References BitArray::count(), m_array, and m_chunkSize.
Referenced by SplitAllocator::available().
base()
Address BitAllocator::base () const
Get base memory address.
Definition at line 43 of file BitAllocator.cpp.
References m_base.
Referenced by SplitAllocator::allocateHigh().
chunkSize()
Size BitAllocator::chunkSize () const
Get chunk size.
Returns
Chunk size.
Definition at line 28 of file BitAllocator.cpp.
References m_chunkSize.
getBitArray()
BitArray * BitAllocator::getBitArray ()
Get allocation BitArray.
Returns
BitArray object pointer.
Definition at line 48 of file BitAllocator.cpp.
References m_array.
isAllocated()
bool BitAllocator::isAllocated (Address page) const
Check if a chunk is allocated.
Returns
True if allocated, false otherwise.
Definition at line 96 of file BitAllocator.cpp.
References BitArray::isSet(), m_array, m_base, and m_chunkSize.
Referenced by allocate().
release()
Allocator::Result BitAllocator::release (Address chunk) virtual
Release memory chunk.
Parameters
chunk The memory chunk to release.
Returns
Result value.
Implements Allocator.
Definition at line 104 of file BitAllocator.cpp.
References Allocator::InvalidAddress, m_array, m_base, m_chunkSize, Allocator::Success, and BitArray::unset().
Referenced by SplitAllocator::release().
size()
Size BitAllocator::size () const virtual
Get total size.
Returns
Total size.
Implements Allocator.
Definition at line 33 of file BitAllocator.cpp.
References m_array, m_chunkSize, and BitArray::size().
Referenced by SplitAllocator::size().
Field Documentation
m_array
BitArray BitAllocator::m_array private
Marks which chunks are (un)used.
Definition at line 140 of file BitAllocator.h.
Referenced by allocate(), available(), getBitArray(), isAllocated(), release(), and size().
m_base
Address BitAllocator::m_base private
Start of memory region.
Definition at line 143 of file BitAllocator.h.
Referenced by allocate(), base(), isAllocated(), and release().
m_chunkSize
Size BitAllocator::m_chunkSize private
Size of each chunk.
Definition at line 146 of file BitAllocator.h.
Referenced by allocate(), available(), chunkSize(), isAllocated(), release(), and size().
The documentation for this class was generated from the following files:
lib/liballoc/BitAllocator.h
lib/liballoc/BitAllocator.cpp