FreeNOS: UDPFactory Class Reference
UDPFactory Class Reference
lib » libnet
User Datagram Protocol (UDP).
#include <UDPFactory.h>
Public Member Functions
UDPFactory (UDP *udp)
Constructor.
virtual ~UDPFactory ()
Destructor.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Receive UDP socket information.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Attributes
UDP * m_udp
UDP protocol instance.
Additional Inherited Members
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
User Datagram Protocol (UDP).
The UDP factory creates new sockets for applications.
Definition at line 38 of file UDPFactory.h.
Constructor & Destructor Documentation
UDPFactory()
UDPFactory::UDPFactory (UDP * udp)
Constructor.
Definition at line 22 of file UDPFactory.cpp.
References m_udp.
~UDPFactory()
UDPFactory::~UDPFactory () virtual
Destructor.
Definition at line 27 of file UDPFactory.cpp.
Member Function Documentation
read()
Error UDPFactory::read (IOBuffer & buffer, Size size, Size offset) virtual
Receive UDP socket information.
Parameters
buffer Input/Output buffer to output bytes to.
size Number of bytes to read, at maximum.
offset Offset inside the file to start reading.
Returns
Number of bytes read on success, Error on failure.
Reimplemented from File.
Definition at line 31 of file UDPFactory.cpp.
References UDP::createSocket(), DEBUG, EIO, String::length(), m_udp, and IOBuffer::write().
Field Documentation
m_udp
UDP* UDPFactory::m_udp private
UDP protocol instance.
Definition at line 66 of file UDPFactory.h.
Referenced by read(), and UDPFactory().
The documentation for this class was generated from the following files:
lib/libnet/UDPFactory.h
lib/libnet/UDPFactory.cpp