FreeNOS: TestInt< T > Class Template Reference
TestInt< T > Class Template Reference
lib » libtest
Generate test data for integers.
#include <TestInt.h>
Public Member Functions
TestInt (T min, T max)
Constructor.
virtual T random (Size count=1)
Get random test value(s).
virtual T unique (Size count=1)
Get unique random test value(s).
template<>
int random (Size count)
Get random test value(s).
template<>
int unique (Size count)
Get unique random test value(s).
template<>
uint random (Size count)
Get random test value(s).
template<>
uint unique (Size count)
Get unique random test value(s).
Public Member Functions inherited from TestData< T >
TestData ()
Constructor.
virtual ~TestData ()
Destructor.
void seed ()
Initialize the random number generator.
Size count () const
The number of generated values.
T & get (Size index)
Retrieve previously random generated test data by index.
T & operator[] (Size index)
Retrieve previously random generated test data by index.
Private Attributes
T m_max
Maximum value.
T m_min
Minimum value.
Additional Inherited Members
Protected Attributes inherited from TestData< T >
Vector< T > m_values
Vector with generated values.
Detailed Description
template<class T>
class TestInt< T >
Generate test data for integers.
Definition at line 34 of file TestInt.h.
Constructor & Destructor Documentation
TestInt()
template<class T> TestInt< T >::TestInt (T min, T max) inline
Constructor.
Definition at line 41 of file TestInt.h.
References TestData< T >::count(), TestInt< T >::m_max, TestInt< T >::m_min, TestInt< T >::random(), and TestInt< T >::unique().
Member Function Documentation
random() [1/3]
template<class T> virtual T TestInt< T >::random (Size count = 1) virtual
Get random test value(s).
Parameters
count Number or values to generate.
Returns
The last generated T value.
Implements TestData< T >.
Referenced by TestInt< T >::random(), TestChar< T >::random(), TestInt< T >::TestInt(), TestInt< T >::unique(), and TestChar< T >::unique().
random() [2/3]
template<> int TestInt< int >::random (Size count) virtual
Get random test value(s).
Parameters
count Number or values to generate.
Returns
The last generated T value.
Implements TestData< T >.
Definition at line 74 of file TestInt.h.
References TestInt< T >::m_max, TestInt< T >::m_min, TestData< T >::m_values, and TestInt< T >::random().
random() [3/3]
template<> uint TestInt< uint >::random (Size count) virtual
Get random test value(s).
Parameters
count Number or values to generate.
Returns
The last generated T value.
Implements TestData< T >.
Definition at line 116 of file TestInt.h.
References TestInt< T >::m_max, TestInt< T >::m_min, TestData< T >::m_values, and TestInt< T >::random().
unique() [1/3]
template<class T> virtual T TestInt< T >::unique (Size count = 1) virtual
Get unique random test value(s).
Parameters
count Number of unique values to generate.
Returns
The last generated T value.
Implements TestData< T >.
Referenced by TestInt< T >::TestInt().
unique() [2/3]
template<> int TestInt< int >::unique (Size count) virtual
Get unique random test value(s).
Parameters
count Number of unique values to generate.
Returns
The last generated T value.
Implements TestData< T >.
Definition at line 91 of file TestInt.h.
References TestInt< T >::m_min, TestData< T >::m_values, and TestInt< T >::random().
unique() [3/3]
template<> uint TestInt< uint >::unique (Size count) virtual
Get unique random test value(s).
Parameters
count Number of unique values to generate.
Returns
The last generated T value.
Implements TestData< T >.
Definition at line 133 of file TestInt.h.
References TestData< T >::count(), TestInt< T >::m_min, TestData< T >::m_values, and TestInt< T >::random().
Field Documentation
m_max
template<class T> T TestInt< T >::m_max private
Maximum value.
Definition at line 68 of file TestInt.h.
Referenced by TestInt< T >::random(), and TestInt< T >::TestInt().
m_min
template<class T> T TestInt< T >::m_min private
Minimum value.
Definition at line 71 of file TestInt.h.
Referenced by TestInt< T >::random(), TestInt< T >::TestInt(), and TestInt< T >::unique().
The documentation for this class was generated from the following file:
lib/libtest/TestInt.h