FreeNOS: PL011 Class Reference
PL011 Class Reference
server » serial
The PL011 is a commonly available UART device frequently found in ARM systems.
#include <PL011.h>
Public Member Functions
PL011 (u32 irq)
Constructor.
virtual Error initialize ()
Initializes the i8250 serial UART.
virtual Error interrupt (Size vector)
Called when an interrupt has been triggered for this device.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read bytes from the i8250.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the device.
Public Member Functions inherited from Device
Device (FileType type)
Constructor.
virtual ~Device ()
Destructor.
virtual const String & getIdentifier () const
Get unique device identifier.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Types
enum {
GPIO_BASE = 0x200000, GPPUD = (0x94), GPPUDCLK0 = (0x98), PL011_BASE = (0x1000),
PL011_DR = (PL011_BASE + 0x00), PL011_RSRECR = (PL011_BASE + 0x04), PL011_FR = (PL011_BASE + 0x18), PL011_FR_RXFE = (1 << 4),
PL011_FR_TXFE = (1 << 7), PL011_ILPR = (PL011_BASE + 0x20), PL011_IBRD = (PL011_BASE + 0x24), PL011_FBRD = (PL011_BASE + 0x28),
PL011_LCRH = (PL011_BASE + 0x2C), PL011_LCRH_WLEN_8BIT = (0b11<<5), PL011_CR = (PL011_BASE + 0x30), PL011_IFLS = (PL011_BASE + 0x34),
PL011_IMSC = (PL011_BASE + 0x38), PL011_IMSC_RXIM = (1 << 4), PL011_IMSC_TXIM = (1 << 5), PL011_RIS = (PL011_BASE + 0x3C),
PL011_MIS = (PL011_BASE + 0x40), PL011_MIS_RXMIS = (1 << 4), PL011_MIS_TXMIS = (1 << 5), PL011_ICR = (PL011_BASE + 0x44),
PL011_ICR_TXIC = (1 << 5), PL011_ICR_RXIC = (1 << 4), PL011_DMACR = (PL011_BASE + 0x48), PL011_ITCR = (PL011_BASE + 0x80),
PL011_ITIP = (PL011_BASE + 0x84), PL011_ITOP = (PL011_BASE + 0x88), PL011_TDR = (PL011_BASE + 0x8C)
}
Private Member Functions
void delay (s32 count)
Private Attributes
u32 m_irq
interrupt vector
Arch::IO m_io
I/O instance.
Additional Inherited Members
Protected Attributes inherited from Device
String m_identifier
Unique identifier for this Device.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
The PL011 is a commonly available UART device frequently found in ARM systems.
See also
ARM
Definition at line 41 of file PL011.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
GPIO_BASE
GPPUD
GPPUDCLK0
PL011_BASE
PL011_DR
PL011_RSRECR
PL011_FR
PL011_FR_RXFE
PL011_FR_TXFE
PL011_ILPR
PL011_IBRD
PL011_FBRD
PL011_LCRH
PL011_LCRH_WLEN_8BIT
PL011_CR
PL011_IFLS
PL011_IMSC
PL011_IMSC_RXIM
PL011_IMSC_TXIM
PL011_RIS
PL011_MIS
PL011_MIS_RXMIS
PL011_MIS_TXMIS
PL011_ICR
PL011_ICR_TXIC
PL011_ICR_RXIC
PL011_DMACR
PL011_ITCR
PL011_ITIP
PL011_ITOP
PL011_TDR
Definition at line 90 of file PL011.h.
Constructor & Destructor Documentation
PL011()
PL011::PL011 (u32 irq)
Constructor.
Definition at line 22 of file PL011.cpp.
References Device::m_identifier, and m_irq.
Member Function Documentation
delay()
void PL011::delay (s32 count) private
Definition at line 131 of file PL011.cpp.
Referenced by initialize().
initialize()
Error PL011::initialize () virtual
Initializes the i8250 serial UART.
Returns
Error status code.
Reimplemented from Device.
Definition at line 29 of file PL011.cpp.
References delay(), Memory::Device, DisableIRQ, EINVAL, GPIO_BASE, GPPUD, GPPUDCLK0, m_io, IO::map(), PAGESIZE, PL011_CR, PL011_FBRD, PL011_IBRD, PL011_ICR, PL011_IMSC, PL011_IMSC_RXIM, PL011_LCRH, PL011_LCRH_WLEN_8BIT, ProcessCtl(), Memory::Readable, SELF, IO::Success, Memory::User, Memory::Writable, and ARMIO::write().
interrupt()
Error PL011::interrupt (Size vector) virtual
Called when an interrupt has been triggered for this device.
Parameters
vector Vector number of the interrupt.
Returns
Error result code.
Reimplemented from Device.
Definition at line 74 of file PL011.cpp.
References EnableIRQ, ESUCCESS, m_io, m_irq, PL011_ICR, PL011_ICR_RXIC, PL011_ICR_TXIC, PL011_MIS, PL011_MIS_RXMIS, PL011_MIS_TXMIS, ProcessCtl(), ARMIO::read(), SELF, and ARMIO::write().
read()
Error PL011::read (IOBuffer & buffer, Size size, Size offset) virtual
Read bytes from the i8250.
Parameters
buffer Buffer to save the read bytes.
size Number of bytes to read.
offset Unused.
Returns
Number of bytes on success and ZERO on failure.
Reimplemented from File.
Definition at line 91 of file PL011.cpp.
References IOBuffer::bufferedWrite(), EAGAIN, IOBuffer::getCount(), m_io, PL011_DR, PL011_FR, PL011_FR_RXFE, PL011_ICR, PL011_ICR_RXIC, PL011_MIS, PL011_MIS_RXMIS, ARMIO::read(), and ARMIO::write().
write()
Error PL011::write (IOBuffer & buffer, Size size, Size offset) virtual
Write bytes to the device.
Parameters
buffer Buffer containing bytes to write.
size Number of bytes to write.
offset Unused.
Returns
Number of bytes on success and ZERO on failure.
Reimplemented from File.
Definition at line 111 of file PL011.cpp.
References EAGAIN, m_io, PL011_DR, PL011_FR, PL011_FR_TXFE, PL011_ICR, PL011_ICR_TXIC, PL011_MIS, PL011_MIS_TXMIS, ARMIO::read(), and ARMIO::write().
Field Documentation
m_io
Arch::IO PL011::m_io private
I/O instance.
Definition at line 156 of file PL011.h.
Referenced by initialize(), interrupt(), read(), and write().
m_irq
u32 PL011::m_irq private
interrupt vector
Definition at line 153 of file PL011.h.
Referenced by interrupt(), and PL011().
The documentation for this class was generated from the following files:
server/serial/PL011.h
server/serial/PL011.cpp