FreeNOS: ArgumentContainer Class Reference
ArgumentContainer Class Reference
lib » libstd
Generic command-line argument parser.
#include <ArgumentContainer.h>
Public Types
enum Result { Success, InvalidArgument, NotFound }
Result codes.
Public Member Functions
ArgumentContainer ()
Constructor.
virtual ~ArgumentContainer ()
Destructor.
const char * get (const char *name) const
Get argument by name (eigher identifier or fullname)
const Vector< Argument * > & getPositionals () const
Get positional arguments.
const HashTable< String, Argument * > & getFlags () const
Get flag arguments.
Result addPositional (Argument *arg)
Add positional argument.
Result addFlag (Argument *arg)
Add flag argument.
Private Attributes
HashTable< String, Argument * > m_flags
Contains all flag arguments.
Vector< Argument * > m_positionals
Contains all positional arguments.
Detailed Description
Generic command-line argument parser.
Definition at line 40 of file ArgumentContainer.h.
Member Enumeration Documentation
Result
enum ArgumentContainer::Result
Result codes.
Enumerator
Success
InvalidArgument
NotFound
Definition at line 47 of file ArgumentContainer.h.
Constructor & Destructor Documentation
ArgumentContainer()
ArgumentContainer::ArgumentContainer ()
Constructor.
Definition at line 20 of file ArgumentContainer.cpp.
~ArgumentContainer()
ArgumentContainer::~ArgumentContainer () virtual
Destructor.
Definition at line 24 of file ArgumentContainer.cpp.
References Vector< T >::count(), HashIterator< K, V >::hasCurrent(), m_flags, and m_positionals.
Member Function Documentation
addFlag()
ArgumentContainer::Result ArgumentContainer::addFlag (Argument * arg)
Add flag argument.
Parameters
arg Flag argument
Returns
Result code
Definition at line 73 of file ArgumentContainer.cpp.
References Argument::getName(), HashTable< K, V >::insert(), m_flags, and Success.
Referenced by ArgumentParser::parse().
addPositional()
ArgumentContainer::Result ArgumentContainer::addPositional (Argument * arg)
Add positional argument.
Parameters
arg Positional argument
Returns
Result code
Definition at line 67 of file ArgumentContainer.cpp.
References Vector< T >::insert(), m_positionals, and Success.
Referenced by ArgumentParser::parse().
get()
const char * ArgumentContainer::get (const char * name) const
Get argument by name (eigher identifier or fullname)
Parameters
name Name of the argument
Returns
String object pointer if found or ZERO if not found
Definition at line 49 of file ArgumentContainer.cpp.
References Vector< T >::count(), String::equals(), HashTable< K, V >::get(), Argument::getName(), Argument::getValue(), m_flags, m_positionals, and ZERO.
Referenced by NetPing::exec(), Echo::exec(), Init::exec(), BootImageCreate::exec(), and Application::run().
getFlags()
const HashTable< String, Argument * > & ArgumentContainer::getFlags () const
Get flag arguments.
Returns
HashTable object reference
Definition at line 44 of file ArgumentContainer.cpp.
References m_flags.
getPositionals()
const Vector< Argument * > & ArgumentContainer::getPositionals () const
Get positional arguments.
Returns
Vector object reference
Definition at line 39 of file ArgumentContainer.cpp.
References m_positionals.
Referenced by NetSend::arpRequest(), ListFiles::exec(), FileStatus::exec(), CreateFile::exec(), Echo::exec(), Remove::exec(), Shell::exec(), Cat::exec(), Cat::initialize(), ArgumentParser::parse(), and NetReceive::receivePacket().
Field Documentation
m_flags
HashTable<String, Argument *> ArgumentContainer::m_flags private
Contains all flag arguments.
Definition at line 110 of file ArgumentContainer.h.
Referenced by addFlag(), get(), getFlags(), and ~ArgumentContainer().
m_positionals
Vector<Argument *> ArgumentContainer::m_positionals private
Contains all positional arguments.
Definition at line 113 of file ArgumentContainer.h.
Referenced by addPositional(), get(), getPositionals(), and ~ArgumentContainer().
The documentation for this class was generated from the following files:
lib/libstd/ArgumentContainer.h
lib/libstd/ArgumentContainer.cpp