FreeNOS: NetReceive Class Reference
NetReceive Class Reference
bin
Network receive application.
#include <NetReceive.h>
Public Member Functions
NetReceive (int argc, char **argv)
Class constructor.
virtual ~NetReceive ()
Class destructor.
virtual Result exec ()
Execute the application event loop.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Private Member Functions
Result receiveArp ()
Result receivePacket (u8 *packet, Size size)
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
Network receive application.
Definition at line 33 of file NetReceive.h.
Constructor & Destructor Documentation
NetReceive()
NetReceive::NetReceive (int argc, char ** argv)
Class constructor.
Definition at line 50 of file NetReceive.cpp.
References Application::parser(), ArgumentParser::registerFlag(), ArgumentParser::registerPositional(), and ArgumentParser::setDescription().
~NetReceive()
NetReceive::~NetReceive () virtual
Class destructor.
Definition at line 59 of file NetReceive.cpp.
Member Function Documentation
exec()
NetReceive::Result NetReceive::exec () virtual
Execute the application event loop.
Implements Application.
Definition at line 63 of file NetReceive.cpp.
References DEBUG, and receiveArp().
receiveArp()
NetReceive::Result NetReceive::receiveArp () private
Definition at line 69 of file NetReceive.cpp.
References Ethernet::Address::addr, Ethernet::ARP, be16_to_cpu, be32_to_cpu, ARP::Header::etherSender, ARP::Header::etherTarget, ARP::Header::hardwareLength, ARP::Header::hardwareType, ARP::Header::ipSender, ARP::Header::ipTarget, ARP::Header::operation, printf(), ARP::Header::protocolLength, ARP::Header::protocolType, receivePacket(), Application::Success, and Ethernet::Header::type.
Referenced by exec().
receivePacket()
NetReceive::Result NetReceive::receivePacket (u8 * packet, Size size) private
Definition at line 110 of file NetReceive.cpp.
References Application::arguments(), close(), DEBUG, errno, exit(), EXIT_FAILURE, ArgumentContainer::getPositionals(), Application::IOError, O_RDWR, open(), printf(), read(), strerror(), and Application::Success.
Referenced by receiveArp().
The documentation for this class was generated from the following files:
bin/netrecv/NetReceive.h
bin/netrecv/NetReceive.cpp