FreeNOS: ARMTimer Class Reference
ARMTimer Class Reference
lib » libarch » ARM
ARM Generic Timer.
#include <ARMTimer.h>
Public Member Functions
ARMTimer ()
virtual Result setFrequency (Size hertz)
Set timer frequency.
virtual Result tick ()
Process timer tick.
Public Member Functions inherited from Timer
struct Timer::Info ALIGN (8) Info
Timer information structure.
Timer ()
Constructor.
Size getInterrupt () const
Get timer interrupt number.
Size getFrequency () const
Get timer frequency.
virtual Result getCurrent (Info *info)
Get current timer info.
virtual Result initialize ()
Initialize the timer.
virtual Result start ()
Start the timer.
virtual Result stop ()
Stop the timer.
virtual Result wait (u32 microseconds) const
Busy wait a number of microseconds.
bool isExpired (const Info &info) const
Check if a timer value is expired.
Private Member Functions
u32 getSystemFrequency (void) const
Retrieve system timer frequency.
void setPL1TimerValue (u32 value)
Set Timer 1 value.
void setPL1Control (u32 value)
Set Timer 1 control value.
Private Attributes
Size m_frequency
Additional Inherited Members
Public Types inherited from Timer
enum Result { Success, NotFound, IOError, InvalidFrequency }
Result codes.
Data Fields inherited from Timer
enum Timer::Result ALIGN
Protected Attributes inherited from Timer
Info m_info
The current Timer information.
Size m_frequency
Frequency of the Timer.
Size m_int
Timer interrupt number.
Detailed Description
ARM Generic Timer.
Note
Currently only used for QEMU emulator support of Raspberry Pi
Definition at line 44 of file ARMTimer.h.
Constructor & Destructor Documentation
ARMTimer()
ARMTimer::ARMTimer ()
Definition at line 25 of file ARMTimer.cpp.
Member Function Documentation
getSystemFrequency()
u32 ARMTimer::getSystemFrequency (void) const private
Retrieve system timer frequency.
Returns
System frequency
Definition at line 30 of file ARMTimer.cpp.
References mrc.
Referenced by tick().
setFrequency()
ARMTimer::Result ARMTimer::setFrequency (Size hertz) virtual
Set timer frequency.
Parameters
hertz Frequency of the timer in hertz.
Returns
Result code
Reimplemented from Timer.
Definition at line 45 of file ARMTimer.cpp.
References m_frequency, Timer::Success, and tick().
setPL1Control()
void ARMTimer::setPL1Control (u32 value) private
Set Timer 1 control value.
Parameters
value New timer control value
Definition at line 40 of file ARMTimer.cpp.
References mcr.
Referenced by tick().
setPL1TimerValue()
void ARMTimer::setPL1TimerValue (u32 value) private
Set Timer 1 value.
Parameters
value New timer value
Definition at line 35 of file ARMTimer.cpp.
References mcr.
Referenced by tick().
tick()
ARMTimer::Result ARMTimer::tick () virtual
Process timer tick.
Should be called on each Timer interrupt to keep the m_info variable synchronized with the actual hardware. Also clears the timer interrupt flag.
Returns
Result code
Reimplemented from Timer.
Definition at line 52 of file ARMTimer.cpp.
References CNTP_CTL_ENABLE, getSystemFrequency(), m_frequency, setPL1Control(), setPL1TimerValue(), and Timer::Success.
Referenced by setFrequency().
Field Documentation
m_frequency
Size ARMTimer::m_frequency private
Definition at line 95 of file ARMTimer.h.
Referenced by setFrequency(), and tick().
The documentation for this class was generated from the following files:
lib/libarch/arm/ARMTimer.h
lib/libarch/arm/ARMTimer.cpp