FreeNOS: PseudoFile Class Reference
PseudoFile Class Reference
lib » libfs
Pseudo files only exist in memory.
#include <PseudoFile.h>
Public Member Functions
PseudoFile ()
Default constructor.
PseudoFile (const char *str)
Constructor.
PseudoFile (const char *format,...)
Constructor with formatted input.
virtual ~PseudoFile ()
Destructor.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read bytes from the file.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Attributes
char * m_buffer
Buffer from which we read.
Additional Inherited Members
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
Pseudo files only exist in memory.
Definition at line 36 of file PseudoFile.h.
Constructor & Destructor Documentation
PseudoFile() [1/3]
PseudoFile::PseudoFile ()
Default constructor.
Definition at line 23 of file PseudoFile.cpp.
References File::m_access, m_buffer, File::m_size, OwnerRW, and ZERO.
PseudoFile() [2/3]
PseudoFile::PseudoFile (const char * str)
Constructor.
Parameters
str Text string with file data
Definition at line 31 of file PseudoFile.cpp.
References File::m_access, m_buffer, File::m_size, OwnerRW, strlcpy(), and strlen().
PseudoFile() [3/3]
PseudoFile::PseudoFile (const char * format, ...)
Constructor with formatted input.
Parameters
format Format string.
... Argument list.
Definition at line 40 of file PseudoFile.cpp.
References File::m_access, m_buffer, File::m_size, OwnerRW, va_end, va_start, and vsnprintf().
~PseudoFile()
PseudoFile::~PseudoFile () virtual
Destructor.
Definition at line 56 of file PseudoFile.cpp.
References m_buffer.
Member Function Documentation
read()
Error PseudoFile::read (IOBuffer & buffer, Size size, Size offset) virtual
Read bytes from the file.
Parameters
buffer Output buffer.
size Number of bytes to read, at maximum.
offset Offset inside the file to start reading.
Returns
Number of bytes read on success, Error on failure.
See also
IOBuffer
Reimplemented from File.
Definition at line 62 of file PseudoFile.cpp.
References m_buffer, File::m_size, and IOBuffer::write().
write()
Error PseudoFile::write (IOBuffer & buffer, Size size, Size offset) virtual
Write bytes to the file.
Parameters
buffer Input/Output buffer to input bytes from.
size Number of bytes to write, at maximum.
offset Offset inside the file to start writing.
Returns
Number of bytes written on success, Error on failure.
Reimplemented from File.
Definition at line 75 of file PseudoFile.cpp.
References m_buffer, File::m_size, memcpy(), memset(), and IOBuffer::read().
Field Documentation
m_buffer
char* PseudoFile::m_buffer private
Buffer from which we read.
Definition at line 92 of file PseudoFile.h.
Referenced by PseudoFile(), read(), write(), and ~PseudoFile().
The documentation for this class was generated from the following files:
lib/libfs/PseudoFile.h
lib/libfs/PseudoFile.cpp