FreeNOS: ARP Class Reference
ARP Class Reference
lib » libnet
Address Resolution Protocol.
#include <ARP.h>
Data Structures
struct ARPCache
ARP table cache entry.
struct Header
ARP network packet header.
Public Types
enum HardwareType { Ethernet = 1 }
ARP hardware types.
enum ProtocolType { IPV4 = 0x0800 }
ARP inter-network protocol types.
enum Operation { Request = 1, Reply = 2 }
ARP message types (operation codes)
typedef struct ARP::Header Header
ARP network packet header.
Public Member Functions
ARP (NetworkServer *server, NetworkDevice *device)
Constructor.
virtual ~ARP ()
Destructor.
virtual Error initialize ()
Perform initialization.
void setIP (::IPV4 *ip)
Set IPV4 instance.
void setEthernet (::Ethernet *ether)
Set Ethernet instance.
Error lookupAddress (IPV4::Address *ipAddr, Ethernet::Address *ethAddr)
Lookup Ethernet address for an IP.
Error sendRequest (IPV4::Address address)
Send ARP request.
Error sendReply (const Ethernet::Address *ethaddr, const IPV4::Address ipAddr)
Send ARP reply.
virtual Error process (NetworkQueue::Packet *pkt, Size offset)
Process incoming network packet.
Public Member Functions inherited from NetworkProtocol
NetworkProtocol (NetworkServer *server, NetworkDevice *device)
Constructor.
virtual ~NetworkProtocol ()
Destructor.
virtual const Size getMaximumPacketSize () const
Get maximum packet size.
Public Member Functions inherited from Directory
Directory ()
Constructor.
virtual ~Directory ()
Destructor.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read directory entries.
virtual File * lookup (const char *name)
Retrieve a File from storage.
void insert (FileType type, const char *name,...)
Insert a new directory entry.
void remove (const char *name)
Remove a directory entry.
void clear ()
Clears the internal list of entries.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Types
typedef struct ARP::ARPCache ARPCache
ARP table cache entry.
Private Member Functions
ARPCache * insertCacheEntry (IPV4::Address ipAddr)
Insert a new entry to the ARP cache.
ARPCache * getCacheEntry (IPV4::Address ipAddr)
Retrieve cache entry by IP.
void updateCacheEntry (IPV4::Address ipAddr, Ethernet::Address ethAddr)
Update cache entry.
Private Attributes
ARPSocket * m_sock
The single ARP socket.
::IPV4 * m_ip
IPV4 instance object.
::Ethernet * m_ether
Ethernet instance.
HashTable< IPV4::Address, ARPCache * > m_cache
Contains a cached mapping from IP to Ethernet addresses.
Static Private Attributes
static const Size MaxRetries = 3
Maximum number of retries for ARP lookup.
Additional Inherited Members
Protected Attributes inherited from NetworkProtocol
NetworkServer * m_server
Network server instance.
NetworkDevice * m_device
Network device instance.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
Address Resolution Protocol.
Definition at line 40 of file ARP.h.
Member Typedef Documentation
ARPCache
typedef struct ARP::ARPCache ARP::ARPCache private
ARP table cache entry.
Header
typedef struct ARP::Header ARP::Header
ARP network packet header.
This header is prepended to every ARP packet send on the actual physical link.
Member Enumeration Documentation
HardwareType
enum ARP::HardwareType
ARP hardware types.
Enumerator
Ethernet
Definition at line 64 of file ARP.h.
Operation
enum ARP::Operation
ARP message types (operation codes)
Enumerator
Request
Reply
Definition at line 80 of file ARP.h.
ProtocolType
enum ARP::ProtocolType
ARP inter-network protocol types.
Enumerator
IPV4
Definition at line 72 of file ARP.h.
Constructor & Destructor Documentation
ARP()
ARP::ARP (NetworkServer * server, NetworkDevice * device)
Constructor.
Definition at line 24 of file ARP.cpp.
References m_ether, and m_ip.
~ARP()
ARP::~ARP () virtual
Destructor.
Definition at line 31 of file ARP.cpp.
Member Function Documentation
getCacheEntry()
ARP::ARPCache * ARP::getCacheEntry (IPV4::Address ipAddr) private
Retrieve cache entry by IP.
Parameters
ipAddr IP address to lookup
Returns
ARPCache object pointer or ZERO if not found
Definition at line 53 of file ARP.cpp.
References insertCacheEntry(), and m_cache.
Referenced by lookupAddress(), sendRequest(), and updateCacheEntry().
initialize()
Error ARP::initialize () virtual
Perform initialization.
Implements NetworkProtocol.
Definition at line 35 of file ARP.cpp.
References ESUCCESS, NetworkProtocol::m_server, m_sock, and FileSystem::registerFile().
Referenced by NetworkDevice::initialize().
insertCacheEntry()
ARP::ARPCache * ARP::insertCacheEntry (IPV4::Address ipAddr) private
Insert a new entry to the ARP cache.
Parameters
ipAddr IP address to add
Returns
ARPCache object pointer
Definition at line 62 of file ARP.cpp.
References m_cache, MemoryBlock::set(), and ARP::ARPCache::valid.
Referenced by getCacheEntry().
lookupAddress()
Error ARP::lookupAddress (IPV4::Address * ipAddr, Ethernet::Address * ethAddr)
Lookup Ethernet address for an IP.
Parameters
ipAddr Input IP address to lookup
ethAddr Output Ethernet address when found
Returns
EAGAIN when the lookup is in progress ESUCCESS on success Other error code on error
Definition at line 84 of file ARP.cpp.
References MemoryBlock::copy(), DEBUG, EAGAIN, ESUCCESS, ARP::ARPCache::ethAddr, getCacheEntry(), NetworkProtocol::m_server, sendRequest(), ChannelServer< Base, MsgType >::setTimeout(), and ARP::ARPCache::valid.
Referenced by IPV4::getTransmitPacket(), ARPSocket::read(), and ARPSocket::write().
process()
Error ARP::process (NetworkQueue::Packet * pkt, Size offset) virtual
Process incoming network packet.
Parameters
pkt Incoming packet pointer
offset Offset for processing
Returns
Error code
Implements NetworkProtocol.
Definition at line 203 of file ARP.cpp.
References be16_to_cpu, be32_to_cpu, NetworkQueue::Packet::data, DEBUG, EINVAL, ENOTSUP, ARP::Header::etherSender, IPV4::getAddress(), ARP::Header::ipSender, ARP::Header::ipTarget, m_ip, m_sock, ARP::Header::operation, ARPSocket::process(), Reply, Request, sendReply(), Ethernet::Header::source, and updateCacheEntry().
Referenced by Ethernet::process().
sendReply()
Error ARP::sendReply (const Ethernet::Address * ethaddr, const IPV4::Address ipAddr)
Send ARP reply.
Parameters
ethaddr Ethernet address to send reply to
ipaddr IP address of the origin
Returns
Error code
Definition at line 161 of file ARP.cpp.
References Ethernet::ARP, MemoryBlock::copy(), cpu_to_be16, cpu_to_be32, NetworkQueue::Packet::data, DEBUG, Ethernet::Header::destination, EAGAIN, EINVAL, Ethernet, ARP::Header::etherSender, ARP::Header::etherTarget, IPV4::getAddress(), Ethernet::getTransmitPacket(), ARP::Header::hardwareLength, ARP::Header::hardwareType, ARP::Header::ipSender, ARP::Header::ipTarget, IPV4, NetworkProtocol::m_device, m_ether, m_ip, ARP::Header::operation, ARP::Header::protocolLength, ARP::Header::protocolType, Reply, NetworkQueue::Packet::size, Ethernet::Header::source, and NetworkDevice::transmit().
Referenced by process().
sendRequest()
Error ARP::sendRequest (IPV4::Address address)
Send ARP request.
Parameters
address IPV4 address to lookup
Returns
Error code
Definition at line 106 of file ARP.cpp.
References Ethernet::ARP, MemoryBlock::copy(), cpu_to_be16, cpu_to_be32, NetworkQueue::Packet::data, DEBUG, Ethernet::Header::destination, EAGAIN, EHOSTUNREACH, Ethernet, ARP::Header::etherSender, ARP::Header::etherTarget, IPV4::getAddress(), getCacheEntry(), Ethernet::getTransmitPacket(), ARP::Header::hardwareLength, ARP::Header::hardwareType, ARP::Header::ipSender, ARP::Header::ipTarget, IPV4, NetworkProtocol::m_device, m_ether, m_ip, MaxRetries, ARP::Header::operation, ARP::Header::protocolLength, ARP::Header::protocolType, Request, ARP::ARPCache::retryCount, MemoryBlock::set(), NetworkQueue::Packet::size, Ethernet::Header::source, NetworkDevice::transmit(), and ARP::ARPCache::valid.
Referenced by lookupAddress().
setEthernet()
void ARP::setEthernet (::Ethernet * ether)
Set Ethernet instance.
Parameters
ether Ethernet intstance
Definition at line 48 of file ARP.cpp.
References m_ether.
Referenced by NetworkDevice::initialize().
setIP()
void ARP::setIP (::IPV4 * ip)
Set IPV4 instance.
Parameters
ip IPV4 instance
Definition at line 43 of file ARP.cpp.
References m_ip.
Referenced by NetworkDevice::initialize().
updateCacheEntry()
void ARP::updateCacheEntry (IPV4::Address ipAddr, Ethernet::Address ethAddr) private
Update cache entry.
Parameters
ipAddr IP address for update
ethAddr Ethernet address for update
Definition at line 73 of file ARP.cpp.
References MemoryBlock::copy(), ARP::ARPCache::ethAddr, getCacheEntry(), and ARP::ARPCache::valid.
Referenced by process().
Field Documentation
m_cache
HashTable<IPV4::Address, ARPCache *> ARP::m_cache private
Contains a cached mapping from IP to Ethernet addresses.
Definition at line 224 of file ARP.h.
Referenced by getCacheEntry(), and insertCacheEntry().
m_ether
::Ethernet* ARP::m_ether private
Ethernet instance.
Definition at line 221 of file ARP.h.
Referenced by ARP(), sendReply(), sendRequest(), and setEthernet().
m_ip
::IPV4* ARP::m_ip private
IPV4 instance object.
Definition at line 218 of file ARP.h.
Referenced by ARP(), process(), sendReply(), sendRequest(), and setIP().
m_sock
ARPSocket* ARP::m_sock private
The single ARP socket.
Definition at line 215 of file ARP.h.
Referenced by initialize(), and process().
MaxRetries
const Size ARP::MaxRetries = 3 static private
Maximum number of retries for ARP lookup.
Definition at line 45 of file ARP.h.
Referenced by sendRequest().
The documentation for this class was generated from the following files:
lib/libnet/ARP.h
lib/libnet/ARP.cpp