FreeNOS: IntelPageTable Class Reference
IntelPageTable Class Reference
lib » libarch » Intel
Intel second level page table implementation.
#include <IntelPageTable.h>
Public Member Functions
MemoryContext::Result map (Address virt, Address phys, Memory::Access)
Map a virtual address to a physical address.
MemoryContext::Result unmap (Address virt)
Remove virtual address mapping.
MemoryContext::Result translate (Address virt, Address *phys) const
Translate virtual address to physical address.
MemoryContext::Result access (Address virt, Memory::Access *access) const
Get Access flags for a virtual address.
Private Member Functions
u32 flags (Memory::Access access) const
Convert MemoryAccess to page table flags.
Private Attributes
u32 m_pages [1024]
Array of page table entries.
Detailed Description
Intel second level page table implementation.
Definition at line 39 of file IntelPageTable.h.
Member Function Documentation
access()
MemoryContext::Result IntelPageTable::access (Address virt, Memory::Access * access) const
Get Access flags for a virtual address.
Parameters
virt Virtual address to get Access flags for.
access MemoryAccess object pointer.
Returns
Result code.
Definition at line 66 of file IntelPageTable.cpp.
References MemoryContext::InvalidAddress, m_pages, PAGE_PRESENT, PAGE_USER, PAGE_WRITE, Memory::Readable, MemoryContext::Success, TABENTRY, Memory::User, and Memory::Writable.
Referenced by IntelPageDirectory::access().
flags()
u32 IntelPageTable::flags (Memory::Access access) const private
Convert MemoryAccess to page table flags.
Parameters
access Memory access flags to convert
Returns
Page table flags
Definition at line 81 of file IntelPageTable.cpp.
References PAGE_USER, PAGE_WRITE, Memory::User, and Memory::Writable.
Referenced by map().
map()
MemoryContext::Result IntelPageTable::map (Address virt, Address phys, Memory::Access access)
Map a virtual address to a physical address.
Parameters
virt Virtual address.
phys Physical address.
access Memory access flags.
Returns
Result code
Definition at line 38 of file IntelPageTable.cpp.
References MemoryContext::AlreadyExists, flags(), m_pages, PAGE_PRESENT, MemoryContext::Success, and TABENTRY.
Referenced by IntelPageDirectory::map().
translate()
MemoryContext::Result IntelPageTable::translate (Address virt, Address * phys) const
Translate virtual address to physical address.
Parameters
virt Virtual address to lookup on input, physical address on output.
Returns
Result code
Definition at line 57 of file IntelPageTable.cpp.
References MemoryContext::InvalidAddress, m_pages, PAGE_PRESENT, PAGEMASK, MemoryContext::Success, and TABENTRY.
Referenced by IntelPageDirectory::releaseRange(), and IntelPageDirectory::translate().
unmap()
MemoryContext::Result IntelPageTable::unmap (Address virt)
Remove virtual address mapping.
Parameters
virt Virtual address.
Returns
Result code
Definition at line 51 of file IntelPageTable.cpp.
References m_pages, PAGE_NONE, MemoryContext::Success, and TABENTRY.
Referenced by IntelPageDirectory::unmap().
Field Documentation
m_pages
u32 IntelPageTable::m_pages[1024] private
Array of page table entries.
Definition at line 98 of file IntelPageTable.h.
Referenced by access(), map(), translate(), and unmap().
The documentation for this class was generated from the following files:
lib/libarch/intel/IntelPageTable.h
lib/libarch/intel/IntelPageTable.cpp