FreeNOS: NetSend Class Reference
NetSend Class Reference
bin
Network send application.
#include <NetSend.h>
Public Member Functions
NetSend (int argc, char **argv)
Class constructor.
virtual ~NetSend ()
Class destructor.
virtual Result exec ()
Execute the application event loop.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Private Member Functions
Result arpRequest (IPV4::Address ipAddr, Ethernet::Address *ethAddr)
Send ARP request.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
Network send application.
Definition at line 33 of file NetSend.h.
Constructor & Destructor Documentation
NetSend()
NetSend::NetSend (int argc, char ** argv)
Class constructor.
Definition at line 53 of file NetSend.cpp.
References Application::parser(), ArgumentParser::registerFlag(), ArgumentParser::registerPositional(), and ArgumentParser::setDescription().
~NetSend()
NetSend::~NetSend () virtual
Class destructor.
Definition at line 62 of file NetSend.cpp.
Member Function Documentation
arpRequest()
NetSend::Result NetSend::arpRequest (IPV4::Address ipAddr, Ethernet::Address * ethAddr) private
Send ARP request.
Definition at line 76 of file NetSend.cpp.
References Ethernet::Address::addr, Application::arguments(), Ethernet::ARP, MemoryBlock::copy(), cpu_to_be16, cpu_to_be32, DEBUG, Ethernet::Header::destination, errno, ARP::Ethernet, ARP::Header::etherSender, ARP::Header::etherTarget, exit(), EXIT_FAILURE, ArgumentContainer::getPositionals(), ARP::Header::hardwareLength, ARP::Header::hardwareType, ARP::Header::ipSender, ARP::Header::ipTarget, ARP::IPV4, O_RDWR, open(), ARP::Header::operation, printf(), ARP::Header::protocolLength, ARP::Header::protocolType, ARP::Request, MemoryBlock::set(), Ethernet::Header::source, strerror(), Application::Success, Ethernet::Header::type, and write().
Referenced by exec().
exec()
NetSend::Result NetSend::exec () virtual
Execute the application event loop.
Implements Application.
Definition at line 66 of file NetSend.cpp.
References arpRequest(), and DEBUG.
The documentation for this class was generated from the following files:
bin/netsend/NetSend.h
bin/netsend/NetSend.cpp