FreeNOS: ListIterator< T > Class Template Reference
ListIterator< T > Class Template Reference
lib » libstd
Iterate through a List.
#include <ListIterator.h>
Public Member Functions
ListIterator (List< T > *list)
Class constructor.
ListIterator (List< T > &list)
Class constructor.
ListIterator (const List< T > &list)
Constant class constructor.
virtual void reset ()
Reset the iterator.
virtual bool hasNext () const
Check if there is more on the List to iterate.
virtual bool hasCurrent () const
Check if there is a current item on the List.
virtual const T & current () const
Get current item in the List.
virtual T & current ()
Get current item in the List.
virtual T & next ()
Fetch the next item.
virtual bool remove ()
Remove the current item from the List.
virtual void operator++ (int num)
Increment operator.
Public Member Functions inherited from Iterator< T >
virtual ~Iterator ()
Destructor.
Private Attributes
List< T > & m_list
Points to the List to iterate.
class List< T >::Node * m_current
Current node.
class List< T >::Node * m_next
Next node.
Detailed Description
template<class T>
class ListIterator< T >
Iterate through a List.
Definition at line 37 of file ListIterator.h.
Constructor & Destructor Documentation
ListIterator() [1/3]
template<class T> ListIterator< T >::ListIterator (List< T > * list) inline
Class constructor.
Parameters
list Reference to the List to iterate.
Definition at line 46 of file ListIterator.h.
ListIterator() [2/3]
template<class T> ListIterator< T >::ListIterator (List< T > & list) inline
Class constructor.
Parameters
list Reference to the List to iterate.
Definition at line 60 of file ListIterator.h.
ListIterator() [3/3]
template<class T> ListIterator< T >::ListIterator (const List< T > & list) inline
Constant class constructor.
Parameters
list Reference to the List to iterate.
Definition at line 74 of file ListIterator.h.
Member Function Documentation
current() [1/2]
template<class T> virtual const T& ListIterator< T >::current () const inline virtual
Get current item in the List.
Returns
Current item.
Implements Iterator< T >.
Definition at line 118 of file ListIterator.h.
Referenced by ConstHashIterator< K, V >::current(), HashIterator< K, V >::current(), ConstHashIterator< K, V >::key(), HashIterator< K, V >::key(), and HashIterator< K, V >::remove().
current() [2/2]
template<class T> virtual T& ListIterator< T >::current () inline virtual
Get current item in the List.
Returns
Current item.
Implements Iterator< T >.
Definition at line 128 of file ListIterator.h.
hasCurrent()
template<class T> virtual bool ListIterator< T >::hasCurrent () const inline virtual
Check if there is a current item on the List.
Returns
True if current item available, false otherwise.
Implements Iterator< T >.
Definition at line 108 of file ListIterator.h.
Referenced by HashTable< String, FileCache *>::at(), CoreServer::bootAll(), chdir(), Directory::clear(), Associative< String, FileCache * >::compareTo(), CoreServer::discover(), Shell::exec(), Kernel::executeIntVector(), FileSystem::findFileCache(), Directory::get(), HashTable< String, FileCache *>::get(), ConstHashIterator< K, V >::hasCurrent(), HashIterator< K, V >::hasCurrent(), HashTable< String, FileCache *>::insert(), LinnCreate::insertDirectory(), DeviceServer::interruptHandler(), HashTable< String, FileCache *>::keys(), FileSystem::lookupFile(), FileSystemPath::parse(), Directory::read(), Directory::remove(), HashTable< String, FileCache *>::remove(), FileSystem::retryRequests(), TestRunner::run(), IPV4::toAddress(), HashTable< String, FileCache *>::value(), HashTable< String, FileCache *>::values(), Directory::~Directory(), FileSystemPath::~FileSystemPath(), and ProcessShares::~ProcessShares().
hasNext()
template<class T> virtual bool ListIterator< T >::hasNext () const inline virtual
Check if there is more on the List to iterate.
Returns
true if more items, false if not.
Implements Iterator< T >.
Definition at line 98 of file ListIterator.h.
Referenced by Associative< String, FileCache * >::clear(), ConstHashIterator< K, V >::hasNext(), and HashIterator< K, V >::hasNext().
next()
template<class T> virtual T& ListIterator< T >::next () inline virtual
Fetch the next item.
8 This function first fetches the next item and then updates the current item pointer to that item. It assumes the iterator has a next item.
Returns
The next item.
See also
hasNext
Implements Iterator< T >.
Definition at line 144 of file ListIterator.h.
Referenced by ConstHashIterator< K, V >::next(), HashIterator< K, V >::next(), and ListIterator< K >::remove().
operator++()
template<class T> virtual void ListIterator< T >::operator++ (int num) inline virtual
Increment operator.
This function first increment the current item and then updates the next item pointer.
Implements Iterator< T >.
Definition at line 181 of file ListIterator.h.
remove()
template<class T> virtual bool ListIterator< T >::remove () inline virtual
Remove the current item from the List.
Returns
True if successfull, false otherwise.
Implements Iterator< T >.
Definition at line 159 of file ListIterator.h.
Referenced by HashIterator< K, V >::remove(), and ListIterator< K >::remove().
reset()
template<class T> virtual void ListIterator< T >::reset () inline virtual
Reset the iterator.
Implements Iterator< T >.
Definition at line 86 of file ListIterator.h.
Referenced by ListIterator< K >::ListIterator(), ConstHashIterator< K, V >::reset(), and HashIterator< K, V >::reset().
Field Documentation
m_current
template<class T> class List< T >::Node* ListIterator< T >::m_current private
Current node.
Definition at line 200 of file ListIterator.h.
Referenced by ListIterator< K >::current(), ListIterator< K >::hasCurrent(), ListIterator< K >::ListIterator(), ListIterator< K >::next(), ListIterator< K >::operator++(), ListIterator< K >::remove(), and ListIterator< K >::reset().
m_list
template<class T> List<T>& ListIterator< T >::m_list private
Points to the List to iterate.
Definition at line 197 of file ListIterator.h.
Referenced by ListIterator< K >::remove(), and ListIterator< K >::reset().
m_next
template<class T> class List< T >::Node* ListIterator< T >::m_next private
Next node.
Definition at line 203 of file ListIterator.h.
Referenced by ListIterator< K >::hasNext(), ListIterator< K >::next(), ListIterator< K >::operator++(), ListIterator< K >::remove(), and ListIterator< K >::reset().
The documentation for this class was generated from the following file:
lib/libstd/ListIterator.h