FreeNOS: BroadcomSPI Class Reference
BroadcomSPI Class Reference
lib » libspi
Broadcom (2835) SPI controller implementation.
#include <BroadcomSPI.h>
Public Member Functions
BroadcomSPI ()
Constructor.
virtual Result initialize ()
Initialize the Controller.
virtual Result setClockDivider (Size divider)
Set clock divider.
virtual Result transfer (u8 *sendBuf, u8 *recvBuf, Size size)
Read and Write data to/from slave.
virtual Result write (u8 *buf, Size size)
Write data to slave.
virtual Result read (u8 *buf, Size size)
Read data from slave.
Public Member Functions inherited from SPI
SPI ()
Constructor.
Private Types
enum Registers {
Control = 0x0, FIFO = 0x4, ClockDivider = 0x8, LoSSI = 0x10,
DMACtl = 0x14
}
Hardware registers.
enum ControlFlags {
ChipSelect0 = (0), ChipSelect1 = (1 << 0), ChipSelect2 = (1 << 1), ClockPolHigh = (1 << 3),
ClearFIFO = 0x30, ClearFIFORx = 0x20, ClearFIFOTx = 0x10, ChipSelActiveHigh = (1 << 6),
TransferActive = (1 << 7), DMAEnable = (1 << 8), ChipSelAutoDeassert = (1 << 11), ReadEnable = (1 << 12),
TransferDone = (1 << 16), RxHasData = (1 << 17), TxHasSpace = (1 << 18), RxNeedRead = (1 << 19),
RxIsFull = (1 << 20), ChipSelect0ActiveHigh = (1 << 21), ChipSelect1ActiveHigh = (1 << 22), ChipSelect2ActiveHigh = (1 << 23)
}
Control Register Flags.
Private Attributes
BroadcomGPIO m_gpio
GPIO controller.
Static Private Attributes
static const uint SPI0 = 0x204000
Additional Inherited Members
Public Types inherited from SPI
enum Result { Success, NotFound, IOError, RangeError }
Result codes.
Protected Attributes inherited from SPI
Arch::IO m_io
I/O instance.
Detailed Description
Broadcom (2835) SPI controller implementation.
Definition at line 37 of file BroadcomSPI.h.
Member Enumeration Documentation
ControlFlags
enum BroadcomSPI::ControlFlags private
Control Register Flags.
Enumerator
ChipSelect0
ChipSelect1
ChipSelect2
ClockPolHigh
ClearFIFO
ClearFIFORx
ClearFIFOTx
ChipSelActiveHigh
TransferActive
DMAEnable
ChipSelAutoDeassert
ReadEnable
TransferDone
RxHasData
TxHasSpace
RxNeedRead
RxIsFull
ChipSelect0ActiveHigh
ChipSelect1ActiveHigh
ChipSelect2ActiveHigh
Definition at line 58 of file BroadcomSPI.h.
Registers
enum BroadcomSPI::Registers private
Hardware registers.
Enumerator
Control
FIFO
ClockDivider
LoSSI
DMACtl
Definition at line 46 of file BroadcomSPI.h.
Constructor & Destructor Documentation
BroadcomSPI()
BroadcomSPI::BroadcomSPI ()
Constructor.
Definition at line 21 of file BroadcomSPI.cpp.
Member Function Documentation
initialize()
BroadcomSPI::Result BroadcomSPI::initialize () virtual
Initialize the Controller.
Returns
Result code
Implements SPI.
Definition at line 25 of file BroadcomSPI.cpp.
References ClearFIFO, Control, Memory::Device, BroadcomGPIO::Function0, BroadcomGPIO::initialize(), SPI::IOError, m_gpio, SPI::m_io, IO::map(), PAGESIZE, Memory::Readable, BroadcomGPIO::setAltFunction(), SPI0, SPI::Success, IO::Success, BroadcomGPIO::Success, Memory::User, Memory::Writable, and ARMIO::write().
Referenced by main().
read()
BroadcomSPI::Result BroadcomSPI::read (u8 * buf, Size size) virtual
Read data from slave.
Parameters
buf Buffer for storing bytes read.
size Number of bytes to read.
Returns
Result code.
Implements SPI.
Definition at line 99 of file BroadcomSPI.cpp.
References SPI::Success.
setClockDivider()
BroadcomSPI::Result BroadcomSPI::setClockDivider (Size divider) virtual
Set clock divider.
Parameters
divider Clock divider to use.
Returns
Result code.
Definition at line 48 of file BroadcomSPI.cpp.
References ClockDivider, SPI::m_io, SPI::Success, and ARMIO::write().
transfer()
BroadcomSPI::Result BroadcomSPI::transfer (u8 * sendBuf, u8 * recvBuf, Size size) virtual
Read and Write data to/from slave.
Parameters
sendBuf Buffer containing bytes to write, and to read.
recvBuf Buffer for receiving bytes.
size Number of bytes to write/read.
Returns
Result code.
Implements SPI.
Definition at line 54 of file BroadcomSPI.cpp.
References ClearFIFO, Control, DEBUG, FIFO, SPI::m_io, ARMIO::read(), RxHasData, ARMIO::set(), SPI::Success, TransferActive, TransferDone, TxHasSpace, and ARMIO::write().
write()
BroadcomSPI::Result BroadcomSPI::write (u8 * buf, Size size) virtual
Write data to slave.
Parameters
buf Buffer containing bytes to write.
size Number of bytes to write.
Returns
Result code.
Implements SPI.
Definition at line 94 of file BroadcomSPI.cpp.
References SPI::Success.
Field Documentation
m_gpio
BroadcomGPIO BroadcomSPI::m_gpio private
GPIO controller.
Definition at line 139 of file BroadcomSPI.h.
Referenced by initialize().
SPI0
const uint BroadcomSPI::SPI0 = 0x204000 static private
Definition at line 41 of file BroadcomSPI.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
lib/libspi/BroadcomSPI.h
lib/libspi/BroadcomSPI.cpp