FreeNOS: Index< T > Class Template Reference
Index< T > Class Template Reference
lib » libstd
Index is a resizable array of pointers to items.
#include <Index.h>
Public Member Functions
Index (Size size=INDEX_DEFAULT_SIZE)
Constructor.
virtual ~Index ()
Destructor.
virtual int insert (const T &item)
Adds the given item to the Sequence, if possible.
virtual bool insert (Size position, const T &item)
Inserts the given item at the given position.
virtual void fill (T value)
Fill the Sequence with the given value.
virtual bool remove (Size position)
Removes the item at the given position.
virtual const T * get (Size position) const
Returns the item at the given position.
virtual const T & at (Size position) const
Returns a reference to the item at the given position.
virtual bool contains (T value)
Check if the given item is stored in this Sequence.
virtual int compareTo (const Index< T > &idx) const
Compare this Sequence to another Sequence.
virtual Size size () const
Size of the index.
virtual Size count () const
Item count of the index.
Public Member Functions inherited from Sequence< T >
virtual int remove (T value)
Remove all items with the given value.
virtual bool removeAt (Size position)
Removes the item at the given position.
virtual void clear ()
Removes all items from the Sequence.
virtual bool contains (const T value) const
Check if the given item is stored in this Sequence.
virtual int compareTo (const Sequence< T > &s) const
Compare this Sequence to another Sequence.
const T & operator[] (int i) const
Returns the item at the given position in the Sequence.
const T & operator[] (Size i) const
Returns the item at the given position in the Sequence.
T & operator[] (int i)
Returns the item at the given position in the Sequence.
T & operator[] (Size i)
Returns the item at the given position in the Sequence.
Public Member Functions inherited from Container
Container ()
Constructor.
virtual ~Container ()
Destructor.
virtual bool isEmpty () const
Check if the Container is empty.
virtual bool reserve (Size size)
Ensure that at least the given size is available.
virtual bool shrink (Size size)
Shrink the container size by the given amount of items.
virtual Size squeeze ()
Try to minimize the memory required in the Container.
virtual bool resize (Size size)
Change the size of the Container.
Public Member Functions inherited from Comparable< Sequence< T > >
virtual ~Comparable ()
Class destructor.
virtual bool equals (const Sequence< T > &t) const
Test if an object is equal to an other object.
Private Attributes
T ** m_array
Array of pointers to items.
Size m_size
Size of the pointer array.
Size m_count
Amount of valid pointers in the array.
Detailed Description
template<class T>
class Index< T >
Index is a resizable array of pointers to items.
Definition at line 40 of file Index.h.
Constructor & Destructor Documentation
Index()
template<class T> Index< T >::Index (Size size = INDEX_DEFAULT_SIZE) inline
Constructor.
Definition at line 51 of file Index.h.
~Index()
template<class T> virtual Index< T >::~Index () inline virtual
Destructor.
Definition at line 64 of file Index.h.
Member Function Documentation
at()
template<class T> virtual const T& Index< T >::at (Size position) const inline virtual
Returns a reference to the item at the given position.
Parameters
position Valid index inside this array.
Returns
Reference to the item at the given position
Note
This function does not perform bounds checking. Position must be a valid index.
Implements Sequence< T >.
Definition at line 169 of file Index.h.
compareTo()
template<class T> virtual int Index< T >::compareTo (const Index< T > & idx) const inline virtual
Compare this Sequence to another Sequence.
Definition at line 189 of file Index.h.
contains()
template<class T> virtual bool Index< T >::contains (T value) inline virtual
Check if the given item is stored in this Sequence.
Definition at line 177 of file Index.h.
count()
template<class T> virtual Size Index< T >::count () const inline virtual
Item count of the index.
Implements Container.
Definition at line 224 of file Index.h.
Referenced by Index< SynopsisChannel >::compareTo().
fill()
template<class T> virtual void Index< T >::fill (T value) inline virtual
Fill the Sequence with the given value.
Parameters
value New value to fill the Sequence.
Reimplemented from Sequence< T >.
Definition at line 120 of file Index.h.
get()
template<class T> virtual const T* Index< T >::get (Size position) const inline virtual
Returns the item at the given position.
Parameters
position The position of the item to get.
Returns
Pointer to the item at the given position or ZERO if no item available.
Implements Sequence< T >.
Definition at line 152 of file Index.h.
Referenced by CoreServer::bootAll(), CoreServer::createProcess(), MPI_Recv(), MPI_Send(), ICMP::process(), CoreServer::setupChannels(), and CoreServer::test().
insert() [1/2]
template<class T> virtual int Index< T >::insert (const T & item) inline virtual
Adds the given item to the Sequence, if possible.
Parameters
item The item to add to the Sequence.
Returns
Position of the item in the Sequence or -1 on failure.
Reimplemented from Sequence< T >.
Definition at line 76 of file Index.h.
Referenced by UDP::createSocket(), ICMP::createSocket(), CoreServer::discover(), USBDevice::initialize(), MPI_Init(), CoreServer::setupChannels(), and SynopsisController::SynopsisController().
insert() [2/2]
template<class T> virtual bool Index< T >::insert (Size position, const T & item) inline virtual
Inserts the given item at the given position.
If an item exists at the given position, it will be replaced by the given item.
Parameters
position The position to insert the item.
item The item to insert
Returns
bool Whether inserting the item at the given position succeeded.
Reimplemented from Sequence< T >.
Definition at line 103 of file Index.h.
remove()
template<class T> virtual bool Index< T >::remove (Size position) inline virtual
Removes the item at the given position.
Parameters
position The position of the item to remove.
Returns
bool Whether removing the item succeeded.
Definition at line 132 of file Index.h.
size()
template<class T> virtual Size Index< T >::size () const inline virtual
Size of the index.
Implements Container.
Definition at line 216 of file Index.h.
Referenced by Index< SynopsisChannel >::compareTo(), Index< SynopsisChannel >::Index(), and ICMP::process().
Field Documentation
m_array
template<class T> T** Index< T >::m_array private
Array of pointers to items.
Definition at line 232 of file Index.h.
Referenced by Index< SynopsisChannel >::at(), Index< SynopsisChannel >::compareTo(), Index< SynopsisChannel >::contains(), Index< SynopsisChannel >::get(), Index< SynopsisChannel >::Index(), Index< SynopsisChannel >::insert(), Index< SynopsisChannel >::remove(), and Index< SynopsisChannel >::~Index().
m_count
template<class T> Size Index< T >::m_count private
Amount of valid pointers in the array.
Definition at line 238 of file Index.h.
Referenced by Index< SynopsisChannel >::count(), Index< SynopsisChannel >::Index(), Index< SynopsisChannel >::insert(), and Index< SynopsisChannel >::remove().
m_size
template<class T> Size Index< T >::m_size private
Size of the pointer array.
Definition at line 235 of file Index.h.
Referenced by Index< SynopsisChannel >::contains(), Index< SynopsisChannel >::get(), Index< SynopsisChannel >::Index(), Index< SynopsisChannel >::insert(), Index< SynopsisChannel >::remove(), and Index< SynopsisChannel >::size().
The documentation for this class was generated from the following file:
lib/libstd/Index.h