FreeNOS: ARMPaging Class Reference
ARMPaging Class Reference
lib » libarch » ARM
ARM virtual memory implementation.
#include <ARMPaging.h>
Public Member Functions
ARMPaging (MemoryMap *map, SplitAllocator *alloc)
Constructor.
virtual ~ARMPaging ()
Destructor.
virtual Result activate ()
Activate the MemoryContext.
virtual Result map (Address virt, Address phys, Memory::Access access)
Map a physical page to a virtual address.
virtual Result unmap (Address virt)
Unmap a virtual address.
virtual Result lookup (Address virt, Address *phys) const
Translate virtual address to physical address.
virtual Result access (Address addr, Memory::Access *access) const
Get Access flags for a virtual address.
virtual Result releaseRegion (MemoryMap::Region region, bool tablesOnly)
Release region of memory.
virtual Result releaseRange (Memory::Range *range, bool tablesOnly)
Release range of memory.
Public Member Functions inherited from MemoryContext
MemoryContext (MemoryMap *map, SplitAllocator *alloc)
Constructor.
virtual ~MemoryContext ()
Destructor.
virtual Result mapRange (Memory::Range *range)
Map a range of physical pages to virtual addresses.
virtual Result unmapRange (Memory::Range *range)
Unmaps a range of virtual memory.
virtual Result release (Address virt)
Release a memory page mapping.
virtual Result findFree (Size size, MemoryMap::Region region, Address *virt) const
Find unused memory.
Private Member Functions
Result enableMMU ()
Enable the MMU.
Private Attributes
ARMFirstTable * m_firstTable
Pointer to the first level page table.
Address m_firstTableAddr
Physical address of the first level page table.
Arch::Cache m_cache
Caching implementation.
Additional Inherited Members
Public Types inherited from MemoryContext
enum Result {
Success, InvalidAddress, InvalidSize, AlreadyExists,
OutOfMemory
}
Result codes.
typedef enum MemoryContext::Result Result
Result codes.
Static Public Member Functions inherited from MemoryContext
static MemoryContext * getCurrent ()
Get currently active MemoryContext.
Protected Attributes inherited from MemoryContext
SplitAllocator * m_alloc
Physical memory allocator.
MemoryMap * m_map
Virtual memory layout.
Static Protected Attributes inherited from MemoryContext
static MemoryContext * m_current = 0
The currently active MemoryContext.
Detailed Description
ARM virtual memory implementation.
Definition at line 43 of file ARMPaging.h.
Constructor & Destructor Documentation
ARMPaging()
ARMPaging::ARMPaging (MemoryMap * map, SplitAllocator * alloc)
Constructor.
Parameters
map Virtual memory map.
alloc Allocator pointer of the physical memory page allocations.
Definition at line 27 of file ARMPaging.cpp.
References Memory::Range::access, SplitAllocator::allocateLow(), Memory::Device, MemoryMap::KernelData, MemoryContext::m_alloc, m_firstTable, m_firstTableAddr, MemoryContext::m_map, ARMFirstTable::mapLarge(), MegaByte, Memory::Range::phys, MemoryMap::range(), Memory::Readable, MemoryBlock::set(), Memory::Range::size, Allocator::Success, SplitAllocator::toVirtual(), ARMFirstTable::unmap(), Memory::Range::virt, and Memory::Writable.
~ARMPaging()
ARMPaging::~ARMPaging () virtual
Destructor.
Definition at line 59 of file ARMPaging.cpp.
References ARMControl::AccessPermissions, ARMControl::AlignmentFaults, ARMControl::BranchPrediction, ARMCacheV6::cleanInvalidate(), ARMControl::DataCache, ARMControl::DisablePageColoring, ARMControl::DomainClient, ARMControl::DomainControl, dsb(), enableMMU(), ARMControl::ExtendedPaging, ARMControl::InstructionCache, isb(), MemoryContext::m_alloc, m_cache, m_firstTableAddr, ARMControl::MMUEnabled, NOTICE, PAGESIZE, ARMControl::read(), SplitAllocator::release(), ARMControl::set(), MemoryContext::Success, ARMControl::SystemControl, tlb_flush_all(), ARMControl::TranslationTable0, ARMControl::TranslationTable1, ARMControl::TranslationTableCtrl, Cache::Unified, ARMControl::unset(), and ARMControl::write().
Member Function Documentation
access()
MemoryContext::Result ARMPaging::access (Address addr, Memory::Access * access) const virtual
Get Access flags for a virtual address.
Parameters
virt Virtual address to get Access flags for.
access MemoryAccess object pointer.
Returns
Result code.
Implements MemoryContext.
Definition at line 229 of file ARMPaging.cpp.
References ARMFirstTable::access(), MemoryContext::m_alloc, and m_firstTable.
activate()
MemoryContext::Result ARMPaging::activate () virtual
Activate the MemoryContext.
This function applies this MemoryContext to the hardware MMU.
Returns
Result code.
Implements MemoryContext.
Definition at line 153 of file ARMPaging.cpp.
References ARMCacheV6::cleanInvalidate(), enableMMU(), isb(), m_cache, MemoryContext::m_current, m_firstTableAddr, mcr, ARMControl::MMUEnabled, ARMControl::read(), MemoryContext::Success, ARMControl::SystemControl, tlb_flush_all(), ARMControl::TranslationTable0, Cache::Unified, and ARMControl::write().
enableMMU()
Result ARMPaging::enableMMU () private
Enable the MMU.
Returns
Result code
Referenced by activate(), and ~ARMPaging().
lookup()
MemoryContext::Result ARMPaging::lookup (Address virt, Address * phys) const virtual
Translate virtual address to physical address.
Parameters
virt Virtual address to lookup on input, physical address on output.
Returns
Result code
Implements MemoryContext.
Definition at line 224 of file ARMPaging.cpp.
References MemoryContext::m_alloc, m_firstTable, and ARMFirstTable::translate().
map()
MemoryContext::Result ARMPaging::map (Address virt, Address phys, Memory::Access access) virtual
Map a physical page to a virtual address.
Parameters
virt Virtual address.
phys Physical address.
access Memory access flags.
Returns
Result code
Implements MemoryContext.
Definition at line 192 of file ARMPaging.cpp.
References isb(), MemoryContext::m_alloc, MemoryContext::m_current, m_firstTable, ARMFirstTable::map(), and tlb_invalidate.
releaseRange()
MemoryContext::Result ARMPaging::releaseRange (Memory::Range * range, bool tablesOnly) virtual
Release range of memory.
Parameters
range Memory range input
tablesOnly Set to true to only release page tables and not mapped pages.
Returns
Result code.
Implements MemoryContext.
Definition at line 239 of file ARMPaging.cpp.
References MemoryContext::m_alloc, m_firstTable, and ARMFirstTable::releaseRange().
releaseRegion()
MemoryContext::Result ARMPaging::releaseRegion (MemoryMap::Region region, bool tablesOnly) virtual
Release region of memory.
Parameters
region Memory region input
tablesOnly Set to true to only release page tables and not mapped pages.
Returns
Result code.
Implements MemoryContext.
Definition at line 234 of file ARMPaging.cpp.
References MemoryContext::m_alloc, m_firstTable, MemoryContext::m_map, MemoryMap::range(), and ARMFirstTable::releaseRange().
unmap()
MemoryContext::Result ARMPaging::unmap (Address virt) virtual
Unmap a virtual address.
This function removes a virtual to physical memory mapping without deallocating any physical memory.
Parameters
virt Virtual address to unmap.
Returns
Result code
Implements MemoryContext.
Definition at line 206 of file ARMPaging.cpp.
References ARMCacheV6::cleanInvalidateAddress(), Cache::Data, isb(), MemoryContext::m_alloc, m_cache, MemoryContext::m_current, m_firstTable, tlb_invalidate, and ARMFirstTable::unmap().
Field Documentation
m_cache
Arch::Cache ARMPaging::m_cache private
Caching implementation.
Definition at line 149 of file ARMPaging.h.
Referenced by activate(), unmap(), and ~ARMPaging().
m_firstTable
ARMFirstTable* ARMPaging::m_firstTable private
Pointer to the first level page table.
Definition at line 143 of file ARMPaging.h.
Referenced by access(), ARMPaging(), lookup(), map(), releaseRange(), releaseRegion(), and unmap().
m_firstTableAddr
Address ARMPaging::m_firstTableAddr private
Physical address of the first level page table.
Definition at line 146 of file ARMPaging.h.
Referenced by activate(), ARMPaging(), and ~ARMPaging().
The documentation for this class was generated from the following files:
lib/libarch/arm/ARMPaging.h
lib/libarch/arm/ARMPaging.cpp