FreeNOS: Kernel Class Reference
Kernel Class Reference
kernel
FreeNOS kernel implementation.
#include <Kernel.h>
Public Types
enum Result { Success, InvalidBootImage, ProcessError }
Result codes.
Public Member Functions
Kernel (CoreInfo *info)
Constructor function.
SplitAllocator * getAllocator ()
Get physical memory allocator.
ProcessManager * getProcessManager ()
Get process manager.
API * getAPI ()
Get API.
MemoryContext * getMemoryContext ()
Get the current MMU context.
CoreInfo * getCoreInfo ()
Get CoreInfo.
Timer * getTimer ()
Get Timer.
int run ()
Execute the kernel.
void enableIRQ (u32 irq, bool enabled)
Enable or disable an hardware interrupt (IRQ).
virtual void hookIntVector (u32 vec, InterruptHandler h, ulong p)
Hooks a function to an hardware interrupt.
virtual void executeIntVector (u32 vec, CPUState *state)
Execute an interrupt handler.
virtual Result loadBootImage ()
Loads the boot image.
Public Member Functions inherited from Singleton< Kernel >
Singleton (Kernel *obj)
Constructor.
Static Public Member Functions
static Error heap (Address base, Size size)
Initialize heap.
Protected Attributes
SplitAllocator * m_alloc
Physical memory allocator.
ProcessManager * m_procs
Process Manager.
API * m_api
API handlers object.
CoreInfo * m_coreInfo
CoreInfo object for this core.
Vector< List< InterruptHook * > * > m_interrupts
Interrupt handlers.
IntController * m_intControl
Interrupt Controller.
Timer * m_timer
Timer device.
Private Member Functions
virtual Result loadBootProcess (BootImage *image, Address imagePAddr, Size index)
Load a boot program.
Additional Inherited Members
Static Public Attributes inherited from Singleton< Kernel >
static Kernel * instance
One and only instance.
Detailed Description
FreeNOS kernel implementation.
Definition at line 87 of file Kernel.h.
Member Enumeration Documentation
Result
enum Kernel::Result
Result codes.
Enumerator
Success
InvalidBootImage
ProcessError
Definition at line 94 of file Kernel.h.
Constructor & Destructor Documentation
Kernel()
Kernel::Kernel (CoreInfo * info)
Constructor function.
Parameters
info CoreInfo structure for this core.
Definition at line 33 of file Kernel.cpp.
References SplitAllocator::allocate(), Log::append(), BANNER, CoreInfo::bootImageAddress, CoreInfo::bootImageSize, CoreInfo::coreChannelAddress, CoreInfo::coreChannelSize, Sequence< T >::fill(), CoreInfo::heapAddress, CoreInfo::heapSize, Singleton< Log >::instance, CoreInfo::kernel, MemoryMap::KernelData, m_alloc, m_api, m_coreInfo, m_intControl, m_interrupts, m_procs, m_timer, CoreInfo::memory, PAGESIZE, Memory::Range::phys, MemoryMap::range(), MemoryBlock::set(), Memory::Range::size, and ZERO.
Member Function Documentation
enableIRQ()
void Kernel::enableIRQ (u32 irq, bool enabled)
Enable or disable an hardware interrupt (IRQ).
Parameters
irq IRQ number.
enabled True to enable, and false to disable.
Definition at line 125 of file Kernel.cpp.
References IntController::disable(), IntController::enable(), and m_intControl.
Referenced by IntelKernel::clocktick(), executeIntVector(), IntelKernel::IntelKernel(), and ProcessCtlHandler().
executeIntVector()
void Kernel::executeIntVector (u32 vec, CPUState * state) virtual
Execute an interrupt handler.
Parameters
vec Interrupt vector.
state CPU state.
Definition at line 152 of file Kernel.cpp.
References enableIRQ(), ListIterator< T >::hasCurrent(), and m_interrupts.
Referenced by executeInterrupt(), and ARMKernel::interrupt().
getAllocator()
SplitAllocator * Kernel::getAllocator ()
Get physical memory allocator.
Returns
SplitAllocator object pointer
Definition at line 95 of file Kernel.cpp.
References m_alloc.
Referenced by ProcessShares::releaseShare(), SystemInfoHandler(), and IntelProcess::~IntelProcess().
getAPI()
API * Kernel::getAPI ()
Get API.
Returns
Kernel API object pointer.
Definition at line 105 of file Kernel.cpp.
References m_api.
Referenced by IntelKernel::trap(), and ARMKernel::trap().
getCoreInfo()
CoreInfo * Kernel::getCoreInfo ()
Get CoreInfo.
Returns
CoreInfo object pointer
Definition at line 115 of file Kernel.cpp.
References m_coreInfo.
Referenced by ProcessShares::createShare(), and SystemInfoHandler().
getMemoryContext()
MemoryContext * Kernel::getMemoryContext ()
Get the current MMU context.
Returns
MemoryContext object pointer
Definition at line 110 of file Kernel.cpp.
References ProcessManager::current(), Process::getMemoryContext(), and m_procs.
getProcessManager()
ProcessManager * Kernel::getProcessManager ()
Get process manager.
Returns
Kernel ProcessManager object pointer.
Definition at line 100 of file Kernel.cpp.
References m_procs.
Referenced by IntelKernel::clocktick(), ProcessShares::createShare(), ARMKernel::dataAbort(), IntelKernel::exception(), ARMKernel::interrupt(), ARMKernel::prefetchAbort(), PrivExecHandler(), ProcessCtlHandler(), ProcessShares::releaseShare(), ARMKernel::reserved(), ARMKernel::trap(), ARMKernel::undefinedInstruction(), VMCopyHandler(), VMCtlHandler(), VMShareHandler(), and ProcessShares::~ProcessShares().
getTimer()
Timer * Kernel::getTimer ()
Get Timer.
Returns
Timer object pointer
Definition at line 120 of file Kernel.cpp.
References m_timer.
heap()
Error Kernel::heap (Address base, Size size) static
Initialize heap.
This function sets up the kernel heap for dynamic memory allocation with new() and delete() operators. It must be called before any object is created using new().
Returns
Zero on success or error code on failure.
Definition at line 77 of file Kernel.cpp.
References MemoryBlock::set(), Allocator::setDefault(), and Allocator::setParent().
Referenced by kernel_main().
hookIntVector()
void Kernel::hookIntVector (u32 vec, InterruptHandler h, ulong p) virtual
Hooks a function to an hardware interrupt.
Parameters
vec Interrupt vector to hook on.
h Handler function.
p Parameter to pass to the handler function.
Definition at line 136 of file Kernel.cpp.
References Vector< T >::insert(), and m_interrupts.
Referenced by IntelKernel::IntelKernel(), and ProcessCtlHandler().
loadBootImage()
Kernel::Result Kernel::loadBootImage () virtual
Loads the boot image.
Definition at line 173 of file Kernel.cpp.
References BOOTIMAGE_MAGIC0, BOOTIMAGE_MAGIC1, BOOTIMAGE_REVISION, CoreInfo::bootImageAddress, CoreInfo::bootImageSize, ERROR, InvalidBootImage, BootImage::layoutRevision, loadBootProcess(), m_alloc, m_coreInfo, BootImage::magic, NOTICE, Success, BootImage::symbolTableCount, and SplitAllocator::toVirtual().
Referenced by run().
loadBootProcess()
Kernel::Result Kernel::loadBootProcess (BootImage * image, Address imagePAddr, Size index) private virtual
Load a boot program.
Parameters
image BootImage pointer loaded by the bootloader in kernel virtual memory.
imagePAddr Physical memory address of the boot image.
index Index in the BootProcess table.
Definition at line 195 of file Kernel.cpp.
References Memory::Range::access, SplitAllocator::allocateLow(), BOOTIMAGE_NAMELEN, BootProgram, MemoryBlock::copy(), ProcessManager::create(), BootSymbol::entry, Memory::Executable, FATAL, Process::getMemoryContext(), InvalidBootImage, m_alloc, m_procs, MemoryContext::map(), MemoryContext::mapRange(), BootSymbol::name, NOTICE, PAGESIZE, Memory::Range::phys, ProcessError, MemoryMap::range(), Memory::Readable, Process::Ready, BootSymbol::segmentsCount, BootSymbol::segmentsOffset, BootImage::segmentsTableOffset, MemoryBlock::set(), Process::setState(), Memory::Range::size, BootSegment::size, Success, BootImage::symbolTableOffset, SplitAllocator::toVirtual(), BootSymbol::type, Memory::User, MemoryMap::UserArgs, and Memory::Writable.
Referenced by loadBootImage().
run()
int Kernel::run (void)
Execute the kernel.
Definition at line 253 of file Kernel.cpp.
References ProcessManager::getScheduler(), loadBootImage(), m_procs, m_timer, NOTICE, ProcessManager::schedule(), and Scheduler::setTimer().
Referenced by kernel_main().
Field Documentation
m_alloc
SplitAllocator* Kernel::m_alloc protected
Physical memory allocator.
Definition at line 211 of file Kernel.h.
Referenced by getAllocator(), IntelKernel::IntelKernel(), Kernel(), loadBootImage(), and loadBootProcess().
m_api
API* Kernel::m_api protected
API handlers object.
Definition at line 217 of file Kernel.h.
Referenced by getAPI(), and Kernel().
m_coreInfo
CoreInfo* Kernel::m_coreInfo protected
CoreInfo object for this core.
Definition at line 220 of file Kernel.h.
Referenced by getCoreInfo(), IntelKernel::IntelKernel(), Kernel(), and loadBootImage().
m_intControl
IntController* Kernel::m_intControl protected
Interrupt Controller.
Definition at line 226 of file Kernel.h.
Referenced by ARMKernel::ARMKernel(), enableIRQ(), IntelKernel::IntelKernel(), IntelKernel::interrupt(), ARMKernel::interrupt(), and Kernel().
m_interrupts
Vector<List<InterruptHook *> *> Kernel::m_interrupts protected
Interrupt handlers.
Definition at line 223 of file Kernel.h.
Referenced by executeIntVector(), hookIntVector(), and Kernel().
m_procs
ProcessManager* Kernel::m_procs protected
Process Manager.
Definition at line 214 of file Kernel.h.
Referenced by getMemoryContext(), getProcessManager(), Kernel(), loadBootProcess(), and run().
m_timer
Timer* Kernel::m_timer protected
Timer device.
Definition at line 229 of file Kernel.h.
Referenced by ARMKernel::ARMKernel(), IntelKernel::clocktick(), getTimer(), IntelKernel::IntelKernel(), ARMKernel::interrupt(), Kernel(), and run().
The documentation for this class was generated from the following files:
kernel/Kernel.h
kernel/Kernel.cpp