FreeNOS: HashIterator< K, V > Class Template Reference
HashIterator< K, V > Class Template Reference
lib » libstd
Iterate through a HashTable.
#include <HashIterator.h>
Public Member Functions
HashIterator (HashTable< K, V > &hash)
Class constructor.
virtual ~HashIterator ()
Destructor.
virtual void reset ()
Reset the iterator.
virtual bool hasNext () const
Check if there is more to iterate.
virtual bool hasCurrent () const
Check if there is a current item.
virtual const V & current () const
Get the current value (read-only).
virtual V & current ()
Get the current value.
virtual const K & key ()
Get the current key.
virtual V & next ()
Fetch the next item.
virtual bool remove ()
Remove the current item from the underlying Container.
virtual void operator++ (int num)
Increment operator.
Public Member Functions inherited from Iterator< V >
virtual ~Iterator ()
Destructor.
Private Attributes
HashTable< K, V > & m_hash
Points to the HashTable to iterate.
List< K > m_keys
List of keys to iterate.
ListIterator< K > m_iter
Iterator of keys.
Detailed Description
template<class K, class V>
class HashIterator< K, V >
Iterate through a HashTable.
Definition at line 39 of file HashIterator.h.
Constructor & Destructor Documentation
HashIterator()
template<class K , class V > HashIterator< K, V >::HashIterator (HashTable< K, V > & hash) inline
Class constructor.
Parameters
hash Reference to the HashTable to iterate.
Definition at line 48 of file HashIterator.h.
References assertRead.
~HashIterator()
template<class K , class V > virtual HashIterator< K, V >::~HashIterator () inline virtual
Destructor.
Definition at line 57 of file HashIterator.h.
Member Function Documentation
current() [1/2]
template<class K , class V > virtual const V& HashIterator< K, V >::current () const inline virtual
Get the current value (read-only).
Returns
Reference to the current read-only value.
Implements Iterator< V >.
Definition at line 94 of file HashIterator.h.
References ListIterator< T >::current(), HashIterator< K, V >::m_hash, and HashIterator< K, V >::m_iter.
current() [2/2]
template<class K , class V > virtual V& HashIterator< K, V >::current () inline virtual
Get the current value.
Returns
Reference to the current value.
Implements Iterator< V >.
Definition at line 104 of file HashIterator.h.
References ListIterator< T >::current(), HashIterator< K, V >::m_hash, and HashIterator< K, V >::m_iter.
hasCurrent()
template<class K , class V > virtual bool HashIterator< K, V >::hasCurrent () const inline virtual
Check if there is a current item.
Returns
True if the iterator has a current item, false otherwise.
Implements Iterator< V >.
Definition at line 84 of file HashIterator.h.
References ListIterator< T >::hasCurrent(), and HashIterator< K, V >::m_iter.
Referenced by FileSystem::clearFileCache(), HelpCommand::execute(), ChannelServer< FileSystem, FileSystemMessage >::readChannels(), ChannelClient::receiveAny(), ArgumentContainer::~ArgumentContainer(), and ArgumentParser::~ArgumentParser().
hasNext()
template<class K , class V > virtual bool HashIterator< K, V >::hasNext () const inline virtual
Check if there is more to iterate.
Returns
true if more items, false if not.
Implements Iterator< V >.
Definition at line 74 of file HashIterator.h.
References ListIterator< T >::hasNext(), and HashIterator< K, V >::m_iter.
key()
template<class K , class V > virtual const K& HashIterator< K, V >::key () inline virtual
Get the current key.
Returns
Reference to the current key.
Definition at line 114 of file HashIterator.h.
References ListIterator< T >::current(), and HashIterator< K, V >::m_iter.
Referenced by HashIterator< K, V >::remove().
next()
template<class K , class V > virtual V& HashIterator< K, V >::next () inline virtual
Fetch the next item.
This function first fetches the next item and then updates the current item pointer to that item.
Returns
Reference to the next item.
Implements Iterator< V >.
Definition at line 127 of file HashIterator.h.
References HashIterator< K, V >::m_hash, HashIterator< K, V >::m_iter, and ListIterator< T >::next().
operator++()
template<class K , class V > virtual void HashIterator< K, V >::operator++ (int num) inline virtual
Increment operator.
This function first increment the current item and then updates the next item pointer.
Parameters
num Ignored
Implements Iterator< V >.
Definition at line 152 of file HashIterator.h.
References HashIterator< K, V >::m_iter.
remove()
template<class K , class V > virtual bool HashIterator< K, V >::remove () inline virtual
Remove the current item from the underlying Container.
Returns
True if removed successfully, false otherwise.
Implements Iterator< V >.
Definition at line 137 of file HashIterator.h.
References ListIterator< T >::current(), HashIterator< K, V >::key(), HashIterator< K, V >::m_hash, HashIterator< K, V >::m_iter, and ListIterator< T >::remove().
reset()
template<class K , class V > virtual void HashIterator< K, V >::reset () inline virtual
Reset the iterator.
Implements Iterator< V >.
Definition at line 64 of file HashIterator.h.
References HashIterator< K, V >::m_iter, and ListIterator< T >::reset().
Field Documentation
m_hash
template<class K , class V > HashTable<K, V>& HashIterator< K, V >::m_hash private
Points to the HashTable to iterate.
Definition at line 160 of file HashIterator.h.
Referenced by HashIterator< K, V >::current(), HashIterator< K, V >::next(), and HashIterator< K, V >::remove().
m_iter
template<class K , class V > ListIterator<K> HashIterator< K, V >::m_iter private
Iterator of keys.
Definition at line 166 of file HashIterator.h.
Referenced by HashIterator< K, V >::current(), HashIterator< K, V >::hasCurrent(), HashIterator< K, V >::hasNext(), HashIterator< K, V >::key(), HashIterator< K, V >::next(), HashIterator< K, V >::operator++(), HashIterator< K, V >::remove(), and HashIterator< K, V >::reset().
m_keys
template<class K , class V > List<K> HashIterator< K, V >::m_keys private
List of keys to iterate.
Definition at line 163 of file HashIterator.h.
The documentation for this class was generated from the following file:
lib/libstd/HashIterator.h