FreeNOS: USBController Class Reference
USBController Class Reference abstract
lib » libusb
USB controller abstract interface.
#include <USBController.h>
Public Member Functions
USBController (const char *path)
Constructor.
virtual Error initialize ()
Initialize the Controller.
virtual Error transfer (const FileSystemMessage *msg, USBMessage *usb)=0
Submit USB transfer.
Public Member Functions inherited from DeviceServer
DeviceServer (const char *path)
Constructor.
virtual ~DeviceServer ()
Destructor.
void registerDevice (Device *dev, const char *path,...)
Add a Device.
void registerInterrupt (Device *dev, Size vector)
Register an interrupt vector for the given device.
virtual void interruptHandler (Size vector)
Interrupt request handler.
Public Member Functions inherited from FileSystem
FileSystem (const char *path)
Constructor function.
virtual ~FileSystem ()
Destructor function.
const char * getMountPath () const
Get mount path.
Directory * getRoot ()
Get root directory.
Error mount ()
Mount the FileSystem.
Error registerFile (File *file, const char *path,...)
Register a new File.
Error registerFile (File *file, const char *path, va_list args)
Register a new File with variable arguments.
virtual File * createFile (FileType type, DeviceID deviceID)
Create a new file.
FileCache * insertFileCache (File *file, const char *pathFormat,...)
Inserts a file into the in-memory filesystem tree.
FileCache * insertFileCache (File *file, const char *pathFormat, va_list args)
Inserts a file into the in-memory filesystem tree.
void pathHandler (FileSystemMessage *msg)
Process an incoming filesystem request using a path.
virtual void timeout ()
Called when a sleep timeout is expired.
virtual bool retryRequests ()
Retry any pending requests.
Public Member Functions inherited from ChannelServer< FileSystem, FileSystemMessage >
ChannelServer (FileSystem *inst, Size num=32)
Constructor function.
virtual ~ChannelServer ()
Destructor function.
int run ()
Enters an infinite loop, serving incoming requests.
void addIPCHandler (Size slot, IPCHandlerFunction h, bool sendReply=true)
Register a new IPC message action handler.
void addIRQHandler (Size slot, IRQHandlerFunction h)
Register a new IRQ message vector handler.
void setTimeout (uint msec)
Set a sleep timeout.
Protected Attributes
Arch::IO m_io
I/O instance.
Protected Attributes inherited from FileSystem
FileCache * m_root
Root entry of the filesystem tree.
const char * m_mountPath
Mount point.
List< FileSystemRequest * > * m_requests
Contains ongoing requests.
Protected Attributes inherited from ChannelServer< FileSystem, FileSystemMessage >
ChannelRegistry * m_registry
Contains registered channels.
ChannelClient * m_client
Client for sending replies.
MemoryChannel m_kernelEvent
Kernel event channel.
bool m_sendReply
Should we send a reply message?
Vector< MessageHandler< IPCHandlerFunction > *> * m_ipcHandlers
IPC handler functions.
Vector< MessageHandler< IRQHandlerFunction > *> * m_irqHandlers
IRQ handler functions.
FileSystem * m_instance
Server object instance.
ProcessID m_self
ProcessID of ourselves.
Timer::Info m_time
System timer value.
Additional Inherited Members
Public Types inherited from ChannelServer< FileSystem, FileSystemMessage >
enum Result
Result codes.
Protected Types inherited from ChannelServer< FileSystem, FileSystemMessage >
typedef void(FileSystem ::* IPCHandlerFunction) (FileSystemMessage *)
Member function pointer inside Base, to handle IPC messages.
typedef void(FileSystem ::* IRQHandlerFunction) (Size)
Member function pointer inside Base, to handle interrupts.
Protected Member Functions inherited from FileSystem
Error processRequest (FileSystemRequest *req)
Process a FileSystemRequest.
void sendResponse (FileSystemMessage *msg)
Send response for a FileSystemMessage.
void setRoot (Directory *newRoot)
Change the filesystem root directory.
FileCache * lookupFile (FileSystemPath *path)
Retrieve a File from storage.
FileCache * findFileCache (char *path)
Search the cache for an entry.
FileCache * findFileCache (String *path)
Search the cache for an entry.
FileCache * findFileCache (FileSystemPath *p)
Search the cache for an entry.
virtual FileCache * cacheHit (FileCache *cache)
Process a cache hit.
void clearFileCache (FileCache *cache=ZERO)
Cleans up the entire file cache (except opened file caches and root).
Detailed Description
USB controller abstract interface.
Definition at line 38 of file USBController.h.
Constructor & Destructor Documentation
USBController()
USBController::USBController (const char * path)
Constructor.
Definition at line 21 of file USBController.cpp.
Member Function Documentation
initialize()
Error USBController::initialize () virtual
Initialize the Controller.
Returns
Result code
Reimplemented from DeviceServer.
Reimplemented in SynopsisController.
Definition at line 26 of file USBController.cpp.
References ESUCCESS, DeviceServer::initialize(), and FileSystem::registerFile().
Referenced by SynopsisController::initialize().
transfer()
virtual Error USBController::transfer (const FileSystemMessage * msg, USBMessage * usb) pure virtual
Submit USB transfer.
Returns
Result code
Implemented in SynopsisController.
Referenced by USBTransferFile::write().
Field Documentation
m_io
Arch::IO USBController::m_io protected
I/O instance.
Definition at line 65 of file USBController.h.
Referenced by SynopsisController::hostPortChanged(), SynopsisController::initialize(), SynopsisController::interruptHandler(), SynopsisController::softReset(), and SynopsisController::SynopsisController().
The documentation for this class was generated from the following files:
lib/libusb/USBController.h
lib/libusb/USBController.cpp