FreeNOS: LCDBar Class Reference
LCDBar Class Reference
server » grovepi
GrovePi LCD Bar.
#include <LCDBar.h>
Public Member Functions
LCDBar (I2C *i2c)
Constructor function.
virtual Error initialize ()
Initializes the class.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Set LCD Bar text.
Public Member Functions inherited from Device
Device (FileType type)
Constructor.
virtual ~Device ()
Destructor.
virtual const String & getIdentifier () const
Get unique device identifier.
virtual Error interrupt (Size vector)
Called when an interrupt has been triggered for this device.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read bytes from the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Types
enum Command {
ClearDisplay = 0x01, NoCursor = 0x04, DisplayOn = 0x08, DoubleLine = 0x28,
Newline = 0xc0, WriteChar = 0x40
}
LCDBar commands.
Private Member Functions
void setRGB (uint r, uint g, uint b)
Set LCD color.
void setText (const char *text, Size max)
Set LCD text.
void textCommand (Command cmd)
Send I2C text command.
Private Attributes
I2C * m_i2c
I2C controller.
Static Private Attributes
static const uint RGBAddr = 0x62
static const uint TextAddr = 0x3e
Additional Inherited Members
Protected Attributes inherited from Device
String m_identifier
Unique identifier for this Device.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
GrovePi LCD Bar.
See also
https://github.com/DexterInd/GrovePi/blob/master/Firmware/Source/v1.2/grove_pi_v1_2_5/README.md
Definition at line 39 of file LCDBar.h.
Member Enumeration Documentation
Command
enum LCDBar::Command private
LCDBar commands.
Enumerator
ClearDisplay
NoCursor
DisplayOn
DoubleLine
Newline
WriteChar
Definition at line 49 of file LCDBar.h.
Constructor & Destructor Documentation
LCDBar()
LCDBar::LCDBar (I2C * i2c)
Constructor function.
Definition at line 21 of file LCDBar.cpp.
References m_i2c, and Device::m_identifier.
Member Function Documentation
initialize()
Error LCDBar::initialize () virtual
Initializes the class.
Returns
Error status code.
Reimplemented from Device.
Definition at line 28 of file LCDBar.cpp.
References ESUCCESS.
setRGB()
void LCDBar::setRGB (uint r, uint g, uint b) private
Set LCD color.
Definition at line 87 of file LCDBar.cpp.
References m_i2c, I2C::setAddress(), and I2C::write().
Referenced by write().
setText()
void LCDBar::setText (const char * text, Size max) private
Set LCD text.
Definition at line 51 of file LCDBar.cpp.
References ClearDisplay, DisplayOn, DoubleLine, m_i2c, Newline, NoCursor, sleep(), textCommand(), and I2C::write().
Referenced by write().
textCommand()
void LCDBar::textCommand (LCDBar::Command cmd) private
Send I2C text command.
Definition at line 40 of file LCDBar.cpp.
References m_i2c, I2C::setAddress(), TextAddr, and I2C::write().
Referenced by setText().
write()
Error LCDBar::write (IOBuffer & buffer, Size size, Size offset) virtual
Set LCD Bar text.
Parameters
buffer Buffer to save the read bytes.
size Number of bytes to read.
offset Offset in the file to read.
Returns
Number of bytes on success and ZERO on failure.
Reimplemented from File.
Definition at line 33 of file LCDBar.cpp.
References IOBuffer::getBuffer(), setRGB(), and setText().
Field Documentation
m_i2c
I2C* LCDBar::m_i2c private
I2C controller.
Definition at line 104 of file LCDBar.h.
Referenced by LCDBar(), setRGB(), setText(), and textCommand().
RGBAddr
const uint LCDBar::RGBAddr = 0x62 static private
Definition at line 43 of file LCDBar.h.
TextAddr
const uint LCDBar::TextAddr = 0x3e static private
Definition at line 44 of file LCDBar.h.
Referenced by textCommand().
The documentation for this class was generated from the following files:
server/i2c/grovepi/LCDBar.h
server/i2c/grovepi/LCDBar.cpp