FreeNOS: TestInstance Class Reference
TestInstance Class Reference abstract
lib » libtest
Represents a test instance.
#include <TestInstance.h>
Public Member Functions
TestInstance (const char *name)
Class constructor.
const String & getName () const
Retrieve test instance name.
virtual TestResult run ()=0
Run the test instance.
Protected Attributes
String m_name
Name of the test instance.
Detailed Description
Represents a test instance.
Definition at line 35 of file TestInstance.h.
Constructor & Destructor Documentation
TestInstance()
TestInstance::TestInstance (const char * name)
Class constructor.
Parameters
name Name of the test
Definition at line 21 of file TestInstance.cpp.
References TestSuite::addTest(), and Singleton< TestSuite >::instance.
Member Function Documentation
getName()
const String & TestInstance::getName () const
Retrieve test instance name.
Returns
Test instance name
Definition at line 31 of file TestInstance.cpp.
References m_name.
Referenced by TAPReporter::reportAfter().
run()
virtual TestResult TestInstance::run () pure virtual
Run the test instance.
Returns
TestResult
Implemented in LocalTest, and ExternalTest.
Referenced by TestRunner::run().
Field Documentation
m_name
String TestInstance::m_name protected
Name of the test instance.
Definition at line 63 of file TestInstance.h.
Referenced by getName(), StdoutReporter::reportBefore(), and ExternalTest::run().
The documentation for this class was generated from the following files:
lib/libtest/TestInstance.h
lib/libtest/TestInstance.cpp