FreeNOS: POSIXApplication Class Reference
POSIXApplication Class Reference
lib » libposix
POSIX-compatible application.
#include <POSIXApplication.h>
Public Member Functions
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Protected Member Functions
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result exec ()=0
Execute the application event loop.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Detailed Description
POSIX-compatible application.
Definition at line 34 of file POSIXApplication.h.
Constructor & Destructor Documentation
POSIXApplication()
POSIXApplication::POSIXApplication (int argc, char ** argv)
Class constructor.
Parameters
argc Argument count
argv Argument values
Definition at line 24 of file POSIXApplication.cpp.
References Application::setVersion().
~POSIXApplication()
POSIXApplication::~POSIXApplication () virtual
Class destructor.
Definition at line 30 of file POSIXApplication.cpp.
Member Function Documentation
output()
POSIXApplication::Result POSIXApplication::output (const char * string) const protected virtual
Print text to output.
Parameters
string Text to print to program output.
Returns
Result code.
Implements Application.
Definition at line 34 of file POSIXApplication.cpp.
References printf(), and Application::Success.
Referenced by SievePrime::exec().
The documentation for this class was generated from the following files:
lib/libposix/POSIXApplication.h
lib/libposix/POSIXApplication.cpp