FreeNOS: TestReporter Class Reference
TestReporter Class Reference abstract
lib » libtest
Responsible for outputting test results.
#include <TestReporter.h>
Public Member Functions
TestReporter (int argc, char **argv)
Constructor.
virtual ~TestReporter ()
Destructor.
uint getOk () const
Get OK count.
uint getFailed () const
Get fail count.
uint getSkipped () const
Get skip count.
void setReport (bool value)
Set reporting on/off.
void setStatistics (bool value)
Set show statistics on/off.
virtual void prepare (TestInstance &test)
Prepare for next test.
virtual void collect (TestInstance &test, TestResult &result)
Collect test statistics.
virtual void begin (List< TestInstance *> &tests)
Begin testing.
virtual void finish (List< TestInstance *> &tests)
Finish testing.
Protected Member Functions
virtual void reportBegin (List< TestInstance *> &tests)=0
Report start of testing.
virtual void reportBefore (TestInstance &test)=0
Report start of a test.
virtual void reportAfter (TestInstance &test, TestResult &result)=0
Report finish of a test.
virtual void reportFinish (List< TestInstance *> &tests)=0
Report completion of all tests.
Protected Attributes
int m_argc
Argument count.
char ** m_argv
Argument values.
bool m_report
Report on/off.
bool m_showStatistics
Show final statistics.
uint m_ok
Test statistics.
uint m_fail
uint m_skip
Detailed Description
Responsible for outputting test results.
Definition at line 35 of file TestReporter.h.
Constructor & Destructor Documentation
TestReporter()
TestReporter::TestReporter (int argc, char ** argv)
Constructor.
Definition at line 21 of file TestReporter.cpp.
References m_argc, m_argv, m_fail, m_ok, m_report, m_showStatistics, and m_skip.
~TestReporter()
TestReporter::~TestReporter () virtual
Destructor.
Definition at line 32 of file TestReporter.cpp.
Member Function Documentation
begin()
void TestReporter::begin (List< TestInstance *> & tests) virtual
Begin testing.
Definition at line 82 of file TestReporter.cpp.
References m_showStatistics, and reportBegin().
Referenced by TestRunner::run().
collect()
void TestReporter::collect (TestInstance & test, TestResult & result) virtual
Collect test statistics.
Definition at line 67 of file TestReporter.cpp.
References TestResult::isFailed(), TestResult::isOK(), TestResult::isSkipped(), m_fail, m_ok, m_report, m_skip, and reportAfter().
Referenced by TestRunner::run().
finish()
void TestReporter::finish (List< TestInstance *> & tests) virtual
Finish testing.
Definition at line 88 of file TestReporter.cpp.
References m_showStatistics, and reportFinish().
Referenced by TestRunner::run().
getFailed()
uint TestReporter::getFailed () const
Get fail count.
Definition at line 41 of file TestReporter.cpp.
References m_fail.
Referenced by TestRunner::run().
getOk()
uint TestReporter::getOk () const
Get OK count.
Definition at line 36 of file TestReporter.cpp.
References m_ok.
getSkipped()
uint TestReporter::getSkipped () const
Get skip count.
Definition at line 46 of file TestReporter.cpp.
References m_skip.
prepare()
void TestReporter::prepare (TestInstance & test) virtual
Prepare for next test.
Definition at line 61 of file TestReporter.cpp.
References m_report, and reportBefore().
Referenced by TestRunner::run().
reportAfter()
virtual void TestReporter::reportAfter (TestInstance & test, TestResult & result) protected pure virtual
Report finish of a test.
Implemented in TAPReporter, and StdoutReporter.
Referenced by collect().
reportBefore()
virtual void TestReporter::reportBefore (TestInstance & test) protected pure virtual
Report start of a test.
Implemented in TAPReporter, and StdoutReporter.
Referenced by prepare().
reportBegin()
virtual void TestReporter::reportBegin (List< TestInstance *> & tests) protected pure virtual
Report start of testing.
Implemented in TAPReporter, and StdoutReporter.
Referenced by begin().
reportFinish()
virtual void TestReporter::reportFinish (List< TestInstance *> & tests) protected pure virtual
Report completion of all tests.
Implemented in TAPReporter, and StdoutReporter.
Referenced by finish().
setReport()
void TestReporter::setReport (bool value)
Set reporting on/off.
Definition at line 51 of file TestReporter.cpp.
References m_report.
setStatistics()
void TestReporter::setStatistics (bool value)
Set show statistics on/off.
Definition at line 56 of file TestReporter.cpp.
References m_showStatistics.
Referenced by TestRunner::TestRunner().
Field Documentation
m_argc
int TestReporter::m_argc protected
Argument count.
Definition at line 119 of file TestReporter.h.
Referenced by TestReporter().
m_argv
char** TestReporter::m_argv protected
Argument values.
Definition at line 122 of file TestReporter.h.
Referenced by StdoutReporter::reportBefore(), TAPReporter::reportBegin(), StdoutReporter::reportFinish(), TAPReporter::reportFinish(), and TestReporter().
m_fail
uint TestReporter::m_fail protected
Definition at line 131 of file TestReporter.h.
Referenced by collect(), getFailed(), StdoutReporter::reportFinish(), and TestReporter().
m_ok
uint TestReporter::m_ok protected
Test statistics.
Definition at line 131 of file TestReporter.h.
Referenced by collect(), getOk(), StdoutReporter::reportFinish(), and TestReporter().
m_report
bool TestReporter::m_report protected
Report on/off.
Definition at line 125 of file TestReporter.h.
Referenced by collect(), prepare(), setReport(), and TestReporter().
m_showStatistics
bool TestReporter::m_showStatistics protected
Show final statistics.
Definition at line 128 of file TestReporter.h.
Referenced by begin(), finish(), setStatistics(), and TestReporter().
m_skip
uint TestReporter::m_skip protected
Definition at line 131 of file TestReporter.h.
Referenced by collect(), getSkipped(), StdoutReporter::reportFinish(), and TestReporter().
The documentation for this class was generated from the following files:
lib/libtest/TestReporter.h
lib/libtest/TestReporter.cpp