FreeNOS: Cat Class Reference
Cat Class Reference
bin
Concatenate files to standard output.
#include <Cat.h>
Public Member Functions
Cat (int argc, char **argv)
Constructor.
virtual ~Cat ()
Destructor.
virtual Result initialize ()
Initialize the application.
virtual Result exec ()
Execute the application.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Private Member Functions
Result cat (const char *file) const
Concatenate a file.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
Concatenate files to standard output.
Definition at line 31 of file Cat.h.
Constructor & Destructor Documentation
Cat()
Cat::Cat (int argc, char ** argv)
Constructor.
Parameters
argc Argument count
argv Argument values
Definition at line 28 of file Cat.cpp.
References Application::parser(), ArgumentParser::registerPositional(), and ArgumentParser::setDescription().
~Cat()
Cat::~Cat () virtual
Destructor.
Definition at line 35 of file Cat.cpp.
Member Function Documentation
cat()
Cat::Result Cat::cat (const char * file) const private
Concatenate a file.
Parameters
file Name of file to concatenate
Returns
Result code
Definition at line 65 of file Cat.cpp.
References close(), DEBUG, errno, Application::InvalidArgument, Application::IOError, memset(), name, ArgumentParser::name(), Application::NotFound, O_RDONLY, open(), PAGESIZE, Application::parser(), printf(), read(), refreshMounts(), S_ISCHR, S_ISREG, stat::st_mode, stat(), strerror(), and Application::Success.
Referenced by exec().
exec()
Cat::Result Cat::exec () virtual
Execute the application.
Returns
Result code
Implements Application.
Definition at line 44 of file Cat.cpp.
References Application::arguments(), cat(), Vector< T >::count(), ArgumentContainer::getPositionals(), and Application::Success.
initialize()
Cat::Result Cat::initialize () virtual
Initialize the application.
Check if excuted with at least one positional.
Returns
Result code. If has no positional, return ShowUsage; else return Success.
Reimplemented from Application.
Definition at line 39 of file Cat.cpp.
References Application::arguments(), Vector< T >::count(), ArgumentContainer::getPositionals(), Application::ShowUsage, and Application::Success.
The documentation for this class was generated from the following files:
bin/cat/Cat.h
bin/cat/Cat.cpp