FreeNOS: FileSystemPath Class Reference
FileSystemPath Class Reference
lib » libfs
Simple filesystem path parser.
#include <FileSystemPath.h>
Public Member Functions
FileSystemPath ()
Default constructor.
FileSystemPath (char *path, char separator=DEFAULT_SEPARATOR)
Alternative Constructor.
FileSystemPath (String *s, char separator=DEFAULT_SEPARATOR)
Constructor using a String.
virtual ~FileSystemPath ()
Destructor.
void parse (const char *p, char sep=DEFAULT_SEPARATOR)
Parses a given character string as the path.
String * parent () const
Retrieve the full path of our parent.
String * base () const
The name of the last element in the path.
String * full () const
Get the full path as a String instance.
List< String * > * split ()
Returns a List of separate path elements.
Size length () const
Get Length of our full path.
Private Attributes
List< String * > m_path
The path split in pieces.
String * m_fullPath
Full input path.
Size m_fullLength
Full length of the given path.
String * m_parentPath
Full path to our parent.
char m_separator
Separator character.
Detailed Description
Simple filesystem path parser.
Definition at line 43 of file FileSystemPath.h.
Constructor & Destructor Documentation
FileSystemPath() [1/3]
FileSystemPath::FileSystemPath ()
Default constructor.
Definition at line 29 of file FileSystemPath.cpp.
FileSystemPath() [2/3]
FileSystemPath::FileSystemPath (char * path, char separator = DEFAULT_SEPARATOR)
Alternative Constructor.
Parameters
path The input path to parse.
separator Pathname separator.
Definition at line 37 of file FileSystemPath.cpp.
References parse().
FileSystemPath() [3/3]
FileSystemPath::FileSystemPath (String * s, char separator = DEFAULT_SEPARATOR)
Constructor using a String.
Parameters
s String containing the path to parse.
separator Pathname separator.
Definition at line 45 of file FileSystemPath.cpp.
References parse().
~FileSystemPath()
FileSystemPath::~FileSystemPath () virtual
Destructor.
Definition at line 53 of file FileSystemPath.cpp.
References List< T >::clear(), ListIterator< T >::hasCurrent(), m_fullPath, m_parentPath, and m_path.
Member Function Documentation
base()
String * FileSystemPath::base () const
The name of the last element in the path.
Returns
Name of the base.
Definition at line 109 of file FileSystemPath.cpp.
References List< T >::last(), and m_path.
Referenced by FileSystem::insertFileCache(), and FileSystem::registerFile().
full()
String * FileSystemPath::full () const
Get the full path as a String instance.
Returns
String instance.
Definition at line 114 of file FileSystemPath.cpp.
References m_fullPath.
Referenced by FileSystem::processRequest().
length()
Size FileSystemPath::length () const
Get Length of our full path.
Returns
Length.
Definition at line 124 of file FileSystemPath.cpp.
References m_fullLength.
Referenced by FileSystem::findFileCache().
parent()
String * FileSystemPath::parent () const
Retrieve the full path of our parent.
Returns
Path of our parent.
Definition at line 104 of file FileSystemPath.cpp.
References m_parentPath.
Referenced by FileSystem::findFileCache(), FileSystem::insertFileCache(), FileSystem::processRequest(), and FileSystem::registerFile().
parse()
void FileSystemPath::parse (const char * p, char sep = DEFAULT_SEPARATOR)
Parses a given character string as the path.
Parameters
p Path to parse.
separator Pathname separator.
Definition at line 64 of file FileSystemPath.cpp.
References List< T >::append(), ListIterator< T >::hasCurrent(), List< T >::head(), m_fullLength, m_fullPath, m_parentPath, m_path, m_separator, memset(), String::split(), strcat(), strlen(), strncat(), and ZERO.
Referenced by chdir(), FileSystemPath(), FileSystem::insertFileCache(), and FileSystem::processRequest().
split()
List< String * > * FileSystemPath::split ()
Returns a List of separate path elements.
Returns
Pointer to a List.
Definition at line 119 of file FileSystemPath.cpp.
References m_path.
Referenced by chdir(), FileSystem::findFileCache(), and FileSystem::lookupFile().
Field Documentation
m_fullLength
Size FileSystemPath::m_fullLength private
Full length of the given path.
Definition at line 125 of file FileSystemPath.h.
Referenced by length(), and parse().
m_fullPath
String* FileSystemPath::m_fullPath private
Full input path.
Definition at line 122 of file FileSystemPath.h.
Referenced by full(), parse(), and ~FileSystemPath().
m_parentPath
String* FileSystemPath::m_parentPath private
Full path to our parent.
Definition at line 128 of file FileSystemPath.h.
Referenced by parent(), parse(), and ~FileSystemPath().
m_path
List<String *> FileSystemPath::m_path private
The path split in pieces.
Definition at line 119 of file FileSystemPath.h.
Referenced by base(), parse(), split(), and ~FileSystemPath().
m_separator
char FileSystemPath::m_separator private
Separator character.
Definition at line 131 of file FileSystemPath.h.
Referenced by parse().
The documentation for this class was generated from the following files:
lib/libfs/FileSystemPath.h
lib/libfs/FileSystemPath.cpp