FreeNOS: SplitAllocator Class Reference
SplitAllocator Class Reference
lib » liballoc
Allocator which separates kernel mapped low-memory and higher memory.
#include <SplitAllocator.h>
Public Member Functions
SplitAllocator (Memory::Range low, Memory::Range high)
Class constructor.
virtual ~SplitAllocator ()
Class destructor.
virtual Size size () const
Get memory size.
virtual Size available () const
Get memory available.
virtual Result allocate (Size *size, Address *addr, Size align=ZERO)
Allocate memory.
Result allocate (Address addr)
Allocate address.
virtual Result allocateLow (Size size, Address *addr, Size align=ZERO)
Allocate from lower memory.
virtual Result allocateHigh (Size size, Address *addr, Size align=ZERO)
Allocate from high memory.
virtual Result release (Address addr)
Release memory.
void * toVirtual (Address phys) const
Convert the given physical address to lower virtual accessible address.
void * toPhysical (Address virt) const
Convert lower virtual address back to system level physical address.
Public Member Functions inherited from Allocator
Allocator ()
Class constructor.
virtual ~Allocator ()
Class destructor.
void setParent (Allocator *parent)
Set parent allocator.
Result setAlignment (Size size)
Set allocation alignment.
Result setBase (Address addr)
Set allocation base.
Private Attributes
BitAllocator * m_alloc
Physical memory allocator.
Memory::Range m_low
Low memory.
Memory::Range m_high
High memory.
Additional Inherited Members
Public Types inherited from Allocator
enum Result {
Success = 0, InvalidAddress, InvalidSize, InvalidAlignment,
OutOfMemory
}
Allocation results.
Static Public Member Functions inherited from Allocator
static void setDefault (Allocator *alloc)
Makes the given Allocator the default.
static Allocator * getDefault ()
Retrieve the currently default Allocator.
Protected Member Functions inherited from Allocator
Address aligned (Address addr, Size boundary) const
Align memory address.
Protected Attributes inherited from Allocator
Allocator * m_parent
Our parent Allocator, if any.
Size m_alignment
Allocation memory alignment.
Address m_base
Allocation base address.
Detailed Description
Allocator which separates kernel mapped low-memory and higher memory.
Definition at line 36 of file SplitAllocator.h.
Constructor & Destructor Documentation
SplitAllocator()
SplitAllocator::SplitAllocator (Memory::Range low, Memory::Range high)
Class constructor.
Parameters
low Lower physical memory.
high Higher physical memory.
Definition at line 21 of file SplitAllocator.cpp.
References m_alloc, PAGESIZE, and Memory::Range::size.
~SplitAllocator()
SplitAllocator::~SplitAllocator () virtual
Class destructor.
Definition at line 32 of file SplitAllocator.cpp.
References m_alloc.
Member Function Documentation
allocate() [1/2]
Allocator::Result SplitAllocator::allocate (Size * size, Address * addr, Size align = ZERO) virtual
Allocate memory.
Parameters
size Amount of memory in bytes to allocate on input. On output, the amount of memory in bytes actually allocated.
addr Output parameter which contains the address allocated on success.
align Alignment of the required memory or use ZERO for default.
Returns
Result code
Implements Allocator.
Definition at line 47 of file SplitAllocator.cpp.
References allocateHigh(), allocateLow(), and Allocator::Success.
Referenced by Kernel::Kernel(), and MemoryContext::mapRange().
allocate() [2/2]
Allocator::Result SplitAllocator::allocate (Address addr)
Allocate address.
Parameters
addr Allocate a specific address.
Returns
Result value.
Definition at line 57 of file SplitAllocator.cpp.
References BitAllocator::allocate(), and m_alloc.
allocateHigh()
Allocator::Result SplitAllocator::allocateHigh (Size size, Address * addr, Size align = ZERO) virtual
Allocate from high memory.
Parameters
size Amount of memory in bytes to allocate.
addr Output parameter which contains the address allocated on success.
align Alignment of the required memory or use ZERO for default.
Returns
Result code
Definition at line 67 of file SplitAllocator.cpp.
References BitAllocator::allocate(), BitAllocator::base(), m_alloc, m_high, and Memory::Range::phys.
Referenced by allocate().
allocateLow()
Allocator::Result SplitAllocator::allocateLow (Size size, Address * addr, Size align = ZERO) virtual
Allocate from lower memory.
Parameters
size Amount of memory in bytes to allocate.
addr Output parameter which contains the address allocated on success.
align Alignment of the required memory or use ZERO for default.
Returns
Result code
Definition at line 62 of file SplitAllocator.cpp.
References BitAllocator::allocate(), and m_alloc.
Referenced by allocate(), ARMPaging::ARMPaging(), IntelPaging::IntelPaging(), Kernel::loadBootProcess(), ARMFirstTable::map(), and IntelPageDirectory::map().
available()
Size SplitAllocator::available () const virtual
Get memory available.
Returns
Size of memory available by the Allocator.
Implements Allocator.
Definition at line 42 of file SplitAllocator.cpp.
References BitAllocator::available(), and m_alloc.
Referenced by SystemInfoHandler().
release()
Allocator::Result SplitAllocator::release (Address addr) virtual
Release memory.
Parameters
addr Points to memory previously returned by allocate().
Returns
Result value.
See also
allocate
Implements Allocator.
Definition at line 72 of file SplitAllocator.cpp.
References m_alloc, and BitAllocator::release().
Referenced by MemoryContext::release(), IntelPageDirectory::releaseRange(), ARMFirstTable::releaseRange(), ARMPaging::~ARMPaging(), IntelPaging::~IntelPaging(), and IntelProcess::~IntelProcess().
size()
Size SplitAllocator::size () const virtual
Get memory size.
Returns
Size of memory owned by the Allocator.
Implements Allocator.
Definition at line 37 of file SplitAllocator.cpp.
References m_alloc, and BitAllocator::size().
Referenced by SystemInfoHandler().
toPhysical()
void * SplitAllocator::toPhysical (Address virt) const
Convert lower virtual address back to system level physical address.
Definition at line 82 of file SplitAllocator.cpp.
References m_low, and Memory::Range::phys.
Referenced by IntelProcess::~IntelProcess().
toVirtual()
void * SplitAllocator::toVirtual (Address phys) const
Convert the given physical address to lower virtual accessible address.
Definition at line 77 of file SplitAllocator.cpp.
References m_low, and Memory::Range::phys.
Referenced by ARMPaging::ARMPaging(), IntelPageDirectory::getPageTable(), ARMFirstTable::getSecondTable(), IntelPaging::IntelPaging(), Kernel::loadBootImage(), Kernel::loadBootProcess(), ARMFirstTable::map(), and IntelPageDirectory::map().
Field Documentation
m_alloc
BitAllocator* SplitAllocator::m_alloc private
Physical memory allocator.
Definition at line 137 of file SplitAllocator.h.
Referenced by allocate(), allocateHigh(), allocateLow(), available(), release(), size(), SplitAllocator(), and ~SplitAllocator().
m_high
Memory::Range SplitAllocator::m_high private
High memory.
Definition at line 143 of file SplitAllocator.h.
Referenced by allocateHigh().
m_low
Memory::Range SplitAllocator::m_low private
Low memory.
Definition at line 140 of file SplitAllocator.h.
Referenced by toPhysical(), and toVirtual().
The documentation for this class was generated from the following files:
lib/liballoc/SplitAllocator.h
lib/liballoc/SplitAllocator.cpp