FreeNOS: FileStorage Class Reference
FileStorage Class Reference
lib » libfs
Use a file as Storage provider.
#include <FileStorage.h>
Public Member Functions
FileStorage (const char *path, Size offset=ZERO)
Constructor function.
virtual ~FileStorage ()
Destructor function.
virtual Error read (u64 offset, void *buffer, Size size)
Read a contiguous set of data.
virtual Error write (u64 offset, void *buffer, Size size)
Write a contiguous set of data.
virtual u64 capacity () const
Retrieve maximum storage capacity.
Public Member Functions inherited from Storage
Storage ()
Constructor function.
virtual ~Storage ()
Destructor function.
Private Attributes
int m_file
File descriptor of the file for Storage I/O.
struct stat m_stat
Status of the file for Storage I/O.
Size m_offset
Offset used as a base for I/O.
Detailed Description
Use a file as Storage provider.
See also
Storage
Definition at line 38 of file FileStorage.h.
Constructor & Destructor Documentation
FileStorage()
FileStorage::FileStorage (const char * path, Size offset = ZERO)
Constructor function.
Parameters
path Full path to the file to use.
offset Offset in the file as a base for I/O.
Definition at line 25 of file FileStorage.cpp.
References m_file, m_offset, m_stat, O_RDWR, open(), and stat().
~FileStorage()
FileStorage::~FileStorage () virtual
Destructor function.
Definition at line 32 of file FileStorage.cpp.
References close(), and m_file.
Member Function Documentation
capacity()
u64 FileStorage::capacity () const virtual
Retrieve maximum storage capacity.
Returns
Storage capacity.
Implements Storage.
Definition at line 67 of file FileStorage.cpp.
References m_stat, and stat::st_size.
read()
Error FileStorage::read (u64 offset, void * buffer, Size size) virtual
Read a contiguous set of data.
Parameters
offset Offset to start reading from.
buffer Output buffer.
size Number of bytes to copied.
Returns
Result code
Reimplemented from Storage.
Definition at line 37 of file FileStorage.cpp.
References errno, lseek(), m_file, m_offset, and SEEK_SET.
write()
Error FileStorage::write (u64 offset, void * buffer, Size size) virtual
Write a contiguous set of data.
Parameters
offset Offset to start writing to.
buffer Input buffer.
size Number of bytes to written.
Returns
Result code
Reimplemented from Storage.
Definition at line 52 of file FileStorage.cpp.
References errno, lseek(), m_file, m_offset, and SEEK_SET.
Field Documentation
m_file
int FileStorage::m_file private
File descriptor of the file for Storage I/O.
Definition at line 87 of file FileStorage.h.
Referenced by FileStorage(), read(), write(), and ~FileStorage().
m_offset
Size FileStorage::m_offset private
Offset used as a base for I/O.
Definition at line 93 of file FileStorage.h.
Referenced by FileStorage(), read(), and write().
m_stat
struct stat FileStorage::m_stat private
Status of the file for Storage I/O.
Definition at line 90 of file FileStorage.h.
Referenced by capacity(), and FileStorage().
The documentation for this class was generated from the following files:
lib/libfs/FileStorage.h
lib/libfs/FileStorage.cpp