FreeNOS: ARMIO Class Reference
ARMIO Class Reference
lib » libarch » ARM
Input/Output operations specific to the ARM architecture.
#include <ARMIO.h>
Public Member Functions
ARMIO ()
Constructor.
u8 inb (u16 port)
Read a byte from a port.
u16 inw (u16 port)
Read a word from a port.
void outb (u16 port, u8 byte)
Output a byte to a port.
void outw (u16 port, u16 word)
Output a word to a port.
void outl (u16 port, u32 l)
Output a long to a I/O port.
void write (u32 reg, u32 data)
write to memory mapped I/O register
u32 read (u32 reg) const
read from memory mapped I/O register
void read (Address addr, Size count, void *buf) const
Read a number of 32-bit values.
void write (Address addr, Size count, void *buf)
Write a number of 32-bit values.
void set (Address addr, u32 data)
Set bits in memory mapped register.
void unset (Address addr, u32 data)
Unset bits in memory mapped register.
Public Member Functions inherited from IO
IO ()
Constructor.
uint getBase () const
Get I/O base offset.
void setBase (uint base)
Set I/O base offset.
Result map (Address phys, Size size=4096, Memory::Access access=Memory::Readable|Memory::Writable|Memory::User)
Map I/O address space.
Result unmap ()
Unmap I/O address space.
Additional Inherited Members
Public Types inherited from IO
enum Result { Success, MapFailure, OutOfMemory }
Result codes.
Protected Attributes inherited from IO
volatile uint m_base
I/O base offset is added to each I/O address.
Memory::Range m_range
Memory range for performing I/O mappings.
Detailed Description
Input/Output operations specific to the ARM architecture.
Definition at line 39 of file ARMIO.h.
Constructor & Destructor Documentation
ARMIO()
ARMIO::ARMIO ()
Constructor.
Definition at line 21 of file ARMIO.cpp.
References IO::setBase().
Member Function Documentation
inb()
u8 ARMIO::inb (u16 port) inline
Read a byte from a port.
Parameters
port The I/O port to read from.
Returns
A byte read from the port.
Definition at line 55 of file ARMIO.h.
Referenced by IOCtlHandler().
inw()
u16 ARMIO::inw (u16 port) inline
Read a word from a port.
Parameters
port The I/O port to read from.
Returns
Word read from the port.
Definition at line 67 of file ARMIO.h.
Referenced by IOCtlHandler().
outb()
void ARMIO::outb (u16 port, u8 byte) inline
Output a byte to a port.
Parameters
port Port to write to.
byte The byte to output.
Definition at line 78 of file ARMIO.h.
Referenced by IOCtlHandler().
outl()
void ARMIO::outl (u16 port, u32 l) inline
Output a long to a I/O port.
Parameters
port Target I/O port.
l The long 32-bit number to output.
Definition at line 98 of file ARMIO.h.
Referenced by IOCtlHandler().
outw()
void ARMIO::outw (u16 port, u16 word) inline
Output a word to a port.
Parameters
port Port to write to.
byte The word to output.
Definition at line 88 of file ARMIO.h.
Referenced by IOCtlHandler().
read() [1/2]
u32 ARMIO::read (u32 reg) const inline
read from memory mapped I/O register
Parameters
reg Address to read
Returns
32-bit value
Definition at line 121 of file ARMIO.h.
References dmb(), and IO::m_base.
Referenced by RaspiSerial::get(), Broadcom2836::getCoreTimerIrqStatus(), SynopsisController::hostPortChanged(), BroadcomI2C::initialize(), SynopsisController::initialize(), PL011::interrupt(), SynopsisChannel::interrupt(), SynopsisController::interruptHandler(), BroadcomInterrupt::isTriggered(), RaspiSerial::put(), PL011::read(), MemoryChannel::read(), BroadcomMailbox::read(), read(), BroadcomI2C::read(), set(), BroadcomTimer::setFrequency(), SynopsisController::softReset(), BroadcomTimer::tick(), BroadcomSPI::transfer(), SynopsisChannel::transfer(), unset(), PL011::write(), MemoryChannel::write(), BroadcomMailbox::write(), and BroadcomI2C::write().
read() [2/2]
void ARMIO::read (Address addr, Size count, void * buf) const inline
Read a number of 32-bit values.
Parameters
addr Address of the starting 32-bit value.
count Number of bytes to read.
buf Output buffer.
Definition at line 139 of file ARMIO.h.
References read().
set()
void ARMIO::set (Address addr, u32 data) inline
Set bits in memory mapped register.
Parameters
addr Address of the register to write.
data 32-bit value containing the bits to set (bitwise or).
Definition at line 168 of file ARMIO.h.
References read(), and write().
Referenced by SynopsisController::initialize(), BroadcomGPIO::setAltFunction(), Broadcom2836::setCoreTimerIrq(), BroadcomSPI::transfer(), and SynopsisChannel::transfer().
unset()
void ARMIO::unset (Address addr, u32 data) inline
Unset bits in memory mapped register.
Parameters
addr Address of the register to write.
data 32-bit value containing the bits to set (bitwise or).
Definition at line 181 of file ARMIO.h.
References read(), and write().
Referenced by Broadcom2836::setCoreTimerIrq().
write() [1/2]
void ARMIO::write (u32 reg, u32 data) inline
write to memory mapped I/O register
Definition at line 105 of file ARMIO.h.
References dmb(), and IO::m_base.
Referenced by BroadcomInterrupt::BroadcomInterrupt(), BroadcomInterrupt::disable(), BroadcomInterrupt::enable(), SynopsisController::hostPortChanged(), RaspiSerial::init(), PL011::initialize(), BroadcomSPI::initialize(), BroadcomMailbox::initialize(), SynopsisController::initialize(), SynopsisChannel::initialize(), PL011::interrupt(), SynopsisChannel::interrupt(), RaspiSerial::put(), PL011::read(), MemoryChannel::read(), BroadcomI2C::read(), set(), BroadcomI2C::setAddress(), BroadcomSPI::setClockDivider(), BroadcomI2C::setClockDivider(), BroadcomTimer::setFrequency(), SynopsisController::softReset(), BroadcomTimer::tick(), BroadcomSPI::transfer(), SynopsisChannel::transfer(), unset(), PL011::write(), MemoryChannel::write(), BroadcomMailbox::write(), BroadcomI2C::write(), and write().
write() [2/2]
void ARMIO::write (Address addr, Size count, void * buf) inline
Write a number of 32-bit values.
Parameters
addr Address of the starting 32-bit value.
count Number of bytes to write.
buf Input buffer.
Definition at line 154 of file ARMIO.h.
References write().
The documentation for this class was generated from the following files:
lib/libarch/arm/ARMIO.h
lib/libarch/arm/ARMIO.cpp