FreeNOS: DirectoryScanner Class Reference
DirectoryScanner Class Reference
lib » libtest
Scan directory for automated tests.
#include <DirectoryScanner.h>
Public Member Functions
DirectoryScanner (int argc, char **argv)
Constructor.
int scan (const char *path)
Scan filesystem path for tests.
Private Attributes
int m_argc
Program argument count.
char ** m_argv
Program argument values.
Detailed Description
Scan directory for automated tests.
Definition at line 32 of file DirectoryScanner.h.
Constructor & Destructor Documentation
DirectoryScanner()
DirectoryScanner::DirectoryScanner (int argc, char ** argv)
Constructor.
Parameters
argc Program argument count
argv Program argument values
Definition at line 28 of file DirectoryScanner.cpp.
References m_argc, and m_argv.
Member Function Documentation
scan()
int DirectoryScanner::scan (const char * path)
Scan filesystem path for tests.
Parameters
path Input filesystem path
Returns
Zero on success, non-zero otherwise
Definition at line 34 of file DirectoryScanner.cpp.
References closedir(), dirent::d_name, dirent::d_type, DT_DIR, DT_REG, String::endsWith(), errno, EXIT_FAILURE, EXIT_SUCCESS, m_argc, m_argv, opendir(), printf(), readdir(), snprintf(), and strerror().
Field Documentation
m_argc
int DirectoryScanner::m_argc private
Program argument count.
Definition at line 56 of file DirectoryScanner.h.
Referenced by DirectoryScanner(), and scan().
m_argv
char** DirectoryScanner::m_argv private
Program argument values.
Definition at line 59 of file DirectoryScanner.h.
Referenced by DirectoryScanner(), and scan().
The documentation for this class was generated from the following files:
lib/libtest/DirectoryScanner.h
lib/libtest/DirectoryScanner.cpp