FreeNOS: IntelKernel Class Reference
IntelKernel Class Reference
kernel » Intel
Implements an x86 compatible kernel.
#include <IntelKernel.h>
Public Member Functions
IntelKernel (CoreInfo *info)
Constructor function.
Public Member Functions inherited from Kernel
Kernel (CoreInfo *info)
Constructor function.
SplitAllocator * getAllocator ()
Get physical memory allocator.
ProcessManager * getProcessManager ()
Get process manager.
API * getAPI ()
Get API.
MemoryContext * getMemoryContext ()
Get the current MMU context.
CoreInfo * getCoreInfo ()
Get CoreInfo.
Timer * getTimer ()
Get Timer.
int run ()
Execute the kernel.
void enableIRQ (u32 irq, bool enabled)
Enable or disable an hardware interrupt (IRQ).
virtual void hookIntVector (u32 vec, InterruptHandler h, ulong p)
Hooks a function to an hardware interrupt.
virtual void executeIntVector (u32 vec, CPUState *state)
Execute an interrupt handler.
virtual Result loadBootImage ()
Loads the boot image.
Public Member Functions inherited from Singleton< Kernel >
Singleton (Kernel *obj)
Constructor.
Static Private Member Functions
static void exception (CPUState *state, ulong param)
Called when the CPU detects a fault.
static void interrupt (CPUState *state, ulong param)
Default interrupt handler.
static void trap (CPUState *state, ulong param)
Kernel trap handler (system calls).
static void clocktick (CPUState *state, ulong param)
i8253 system clock interrupt handler.
Private Attributes
IntelPIT m_pit
PIT timer instance.
IntelAPIC m_apic
APIC instance (used if available)
IntelPIC m_pic
PIC instance.
Additional Inherited Members
Public Types inherited from Kernel
enum Result { Success, InvalidBootImage, ProcessError }
Result codes.
Static Public Member Functions inherited from Kernel
static Error heap (Address base, Size size)
Initialize heap.
Static Public Attributes inherited from Singleton< Kernel >
static Kernel * instance
One and only instance.
Protected Attributes inherited from Kernel
SplitAllocator * m_alloc
Physical memory allocator.
ProcessManager * m_procs
Process Manager.
API * m_api
API handlers object.
CoreInfo * m_coreInfo
CoreInfo object for this core.
Vector< List< InterruptHook * > * > m_interrupts
Interrupt handlers.
IntController * m_intControl
Interrupt Controller.
Timer * m_timer
Timer device.
Detailed Description
Implements an x86 compatible kernel.
Definition at line 161 of file IntelKernel.h.
Constructor & Destructor Documentation
IntelKernel()
IntelKernel::IntelKernel (CoreInfo * info)
Constructor function.
Definition at line 37 of file IntelKernel.cpp.
References IntelPaging::activate(), Segment::baseHigh, Segment::baseLow, Segment::baseMid, TSS::bitmap, clocktick(), CoreInfo::coreId, Kernel::enableIRQ(), TSS::esp0, exception(), executeInterrupt(), gdt, IntController::getBase(), IntelAPIC::getCounter(), Timer::getFrequency(), Timer::getInterrupt(), Segment::granularity, Kernel::hookIntVector(), IntelPIC::initialize(), IntelAPIC::initialize(), interrupt(), interruptRun, KERNEL_DS_SEL, KERNEL_TSS, KERNEL_TSS_SEL, kernelTss, Segment::limitHigh, Segment::limitLow, ltr, Kernel::m_alloc, m_apic, Kernel::m_coreInfo, Kernel::m_intControl, m_pic, m_pit, Kernel::m_timer, NOTICE, Segment::present, Segment::privilege, IntelCore::readCR3(), MemoryBlock::set(), IntelPIT::setFrequency(), TSS::ss0, IntelAPIC::start(), Timer::Success, CoreInfo::timerCounter, trap(), and Segment::type.
Member Function Documentation
clocktick()
void IntelKernel::clocktick (CPUState * state, ulong param) static private
i8253 system clock interrupt handler.
Parameters
state CPU registers on time of interrupt.
param Not used.
Definition at line 170 of file IntelKernel.cpp.
References IntelAPIC::clear(), Kernel::enableIRQ(), Timer::getInterrupt(), Kernel::getProcessManager(), Singleton< Kernel >::instance, m_apic, Kernel::m_timer, ProcessManager::schedule(), and Timer::tick().
Referenced by IntelKernel().
exception()
void IntelKernel::exception (CPUState * state, ulong param) static private
Called when the CPU detects a fault.
Parameters
state Contains CPU registers, interrupt vector and error code.
param Not used.
Definition at line 133 of file IntelKernel.cpp.
References assert, ProcessManager::current(), ERROR, Process::getID(), Kernel::getProcessManager(), Singleton< Kernel >::instance, IntelCore::logException(), ProcessManager::remove(), ProcessManager::schedule(), and ZERO.
Referenced by IntelKernel().
interrupt()
void IntelKernel::interrupt (CPUState * state, ulong param) static private
Default interrupt handler.
Parameters
state Contains CPU registers, interrupt vector and error code.
param Not used.
Definition at line 146 of file IntelKernel.cpp.
References IntController::clear(), IntController::getBase(), Singleton< Kernel >::instance, Kernel::m_intControl, and CPUState::vector.
Referenced by IntelKernel().
trap()
void IntelKernel::trap (CPUState * state, ulong param) static private
Kernel trap handler (system calls).
Parameters
state Contains the arguments for the APIHandler, in CPU registers.
param Not used.
Definition at line 158 of file IntelKernel.cpp.
References CPURegs::eax, CPURegs::ebx, CPURegs::ecx, CPURegs::edi, CPURegs::edx, CPURegs::esi, Kernel::getAPI(), Singleton< Kernel >::instance, API::invoke(), and CPUState::regs.
Referenced by IntelKernel().
Field Documentation
m_apic
IntelAPIC IntelKernel::m_apic private
APIC instance (used if available)
Definition at line 210 of file IntelKernel.h.
Referenced by clocktick(), and IntelKernel().
m_pic
IntelPIC IntelKernel::m_pic private
PIC instance.
Definition at line 213 of file IntelKernel.h.
Referenced by IntelKernel().
m_pit
IntelPIT IntelKernel::m_pit private
PIT timer instance.
Definition at line 207 of file IntelKernel.h.
Referenced by IntelKernel().
The documentation for this class was generated from the following files:
kernel/intel/IntelKernel.h
kernel/intel/IntelKernel.cpp