FreeNOS: AnalogPort Class Reference
AnalogPort Class Reference
server » grovepi
GrovePi Analog Port.
#include <AnalogPort.h>
Public Member Functions
AnalogPort (I2C *i2c, uint port)
Constructor function.
virtual Error initialize ()
Initializes the time class.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read digital port value.
Public Member Functions inherited from Device
Device (FileType type)
Constructor.
virtual ~Device ()
Destructor.
virtual const String & getIdentifier () const
Get unique device identifier.
virtual Error interrupt (Size vector)
Called when an interrupt has been triggered for this device.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Attributes
I2C * m_i2c
I2C controller.
uint m_port
Analog port number.
Additional Inherited Members
Protected Attributes inherited from Device
String m_identifier
Unique identifier for this Device.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
GrovePi Analog Port.
See also
https://github.com/DexterInd/GrovePi/blob/master/Firmware/Source/v1.2/grove_pi_v1_2_5/README.md
Definition at line 39 of file AnalogPort.h.
Constructor & Destructor Documentation
AnalogPort()
AnalogPort::AnalogPort (I2C * i2c, uint port)
Constructor function.
Definition at line 22 of file AnalogPort.cpp.
References m_i2c, Device::m_identifier, and m_port.
Member Function Documentation
initialize()
Error AnalogPort::initialize () virtual
Initializes the time class.
Returns
Error status code.
Reimplemented from Device.
Definition at line 30 of file AnalogPort.cpp.
References ESUCCESS.
read()
Error AnalogPort::read (IOBuffer & buffer, Size size, Size offset) virtual
Read digital port value.
Parameters
buffer Buffer to save the read bytes.
size Number of bytes to read.
offset Offset in the file to read.
Returns
Number of bytes on success and ZERO on failure.
Reimplemented from File.
Definition at line 35 of file AnalogPort.cpp.
References DEBUG, m_i2c, m_port, I2C::read(), I2C::setAddress(), snprintf(), I2C::write(), and IOBuffer::write().
Field Documentation
m_i2c
I2C* AnalogPort::m_i2c private
I2C controller.
Definition at line 69 of file AnalogPort.h.
Referenced by AnalogPort(), and read().
m_port
uint AnalogPort::m_port private
Analog port number.
Definition at line 72 of file AnalogPort.h.
Referenced by AnalogPort(), and read().
The documentation for this class was generated from the following files:
server/i2c/grovepi/AnalogPort.h
server/i2c/grovepi/AnalogPort.cpp