FreeNOS: Remove Class Reference
Remove Class Reference
bin
Remove file from the filesystem.
#include <Remove.h>
Public Member Functions
Remove (int argc, char **argv)
Constructor.
virtual ~Remove ()
Destructor.
virtual Result exec ()
Execute the application.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
Remove file from the filesystem.
Definition at line 31 of file Remove.h.
Constructor & Destructor Documentation
Remove()
Remove::Remove (int argc, char ** argv)
Constructor.
Parameters
argc Argument count
argv Argument values
Definition at line 28 of file Remove.cpp.
References Application::parser(), ArgumentParser::registerPositional(), and ArgumentParser::setDescription().
~Remove()
Remove::~Remove () virtual
Destructor.
Definition at line 35 of file Remove.cpp.
Member Function Documentation
exec()
Remove::Result Remove::exec () virtual
Execute the application.
Returns
Result code
Implements Application.
Definition at line 39 of file Remove.cpp.
References Application::arguments(), Vector< T >::count(), errno, ERROR, ArgumentContainer::getPositionals(), Application::IOError, refreshMounts(), strerror(), Application::Success, and unlink().
The documentation for this class was generated from the following files:
bin/rm/Remove.h
bin/rm/Remove.cpp