FreeNOS: Shell Class Reference
Shell Class Reference
bin
System command shell interpreter.
#include <Shell.h>
Public Member Functions
Shell (int argc, char **argv)
Constructor.
virtual ~Shell ()
Destructor.
virtual Result exec ()
Execute the application.
ShellCommand * getCommand (const char *name)
Get shell command.
HashTable< String, ShellCommand * > & getCommands ()
Get all shell commands.
void registerCommand (ShellCommand *command)
Register a new ShellCommand.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Private Member Functions
Result runInteractive ()
Executes the Shell by entering an infinite loop.
int executeInput (char *cmdline)
Executes the given input.
char * getInput ()
Fetch a command text from standard input.
void prompt ()
Output a prompt.
Size parse (char *cmdline, char **argv, Size maxArgv, bool *background)
Parses an input string into separate pieces.
Private Attributes
HashTable< String, ShellCommand * > m_commands
All known ShellCommands.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
System command shell interpreter.
Definition at line 33 of file Shell.h.
Constructor & Destructor Documentation
Shell()
Shell::Shell (int argc, char ** argv)
Constructor.
Parameters
argc Argument count
argv Argument values
Definition at line 41 of file Shell.cpp.
References Application::parser(), registerCommand(), ArgumentParser::registerPositional(), and ArgumentParser::setDescription().
~Shell()
Shell::~Shell () virtual
Destructor.
Definition at line 55 of file Shell.cpp.
Member Function Documentation
exec()
Shell::Result Shell::exec () virtual
Execute the application.
Returns
Result code
Implements Application.
Definition at line 59 of file Shell.cpp.
References Application::arguments(), Vector< T >::count(), errno, ERROR, executeInput(), fclose(), fopen(), fread(), ArgumentContainer::getPositionals(), ListIterator< T >::hasCurrent(), NULL, printf(), refreshMounts(), runInteractive(), String::split(), stat::st_size, stat(), strerror(), and Application::Success.
executeInput()
int Shell::executeInput (char * cmdline) private
Executes the given input.
Parameters
cmdline Input to execute.
Returns
Exit status of the command.
Definition at line 161 of file Shell.cpp.
References DEBUG, errno, ERROR, ShellCommand::execute(), EXIT_FAILURE, EXIT_SUCCESS, forkexec(), getCommand(), ShellCommand::getMinimumParams(), ShellCommand::getName(), MAX_ARGV, parse(), snprintf(), strerror(), strlen(), and waitpid().
Referenced by exec(), and runInteractive().
getCommand()
ShellCommand * Shell::getCommand (const char * name)
Get shell command.
Parameters
name ShellCommand name.
Returns
ShellCommand object pointer.
Definition at line 290 of file Shell.cpp.
References HashTable< K, V >::get(), m_commands, and ZERO.
Referenced by executeInput().
getCommands()
HashTable< String, ShellCommand * > & Shell::getCommands ()
Get all shell commands.
Returns
HashTable with ShellCommands
Definition at line 285 of file Shell.cpp.
References m_commands.
Referenced by HelpCommand::execute().
getInput()
char * Shell::getInput () private
Fetch a command text from standard input.
Returns
Pointer to a command text.
Definition at line 229 of file Shell.cpp.
References printf(), read(), total, and ZERO.
Referenced by runInteractive().
parse()
Size Shell::parse (char * cmdline, char ** argv, Size maxArgv, bool * background) private
Parses an input string into separate pieces.
Parameters
cmdline Command input string.
argv Argument list buffer.
maxArgv Maximum number of entries in argv.
background True if process must run in the background.
Returns
Number of parsed arguments.
Definition at line 300 of file Shell.cpp.
References ZERO.
Referenced by executeInput().
prompt()
void Shell::prompt () private
Output a prompt.
Definition at line 270 of file Shell.cpp.
References BLUE, getcwd(), gethostname(), GREEN, printf(), and WHITE.
Referenced by runInteractive().
registerCommand()
void Shell::registerCommand (ShellCommand * command)
Register a new ShellCommand.
Parameters
command ShellCommand object pointer.
Definition at line 295 of file Shell.cpp.
References ShellCommand::getName(), HashTable< K, V >::insert(), and m_commands.
Referenced by Shell().
runInteractive()
Shell::Result Shell::runInteractive () private
Executes the Shell by entering an infinite loop.
Returns
Result code
Definition at line 135 of file Shell.cpp.
References executeInput(), getInput(), prompt(), strlen(), and Application::Success.
Referenced by exec().
Field Documentation
m_commands
HashTable<String, ShellCommand *> Shell::m_commands private
All known ShellCommands.
Definition at line 120 of file Shell.h.
Referenced by getCommand(), getCommands(), and registerCommand().
The documentation for this class was generated from the following files:
bin/sh/Shell.h
bin/sh/Shell.cpp