FreeNOS: ProcessList Class Reference
ProcessList Class Reference
bin
Output the system process list.
#include <ProcessList.h>
Public Member Functions
ProcessList (int argc, char **argv)
Constructor.
virtual Result exec ()
Execute the application.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Static Private Attributes
static const char * ProcessStates []
Array of process state strings.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
Output the system process list.
Definition at line 31 of file ProcessList.h.
Constructor & Destructor Documentation
ProcessList()
ProcessList::ProcessList (int argc, char ** argv)
Constructor.
Parameters
argc Argument count
argv Argument values
Definition at line 38 of file ProcessList.cpp.
References Application::parser(), and ArgumentParser::setDescription().
Member Function Documentation
exec()
ProcessList::Result ProcessList::exec () virtual
Execute the application.
Returns
Result code
Implements Application.
Definition at line 44 of file ProcessList.cpp.
References DEBUG, InfoPID, String::length(), MAX_PROCS, memset(), API::NotFound, PATH_MAX, ProcessCtl(), ProcessStates, MemoryMap::range(), API::Read, snprintf(), Application::Success, MemoryMap::UserArgs, Memory::Range::virt, VMCopy(), and write().
Field Documentation
ProcessStates
const char * ProcessList::ProcessStates static private
Initial value:
=
{
    "Running",
    "Ready",
    "Stopped",
    "Sleeping",
    "Waiting"
}
Array of process state strings.
Definition at line 36 of file ProcessList.h.
Referenced by exec().
The documentation for this class was generated from the following files:
bin/ps/ProcessList.h
bin/ps/ProcessList.cpp