FreeNOS: Cache Class Reference
Cache Class Reference abstract
lib » libarch
Cache management interface.
#include <Cache.h>
Public Types
enum Result { Success, InvalidArgument, IOError }
Result codes.
enum Type { Instruction, Data, Unified }
Cache types.
Public Member Functions
virtual Result invalidate (Type type)=0
Invalidate the entire cache.
virtual Result cleanInvalidate (Type type)=0
Clean and invalidate entire cache.
virtual Result cleanInvalidateAddress (Type type, Address addr)=0
Clean and invalidate one memory page.
virtual Result cleanAddress (Type type, Address addr)=0
Clean one memory page.
virtual Result cleanData (Address addr)
Clean one data page.
virtual Result cleanData (void *ptr)
Clean one data page.
Detailed Description
Cache management interface.
Definition at line 35 of file Cache.h.
Member Enumeration Documentation
Result
enum Cache::Result
Result codes.
Enumerator
Success
InvalidArgument
IOError
Definition at line 42 of file Cache.h.
Type
enum Cache::Type
Cache types.
Enumerator
Instruction
Data
Unified
Definition at line 52 of file Cache.h.
Member Function Documentation
cleanAddress()
virtual Result Cache::cleanAddress (Type type, Address addr) pure virtual
Clean one memory page.
Parameters
type Cache type to clean
addr Virtual memory address of the page to clean and invalidate
Returns
Result code
Implemented in ARMCacheV7, ARMCacheV6, and IntelCache.
Referenced by cleanData().
cleanData() [1/2]
Cache::Result Cache::cleanData (Address addr) virtual
Clean one data page.
Parameters
addr Virtual memory address to clean
Returns
Result code
Definition at line 20 of file Cache.cpp.
References cleanAddress(), and Data.
Referenced by ProcessShares::createShare(), MemoryChannel::flush(), Process::initialize(), ARMSecondTable::map(), ARMFirstTable::map(), ARMFirstTable::mapLarge(), ARMSecondTable::unmap(), and ARMFirstTable::unmap().
cleanData() [2/2]
Cache::Result Cache::cleanData (void * ptr) virtual
Clean one data page.
Parameters
ptr Pointer with a virtual memory address to clean
Returns
Result code
Definition at line 25 of file Cache.cpp.
References cleanAddress(), and Data.
cleanInvalidate()
virtual Result Cache::cleanInvalidate (Type type) pure virtual
Clean and invalidate entire cache.
This operation will clean and invalidate the entire given cache.
Parameters
type Cache type to clean and invalidate.
Returns
Result code
Implemented in ARMCacheV7, ARMCacheV6, and IntelCache.
cleanInvalidateAddress()
virtual Result Cache::cleanInvalidateAddress (Type type, Address addr) pure virtual
Clean and invalidate one memory page.
Parameters
type Cache type to clean and invalidate.
addr Virtual memory address of the page to clean and invalidate
Returns
Result code
Implemented in ARMCacheV7, ARMCacheV6, and IntelCache.
invalidate()
virtual Result Cache::invalidate (Type type) pure virtual
Invalidate the entire cache.
Parameters
type Cache type to invalidate.
Returns
Result code
Implemented in ARMCacheV7, ARMCacheV6, and IntelCache.
The documentation for this class was generated from the following files:
lib/libarch/Cache.h
lib/libarch/Cache.cpp