FreeNOS: Keyboard Class Reference
Keyboard Class Reference
server » ps2
PS2 Keyboard device driver.
#include <Keyboard.h>
Public Member Functions
Keyboard ()
Constructor function.
virtual Error initialize ()
Initialize the PS2 Keyboard driver.
virtual Error interrupt (Size vector)
Executed when a key state has changed.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read a character from the keyboard.
Public Member Functions inherited from Device
Device (FileType type)
Constructor.
virtual ~Device ()
Destructor.
virtual const String & getIdentifier () const
Get unique device identifier.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Attributes
u8 shiftState
State of the shift key.
bool pending
Do we have a byte ready?
Static Private Attributes
static const char keymap [0x3a][2]
Keyboard map table.
Additional Inherited Members
Protected Attributes inherited from Device
String m_identifier
Unique identifier for this Device.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
PS2 Keyboard device driver.
Definition at line 45 of file Keyboard.h.
Constructor & Destructor Documentation
Keyboard()
Keyboard::Keyboard ()
Constructor function.
Definition at line 46 of file Keyboard.cpp.
References Device::m_identifier.
Member Function Documentation
initialize()
Error Keyboard::initialize () virtual
Initialize the PS2 Keyboard driver.
Returns
Error status code.
Reimplemented from Device.
Definition at line 51 of file Keyboard.cpp.
References ESUCCESS.
interrupt()
Error Keyboard::interrupt (Size vector) virtual
Executed when a key state has changed.
Parameters
vector Interrupt vector.
Returns
Error status code.
Reimplemented from Device.
Definition at line 56 of file Keyboard.cpp.
References ESUCCESS, and pending.
read()
Error Keyboard::read (IOBuffer & buffer, Size size, Size offset) virtual
Read a character from the keyboard.
Parameters
buffer Output buffer.
size Number of bytes to read.
offset Unused.
Returns
Number of bytes read or error code on failure.
Reimplemented from File.
Definition at line 62 of file Keyboard.cpp.
References EAGAIN, EnableIRQ, keymap, pending, ProcessCtl(), PS2_IRQ, PS2_PORT, PS2_RELEASE, ReadByte(), SELF, shiftState, and IOBuffer::write().
Field Documentation
keymap
const char Keyboard::keymap static private
Initial value:
=
{
    {0x0, 0x0}, {0x0, 0x0}, {'1', '!'}, {'2', '@'},
    {'3', '#'}, {'4', '$'}, {'5', '%'}, {'6', '^'},
    {'7', '&'}, {'8', '*'}, {'9', '('}, {'0', ')'},
    {'-', '_'}, {'=', '+'}, {'\b','\b'},{'\t','\t'},
    {'q', 'Q'}, {'w', 'W'}, {'e', 'E'}, {'r', 'R'},
    {'t', 'T'}, {'y', 'Y'}, {'u', 'U'}, {'i', 'I'},
    {'o', 'O'}, {'p', 'P'}, {'[', '{'}, {']', '}'},
    {'\n','\n'},{0x0, 0x0}, {'a', 'A'}, {'s', 'S'},
    {'d', 'D'}, {'f', 'F'}, {'g', 'G'}, {'h', 'H'},
    {'j', 'J'}, {'k', 'K'}, {'l', 'L'}, {';', ':'},
    {'\'','\"'},{'`', '~'}, {0x0, 0x0}, {'\\','|'},
    {'z', 'Z'}, {'x', 'X'}, {'c', 'C'}, {'v', 'V'},
    {'b', 'B'}, {'n', 'N'}, {'m', 'M'}, {',', '<'},
    {'.', '>'}, {'/', '?'}, {0x0, 0x0}, {'*', '*'},
    {0x0, 0x0}, {' ', ' '}
}
Keyboard map table.
Temporary hardcoded keyboard map, from kb.c in SkelixOS.
See also
http://www.skelix.org
Definition at line 86 of file Keyboard.h.
Referenced by read().
pending
bool Keyboard::pending private
Do we have a byte ready?
Definition at line 96 of file Keyboard.h.
Referenced by interrupt(), and read().
shiftState
u8 Keyboard::shiftState private
State of the shift key.
Non-zero if pressed, and ZERO otherwise.
Definition at line 93 of file Keyboard.h.
Referenced by read().
The documentation for this class was generated from the following files:
server/ps2/Keyboard.h
server/ps2/Keyboard.cpp