FreeNOS: Timer Class Reference
Timer Class Reference
lib » libarch
Represents a configurable timer device.
#include <Timer.h>
Data Structures
struct Info
Timer information structure.
Public Types
enum Result { Success, NotFound, IOError, InvalidFrequency }
Result codes.
Public Member Functions
struct Timer::Info ALIGN (8) Info
Timer information structure.
Timer ()
Constructor.
Size getInterrupt () const
Get timer interrupt number.
Size getFrequency () const
Get timer frequency.
virtual Result setFrequency (Size hertz)
Set timer frequency.
virtual Result getCurrent (Info *info)
Get current timer info.
virtual Result initialize ()
Initialize the timer.
virtual Result start ()
Start the timer.
virtual Result stop ()
Stop the timer.
virtual Result tick ()
Process timer tick.
virtual Result wait (u32 microseconds) const
Busy wait a number of microseconds.
bool isExpired (const Info &info) const
Check if a timer value is expired.
Data Fields
enum Timer::Result ALIGN
Protected Attributes
Info m_info
The current Timer information.
Size m_frequency
Frequency of the Timer.
Size m_int
Timer interrupt number.
Detailed Description
Represents a configurable timer device.
Definition at line 35 of file Timer.h.
Member Enumeration Documentation
Result
enum Timer::Result
Result codes.
Enumerator
Success
NotFound
IOError
InvalidFrequency
Definition at line 52 of file Timer.h.
Constructor & Destructor Documentation
Timer()
Timer::Timer ()
Constructor.
Definition at line 21 of file Timer.cpp.
References m_frequency, m_info, m_int, and MemoryBlock::set().
Member Function Documentation
ALIGN()
struct Timer::Info Timer::ALIGN (8)
Timer information structure.
getCurrent()
Timer::Result Timer::getCurrent (Info * info) virtual
Get current timer info.
Parameters
info Timer Info object pointer for output.
Returns
Result code.
Definition at line 44 of file Timer.cpp.
References Timer::Info::frequency, m_frequency, m_info, Success, and Timer::Info::ticks.
Referenced by ProcessCtlHandler().
getFrequency()
Size Timer::getFrequency () const
Get timer frequency.
Returns
Frequency of the timer in hertz.
Definition at line 33 of file Timer.cpp.
References m_frequency.
Referenced by IntelKernel::IntelKernel(), and IntelAPIC::start().
getInterrupt()
Size Timer::getInterrupt () const
Get timer interrupt number.
Returns
Interrupt number.
Definition at line 28 of file Timer.cpp.
References m_int.
Referenced by IntelKernel::clocktick(), and IntelKernel::IntelKernel().
initialize()
Timer::Result Timer::initialize () virtual
Initialize the timer.
Returns
Result code.
Reimplemented in IntelAPIC.
Definition at line 51 of file Timer.cpp.
References Success.
isExpired()
bool Timer::isExpired (const Info & info) const
Check if a timer value is expired.
Parameters
info Timer info value to compare
Returns
True if expired, false otherwise
Definition at line 77 of file Timer.cpp.
References Timer::Info::frequency, m_info, and Timer::Info::ticks.
Referenced by Scheduler::select().
setFrequency()
Timer::Result Timer::setFrequency (Size hertz) virtual
Set timer frequency.
Parameters
hertz Frequency of the timer in hertz.
Returns
Result code.
Reimplemented in IntelPIT, BroadcomTimer, and ARMTimer.
Definition at line 38 of file Timer.cpp.
References m_frequency, and Success.
start()
Timer::Result Timer::start () virtual
Start the timer.
This function lets the timer run. The timer will generate interrupts on the configured frequency.
Returns
Result code.
Definition at line 56 of file Timer.cpp.
References Success.
stop()
Timer::Result Timer::stop () virtual
Stop the timer.
This function brings the timer to a halt. The timer will not generate any interrupts.
Returns
Result code.
Definition at line 61 of file Timer.cpp.
References Success.
tick()
Timer::Result Timer::tick () virtual
Process timer tick.
Should be called on each Timer interrupt to keep the m_info variable synchronized with the actual hardware.
Reimplemented in BroadcomTimer, and ARMTimer.
Definition at line 66 of file Timer.cpp.
References m_info, Success, and Timer::Info::ticks.
Referenced by IntelKernel::clocktick(), and ARMKernel::interrupt().
wait()
Timer::Result Timer::wait (u32 microseconds) const virtual
Busy wait a number of microseconds.
Parameters
microseconds The number of microseconds to wait at minimum.
Returns
Result code.
Reimplemented in IntelAPIC.
Definition at line 72 of file Timer.cpp.
References Success.
Field Documentation
ALIGN
enum Timer::Result Timer::ALIGN
m_frequency
Size Timer::m_frequency protected
Frequency of the Timer.
Definition at line 156 of file Timer.h.
Referenced by getCurrent(), getFrequency(), IntelAPIC::IntelAPIC(), BroadcomTimer::setFrequency(), setFrequency(), IntelPIT::setFrequency(), IntelAPIC::start(), Timer(), and IntelAPIC::wait().
m_info
Info Timer::m_info protected
The current Timer information.
Definition at line 153 of file Timer.h.
Referenced by getCurrent(), isExpired(), BroadcomTimer::tick(), tick(), and Timer().
m_int
Size Timer::m_int protected
Timer interrupt number.
Definition at line 159 of file Timer.h.
Referenced by getInterrupt(), IntelAPIC::IntelAPIC(), IntelPIT::IntelPIT(), and Timer().
The documentation for this class was generated from the following files:
lib/libarch/Timer.h
lib/libarch/Timer.cpp