FreeNOS: DigitalPort Class Reference
DigitalPort Class Reference
server » grovepi
GrovePi Digital Port.
#include <DigitalPort.h>
Public Member Functions
DigitalPort (I2C *i2c, uint port)
Constructor function.
virtual Error initialize ()
Initializes the time class.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read digital port value.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Set digital port value.
Public Member Functions inherited from Device
Device (FileType type)
Constructor.
virtual ~Device ()
Destructor.
virtual const String & getIdentifier () const
Get unique device identifier.
virtual Error interrupt (Size vector)
Called when an interrupt has been triggered for this device.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Private Attributes
I2C * m_i2c
I2C controller.
uint m_port
Digital port number.
Additional Inherited Members
Protected Attributes inherited from Device
String m_identifier
Unique identifier for this Device.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
GrovePi Digital Port.
See also
https://github.com/DexterInd/GrovePi/blob/master/Firmware/Source/v1.2/grove_pi_v1_2_5/README.md
Definition at line 39 of file DigitalPort.h.
Constructor & Destructor Documentation
DigitalPort()
DigitalPort::DigitalPort (I2C * i2c, uint port)
Constructor function.
Definition at line 21 of file DigitalPort.cpp.
References m_i2c, Device::m_identifier, and m_port.
Member Function Documentation
initialize()
Error DigitalPort::initialize () virtual
Initializes the time class.
Returns
Error status code.
Reimplemented from Device.
Definition at line 29 of file DigitalPort.cpp.
References ESUCCESS.
read()
Error DigitalPort::read (IOBuffer & buffer, Size size, Size offset) virtual
Read digital port value.
Parameters
buffer Buffer to save the read bytes.
size Number of bytes to read.
offset Offset in the file to read.
Returns
Number of bytes on success and ZERO on failure.
Reimplemented from File.
Definition at line 34 of file DigitalPort.cpp.
References DEBUG, m_i2c, m_port, I2C::read(), I2C::setAddress(), I2C::write(), and IOBuffer::write().
write()
Error DigitalPort::write (IOBuffer & buffer, Size size, Size offset) virtual
Set digital port value.
Parameters
buffer Buffer to save the read bytes.
size Number of bytes to read.
offset Offset in the file to read.
Returns
Number of bytes on success and ZERO on failure.
Reimplemented from File.
Definition at line 62 of file DigitalPort.cpp.
References DEBUG, m_i2c, m_port, I2C::setAddress(), and I2C::write().
Field Documentation
m_i2c
I2C* DigitalPort::m_i2c private
I2C controller.
Definition at line 80 of file DigitalPort.h.
Referenced by DigitalPort(), read(), and write().
m_port
uint DigitalPort::m_port private
Digital port number.
Definition at line 83 of file DigitalPort.h.
Referenced by DigitalPort(), read(), and write().
The documentation for this class was generated from the following files:
server/i2c/grovepi/DigitalPort.h
server/i2c/grovepi/DigitalPort.cpp