FreeNOS: I2C Class Reference
I2C Class Reference abstract
lib » libi2c
I2C controller abstract interface.
#include <I2C.h>
Public Types
enum Result { Success, NotFound, IOError, RangeError }
Result codes.
Public Member Functions
I2C ()
Constructor.
virtual Result initialize ()=0
Initialize the Controller.
virtual Result setAddress (Address addr)=0
Set Slave address.
virtual Result write (u8 *buf, Size size)=0
Write data to slave.
virtual Result read (u8 *buf, Size size)=0
Read data from slave.
Protected Attributes
Arch::IO m_io
I/O instance.
Detailed Description
I2C controller abstract interface.
Definition at line 35 of file I2C.h.
Member Enumeration Documentation
Result
enum I2C::Result
Result codes.
Enumerator
Success
NotFound
IOError
RangeError
Definition at line 42 of file I2C.h.
Constructor & Destructor Documentation
I2C()
I2C::I2C ()
Constructor.
Definition at line 20 of file I2C.cpp.
Member Function Documentation
initialize()
virtual Result I2C::initialize () pure virtual
Initialize the Controller.
Returns
Result code
Implemented in BroadcomI2C.
read()
virtual Result I2C::read (u8 * buf, Size size) pure virtual
Read data from slave.
Parameters
buf Buffer for storing bytes read.
size Number of bytes to read.
Returns
Result code.
Implemented in BroadcomI2C.
Referenced by AnalogPort::read(), and DigitalPort::read().
setAddress()
virtual Result I2C::setAddress (Address addr) pure virtual
Set Slave address.
Parameters
addr The 7-bit address of the I2C slave device.
Returns
Result code.
Implemented in BroadcomI2C.
Referenced by AnalogPort::read(), DigitalPort::read(), LCDBar::setRGB(), LCDBar::textCommand(), and DigitalPort::write().
write()
virtual Result I2C::write (u8 * buf, Size size) pure virtual
Write data to slave.
Parameters
buf Buffer containing bytes to write.
size Number of bytes to write.
Returns
Result code.
Implemented in BroadcomI2C.
Referenced by AnalogPort::read(), DigitalPort::read(), LCDBar::setRGB(), LCDBar::setText(), LCDBar::textCommand(), and DigitalPort::write().
Field Documentation
m_io
Arch::IO I2C::m_io protected
I/O instance.
Definition at line 94 of file I2C.h.
Referenced by BroadcomI2C::initialize(), BroadcomI2C::read(), BroadcomI2C::setAddress(), BroadcomI2C::setClockDivider(), and BroadcomI2C::write().
The documentation for this class was generated from the following files:
lib/libi2c/I2C.h
lib/libi2c/I2C.cpp