FreeNOS: NetworkDevice Class Reference
NetworkDevice Class Reference abstract
lib » libnet
Network Device abstract class.
#include <NetworkDevice.h>
Public Member Functions
NetworkDevice (NetworkServer *server)
Constructor.
virtual ~NetworkDevice ()
Destructor.
virtual Error initialize ()
Initialize the NetworkDevice.
const Size getMaximumPacketSize () const
Get maximum packet size.
virtual Error getAddress (Ethernet::Address *address)=0
Read ethernet address.
virtual Error setAddress (Ethernet::Address *address)=0
Set ethernet address.
NetworkQueue * getReceiveQueue ()
Get receive queue.
NetworkQueue * getTransmitQueue ()
Get transmit queue.
virtual Error transmit (NetworkQueue::Packet *packet)=0
Transmit one network packet.
virtual Error process (NetworkQueue::Packet *packet, Size offset=0)
Process a received network packet.
Public Member Functions inherited from Device
Device (FileType type)
Constructor.
virtual ~Device ()
Destructor.
virtual const String & getIdentifier () const
Get unique device identifier.
virtual Error interrupt (Size vector)
Called when an interrupt has been triggered for this device.
Public Member Functions inherited from File
File (FileType type=RegularFile, UserID uid=ZERO, GroupID gid=ZERO)
Constructor function.
virtual ~File ()
Destructor function.
FileType getType () const
Retrieve our filetype.
virtual Error read (IOBuffer &buffer, Size size, Size offset)
Read bytes from the file.
virtual Error write (IOBuffer &buffer, Size size, Size offset)
Write bytes to the file.
virtual Error status (FileSystemMessage *msg)
Retrieve file statistics.
Protected Attributes
Size m_maximumPacketSize
Maximum size of each packet.
NetworkQueue m_receive
NetworkQueue m_transmit
NetworkServer * m_server
Ethernet * m_eth
ARP * m_arp
IPV4 * m_ipv4
ICMP * m_icmp
UDP * m_udp
Protected Attributes inherited from Device
String m_identifier
Unique identifier for this Device.
Protected Attributes inherited from File
FileType m_type
Type of this file.
FileModes m_access
Access permissions.
Size m_size
Size of the file, in bytes.
UserID m_uid
Owner of the file.
GroupID m_gid
Group of the file.
DeviceID m_deviceId
Device major/minor ID.
Detailed Description
Network Device abstract class.
Definition at line 41 of file NetworkDevice.h.
Constructor & Destructor Documentation
NetworkDevice()
NetworkDevice::NetworkDevice (NetworkServer * server)
Constructor.
Definition at line 20 of file NetworkDevice.cpp.
References m_arp, m_eth, m_ipv4, m_maximumPacketSize, m_server, and m_udp.
~NetworkDevice()
NetworkDevice::~NetworkDevice () virtual
Destructor.
Definition at line 33 of file NetworkDevice.cpp.
Member Function Documentation
getAddress()
virtual Error NetworkDevice::getAddress (Ethernet::Address * address) pure virtual
Read ethernet address.
Parameters
address Ethernet address reference for output
Returns
Error code
Implemented in SMSC95xx, and Loopback.
Referenced by Ethernet::Ethernet().
getMaximumPacketSize()
const Size NetworkDevice::getMaximumPacketSize () const
Get maximum packet size.
Returns
Maximum packet size
Definition at line 74 of file NetworkDevice.cpp.
References m_maximumPacketSize.
Referenced by NetworkProtocol::getMaximumPacketSize().
getReceiveQueue()
NetworkQueue * NetworkDevice::getReceiveQueue ()
Get receive queue.
Definition at line 79 of file NetworkDevice.cpp.
References m_receive.
Referenced by SMSC95xxUSB::readFinished(), and SMSC95xxUSB::readStart().
getTransmitQueue()
NetworkQueue * NetworkDevice::getTransmitQueue ()
Get transmit queue.
Definition at line 84 of file NetworkDevice.cpp.
References m_transmit.
Referenced by Ethernet::getTransmitPacket(), SMSC95xxUSB::SMSC95xxUSB(), SMSC95xxUSB::transmit(), SMSC95xxUSB::writeFinished(), and SMSC95xxUSB::writeStart().
initialize()
Error NetworkDevice::initialize () virtual
Initialize the NetworkDevice.
Returns
Error code
Reimplemented from Device.
Reimplemented in SMSC95xx, and Loopback.
Definition at line 37 of file NetworkDevice.cpp.
References ERROR, ESUCCESS, Device::initialize(), UDP::initialize(), ICMP::initialize(), Ethernet::initialize(), IPV4::initialize(), ARP::initialize(), m_arp, m_eth, m_icmp, m_ipv4, m_server, m_udp, IPV4::setARP(), Ethernet::setARP(), IPV4::setEthernet(), ARP::setEthernet(), IPV4::setICMP(), UDP::setIP(), ICMP::setIP(), ARP::setIP(), Ethernet::setIP(), and IPV4::setUDP().
Referenced by Loopback::initialize(), and SMSC95xx::initialize().
process()
Error NetworkDevice::process (NetworkQueue::Packet * packet, Size offset = 0) virtual
Process a received network packet.
Parameters
packet Network packet received by the device
offset Network packet payload offset
Returns
Error code
Definition at line 89 of file NetworkDevice.cpp.
References DEBUG, ESUCCESS, m_eth, and Ethernet::process().
Referenced by SMSC95xxUSB::readFinished(), and Loopback::transmit().
setAddress()
virtual Error NetworkDevice::setAddress (Ethernet::Address * address) pure virtual
Set ethernet address.
Parameters
address New ethernet address to set
Returns
Error code
Implemented in SMSC95xx, and Loopback.
Referenced by Ethernet::setAddress().
transmit()
virtual Error NetworkDevice::transmit (NetworkQueue::Packet * packet) pure virtual
Transmit one network packet.
Parameters
buffer Input/Output buffer to input bytes from.
size Size of the network packet.
Returns
Error code
Implemented in SMSC95xx, and Loopback.
Referenced by UDP::sendPacket(), ICMP::sendPacket(), ARP::sendReply(), and ARP::sendRequest().
Field Documentation
m_arp
ARP* NetworkDevice::m_arp protected
Definition at line 129 of file NetworkDevice.h.
Referenced by initialize(), and NetworkDevice().
m_eth
Ethernet* NetworkDevice::m_eth protected
Definition at line 127 of file NetworkDevice.h.
Referenced by initialize(), NetworkDevice(), and process().
m_icmp
ICMP* NetworkDevice::m_icmp protected
Definition at line 133 of file NetworkDevice.h.
Referenced by initialize().
m_ipv4
IPV4* NetworkDevice::m_ipv4 protected
Definition at line 131 of file NetworkDevice.h.
Referenced by initialize(), and NetworkDevice().
m_maximumPacketSize
Size NetworkDevice::m_maximumPacketSize protected
Maximum size of each packet.
Definition at line 119 of file NetworkDevice.h.
Referenced by getMaximumPacketSize(), SMSC95xx::initialize(), and NetworkDevice().
m_receive
NetworkQueue NetworkDevice::m_receive protected
Definition at line 121 of file NetworkDevice.h.
Referenced by getReceiveQueue().
m_server
NetworkServer* NetworkDevice::m_server protected
Definition at line 125 of file NetworkDevice.h.
Referenced by initialize(), NetworkDevice(), and SMSC95xx::SMSC95xx().
m_transmit
NetworkQueue NetworkDevice::m_transmit protected
Definition at line 123 of file NetworkDevice.h.
Referenced by getTransmitQueue(), and Loopback::transmit().
m_udp
UDP* NetworkDevice::m_udp protected
Definition at line 135 of file NetworkDevice.h.
Referenced by initialize(), and NetworkDevice().
The documentation for this class was generated from the following files:
lib/libnet/NetworkDevice.h
lib/libnet/NetworkDevice.cpp