FreeNOS: Sleep Class Reference
Sleep Class Reference
bin
Stop executing for some time.
#include <Sleep.h>
Public Member Functions
Sleep (int argc, char **argv)
Constructor.
virtual ~Sleep ()
Destructor.
virtual Result exec ()
Execute the application.
Public Member Functions inherited from POSIXApplication
POSIXApplication (int argc, char **argv)
Class constructor.
virtual ~POSIXApplication ()
Class destructor.
Public Member Functions inherited from Application
Application (int argc, char **argv)
Class constructor.
virtual ~Application ()
Class destructor.
virtual int run ()
Run the application.
Additional Inherited Members
Public Types inherited from Application
enum Result {
Success, NotFound, IOError, InvalidArgument,
ShowUsage
}
Result codes.
Protected Member Functions inherited from POSIXApplication
virtual Result output (const char *string) const
Print text to output.
Protected Member Functions inherited from Application
virtual Result initialize ()
Initialize the application.
virtual Result output (String &string) const
Print string to output.
ArgumentParser & parser ()
Get program arguments parser.
const ArgumentParser & parser () const
Get constant program arguments parser.
const ArgumentContainer & arguments () const
Get program arguments.
void setVersion (const String &version)
Set program version.
Detailed Description
Stop executing for some time.
Definition at line 31 of file Sleep.h.
Constructor & Destructor Documentation
Sleep()
Sleep::Sleep (int argc, char ** argv)
Constructor.
Parameters
argc Argument count
argv Argument values
Definition at line 25 of file Sleep.cpp.
References Application::parser(), ArgumentParser::registerPositional(), and ArgumentParser::setDescription().
~Sleep()
Sleep::~Sleep () virtual
Destructor.
Definition at line 32 of file Sleep.cpp.
Member Function Documentation
exec()
Sleep::Result Sleep::exec () virtual
Execute the application.
Returns
Result code
Implements Application.
Definition at line 36 of file Sleep.cpp.
References Application::arguments(), atoi(), errno, ERROR, Application::InvalidArgument, Application::IOError, sleep(), strerror(), and Application::Success.
The documentation for this class was generated from the following files:
bin/sleep/Sleep.h
bin/sleep/Sleep.cpp