FreeNOS: WriteCommand Class Reference
WriteCommand Class Reference
bin » sh
Write data to a file.
#include <WriteCommand.h>
Public Member Functions
WriteCommand ()
Constructor function.
virtual int execute (Size nparams, char **params)
Executes the command.
Public Member Functions inherited from ShellCommand
ShellCommand (const char *name, Size minParams=0)
Constructor.
virtual ~ShellCommand ()
Destructor.
const char * getName () const
Get command name.
const char * getHelp () const
Get command help.
Size getMinimumParams () const
Get the minimum number of parameters required.
Additional Inherited Members
Protected Attributes inherited from ShellCommand
const char * m_name
Unique name of the command.
const char * m_help
Command help text.
Size m_minParams
Minimum number of parameters required.
Detailed Description
Write data to a file.
Definition at line 35 of file WriteCommand.h.
Constructor & Destructor Documentation
WriteCommand()
WriteCommand::WriteCommand ()
Constructor function.
Definition at line 28 of file WriteCommand.cpp.
References ShellCommand::m_help.
Member Function Documentation
execute()
int WriteCommand::execute (Size nparams, char ** params) virtual
Executes the command.
Parameters
nparams Number of parameters given.
params Array of parameters.
Returns
Error code or zero on success.
Implements ShellCommand.
Definition at line 34 of file WriteCommand.cpp.
References close(), errno, ERROR, EXIT_FAILURE, String::length(), O_WRONLY, open(), strerror(), and write().
The documentation for this class was generated from the following files:
bin/sh/WriteCommand.h
bin/sh/WriteCommand.cpp