FreeNOS: ARMCacheV7 Class Reference
ARMCacheV7 Class Reference
lib » libarch » ARM
ARMv7 cache management implementation.
#include <ARMCacheV7.h>
Public Member Functions
virtual Result invalidate (Type type)
Invalidate the entire cache.
virtual Result cleanInvalidate (Type type)
Clean and invalidate entire cache.
virtual Result cleanInvalidateAddress (Type type, Address addr)
Clean and invalidate one memory page.
virtual Result cleanAddress (Type type, Address addr)
Clean one memory page.
Public Member Functions inherited from Cache
virtual Result cleanData (Address addr)
Clean one data page.
virtual Result cleanData (void *ptr)
Clean one data page.
Private Types
enum CacheLevelType { CacheLevelInstruction = 1, CacheLevelData = 2, CacheLevelInstructionData = 3, CacheLevelUnified = 4 }
Defines the cache level type bits.
Private Member Functions
Result dataFlush (bool clean)
Flush the entire data cache.
u32 getCacheLevelId () const
Get cache level identifier.
u32 readCacheSize (u32 level, u32 type) const
Get cache size.
Result flushLevel (u32 level, bool clean)
Clean and Invalidate by cache level.
Private Attributes
ARMControl m_control
ARM system control processor object.
Additional Inherited Members
Public Types inherited from Cache
enum Result { Success, InvalidArgument, IOError }
Result codes.
enum Type { Instruction, Data, Unified }
Cache types.
Detailed Description
ARMv7 cache management implementation.
See also
ARM Architecture Reference Manual, page xxx
Definition at line 42 of file ARMCacheV7.h.
Member Enumeration Documentation
CacheLevelType
enum ARMCacheV7::CacheLevelType private
Defines the cache level type bits.
Enumerator
CacheLevelInstruction
CacheLevelData
CacheLevelInstructionData
CacheLevelUnified
Definition at line 49 of file ARMCacheV7.h.
Member Function Documentation
cleanAddress()
ARMCacheV7::Result ARMCacheV7::cleanAddress (ARMCacheV7::Type type, Address addr) virtual
Clean one memory page.
Parameters
type Cache type to clean
addr Virtual memory address of the page to clean and invalidate
Returns
Result code
Implements Cache.
Definition at line 102 of file ARMCacheV7.cpp.
References Cache::Data, dsb(), Cache::Instruction, isb(), mcr, Cache::Success, and Cache::Unified.
cleanInvalidate()
ARMCacheV7::Result ARMCacheV7::cleanInvalidate (ARMCacheV7::Type type) virtual
Clean and invalidate entire cache.
This operation will clean and invalidate the entire given cache.
Parameters
type Cache type to clean and invalidate.
Returns
Result code
Implements Cache.
Definition at line 52 of file ARMCacheV7.cpp.
References Cache::Data, dataFlush(), dsb(), flushBranchPrediction(), Cache::Instruction, isb(), mcr, Cache::Success, and Cache::Unified.
Referenced by invalidate().
cleanInvalidateAddress()
ARMCacheV7::Result ARMCacheV7::cleanInvalidateAddress (Type type, Address addr) virtual
Clean and invalidate one memory page.
Parameters
type Cache type to clean and invalidate.
addr Virtual memory address of the page to clean and invalidate
Returns
Result code
Implements Cache.
Definition at line 82 of file ARMCacheV7.cpp.
References Cache::Data, dsb(), Cache::Instruction, isb(), mcr, Cache::Success, and Cache::Unified.
dataFlush()
ARMCacheV7::Result ARMCacheV7::dataFlush (bool clean) private
Flush the entire data cache.
Parameters
clean True to clean cache before invalidation.
Returns
Result code
Definition at line 209 of file ARMCacheV7.cpp.
References CacheLevelData, CacheLevelInstruction, CacheLevelUnified, flushLevel(), getCacheLevelId(), and Cache::Success.
Referenced by cleanInvalidate(), and invalidate().
flushLevel()
ARMCacheV7::Result ARMCacheV7::flushLevel (u32 level, bool clean) private
Clean and Invalidate by cache level.
Parameters
level Cache level
clean True to clean cache before invalidation.
Returns
Result code
Definition at line 160 of file ARMCacheV7.cpp.
References CCSIDR_ASSOCIATIVITY_MASK, CCSIDR_ASSOCIATIVITY_OFFSET, CCSIDR_LINE_SIZE_MASK, CCSIDR_LINE_SIZE_OFFSET, CCSIDR_NUM_SETS_MASK, CCSIDR_NUM_SETS_OFFSET, dsb(), log_2_n_round_up(), readCacheSize(), and Cache::Success.
Referenced by dataFlush().
getCacheLevelId()
u32 ARMCacheV7::getCacheLevelId () const private
Get cache level identifier.
Returns
Cache Level Identifier
Definition at line 123 of file ARMCacheV7.cpp.
Referenced by dataFlush().
invalidate()
ARMCacheV7::Result ARMCacheV7::invalidate (ARMCacheV7::Type type) virtual
Invalidate the entire cache.
Parameters
type Cache type to invalidate.
Returns
Result code
Implements Cache.
Definition at line 34 of file ARMCacheV7.cpp.
References cleanInvalidate(), Cache::Data, dataFlush(), Cache::Instruction, Cache::Success, and Cache::Unified.
readCacheSize()
u32 ARMCacheV7::readCacheSize (u32 level, u32 type) const private
Get cache size.
Parameters
level Cache level to get size for
type Cache type to get size for
Returns
Cache size in bytes
Definition at line 130 of file ARMCacheV7.cpp.
Referenced by flushLevel().
Field Documentation
m_control
ARMControl ARMCacheV7::m_control private
ARM system control processor object.
Definition at line 141 of file ARMCacheV7.h.
The documentation for this class was generated from the following files:
lib/libarch/arm/ARMCacheV7.h
lib/libarch/arm/ARMCacheV7.cpp