FreeNOS: liballoc
liballoc
lib
Memory allocator library for managing the dynamic heap and virtual memory mappings.
Data Structures
class Allocator
Memory Allocator.
class BitAllocator
Bit memory allocator.
class BubbleAllocator
Keeps growing allocated memory, and can't actually free memory (hence the name).
class PageAllocator
Allocates virtual memory using the memory server.
struct MemoryPool
Memory pool contains pre-allocated blocks of a certain size (power of two).
class PoolAllocator
Memory allocator which uses pools.
class SplitAllocator
Allocator which separates kernel mapped low-memory and higher memory.
Macros
#define POOL_MIN_POWER 2
Minimum power of two for a pool size.
#define POOL_MAX_POWER 32
Maximum power of two size a pool can be.
#define POOL_MIN_COUNT(size)
Allocate this many blocks per default for the given size.
#define BITMAP_NUM_BYTES(count) ((count / 8) + 1)
Calculates the number of bytes needed in a bitmap, to hold the specified number of elements.
Typedefs
typedef struct MemoryPool MemoryPool
Memory pool contains pre-allocated blocks of a certain size (power of two).
Dynamic memory allocation.
void * operator new (__SIZE_TYPE__ sz)
Allocate new memory.
void * operator new[] (__SIZE_TYPE__ sz)
Allocate memory for an array.
void operator delete (void *mem)
Free memory back to the current Allocator.
void operator delete[] (void *mem)
Uses the Heap class to free memory, with the delete[] operator.
void * operator new (__SIZE_TYPE__ sz, Address addr)
Let the new() operator return the given memory address.
Detailed Description
Memory allocator library for managing the dynamic heap and virtual memory mappings.
Macro Definition Documentation
BITMAP_NUM_BYTES
#define BITMAP_NUM_BYTES (count) ((count / 8) + 1)
Calculates the number of bytes needed in a bitmap, to hold the specified number of elements.
Parameters
count Number of elements to hold in the bitmap.
Definition at line 53 of file PoolAllocator.h.
Referenced by PoolAllocator::newPool().
POOL_MAX_POWER
#define POOL_MAX_POWER 32
Maximum power of two size a pool can be.
Definition at line 37 of file PoolAllocator.h.
Referenced by PoolAllocator::allocate(), and PoolAllocator::release().
POOL_MIN_COUNT
#define POOL_MIN_COUNT (size)
Value:
(64 / (((size) / 1024) + 1)) > 0 ? \
    (64 / (((size) / 1024 ) + 1)) : 1
Allocate this many blocks per default for the given size.
Parameters
size Size of each block.
Definition at line 44 of file PoolAllocator.h.
Referenced by PoolAllocator::allocate().
POOL_MIN_POWER
#define POOL_MIN_POWER 2
Minimum power of two for a pool size.
Definition at line 34 of file PoolAllocator.h.
Referenced by PoolAllocator::allocate(), and PoolAllocator::release().
Typedef Documentation
MemoryPool
typedef struct MemoryPool MemoryPool
Memory pool contains pre-allocated blocks of a certain size (power of two).
Function Documentation
operator delete()
void operator delete (void * mem) inline
Free memory back to the current Allocator.
Parameters
mem Points to memory to release.
Definition at line 228 of file Allocator.h.
References Allocator::getDefault(), and Allocator::release().
operator delete[]()
void operator delete[] (void * mem) inline
Uses the Heap class to free memory, with the delete[] operator.
Parameters
mem Points to memory to release.
Definition at line 238 of file Allocator.h.
References Allocator::getDefault(), and Allocator::release().
operator new() [1/2]
void* operator new (__SIZE_TYPE__ sz) inline
Allocate new memory.
Parameters
sz Amount of memory to allocate.
Definition at line 198 of file Allocator.h.
References Allocator::allocate(), Allocator::getDefault(), NULL, and Allocator::Success.
operator new() [2/2]
void* operator new (__SIZE_TYPE__ sz, Address addr) inline
Let the new() operator return the given memory address.
Parameters
sz Size to allocate (ignored).
addr Memory address to return.
Definition at line 249 of file Allocator.h.
operator new[]()
void* operator new[] (__SIZE_TYPE__ sz) inline
Allocate memory for an array.
Parameters
sz Amount of memory to allocate.
Definition at line 213 of file Allocator.h.
References Allocator::allocate(), Allocator::getDefault(), NULL, and Allocator::Success.