FreeNOS: libposix
libposix
lib
Provides support for the POSIX.1-2008 portable operating system interface for user programs.
Data Structures
struct dirent
Represents a directory entry.
struct DIR
A type representing a directory stream.
class FileDescriptor
Abstracts a file which is opened by a user process.
struct FileSystemMount
Represents a mounted filesystem.
class POSIXApplication
POSIX-compatible application.
struct FILE
A structure containing information about a file.
class StdioLog
Log to standard output.
struct sockaddr
struct stat
The <sys/stat.h> header shall define the stat structure.
struct timeval
Time value information.
struct timezone
Time zone information.
struct utsname
System name structure.
struct timespec
The <time.h> header shall declare the timespec structure.
Macros
#define assert(exp)
Insert program diagnostics.
#define isdigit(c) Character::isDigit(c)
Test for a decimal digit.
#define islower(c) Character::isLower(c)
Test for a lowercase letter.
#define isupper(c) Character::isUpper(c)
Test for an uppercase letter.
#define isalpha(c) Character::isAlpha(c)
Test for an alphabetic character.
#define isalnum(c) Character::isAlnum(c)
Test for an alphanumeric character.
#define isblank(c) Character::isBlank(c)
Test for a blank character.
#define isspace(c) Character::isSpace(c)
Test for a white-space character.
#define tolower(c) Character::lower(c)
Converts the letter c to lowercase.
#define toupper(c) Character::upper(c)
Converts the letter c to uppercase.
#define DT_UNKNOWN 0
The file type is unknown.
#define DT_FIFO 1
This is a named pipe (FIFO).
#define DT_CHR 2
This is a character device.
#define DT_DIR 4
This is a directory.
#define DT_BLK 6
This is a block device.
#define DT_REG 8
This is a regular file.
#define DT_LNK 10
This is a symbolic link.
#define DT_SOCK 12
This is a Unix domain socket.
#define DIRLEN 64
Maximum length of a directory entry name.
#define FILE_DESCRIPTOR_MAX 1024
#define FILESYSTEM_MAXMOUNTS 16
Maximum number of mounted filesystems.
#define CHAR_BIT 8
Number of bits in a type char.
#define PATH_MAX 64
Maximum file path length.
#define ARGV_SIZE 128
Maximum size of each argument.
#define ARGV_COUNT (PAGESIZE / ARGV_SIZE)
Number of arguments at maximum.
#define dprintf(fmt, ...) printf("{%s:%d}: " fmt, __FILE__, __LINE__, ##__VA_ARGS__);
Output a debug message using printf().
#define EXIT_SUCCESS 0
Successful termination.
#define EXIT_FAILURE 1
Unsuccessful termination.
#define UTSBUF 128
Size of each buffer in the utsname structure fields.
#define _POSIX_VERSION 200809L
Integer value indicating version of this standard (C-language binding) to which the implementation conforms.
#define _POSIX2_VERSION 200809L
Integer value indicating version of the Shell and Utilities volume of POSIX.1 to which the implementation conforms.
Typedefs
typedef struct DIR DIR
A type representing a directory stream.
typedef struct FileSystemMount FileSystemMount
Represents a mounted filesystem.
typedef Size socklen_t
typedef ProcessID pid_t
Used for process IDs and process group IDs.
typedef Size size_t
Used for sizes of objects.
typedef slong ssize_t
Used for a count of bytes or an error indication.
typedef DeviceID dev_t
Used for device IDs.
typedef uint ino_t
Used for file serial numbers.
typedef uint mode_t
Used for some file attributes.
typedef u16 uid_t
Used for user IDs.
typedef u16 gid_t
Used for group IDs.
typedef Size nlink_t
Used for link counts.
typedef sint off_t
Used for file sizes.
typedef sint blkcnt_t
Used for file block counts.
typedef sint blksize_t
Used for block sizes.
typedef u64 time_t
Used for time in seconds.
Enumerations
enum { AF_INET, AF_INET6, AF_UNIX }
Communication domains.
enum { SOCK_STREAM, SOCK_DGRAM }
Socket types.
enum { IPPROTO_TCP, IPPROTO_UDP, IPPROTO_ICMP }
Communication Protocols.
enum { SHUT_RD, SHUT_WR, SHUT_RDWR }
Functions
C DIR * opendir (const char *dirname)
Open directory associated with file descriptor.
C struct dirent * readdir (DIR *dirp)
Read a directory.
C int closedir (DIR *dirp)
Close a directory stream.
C int open (const char *path, int oflag,...)
Open file relative to directory file descriptor.
C char * basename (char *path)
Return the last component of a pathname.
C char * dirname (char *path)
Return the directory portion of a pathname.
C int abs (int number)
Compute the absolute value of a number.
C u32 sqrt (u32 number)
Compute the square root of a number.
int main (int argc, char **argv)
Program entry point.
ProcessID findMount (const char *path)
Retrieve the ProcessID of the FileSystemMount for the given path.
ProcessID findMount (int fildes)
Lookup the ProcessID of a FileSystemMount by a filedescriptor number.
void refreshMounts (const char *path)
Refresh mounted filesystems.
void waitMount (const char *path)
Blocking wait for a mounted filesystem.
FileDescriptor * getFiles ()
Get File Descriptors table.
FileSystemMount * getMounts ()
Get mounts table.
String * getCurrentDirectory ()
Get current directory String.
C int snprintf (char *buffer, unsigned int size, const char *fmt,...)
Write a formatted string into a buffer.
C int vsnprintf (char *buffer, unsigned int size, const char *fmt, va_list args)
Write a formatted string into a buffer.
C int printf (const char *format,...)
Output a formatted string to standard output.
C int vprintf (const char *format, va_list args)
Output a formatted string to standard output, using a variable argument list.
C void exit (int status)
Terminate a process.
C void itoa (char *buffer, int divisor, int number)
Convert a number to a string.
C int atoi (const char *nptr)
Convert a string to an integer.
C long strtol (const char *nptr, char **endptr, int base)
Convert a string to a long integer.
C void * malloc (size_t size)
A memory allocator.
C void free (void *ptr)
Free allocated memory.
C void srandom (unsigned int seed)
Random number generator.
C long int random (void)
Random number generator.
C int strcmp (const char *dest, const char *src)
Compare two strings.
C int strncmp (const char *dest, const char *src, size_t count)
Compare two strings, by only a maximum number of bytes.
C int strcasecmp (const char *dest, const char *src)
Compare two strings, ignoring case considerations.
C int strncasecmp (const char *dest, const char *src, size_t count)
Compare two strings, ignoring case considerations.
C char * strdup (const char *str)
Duplicate a string.
C char * strndup (const char *s, size_t size)
Duplicate a specific number of bytes from a string.
C void * memset (void *dest, int ch, size_t count)
Fill memory with a constant byte.
C void * memcpy (void *dest, const void *src, size_t count)
Copy memory from one place to another.
C size_t strlen (const char *str)
Calculate the length of a string.
C int strcpy (char *dest, const char *src)
Copy a string.
C int strncpy (char *dest, const char *src, size_t sz)
Copy a string, given a maximum number of bytes.
C size_t strlcpy (char *dst, const char *src, size_t siz)
Copy src to string dst of size siz.
C char * strcat (char *dest, const char *src)
Concatenate two strings.
C char * strncat (char *dest, const char *src, size_t siz)
Concatenate a string with part of another.
C char * strerror (int errnum)
The strerror function maps the number in errnum to a message string.
C char * strchr (const char *s, int c)
String scanning operation.
C char * strrchr (const char *s, int c)
String scanning operation.
C int socket (int domain, int type, int protocol)
Create socket endpoint for communication.
C int bind (int sockfd, const struct sockaddr *addr, socklen_t addrlen)
C int listen (int sockfd, int backlog)
Listen for connections on a socket.
C int accept (int sockfd, struct sockaddr *addr, socklen_t addrlen)
C int connect (int sockfd, struct sockaddr *addr, socklen_t addrlen)
C int recvfrom (int sockfd, void *buf, size_t len, int flags, struct sockaddr *addr, socklen_t addrlen)
C int sendto (int sockfd, const void *buf, size_t len, int flags, const struct sockaddr *addr, socklen_t addrlen)
C int shutdown (int sockfd, int how)
C int stat (const char *path, struct stat *buf)
Get file status.
C int mknod (const char *path, mode_t mode, dev_t dev)
Make directory, special file, or regular file.
C int mkdir (const char *path, mode_t mode)
Create a new directory.
C int creat (const char *path, mode_t mode)
Create a new file or rewrite an existing one.
C int gettimeofday (struct timeval *tv, struct timezone *tz)
Get current time of day.
C int printtimediff (struct timeval *t1, struct timeval *t2)
Print time difference.
C int uname (struct utsname *name)
Get the name of the current system.
C pid_t waitpid (pid_t pid, int *stat_loc, int options)
Wait for a child process to stop or terminate.
C unsigned long mktime (const unsigned int year, const unsigned int month, const unsigned int day, const unsigned int hour, const unsigned int min, const unsigned int sec)
Convert given time values to UNIX timestamp (seconds since epoch)
C pid_t getpid ()
Get the process ID.
C pid_t getppid ()
Get parent process ID.
C ssize_t read (int fildes, void *buf, size_t nbyte)
Read from a file.
C ssize_t write (int fildes, const void *buf, size_t nbyte)
Write on a file.
C int close (int fildes)
Close a file descriptor.
C off_t lseek (int fildes, off_t offset, int whence)
Move the read/write file offset.
C int forkexec (const char *path, const char *argv[])
Create a new process and execute program.
C int spawn (Address program, Size programSize, const char *command)
Create a new process using in-memory image.
C int gethostname (char *name, size_t namelen)
Get name of current host.
C char * getcwd (char *buf, size_t size)
Get the pathname of the current working directory.
C int chdir (const char *path)
Change working directory.
C int unlink (const char *path)
Remove a file from the filesystem.
C unsigned int sleep (unsigned int seconds)
Sleep for the specified number of seconds.
Variables
C int errno
The lvalue errno is used by many functions to return error values.
C char * error_map []
Contains a array of character strings, representing errno values.
Error codes
Functions that use errno variable can set the errno value to any of these values.
See also
errno
#define ESUCCESS 0
Reports a success operation.
#define E2BIG -1
Argument list too long.
#define EACCES -2
Permission denied.
#define EADDRINUSE -3
Address in use.
#define EADDRNOTAVAIL -4
Address not available.
#define EAFNOSUPPORT -5
Address family not supported.
#define EAGAIN -6
Resource unavailable, try again (may be the same value as [EWOULDBLOCK]).
#define EALREADY -7
Connection already in progress.
#define EBADF -8
Bad file descriptor.
#define EBADMSG -9
Bad message.
#define EBUSY -10
Device or resource busy.
#define ECANCELED -11
Operation canceled.
#define ECHILD -12
No child processes.
#define ECONNABORTED -13
Connection aborted.
#define ECONNREFUSED -14
Connection refused.
#define ECONNRESET -15
Connection reset.
#define EDEADLK -16
Resource deadlock would occur.
#define EDESTADDRREQ -17
Destination address required.
#define EDOM -18
Mathematics argument out of domain of function.
#define EDQUOT -19
Reserved.
#define EEXIST -20
File exists.
#define EFAULT -21
Bad address.
#define EFBIG -22
File too large.
#define EHOSTUNREACH -23
Host is unreachable.
#define EIDRM -24
Identifier removed.
#define EILSEQ -25
Illegal byte sequence.
#define EINPROGRESS -26
Operation in progress.
#define EINTR -27
Interrupted function.
#define EINVAL -28
Invalid argument.
#define EIO -29
I/O error.
#define EISCONN -30
Socket is connected.
#define EISDIR -31
Is a directory.
#define ELOOP -32
Too many levels of symbolic links.
#define EMFILE -33
File descriptor value too large.
#define EMLINK -34
Too many links.
#define EMSGSIZE -35
Message too large.
#define EMULTIHOP -36
Reserved.
#define ENAMETOOLONG -37
Filename too long.
#define ENETDOWN -38
Network is down.
#define ENETRESET -39
Connection aborted by network.
#define ENETUNREACH -40
Network unreachable.
#define ENFILE -41
Too many files open in system.
#define ENOBUFS -42
No buffer space available.
#define ENODATA -43
No message is available on the STREAM head read queue.
#define ENODEV -44
No such device.
#define ENOENT -45
No such file or directory.
#define ENOEXEC -46
Executable file format error.
#define ENOLCK -47
No locks available.
#define ENOLINK -48
Reserved.
#define ENOMEM -49
Not enough space.
#define ENOMSG -50
No message of the desired type.
#define ENOPROTOOPT -51
Protocol not available.
#define ENOSPC -52
No space left on device.
#define ENOSR -53
No STREAM resources.
#define ENOSTR -54
Not a STREAM.
#define ENOSYS -55
Function not supported.
#define ENOTCONN -56
The socket is not connected.
#define ENOTDIR -57
Not a directory.
#define ENOTEMPTY -58
Directory not empty.
#define ENOTRECOVERABLE -59
State not recoverable.
#define ENOTSOCK -60
Not a socket.
#define ENOTSUP -61
Not supported (may be the same value as [EOPNOTSUPP]).
#define ENOTTY -62
Inappropriate I/O control operation.
#define ENXIO -63
No such device or address.
#define EOPNOTSUPP -64
Operation not supported on socket (may be the same value as [ENOTSUP]).
#define EOVERFLOW -65
Value too large to be stored in data type.
#define EOWNERDEAD -66
Previous owner died.
#define EPERM -67
Operation not permitted.
#define EPIPE -68
Broken pipe.
#define EPROTO -69
Protocol error.
#define EPROTONOSUPPORT -70
Protocol not supported.
#define EPROTOTYPE -71
Protocol wrong type for socket.
#define ERANGE -72
Result too large.
#define EROFS -73
Read-only file system.
#define ESPIPE -74
Invalid seek.
#define ESRCH -75
No such process.
#define ESTALE -76
Reserved.
#define ETIME -77
Stream ioctl() timeout.
#define ETIMEDOUT -78
Connection timed out.
#define ETXTBSY -79
Text file busy.
#define EWOULDBLOCK -80
Operation would block (may be the same value as [EAGAIN]).
#define EXDEV -81
Cross-device link.
#define ERESTART (1 << 17)
Triggers a restart of all filesystem requests.
#define ELAST ERESTART
Last defined error value (do not use).
File Constants
#define O_CREAT (1 << 0)
Create file if it does not exist.
#define O_EXCL (1 << 1)
Exclusive use flag.
#define O_NOCTTY (1 << 2)
Do not assign controlling terminal.
#define O_TRUNC (1 << 3)
Truncate flag.
#define O_TTY_INIT (1 << 4)
Set the termios structure terminal parameters to a state that provides conforming behavior; see Parameters that Can be Set.
#define O_APPEND (1 << 5)
Set append mode.
#define O_DSYNC (1 << 6)
Write according to synchronized I/O data integrity completion.
#define O_NONBLOCK (1 << 7)
Non-blocking mode.
#define O_RSYNC (1 << 8)
Synchronized read I/O operations.
#define O_SYNC (1 << 9)
Write according to synchronized I/O file integrity completion.
#define O_ACCMODE (O_EXEC | O_RDONLY | O_RDWR | O_SEARCH | O_WRONLY)
Mask for file access modes.
#define O_EXEC (1 << 10)
Open for execute only (non-directory files).
#define O_RDONLY (1 << 11)
Open for reading only.
#define O_RDWR (1 << 12)
Open for reading and writing.
#define O_SEARCH (1 << 13)
Open directory for search only.
#define O_WRONLY (1 << 14)
Open for writing only.
File seek operations
#define SEEK_CUR 0
Seek relative to current position.
#define SEEK_END 1
Seek relative to end-of-file.
#define SEEK_SET 2
Seek relative to start-of-file.
File streams
typedef struct FILE FILE
A structure containing information about a file.
C FILE * fopen (const char *filename, const char *mode)
Open a stream.
C size_t fread (void *ptr, size_t size, size_t nitems, FILE *stream)
Binary input.
C int fclose (FILE *stream)
Close a stream.
File stat type bits.
The <sys/stat.h> header shall define the following symbolic constants for the file types encoded in type mode_t.
The values shall be suitable for use in #if preprocessing directives.
#define S_IFMT (FILETYPE_MASK << FILEMODE_BITS)
Type of file.
#define S_IFBLK (BlockDeviceFile << FILEMODE_BITS)
Block special.
#define S_IFCHR (CharacterDeviceFile << FILEMODE_BITS)
Character special.
#define S_IFIFO (FIFOFile << FILEMODE_BITS)
FIFO special.
#define S_IFREG (RegularFile << FILEMODE_BITS)
Regular.
#define S_IFDIR (DirectoryFile << FILEMODE_BITS)
Directory.
#define S_IFLNK (SymlinkFile << FILEMODE_BITS)
Symbolic link.
#define S_IFSOCK (SocketFile << FILEMODE_BITS)
Socket.
#define S_IRWXU OwnerRWX
File mode bits.
#define S_IRUSR OwnerR
Read permission, owner.
#define S_IWUSR OwnerW
Write permission, owner.
#define S_IXUSR OwnerX
Execute/search permission, owner.
#define S_IRWXG GroupRWX
Read, write, execute/search by group.
#define S_IRGRP GroupR
Read permission, group.
#define S_IWGRP GroupW
Write permission, group.
#define S_IXGRP GroupX
Execute/search permission, group.
#define S_IRWXO OtherRWX
Read, write, execute/search by others.
#define S_IROTH OtherR
Read permission, others.
#define S_IWOTH OtherW
Write permission, others.
#define S_IXOTH OtherX
Execute/search permission, others.
File type macros.
The following macros shall be provided to test whether a file is of the specified type.
The value m supplied to the macros is the value of st_mode from a stat structure. The macro shall evaluate to a non-zero value if the test is true; 0 if the test is false.
#define S_ISTYPE(mode, mask) (((mode) & S_IFMT) == (mask))
Test for mode bits.
#define S_ISBLK(m) S_ISTYPE(m, S_IFBLK)
Test for a block special file.
#define S_ISCHR(m) S_ISTYPE(m, S_IFCHR)
Test for a character special file.
#define S_ISDIR(m) S_ISTYPE(m, S_IFDIR)
Test for a directory.
#define S_ISFIFO(m) S_ISTYPE(m, S_IFIFO)
Test for a pipe or FIFO special file.
#define S_ISREG(m) S_ISTYPE(m, S_IFREG)
Test for a regular file.
#define S_ISLNK(m) S_ISTYPE(m, S_IFLNK)
Test for a symbolic link.
#define S_ISSOCK(m) S_ISTYPE(m, S_IFSOCK)
Test for a socket.
Detailed Description
Provides support for the POSIX.1-2008 portable operating system interface for user programs.
Macro Definition Documentation
_POSIX2_VERSION
#define _POSIX2_VERSION 200809L
Integer value indicating version of the Shell and Utilities volume of POSIX.1 to which the implementation conforms.
For implementations conforming to POSIX.1-2008, the value shall be 200809L.
Definition at line 45 of file unistd.h.
_POSIX_VERSION
#define _POSIX_VERSION 200809L
Integer value indicating version of this standard (C-language binding) to which the implementation conforms.
For implementations conforming to POSIX.1-2008, the value shall be 200809L.
Definition at line 38 of file unistd.h.
ARGV_COUNT
#define ARGV_COUNT (PAGESIZE / ARGV_SIZE)
Number of arguments at maximum.
Definition at line 41 of file Runtime.h.
Referenced by SECTION().
ARGV_SIZE
#define ARGV_SIZE 128
Maximum size of each argument.
Definition at line 38 of file Runtime.h.
Referenced by forkexec(), SECTION(), and spawn().
assert
#define assert (exp)
Value:
if (!(exp)) \
    { \
        printf("[%s:%d]: *** Assertion `%s' failed ***\n", \
                __FILE__, __LINE__, #exp); \
        exit(1); \
    }
Insert program diagnostics.
The assert() macro shall insert diagnostics into programs; it shall expand to a void expression. When it is executed, if expression (which shall have a scalar type) is false (that is, compares equal to 0), assert() shall write information about the particular call that failed on stderr and shall call abort().
The information written about the call that failed shall include the text of the argument, the name of the source file, the source file line number, and the name of the enclosing function; the latter are, respectively, the values of the preprocessing macros FILE and LINE and of the identifier func.
Forcing a definition of the name NDEBUG, either from the compiler command line or with the preprocessor control statement #define NDEBUG ahead of the #include <assert.h> statement, shall stop assertions from being compiled into the program.
Parameters
exp Boolean expression.
Returns
The assert() macro shall not return a value.
Definition at line 60 of file assert.h.
Referenced by LinnCreate::create(), IntelKernel::exception(), hash(), HashTable< String, FileCache *>::HashTable(), BitArray::isSet(), Vector< List< HashTable::Bucket > >::resize(), and Vector< List< HashTable::Bucket > >::Vector().
CHAR_BIT
#define CHAR_BIT 8
Number of bits in a type char.
Definition at line 33 of file limits.h.
Referenced by abs().
DIRLEN
#define DIRLEN 64
Maximum length of a directory entry name.
Definition at line 59 of file dirent.h.
Referenced by opendir().
dprintf
#define dprintf (fmt, ...) printf("{%s:%d}: " fmt, __FILE__, __LINE__, ##__VA_ARGS__);
Output a debug message using printf().
Parameters
fmt Formatted string.
... Argument list.
See also
printf
Definition at line 154 of file stdio.h.
DT_BLK
#define DT_BLK 6
This is a block device.
Definition at line 47 of file dirent.h.
Referenced by opendir().
DT_CHR
#define DT_CHR 2
This is a character device.
Definition at line 41 of file dirent.h.
Referenced by opendir().
DT_DIR
#define DT_DIR 4
This is a directory.
Definition at line 44 of file dirent.h.
Referenced by opendir(), and DirectoryScanner::scan().
DT_FIFO
#define DT_FIFO 1
This is a named pipe (FIFO).
Definition at line 38 of file dirent.h.
Referenced by opendir().
DT_LNK
#define DT_LNK 10
This is a symbolic link.
Definition at line 53 of file dirent.h.
Referenced by opendir().
DT_REG
#define DT_REG 8
This is a regular file.
Definition at line 50 of file dirent.h.
Referenced by opendir(), and DirectoryScanner::scan().
DT_SOCK
#define DT_SOCK 12
This is a Unix domain socket.
Definition at line 56 of file dirent.h.
Referenced by opendir().
DT_UNKNOWN
#define DT_UNKNOWN 0
The file type is unknown.
Definition at line 35 of file dirent.h.
E2BIG
#define E2BIG -1
Argument list too long.
Definition at line 46 of file errno.h.
EACCES
#define EACCES -2
Permission denied.
Definition at line 49 of file errno.h.
Referenced by FileSystem::processRequest(), and LinnDirectory::read().
EADDRINUSE
#define EADDRINUSE -3
Address in use.
Definition at line 52 of file errno.h.
EADDRNOTAVAIL
#define EADDRNOTAVAIL -4
Address not available.
Definition at line 55 of file errno.h.
EAFNOSUPPORT
#define EAFNOSUPPORT -5
Address family not supported.
Definition at line 58 of file errno.h.
EAGAIN
#define EAGAIN -6
Resource unavailable, try again (may be the same value as [EWOULDBLOCK]).
Definition at line 61 of file errno.h.
Referenced by ARP::lookupAddress(), FileSystem::pathHandler(), FileSystem::processRequest(), UDPSocket::read(), ICMPSocket::read(), PL011::read(), Keyboard::read(), i8250::read(), FileSystem::retryRequests(), ARP::sendReply(), ARP::sendRequest(), sleep(), SynopsisController::transfer(), MountWaitFile::write(), PL011::write(), and i8250::write().
EALREADY
#define EALREADY -7
Connection already in progress.
Definition at line 64 of file errno.h.
EBADF
#define EBADF -8
Bad file descriptor.
Definition at line 67 of file errno.h.
Referenced by CoreServer::createProcess().
EBADMSG
#define EBADMSG -9
Bad message.
Definition at line 70 of file errno.h.
EBUSY
#define EBUSY -10
Device or resource busy.
Definition at line 73 of file errno.h.
ECANCELED
#define ECANCELED -11
Operation canceled.
Definition at line 76 of file errno.h.
ECHILD
#define ECHILD -12
No child processes.
Definition at line 79 of file errno.h.
ECONNABORTED
#define ECONNABORTED -13
Connection aborted.
Definition at line 82 of file errno.h.
ECONNREFUSED
#define ECONNREFUSED -14
Connection refused.
Definition at line 85 of file errno.h.
ECONNRESET
#define ECONNRESET -15
Connection reset.
Definition at line 88 of file errno.h.
EDEADLK
#define EDEADLK -16
Resource deadlock would occur.
Definition at line 91 of file errno.h.
EDESTADDRREQ
#define EDESTADDRREQ -17
Destination address required.
Definition at line 94 of file errno.h.
EDOM
#define EDOM -18
Mathematics argument out of domain of function.
Definition at line 97 of file errno.h.
EDQUOT
#define EDQUOT -19
Reserved.
Definition at line 100 of file errno.h.
EEXIST
#define EEXIST -20
File exists.
Definition at line 103 of file errno.h.
Referenced by FileSystem::processRequest().
EFAULT
#define EFAULT -21
Bad address.
Definition at line 106 of file errno.h.
Referenced by forkexec(), LinnDirectory::read(), VGA::read(), spawn(), and VGA::write().
EFBIG
#define EFBIG -22
File too large.
Definition at line 109 of file errno.h.
EHOSTUNREACH
#define EHOSTUNREACH -23
Host is unreachable.
Definition at line 112 of file errno.h.
Referenced by ARP::sendRequest().
EIDRM
#define EIDRM -24
Identifier removed.
Definition at line 115 of file errno.h.
EILSEQ
#define EILSEQ -25
Illegal byte sequence.
Definition at line 118 of file errno.h.
EINPROGRESS
#define EINPROGRESS -26
Operation in progress.
Definition at line 121 of file errno.h.
EINTR
#define EINTR -27
Interrupted function.
Definition at line 124 of file errno.h.
EINVAL
#define EINVAL -28
Invalid argument.
Definition at line 127 of file errno.h.
Referenced by UDP::bind(), CoreServer::getCoreCount(), PL011::initialize(), UDP::process(), Ethernet::process(), ARP::process(), IPV4::process(), LinnDirectory::read(), and ARP::sendReply().
EIO
#define EIO -29
I/O error.
Definition at line 130 of file errno.h.
Referenced by USBDevice::beginTransfer(), connect(), forkexec(), USBDevice::initialize(), SynopsisController::initialize(), USBHub::portAttach(), UDPSocket::process(), FileSystem::processRequest(), UDPFactory::read(), MountsFile::read(), ICMPFactory::read(), LinnFile::read(), ATAController::read(), sleep(), spawn(), USBDevice::submit(), SynopsisController::transfer(), USBTransferFile::write(), MountWaitFile::write(), and MountsFile::write().
EISCONN
#define EISCONN -30
Socket is connected.
Definition at line 133 of file errno.h.
EISDIR
#define EISDIR -31
Is a directory.
Definition at line 136 of file errno.h.
ELAST
#define ELAST ERESTART
Last defined error value (do not use).
Definition at line 292 of file errno.h.
Referenced by strerror().
ELOOP
#define ELOOP -32
Too many levels of symbolic links.
Definition at line 139 of file errno.h.
EMFILE
#define EMFILE -33
File descriptor value too large.
Definition at line 142 of file errno.h.
EMLINK
#define EMLINK -34
Too many links.
Definition at line 145 of file errno.h.
EMSGSIZE
#define EMSGSIZE -35
Message too large.
Definition at line 148 of file errno.h.
EMULTIHOP
#define EMULTIHOP -36
Reserved.
Definition at line 151 of file errno.h.
ENAMETOOLONG
#define ENAMETOOLONG -37
Filename too long.
Definition at line 154 of file errno.h.
ENETDOWN
#define ENETDOWN -38
Network is down.
Definition at line 157 of file errno.h.
ENETRESET
#define ENETRESET -39
Connection aborted by network.
Definition at line 160 of file errno.h.
ENETUNREACH
#define ENETUNREACH -40
Network unreachable.
Definition at line 163 of file errno.h.
ENFILE
#define ENFILE -41
Too many files open in system.
Definition at line 166 of file errno.h.
Referenced by open().
ENOBUFS
#define ENOBUFS -42
No buffer space available.
Definition at line 169 of file errno.h.
Referenced by MountsFile::write().
ENODATA
#define ENODATA -43
No message is available on the STREAM head read queue.
Definition at line 172 of file errno.h.
ENODEV
#define ENODEV -44
No such device.
Definition at line 175 of file errno.h.
ENOENT
#define ENOENT -45
No such file or directory.
Definition at line 178 of file errno.h.
Referenced by close(), creat(), lseek(), mkdir(), mknod(), open(), FileSystem::processRequest(), read(), stat(), unlink(), and write().
ENOEXEC
#define ENOEXEC -46
Executable file format error.
Definition at line 181 of file errno.h.
Referenced by forkexec(), and spawn().
ENOLCK
#define ENOLCK -47
No locks available.
Definition at line 184 of file errno.h.
ENOLINK
#define ENOLINK -48
Reserved.
Definition at line 187 of file errno.h.
ENOMEM
#define ENOMEM -49
Not enough space.
Definition at line 190 of file errno.h.
ENOMSG
#define ENOMSG -50
No message of the desired type.
Definition at line 193 of file errno.h.
ENOPROTOOPT
#define ENOPROTOOPT -51
Protocol not available.
Definition at line 196 of file errno.h.
ENOSPC
#define ENOSPC -52
No space left on device.
Definition at line 199 of file errno.h.
ENOSR
#define ENOSR -53
No STREAM resources.
Definition at line 202 of file errno.h.
ENOSTR
#define ENOSTR -54
Not a STREAM.
Definition at line 205 of file errno.h.
ENOSYS
#define ENOSYS -55
Function not supported.
Definition at line 208 of file errno.h.
ENOTCONN
#define ENOTCONN -56
The socket is not connected.
Definition at line 211 of file errno.h.
ENOTDIR
#define ENOTDIR -57
Not a directory.
Definition at line 214 of file errno.h.
Referenced by chdir().
ENOTEMPTY
#define ENOTEMPTY -58
Directory not empty.
Definition at line 217 of file errno.h.
Referenced by FileSystem::processRequest().
ENOTRECOVERABLE
#define ENOTRECOVERABLE -59
State not recoverable.
Definition at line 220 of file errno.h.
ENOTSOCK
#define ENOTSOCK -60
Not a socket.
Definition at line 223 of file errno.h.
ENOTSUP
#define ENOTSUP -61
Not supported (may be the same value as [EOPNOTSUPP]).
Definition at line 226 of file errno.h.
Referenced by fopen(), LinnFileSystem::notSupportedHandler(), ARP::process(), Storage::read(), File::read(), SynopsisController::transfer(), EthernetAddress::write(), Storage::write(), and File::write().
ENOTTY
#define ENOTTY -62
Inappropriate I/O control operation.
Definition at line 229 of file errno.h.
ENXIO
#define ENXIO -63
No such device or address.
Definition at line 232 of file errno.h.
EOPNOTSUPP
#define EOPNOTSUPP -64
Operation not supported on socket (may be the same value as [ENOTSUP]).
Definition at line 235 of file errno.h.
EOVERFLOW
#define EOVERFLOW -65
Value too large to be stored in data type.
Definition at line 238 of file errno.h.
EOWNERDEAD
#define EOWNERDEAD -66
Previous owner died.
Definition at line 241 of file errno.h.
EPERM
#define EPERM -67
Operation not permitted.
Definition at line 244 of file errno.h.
EPIPE
#define EPIPE -68
Broken pipe.
Definition at line 247 of file errno.h.
EPROTO
#define EPROTO -69
Protocol error.
Definition at line 250 of file errno.h.
EPROTONOSUPPORT
#define EPROTONOSUPPORT -70
Protocol not supported.
Definition at line 253 of file errno.h.
EPROTOTYPE
#define EPROTOTYPE -71
Protocol wrong type for socket.
Definition at line 256 of file errno.h.
ERANGE
#define ERANGE -72
Result too large.
Definition at line 259 of file errno.h.
Referenced by close(), gettimeofday(), lseek(), IPV4::process(), ARPSocket::read(), read(), recvfrom(), sendto(), SMSC95xxUSB::transmit(), IPV4Address::write(), and write().
ERESTART
#define ERESTART (1 << 17)
Triggers a restart of all filesystem requests.
Definition at line 289 of file errno.h.
Referenced by Loopback::transmit().
EROFS
#define EROFS -73
Read-only file system.
Definition at line 262 of file errno.h.
ESPIPE
#define ESPIPE -74
Invalid seek.
Definition at line 265 of file errno.h.
ESRCH
#define ESRCH -75
No such process.
Definition at line 268 of file errno.h.
ESTALE
#define ESTALE -76
Reserved.
Definition at line 271 of file errno.h.
ESUCCESS
#define ESUCCESS 0
Reports a success operation.
Definition at line 43 of file errno.h.
Referenced by USBDevice::beginTransfer(), UDP::bind(), connect(), creat(), CoreServer::createProcess(), USBDevice::finishTransfer(), Loopback::getAddress(), SMSC95xx::getAddress(), Ethernet::getAddress(), IPV4::getAddress(), CoreServer::getCoreCount(), getcwd(), SMSC95xxUSB::getMACAddress(), IPV4::getTransmitPacket(), USBController::initialize(), AnalogPort::initialize(), DigitalPort::initialize(), SMSC95xx::initialize(), Keyboard::initialize(), Device::initialize(), NetworkDevice::initialize(), USBDevice::initialize(), DeviceServer::initialize(), LCDBar::initialize(), i8250::initialize(), UDP::initialize(), PN532::initialize(), ICMP::initialize(), Ethernet::initialize(), USBHub::initialize(), Time::initialize(), VGA::initialize(), IPV4::initialize(), ARP::initialize(), Terminal::initialize(), SynopsisController::initialize(), SMSC95xxUSB::initialize(), ATAController::initialize(), PL011::interrupt(), Keyboard::interrupt(), Device::interrupt(), i8250::interrupt(), ATAController::interrupt(), ARP::lookupAddress(), mkdir(), mknod(), FileSystem::mount(), MPI_Init(), open(), opendir(), USBHub::portAttach(), ARPSocket::process(), UDPSocket::process(), ICMPSocket::process(), UDP::process(), ICMP::process(), NetworkDevice::process(), FileSystem::processRequest(), ARPSocket::read(), SMSC95xxUSB::read(), SMSC95xxUSB::readStart(), FileSystem::registerFile(), UDP::sendPacket(), ICMP::sendPacket(), Loopback::setAddress(), SMSC95xx::setAddress(), USBDevice::setAddress(), Ethernet::setAddress(), IPV4::setAddress(), SMSC95xxUSB::setMACAddress(), stat(), File::status(), USBDevice::submit(), SynopsisController::transfer(), unlink(), IPV4Address::write(), ARPSocket::write(), UDPSocket::write(), ICMPSocket::write(), and SMSC95xxUSB::write().
ETIME
#define ETIME -77
Stream ioctl() timeout.
Definition at line 274 of file errno.h.
ETIMEDOUT
#define ETIMEDOUT -78
Connection timed out.
Definition at line 277 of file errno.h.
ETXTBSY
#define ETXTBSY -79
Text file busy.
Definition at line 280 of file errno.h.
EWOULDBLOCK
#define EWOULDBLOCK -80
Operation would block (may be the same value as [EAGAIN]).
Definition at line 283 of file errno.h.
EXDEV
#define EXDEV -81
Cross-device link.
Definition at line 286 of file errno.h.
EXIT_FAILURE
#define EXIT_FAILURE 1
Unsuccessful termination.
Definition at line 36 of file stdlib.h.
Referenced by __assertFailure(), NetSend::arpRequest(), LinnCreate::createInode(), ChangeDirCommand::execute(), WriteCommand::execute(), TimeCommand::execute(), Shell::executeInput(), Terminal::initialize(), ATAController::initialize(), LinnCreate::insertDirectory(), LinnCreate::insertEntry(), LinnCreate::insertFile(), main(), BootImageCreate::readBootSymbols(), NetReceive::receivePacket(), DirectoryScanner::scan(), and LinnCreate::writeImage().
EXIT_SUCCESS
#define EXIT_SUCCESS 0
Successful termination.
Definition at line 33 of file stdlib.h.
Referenced by ChangeDirCommand::execute(), ExitCommand::execute(), Shell::executeInput(), main(), DirectoryScanner::scan(), and LinnCreate::writeImage().
FILE_DESCRIPTOR_MAX
#define FILE_DESCRIPTOR_MAX 1024
Definition at line 35 of file FileDescriptor.h.
Referenced by USBDevice::beginTransfer(), close(), lseek(), open(), read(), and write().
FILESYSTEM_MAXMOUNTS
#define FILESYSTEM_MAXMOUNTS 16
Maximum number of mounted filesystems.
Definition at line 33 of file FileSystemMount.h.
Referenced by Mount::exec(), NetCtl::exec(), findMount(), NetworkClient::initialize(), MountsFile::MountsFile(), refreshMounts(), setupMappings(), MountWaitFile::write(), and MountsFile::write().
isalnum
#define isalnum (c) Character::isAlnum(c)
Test for an alphanumeric character.
Parameters
c Input character.
Returns
Boolean
Definition at line 72 of file ctype.h.
isalpha
#define isalpha (c) Character::isAlpha(c)
Test for an alphabetic character.
Parameters
c Input character.
Returns
Boolean
Definition at line 63 of file ctype.h.
isblank
#define isblank (c) Character::isBlank(c)
Test for a blank character.
Parameters
c Input character.
Returns
Boolean
Definition at line 81 of file ctype.h.
isdigit
#define isdigit (c) Character::isDigit(c)
Test for a decimal digit.
Parameters
c Input character.
Definition at line 36 of file ctype.h.
islower
#define islower (c) Character::isLower(c)
Test for a lowercase letter.
Parameters
c Input character.
Returns
Boolean
Definition at line 45 of file ctype.h.
isspace
#define isspace (c) Character::isSpace(c)
Test for a white-space character.
Parameters
c Input character.
Returns
Boolean
Definition at line 90 of file ctype.h.
isupper
#define isupper (c) Character::isUpper(c)
Test for an uppercase letter.
Parameters
c Input character.
Returns
Boolean
Definition at line 54 of file ctype.h.
O_ACCMODE
#define O_ACCMODE (O_EXEC | O_RDONLY | O_RDWR | O_SEARCH | O_WRONLY)
Mask for file access modes.
Definition at line 72 of file fcntl.h.
O_APPEND
#define O_APPEND (1 << 5)
Set append mode.
Definition at line 57 of file fcntl.h.
O_CREAT
#define O_CREAT (1 << 0)
Create file if it does not exist.
Definition at line 39 of file fcntl.h.
O_DSYNC
#define O_DSYNC (1 << 6)
Write according to synchronized I/O data integrity completion.
Definition at line 60 of file fcntl.h.
O_EXCL
#define O_EXCL (1 << 1)
Exclusive use flag.
Definition at line 42 of file fcntl.h.
O_EXEC
#define O_EXEC (1 << 10)
Open for execute only (non-directory files).
The result is unspecified if this flag is applied to a directory.
Definition at line 78 of file fcntl.h.
O_NOCTTY
#define O_NOCTTY (1 << 2)
Do not assign controlling terminal.
Definition at line 45 of file fcntl.h.
O_NONBLOCK
#define O_NONBLOCK (1 << 7)
Non-blocking mode.
Definition at line 63 of file fcntl.h.
O_RDONLY
#define O_RDONLY (1 << 11)
Open for reading only.
Definition at line 81 of file fcntl.h.
Referenced by Cat::cat(), Login::exec(), forkexec(), Terminal::initialize(), LinnCreate::insertFile(), CoreServer::loadKernel(), main(), MPI_Init(), and NetCtl::showDevice().
O_RDWR
#define O_RDWR (1 << 12)
Open for reading and writing.
Definition at line 84 of file fcntl.h.
Referenced by NetSend::arpRequest(), NetworkClient::createSocket(), Login::exec(), StdioCommand::execute(), FileStorage::FileStorage(), USBDevice::initialize(), Terminal::initialize(), main(), and NetReceive::receivePacket().
O_RSYNC
#define O_RSYNC (1 << 8)
Synchronized read I/O operations.
Definition at line 66 of file fcntl.h.
O_SEARCH
#define O_SEARCH (1 << 13)
Open directory for search only.
The result is unspecified if this flag is applied to a non-directory file.
Definition at line 90 of file fcntl.h.
O_SYNC
#define O_SYNC (1 << 9)
Write according to synchronized I/O file integrity completion.
Definition at line 69 of file fcntl.h.
O_TRUNC
#define O_TRUNC (1 << 3)
Truncate flag.
Definition at line 48 of file fcntl.h.
O_TTY_INIT
#define O_TTY_INIT (1 << 4)
Set the termios structure terminal parameters to a state that provides conforming behavior; see Parameters that Can be Set.
Definition at line 54 of file fcntl.h.
O_WRONLY
#define O_WRONLY (1 << 14)
Open for writing only.
Definition at line 93 of file fcntl.h.
Referenced by WriteCommand::execute(), main(), and FileSystem::mount().
PATH_MAX
#define PATH_MAX 64
Maximum file path length.
Definition at line 36 of file limits.h.
Referenced by chdir(), creat(), dirname(), ProcessList::exec(), ListFiles::exec(), FileDescriptor::FileDescriptor(), findMount(), forkexec(), FileSystem::mount(), open(), ListFiles::printFiles(), BootImageCreate::readBootSymbols(), setupMappings(), stat(), unlink(), and MountWaitFile::write().
S_IFBLK
#define S_IFBLK (BlockDeviceFile << FILEMODE_BITS)
Block special.
Definition at line 51 of file stat.h.
S_IFCHR
#define S_IFCHR (CharacterDeviceFile << FILEMODE_BITS)
Character special.
Definition at line 54 of file stat.h.
Referenced by MakeNode::exec().
S_IFDIR
#define S_IFDIR (DirectoryFile << FILEMODE_BITS)
Directory.
Definition at line 63 of file stat.h.
S_IFIFO
#define S_IFIFO (FIFOFile << FILEMODE_BITS)
FIFO special.
Definition at line 57 of file stat.h.
S_IFLNK
#define S_IFLNK (SymlinkFile << FILEMODE_BITS)
Symbolic link.
Definition at line 66 of file stat.h.
S_IFMT
#define S_IFMT (FILETYPE_MASK << FILEMODE_BITS)
Type of file.
Definition at line 48 of file stat.h.
S_IFREG
#define S_IFREG (RegularFile << FILEMODE_BITS)
Regular.
Definition at line 60 of file stat.h.
S_IFSOCK
#define S_IFSOCK (SocketFile << FILEMODE_BITS)
Socket.
Definition at line 69 of file stat.h.
S_IRGRP
#define S_IRGRP GroupR
Read permission, group.
Definition at line 102 of file stat.h.
Referenced by ListFiles::printSingleFile().
S_IROTH
#define S_IROTH OtherR
Read permission, others.
Definition at line 114 of file stat.h.
Referenced by ListFiles::printSingleFile().
S_IRUSR
#define S_IRUSR OwnerR
Read permission, owner.
Definition at line 90 of file stat.h.
Referenced by CreateFile::createFile(), and ListFiles::printSingleFile().
S_IRWXG
#define S_IRWXG GroupRWX
Read, write, execute/search by group.
Definition at line 99 of file stat.h.
S_IRWXO
#define S_IRWXO OtherRWX
Read, write, execute/search by others.
Definition at line 111 of file stat.h.
S_IRWXU
#define S_IRWXU OwnerRWX
File mode bits.
The <sys/stat.h> header shall define the following symbolic constants for the file mode bits encoded in type mode_t, with the indicated numeric values. These macros shall expand to an expression which has a type that allows them to be used, either singly or OR'ed together, as the third argument to open() without the need for a mode_t cast. The values shall be suitable for use in #if preprocessing directives.Read, write, execute/search by owner.
Definition at line 87 of file stat.h.
S_ISBLK
#define S_ISBLK (m) S_ISTYPE(m, S_IFBLK)
Test for a block special file.
Definition at line 139 of file stat.h.
Referenced by ListFiles::printSingleFile(), and FileStatus::printStatus().
S_ISCHR
#define S_ISCHR (m) S_ISTYPE(m, S_IFCHR)
Test for a character special file.
Definition at line 142 of file stat.h.
Referenced by Cat::cat(), ListFiles::printSingleFile(), and FileStatus::printStatus().
S_ISDIR
#define S_ISDIR (m) S_ISTYPE(m, S_IFDIR)
Test for a directory.
Definition at line 145 of file stat.h.
Referenced by chdir(), LinnCreate::insertDirectory(), ListFiles::printFiles(), ListFiles::printSingleFile(), and FileStatus::printStatus().
S_ISFIFO
#define S_ISFIFO (m) S_ISTYPE(m, S_IFIFO)
Test for a pipe or FIFO special file.
Definition at line 148 of file stat.h.
S_ISLNK
#define S_ISLNK (m) S_ISTYPE(m, S_IFLNK)
Test for a symbolic link.
Definition at line 154 of file stat.h.
S_ISREG
#define S_ISREG (m) S_ISTYPE(m, S_IFREG)
Test for a regular file.
Definition at line 151 of file stat.h.
Referenced by Cat::cat(), LinnCreate::createInode(), and FileStatus::printStatus().
S_ISSOCK
#define S_ISSOCK (m) S_ISTYPE(m, S_IFSOCK)
Test for a socket.
Definition at line 157 of file stat.h.
S_ISTYPE
#define S_ISTYPE (mode, mask) (((mode) & S_IFMT) == (mask))
Test for mode bits.
Definition at line 136 of file stat.h.
S_IWGRP
#define S_IWGRP GroupW
Write permission, group.
Definition at line 105 of file stat.h.
Referenced by ListFiles::printSingleFile().
S_IWOTH
#define S_IWOTH OtherW
Write permission, others.
Definition at line 117 of file stat.h.
Referenced by ListFiles::printSingleFile().
S_IWUSR
#define S_IWUSR OwnerW
Write permission, owner.
Definition at line 93 of file stat.h.
Referenced by CreateFile::createFile(), and ListFiles::printSingleFile().
S_IXGRP
#define S_IXGRP GroupX
Execute/search permission, group.
Definition at line 108 of file stat.h.
Referenced by ListFiles::printSingleFile().
S_IXOTH
#define S_IXOTH OtherX
Execute/search permission, others.
Definition at line 120 of file stat.h.
Referenced by ListFiles::printSingleFile().
S_IXUSR
#define S_IXUSR OwnerX
Execute/search permission, owner.
Definition at line 96 of file stat.h.
Referenced by ListFiles::printSingleFile().
SEEK_CUR
#define SEEK_CUR 0
Seek relative to current position.
Definition at line 40 of file stdio.h.
SEEK_END
#define SEEK_END 1
Seek relative to end-of-file.
Definition at line 43 of file stdio.h.
SEEK_SET
#define SEEK_SET 2
Seek relative to start-of-file.
Definition at line 46 of file stdio.h.
Referenced by BootImageCreate::exec(), main(), FileStorage::read(), FileStorage::write(), and Terminal::write().
tolower
#define tolower (c) Character::lower(c)
Converts the letter c to lowercase.
Parameters
c The letter to convert.
Returns
The converted letter, or c if conversion was not possible.
Definition at line 99 of file ctype.h.
Referenced by strcasecmp(), and strncasecmp().
toupper
#define toupper (c) Character::upper(c)
Converts the letter c to uppercase.
Parameters
c The letter to convert.
Returns
The converted letter, or c if conversion was not possible.
Definition at line 108 of file ctype.h.
UTSBUF
#define UTSBUF 128
Size of each buffer in the utsname structure fields.
Definition at line 33 of file utsname.h.
Referenced by uname().
Typedef Documentation
blkcnt_t
typedef sint blkcnt_t
Used for file block counts.
Definition at line 62 of file types.h.
blksize_t
typedef sint blksize_t
Used for block sizes.
Definition at line 65 of file types.h.
dev_t
typedef DeviceID dev_t
Used for device IDs.
Definition at line 41 of file types.h.
DIR
typedef struct DIR DIR
A type representing a directory stream.
Note
The DIR type may be an incomplete type.
FILE
typedef struct FILE FILE
A structure containing information about a file.
FileSystemMount
typedef struct FileSystemMount FileSystemMount
Represents a mounted filesystem.
gid_t
typedef u16 gid_t
Used for group IDs.
Definition at line 53 of file types.h.
ino_t
typedef uint ino_t
Used for file serial numbers.
Definition at line 44 of file types.h.
mode_t
typedef uint mode_t
Used for some file attributes.
Definition at line 47 of file types.h.
nlink_t
typedef Size nlink_t
Used for link counts.
Definition at line 56 of file types.h.
off_t
typedef sint off_t
Used for file sizes.
Definition at line 59 of file types.h.
pid_t
typedef ProcessID pid_t
Used for process IDs and process group IDs.
Definition at line 32 of file types.h.
size_t
typedef Size size_t
Used for sizes of objects.
Definition at line 35 of file types.h.
socklen_t
typedef Size socklen_t
Definition at line 74 of file socket.h.
ssize_t
typedef slong ssize_t
Used for a count of bytes or an error indication.
Definition at line 38 of file types.h.
time_t
typedef u64 time_t
Used for time in seconds.
Definition at line 68 of file types.h.
uid_t
typedef u16 uid_t
Used for user IDs.
Definition at line 50 of file types.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Communication domains.
Enumerator
AF_INET
AF_INET6
AF_UNIX
Definition at line 35 of file socket.h.
anonymous enum
anonymous enum
Socket types.
Enumerator
SOCK_STREAM
SOCK_DGRAM
Definition at line 45 of file socket.h.
anonymous enum
anonymous enum
Communication Protocols.
Enumerator
IPPROTO_TCP
IPPROTO_UDP
IPPROTO_ICMP
Definition at line 54 of file socket.h.
anonymous enum
anonymous enum
Enumerator
SHUT_RD
SHUT_WR
SHUT_RDWR
Definition at line 61 of file socket.h.
Function Documentation
abs()
C int abs (int number)
Compute the absolute value of a number.
The absolute value of a number turns it to positive in case it is negative. Basically it just removes the sign (-) from a number. For example, -3 returns 3, and 8 returns 8.
Parameters
number The number to make absolute.
Returns
Absolute value of the given number.
Definition at line 21 of file abs.cpp.
References CHAR_BIT.
accept()
C int accept (int sockfd, struct sockaddr * addr, socklen_t addrlen)
Referenced by ChannelServer< FileSystem, FileSystemMessage >::readKernelEvents().
atoi()
C int atoi (const char * nptr)
Convert a string to an integer.
The atoi, atol, and atoll functions convert the initial portion of the string pointed to by nptr to int, long int, and long long int representation, respectively.
Parameters
nptr String pointer to convert.
Returns
The atoi, atol, and atoll functions return the converted value.
Definition at line 21 of file atoi.cpp.
References String::toLong().
Referenced by MakeNode::exec(), SievePrime::exec(), Sleep::exec(), NetCat::initialize(), main(), MPI_Init(), and vsnprintf().
basename()
C char* basename (char * path)
Return the last component of a pathname.
The basename() function shall take the pathname pointed to by path and return a pointer to the final component of the pathname, deleting any trailing '/' characters.
Parameters
path Filesystem path.
Returns
String pointer to the last component.
Definition at line 21 of file basename.cpp.
References strrchr().
Referenced by ListFiles::printSingleFile(), StdoutReporter::reportBefore(), and StdoutReporter::reportFinish().
bind()
C int bind (int sockfd, const struct sockaddr * addr, socklen_t addrlen)
chdir()
C int chdir (const char * path)
Change working directory.
The chdir() function shall cause the directory named by the pathname pointed to by the path argument to become the current working directory; that is, the starting point for path searches for pathnames not beginning with '/' .
Parameters
path Path to the directory to use as working directory.
Returns
Upon successful completion, 0 shall be returned. Otherwise, -1 shall be returned, the current working directory shall remain unchanged, and errno shall be set to indicate the error.
Definition at line 25 of file chdir.cpp.
References List< T >::append(), ENOTDIR, errno, getCurrentDirectory(), getcwd(), ListIterator< T >::hasCurrent(), memset(), FileSystemPath::parse(), PATH_MAX, List< T >::remove(), S_ISDIR, snprintf(), FileSystemPath::split(), stat::st_mode, stat(), strcat(), strcpy(), and ZERO.
Referenced by ChangeDirCommand::execute().
close()
C int close (int fildes)
Close a file descriptor.
Parameters
fildes The close() function shall deallocate the file descriptor indicated by fildes.
Returns
Upon successful completion, 0 shall be returned; otherwise, -1 shall be returned and errno set to indicate the error.
Definition at line 24 of file close.cpp.
References ENOENT, ERANGE, errno, FILE_DESCRIPTOR_MAX, files, getFiles(), open(), and FileDescriptor::open.
Referenced by Cat::cat(), closedir(), Login::exec(), StdioCommand::execute(), WriteCommand::execute(), fclose(), forkexec(), NetPing::icmpPing(), Terminal::initialize(), LinnCreate::insertFile(), CoreServer::loadKernel(), main(), FileSystem::mount(), MPI_Init(), NetReceive::receivePacket(), NetCtl::showDevice(), FileStorage::~FileStorage(), and Terminal::~Terminal().
closedir()
C int closedir (DIR * dirp)
Close a directory stream.
Parameters
dirp The closedir() function shall close the directory stream referred to by the argument dirp.
Returns
Upon successful completion, closedir() shall return 0; otherwise, -1 shall be returned and errno set to indicate the error.
Definition at line 22 of file closedir.cpp.
References DIR::buffer, close(), and DIR::fd.
Referenced by LinnCreate::insertDirectory(), opendir(), ListFiles::printFiles(), and DirectoryScanner::scan().
connect()
C int connect (int sockfd, struct sockaddr * addr, socklen_t addrlen)
Definition at line 23 of file connect.cpp.
References sockaddr::addr, NetworkClient::connectSocket(), EIO, ESUCCESS, NetworkClient::initialize(), and NetworkClient::Success.
Referenced by IPCTest::exec().
creat()
C int creat (const char * path, mode_t mode)
Create a new file or rewrite an existing one.
The creat() function is redundant. Its services are also provided by the open() function. It has been included primarily for historical purposes since many existing applications depend on it. It is best considered a part of the C binding rather than a function that should be provided in other languages.
Parameters
path Full path to the file to create
mode Initial access permissions for the file.
Returns
Upon successful completion, these functions shall return 0. Otherwise, these functions shall return -1 and set errno to indicate the error. If -1 is returned, no file shall be created.
Definition at line 28 of file creat.cpp.
References FileSystemMessage::action, CreateFile, ENOENT, errno, ESUCCESS, FILEMODE_MASK, FileSystemMessage::filetype, findMount(), getcwd(), Singleton< ChannelClient >::instance, FileSystemMessage::mode, FileSystemMessage::path, PATH_MAX, RegularFile, ChannelMessage::Request, FileSystemMessage::result, snprintf(), strlcpy(), ChannelClient::syncSendReceive(), and ChannelMessage::type.
Referenced by CreateFile::createFile().
dirname()
C char* dirname (char * path)
Return the directory portion of a pathname.
Parameters
path Filesystem path
Returns
String pointer to the directory of pathname.
Definition at line 22 of file dirname.cpp.
References PATH_MAX, strlcpy(), and strrchr().
exit()
C void exit (int status)
Terminate a process.
The exit function causes normal program termination to occur. If more than one call to the exit function is executed by a program, the behaviour is undefined.
Parameters
status If the value of status is zero or EXIT_SUCCESS, an implementation defined form of the status successful termination is returned. If the value of status is EXIT_FAILURE, an implementation-defined form of the status unsuccesful termination is returned. Otherwise the status is implementation-defined.
Returns
The exit function cannot return to its caller.
Definition at line 21 of file exit.cpp.
References KillPID, ProcessCtl(), and SELF.
Referenced by __assertFailure(), NetSend::arpRequest(), LinnCreate::createInode(), ExitCommand::execute(), Terminal::initialize(), ATAController::initialize(), LinnCreate::insertDirectory(), LinnCreate::insertEntry(), LinnCreate::insertFile(), BootImageCreate::readBootSymbols(), NetCat::readLine(), NetReceive::receivePacket(), and SECTION().
fclose()
C int fclose (FILE * stream)
Close a stream.
The fclose() function shall cause the stream pointed to by stream to be flushed and the associated file to be closed. Any unwritten buffered data for the stream shall be written to the file; any unread buffered data shall be discarded. Whether or not the call succeeds, the stream shall be disassociated from the file and any buffer set by the setbuf() or setvbuf() function shall be disassociated from the stream. If the associated buffer was automatically allocated, it shall be deallocated.
Parameters
stream File stream to close.
Returns
Upon successful completion, fclose() shall return 0; otherwise, it shall return EOF and set errno to indicate the error.
Definition at line 23 of file fclose.cpp.
References close(), errno, FILE::fd, and free().
Referenced by Shell::exec(), BootImageCreate::exec(), main(), BootImageCreate::readBootSymbols(), and LinnCreate::writeImage().
findMount() [1/2]
ProcessID findMount (const char * path)
Retrieve the ProcessID of the FileSystemMount for the given path.
Parameters
path Path to lookup.
Returns
ProcessID of the FileSystemMount on success and ZERO otherwise.
Definition at line 171 of file Runtime.cpp.
References FILESYSTEM_MAXMOUNTS, getcwd(), length, PATH_MAX, FileSystemMount::procID, snprintf(), strlcpy(), strlen(), strncmp(), and ZERO.
Referenced by creat(), mkdir(), mknod(), open(), stat(), and unlink().
findMount() [2/2]
ProcessID findMount (int fildes)
Lookup the ProcessID of a FileSystemMount by a filedescriptor number.
Parameters
fildes FileDescriptor number.
Returns
ProcessID of the FileSystemMount on success and ZERO otherwise.
Definition at line 230 of file Runtime.cpp.
References FileDescriptor::mount, NULL, FileDescriptor::open, and ZERO.
fopen()
C FILE* fopen (const char * filename, const char * mode)
Open a stream.
The fopen() function shall open the file whose pathname is the string pointed to by filename, and associates a stream with it. The mode argument points to a string. If the string is one of the following, the file shall be opened in the indicated mode. Otherwise, the behavior is undefined.
r or rb Open file for reading. w or wb Truncate to zero length or create file for writing. a or ab Append; open or create file for writing at end-of-file. r+ or rb+ or r+b Open file for update (reading and writing). w+ or wb+ or w+b Truncate to zero length or create file for update. a+ or ab+ or a+b Append; open or create file for update, writing at end-of-file.
Parameters
filename Path to the file to open.
mode Mode describes how to open the file.
Returns
Upon successful completion, fopen() shall return a pointer to the object controlling the stream. Otherwise, a null pointer shall be returned, and errno shall be set to indicate the error.
Definition at line 24 of file fopen.cpp.
References ENOTSUP, errno, FILE::fd, malloc(), NULL, open(), and ZERO.
Referenced by Shell::exec(), BootImageCreate::exec(), main(), BootImageCreate::readBootSymbols(), and LinnCreate::writeImage().
forkexec()
C int forkexec (const char * path, const char * argv[])
Create a new process and execute program.
Parameters
path File to execute.
argv Argument list pointer.
Returns
New process ID on success and -1 on failure.
Note
Errno is set with the appropriate error code on failure.
Definition at line 28 of file forkexec.cpp.
References Memory::Range::access, ANY, ARGV_SIZE, close(), ExecutableFormat::Region::data, EFAULT, EIO, ENOEXEC, ExecutableFormat::entry(), errno, Memory::Executable, ExecutableFormat::find(), getCurrentDirectory(), getFiles(), KillPID, Map, memset(), O_RDONLY, open(), PAGESIZE, PATH_MAX, Memory::Range::phys, ProcessCtl(), MemoryMap::range(), read(), Memory::Readable, ExecutableFormat::regions(), Resume, ExecutableFormat::Region::size, Memory::Range::size, Spawn, stat::st_size, stat(), strlcpy(), ExecutableFormat::Success, Memory::User, MemoryMap::UserArgs, Memory::Range::virt, ExecutableFormat::Region::virt, VMCopy(), VMCtl(), Memory::Writable, API::Write, and ZERO.
Referenced by Init::exec(), Login::exec(), TimeCommand::execute(), Shell::executeInput(), USBHub::portAttach(), and ExternalTest::run().
fread()
C size_t fread (void * ptr, size_t size, size_t nitems, FILE * stream)
Binary input.
The fread() function shall read into the array pointed to by ptr up to nitems elements whose size is specified by size in bytes, from the stream pointed to by stream. For each object, size calls shall be made to the fgetc() function and the results stored, in the order read, in an array of unsigned char exactly overlaying the object. The file position indicator for the stream (if defined) shall be advanced by the number of bytes successfully read. If an error occurs, the resulting value of the file position indicator for the stream is unspecified. If a partial element is read, its value is unspecified.
Parameters
ptr Output buffer.
size Size of each item to read.
nitems Number of items to read.
stream FILE pointer to read from.
Returns
Upon successful completion, fread() shall return the number of elements successfully read which is less than nitems only if a read error or end-of-file is encountered. If size or nitems is 0, fread() shall return 0 and the contents of the array and the state of the stream remain unchanged. Otherwise, if a read error occurs, the error indicator for the stream shall be set, and errno shall be set to indicate the error.
Definition at line 24 of file fread.cpp.
References FILE::fd, and read().
Referenced by Shell::exec(), main(), and BootImageCreate::readBootSymbols().
free()
C void free (void * ptr)
Free allocated memory.
The free() function shall cause the space pointed to by ptr to be deallocated; that is, made available for further allocation. If ptr is a null pointer, no action shall occur. Otherwise, if the argument does not match a pointer earlier returned by a function in POSIX.1-2008 that allocates memory as if by malloc(), or if the space has been deallocated by a call to free() or realloc(), the behavior is undefined. Any use of a pointer that refers to freed space results in undefined behavior.
Parameters
ptr Previously allocated memory to free.
Returns
The free() function shall not return a value.
Definition at line 22 of file free.cpp.
Referenced by collect(), fclose(), and main().
getCurrentDirectory()
String* getCurrentDirectory ()
Get current directory String.
Returns
String pointer containing current directory
Definition at line 263 of file Runtime.cpp.
References currentDirectory.
Referenced by chdir(), forkexec(), and getcwd().
getcwd()
C char* getcwd (char * buf, size_t size)
Get the pathname of the current working directory.
The getcwd() function shall place an absolute pathname of the current working directory in the array pointed to by buf, and return buf. The pathname shall contain no components that are dot or dot-dot, or are symbolic links.
Parameters
buf Output buffer, to store the current directory.
size Size of the output buffer.
Returns
Upon successful completion, getcwd() shall return the buf argument. Otherwise, getcwd() shall return a null pointer and set errno to indicate the error. The contents of the array pointed to by buf are then undefined.
Definition at line 23 of file getcwd.cpp.
References errno, ESUCCESS, getCurrentDirectory(), and memcpy().
Referenced by chdir(), creat(), ListFiles::exec(), findMount(), open(), Shell::prompt(), stat(), and unlink().
getFiles()
FileDescriptor* getFiles ()
Get File Descriptors table.
Returns
FileDescriptor array pointer
Definition at line 258 of file Runtime.cpp.
References files.
Referenced by USBDevice::beginTransfer(), close(), forkexec(), lseek(), open(), read(), write(), and NetworkClient::writeSocketInfo().
gethostname()
C int gethostname (char * name, size_t namelen)
Get name of current host.
The gethostname() function shall return the standard host name for the current machine. The namelen argument shall specify the size of the array pointed to by the name argument. The returned name shall be null-terminated, except that if namelen is an insufficient length to hold the host name, then the returned name shall be truncated and it is unspecified whether the returned name is null-terminated. Host names are limited to {HOST_NAME_MAX} bytes.
Parameters
name Output buffer.
namelen Size of the output buffer.
Returns
Upon successful completion, 0 shall be returned; otherwise, -1 shall be returned.
Definition at line 21 of file gethostname.cpp.
References strlcpy().
Referenced by Hostname::exec(), Shell::prompt(), and uname().
getMounts()
FileSystemMount* getMounts ()
Get mounts table.
Returns
FileSystemMount array pointer
Definition at line 253 of file Runtime.cpp.
References mounts.
Referenced by Mount::exec(), NetCtl::exec(), NetworkClient::initialize(), MountsFile::read(), MountWaitFile::write(), and MountsFile::write().
getpid()
C pid_t getpid ()
Get the process ID.
The getpid() function shall return the process ID of the calling process.
Returns
The getpid() function shall always be successful and no return value is reserved to indicate an error.
Definition at line 21 of file getpid.cpp.
References GetPID, ProcessCtl(), and SELF.
Referenced by refreshMounts(), TestData< T >::seed(), and setupRandomizer().
getppid()
C pid_t getppid ()
Get parent process ID.
Returns
The parent process ID.
Definition at line 21 of file getppid.cpp.
References GetParent, ProcessCtl(), and SELF.
Referenced by setupMappings().
gettimeofday()
C int gettimeofday (struct timeval * tv, struct timezone * tz)
Get current time of day.
Parameters
tv Timeval struct object pointer.
tz Timezone struct object pointer.
Returns
Zero on success and -1 on error.
Definition at line 22 of file gettimeofday.cpp.
References ERANGE, errno, InfoTimer, ProcessCtl(), SELF, timeval::tv_sec, and timeval::tv_usec.
Referenced by SysInfo::exec(), TimeCommand::execute(), main(), search_parallel(), and TestData< T >::seed().
itoa()
C void itoa (char * buffer, int divisor, int number)
Convert a number to a string.
Parameters
buffer String buffer to write to.
divisor Base of the number, e.g. 16 for hexadecimal.
number The number to convert.
Definition at line 21 of file itoa.cpp.
References Number::Dec, Number::Hex, and String::set().
Referenced by vsnprintf().
listen()
C int listen (int sockfd, int backlog)
Listen for connections on a socket.
Parameters
sockfd pid Process ID of child to wait for.
backlog Number of pending connections which can be queued.
Returns
Zero on success and -1 on error.
lseek()
C off_t lseek (int fildes, off_t offset, int whence)
Move the read/write file offset.
The lseek() function shall set the file offset for the open file description associated with the file descriptor fildes, as follows:
If whence is SEEK_SET, the file offset shall be set to offset bytes. If whence is SEEK_CUR, the file offset shall be set to its current location plus offset. If whence is SEEK_END, the file offset shall be set to the size of the file plus offset.
Parameters
fildes File descriptor.
offset New file offset.
whence Determines how to modify the file offset pointer.
Returns
Upon successful completion, the resulting offset, as measured in bytes from the beginning of the file, shall be returned. Otherwise, (off_t)-1 shall be returned, errno shall be set to indicate the error, and the file offset shall remain unchanged.
Definition at line 22 of file lseek.cpp.
References ENOENT, ERANGE, errno, FILE_DESCRIPTOR_MAX, files, getFiles(), open(), and FileDescriptor::position.
Referenced by main(), FileStorage::read(), FileStorage::write(), and Terminal::write().
main()
int main (int argc, char ** argv)
Program entry point.
Parameters
argc Argument count.
argv Argument values.
Returns
Exit status.
Program entry point.
Parameters
argc Argument count
argv Argument values
Returns
Zero on success or number of failed tests on failure
Definition at line 21 of file Main.cpp.
References atoi(), LinnGroup::blockMap, LinnSuperBlock::blocksCount, LinnSuperBlock::blockSize, LinnSuperBlock::blocksPerGroup, close(), SystemInformation::coreId, LinnCreate::create(), LinnSuperBlock::creationTime, DirectoryFile, errno, ERROR, EXIT_FAILURE, EXIT_SUCCESS, FATAL, fclose(), fopen(), fread(), free(), LinnSuperBlock::freeBlocksCount, LinnGroup::freeBlocksCount, LinnSuperBlock::freeInodesCount, LinnGroup::freeInodesCount, FileSystem::getRoot(), gettimeofday(), LinnSuperBlock::groupsTable, Idle, idle, INFO, NetworkServer::initialize(), DeviceServer::initialize(), CoreServer::initialize(), BroadcomSPI::initialize(), BroadcomI2C::initialize(), SynopsisController::initialize(), LinnGroup::inodeMap, LinnSuperBlock::inodesCount, LinnSuperBlock::inodesPerGroup, LinnGroup::inodeTable, Directory::insert(), FileSystem::insertFileCache(), SerialAddress::irq, LinnSuperBlock::lastCheck, length, String::length(), LINN_CREATE_BLOCK_NUM, LINN_CREATE_BLOCK_SIZE, LINN_CREATE_INODE_NUM, LINN_GROUP_COUNT, LINN_GROUP_NUM_BLOCKMAP, LINN_GROUP_NUM_INODEMAP, LINN_GROUP_NUM_INODETAB, LINN_SUPER_MAGIC0, LINN_SUPER_MAGIC1, LINN_SUPER_OFFSET, LINNFS_ROOTFS_FILE, BootImageStorage::load(), lseek(), LinnSuperBlock::magic0, LinnSuperBlock::magic1, LinnSuperBlock::majorRevision, malloc(), LinnSuperBlock::minorRevision, FileSystem::mount(), LinnSuperBlock::mountCount, LinnSuperBlock::mountTime, MPI_Comm_rank(), MPI_Comm_size(), MPI_COMM_WORLD, MPI_Finalize(), MPI_Get_processor_name(), MPI_Init(), MPI_INT, MPI_Recv(), MPI_Send(), MPI_SUCCESS, name, SPI::NotFound, I2C::NotFound, NOTICE, Log::Notice, NULL, O_RDONLY, O_RDWR, O_WRONLY, open(), SerialAddress::port, printf(), printtimediff(), PrivExec(), PS2_IRQ, rank, read(), Reboot, refreshMounts(), DeviceServer::registerDevice(), DeviceServer::registerInterrupt(), TestRunner::run(), Application::run(), ChannelServer< Base, MsgType >::run(), CoreServer::runCore(), search_parallel(), SEEK_SET, BroadcomI2C::setAddress(), LinnCreate::setExclude(), LinnCreate::setImage(), LinnCreate::setInput(), Log::setMinimumLogLevel(), LinnCreate::setProgram(), LinnCreate::setVerbose(), Shutdown, sleep(), snprintf(), LinnSuperBlock::state, strcmp(), strerror(), I2C::Success, SPI::Success, CoreServer::test(), timeString(), total, uarts, usage(), waitMount(), write(), BroadcomI2C::write(), and ZERO.
Referenced by SECTION().
malloc()
C void* malloc (size_t size)
A memory allocator.
The malloc() function shall allocate unused space for an object whose size in bytes is specified by size and whose value is unspecified.
Parameters
size Number of bytes to allocate.
Returns
Upon successful completion with size not equal to 0, malloc() shall return a pointer to the allocated space. If size is 0, either a null pointer or a unique pointer that can be successfully passed to free() shall be returned. Otherwise, it shall return a null pointer [CX] [Option Start] and set errno to indicate the error.
Definition at line 22 of file malloc.cpp.
References errno.
Referenced by collect(), SievePrime::exec(), fopen(), main(), strdup(), strndup(), and timeString().
memcpy()
C void* memcpy (void * dest, const void * src, size_t count)
Copy memory from one place to another.
Parameters
dest Destination address.
src Source address.
count Number of bytes to copy.
Returns
The destination address.
Definition at line 20 of file memcpy.cpp.
References sp.
Referenced by copy(), getcwd(), BootImageStorage::read(), recvfrom(), sendto(), strdup(), strndup(), MountsFile::write(), PseudoFile::write(), and VGA::write().
memset()
C void* memset (void * dest, int ch, size_t count)
Fill memory with a constant byte.
Parameters
dest Memory to write to.
ch Constant byte.
Returns
Pointer to dest.
Definition at line 20 of file memset.cpp.
Referenced by Cat::cat(), chdir(), LinnCreate::create(), ProcessList::exec(), BootImageCreate::exec(), forkexec(), PN532::initialize(), Terminal::initialize(), opendir(), FileSystemPath::parse(), ELF::regions(), setupMappings(), spawn(), teken_subr_tab_clear(), teken_tab_default(), and PseudoFile::write().
mkdir()
C int mkdir (const char * path, mode_t mode)
Create a new directory.
The mkdir() function shall create a new directory with name path. The file permission bits of the new directory shall be initialized from mode. These file permission bits of the mode argument shall be modified by the process' file creation mask.
Parameters
path Full path to the directory to create.
mode Initial access permissions on the directory.
Returns
Upon successful completion, these functions shall return 0. Otherwise, these functions shall return -1 and set errno to indicate the error. If -1 is returned, no directory shall be created.
Definition at line 24 of file mkdir.cpp.
References FileSystemMessage::action, CreateFile, DirectoryFile, ENOENT, errno, ESUCCESS, FileSystemMessage::filetype, findMount(), Singleton< ChannelClient >::instance, FileSystemMessage::mode, FileSystemMessage::path, ChannelMessage::Request, FileSystemMessage::result, ChannelClient::syncSendReceive(), and ChannelMessage::type.
mknod()
C int mknod (const char * path, mode_t mode, dev_t dev)
Make directory, special file, or regular file.
Parameters
path The mknod() function shall create a new file named by the pathname to which the argument path points.
mode The file type for path is OR'ed into the mode argument.
Returns
Upon successful completion, these functions shall return 0. Otherwise, these functions shall return -1 and set errno to indicate the error. If -1 is returned, the new file shall not be created.
Definition at line 26 of file mknod.cpp.
References FileSystemMessage::action, CreateFile, FileSystemMessage::deviceID, ENOENT, errno, ESUCCESS, FILEMODE_BITS, FILEMODE_MASK, FileSystemMessage::filetype, FILETYPE_MASK, findMount(), Singleton< ChannelClient >::instance, FileSystemMessage::mode, FileSystemMessage::path, ChannelMessage::Request, FileSystemMessage::result, ChannelClient::syncSendReceive(), and ChannelMessage::type.
Referenced by MakeNode::exec().
mktime()
C unsigned long mktime (const unsigned int year0, const unsigned int month0, const unsigned int day, const unsigned int hour, const unsigned int min, const unsigned int sec)
Convert given time values to UNIX timestamp (seconds since epoch)
Parameters
year Year value
month Month value
day Day value
hour Hour value (0-23)
min Minute value (0-59)
sec Second value (0-59)
Returns
Converted timestamp in seconds since epoch (UNIX time)
Note
This code is based on the linux source in kernel/time.c
Convert given time values to UNIX timestamp (seconds since epoch)
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition at line 20 of file time.cpp.
Referenced by Time::read().
open()
C int open (const char * path, int oflag, ...)
Open file relative to directory file descriptor.
Parameters
path The path argument points to a pathname naming the file.
oflag Values for oflag are constructed by a bitwise-inclusive OR of flags from the following list, defined in <fcntl.h>.
Returns
Upon successful completion, these functions shall open the file and return a non-negative integer representing the lowest numbered unused file descriptor. Otherwise, these functions shall return -1 and set errno to indicate the error. If - is returned, no files shall be created or modified.
Definition at line 26 of file open.cpp.
References FileSystemMessage::action, ENFILE, ENOENT, errno, ESUCCESS, FILE_DESCRIPTOR_MAX, files, findMount(), getcwd(), getFiles(), FileDescriptor::identifier, Singleton< ChannelClient >::instance, FileDescriptor::mount, NULL, open(), FileDescriptor::open, FileSystemMessage::path, PATH_MAX, FileDescriptor::position, refreshMounts(), ChannelMessage::Request, FileSystemMessage::result, snprintf(), FileSystemMessage::stat, StatFile, strlcpy(), ChannelClient::syncSendReceive(), and ChannelMessage::type.
Referenced by NetSend::arpRequest(), USBDevice::beginTransfer(), Cat::cat(), close(), NetworkClient::createSocket(), Login::exec(), StdioCommand::execute(), WriteCommand::execute(), FileStorage::FileStorage(), fopen(), forkexec(), USBDevice::initialize(), Terminal::initialize(), LinnCreate::insertFile(), CoreServer::loadKernel(), lseek(), main(), FileSystem::mount(), MPI_Init(), open(), opendir(), read(), NetReceive::receivePacket(), NetCtl::showDevice(), and write().
opendir()
C DIR* opendir (const char * dirname)
Open directory associated with file descriptor.
Parameters
dirname The opendir() function shall open a directory stream corresponding to the directory named by the dirname argument.
Returns
Upon successful completion, these functions shall return a pointer to an object of type DIR. Otherwise, these functions shall return a null pointer and set errno to indicate the error.
Definition at line 27 of file opendir.cpp.
References DIR::buffer, closedir(), DIR::count, DIR::current, dirent::d_type, DIRLEN, DT_BLK, DT_CHR, DT_DIR, DT_FIFO, DT_LNK, DT_REG, DT_SOCK, DIR::eof, errno, ESUCCESS, DIR::fd, memset(), Dirent::name, open(), read(), stat(), strlcpy(), and ZERO.
Referenced by LinnCreate::insertDirectory(), ListFiles::printFiles(), and DirectoryScanner::scan().
printf()
C int printf (const char * format, ...)
Output a formatted string to standard output.
Parameters
format Formatted string.
... Argument list.
Returns
Number of bytes written or error code on failure.
Definition at line 22 of file printf.cpp.
References va_end, va_start, and vprintf().
Referenced by NetPing::arpPing(), NetSend::arpRequest(), Cat::cat(), LinnCreate::createInode(), BenchMark::exec(), Echo::exec(), Mount::exec(), SysInfo::exec(), UnixName::exec(), Hostname::exec(), Shell::exec(), TimeCommand::execute(), HelpCommand::execute(), Shell::getInput(), Login::getUsername(), NetPing::icmpPing(), Terminal::initialize(), LinnCreate::insertDirectory(), LinnCreate::insertEntry(), LinnCreate::insertFile(), main(), MPI_Init(), POSIXApplication::output(), BootImageCreate::output(), NetCat::printLine(), Login::printPrompt(), FileStatus::printStatus(), printtimediff(), Shell::prompt(), BootImageCreate::readBootSymbols(), NetCat::readLine(), NetReceive::receiveArp(), NetReceive::receivePacket(), StdoutReporter::reportAfter(), TAPReporter::reportAfter(), StdoutReporter::reportBefore(), TAPReporter::reportBegin(), StdoutReporter::reportFinish(), TAPReporter::reportFinish(), DirectoryScanner::scan(), search_parallel(), NetCtl::showDevice(), usage(), and LinnCreate::writeImage().
printtimediff()
C int printtimediff (struct timeval * t1, struct timeval * t2)
Print time difference.
Parameters
t1 First timeval struct.
t2 Second timeval struct.
Returns
Zero on success or -1 on failure.
Definition at line 24 of file printtimediff.cpp.
References printf(), timeval::tv_sec, and timeval::tv_usec.
Referenced by TimeCommand::execute(), main(), and search_parallel().
random()
C long int random (void)
Random number generator.
Returns
Successive pseudo-random numbers in the range from 0 to RAND_MAX.
Definition at line 27 of file random.cpp.
References seed.
Referenced by UDPSocket::write().
read()
C ssize_t read (int fildes, void * buf, size_t nbyte)
Read from a file.
Parameters
fildes The read() function shall attempt to read nbyte bytes from the file associated with the open file descriptor, fildes, into the buffer pointed to by buf.
buf The read() function shall attempt to read nbyte bytes from the file associated with the open file descriptor, fildes, into the buffer pointed to by buf.
nbyte If the value of nbyte is greater than {SSIZE_MAX}, the result is implementation-defined.
Returns
Upon successful completion, these functions shall return a non-negative integer indicating the number of bytes actually read. Otherwise, the functions shall return -1 and set errno to indicate the error.
Definition at line 24 of file read.cpp.
References FileSystemMessage::action, FileSystemMessage::buffer, FileSystemMessage::deviceID, ENOENT, ERANGE, errno, FILE_DESCRIPTOR_MAX, files, FileSystemMessage::from, getFiles(), FileDescriptor::identifier, Singleton< ChannelClient >::instance, DeviceID::minor, FileSystemMessage::offset, open(), FileDescriptor::path, FileSystemMessage::path, FileDescriptor::position, ReadFile, ChannelMessage::Request, FileSystemMessage::result, SELF, FileSystemMessage::size, ChannelClient::syncSendReceive(), and ChannelMessage::type.
Referenced by NetPing::arpPing(), Cat::cat(), forkexec(), fread(), Shell::getInput(), Login::getUsername(), NetPing::icmpPing(), LinnCreate::insertFile(), CoreServer::loadKernel(), main(), MPI_Init(), opendir(), NetCat::readLine(), NetReceive::receivePacket(), recvfrom(), NetCtl::showDevice(), and NetworkClient::writeSocketInfo().
readdir()
C struct dirent* readdir (DIR * dirp)
Read a directory.
Parameters
dirp The readdir() function shall return a pointer to a structure representing the directory entry at the current position in the directory stream specified by the argument dirp, and position the directory stream at the next entry.
Returns
Upon successful completion, readdir() shall return a pointer to an object of type struct dirent. When an error is encountered, a null pointer shall be returned and errno shall be set to indicate the error. When the end of the directory is encountered, a null pointer shall be returned and errno is not changed.
Definition at line 21 of file readdir.cpp.
References DIR::buffer, DIR::count, DIR::current, and ZERO.
Referenced by LinnCreate::insertDirectory(), ListFiles::printFiles(), and DirectoryScanner::scan().
recvfrom()
C int recvfrom (int sockfd, void * buf, size_t len, int flags, struct sockaddr * addr, socklen_t addrlen)
Definition at line 25 of file recvfrom.cpp.
References sockaddr::addr, NetworkClient::SocketInfo::address, ERANGE, memcpy(), NetworkClient::SocketInfo::port, sockaddr::port, and read().
Referenced by NetCat::udpReceive().
refreshMounts()
void refreshMounts (const char * path)
Refresh mounted filesystems.
Parameters
path Input path to refresh or NULL to refresh all mountpoints
Definition at line 207 of file Runtime.cpp.
References FileSystemMessage::action, FileSystemMessage::buffer, FILESYSTEM_MAXMOUNTS, FileSystemMessage::from, getpid(), Singleton< ChannelClient >::instance, FileSystemMessage::offset, FileSystemMessage::path, ReadFile, ChannelMessage::Request, ROOTFS_PID, SELF, MemoryBlock::set(), FileSystemMessage::size, ChannelClient::syncSendReceive(), SYSFS_PID, and ChannelMessage::type.
Referenced by Cat::cat(), MakeNode::exec(), Mount::exec(), FileStatus::exec(), CreateFile::exec(), ListFiles::exec(), Remove::exec(), Shell::exec(), NetCtl::exec(), ChangeDirCommand::execute(), NetworkClient::initialize(), main(), and open().
sendto()
C int sendto (int sockfd, const void * buf, size_t len, int flags, const struct sockaddr * addr, socklen_t addrlen)
Definition at line 25 of file sendto.cpp.
References sockaddr::addr, NetworkClient::SocketInfo::address, ERANGE, memcpy(), NetworkClient::SocketInfo::port, sockaddr::port, and write().
Referenced by NetCat::udpSend().
shutdown()
C int shutdown (int sockfd, int how)
sleep()
C unsigned int sleep (unsigned int seconds)
Sleep for the specified number of seconds.
Parameters
seconds Number of seconds to sleep
Returns
Zero on success or number of seconds left when interrupted.
Definition at line 23 of file sleep.cpp.
References EAGAIN, EIO, errno, InfoTimer, ProcessCtl(), SELF, API::Success, and WaitTimer.
Referenced by Sleep::exec(), SynopsisController::initialize(), main(), USBHub::portAttach(), LCDBar::setText(), and SynopsisController::softReset().
snprintf()
C int snprintf (char * buffer, unsigned int size, const char * fmt, ...)
Write a formatted string into a buffer.
Parameters
buffer String buffer to write to.
size Maximum number of bytes to write.
fmt Formatted string.
... Argument list.
Returns
Number of bytes written to the buffer.
Definition at line 22 of file snprintf.cpp.
References va_end, va_start, and vsnprintf().
Referenced by chdir(), creat(), ProcessList::exec(), TimeCommand::execute(), Shell::executeInput(), findMount(), LinnCreate::insertDirectory(), main(), MPI_Init(), open(), ListFiles::printFiles(), AnalogPort::read(), Time::read(), BootImageCreate::readBootSymbols(), DirectoryScanner::scan(), stat(), teken_subr_do_cpr(), and unlink().
socket()
C int socket (int domain, int type, int protocol)
Create socket endpoint for communication.
Parameters
domain Communication domain
spawn()
C int spawn (Address program, Size programSize, const char * command)
Create a new process using in-memory image.
Parameters
program In-memory executable to run
programSize number of bytes of the executable
command Command line to pass to the program
Returns
New process ID on success and -1 on failure.
Note
Errno is set with the appropriate error code on failure.
Definition at line 26 of file spawn.cpp.
References Memory::Range::access, ANY, ARGV_SIZE, ExecutableFormat::Region::data, EFAULT, EIO, ENOEXEC, ExecutableFormat::entry(), errno, Memory::Executable, ExecutableFormat::find(), KillPID, Map, memset(), PAGESIZE, Memory::Range::phys, ProcessCtl(), MemoryMap::range(), Memory::Readable, ExecutableFormat::regions(), Resume, ExecutableFormat::Region::size, Memory::Range::size, Spawn, strlcpy(), ExecutableFormat::Success, Memory::User, MemoryMap::UserArgs, Memory::Range::virt, ExecutableFormat::Region::virt, VMCopy(), VMCtl(), Memory::Writable, API::Write, and ZERO.
Referenced by CoreServer::createProcess().
sqrt()
C u32 sqrt (u32 number)
Compute the square root of a number.
Parameters
number The number to use for square root.
Returns
Square root of the given number.
Definition at line 20 of file sqrt.cpp.
Referenced by collect(), SievePrime::exec(), and search_parallel().
srandom()
C void srandom (unsigned int seed)
Random number generator.
The srandom() function sets its argument as the seed for a new sequence of pseudo-random integers to be returned by random(). These sequences are repeatable by calling srandom() with the same seed value. If no seed value is provided, the random() function is automatically seeded with a value of 1.
Parameters
seed Initial seed value for the randomizer
Definition at line 22 of file random.cpp.
References seed.
Referenced by TestData< T >::seed(), and setupRandomizer().
stat()
C int stat (const char * path, struct stat * buf)
Get file status.
Parameters
path The path argument points to a pathname naming a file. Read, write, or execute permission of the named file is not required. An implementation that provides additional or alternate file access control mechanisms may, under implementation-defined conditions, cause stat() to fail. In particular, the system may deny the existence of the file specified by path.
buf The buf argument is a pointer to a stat structure, as defined in the <sys/stat.h> header, into which information is placed concerning the file.
Returns
Upon successful completion, these functions shall return 0. Otherwise, these functions shall return -1 and set errno to indicate the error.
Definition at line 26 of file stat.cpp.
References FileSystemMessage::action, DEBUG, ENOENT, errno, ESUCCESS, findMount(), getcwd(), Singleton< ChannelClient >::instance, FileSystemMessage::path, PATH_MAX, ChannelMessage::Request, FileSystemMessage::result, snprintf(), FileSystemMessage::stat, StatFile, strlcpy(), ChannelClient::syncSendReceive(), and ChannelMessage::type.
Referenced by Cat::cat(), chdir(), BenchMark::exec(), Shell::exec(), FileStorage::FileStorage(), forkexec(), LinnCreate::insertDirectory(), CoreServer::loadKernel(), MPI_Init(), opendir(), ListFiles::printFiles(), ListFiles::printSingleFile(), FileStatus::printStatus(), and BootImageCreate::readBootSymbols().
strcasecmp()
C int strcasecmp (const char * dest, const char * src)
Compare two strings, ignoring case considerations.
Parameters
dest Destination string to compare.
src Source string to compare.
Returns
Zero if equal, non-zero if not.
Definition at line 21 of file strcasecmp.cpp.
References tolower.
strcat()
C char* strcat (char * dest, const char * src)
Concatenate two strings.
The strcat() function shall append a copy of the string pointed to by s2 (including the terminating NUL character) to the end of the string pointed to by s1.
Parameters
dest Destination string.
src Source string.
Returns
The strcat() function shall return s1; no return value is reserved to indicate an error.
Definition at line 20 of file strcat.cpp.
References strcpy().
Referenced by chdir(), MPI_Init(), and FileSystemPath::parse().
strchr()
C char* strchr (const char * s, int c)
String scanning operation.
The strchr() function shall locate the first occurrence of c (converted to a char) in the string pointed to by s. The terminating NULL character is considered to be part of the string.
Parameters
s String to search in.
c Character to look for.
Returns
Upon completion, strchr() shall return a pointer to the byte, or a null pointer if the byte was not found.
Definition at line 20 of file strchr.cpp.
References NULL.
strcmp()
C int strcmp (const char * dest, const char * src)
Compare two strings.
Parameters
dest Destination string to compare.
src Source string to compare.
Returns
Zero if equal, non-zero if not.
Definition at line 20 of file strcmp.cpp.
Referenced by Directory::get(), LinnDirectory::getLinnDirectoryEntry(), BootImageStorage::load(), main(), MPI_Init(), FileDescriptor::operator!=(), Dirent::operator==(), FileDescriptor::operator==(), NetCat::readLine(), Directory::remove(), TestRunner::TestRunner(), and MountWaitFile::write().
strcpy()
C int strcpy (char * dest, const char * src)
Copy a string.
Parameters
dest Destination buffer.
src Source string.
Returns
Number of bytes copied.
Definition at line 20 of file strcpy.cpp.
Referenced by chdir(), strcat(), and teken_subr_do_cpr().
strdup()
C char* strdup (const char * str)
Duplicate a string.
Parameters
str String to duplicate
Returns
Duplicated string or NULL if not enough memory is available.
Definition at line 37 of file strdup.cpp.
References copy(), malloc(), memcpy(), NULL, and strlen().
Referenced by timeString().
strerror()
C char* strerror (int errnum)
The strerror function maps the number in errnum to a message string.
Parameters
errnum Error number to convert.
Returns
The strerror function returns a pointer to the string, the contents of which are locale specific. The array pointed to shall not be modified by the program, but may be overwritten by a subsequent call to the strerror function.
Definition at line 20 of file strerror.cpp.
References ELAST, and error_map.
Referenced by NetPing::arpPing(), NetSend::arpRequest(), Cat::cat(), CreateFile::createFile(), MakeNode::exec(), Sleep::exec(), Init::exec(), Login::exec(), UnixName::exec(), SievePrime::exec(), Remove::exec(), Shell::exec(), BootImageCreate::exec(), ChangeDirCommand::execute(), TimeCommand::execute(), WriteCommand::execute(), Shell::executeInput(), LinnFileSystem::getInode(), USBDevice::initialize(), Terminal::initialize(), LinnCreate::insertDirectory(), LinnCreate::insertFile(), LinnFileSystem::LinnFileSystem(), main(), FileSystem::mount(), MPI_Init(), USBHub::portAttach(), ListFiles::printFiles(), ListFiles::printSingleFile(), FileStatus::printStatus(), BootImageCreate::readBootSymbols(), NetReceive::receivePacket(), DirectoryScanner::scan(), USBDevice::submit(), NetCat::udpReceive(), NetCat::udpSend(), and LinnCreate::writeImage().
strlcpy()
C size_t strlcpy (char * dst, const char * src, size_t siz)
Copy src to string dst of size siz.
At most siz-1 characters will be copied. Always NUL terminates (unless siz == 0).
Parameters
dst Destination string
src Source string
siz size_t of dst buffer
Returns
strlen(src); if retval >= siz, truncation occurred.
Note
This function is copied from OpenBSD-4.3
Definition at line 19 of file strlcpy.cpp.
Referenced by creat(), dirname(), CoreServer::discover(), FileDescriptor::FileDescriptor(), findMount(), forkexec(), gethostname(), Directory::insert(), FileSystem::mount(), MPI_Init(), open(), opendir(), PseudoFile::PseudoFile(), LinnDirectory::read(), setupMappings(), spawn(), stat(), uname(), and unlink().
strlen()
C size_t strlen (const char * str)
Calculate the length of a string.
Parameters
str String to calculate length for.
Returns
Length of the string.
Definition at line 21 of file strlen.cpp.
Referenced by IPCTest::exec(), Login::exec(), Shell::executeInput(), findMount(), Terminal::initialize(), FileSystemPath::parse(), FileSystem::processRequest(), PseudoFile::PseudoFile(), BootImageCreate::readBootSymbols(), Shell::runInteractive(), strdup(), strndup(), waitMount(), and StdioLog::write().
strncasecmp()
C int strncasecmp (const char * dest, const char * src, size_t count)
Compare two strings, ignoring case considerations.
Parameters
dest Destination string to compare.
src Source string to compare.
count Maximum number of bytes to compare.
Returns
Zero if equal, non-zero if not.
Definition at line 21 of file strncasecmp.cpp.
References tolower.
strncat()
C char* strncat (char * dest, const char * src, size_t siz)
Concatenate a string with part of another.
The strncat() function shall append not more than n bytes (a NUL character and bytes that follow it are not appended) from the array pointed to by s2 to the end of the string pointed to by s1. The initial byte of s2 overwrites the NUL character at the end of s1. A terminating NUL character is always appended to the result. If copying takes place between objects that overlap, the behavior is undefined.
Parameters
dest Destination string.
src Source string.
n Number of character to concatenate.
Returns
The strncat() function shall return s1; no return value shall be reserved to indicate an error.
Definition at line 20 of file strncat.cpp.
References strncpy().
Referenced by FileSystemPath::parse().
strncmp()
C int strncmp (const char * dest, const char * src, size_t count)
Compare two strings, by only a maximum number of bytes.
Parameters
dest Destination string to compare.
src Source string to compare.
count Maximum number of bytes to compare.
Returns
Zero if equal, non-zero if not.
Definition at line 20 of file strncmp.cpp.
Referenced by IPCTest::exec(), NetCtl::exec(), findMount(), NetworkClient::initialize(), and MPI_Init().
strncpy()
C int strncpy (char * dest, const char * src, size_t sz)
Copy a string, given a maximum number of bytes.
Parameters
dest Destination buffer.
src Source string.
sz Maximum number of bytes to copy.
Returns
Number of bytes copied.
Definition at line 20 of file strncpy.cpp.
Referenced by BootImageCreate::exec(), LinnCreate::insertEntry(), BootImageCreate::readBootSymbols(), and strncat().
strndup()
C char* strndup (const char * s, size_t size)
Duplicate a specific number of bytes from a string.
The strndup() function shall be equivalent to the strdup() function, duplicating the provided s in a new block of memory allocated as if by using malloc(), with the exception being that strndup() copies at most size plus one bytes into the newly allocated memory, terminating the new string with a NUL character. If the length of s is larger than size, only size bytes shall be duplicated. If size is larger than the length of s, all bytes in s shall be copied into the new memory buffer, including the terminating NUL character. The newly created string shall always be properly terminated.
Parameters
s String to duplicate.
size Maximum number of bytes to copy, excluding the NULL byte.
Returns
Upon successful completion, the strndup() function shall return a pointer to the newly allocated memory containing the duplicated string. Otherwise, it shall return a null pointer and set errno to indicate the error.
Definition at line 22 of file strndup.cpp.
References malloc(), memcpy(), NULL, and strlen().
strrchr()
C char* strrchr (const char * s, int c)
String scanning operation.
The strrchr() function shall locate the last occurrence of c (converted to a char) in the string pointed to by s. The terminating NUL character is considered to be part of the string.
Parameters
s String to search in.
c Character to look for.
Returns
Upon successful completion, strrchr() shall return a pointer to the byte or a null pointer if c does not occur in the string.
Definition at line 20 of file strrchr.cpp.
References NULL.
Referenced by basename(), and dirname().
strtol()
C long strtol (const char * nptr, char ** endptr, int base)
Convert a string to a long integer.
These functions shall convert the initial portion of the string pointed to by str to a type long and long long representation, respectively. First, they decompose the input string into three parts:
Parameters
nptr Input string pointer to convert.
endptr If the subject sequence is empty or does not have the expected form, no conversion is performed; the value of str is stored in the object pointed to by endptr, provided that endptr is not a null pointer.
base Base of the number, e.g. 16 for hexadecimal.
Returns
Upon successful completion, these functions shall return the converted value, if any. If no conversion could be performed, 0 shall be returned and errno may be set to [EINVAL]. If the correct value is outside the range of representable values, {LONG_MIN}, {LONG_MAX}, {LLONG_MIN}, or {LLONG_MAX} shall be returned (according to the sign of the value), and errno set to [ERANGE].
Definition at line 23 of file strtol.cpp.
References Number::Dec, Number::Hex, Character::isDigit(), and String::toLong().
uname()
C int uname (struct utsname * name)
Get the name of the current system.
Parameters
name Used to store information identifying the current system
Returns
Upon successful completion, a non-negative value shall be returned. Otherwise, -1 shall be returned and errno set to indicate the error.
Definition at line 23 of file utsname.cpp.
References gethostname(), utsname::machine, utsname::nodename, utsname::release, strlcpy(), utsname::sysname, UTSBUF, and utsname::version.
Referenced by UnixName::exec(), and Login::printPrompt().
unlink()
C int unlink (const char * path)
Remove a file from the filesystem.
Parameters
path Parh to the file to remove.
Returns
Zero on success or -1 on failure with errno set.
Definition at line 24 of file unlink.cpp.
References FileSystemMessage::action, DeleteFile, ENOENT, errno, ESUCCESS, findMount(), FileSystemMessage::from, getcwd(), Singleton< ChannelClient >::instance, FileSystemMessage::path, PATH_MAX, ChannelMessage::Request, FileSystemMessage::result, SELF, snprintf(), strlcpy(), ChannelClient::syncSendReceive(), and ChannelMessage::type.
Referenced by Remove::exec().
vprintf()
C int vprintf (const char * format, va_list args)
Output a formatted string to standard output, using a variable argument list.
Parameters
format Formatted string.
... Argument list.
Returns
Number of bytes written or error code on failure.
Definition at line 23 of file vprintf.cpp.
References vsnprintf(), and write().
Referenced by __assertFailure(), and printf().
vsnprintf()
C int vsnprintf (char * buffer, unsigned int size, const char * fmt, va_list args)
Write a formatted string into a buffer.
Parameters
buffer String buffer to write to.
size Maximum number of bytes to write.
fmt Formatted string.
args Argument list.
Returns
Number of bytes written to the buffer.
Definition at line 23 of file vsnprintf.cpp.
References atoi(), Number::Dec, Number::Hex, itoa(), length, String::setUnsigned(), va_arg, and ZERO.
Referenced by Directory::insert(), FileSystem::insertFileCache(), PseudoFile::PseudoFile(), FileSystem::registerFile(), snprintf(), and vprintf().
waitMount()
void waitMount (const char * path)
Blocking wait for a mounted filesystem.
Parameters
path Full path of the mounted filesystem
Note
Blocks until a filesystem is mounted on the exact given input path
Definition at line 238 of file Runtime.cpp.
References FileSystemMessage::action, FileSystemMessage::buffer, FileSystemMessage::from, Singleton< ChannelClient >::instance, FileSystemMessage::offset, FileSystemMessage::path, ChannelMessage::Request, SELF, FileSystemMessage::size, strlen(), ChannelClient::syncSendReceive(), SYSFS_PID, ChannelMessage::type, and WriteFile.
Referenced by main().
waitpid()
C pid_t waitpid (pid_t pid, int * stat_loc, int options)
Wait for a child process to stop or terminate.
The wait() and waitpid() functions shall obtain status information pertaining to one of the caller's child processes. Various options permit status information to be obtained for child processes that have terminated or stopped. If status information is available for two or more child processes, the order in which their status is reported is unspecified.
Parameters
pid Process ID of child to wait for.
stat_loc Points to an integer for storing the exit status.
options Optional flags.
Returns
Process ID of the child on success or -1 on error
Definition at line 23 of file waitpid.cpp.
References ProcessCtl(), and WaitPID.
Referenced by CoreServer::createProcess(), Login::exec(), TimeCommand::execute(), Shell::executeInput(), and ExternalTest::run().
write()
C ssize_t write (int fildes, const void * buf, size_t nbyte)
Write on a file.
The write() function shall attempt to write nbyte bytes from the buffer pointed to by buf to the file associated with the open file descriptor, fildes.
Parameters
fildes File descriptor.
buf Input buffer.
nbyte Maximum number of bytes to write.
Returns
Upon successful completion, these functions shall return the number of bytes actually written to the file associated with fildes. This number shall never be greater than nbyte. Otherwise, -1 shall be returned and errno set to indicate the error.
Definition at line 24 of file write.cpp.
References FileSystemMessage::action, FileSystemMessage::buffer, FileSystemMessage::deviceID, ENOENT, ERANGE, errno, FILE_DESCRIPTOR_MAX, files, FileSystemMessage::from, getFiles(), FileDescriptor::identifier, Singleton< ChannelClient >::instance, DeviceID::minor, FileSystemMessage::offset, open(), FileDescriptor::path, FileSystemMessage::path, FileDescriptor::position, ChannelMessage::Request, FileSystemMessage::result, SELF, FileSystemMessage::size, ChannelClient::syncSendReceive(), ChannelMessage::type, and WriteFile.
Referenced by NetPing::arpPing(), NetSend::arpRequest(), SievePrime::exec(), ProcessList::exec(), WriteCommand::execute(), NetPing::icmpPing(), main(), FileSystem::mount(), ListFiles::printFiles(), sendto(), vprintf(), and NetworkClient::writeSocketInfo().
Variable Documentation
errno
C int errno
The lvalue errno is used by many functions to return error values.
Referenced by NetPing::arpPing(), NetSend::arpRequest(), Cat::cat(), chdir(), close(), creat(), CreateFile::createFile(), MakeNode::exec(), Sleep::exec(), Init::exec(), Login::exec(), UnixName::exec(), SievePrime::exec(), Remove::exec(), Shell::exec(), BootImageCreate::exec(), ChangeDirCommand::execute(), TimeCommand::execute(), WriteCommand::execute(), Shell::executeInput(), fclose(), fopen(), forkexec(), getcwd(), gettimeofday(), USBDevice::initialize(), Terminal::initialize(), LinnCreate::insertDirectory(), LinnCreate::insertFile(), lseek(), main(), malloc(), mkdir(), mknod(), FileSystem::mount(), MPI_Init(), open(), opendir(), USBHub::portAttach(), ListFiles::printFiles(), ListFiles::printSingleFile(), FileStatus::printStatus(), FileStorage::read(), read(), BootImageCreate::readBootSymbols(), NetReceive::receivePacket(), DirectoryScanner::scan(), sleep(), spawn(), stat(), USBDevice::submit(), NetCat::udpReceive(), NetCat::udpSend(), unlink(), FileStorage::write(), write(), and LinnCreate::writeImage().
error_map
char * error_map
Contains a array of character strings, representing errno values.
Definition at line 23 of file errno.c.
Referenced by strerror().