FreeNOS: terminal
terminal
server
The terminal server provides the system console via input/output devices.
Data Structures
class Terminal
A Terminal enables user to interact with the system.
Macros
#define BANNER "FreeNOS " RELEASE " [" ARCH "/" SYSTEM "] (" BUILDUSER "@" BUILDHOST ") (" COMPILER_VERSION ") " DATETIME "\r\n"
Print this banner per default on new Terminals.
#define _SGR(x) "\033[" #x "m"
Set Graphic Rendition.
Functions
void bell (Terminal *term)
Makes a sound (bell).
void putchar (Terminal *term, const teken_pos_t *pos, teken_char_t ch, const teken_attr_t *attr)
Output a new character.
void cursor (Terminal *term, const teken_pos_t *pos)
Sets the Terminal cursor.
void fill (Terminal *ctx, const teken_rect_t *rect, teken_char_t ch, const teken_attr_t *attr)
Fills the Terminal buffer with a character.
void copy (Terminal *ctx, const teken_rect_t *rect, const teken_pos_t *pos)
Copy bytes to the terminal.
void param (Terminal *ctx, int key, int value)
Set terminal parameters.
void respond (Terminal *ctx, const void *buf, size_t size)
Unused.
Terminal Colors
See also
http://en.wikipedia.org/wiki/ANSI_escape_code
#define BLACK _SGR(30)
#define RED _SGR(31)
#define GREEN _SGR(32)
#define YELLOW _SGR(33)
#define BLUE _SGR(34)
#define MAGENTA _SGR(35)
#define CYAN _SGR(36)
#define WHITE _SGR(37)
#define RESET _SGR(39)
Detailed Description
The terminal server provides the system console via input/output devices.
Macro Definition Documentation
_SGR
#define _SGR (x) "\033[" #x "m"
Set Graphic Rendition.
Definition at line 30 of file TerminalCodes.h.
BANNER
#define BANNER "FreeNOS " RELEASE " [" ARCH "/" SYSTEM "] (" BUILDUSER "@" BUILDHOST ") (" COMPILER_VERSION ") " DATETIME "\r\n"
Print this banner per default on new Terminals.
Definition at line 38 of file Terminal.h.
Referenced by Terminal::initialize(), and Kernel::Kernel().
BLACK
#define BLACK _SGR(30)
Definition at line 38 of file TerminalCodes.h.
BLUE
#define BLUE _SGR(34)
Definition at line 42 of file TerminalCodes.h.
CYAN
#define CYAN _SGR(36)
Definition at line 44 of file TerminalCodes.h.
GREEN
#define GREEN _SGR(32)
Definition at line 40 of file TerminalCodes.h.
MAGENTA
#define MAGENTA _SGR(35)
Definition at line 43 of file TerminalCodes.h.
RED
#define RED _SGR(31)
Definition at line 39 of file TerminalCodes.h.
RESET
#define RESET _SGR(39)
Definition at line 46 of file TerminalCodes.h.
WHITE
#define WHITE _SGR(37)
Definition at line 45 of file TerminalCodes.h.
YELLOW
#define YELLOW _SGR(33)
Definition at line 41 of file TerminalCodes.h.
Referenced by ListFiles::printSingleFile(), and StdoutReporter::reportAfter().
Function Documentation
bell()
void bell (Terminal * term)
Makes a sound (bell).
Parameters
term Terminal object pointer.
Definition at line 212 of file Terminal.cpp.
Referenced by Terminal::initialize().
copy()
void copy (Terminal * ctx, const teken_rect_t * rect, const teken_pos_t * pos)
Copy bytes to the terminal.
Parameters
ctx Terminal object pointer.
rect Source rectagular area with VGA memory buffer.
pos Position to copy the rect to.
Definition at line 264 of file Terminal.cpp.
References Terminal::buffer, Terminal::getBuffer(), Terminal::getWidth(), Terminal::hideCursor(), memcpy(), Terminal::showCursor(), teken_pos_t::tp_col, teken_pos_t::tp_row, teken_rect_t::tr_begin, teken_rect_t::tr_end, and Terminal::width.
Referenced by Terminal::initialize(), String::split(), strdup(), and String::String().
cursor()
void cursor (Terminal * term, const teken_pos_t * pos)
Sets the Terminal cursor.
Parameters
term Terminal object pointer.
pos Position to put the cursor.
Definition at line 235 of file Terminal.cpp.
References Terminal::hideCursor(), Terminal::setCursor(), and Terminal::showCursor().
Referenced by Terminal::initialize().
fill()
void fill (Terminal * ctx, const teken_rect_t * rect, teken_char_t ch, const teken_attr_t * attr)
Fills the Terminal buffer with a character.
Parameters
term Terminal object pointer.
rect Indicates where to fill.
ch Character to be used for filling.
attr Attributes for this character.
Definition at line 242 of file Terminal.cpp.
References BLACK, Terminal::getBuffer(), Terminal::getWidth(), Terminal::hideCursor(), Terminal::showCursor(), teken_attr_t::ta_fgcolor, tekenToVGA, teken_pos_t::tp_col, teken_pos_t::tp_row, teken_rect_t::tr_begin, and VGA_CHAR.
Referenced by Terminal::initialize().
param()
void param (Terminal * ctx, int key, int value)
Set terminal parameters.
Parameters
ctx Terminal object pointer.
key Option key identifier.
value New value for the option.
Definition at line 287 of file Terminal.cpp.
Referenced by Terminal::initialize(), and PrivExec().
putchar()
void putchar (Terminal * term, const teken_pos_t * pos, teken_char_t ch, const teken_attr_t * attr)
Output a new character.
Parameters
term Terminal object pointer.
pos Terminal position.
ch Character to output.
attr Attributes for this character.
Definition at line 217 of file Terminal.cpp.
References BLACK, Terminal::buffer, Terminal::getBuffer(), Terminal::getWidth(), Terminal::hideCursor(), Terminal::showCursor(), teken_attr_t::ta_fgcolor, tekenToVGA, teken_pos_t::tp_col, teken_pos_t::tp_row, VGA_CHAR, and Terminal::width.
Referenced by Terminal::initialize().
respond()
void respond (Terminal * ctx, const void * buf, size_t size)
Unused.
Definition at line 292 of file Terminal.cpp.
Referenced by Terminal::initialize().