FreeNOS: ARM
ARM
kernel
ARM architecture specific kernel code such as context switching and bootup code.
Namespaces
Arch
Data Structures
class ARMKernel
Represents the ARM kernel implementation.
class ARMProcess
ARM specific process implementation.
class RaspiSerial
BCM2835 specific UART logging implementation for the ARMKernel.
ARM Kernel Traps
ARM specific software interrupts.
These functions are called by the user program to invoke the kernel APIs, also known as system calls.
On ARM, there are no machine-specific input operand constraints to specify registers for inline assembly. Therefore, we need to use Local Register Variables syntax to guarantee that specific registers are used.
See also
https://gcc.gnu.org/onlinedocs/gcc/Local-Register-Variables.html#Local-Register-Variables
ulong trapKernel1 (ulong api, ulong arg1)
Perform a kernel trap with 1 argument.
ulong trapKernel2 (ulong api, ulong arg1, ulong arg2)
Perform a kernel trap with 2 arguments.
ulong trapKernel3 (ulong api, ulong arg1, ulong arg2, ulong arg3)
Perform a kernel trap with 3 arguments.
ulong trapKernel4 (ulong api, ulong arg1, ulong arg2, ulong arg3, ulong arg4)
Perform a kernel trap with 4 arguments.
ulong trapKernel5 (ulong api, ulong arg1, ulong arg2, ulong arg3, ulong arg4, ulong arg5)
Perform a kernel trap with 5 arguments.
Detailed Description
ARM architecture specific kernel code such as context switching and bootup code.
Function Documentation
trapKernel1()
ulong trapKernel1 (ulong api, ulong arg1) inline
Perform a kernel trap with 1 argument.
Parameters
api Unique number of the handler to execute.
Returns
An integer.
Definition at line 66 of file ARMKernel.h.
Referenced by SystemInfo().
trapKernel2()
ulong trapKernel2 (ulong api, ulong arg1, ulong arg2) inline
Perform a kernel trap with 2 arguments.
Parameters
api Unique number of the handler to execute.
arg1 First argument
arg2 Second argument
Returns
An integer
Definition at line 87 of file ARMKernel.h.
Referenced by PrivExec().
trapKernel3()
ulong trapKernel3 (ulong api, ulong arg1, ulong arg2, ulong arg3) inline
Perform a kernel trap with 3 arguments.
Parameters
api Unique number of the handler to execute.
arg1 First argument
arg2 Second argument
arg3 Third argument
Returns
An integer.
Definition at line 110 of file ARMKernel.h.
Referenced by ReadByte(), ReadWord(), VMCtl(), VMShare(), WriteByte(), WriteLong(), and WriteWord().
trapKernel4()
ulong trapKernel4 (ulong api, ulong arg1, ulong arg2, ulong arg3, ulong arg4) inline
Perform a kernel trap with 4 arguments.
Parameters
api Unique number of the handler to execute.
arg1 First argument
arg2 Second argument
arg3 Third argument
arg4 Fourth argument
Returns
An integer.
Definition at line 135 of file ARMKernel.h.
Referenced by ProcessCtl().
trapKernel5()
ulong trapKernel5 (ulong api, ulong arg1, ulong arg2, ulong arg3, ulong arg4, ulong arg5) inline
Perform a kernel trap with 5 arguments.
Parameters
api Unique number of the handler to execute.
arg1 First argument
arg2 Second argument
arg3 Third argument
arg4 Fourth argument
arg5 Fifth argument
Returns
An integer.
Definition at line 163 of file ARMKernel.h.
Referenced by VMCopy().