FreeNOS: API (system call interface)
API (system call interface)
kernel
Application Programming Interface (API) provided by the Kernel for user programs.
Data Structures
struct ProcessInfo
Process information structure, used for Info.
struct SystemInformation
System information structure.
Typedefs
typedef enum IOOperation IOOperation
Available operation to perform using PrivExec().
typedef enum PrivOperation PrivOperation
Available operations to perform using PrivExec().
typedef enum ProcessOperation ProcessOperation
Available operation to perform using ProcessCtl.
typedef struct ProcessInfo ProcessInfo
Process information structure, used for Info.
typedef struct SystemInformation SystemInformation
System information structure.
typedef enum MemoryOperation MemoryOperation
Memory operations which may be used as an argument to VMCtl().
Enumerations
enum IOOperation {
IOByteRead = 0, IOByteWrite = 1, IOWordRead = 2, IOWordWrite = 3,
IOLongWrite = 4
}
Available operation to perform using PrivExec().
enum PrivOperation { Idle = 0, Reboot = 1, Shutdown = 2, WriteConsole = 3 }
Available operations to perform using PrivExec().
enum ProcessOperation {
Spawn = 0, KillPID, GetPID, GetParent,
WatchIRQ, EnableIRQ, DisableIRQ, InfoPID,
WaitPID, InfoTimer, WaitTimer, EnterSleep,
Schedule, Resume, SetStack
}
Available operation to perform using ProcessCtl.
enum MemoryOperation {
Map = 0, UnMap, Release, LookupVirtual,
Access, ReserveMem, AddMem, CacheClean
}
Memory operations which may be used as an argument to VMCtl().
Functions
Log & operator<< (Log &log, IOOperation op)
Operator to print a IOOperation to a Log.
u8 ReadByte (Address addr)
API::Result WriteByte (Address addr, u8 value)
u16 ReadWord (Address addr)
API::Result WriteWord (Address addr, u16 value)
API::Result WriteLong (Address addr, ulong value)
API::Result PrivExec (PrivOperation op, Address param=0)
Prototype for user applications.
Log & operator<< (Log &log, ProcessOperation op)
Operator to print a ProcessOperation to a Log.
API::Result ProcessCtl (ProcessID proc, ProcessOperation op, Address addr=0, Address output=0)
Prototype for user applications.
API::Result SystemInfo (SystemInformation *info)
Prototype for user applications.
API::Result VMCopy (ProcessID proc, API::Operation how, Address ours, Address theirs, Size sz)
Prototype for user applications.
API::Result VMCtl (ProcessID procID, MemoryOperation op, Memory::Range *range=ZERO)
Prototype for user applications.
API::Result VMShare (ProcessID pid, API::Operation op, ProcessShares::MemoryShare *share)
Prototype for user applications.
Static Process IDs
#define ANY 65535
#define SELF 65534
#define KERNEL_PID 65533
#define CORESRV_PID 0
#define SYSFS_PID 1
#define ROOTFS_PID 2
Detailed Description
Application Programming Interface (API) provided by the Kernel for user programs.
Macro Definition Documentation
ANY
#define ANY 65535
Definition at line 34 of file ProcessID.h.
Referenced by forkexec(), and spawn().
CORESRV_PID
#define CORESRV_PID 0
Definition at line 38 of file ProcessID.h.
Referenced by SysInfo::exec(), and MPI_Init().
KERNEL_PID
#define KERNEL_PID 65533
Definition at line 36 of file ProcessID.h.
Referenced by ChannelServer< FileSystem, FileSystemMessage >::ChannelServer(), and Process::initialize().
ROOTFS_PID
#define ROOTFS_PID 2
Definition at line 40 of file ProcessID.h.
Referenced by FileSystem::mount(), refreshMounts(), and setupMappings().
SELF
#define SELF 65534
Definition at line 35 of file ProcessID.h.
Referenced by __assertRead(), __assertWrite(), PageAllocator::allocate(), USBDevice::beginTransfer(), IntelMP::boot(), CoreServer::bootCore(), ChannelServer< FileSystem, FileSystemMessage >::ChannelServer(), CoreServer::clearPages(), USBDevice::controlMessage(), CoreServer::createProcess(), SysInfo::exec(), BenchMark::exec(), exit(), getpid(), getppid(), gettimeofday(), PL011::initialize(), VGA::initialize(), SynopsisController::initialize(), PL011::interrupt(), i8250::interrupt(), SynopsisController::interruptHandler(), BootImageStorage::load(), IO::map(), FileSystem::mount(), MPI_Init(), ProcessCtlHandler(), Keyboard::read(), read(), refreshMounts(), DeviceServer::registerInterrupt(), ChannelServer< FileSystem, FileSystemMessage >::run(), ChannelServer< FileSystem, FileSystemMessage >::setTimeout(), setupHeap(), setupRandomizer(), sleep(), ChannelClient::syncReceiveFrom(), ChannelClient::syncSendTo(), USBDevice::transfer(), SynopsisChannel::transfer(), unlink(), IO::unmap(), VMCopyHandler(), VMCtlHandler(), VMShareHandler(), IntelAPIC::wait(), waitMount(), write(), and SMSC95xxUSB::writeStart().
SYSFS_PID
#define SYSFS_PID 1
Definition at line 39 of file ProcessID.h.
Referenced by FileSystem::mount(), refreshMounts(), setupMappings(), and waitMount().
Typedef Documentation
IOOperation
typedef enum IOOperation IOOperation
Available operation to perform using PrivExec().
See also
PrivExec
MemoryOperation
typedef enum MemoryOperation MemoryOperation
Memory operations which may be used as an argument to VMCtl().
PrivOperation
typedef enum PrivOperation PrivOperation
Available operations to perform using PrivExec().
See also
PrivExec
ProcessInfo
typedef struct ProcessInfo ProcessInfo
Process information structure, used for Info.
ProcessOperation
typedef enum ProcessOperation ProcessOperation
Available operation to perform using ProcessCtl.
See also
ProcessCtl
SystemInformation
typedef struct SystemInformation SystemInformation
System information structure.
Enumeration Type Documentation
IOOperation
enum IOOperation
Available operation to perform using PrivExec().
See also
PrivExec
Enumerator
IOByteRead
IOByteWrite
IOWordRead
IOWordWrite
IOLongWrite
Definition at line 38 of file IOCtl.h.
MemoryOperation
enum MemoryOperation
Memory operations which may be used as an argument to VMCtl().
Enumerator
Map
UnMap
Release
LookupVirtual
Access
ReserveMem
AddMem
CacheClean
Definition at line 34 of file VMCtl.h.
PrivOperation
enum PrivOperation
Available operations to perform using PrivExec().
See also
PrivExec
Enumerator
Idle
Reboot
Shutdown
WriteConsole
Definition at line 36 of file PrivExec.h.
ProcessOperation
enum ProcessOperation
Available operation to perform using ProcessCtl.
See also
ProcessCtl
Enumerator
Spawn
KillPID
GetPID
GetParent
WatchIRQ
EnableIRQ
DisableIRQ
InfoPID
WaitPID
InfoTimer
WaitTimer
EnterSleep
Schedule
Resume
SetStack
Definition at line 38 of file ProcessCtl.h.
Function Documentation
operator<<() [1/2]
Log& operator<< (Log & log, IOOperation op)
Operator to print a IOOperation to a Log.
Definition at line 50 of file IOCtl.cpp.
References Log::append(), IOByteRead, IOByteWrite, IOLongWrite, IOWordRead, and IOWordWrite.
operator<<() [2/2]
Log& operator<< (Log & log, ProcessOperation op)
Operator to print a ProcessOperation to a Log.
Definition at line 139 of file ProcessCtl.cpp.
References Log::append(), DisableIRQ, EnableIRQ, EnterSleep, GetParent, GetPID, InfoPID, InfoTimer, KillPID, Resume, Schedule, SetStack, Spawn, WaitPID, and WatchIRQ.
PrivExec()
API::Result PrivExec (PrivOperation op, Address param = 0) inline
Prototype for user applications.
Performs various privileged operations.
Parameters
op The operation to perform.
Returns
API::Success on success and other API::ErrorCode on failure.
Definition at line 52 of file PrivExec.h.
References param(), PrivExecHandler(), API::PrivExecNumber, and trapKernel2().
Referenced by main(), and KernelLog::write().
ProcessCtl()
API::Result ProcessCtl (ProcessID proc, ProcessOperation op, Address addr = 0, Address output = 0) inline
Prototype for user applications.
Process management related operations.
Parameters
proc Target Process' ID.
op The operation to perform.
addr Input argument address, used for program entry point for Spawn, ProcessInfo pointer for Info.
output Output argument address (optional).
Returns
API::Success on success and other API::ErrorCode on failure.
Definition at line 97 of file ProcessCtl.h.
References ProcessCtlHandler(), API::ProcessCtlNumber, and trapKernel4().
Referenced by ChannelServer< FileSystem, FileSystemMessage >::ChannelServer(), IPCTest::exec(), SysInfo::exec(), BenchMark::exec(), ProcessList::exec(), exit(), forkexec(), getpid(), getppid(), gettimeofday(), PL011::initialize(), SynopsisController::initialize(), PL011::interrupt(), i8250::interrupt(), SynopsisController::interruptHandler(), FileSystem::mount(), FileSystem::processRequest(), Keyboard::read(), ChannelServer< FileSystem, FileSystemMessage >::readChannels(), DeviceServer::registerInterrupt(), ChannelServer< FileSystem, FileSystemMessage >::run(), ChannelClient::sendRequest(), FileSystem::sendResponse(), ChannelServer< FileSystem, FileSystemMessage >::setTimeout(), setupRandomizer(), sleep(), spawn(), ChannelClient::syncReceiveFrom(), ChannelClient::syncSendTo(), IntelAPIC::wait(), and waitpid().
ReadByte()
u8 ReadByte (Address addr) inline
Definition at line 51 of file IOCtl.h.
References IOByteRead, API::IOCtlNumber, and trapKernel3().
Referenced by i8250::initialize(), ATAController::initialize(), ATAController::pollReady(), Keyboard::read(), i8250::read(), Time::readCMOS(), and i8250::write().
ReadWord()
u16 ReadWord (Address addr) inline
Definition at line 61 of file IOCtl.h.
References API::IOCtlNumber, IOWordRead, and trapKernel3().
Referenced by ATAController::initialize(), and ATAController::read().
SystemInfo()
API::Result SystemInfo (SystemInformation * info) inline
Prototype for user applications.
Retrieves system information.
Parameters
info Pointer to SystemInformation output buffer.
Returns
API::Success on success and other API::ErrorCode on failure.
Definition at line 42 of file SystemInfo.h.
References SystemInfoHandler(), API::SystemInfoNumber, and trapKernel1().
Referenced by SystemInformation::SystemInformation().
VMCopy()
API::Result VMCopy (ProcessID proc, API::Operation how, Address ours, Address theirs, Size sz) inline
Prototype for user applications.
Copies virtual memory between two processes.
Parameters
proc Remote process.
how Read or Write.
ours Virtual address of the buffer of this process.
theirs Virtual address of the remote process' buffer.
sz Amount of memory to copy.
Returns
Total number of bytes copied on success and API::ErrorCode on failure.
Definition at line 42 of file VMCopy.h.
References trapKernel5(), VMCopyHandler(), and API::VMCopyNumber.
Referenced by IntelMP::boot(), CoreServer::bootCore(), CoreServer::createProcess(), Mount::exec(), IPCTest::exec(), ProcessList::exec(), forkexec(), FileSystem::processRequest(), IOBuffer::read(), spawn(), File::status(), and IOBuffer::write().
VMCtl()
API::Result VMCtl (ProcessID procID, MemoryOperation op, Memory::Range * range = ZERO) inline
Prototype for user applications.
Examines and modifies virtual memory pages.
Parameters
procID Remote process.
op Determines which operation to perform.
range Describes the memory pages to operate on.
Returns
API::Success on success and other API::ErrorCode on failure.
Definition at line 56 of file VMCtl.h.
References trapKernel3(), VMCtlHandler(), and API::VMCtlNumber.
Referenced by __assertRead(), __assertWrite(), PageAllocator::allocate(), USBDevice::beginTransfer(), CoreServer::bootCore(), CoreServer::clearPages(), USBDevice::controlMessage(), CoreServer::createProcess(), BenchMark::exec(), forkexec(), VGA::initialize(), BootImageStorage::load(), IO::map(), MPI_Init(), setupHeap(), spawn(), USBDevice::transfer(), SynopsisChannel::transfer(), IO::unmap(), and SMSC95xxUSB::writeStart().
VMShare()
API::Result VMShare (ProcessID pid, API::Operation op, ProcessShares::MemoryShare * share) inline
Prototype for user applications.
Creates and removes shared virtual memory mappings.
Parameters
op Determines which operation to perform.
pid Remote process.
parameter Parameter for the operation.
size Size parameter for the operation.
Returns
API::Success on success and other API::ErrorCode on failure.
Definition at line 41 of file VMShare.h.
References trapKernel3(), VMShareHandler(), and API::VMShareNumber.
Referenced by ChannelServer< FileSystem, FileSystemMessage >::ChannelServer(), ChannelClient::connect(), and ChannelServer< FileSystem, FileSystemMessage >::readKernelEvents().
WriteByte()
API::Result WriteByte (Address addr, u8 value) inline
Definition at line 56 of file IOCtl.h.
References IOByteWrite, API::IOCtlNumber, and trapKernel3().
Referenced by i8250::initialize(), VGA::initialize(), ATAController::initialize(), ATAController::read(), Time::readCMOS(), and i8250::write().
WriteLong()
API::Result WriteLong (Address addr, ulong value) inline
Definition at line 71 of file IOCtl.h.
References IOCtlHandler(), API::IOCtlNumber, IOLongWrite, and trapKernel3().
WriteWord()
API::Result WriteWord (Address addr, u16 value) inline
Definition at line 66 of file IOCtl.h.
References API::IOCtlNumber, IOWordWrite, and trapKernel3().