FreeNOS: libmpi
libmpi
lib
MPI (Message Passing Interface) is a standard communication interface for parallel programming.
Data Structures
struct MPIMessage
Typedefs
typedef struct MPIMessage MPIMessage
enum MPI_Datatype {
MPI_CHAR, MPI_SHORT, MPI_LONG, MPI_INT,
MPI_UNSIGNED_CHAR, MPI_UNSIGNED_SHORT, MPI_UNSIGNED, MPI_UNSIGNED_LONG
}
Named Predefined Datatypes.
enum { MPI_COMM_WORLD, MPI_COMM_SELF }
Reserved communicators.
enum {
MPI_SUCCESS, MPI_ERR_BUFFER, MPI_ERR_COUNT, MPI_ERR_TYPE,
MPI_ERR_TAG, MPI_ERR_COMM, MPI_ERR_RANK, MPI_ERR_REQUEST,
MPI_ERR_ROOT, MPI_ERR_GROUP, MPI_ERR_OP, MPI_ERR_TOPOLOGY,
MPI_ERR_DIMS, MPI_ERR_ARG, MPI_ERR_UNKNOWN, MPI_ERR_TRUNCATE,
MPI_ERR_OTHER, MPI_ERR_INTERN, MPI_ERR_PENDING, MPI_ERR_IN_STATUS,
MPI_ERR_ACCESS, MPI_ERR_AMODE, MPI_ERR_ASSERT, MPI_ERR_BAD_FILE,
MPI_ERR_BASE, MPI_ERR_CONVERSION, MPI_ERR_DISP, MPI_ERR_DUP_DATAREP,
MPI_ERR_FILE_EXISTS, MPI_ERR_FILE_IN_USE, MPI_ERR_FILE, MPI_ERR_INFO_KEY,
MPI_ERR_INFO_NOKEY, MPI_ERR_INFO_VALUE, MPI_ERR_INFO, MPI_ERR_IO,
MPI_ERR_KEYVAL, MPI_ERR_LOCKTYPE, MPI_ERR_NAME, MPI_ERR_NO_MEM,
MPI_ERR_NOT_SAME, MPI_ERR_NO_SPACE, MPI_ERR_NO_SUCH_FILE, MPI_ERR_PORT,
MPI_ERR_QUOTA, MPI_ERR_READ_ONLY, MPI_ERR_RMA_ATTACH, MPI_ERR_RMA_CONFLICT,
MPI_ERR_RMA_RANGE, MPI_ERR_RMA_SHARED, MPI_ERR_RMA_SYNC, MPI_ERR_RMA_FLAVOR,
MPI_ERR_SERVICE, MPI_ERR_SIZE, MPI_ERR_SPAWN, MPI_ERR_UNSUPPORTED_DATAREP,
MPI_ERR_UNSUPPORTED_OPERATION, MPI_ERR_WIN, MPI_T_ERR_CANNOT_INIT, MPI_T_ERR_NOT_INITIALIZED,
MPI_T_ERR_MEMORY, MPI_T_ERR_INVALID, MPI_T_ERR_INVALID_INDEX, MPI_T_ERR_INVALID_ITEM,
MPI_T_ERR_INVALID_SESSION, MPI_T_ERR_INVALID_HANDLE, MPI_T_ERR_INVALID_NAME, MPI_T_ERR_OUT_OF_HANDLES,
MPI_T_ERR_OUT_OF_SESSIONS, MPI_T_ERR_CVAR_SET_NOT_NOW, MPI_T_ERR_CVAR_SET_NEVER, MPI_T_ERR_PVAR_NO_WRITE,
MPI_T_ERR_PVAR_NO_STARTSTOP, MPI_T_ERR_PVAR_NO_ATOMIC, MPI_ERR_LASTCODE
}
MPI Error Codes.
typedef uint MPI_Comm
Defined Constants.
typedef uint MPI_Status
Status holder.
C int MPI_Send (const void *buf, int count, MPI_Datatype datatype, int dest, int tag, MPI_Comm comm)
Point-to-Point Communication.
C int MPI_Recv (void *buf, int count, MPI_Datatype datatype, int source, int tag, MPI_Comm comm, MPI_Status *status)
C int MPI_Comm_rank (MPI_Comm comm, int *rank)
Communicator Contexts.
C int MPI_Comm_size (MPI_Comm comm, int *size)
C int MPI_Init (int *argc, char ***argv)
Environmental Management.
C int MPI_Finalize (void)
C int MPI_Get_processor_name (char *name, int *resultlen)
C int MPI_Get_version (int *version, int *subversion)
C int MPI_Get_library_version (char *version, int *resultlen)
Detailed Description
MPI (Message Passing Interface) is a standard communication interface for parallel programming.
Typedef Documentation
MPI_Comm
typedef uint MPI_Comm
Defined Constants.
Communicator identifier
Definition at line 38 of file mpi.h.
MPI_Status
typedef uint MPI_Status
Status holder.
Definition at line 41 of file mpi.h.
MPIMessage
typedef struct MPIMessage MPIMessage
Enumeration Type Documentation
anonymous enum
anonymous enum
Reserved communicators.
Enumerator
MPI_COMM_WORLD
MPI_COMM_SELF
Definition at line 62 of file mpi.h.
anonymous enum
anonymous enum
MPI Error Codes.
Enumerator
MPI_SUCCESS
MPI_ERR_BUFFER
MPI_ERR_COUNT
MPI_ERR_TYPE
MPI_ERR_TAG
MPI_ERR_COMM
MPI_ERR_RANK
MPI_ERR_REQUEST
MPI_ERR_ROOT
MPI_ERR_GROUP
MPI_ERR_OP
MPI_ERR_TOPOLOGY
MPI_ERR_DIMS
MPI_ERR_ARG
MPI_ERR_UNKNOWN
MPI_ERR_TRUNCATE
MPI_ERR_OTHER
MPI_ERR_INTERN
MPI_ERR_PENDING
MPI_ERR_IN_STATUS
MPI_ERR_ACCESS
MPI_ERR_AMODE
MPI_ERR_ASSERT
MPI_ERR_BAD_FILE
MPI_ERR_BASE
MPI_ERR_CONVERSION
MPI_ERR_DISP
MPI_ERR_DUP_DATAREP
MPI_ERR_FILE_EXISTS
MPI_ERR_FILE_IN_USE
MPI_ERR_FILE
MPI_ERR_INFO_KEY
MPI_ERR_INFO_NOKEY
MPI_ERR_INFO_VALUE
MPI_ERR_INFO
MPI_ERR_IO
MPI_ERR_KEYVAL
MPI_ERR_LOCKTYPE
MPI_ERR_NAME
MPI_ERR_NO_MEM
MPI_ERR_NOT_SAME
MPI_ERR_NO_SPACE
MPI_ERR_NO_SUCH_FILE
MPI_ERR_PORT
MPI_ERR_QUOTA
MPI_ERR_READ_ONLY
MPI_ERR_RMA_ATTACH
MPI_ERR_RMA_CONFLICT
MPI_ERR_RMA_RANGE
MPI_ERR_RMA_SHARED
MPI_ERR_RMA_SYNC
MPI_ERR_RMA_FLAVOR
MPI_ERR_SERVICE
MPI_ERR_SIZE
MPI_ERR_SPAWN
MPI_ERR_UNSUPPORTED_DATAREP
MPI_ERR_UNSUPPORTED_OPERATION
MPI_ERR_WIN
MPI_T_ERR_CANNOT_INIT
MPI_T_ERR_NOT_INITIALIZED
MPI_T_ERR_MEMORY
MPI_T_ERR_INVALID
MPI_T_ERR_INVALID_INDEX
MPI_T_ERR_INVALID_ITEM
MPI_T_ERR_INVALID_SESSION
MPI_T_ERR_INVALID_HANDLE
MPI_T_ERR_INVALID_NAME
MPI_T_ERR_OUT_OF_HANDLES
MPI_T_ERR_OUT_OF_SESSIONS
MPI_T_ERR_CVAR_SET_NOT_NOW
MPI_T_ERR_CVAR_SET_NEVER
MPI_T_ERR_PVAR_NO_WRITE
MPI_T_ERR_PVAR_NO_STARTSTOP
MPI_T_ERR_PVAR_NO_ATOMIC
MPI_ERR_LASTCODE
Definition at line 71 of file mpi.h.
MPI_Datatype
enum MPI_Datatype
Named Predefined Datatypes.
Enumerator
MPI_CHAR
MPI_SHORT
MPI_LONG
MPI_INT
MPI_UNSIGNED_CHAR
MPI_UNSIGNED_SHORT
MPI_UNSIGNED
MPI_UNSIGNED_LONG
Definition at line 46 of file mpi.h.
Function Documentation
MPI_Comm_rank()
C int MPI_Comm_rank (MPI_Comm comm, int * rank)
Communicator Contexts.
Definition at line 23 of file MPI_Comm.cpp.
References SystemInformation::coreId, and MPI_SUCCESS.
Referenced by main().
MPI_Comm_size()
C int MPI_Comm_size (MPI_Comm comm, int * size)
Definition at line 31 of file MPI_Comm.cpp.
References coreCount, and MPI_SUCCESS.
Referenced by main().
MPI_Finalize()
C int MPI_Finalize (void)
Definition at line 227 of file MPI.cpp.
References MPI_SUCCESS.
Referenced by main().
MPI_Get_library_version()
C int MPI_Get_library_version (char * version, int * resultlen)
Definition at line 244 of file MPI.cpp.
References MPI_SUCCESS.
MPI_Get_processor_name()
C int MPI_Get_processor_name (char * name, int * resultlen)
Definition at line 232 of file MPI.cpp.
References MPI_SUCCESS.
Referenced by main().
MPI_Get_version()
C int MPI_Get_version (int * version, int * subversion)
Definition at line 237 of file MPI.cpp.
References MPI_SUCCESS.
MPI_Init()
C int MPI_Init (int * argc, char *** argv)
Environmental Management.
Definition at line 40 of file MPI.cpp.
References Memory::Range::access, FileSystemMessage::action, atoi(), FileSystemMessage::buffer, close(), Channel::Consumer, coreCount, SystemInformation::coreId, CORESRV_PID, CreateFile, errno, ESUCCESS, FileSystemMessage::from, Number::Hex, Index< T >::insert(), Singleton< ChannelClient >::instance, Map, MEMBASE, MPI_ERR_ARG, MPI_ERR_BAD_FILE, MPI_ERR_NO_MEM, MPI_ERR_SPAWN, MPI_PROG_CMDLEN, MPI_SUCCESS, O_RDONLY, FileSystemMessage::offset, open(), PAGESIZE, FileSystemMessage::path, Memory::Range::phys, printf(), Channel::Producer, read(), Memory::Readable, ReadFile, ChannelMessage::Request, FileSystemMessage::result, SELF, MemoryBlock::set(), MemoryChannel::setMessageSize(), Channel::setMode(), MemoryChannel::setPhysical(), Memory::Range::size, FileSystemMessage::size, snprintf(), stat::st_size, stat(), strcat(), strcmp(), strerror(), strlcpy(), strncmp(), API::Success, ChannelClient::syncSendReceive(), String::toLong(), ChannelMessage::type, Memory::User, Memory::Range::virt, VMCtl(), and Memory::Writable.
Referenced by main().
MPI_Recv()
C int MPI_Recv (void * buf, int count, MPI_Datatype datatype, int source, int tag, MPI_Comm comm, MPI_Status * status)
Definition at line 26 of file MPI_Recv.cpp.
References Index< T >::get(), MPIMessage::integer, MPI_ERR_RANK, MPI_ERR_UNSUPPORTED_DATAREP, MPI_INT, MPI_SUCCESS, MemoryChannel::read(), and Channel::Success.
Referenced by collect(), and main().
MPI_Send()
C int MPI_Send (const void * buf, int count, MPI_Datatype datatype, int dest, int tag, MPI_Comm comm)
Point-to-Point Communication.
Definition at line 26 of file MPI_Send.cpp.
References Index< T >::get(), MPIMessage::integer, MPI_ERR_RANK, MPI_ERR_UNSUPPORTED_DATAREP, MPI_INT, MPI_SUCCESS, Channel::Success, and MemoryChannel::write().
Referenced by collect(), and main().