FreeNOS: API (kernel handlers)
API (kernel handlers)
kernel
API handlers contain the kernel side implementation of the Application Programming Interface (API).
Functions
Error IOCtlHandler (IOOperation op, Address addr, ulong value)
Kernel handler prototype for various I/O functions.
API::Result PrivExecHandler (PrivOperation op, Address param)
Prototype for kernel handler.
API::Result ProcessCtlHandler (ProcessID proc, ProcessOperation op, Address addr, Address output)
Kernel handler prototype.
API::Result SystemInfoHandler (SystemInformation *info)
Kernel prototype.
API::Result VMCopyHandler (ProcessID proc, API::Operation how, Address ours, Address theirs, Size sz)
API::Result VMCtlHandler (ProcessID procID, MemoryOperation op, Memory::Range *range)
API::Result VMShareHandler (ProcessID pid, API::Operation op, ProcessShares::MemoryShare *share)
Detailed Description
API handlers contain the kernel side implementation of the Application Programming Interface (API).
Function Documentation
IOCtlHandler()
Error IOCtlHandler (IOOperation op, Address addr, ulong value)
Kernel handler prototype for various I/O functions.
Parameters
op Operation to perform
addr Input/Output address
value Value for writing
Returns
Error code
Definition at line 21 of file IOCtl.cpp.
References DEBUG, ARMIO::inb(), ARMIO::inw(), IOByteRead, IOByteWrite, IOLongWrite, IOWordRead, IOWordWrite, ARMIO::outb(), ARMIO::outl(), ARMIO::outw(), and API::Success.
Referenced by API::API(), and WriteLong().
PrivExecHandler()
API::Result PrivExecHandler (PrivOperation op, Address param)
Prototype for kernel handler.
Definition at line 21 of file PrivExec.cpp.
References cpu_reboot, cpu_shutdown, ProcessManager::current(), DEBUG, Kernel::getProcessManager(), Idle, idle, Singleton< Kernel >::instance, Singleton< Log >::instance, API::InvalidArgument, irq_enable, Reboot, ProcessManager::setIdle(), Shutdown, API::Success, and WriteConsole.
Referenced by API::API(), and PrivExec().
ProcessCtlHandler()
API::Result ProcessCtlHandler (ProcessID proc, ProcessOperation op, Address addr, Address output)
Kernel handler prototype.
Definition at line 36 of file ProcessCtl.cpp.
References ProcessManager::create(), ProcessManager::current(), DEBUG, DisableIRQ, EnableIRQ, Kernel::enableIRQ(), EnterSleep, ProcessManager::get(), Timer::getCurrent(), Process::getID(), GetParent, Process::getParent(), GetPID, Kernel::getProcessManager(), Process::getWait(), Kernel::hookIntVector(), ProcessInfo::id, InfoPID, InfoTimer, Singleton< Kernel >::instance, interruptNotify(), IRQ, ProcessInfo::kernelStack, KillPID, API::NotFound, ProcessInfo::pageDirectory, ProcessInfo::parent, ProcessManager::remove(), Resume, Schedule, ProcessManager::schedule(), SELF, Process::setParent(), Process::setSleepTimer(), SetStack, Process::setState(), Process::setWait(), Process::sleep(), Process::Sleeping, Spawn, ProcessInfo::state, Process::Success, API::Success, ProcessInfo::userStack, Process::Waiting, WaitPID, WaitTimer, Process::wakeup(), WatchIRQ, and ZERO.
Referenced by API::API(), and ProcessCtl().
SystemInfoHandler()
API::Result SystemInfoHandler (SystemInformation * info)
Kernel prototype.
Definition at line 24 of file SystemInfo.cpp.
References SplitAllocator::available(), CoreInfo::bootImageAddress, SystemInformation::bootImageAddress, CoreInfo::bootImageSize, SystemInformation::bootImageSize, SystemInformation::cmdline, MemoryBlock::copy(), CoreInfo::coreChannelAddress, SystemInformation::coreChannelAddress, CoreInfo::coreChannelSize, SystemInformation::coreChannelSize, CoreInfo::coreId, SystemInformation::coreId, coreInfo, DEBUG, Kernel::getAllocator(), Kernel::getCoreInfo(), Singleton< Kernel >::instance, CoreInfo::kernelCommand, SystemInformation::memoryAvail, SystemInformation::memorySize, SplitAllocator::size(), API::Success, CoreInfo::timerCounter, SystemInformation::timerCounter, and SystemInformation::version.
Referenced by API::API(), and SystemInfo().
VMCopyHandler()
API::Result VMCopyHandler (ProcessID proc, API::Operation how, Address ours, Address theirs, Size sz)
Definition at line 22 of file VMCopy.cpp.
References API::AccessViolation, MemoryBlock::copy(), ProcessManager::current(), DEBUG, MemoryContext::findFree(), ProcessManager::get(), Process::getMemoryContext(), Kernel::getProcessManager(), Singleton< Kernel >::instance, MemoryMap::KernelPrivate, MemoryContext::lookup(), MemoryContext::map(), API::NotFound, PAGEMASK, PAGESIZE, API::RangeError, API::Read, Memory::Readable, API::ReadPhys, SELF, MemoryContext::Success, total, MemoryContext::unmap(), Memory::Writable, and API::Write.
Referenced by API::API(), and VMCopy().
VMCtlHandler()
API::Result VMCtlHandler (ProcessID procID, MemoryOperation op, Memory::Range * range)
Definition at line 23 of file VMCtl.cpp.
References Access, Memory::Range::access, MemoryContext::access(), API::AccessViolation, CacheClean, ARMCacheV6::cleanInvalidate(), ProcessManager::current(), Cache::Data, DEBUG, ERROR, MemoryContext::findFree(), ProcessManager::get(), Process::getMemoryContext(), Kernel::getProcessManager(), Singleton< Kernel >::instance, API::InvalidArgument, MemoryContext::lookup(), LookupVirtual, Map, MemoryContext::mapRange(), API::NotFound, API::OutOfMemory, PAGEMASK, PAGESIZE, Memory::Range::phys, Release, MemoryContext::releaseRange(), ReserveMem, SELF, Memory::Range::size, MemoryContext::Success, Allocator::Success, API::Success, UnMap, MemoryContext::unmapRange(), MemoryMap::UserPrivate, Memory::Range::virt, and ZERO.
Referenced by API::API(), and VMCtl().
VMShareHandler()
API::Result VMShareHandler (ProcessID pid, API::Operation op, ProcessShares::MemoryShare * share)
Definition at line 24 of file VMShare.cpp.
References API::AlreadyExists, ProcessShares::AlreadyExists, API::Create, ProcessShares::createShare(), ProcessManager::current(), DEBUG, API::Delete, ProcessManager::get(), Kernel::getProcessManager(), Process::getShares(), Singleton< Kernel >::instance, API::InvalidArgument, API::IOError, API::NotFound, API::Read, ProcessShares::readShare(), ProcessShares::removeShares(), SELF, API::Success, ProcessShares::Success, and ZERO.
Referenced by API::API(), and VMShare().