FreeNOS: bin
bin
User program binaries that can be executed from the command line as a command or via forkexec().
Modules
sh
The Shell is a command interpreter program that can run external programs or builtin commands.
Data Structures
class BenchMark
Perform system benchmarking tests.
class Cat
Concatenate files to standard output.
class Echo
Echo standard input to output.
class Hostname
Print the system hostname.
struct BootEntry
Executable entry for use inside a boot image.
class BootImageCreate
Create system boot image.
class Init
Initialize system processes.
class IPCTest
Test program for inter process communication.
class Login
Login program which starts the user shell.
class ListFiles
List files on the filesystem.
class MakeNode
Create new device file node.
class Mount
Mount filesystems on the system.
class NetCat
Network send/receive (cat) application.
class NetCtl
Network interface control application.
class NetPing
Network ping/pong application.
class NetReceive
Network receive application.
class NetSend
Network send application.
class SievePrime
Compute prime numbers using the Sieve of Eratosthenes algorithm.
class ProcessList
Output the system process list.
class Remove
Remove file from the filesystem.
class Shell
System command shell interpreter.
class Sleep
Stop executing for some time.
class FileStatus
Retrieve file status from the filesystem.
class SysInfo
Print global system information.
class CreateFile
Create new files on the filesystem.
class UnixName
Print the operating system name.
Macros
#define BOOTENTRY_MAX_REGIONS 16
Maximum memory regions.
Typedefs
typedef struct BootEntry BootEntry
Executable entry for use inside a boot image.
Functions
ChangeDirCommand::ChangeDirCommand ()
Constructor function.
virtual int ChangeDirCommand::execute (Size nparams, char **params)
Executes the command.
Detailed Description
User program binaries that can be executed from the command line as a command or via forkexec().
Macro Definition Documentation
BOOTENTRY_MAX_REGIONS
#define BOOTENTRY_MAX_REGIONS 16
Maximum memory regions.
Definition at line 31 of file BootImageCreate.h.
Referenced by BootImageCreate::readBootSymbols().
Typedef Documentation
BootEntry
typedef struct BootEntry BootEntry
Executable entry for use inside a boot image.
Function Documentation
ChangeDirCommand()
ChangeDirCommand::ChangeDirCommand ()
Constructor function.
Definition at line 26 of file ChangeDirCommand.cpp.
References ShellCommand::m_help.
execute()
int ChangeDirCommand::execute (Size nparams, char ** params) virtual
Executes the command.
Parameters
nparams Number of parameters given.
params Array of parameters.
Returns
Error code or zero on success.
Implements ShellCommand.
Definition at line 32 of file ChangeDirCommand.cpp.
References chdir(), errno, ERROR, EXIT_FAILURE, EXIT_SUCCESS, ShellCommand::getName(), refreshMounts(), and strerror().