FreeNOS: kernel/intel/pc/Main.cpp File Reference
Main.cpp File Reference
#include <FreeNOS/Config.h>
#include <FreeNOS/Support.h>
#include <FreeNOS/System.h>
#include <intel/IntelKernel.h>
#include <intel/IntelSerial.h>
#include <CoreInfo.h>
#include <Macros.h>
#include <Log.h>
Functions
C int kernel_main (CoreInfo *info)
Function Documentation
kernel_main()
C int kernel_main (CoreInfo * info)
Definition at line 27 of file Main.cpp.
References constructors(), CoreInfo::coreId, coreInfo, Kernel::heap(), CoreInfo::heapAddress, CoreInfo::heapSize, MegaByte, Log::Notice, Kernel::run(), and Log::setMinimumLogLevel().