FreeNOS: kernel/arm/raspberry/Main.cpp File Reference
Main.cpp File Reference
#include <FreeNOS/Config.h>
#include <FreeNOS/Support.h>
#include <FreeNOS/System.h>
#include <FreeNOS/arm/ARMKernel.h>
#include <Macros.h>
#include <arm/ARMControl.h>
#include <arm/broadcom/BroadcomInterrupt.h>
#include <arm/broadcom/BroadcomTimer.h>
#include "RaspiSerial.h"
Functions
C int kernel_main (u32 r0, u32 r1, u32 r2)
Variables
Address __bootimg
Function Documentation
kernel_main()
C int kernel_main (u32 r0, u32 r1, u32 r2)
Definition at line 30 of file Main.cpp.
References __bootimg, CoreInfo::bootImageAddress, BootImage::bootImageSize, CoreInfo::bootImageSize, constructors(), coreInfo, Kernel::heap(), CoreInfo::heapAddress, CoreInfo::heapSize, ARMCacheV6::invalidate(), CoreInfo::kernel, MegaByte, CoreInfo::memory, Log::Notice, PAGEMASK, PAGESIZE, Memory::Range::phys, Kernel::run(), MemoryBlock::set(), ARMControl::set(), Log::setMinimumLogLevel(), Memory::Range::size, ARMControl::SMPBit, and Cache::Unified.
Variable Documentation
__bootimg
Address __bootimg
Referenced by kernel_main().