FreeNOS: server/filesystem/linn/LinnDump.cpp File Reference
LinnDump.cpp File Reference
#include <Types.h>
#include "LinnSuperBlock.h"
#include "LinnGroup.h"
#include "LinnInode.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <time.h>
Functions
char * timeString (u32 timestamp)
void usage (char *prog)
int main (int argc, char **argv)
Program entry point.
Function Documentation
timeString()
char* timeString (u32 timestamp)
Definition at line 28 of file LinnDump.cpp.
References malloc(), and strdup().
Referenced by main().
usage()
void usage (char * prog)
Definition at line 52 of file LinnDump.cpp.
References printf().
Referenced by ArgumentParser::getUsage(), and main().