FreeNOS: Character Namespace Reference
Character Namespace Reference
lib » libstd
Functions
bool isDigit (char c)
Test for a decimal digit.
bool isWildcard (char c)
Test for a wildcard character.
bool isLower (char c)
Test for a lowercase letter.
bool isUpper (char c)
Test for an uppercase letter.
bool isAlpha (char c)
Test for an alphabetic character.
bool isAlnum (char c)
Test for an alphanumeric character.
bool isBlank (char c)
Test for a blank character.
bool isWhitespace (char c)
Test for a white-space character.
char lower (char c)
Converts the letter c to lowercase.
char upper (char c)
Converts the letter c to uppercase.
Function Documentation
isAlnum()
bool Character::isAlnum (char c) inline
Test for an alphanumeric character.
Parameters
c Input character.
Returns
Boolean
Definition at line 98 of file Character.h.
References isAlpha(), and isDigit().
isAlpha()
bool Character::isAlpha (char c) inline
Test for an alphabetic character.
Parameters
c Input character.
Returns
Boolean
Definition at line 86 of file Character.h.
References isLower(), and isUpper().
Referenced by isAlnum(), and String::toLong().
isBlank()
bool Character::isBlank (char c) inline
Test for a blank character.
Parameters
c Input character.
Returns
Boolean
Definition at line 110 of file Character.h.
Referenced by isWhitespace().
isDigit()
bool Character::isDigit (char c) inline
Test for a decimal digit.
Parameters
c Input character.
Returns
Boolean
Definition at line 38 of file Character.h.
Referenced by isAlnum(), strtol(), and String::toLong().
isLower()
bool Character::isLower (char c) inline
Test for a lowercase letter.
Parameters
c Input character.
Returns
Boolean
Definition at line 62 of file Character.h.
Referenced by isAlpha().
isUpper()
bool Character::isUpper (char c) inline
Test for an uppercase letter.
Parameters
c Input character.
Returns
Boolean
Definition at line 74 of file Character.h.
Referenced by isAlpha(), and String::toLong().
isWhitespace()
bool Character::isWhitespace (char c) inline
Test for a white-space character.
Parameters
c Input character.
Returns
Boolean
Definition at line 122 of file Character.h.
References isBlank().
Referenced by String::toLong(), and String::trim().
isWildcard()
bool Character::isWildcard (char c) inline
Test for a wildcard character.
Parameters
c Input character.
Returns
True if wildcard, false otherwise.
Definition at line 50 of file Character.h.
Referenced by String::match().
lower()
char Character::lower (char c) inline
Converts the letter c to lowercase.
Parameters
c The letter to convert.
Returns
The converted letter, or c if conversion was not possible.
Definition at line 135 of file Character.h.
Referenced by String::compareTo(), and String::lower().
upper()
char Character::upper (char c) inline
Converts the letter c to uppercase.
Parameters
c The letter to convert.
Returns
The converted letter, or c if conversion was not possible.
Definition at line 147 of file Character.h.
Referenced by String::upper().