FreeNOS: lib/libposix/Runtime.cpp File Reference
Runtime.cpp File Reference
#include <FreeNOS/System.h>
#include <Types.h>
#include <Macros.h>
#include <Array.h>
#include <ChannelClient.h>
#include <PageAllocator.h>
#include <PoolAllocator.h>
#include <FileSystemMount.h>
#include <FileSystemMessage.h>
#include <MemoryMap.h>
#include <Core.h>
#include "FileDescriptor.h"
#include "stdlib.h"
#include "string.h"
#include "Runtime.h"
#include "unistd.h"
#include "libgen.h"
#include "fcntl.h"
#include "dirent.h"
Functions
C void __aeabi_unwind_cpp_pr0 ()
C int __cxa_atexit (void(*func)(void *), void *arg, void *dso_handle)
C int __aeabi_atexit ()
C void __cxa_pure_virtual ()
Unknown function, required by g++.
C void __stack_chk_fail (void)
C int raise (int sig)
void runConstructors ()
void runDestructors ()
void setupHeap ()
void setupRandomizer ()
void setupChannels ()
void setupMappings ()
ProcessID findMount (const char *path)
Retrieve the ProcessID of the FileSystemMount for the given path.
void refreshMounts (const char *path)
Refresh mounted filesystems.
ProcessID findMount (int fildes)
Lookup the ProcessID of a FileSystemMount by a filedescriptor number.
void waitMount (const char *path)
Blocking wait for a mounted filesystem.
FileSystemMount * getMounts ()
Get mounts table.
FileDescriptor * getFiles (void)
Get File Descriptors table.
String * getCurrentDirectory ()
Get current directory String.
C void SECTION (".entry") _entry()
Variables
void(* CTOR_LIST)()
List of constructors.
void(* DTOR_LIST)()
List of destructors.
static FileSystemMount mounts [FILESYSTEM_MAXMOUNTS]
FileSystem mounts table.
static FileDescriptor * files = (FileDescriptor *) NULL
Table with FileDescriptors.
String * currentDirectory = (String *) NULL
Current Directory String.
void * __dso_handle = 0
Function Documentation
__aeabi_atexit()
C int __aeabi_atexit ()
Definition at line 65 of file Runtime.cpp.
__aeabi_unwind_cpp_pr0()
C void __aeabi_unwind_cpp_pr0 ()
Definition at line 55 of file Runtime.cpp.
__cxa_atexit()
C int __cxa_atexit (void(*)(void *) func, void * arg, void * dso_handle)
Definition at line 59 of file Runtime.cpp.
__stack_chk_fail()
C void __stack_chk_fail (void)
Definition at line 74 of file Runtime.cpp.
raise()
C int raise (int sig)
Definition at line 78 of file Runtime.cpp.
runConstructors()
void runConstructors ()
Definition at line 83 of file Runtime.cpp.
References CTOR_LIST.
Referenced by SECTION().
runDestructors()
void runDestructors ()
Definition at line 91 of file Runtime.cpp.
References DTOR_LIST.
Referenced by SECTION().
SECTION()
C void SECTION (".entry")
Definition at line 268 of file Runtime.cpp.
References ARGV_COUNT, ARGV_SIZE, clearBSS(), exit(), main(), MemoryMap::range(), runConstructors(), runDestructors(), setupChannels(), setupHeap(), setupMappings(), setupRandomizer(), MemoryMap::UserArgs, and Memory::Range::virt.
setupChannels()
void setupChannels ()
Definition at line 132 of file Runtime.cpp.
References Singleton< ChannelClient >::instance, and ChannelClient::setRegistry().
Referenced by SECTION().
setupHeap()
void setupHeap ()
Definition at line 99 of file Runtime.cpp.
References Memory::Range::access, Map, PAGESIZE, Memory::Range::phys, MemoryMap::range(), Memory::Readable, SELF, Allocator::setDefault(), Allocator::setParent(), Memory::Range::size, Memory::User, MemoryMap::UserHeap, Memory::Range::virt, VMCtl(), Memory::Writable, and ZERO.
Referenced by SECTION().
setupMappings()
void setupMappings ()
Definition at line 140 of file Runtime.cpp.
References FILESYSTEM_MAXMOUNTS, getppid(), memset(), FileSystemMount::options, PAGESIZE, PATH_MAX, FileSystemMount::procID, MemoryMap::range(), ROOTFS_PID, Memory::Range::size, strlcpy(), SYSFS_PID, MemoryMap::UserArgs, Memory::Range::virt, and ZERO.
Referenced by SECTION().
setupRandomizer()
void setupRandomizer ()
Definition at line 123 of file Runtime.cpp.
References getpid(), InfoTimer, ProcessCtl(), SELF, and srandom().
Referenced by SECTION().
Variable Documentation
__dso_handle
void* __dso_handle = 0
Definition at line 53 of file Runtime.cpp.
CTOR_LIST
void(* CTOR_LIST) ()
List of constructors.
Referenced by constructors(), and runConstructors().
currentDirectory
String* currentDirectory = (String *) NULL
Current Directory String.
Definition at line 51 of file Runtime.cpp.
Referenced by getCurrentDirectory(), and IntelPaging::IntelPaging().
DTOR_LIST
void(* DTOR_LIST) ()
List of destructors.
Referenced by destructors(), and runDestructors().
files
FileDescriptor* files = (FileDescriptor *) NULL static
Table with FileDescriptors.
Definition at line 48 of file Runtime.cpp.
Referenced by USBDevice::beginTransfer(), close(), getFiles(), lseek(), open(), read(), and write().
mounts
FileSystemMount mounts[FILESYSTEM_MAXMOUNTS] static
FileSystem mounts table.
Definition at line 45 of file Runtime.cpp.
Referenced by Mount::exec(), NetCtl::exec(), getMounts(), NetworkClient::initialize(), MountsFile::read(), MountWaitFile::write(), and MountsFile::write().