FreeNOS: lib/libteken/teken.c File Reference
teken.c File Reference
#include <sys/types.h>
#include <Assert.h>
#include <stdio.h>
#include <string.h>
#include "teken.h"
#include "teken_subr.h"
#include "teken_subr_compat.h"
#include "teken_state.h"
Macros
#define __unused __attribute((unused))
#define teken_assert(x) assert(x)
#define teken_printf(x, ...)
#define teken_wcwidth(c) (1)
#define teken_scs_process(t, c) (c)
#define teken_scs_restore(t)
#define teken_scs_save(t)
#define teken_scs_set(t, g, ts)
#define teken_scs_switch(t, g)
#define TS_FIRSTDIGIT 0x01 /* First numeric digit in escape sequence. */
#define TS_INSERT 0x02 /* Insert mode. */
#define TS_AUTOWRAP 0x04 /* Autowrap. */
#define TS_ORIGIN 0x08 /* Origin mode. */
#define TS_WRAPPED 0x00 /* Simple line wrapping. */
#define BLANK ' '
Functions
static void teken_funcs_bell (teken_t *t)
static void teken_funcs_cursor (teken_t *t)
static void teken_funcs_putchar (teken_t *t, const teken_pos_t *p, teken_char_t c, const teken_attr_t *a)
static void teken_funcs_fill (teken_t *t, const teken_rect_t *r, const teken_char_t c, const teken_attr_t *a)
static void teken_funcs_copy (teken_t *t, const teken_rect_t *r, const teken_pos_t *p)
static void teken_funcs_param (teken_t *t, int cmd, unsigned int value)
static void teken_funcs_respond (teken_t *t, const void *buf, size_t len)
void teken_init (teken_t *t, const teken_funcs_t *tf, void *softc)
static void teken_input_char (teken_t *t, teken_char_t c)
static void teken_input_byte (teken_t *t, unsigned char c)
void teken_input (teken_t *t, const void *buf, size_t len)
void teken_set_cursor (teken_t *t, const teken_pos_t *p)
const teken_attr_t * teken_get_curattr (teken_t *t)
void teken_set_curattr (teken_t *t, const teken_attr_t *a)
const teken_attr_t * teken_get_defattr (teken_t *t)
void teken_set_defattr (teken_t *t, const teken_attr_t *a)
void teken_set_winsize (teken_t *t, const teken_pos_t *p)
static void teken_state_switch (teken_t *t, teken_state_t *s)
static int teken_state_numbers (teken_t *t, teken_char_t c)
Variables
static FILE * df
static teken_state_t teken_state_init
Macro Definition Documentation
__unused
#define __unused __attribute((unused))
Definition at line 29 of file teken.c.
BLANK
#define BLANK ' '
Definition at line 77 of file teken.c.
Referenced by teken_subr_delete_character(), teken_subr_delete_line(), teken_subr_do_scroll(), teken_subr_erase_character(), teken_subr_erase_display(), teken_subr_erase_line(), teken_subr_horizontal_tab(), teken_subr_insert_character(), teken_subr_insert_line(), and teken_subr_newpage().
teken_assert
#define teken_assert (x) assert(x)
Definition at line 34 of file teken.c.
Referenced by teken_funcs_copy(), teken_funcs_cursor(), teken_funcs_fill(), teken_funcs_putchar(), teken_input_char(), teken_set_cursor(), teken_state_numbers(), and teken_subr_do_scroll().
teken_printf
#define teken_printf (x, ...)
Value:
do { \
        if (df != NULL) \
                printf(x, ## __VA_ARGS__); \
} while (0)
Definition at line 35 of file teken.c.
Referenced by teken_input_byte(), teken_state_1(), teken_state_2(), teken_state_3(), teken_state_4(), teken_state_5(), teken_state_6(), teken_state_7(), teken_state_8(), teken_subr_device_control_string(), teken_subr_do_cpr(), teken_subr_double_height_double_width_line_bottom(), teken_subr_double_height_double_width_line_top(), teken_subr_primary_device_attributes(), teken_subr_reset_dec_mode(), teken_subr_reset_mode(), teken_subr_secondary_device_attributes(), teken_subr_set_dec_mode(), teken_subr_set_graphic_rendition(), teken_subr_set_mode(), teken_subr_single_height_double_width_line(), teken_subr_single_height_single_width_line(), and teken_subr_string_terminator().
teken_scs_process
#define teken_scs_process (t, c) (c)
Definition at line 58 of file teken.c.
Referenced by teken_subr_regular_character().
teken_scs_restore
#define teken_scs_restore (t)
Definition at line 59 of file teken.c.
Referenced by teken_subr_restore_cursor().
teken_scs_save
#define teken_scs_save (t)
Definition at line 60 of file teken.c.
Referenced by teken_subr_save_cursor().
teken_scs_set
#define teken_scs_set (t, g, ts)
Definition at line 61 of file teken.c.
Referenced by teken_subr_do_reset(), teken_subr_g0_scs_special_graphics(), teken_subr_g0_scs_uk_national(), teken_subr_g0_scs_us_ascii(), teken_subr_g1_scs_special_graphics(), teken_subr_g1_scs_uk_national(), and teken_subr_g1_scs_us_ascii().
teken_scs_switch
#define teken_scs_switch (t, g)
Definition at line 62 of file teken.c.
Referenced by teken_input_char(), and teken_subr_do_reset().
teken_wcwidth
#define teken_wcwidth (c) (1)
Definition at line 51 of file teken.c.
Referenced by teken_subr_regular_character().
TS_AUTOWRAP
#define TS_AUTOWRAP 0x04 /* Autowrap. */
Definition at line 68 of file teken.c.
Referenced by teken_subr_do_reset(), teken_subr_regular_character(), teken_subr_reset_dec_mode(), and teken_subr_set_dec_mode().
TS_FIRSTDIGIT
#define TS_FIRSTDIGIT 0x01 /* First numeric digit in escape sequence. */
Definition at line 66 of file teken.c.
Referenced by teken_state_numbers(), and teken_state_switch().
TS_INSERT
#define TS_INSERT 0x02 /* Insert mode. */
Definition at line 67 of file teken.c.
Referenced by teken_subr_do_putchar(), teken_subr_reset_mode(), and teken_subr_set_mode().
TS_ORIGIN
#define TS_ORIGIN 0x08 /* Origin mode. */
Definition at line 69 of file teken.c.
Referenced by teken_subr_reset_dec_mode(), teken_subr_set_dec_mode(), and teken_subr_set_top_and_bottom_margins().
TS_WRAPPED
#define TS_WRAPPED 0x00 /* Simple line wrapping. */
Definition at line 73 of file teken.c.
Referenced by teken_subr_alignment_test(), teken_subr_backspace(), teken_subr_carriage_return(), teken_subr_cursor_backward(), teken_subr_cursor_down(), teken_subr_cursor_forward(), teken_subr_cursor_position(), teken_subr_cursor_up(), teken_subr_horizontal_position_absolute(), teken_subr_index(), teken_subr_newline(), teken_subr_regular_character(), teken_subr_reset_dec_mode(), teken_subr_restore_cursor(), teken_subr_reverse_index(), teken_subr_set_dec_mode(), teken_subr_set_top_and_bottom_margins(), and teken_subr_vertical_position_absolute().
Function Documentation
teken_funcs_bell()
static void teken_funcs_bell (teken_t * t) inline static
Definition at line 86 of file teken.c.
References __teken::t_funcs, __teken::t_softc, and teken_funcs_t::tf_bell.
Referenced by teken_subr_bell().
teken_funcs_copy()
static void teken_funcs_copy (teken_t * t, const teken_rect_t * r, const teken_pos_t * p) inline static
Definition at line 127 of file teken.c.
References __teken::t_funcs, __teken::t_softc, __teken::t_winsize, teken_assert, teken_funcs_t::tf_copy, teken_pos_t::tp_col, teken_pos_t::tp_row, teken_rect_t::tr_begin, and teken_rect_t::tr_end.
Referenced by teken_subr_delete_character(), teken_subr_delete_line(), teken_subr_do_putchar(), teken_subr_do_scroll(), teken_subr_insert_character(), and teken_subr_insert_line().
teken_funcs_cursor()
static void teken_funcs_cursor (teken_t * t) inline static
Definition at line 93 of file teken.c.
References __teken::t_cursor, __teken::t_funcs, __teken::t_softc, __teken::t_winsize, teken_assert, teken_funcs_t::tf_cursor, teken_pos_t::tp_col, and teken_pos_t::tp_row.
Referenced by teken_subr_alignment_test(), teken_subr_backspace(), teken_subr_carriage_return(), teken_subr_cursor_backward(), teken_subr_cursor_backward_tabulation(), teken_subr_cursor_down(), teken_subr_cursor_forward(), teken_subr_cursor_forward_tabulation(), teken_subr_cursor_position(), teken_subr_cursor_up(), teken_subr_horizontal_position_absolute(), teken_subr_index(), teken_subr_newline(), teken_subr_newpage(), teken_subr_regular_character(), teken_subr_reset_dec_mode(), teken_subr_reset_to_initial_state(), teken_subr_restore_cursor(), teken_subr_reverse_index(), teken_subr_set_dec_mode(), teken_subr_set_top_and_bottom_margins(), and teken_subr_vertical_position_absolute().
teken_funcs_fill()
static void teken_funcs_fill (teken_t * t, const teken_rect_t * r, const teken_char_t c, const teken_attr_t * a) inline static
Definition at line 114 of file teken.c.
References __teken::t_funcs, __teken::t_softc, __teken::t_winsize, teken_assert, teken_funcs_t::tf_fill, teken_pos_t::tp_col, teken_pos_t::tp_row, teken_rect_t::tr_begin, and teken_rect_t::tr_end.
Referenced by teken_subr_alignment_test(), teken_subr_delete_character(), teken_subr_delete_line(), teken_subr_do_scroll(), teken_subr_erase_character(), teken_subr_erase_display(), teken_subr_erase_line(), teken_subr_horizontal_tab(), teken_subr_insert_character(), teken_subr_insert_line(), and teken_subr_newpage().
teken_funcs_param()
static void teken_funcs_param (teken_t * t, int cmd, unsigned int value) inline static
Definition at line 141 of file teken.c.
References __teken::t_funcs, __teken::t_softc, and teken_funcs_t::tf_param.
Referenced by teken_subr_cons25_set_cursor_type(), teken_subr_cons25_switch_virtual_terminal(), teken_subr_keypad_application_mode(), teken_subr_keypad_numeric_mode(), teken_subr_reset_dec_mode(), teken_subr_reset_to_initial_state(), and teken_subr_set_dec_mode().
teken_funcs_putchar()
static void teken_funcs_putchar (teken_t * t, const teken_pos_t * p, teken_char_t c, const teken_attr_t * a) inline static
Definition at line 103 of file teken.c.
References __teken::t_funcs, __teken::t_softc, __teken::t_winsize, teken_assert, teken_funcs_t::tf_putchar, teken_pos_t::tp_col, and teken_pos_t::tp_row.
Referenced by teken_subr_do_putchar().
teken_funcs_respond()
static void teken_funcs_respond (teken_t * t, const void * buf, size_t len) inline static
Definition at line 148 of file teken.c.
References __teken::t_funcs, __teken::t_softc, and teken_funcs_t::tf_respond.
Referenced by teken_subr_cursor_position_report(), teken_subr_device_status_report(), teken_subr_primary_device_attributes(), and teken_subr_secondary_device_attributes().
teken_get_curattr()
const teken_attr_t* teken_get_curattr (teken_t * t)
Definition at line 298 of file teken.c.
References __teken::t_curattr.
teken_get_defattr()
const teken_attr_t* teken_get_defattr (teken_t * t)
Definition at line 312 of file teken.c.
References __teken::t_defattr.
teken_init()
void teken_init (teken_t * t, const teken_funcs_t * tf, void * softc)
Definition at line 162 of file teken.c.
References __teken::t_defattr, __teken::t_funcs, __teken::t_nextstate, __teken::t_softc, teken_attr_t::ta_bgcolor, teken_attr_t::ta_fgcolor, teken_attr_t::ta_format, TC_BLACK, TC_WHITE, teken_set_winsize(), teken_state_init, teken_subr_do_reset(), and teken_pos_t::tp_row.
Referenced by Terminal::initialize().
teken_input()
void teken_input (teken_t * t, const void * buf, size_t len)
Definition at line 278 of file teken.c.
References teken_input_byte().
Referenced by Terminal::write().
teken_input_byte()
static void teken_input_byte (teken_t * t, unsigned char c) static
Definition at line 239 of file teken.c.
References teken_input_char(), and teken_printf.
Referenced by teken_input().
teken_input_char()
static void teken_input_char (teken_t * t, teken_char_t c) static
Definition at line 184 of file teken.c.
References __teken::t_cursor, __teken::t_nextstate, __teken::t_originreg, __teken::t_saved_cursor, __teken::t_scrollreg, __teken::t_winsize, teken_assert, teken_scs_switch, teken_subr_backspace(), teken_subr_bell(), teken_subr_carriage_return(), teken_subr_horizontal_tab(), teken_subr_newline(), teken_subr_newpage(), teken_pos_t::tp_col, teken_pos_t::tp_row, teken_span_t::ts_begin, and teken_span_t::ts_end.
Referenced by teken_input_byte().
teken_set_curattr()
void teken_set_curattr (teken_t * t, const teken_attr_t * a)
Definition at line 305 of file teken.c.
References __teken::t_curattr.
teken_set_cursor()
void teken_set_cursor (teken_t * t, const teken_pos_t * p)
Definition at line 287 of file teken.c.
References __teken::t_cursor, __teken::t_winsize, teken_assert, teken_pos_t::tp_col, and teken_pos_t::tp_row.
teken_set_defattr()
void teken_set_defattr (teken_t * t, const teken_attr_t * a)
Definition at line 319 of file teken.c.
References __teken::t_curattr, __teken::t_defattr, and __teken::t_saved_curattr.
teken_set_winsize()
void teken_set_winsize (teken_t * t, const teken_pos_t * p)
Definition at line 326 of file teken.c.
References __teken::t_originreg, __teken::t_scrollreg, __teken::t_winsize, teken_pos_t::tp_row, teken_span_t::ts_begin, and teken_span_t::ts_end.
Referenced by Terminal::initialize(), and teken_init().
teken_state_numbers()
static int teken_state_numbers (teken_t * t, teken_char_t c) static
Definition at line 350 of file teken.c.
References __teken::t_curnum, __teken::t_nums, T_NUMSIZE, __teken::t_stateflags, teken_assert, teken_state_init, teken_state_switch(), and TS_FIRSTDIGIT.
Referenced by teken_state_2(), teken_state_3(), teken_state_5(), and teken_state_8().
teken_state_switch()
static void teken_state_switch (teken_t * t, teken_state_t * s) static
Definition at line 341 of file teken.c.
References __teken::t_curnum, __teken::t_nextstate, __teken::t_stateflags, and TS_FIRSTDIGIT.
Referenced by teken_state_1(), teken_state_2(), teken_state_3(), teken_state_4(), teken_state_5(), teken_state_6(), teken_state_7(), teken_state_8(), teken_state_init(), and teken_state_numbers().
Variable Documentation
df
FILE* df static
Definition at line 41 of file teken.c.
teken_state_init
teken_state_t teken_state_init static
Definition at line 79 of file teken.c.
Referenced by teken_init(), and teken_state_numbers().