FreeNOS: lib/libteken/teken_subr_compat.h File Reference
teken_subr_compat.h File Reference
Functions
static void teken_subr_cons25_set_cursor_type (teken_t *t, unsigned int type)
static void teken_subr_cons25_set_adapter_background (teken_t *t, unsigned int c)
static void teken_subr_cons25_set_adapter_foreground (teken_t *t, unsigned int c)
static void teken_subr_cons25_switch_virtual_terminal (teken_t *t, unsigned int vt)
Variables
static const teken_color_t cons25_colors [8]
Function Documentation
teken_subr_cons25_set_adapter_background()
static void teken_subr_cons25_set_adapter_background (teken_t * t, unsigned int c) static
Definition at line 40 of file teken_subr_compat.h.
References cons25_colors, __teken::t_curattr, __teken::t_defattr, and teken_attr_t::ta_bgcolor.
Referenced by teken_state_8().
teken_subr_cons25_set_adapter_foreground()
static void teken_subr_cons25_set_adapter_foreground (teken_t * t, unsigned int c) static
Definition at line 48 of file teken_subr_compat.h.
References cons25_colors, __teken::t_curattr, __teken::t_defattr, teken_attr_t::ta_fgcolor, teken_attr_t::ta_format, and TF_BOLD.
Referenced by teken_state_8().
teken_subr_cons25_set_cursor_type()
static void teken_subr_cons25_set_cursor_type (teken_t * t, unsigned int type) static
Definition at line 30 of file teken_subr_compat.h.
References teken_funcs_param(), and TP_SHOWCURSOR.
Referenced by teken_state_8().
teken_subr_cons25_switch_virtual_terminal()
static void teken_subr_cons25_switch_virtual_terminal (teken_t * t, unsigned int vt) static
Definition at line 63 of file teken_subr_compat.h.
References teken_funcs_param(), and TP_SWITCHVT.
Referenced by teken_state_2().
Variable Documentation
cons25_colors
const teken_color_t cons25_colors[8] static
Initial value:
= { TC_BLACK, TC_BLUE,
    TC_GREEN, TC_CYAN, TC_RED, TC_MAGENTA, TC_BROWN, TC_WHITE }
Definition at line 36 of file teken_subr_compat.h.
Referenced by teken_subr_cons25_set_adapter_background(), and teken_subr_cons25_set_adapter_foreground().