FreeNOS: lib/libteken/teken_state.h File Reference
teken_state.h File Reference
Functions
static void teken_state_3 (teken_t *t, teken_char_t c)
static void teken_state_init (teken_t *t, teken_char_t c)
static void teken_state_5 (teken_t *t, teken_char_t c)
static void teken_state_2 (teken_t *t, teken_char_t c)
static void teken_state_1 (teken_t *t, teken_char_t c)
static void teken_state_6 (teken_t *t, teken_char_t c)
static void teken_state_7 (teken_t *t, teken_char_t c)
static void teken_state_8 (teken_t *t, teken_char_t c)
static void teken_state_4 (teken_t *t, teken_char_t c)
Variables
static teken_state_t teken_state_3
static teken_state_t teken_state_5
static teken_state_t teken_state_2
static teken_state_t teken_state_1
static teken_state_t teken_state_6
static teken_state_t teken_state_7
static teken_state_t teken_state_8
static teken_state_t teken_state_4
Function Documentation
teken_state_1()
static void teken_state_1 (teken_t * t, teken_char_t c) static
Definition at line 203 of file teken_state.h.
References teken_printf, teken_state_2, teken_state_4, teken_state_6, teken_state_7, teken_state_init(), teken_state_switch(), teken_subr_device_control_string(), teken_subr_horizontal_tab_set(), teken_subr_index(), teken_subr_keypad_application_mode(), teken_subr_keypad_numeric_mode(), teken_subr_next_line(), teken_subr_reset_to_initial_state(), teken_subr_restore_cursor(), teken_subr_reverse_index(), teken_subr_save_cursor(), and teken_subr_string_terminator().
teken_state_2()
static void teken_state_2 (teken_t * t, teken_char_t c) static
Definition at line 75 of file teken_state.h.
References __teken::t_curnum, __teken::t_nums, teken_printf, teken_state_3, teken_state_5, teken_state_8, teken_state_init(), teken_state_numbers(), teken_state_switch(), teken_subr_cons25_switch_virtual_terminal(), teken_subr_cursor_backward(), teken_subr_cursor_backward_tabulation(), teken_subr_cursor_down(), teken_subr_cursor_forward(), teken_subr_cursor_forward_tabulation(), teken_subr_cursor_next_line(), teken_subr_cursor_position(), teken_subr_cursor_position_report(), teken_subr_cursor_previous_line(), teken_subr_cursor_up(), teken_subr_delete_character(), teken_subr_delete_line(), teken_subr_erase_character(), teken_subr_erase_display(), teken_subr_erase_line(), teken_subr_horizontal_position_absolute(), teken_subr_insert_character(), teken_subr_insert_line(), teken_subr_pan_down(), teken_subr_pan_up(), teken_subr_primary_device_attributes(), teken_subr_reset_mode(), teken_subr_restore_cursor(), teken_subr_save_cursor(), teken_subr_set_graphic_rendition(), teken_subr_set_mode(), teken_subr_set_top_and_bottom_margins(), teken_subr_tab_clear(), and teken_subr_vertical_position_absolute().
teken_state_3()
static void teken_state_3 (teken_t * t, teken_char_t c) static
Definition at line 14 of file teken_state.h.
References __teken::t_curnum, __teken::t_nums, teken_printf, teken_state_init(), teken_state_numbers(), teken_state_switch(), and teken_subr_secondary_device_attributes().
teken_state_4()
static void teken_state_4 (teken_t * t, teken_char_t c) static
Definition at line 346 of file teken_state.h.
References teken_printf, teken_state_init(), teken_state_switch(), teken_subr_alignment_test(), teken_subr_double_height_double_width_line_bottom(), teken_subr_double_height_double_width_line_top(), teken_subr_single_height_double_width_line(), and teken_subr_single_height_single_width_line().
teken_state_5()
static void teken_state_5 (teken_t * t, teken_char_t c) static
Definition at line 49 of file teken_state.h.
References __teken::t_curnum, __teken::t_nums, teken_printf, teken_state_init(), teken_state_numbers(), teken_state_switch(), teken_subr_device_status_report(), teken_subr_reset_dec_mode(), and teken_subr_set_dec_mode().
teken_state_6()
static void teken_state_6 (teken_t * t, teken_char_t c) static
Definition at line 262 of file teken_state.h.
References teken_printf, teken_state_init(), teken_state_switch(), teken_subr_g0_scs_special_graphics(), teken_subr_g0_scs_uk_national(), and teken_subr_g0_scs_us_ascii().
teken_state_7()
static void teken_state_7 (teken_t * t, teken_char_t c) static
Definition at line 291 of file teken_state.h.
References teken_printf, teken_state_init(), teken_state_switch(), teken_subr_g1_scs_special_graphics(), teken_subr_g1_scs_uk_national(), and teken_subr_g1_scs_us_ascii().
teken_state_8()
static void teken_state_8 (teken_t * t, teken_char_t c) static
Definition at line 320 of file teken_state.h.
References __teken::t_curnum, __teken::t_nums, teken_printf, teken_state_init(), teken_state_numbers(), teken_state_switch(), teken_subr_cons25_set_adapter_background(), teken_subr_cons25_set_adapter_foreground(), and teken_subr_cons25_set_cursor_type().
teken_state_init()
static void teken_state_init (teken_t * t, teken_char_t c) static
Definition at line 34 of file teken_state.h.
References teken_state_1, teken_state_switch(), and teken_subr_regular_character().
Referenced by teken_state_1(), teken_state_2(), teken_state_3(), teken_state_4(), teken_state_5(), teken_state_6(), teken_state_7(), and teken_state_8().
Variable Documentation
teken_state_1
teken_state_t teken_state_1 static
Definition at line 6 of file teken_state.h.
Referenced by teken_state_init().
teken_state_2
teken_state_t teken_state_2 static
Definition at line 5 of file teken_state.h.
Referenced by teken_state_1().
teken_state_3
teken_state_t teken_state_3 static
Definition at line 3 of file teken_state.h.
Referenced by teken_state_2().
teken_state_4
teken_state_t teken_state_4 static
Definition at line 10 of file teken_state.h.
Referenced by teken_state_1().
teken_state_5
teken_state_t teken_state_5 static
Definition at line 4 of file teken_state.h.
Referenced by teken_state_2().
teken_state_6
teken_state_t teken_state_6 static
Definition at line 7 of file teken_state.h.
Referenced by teken_state_1().
teken_state_7
teken_state_t teken_state_7 static
Definition at line 8 of file teken_state.h.
Referenced by teken_state_1().
teken_state_8
teken_state_t teken_state_8 static
Definition at line 9 of file teken_state.h.
Referenced by teken_state_2().