FreeNOS: lib/libteken/teken_subr.h File Reference
teken_subr.h File Reference
Functions
static void teken_subr_cursor_up (teken_t *, unsigned int)
static void teken_subr_erase_line (teken_t *, unsigned int)
static void teken_subr_regular_character (teken_t *, teken_char_t)
static void teken_subr_reset_to_initial_state (teken_t *)
static void teken_subr_save_cursor (teken_t *)
static int teken_tab_isset (teken_t *t, unsigned int col)
static void teken_tab_clear (teken_t *t, unsigned int col)
static void teken_tab_set (teken_t *t, unsigned int col)
static void teken_tab_default (teken_t *t)
static void teken_subr_do_scroll (teken_t *t, int amount)
static ssize_t teken_subr_do_cpr (teken_t *t, unsigned int cmd, char response[16])
static void teken_subr_alignment_test (teken_t *t)
static void teken_subr_backspace (teken_t *t)
static void teken_subr_bell (teken_t *t)
static void teken_subr_carriage_return (teken_t *t)
static void teken_subr_cursor_backward (teken_t *t, unsigned int ncols)
static void teken_subr_cursor_backward_tabulation (teken_t *t, unsigned int ntabs)
static void teken_subr_cursor_down (teken_t *t, unsigned int nrows)
static void teken_subr_cursor_forward (teken_t *t, unsigned int ncols)
static void teken_subr_cursor_forward_tabulation (teken_t *t, unsigned int ntabs)
static void teken_subr_cursor_next_line (teken_t *t, unsigned int ncols)
static void teken_subr_cursor_position (teken_t *t, unsigned int row, unsigned int col)
static void teken_subr_cursor_position_report (teken_t *t, unsigned int cmd)
static void teken_subr_cursor_previous_line (teken_t *t, unsigned int ncols)
static void teken_subr_delete_character (teken_t *t, unsigned int ncols)
static void teken_subr_delete_line (teken_t *t, unsigned int nrows)
static void teken_subr_device_control_string (teken_t *t __unused)
static void teken_subr_device_status_report (teken_t *t, unsigned int cmd)
static void teken_subr_double_height_double_width_line_top (teken_t *t __unused)
static void teken_subr_double_height_double_width_line_bottom (teken_t *t __unused)
static void teken_subr_erase_character (teken_t *t, unsigned int ncols)
static void teken_subr_erase_display (teken_t *t, unsigned int mode)
static void teken_subr_g0_scs_special_graphics (teken_t *t __unused)
static void teken_subr_g0_scs_uk_national (teken_t *t __unused)
static void teken_subr_g0_scs_us_ascii (teken_t *t __unused)
static void teken_subr_g1_scs_special_graphics (teken_t *t __unused)
static void teken_subr_g1_scs_uk_national (teken_t *t __unused)
static void teken_subr_g1_scs_us_ascii (teken_t *t __unused)
static void teken_subr_horizontal_position_absolute (teken_t *t, unsigned int col)
static void teken_subr_horizontal_tab (teken_t *t)
static void teken_subr_horizontal_tab_set (teken_t *t)
static void teken_subr_index (teken_t *t)
static void teken_subr_insert_character (teken_t *t, unsigned int ncols)
static void teken_subr_insert_line (teken_t *t, unsigned int nrows)
static void teken_subr_keypad_application_mode (teken_t *t)
static void teken_subr_keypad_numeric_mode (teken_t *t)
static void teken_subr_newline (teken_t *t)
static void teken_subr_newpage (teken_t *t)
static void teken_subr_next_line (teken_t *t)
static void teken_subr_pan_down (teken_t *t, unsigned int nrows)
static void teken_subr_pan_up (teken_t *t, unsigned int nrows)
static void teken_subr_primary_device_attributes (teken_t *t, unsigned int request)
static void teken_subr_do_putchar (teken_t *t, const teken_pos_t *tp, teken_char_t c, int width)
static void teken_subr_reset_dec_mode (teken_t *t, unsigned int cmd)
static void teken_subr_reset_mode (teken_t *t, unsigned int cmd)
static void teken_subr_do_reset (teken_t *t)
static void teken_subr_restore_cursor (teken_t *t)
static void teken_subr_reverse_index (teken_t *t)
static void teken_subr_secondary_device_attributes (teken_t *t, unsigned int request)
static void teken_subr_set_dec_mode (teken_t *t, unsigned int cmd)
static void teken_subr_set_mode (teken_t *t, unsigned int cmd)
static void teken_subr_set_graphic_rendition (teken_t *t, unsigned int ncmds, unsigned int cmds[])
static void teken_subr_set_top_and_bottom_margins (teken_t *t, unsigned int top, unsigned int bottom)
static void teken_subr_single_height_double_width_line (teken_t *t __unused)
static void teken_subr_single_height_single_width_line (teken_t *t __unused)
static void teken_subr_string_terminator (teken_t *t __unused)
static void teken_subr_tab_clear (teken_t *t, unsigned int cmd)
static void teken_subr_vertical_position_absolute (teken_t *t, unsigned int row)
Function Documentation
teken_subr_alignment_test()
static void teken_subr_alignment_test (teken_t * t) static
Definition at line 184 of file teken_subr.h.
References __teken::t_cursor, __teken::t_defattr, __teken::t_scrollreg, __teken::t_stateflags, __teken::t_winsize, teken_funcs_cursor(), teken_funcs_fill(), teken_pos_t::tp_col, teken_pos_t::tp_row, teken_rect_t::tr_begin, teken_rect_t::tr_end, teken_span_t::ts_begin, teken_span_t::ts_end, and TS_WRAPPED.
Referenced by teken_state_4().
teken_subr_backspace()
static void teken_subr_backspace (teken_t * t) static
Definition at line 202 of file teken_subr.h.
References __teken::t_cursor, __teken::t_originreg, __teken::t_stateflags, __teken::t_winsize, teken_funcs_cursor(), teken_pos_t::tp_col, teken_pos_t::tp_row, teken_span_t::ts_begin, and TS_WRAPPED.
Referenced by teken_input_char().
teken_subr_bell()
static void teken_subr_bell (teken_t * t) static
Definition at line 226 of file teken_subr.h.
References teken_funcs_bell().
Referenced by teken_input_char().
teken_subr_carriage_return()
static void teken_subr_carriage_return (teken_t * t) static
Definition at line 233 of file teken_subr.h.
References __teken::t_cursor, __teken::t_stateflags, teken_funcs_cursor(), teken_pos_t::tp_col, and TS_WRAPPED.
Referenced by teken_input_char().
teken_subr_cursor_backward()
static void teken_subr_cursor_backward (teken_t * t, unsigned int ncols) static
Definition at line 242 of file teken_subr.h.
References __teken::t_cursor, __teken::t_stateflags, teken_funcs_cursor(), teken_pos_t::tp_col, and TS_WRAPPED.
Referenced by teken_state_2().
teken_subr_cursor_backward_tabulation()
static void teken_subr_cursor_backward_tabulation (teken_t * t, unsigned int ntabs) static
Definition at line 254 of file teken_subr.h.
References __teken::t_cursor, teken_funcs_cursor(), teken_tab_isset(), and teken_pos_t::tp_col.
Referenced by teken_state_2().
teken_subr_cursor_down()
static void teken_subr_cursor_down (teken_t * t, unsigned int nrows) static
Definition at line 273 of file teken_subr.h.
References __teken::t_cursor, __teken::t_scrollreg, __teken::t_stateflags, teken_funcs_cursor(), teken_pos_t::tp_row, teken_span_t::ts_end, and TS_WRAPPED.
Referenced by teken_state_2(), and teken_subr_cursor_next_line().
teken_subr_cursor_forward()
static void teken_subr_cursor_forward (teken_t * t, unsigned int ncols) static
Definition at line 285 of file teken_subr.h.
References __teken::t_cursor, __teken::t_stateflags, __teken::t_winsize, teken_funcs_cursor(), teken_pos_t::tp_col, and TS_WRAPPED.
Referenced by teken_state_2().
teken_subr_cursor_forward_tabulation()
static void teken_subr_cursor_forward_tabulation (teken_t * t, unsigned int ntabs) static
Definition at line 297 of file teken_subr.h.
References __teken::t_cursor, __teken::t_winsize, teken_funcs_cursor(), teken_tab_isset(), and teken_pos_t::tp_col.
Referenced by teken_state_2(), and teken_subr_horizontal_tab().
teken_subr_cursor_next_line()
static void teken_subr_cursor_next_line (teken_t * t, unsigned int ncols) static
Definition at line 316 of file teken_subr.h.
References __teken::t_cursor, teken_subr_cursor_down(), and teken_pos_t::tp_col.
Referenced by teken_state_2().
teken_subr_cursor_position()
static void teken_subr_cursor_position (teken_t * t, unsigned int row, unsigned int col) static
Definition at line 324 of file teken_subr.h.
References __teken::t_cursor, __teken::t_originreg, __teken::t_stateflags, __teken::t_winsize, teken_funcs_cursor(), teken_pos_t::tp_col, teken_pos_t::tp_row, teken_span_t::ts_begin, teken_span_t::ts_end, and TS_WRAPPED.
Referenced by teken_state_2().
teken_subr_cursor_position_report()
static void teken_subr_cursor_position_report (teken_t * t, unsigned int cmd) static
Definition at line 340 of file teken_subr.h.
References teken_funcs_respond(), and teken_subr_do_cpr().
Referenced by teken_state_2().
teken_subr_cursor_previous_line()
static void teken_subr_cursor_previous_line (teken_t * t, unsigned int ncols) static
Definition at line 353 of file teken_subr.h.
References __teken::t_cursor, teken_subr_cursor_up(), and teken_pos_t::tp_col.
Referenced by teken_state_2().
teken_subr_cursor_up()
static void teken_subr_cursor_up (teken_t * t, unsigned int nrows) static
Definition at line 361 of file teken_subr.h.
References __teken::t_cursor, __teken::t_scrollreg, __teken::t_stateflags, teken_funcs_cursor(), teken_pos_t::tp_row, teken_span_t::ts_begin, and TS_WRAPPED.
Referenced by teken_state_2(), and teken_subr_cursor_previous_line().
teken_subr_delete_character()
static void teken_subr_delete_character (teken_t * t, unsigned int ncols) static
Definition at line 373 of file teken_subr.h.
References BLANK, __teken::t_curattr, __teken::t_cursor, __teken::t_winsize, teken_funcs_copy(), teken_funcs_fill(), teken_pos_t::tp_col, teken_pos_t::tp_row, teken_rect_t::tr_begin, and teken_rect_t::tr_end.
Referenced by teken_state_2().
teken_subr_delete_line()
static void teken_subr_delete_line (teken_t * t, unsigned int nrows) static
Definition at line 396 of file teken_subr.h.
References BLANK, __teken::t_curattr, __teken::t_cursor, __teken::t_scrollreg, __teken::t_winsize, teken_funcs_copy(), teken_funcs_fill(), teken_pos_t::tp_col, teken_pos_t::tp_row, teken_rect_t::tr_begin, teken_rect_t::tr_end, and teken_span_t::ts_end.
Referenced by teken_state_2().
teken_subr_device_control_string()
static void teken_subr_device_control_string (teken_t *t __unused) static
Definition at line 423 of file teken_subr.h.
References teken_printf.
Referenced by teken_state_1().
teken_subr_device_status_report()
static void teken_subr_device_status_report (teken_t * t, unsigned int cmd) static
Definition at line 430 of file teken_subr.h.
References teken_funcs_respond(), and teken_subr_do_cpr().
Referenced by teken_state_5().
teken_subr_do_cpr()
static ssize_t teken_subr_do_cpr (teken_t * t, unsigned int cmd, char response[16]) static
Definition at line 150 of file teken_subr.h.
References snprintf(), strcpy(), __teken::t_cursor, __teken::t_originreg, teken_printf, teken_pos_t::tp_col, teken_pos_t::tp_row, and teken_span_t::ts_begin.
Referenced by teken_subr_cursor_position_report(), and teken_subr_device_status_report().
teken_subr_do_putchar()
static void teken_subr_do_putchar (teken_t * t, const teken_pos_t * tp, teken_char_t c, int width) static
Definition at line 764 of file teken_subr.h.
References __teken::t_curattr, __teken::t_stateflags, __teken::t_winsize, teken_funcs_copy(), teken_funcs_putchar(), teken_pos_t::tp_col, teken_pos_t::tp_row, teken_rect_t::tr_begin, teken_rect_t::tr_end, and TS_INSERT.
Referenced by teken_subr_regular_character().
teken_subr_do_reset()
static void teken_subr_do_reset (teken_t * t) static
Definition at line 925 of file teken_subr.h.
References __teken::t_curattr, __teken::t_cursor, __teken::t_defattr, __teken::t_stateflags, teken_scs_set, teken_scs_switch, teken_scs_us_ascii(), teken_subr_save_cursor(), teken_tab_default(), teken_pos_t::tp_col, teken_pos_t::tp_row, and TS_AUTOWRAP.
Referenced by teken_init(), and teken_subr_reset_to_initial_state().
teken_subr_do_scroll()
static void teken_subr_do_scroll (teken_t * t, int amount) static
Definition at line 89 of file teken_subr.h.
References BLANK, __teken::t_curattr, __teken::t_cursor, __teken::t_scrollreg, __teken::t_winsize, teken_assert, teken_funcs_copy(), teken_funcs_fill(), teken_pos_t::tp_col, teken_pos_t::tp_row, teken_rect_t::tr_begin, teken_rect_t::tr_end, teken_span_t::ts_begin, and teken_span_t::ts_end.
Referenced by teken_subr_index(), teken_subr_newline(), teken_subr_pan_down(), teken_subr_pan_up(), teken_subr_regular_character(), and teken_subr_reverse_index().
teken_subr_double_height_double_width_line_bottom()
static void teken_subr_double_height_double_width_line_bottom (teken_t *t __unused) static
Definition at line 450 of file teken_subr.h.
References teken_printf.
Referenced by teken_state_4().
teken_subr_double_height_double_width_line_top()
static void teken_subr_double_height_double_width_line_top (teken_t *t __unused) static
Definition at line 443 of file teken_subr.h.
References teken_printf.
Referenced by teken_state_4().
teken_subr_erase_character()
static void teken_subr_erase_character (teken_t * t, unsigned int ncols) static
Definition at line 457 of file teken_subr.h.
References BLANK, __teken::t_curattr, __teken::t_cursor, __teken::t_winsize, teken_funcs_fill(), teken_pos_t::tp_col, teken_pos_t::tp_row, teken_rect_t::tr_begin, and teken_rect_t::tr_end.
Referenced by teken_state_2().
teken_subr_erase_display()
static void teken_subr_erase_display (teken_t * t, unsigned int mode) static
Definition at line 473 of file teken_subr.h.
References BLANK, __teken::t_curattr, __teken::t_cursor, __teken::t_winsize, teken_funcs_fill(), teken_subr_erase_line(), teken_pos_t::tp_col, teken_pos_t::tp_row, teken_rect_t::tr_begin, and teken_rect_t::tr_end.
Referenced by teken_state_2(), and teken_subr_reset_to_initial_state().
teken_subr_erase_line()
static void teken_subr_erase_line (teken_t * t, unsigned int mode) static
Definition at line 509 of file teken_subr.h.
References BLANK, __teken::t_curattr, __teken::t_cursor, __teken::t_winsize, teken_funcs_fill(), teken_pos_t::tp_col, teken_pos_t::tp_row, teken_rect_t::tr_begin, and teken_rect_t::tr_end.
Referenced by teken_state_2(), and teken_subr_erase_display().
teken_subr_g0_scs_special_graphics()
static void teken_subr_g0_scs_special_graphics (teken_t *t __unused) static
Definition at line 535 of file teken_subr.h.
References teken_scs_set, and teken_scs_special_graphics().
Referenced by teken_state_6().
teken_subr_g0_scs_uk_national()
static void teken_subr_g0_scs_uk_national (teken_t *t __unused) static
Definition at line 542 of file teken_subr.h.
References teken_scs_set, and teken_scs_uk_national().
Referenced by teken_state_6().
teken_subr_g0_scs_us_ascii()
static void teken_subr_g0_scs_us_ascii (teken_t *t __unused) static
Definition at line 549 of file teken_subr.h.
References teken_scs_set, and teken_scs_us_ascii().
Referenced by teken_state_6().
teken_subr_g1_scs_special_graphics()
static void teken_subr_g1_scs_special_graphics (teken_t *t __unused) static
Definition at line 556 of file teken_subr.h.
References teken_scs_set, and teken_scs_special_graphics().
Referenced by teken_state_7().
teken_subr_g1_scs_uk_national()
static void teken_subr_g1_scs_uk_national (teken_t *t __unused) static
Definition at line 563 of file teken_subr.h.
References teken_scs_set, and teken_scs_uk_national().
Referenced by teken_state_7().
teken_subr_g1_scs_us_ascii()
static void teken_subr_g1_scs_us_ascii (teken_t *t __unused) static
Definition at line 570 of file teken_subr.h.
References teken_scs_set, and teken_scs_us_ascii().
Referenced by teken_state_7().
teken_subr_horizontal_position_absolute()
static void teken_subr_horizontal_position_absolute (teken_t * t, unsigned int col) static
Definition at line 577 of file teken_subr.h.
References __teken::t_cursor, __teken::t_stateflags, __teken::t_winsize, teken_funcs_cursor(), teken_pos_t::tp_col, and TS_WRAPPED.
Referenced by teken_state_2().
teken_subr_horizontal_tab()
static void teken_subr_horizontal_tab (teken_t * t) static
Definition at line 589 of file teken_subr.h.
References BLANK, __teken::t_curattr, __teken::t_cursor, teken_funcs_fill(), teken_subr_cursor_forward_tabulation(), teken_pos_t::tp_col, teken_pos_t::tp_row, teken_rect_t::tr_begin, and teken_rect_t::tr_end.
Referenced by teken_input_char().
teken_subr_horizontal_tab_set()
static void teken_subr_horizontal_tab_set (teken_t * t) static
Definition at line 609 of file teken_subr.h.
References __teken::t_cursor, teken_tab_set(), and teken_pos_t::tp_col.
Referenced by teken_state_1().
teken_subr_index()
static void teken_subr_index (teken_t * t) static
Definition at line 616 of file teken_subr.h.
References __teken::t_cursor, __teken::t_scrollreg, __teken::t_stateflags, teken_funcs_cursor(), teken_subr_do_scroll(), teken_pos_t::tp_row, teken_span_t::ts_end, and TS_WRAPPED.
Referenced by teken_state_1().
teken_subr_insert_character()
static void teken_subr_insert_character (teken_t * t, unsigned int ncols) static
Definition at line 629 of file teken_subr.h.
References BLANK, __teken::t_curattr, __teken::t_cursor, __teken::t_winsize, teken_funcs_copy(), teken_funcs_fill(), teken_pos_t::tp_col, teken_pos_t::tp_row, teken_rect_t::tr_begin, and teken_rect_t::tr_end.
Referenced by teken_state_2().
teken_subr_insert_line()
static void teken_subr_insert_line (teken_t * t, unsigned int nrows) static
Definition at line 655 of file teken_subr.h.
References BLANK, __teken::t_curattr, __teken::t_cursor, __teken::t_scrollreg, __teken::t_winsize, teken_funcs_copy(), teken_funcs_fill(), teken_pos_t::tp_col, teken_pos_t::tp_row, teken_rect_t::tr_begin, teken_rect_t::tr_end, and teken_span_t::ts_end.
Referenced by teken_state_2().
teken_subr_keypad_application_mode()
static void teken_subr_keypad_application_mode (teken_t * t) static
Definition at line 682 of file teken_subr.h.
References teken_funcs_param(), and TP_KEYPADAPP.
Referenced by teken_state_1().
teken_subr_keypad_numeric_mode()
static void teken_subr_keypad_numeric_mode (teken_t * t) static
Definition at line 689 of file teken_subr.h.
References teken_funcs_param(), and TP_KEYPADAPP.
Referenced by teken_state_1().
teken_subr_newline()
static void teken_subr_newline (teken_t * t) static
Definition at line 696 of file teken_subr.h.
References __teken::t_cursor, __teken::t_scrollreg, __teken::t_stateflags, teken_funcs_cursor(), teken_subr_do_scroll(), teken_pos_t::tp_row, teken_span_t::ts_end, and TS_WRAPPED.
Referenced by teken_input_char(), teken_subr_newpage(), and teken_subr_next_line().
teken_subr_newpage()
static void teken_subr_newpage (teken_t * t) static
Definition at line 711 of file teken_subr.h.
References BLANK, __teken::t_curattr, __teken::t_cursor, __teken::t_winsize, teken_funcs_cursor(), teken_funcs_fill(), teken_subr_newline(), teken_pos_t::tp_col, teken_pos_t::tp_row, teken_rect_t::tr_begin, and teken_rect_t::tr_end.
Referenced by teken_input_char().
teken_subr_next_line()
static void teken_subr_next_line (teken_t * t) static
Definition at line 729 of file teken_subr.h.
References __teken::t_cursor, teken_subr_newline(), and teken_pos_t::tp_col.
Referenced by teken_state_1().
teken_subr_pan_down()
static void teken_subr_pan_down (teken_t * t, unsigned int nrows) static
Definition at line 737 of file teken_subr.h.
References teken_subr_do_scroll().
Referenced by teken_state_2().
teken_subr_pan_up()
static void teken_subr_pan_up (teken_t * t, unsigned int nrows) static
Definition at line 744 of file teken_subr.h.
References teken_subr_do_scroll().
Referenced by teken_state_2().
teken_subr_primary_device_attributes()
static void teken_subr_primary_device_attributes (teken_t * t, unsigned int request) static
Definition at line 751 of file teken_subr.h.
References teken_funcs_respond(), and teken_printf.
Referenced by teken_state_2().
teken_subr_regular_character()
static void teken_subr_regular_character (teken_t * t, teken_char_t c) static
Definition at line 786 of file teken_subr.h.
References __teken::t_cursor, __teken::t_scrollreg, __teken::t_stateflags, __teken::t_winsize, teken_funcs_cursor(), teken_scs_process, teken_subr_do_putchar(), teken_subr_do_scroll(), teken_wcwidth, teken_pos_t::tp_col, teken_pos_t::tp_row, TS_AUTOWRAP, teken_span_t::ts_end, and TS_WRAPPED.
Referenced by teken_state_init().
teken_subr_reset_dec_mode()
static void teken_subr_reset_dec_mode (teken_t * t, unsigned int cmd) static
Definition at line 863 of file teken_subr.h.
References __teken::t_cursor, __teken::t_originreg, __teken::t_stateflags, __teken::t_winsize, teken_funcs_cursor(), teken_funcs_param(), teken_printf, teken_subr_reset_to_initial_state(), TP_132COLS, TP_AUTOREPEAT, teken_pos_t::tp_col, TP_CURSORKEYS, teken_pos_t::tp_row, TP_SHOWCURSOR, TS_AUTOWRAP, teken_span_t::ts_begin, teken_span_t::ts_end, TS_ORIGIN, and TS_WRAPPED.
Referenced by teken_state_5().
teken_subr_reset_mode()
static void teken_subr_reset_mode (teken_t * t, unsigned int cmd) static
Definition at line 912 of file teken_subr.h.
References __teken::t_stateflags, teken_printf, and TS_INSERT.
Referenced by teken_state_2().
teken_subr_reset_to_initial_state()
static void teken_subr_reset_to_initial_state (teken_t * t) static
Definition at line 941 of file teken_subr.h.
References teken_funcs_cursor(), teken_funcs_param(), teken_subr_do_reset(), teken_subr_erase_display(), and TP_SHOWCURSOR.
Referenced by teken_state_1(), teken_subr_reset_dec_mode(), and teken_subr_set_dec_mode().
teken_subr_restore_cursor()
static void teken_subr_restore_cursor (teken_t * t) static
Definition at line 951 of file teken_subr.h.
References __teken::t_curattr, __teken::t_cursor, __teken::t_saved_curattr, __teken::t_saved_cursor, __teken::t_stateflags, teken_funcs_cursor(), teken_scs_restore, and TS_WRAPPED.
Referenced by teken_state_1(), and teken_state_2().
teken_subr_reverse_index()
static void teken_subr_reverse_index (teken_t * t) static
Definition at line 962 of file teken_subr.h.
References __teken::t_cursor, __teken::t_scrollreg, __teken::t_stateflags, teken_funcs_cursor(), teken_subr_do_scroll(), teken_pos_t::tp_row, teken_span_t::ts_begin, and TS_WRAPPED.
Referenced by teken_state_1().
teken_subr_save_cursor()
static void teken_subr_save_cursor (teken_t * t) static
Definition at line 975 of file teken_subr.h.
References __teken::t_curattr, __teken::t_cursor, __teken::t_saved_curattr, __teken::t_saved_cursor, and teken_scs_save.
Referenced by teken_state_1(), teken_state_2(), and teken_subr_do_reset().
teken_subr_secondary_device_attributes()
static void teken_subr_secondary_device_attributes (teken_t * t, unsigned int request) static
Definition at line 984 of file teken_subr.h.
References teken_funcs_respond(), and teken_printf.
Referenced by teken_state_3().
teken_subr_set_dec_mode()
static void teken_subr_set_dec_mode (teken_t * t, unsigned int cmd) static
Definition at line 996 of file teken_subr.h.
References __teken::t_cursor, __teken::t_originreg, __teken::t_scrollreg, __teken::t_stateflags, teken_funcs_cursor(), teken_funcs_param(), teken_printf, teken_subr_reset_to_initial_state(), TP_132COLS, TP_AUTOREPEAT, teken_pos_t::tp_col, TP_CURSORKEYS, teken_pos_t::tp_row, TP_SHOWCURSOR, TS_AUTOWRAP, teken_span_t::ts_begin, TS_ORIGIN, and TS_WRAPPED.
Referenced by teken_state_5().
teken_subr_set_graphic_rendition()
static void teken_subr_set_graphic_rendition (teken_t * t, unsigned int ncmds, unsigned int cmds[]) static
Definition at line 1059 of file teken_subr.h.
References __teken::t_curattr, __teken::t_defattr, teken_attr_t::ta_bgcolor, teken_attr_t::ta_fgcolor, teken_attr_t::ta_format, teken_printf, TF_BLINK, TF_BOLD, TF_REVERSE, and TF_UNDERLINE.
Referenced by teken_state_2().
teken_subr_set_mode()
static void teken_subr_set_mode (teken_t * t, unsigned int cmd) static
Definition at line 1045 of file teken_subr.h.
References __teken::t_stateflags, teken_printf, and TS_INSERT.
Referenced by teken_state_2().
teken_subr_set_top_and_bottom_margins()
static void teken_subr_set_top_and_bottom_margins (teken_t * t, unsigned int top, unsigned int bottom) static
Definition at line 1134 of file teken_subr.h.
References __teken::t_cursor, __teken::t_originreg, __teken::t_scrollreg, __teken::t_stateflags, __teken::t_winsize, teken_funcs_cursor(), teken_pos_t::tp_col, teken_pos_t::tp_row, teken_span_t::ts_begin, teken_span_t::ts_end, TS_ORIGIN, and TS_WRAPPED.
Referenced by teken_state_2().
teken_subr_single_height_double_width_line()
static void teken_subr_single_height_double_width_line (teken_t *t __unused) static
Definition at line 1164 of file teken_subr.h.
References teken_printf.
Referenced by teken_state_4().
teken_subr_single_height_single_width_line()
static void teken_subr_single_height_single_width_line (teken_t *t __unused) static
Definition at line 1171 of file teken_subr.h.
References teken_printf.
Referenced by teken_state_4().
teken_subr_string_terminator()
static void teken_subr_string_terminator (teken_t *t __unused) static
Definition at line 1178 of file teken_subr.h.
References teken_printf.
Referenced by teken_state_1().
teken_subr_tab_clear()
static void teken_subr_tab_clear (teken_t * t, unsigned int cmd) static
Definition at line 1185 of file teken_subr.h.
References memset(), __teken::t_cursor, T_NUMCOL, __teken::t_tabstops, teken_tab_clear(), and teken_pos_t::tp_col.
Referenced by teken_state_2().
teken_subr_vertical_position_absolute()
static void teken_subr_vertical_position_absolute (teken_t * t, unsigned int row) static
Definition at line 1199 of file teken_subr.h.
References __teken::t_cursor, __teken::t_originreg, __teken::t_stateflags, teken_funcs_cursor(), teken_pos_t::tp_row, teken_span_t::ts_begin, teken_span_t::ts_end, and TS_WRAPPED.
Referenced by teken_state_2().
teken_tab_clear()
static void teken_tab_clear (teken_t * t, unsigned int col) inline static
Definition at line 50 of file teken_subr.h.
References T_NUMCOL, and __teken::t_tabstops.
Referenced by teken_subr_tab_clear().
teken_tab_default()
static void teken_tab_default (teken_t * t) static
Definition at line 78 of file teken_subr.h.
References memset(), T_NUMCOL, __teken::t_tabstops, and teken_tab_set().
Referenced by teken_subr_do_reset().
teken_tab_isset()
static int teken_tab_isset (teken_t * t, unsigned int col) inline static
Definition at line 36 of file teken_subr.h.
References T_NUMCOL, and __teken::t_tabstops.
Referenced by teken_subr_cursor_backward_tabulation(), and teken_subr_cursor_forward_tabulation().
teken_tab_set()
static void teken_tab_set (teken_t * t, unsigned int col) inline static
Definition at line 64 of file teken_subr.h.
References T_NUMCOL, and __teken::t_tabstops.
Referenced by teken_subr_horizontal_tab_set(), and teken_tab_default().