FreeNOS: lib/libteken/teken_scs.h File Reference
teken_scs.h File Reference
Functions
static void teken_scs_set (teken_t *t, unsigned int g, teken_scs_t *ts)
static void teken_scs_switch (teken_t *t, unsigned int g)
static void teken_scs_restore (teken_t *t)
static void teken_scs_save (teken_t *t)
static teken_char_t teken_scs_process (teken_t *t, teken_char_t c)
static teken_char_t teken_scs_special_graphics (teken_char_t c)
static teken_char_t teken_scs_uk_national (teken_char_t c)
static teken_char_t teken_scs_us_ascii (teken_char_t c)
Variables
static const uint16_t teken_boxdrawing [31]
Function Documentation
teken_scs_process()
static teken_char_t teken_scs_process (teken_t * t, teken_char_t c) static
Definition at line 58 of file teken_scs.h.
teken_scs_restore()
static void teken_scs_restore (teken_t * t) static
Definition at line 44 of file teken_scs.h.
teken_scs_save()
static void teken_scs_save (teken_t * t) static
Definition at line 51 of file teken_scs.h.
teken_scs_set()
static void teken_scs_set (teken_t * t, unsigned int g, teken_scs_t * ts) static
Definition at line 30 of file teken_scs.h.
teken_scs_special_graphics()
static teken_char_t teken_scs_special_graphics (teken_char_t c) static
Definition at line 73 of file teken_scs.h.
References teken_boxdrawing.
Referenced by teken_subr_g0_scs_special_graphics(), and teken_subr_g1_scs_special_graphics().
teken_scs_switch()
static void teken_scs_switch (teken_t * t, unsigned int g) static
Definition at line 37 of file teken_scs.h.
teken_scs_uk_national()
static teken_char_t teken_scs_uk_national (teken_char_t c) static
Definition at line 83 of file teken_scs.h.
Referenced by teken_subr_g0_scs_uk_national(), and teken_subr_g1_scs_uk_national().
teken_scs_us_ascii()
static teken_char_t teken_scs_us_ascii (teken_char_t c) static
Definition at line 93 of file teken_scs.h.
Referenced by teken_subr_do_reset(), teken_subr_g0_scs_us_ascii(), and teken_subr_g1_scs_us_ascii().
Variable Documentation
teken_boxdrawing
const uint16_t teken_boxdrawing[31] static
Initial value:
= {
    0x25c6, 0x2592, 0x2409, 0x240c, 0x240d, 0x240a, 0x00b0, 0x00b1,
    0x2424, 0x240b, 0x2518, 0x2510, 0x250c, 0x2514, 0x253c, 0x23ba,
    0x23bb, 0x2500, 0x23bc, 0x23bd, 0x251c, 0x2524, 0x2534, 0x252c,
    0x2502, 0x2264, 0x2265, 0x03c0, 0x2260, 0x00a3, 0x00b7
}
Definition at line 65 of file teken_scs.h.
Referenced by teken_scs_special_graphics().